import type {Topic} from '../recovery.ts';

/** College subjects for the Courses pages: what a first- and second-year student in each
 *  field actually takes, as opposed to the high-school foundations the CET reviewer covers.
 *  Topics are written in Khanpanion's own words from common Philippine first-year course
 *  outlines. Every Khan Academy course, unit and video below was opened in the in-app
 *  browser on its check date: units by their rendered page title, videos by their rendered
 *  title and youtube-nocookie embed id. Nothing is guessed from a URL pattern; the log is
 *  in docs/THIRD_PARTY_MATERIALS.md under "College subjects". Watching or ticking any of
 *  them is activity, never learning evidence. */
export const COLLEGE_CHECKED='2026-10-06';
const KHAN='https://www.khanacademy.org';

export type CollegeUnit={id:string;course:string;unit:string;path:string};
export type CollegeVideo={id:string;title:string;url:string};
export type SubjectKind='math'|'statistics'|'programming'|'computing'|'science'|'social';
export type SubjectLevel='First year'|'Second year'|'Elective';
export type CollegeSubject={id:string;title:string;kind:SubjectKind;level:SubjectLevel;summary:string;topics:string[];units:CollegeUnitId[];videos:CollegeVideo[];buildsOn:string[];engine?:Topic;
 /** Topics the subject covers that no Khan Academy course teaches yet; shown plainly. */
 gap?:string};

export const KIND_LABEL:Record<SubjectKind,string>={math:'Mathematics',statistics:'Statistics',programming:'Programming',computing:'Computing',science:'Science',social:'Social science'};

const u=(id:string,course:string,unit:string,path:string):CollegeUnit=>({id,course,unit,path});
/** A whole course rather than one unit of it. */
const COURSE='Course';
export const COLLEGE_UNITS={
 // Calculus 1 and 2
 c1_limits:u('c1_limits','Calculus 1','Limits and continuity','/math/calculus-1/cs1-limits-and-continuity'),
 c1_rules:u('c1_rules','Calculus 1','Derivatives: definition and basic rules','/math/calculus-1/cs1-derivatives-definition-and-basic-rules'),
 c1_chain:u('c1_chain','Calculus 1','Derivatives: chain rule and other advanced topics','/math/calculus-1/cs1-derivatives-chain-rule-and-other-advanced-topics'),
 c1_apply:u('c1_apply','Calculus 1','Applications of derivatives','/math/calculus-1/cs1-applications-of-derivatives'),
 c1_analyze:u('c1_analyze','Calculus 1','Analyzing functions','/math/calculus-1/cs1-analyzing-functions'),
 c1_integrals:u('c1_integrals','Calculus 1','Integrals','/math/calculus-1/cs1-integrals'),
 c2_techniques:u('c2_techniques','Calculus 2','Integration techniques','/math/calculus-2/cs2-integration-techniques'),
 c2_diffeq:u('c2_diffeq','Calculus 2','Differential equations','/math/calculus-2/cs2-differential-equations'),
 c2_apply:u('c2_apply','Calculus 2','Applications of integrals','/math/calculus-2/cs2-applications-of-integrals'),
 c2_polar:u('c2_polar','Calculus 2','Parametric equations, polar coordinates, and vector-valued functions','/math/calculus-2/cs2-parametric-equations-polar-coordinates-and-vector-valued-functions'),
 c2_series:u('c2_series','Calculus 2','Series','/math/calculus-2/cs2-series'),
 // Multivariable calculus, differential equations, linear algebra
 mv_functions:u('mv_functions','Multivariable calculus','Thinking about multivariable functions','/math/multivariable-calculus/thinking-about-multivariable-function'),
 mv_derivatives:u('mv_derivatives','Multivariable calculus','Derivatives of multivariable functions','/math/multivariable-calculus/multivariable-derivatives'),
 mv_apply:u('mv_apply','Multivariable calculus','Applications of multivariable derivatives','/math/multivariable-calculus/applications-of-multivariable-derivatives'),
 mv_integrals:u('mv_integrals','Multivariable calculus','Integrating multivariable functions','/math/multivariable-calculus/integrating-multivariable-functions'),
 mv_theorems:u('mv_theorems','Multivariable calculus','Green’s, Stokes’, and the divergence theorems','/math/multivariable-calculus/greens-theorem-and-stokes-theorem'),
 de_first:u('de_first','Differential equations','First order differential equations','/math/differential-equations/first-order-differential-equations'),
 de_second:u('de_second','Differential equations','Second order linear equations','/math/differential-equations/second-order-differential-equations'),
 de_laplace:u('de_laplace','Differential equations','Laplace transform','/math/differential-equations/laplace-transform'),
 la_vectors:u('la_vectors','Linear algebra','Vectors and spaces','/math/linear-algebra/vectors-and-spaces'),
 la_transforms:u('la_transforms','Linear algebra','Matrix transformations','/math/linear-algebra/matrix-transformations'),
 la_bases:u('la_bases','Linear algebra','Alternate coordinate systems (bases)','/math/linear-algebra/alternate-bases'),
 // College algebra and precalculus
 ca_functions:u('ca_functions','College Algebra','Functions','/math/college-algebra/xa5dd2923c88e7aa8:functions'),
 ca_logs:u('ca_logs','College Algebra','Logarithms','/math/college-algebra/xa5dd2923c88e7aa8:logarithms'),
 pc_trig:u('pc_trig','Precalculus','Trigonometry','/math/precalculus/x9e81a4f98389efdf:trig'),
 pc_complex:u('pc_complex','Precalculus','Complex numbers','/math/precalculus/x9e81a4f98389efdf:complex'),
 pc_conics:u('pc_conics','Precalculus','Conic sections','/math/precalculus/x9e81a4f98389efdf:conics'),
 pc_vectors:u('pc_vectors','Precalculus','Vectors','/math/precalculus/x9e81a4f98389efdf:vectors'),
 pc_matrices:u('pc_matrices','Precalculus','Matrices','/math/precalculus/x9e81a4f98389efdf:matrices'),
 pc_probcomb:u('pc_probcomb','Precalculus','Probability and combinatorics','/math/precalculus/x9e81a4f98389efdf:prob-comb'),
 pc_series:u('pc_series','Precalculus','Series','/math/precalculus/x9e81a4f98389efdf:series'),
 // Statistics and probability
 sp_categorical:u('sp_categorical','Statistics and probability','Analyzing categorical data','/math/statistics-probability/analyzing-categorical-data'),
 sp_displaying:u('sp_displaying','Statistics and probability','Displaying and comparing quantitative data','/math/statistics-probability/displaying-describing-data'),
 sp_summarizing:u('sp_summarizing','Statistics and probability','Summarizing quantitative data','/math/statistics-probability/summarizing-quantitative-data'),
 sp_modeling:u('sp_modeling','Statistics and probability','Modeling data distributions','/math/statistics-probability/modeling-distributions-of-data'),
 sp_bivariate:u('sp_bivariate','Statistics and probability','Exploring bivariate numerical data','/math/statistics-probability/describing-relationships-quantitative-data'),
 sp_design:u('sp_design','Statistics and probability','Study design','/math/statistics-probability/designing-studies'),
 sp_probability:u('sp_probability','Statistics and probability','Probability','/math/statistics-probability/probability-library'),
 sp_counting:u('sp_counting','Statistics and probability','Counting, permutations, and combinations','/math/statistics-probability/counting-permutations-and-combinations'),
 sp_randomvars:u('sp_randomvars','Statistics and probability','Random variables','/math/statistics-probability/random-variables-stats-library'),
 sp_sampling:u('sp_sampling','Statistics and probability','Sampling distributions','/math/statistics-probability/sampling-distributions-library'),
 sp_ci:u('sp_ci','Statistics and probability','Confidence intervals','/math/statistics-probability/confidence-intervals-one-sample'),
 sp_tests:u('sp_tests','Statistics and probability','Significance tests (hypothesis testing)','/math/statistics-probability/significance-tests-one-sample'),
 sp_twosample:u('sp_twosample','Statistics and probability','Two-sample inference for the difference between groups','/math/statistics-probability/significance-tests-confidence-intervals-two-samples'),
 sp_chisq:u('sp_chisq','Statistics and probability','Inference for categorical data (chi-square tests)','/math/statistics-probability/inference-categorical-data-chi-square-tests'),
 sp_regression:u('sp_regression','Statistics and probability','Advanced regression (inference and transforming)','/math/statistics-probability/advanced-regression-inference-transforming'),
 sp_anova:u('sp_anova','Statistics and probability','Analysis of variance (ANOVA)','/math/statistics-probability/analysis-of-variance-anova-library'),
 aps_collect:u('aps_collect','AP®︎/College Statistics','Exploring one-variable data and collecting data','/math/ap-statistics/xfb5d8e68:exploring-one-variable-data-and-collecting-data'),
 aps_prob:u('aps_prob','AP®︎/College Statistics','Probability, random variables, and probability distributions','/math/ap-statistics/xfb5d8e68:probability-random-variables-and-probability-distributions'),
 aps_regression:u('aps_regression','AP®︎/College Statistics','Regression analysis','/math/ap-statistics/xfb5d8e68:regression-analysis'),
 // Programming
 py_variables:u('py_variables','Intro to computer science - Python','Computational thinking with variables','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:computational-thinking-with-variables'),
 py_conditionals:u('py_conditionals','Intro to computer science - Python','Designing algorithms with conditionals','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:designing-algorithms-with-conditionals'),
 py_loops:u('py_loops','Intro to computer science - Python','Simulating phenomena with loops','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:simulating-phenomena-with-loops'),
 py_functions:u('py_functions','Intro to computer science - Python','Playing games with functions','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:playing-games-with-functions'),
 py_lists:u('py_lists','Intro to computer science - Python','Automating tasks with lists','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:automating-tasks-with-lists'),
 py_dicts:u('py_dicts','Intro to computer science - Python','Analyzing data with dictionaries','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:analyzing-data-with-dictionaries'),
 py_classes:u('py_classes','Intro to computer science - Python','Building software with classes','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:building-software-with-classes'),
 js_intro:u('js_intro','Computer programming','Intro to JS: Drawing & Animation','/computing/computer-programming/programming'),
 js_games:u('js_games','Computer programming','Advanced JS: Games & Visualizations','/computing/computer-programming/programming-games-visualizations'),
 js_sims:u('js_sims','Computer programming','Advanced JS: Natural Simulations','/computing/computer-programming/programming-natural-simulations'),
 web_htmlcss:u('web_htmlcss','Computer programming','Intro to HTML/CSS: Making webpages','/computing/computer-programming/html-css'),
 web_htmljs:u('web_htmljs','Computer programming','HTML/JS: Making webpages interactive','/computing/computer-programming/html-css-js'),
 web_jquery:u('web_jquery','Computer programming','HTML/JS: Making webpages interactive with jQuery','/computing/computer-programming/html-js-jquery'),
 sql:u('sql','Computer programming','Intro to SQL: Querying and managing data','/computing/computer-programming/sql'),
 cs_algorithms:u('cs_algorithms','Computer science theory','Algorithms','/computing/computer-science/algorithms'),
 cs_crypto:u('cs_crypto','Computer science theory','Cryptography','/computing/computer-science/cryptography'),
 cs_info:u('cs_info','Computer science theory','Information theory','/computing/computer-science/informationtheory'),
 ci_digital:u('ci_digital','Computers and the Internet','Digital information','/computing/computers-and-internet/xcae6f4a7ff015e7d:digital-information'),
 ci_computers:u('ci_computers','Computers and the Internet','Computers','/computing/computers-and-internet/xcae6f4a7ff015e7d:computers'),
 ci_internet:u('ci_internet','Computers and the Internet','The Internet','/computing/computers-and-internet/xcae6f4a7ff015e7d:the-internet'),
 ci_security:u('ci_security','Computers and the Internet','Online data security','/computing/computers-and-internet/xcae6f4a7ff015e7d:online-data-security'),
 csp_data:u('csp_data','AP®︎/College Computer Science Principles','Data analysis','/computing/ap-computer-science-principles/data-analysis-101'),
 csp_simulations:u('csp_simulations','AP®︎/College Computer Science Principles','Simulations','/computing/ap-computer-science-principles/x2d2f703b37b450a3:simulations'),
 pixar_sim:u('pixar_sim','Pixar in a Box','Simulation','/computing/pixar/simulation'),
 // Chemistry
 apc_atomic:u('apc_atomic','AP®︎/College Chemistry','Atomic structure and properties','/science/ap-chemistry-beta/x2eef969c74e0d802:atomic-structure-and-properties'),
 apc_bonding:u('apc_bonding','AP®︎/College Chemistry','Molecular and ionic compound structure and properties','/science/ap-chemistry-beta/x2eef969c74e0d802:molecular-and-ionic-compound-structure-and-properties'),
 apc_imf:u('apc_imf','AP®︎/College Chemistry','Intermolecular forces and properties','/science/ap-chemistry-beta/x2eef969c74e0d802:intermolecular-forces-and-properties'),
 apc_reactions:u('apc_reactions','AP®︎/College Chemistry','Chemical reactions','/science/ap-chemistry-beta/x2eef969c74e0d802:chemical-reactions'),
 apc_kinetics:u('apc_kinetics','AP®︎/College Chemistry','Kinetics','/science/ap-chemistry-beta/x2eef969c74e0d802:kinetics'),
 apc_thermo:u('apc_thermo','AP®︎/College Chemistry','Thermodynamics','/science/ap-chemistry-beta/x2eef969c74e0d802:thermodynamics'),
 apc_equilibrium:u('apc_equilibrium','AP®︎/College Chemistry','Equilibrium','/science/ap-chemistry-beta/x2eef969c74e0d802:equilibrium'),
 apc_acids:u('apc_acids','AP®︎/College Chemistry','Acids and bases','/science/ap-chemistry-beta/x2eef969c74e0d802:acids-and-bases'),
 apc_appthermo:u('apc_appthermo','AP®︎/College Chemistry','Applications of thermodynamics','/science/ap-chemistry-beta/x2eef969c74e0d802:applications-of-thermodynamics'),
 oc_structure:u('oc_structure','Organic chemistry','Structure and bonding','/science/organic-chemistry/gen-chem-review'),
 oc_resonance:u('oc_resonance','Organic chemistry','Resonance and acid-base chemistry','/science/organic-chemistry/organic-structures'),
 oc_alkanes:u('oc_alkanes','Organic chemistry','Alkanes, cycloalkanes, and functional groups','/science/organic-chemistry/bond-line-structures-alkanes-cycloalkanes'),
 oc_stereo:u('oc_stereo','Organic chemistry','Stereochemistry','/science/organic-chemistry/stereochemistry-topic'),
 oc_substitution:u('oc_substitution','Organic chemistry','Substitution and elimination reactions','/science/organic-chemistry/substitution-elimination-reactions'),
 oc_aromatic:u('oc_aromatic','Organic chemistry','Aromatic compounds','/science/organic-chemistry/aromatic-compounds'),
 oc_carbonyl:u('oc_carbonyl','Organic chemistry','Aldehydes and ketones','/science/organic-chemistry/aldehydes-ketones'),
 oc_spectroscopy:u('oc_spectroscopy','Organic chemistry','Spectroscopy','/science/organic-chemistry/spectroscopy-jay'),
 // Biology, health and medicine
 apb_chemlife:u('apb_chemlife','AP®︎/College Biology','Chemistry of life','/science/ap-biology/chemistry-of-life'),
 apb_cells:u('apb_cells','AP®︎/College Biology','Cells','/science/ap-biology/cell-structure-and-function'),
 apb_energetics:u('apb_energetics','AP®︎/College Biology','Cellular energetics','/science/ap-biology/cellular-energetics'),
 apb_signaling:u('apb_signaling','AP®︎/College Biology','Cell communication and cell cycle','/science/ap-biology/cell-communication-and-cell-cycle'),
 apb_heredity:u('apb_heredity','AP®︎/College Biology','Heredity','/science/ap-biology/heredity'),
 apb_expression:u('apb_expression','AP®︎/College Biology','Gene expression and regulation','/science/ap-biology/gene-expression-and-regulation'),
 apb_selection:u('apb_selection','AP®︎/College Biology','Natural selection','/science/ap-biology/natural-selection'),
 apb_ecology:u('apb_ecology','AP®︎/College Biology','Ecology','/science/ap-biology/ecology-ap'),
 bio_macro:u('bio_macro','Biology archive','Macromolecules','/science/biology/macromolecules'),
 bio_enzymes:u('bio_enzymes','Biology archive','Energy and enzymes','/science/biology/energy-and-enzymes'),
 bio_genetics:u('bio_genetics','Biology archive','Classical and molecular genetics','/science/biology/classical-genetics'),
 bio_dogma:u('bio_dogma','Biology archive','Central dogma (DNA to RNA to protein)','/science/biology/gene-expression-central-dogma'),
 bio_biotech:u('bio_biotech','Biology archive','Biotechnology','/science/biology/biotech-dna-technology'),
 bio_bacteria:u('bio_bacteria','Biology archive','Bacteria and archaea','/science/biology/bacteria-archaea'),
 bio_viruses:u('bio_viruses','Biology archive','Viruses','/science/biology/biology-of-viruses'),
 bio_tree:u('bio_tree','Biology archive','Evolution and the tree of life','/science/biology/her'),
 bio_biodiversity:u('bio_biodiversity','Biology archive','Biodiversity and conservation','/science/biology/biodiversity-and-conservation'),
 hm_intro:u('hm_intro','Health and medicine','Introduction to human body systems','/science/health-and-medicine/human-anatomy-and-physiology'),
 hm_circulatory:u('hm_circulatory','Health and medicine','Circulatory system anatomy and physiology','/science/health-and-medicine/circulatory-system'),
 hm_respiratory:u('hm_respiratory','Health and medicine','Respiratory system anatomy and physiology','/science/health-and-medicine/respiratory-system'),
 hm_endocrine:u('hm_endocrine','Health and medicine','Endocrine system physiology and disease','/science/health-and-medicine/advanced-endocrine-system'),
 hm_nervous:u('hm_nervous','Health and medicine','Nervous system physiology and disease','/science/health-and-medicine/nervous-system-and-sensory-infor'),
 hm_brain:u('hm_brain','Health and medicine','Brain function and mental health','/science/health-and-medicine/executive-systems-of-the-brain'),
 hm_gi:u('hm_gi','Health and medicine','Gastrointestinal system physiology and disease','/science/health-and-medicine/gastro-intestinal-system'),
 hm_musculo:u('hm_musculo','Health and medicine','Musculoskeletal system physiology and disease','/science/health-and-medicine/advanced-muscular-system'),
 hm_infectious:u('hm_infectious','Health and medicine','Infectious diseases','/science/health-and-medicine/infectious-diseases'),
 mcat_biomolecules:u('mcat_biomolecules','MCAT','Foundation 1: Biomolecules','/test-prep/mcat/biomolecules'),
 mcat_organs:u('mcat_organs','MCAT','Foundation 3: Organ systems','/test-prep/mcat/organ-systems'),
 mcat_physical:u('mcat_physical','MCAT','Foundation 4: Physical processes','/test-prep/mcat/physical-processes'),
 mcat_environment:u('mcat_environment','MCAT','Foundation 6: Processing the environment','/test-prep/mcat/processing-the-environment'),
 mcat_behavior:u('mcat_behavior','MCAT','Foundation 7: Behavior','/test-prep/mcat/behavior'),
 mcat_individuals:u('mcat_individuals','MCAT','Foundation 8: Individuals and society','/test-prep/mcat/individuals-and-society'),
 mcat_society:u('mcat_society','MCAT','Foundation 9: Society and culture','/test-prep/mcat/society-and-culture'),
 mcat_inequality:u('mcat_inequality','MCAT','Foundation 10: Social inequality','/test-prep/mcat/social-inequality'),
 // Physics and engineering
 ap1_kinematics:u('ap1_kinematics','AP®︎/College Physics 1','Kinematics','/science/ap-college-physics-1/xf557a762645cccc5:kinematics'),
 ap1_forces:u('ap1_forces','AP®︎/College Physics 1','Force and translational dynamics','/science/ap-college-physics-1/xf557a762645cccc5:force-and-translational-dynamics'),
 ap1_energy:u('ap1_energy','AP®︎/College Physics 1','Work, energy, and power','/science/ap-college-physics-1/xf557a762645cccc5:work-energy-and-power'),
 ap1_momentum:u('ap1_momentum','AP®︎/College Physics 1','Linear momentum','/science/ap-college-physics-1/xf557a762645cccc5:linear-momentum'),
 ap1_torque:u('ap1_torque','AP®︎/College Physics 1','Torque and rotational dynamics','/science/ap-college-physics-1/xf557a762645cccc5:torque-and-rotational-dynamics'),
 ap1_oscillations:u('ap1_oscillations','AP®︎/College Physics 1','Oscillations','/science/ap-college-physics-1/xf557a762645cccc5:oscillations'),
 ap1_fluids:u('ap1_fluids','AP®︎/College Physics 1','Fluids','/science/ap-college-physics-1/xf557a762645cccc5:fluids'),
 apcm:u('apcm','AP®︎/College Physics C: Mechanics',COURSE,'/science/ap-physics-c-mechanics'),
 ap2_thermo:u('ap2_thermo','AP®︎/College Physics 2','Thermodynamics','/science/ap-physics-2/x0e2f5a2c:thermodynamics'),
 ap2_electric:u('ap2_electric','AP®︎/College Physics 2','Electric force, field, and potential','/science/ap-physics-2/x0e2f5a2c:electric-force-field-and-potential'),
 ap2_circuits:u('ap2_circuits','AP®︎/College Physics 2','Electric circuits','/science/ap-physics-2/x0e2f5a2c:electric-circuits'),
 ap2_magnetism:u('ap2_magnetism','AP®︎/College Physics 2','Magnetism and electromagnetism','/science/ap-physics-2/x0e2f5a2c:magnetism-and-electromagnetism'),
 ap2_optics:u('ap2_optics','AP®︎/College Physics 2','Geometric optics','/science/ap-physics-2/x0e2f5a2c:geometric-optics'),
 ap2_waves:u('ap2_waves','AP®︎/College Physics 2','Waves, sound, and physical optics','/science/ap-physics-2/x0e2f5a2c:waves-sound-and-physical-optics'),
 ap2_modern:u('ap2_modern','AP®︎/College Physics 2','Modern physics','/science/ap-physics-2/x0e2f5a2c:modern-physics'),
 ee_intro:u('ee_intro','Electrical engineering','Introduction to electrical engineering','/science/electrical-engineering/introduction-to-ee'),
 ee_circuits:u('ee_circuits','Electrical engineering','Circuit analysis','/science/electrical-engineering/ee-circuit-analysis-topic'),
 ee_amplifiers:u('ee_amplifiers','Electrical engineering','Amplifiers','/science/electrical-engineering/ee-amplifiers'),
 ee_semiconductors:u('ee_semiconductors','Electrical engineering','Semiconductor devices','/science/electrical-engineering/ee-semiconductor-devices'),
 ee_signals:u('ee_signals','Electrical engineering','Signals and systems','/science/electrical-engineering/ee-signals'),
 // Environment, astronomy and history
 apes_living:u('apes_living','AP®︎/College Environmental science','The living world: ecosystems and biodiversity','/science/ap-college-environmental-science/x0b0e430a38ebd23f:the-living-world-ecosystems-and-biodiversity'),
 apes_populations:u('apes_populations','AP®︎/College Environmental science','Populations','/science/ap-college-environmental-science/x0b0e430a38ebd23f:populations'),
 apes_earth:u('apes_earth','AP®︎/College Environmental science','Earth systems and resources','/science/ap-college-environmental-science/x0b0e430a38ebd23f:earth-systems-and-resources'),
 apes_land:u('apes_land','AP®︎/College Environmental science','Land and water use','/science/ap-college-environmental-science/x0b0e430a38ebd23f:land-and-water-use'),
 apes_energy:u('apes_energy','AP®︎/College Environmental science','Energy resources and consumption','/science/ap-college-environmental-science/x0b0e430a38ebd23f:energy-resources-and-consumption'),
 apes_air:u('apes_air','AP®︎/College Environmental science','Atmospheric pollution','/science/ap-college-environmental-science/x0b0e430a38ebd23f:atmospheric-pollution'),
 apes_aquatic:u('apes_aquatic','AP®︎/College Environmental science','Aquatic and terrestrial pollution','/science/ap-college-environmental-science/x0b0e430a38ebd23f:aquatic-and-terrestrial-pollution'),
 apes_global:u('apes_global','AP®︎/College Environmental science','Global change','/science/ap-college-environmental-science/x0b0e430a38ebd23f:global-change'),
 cos_scale:u('cos_scale','Cosmology and astronomy','Scale of the universe','/science/cosmology-and-astronomy/universe-scale-topic'),
 cos_stars:u('cos_stars','Cosmology and astronomy','Stars, black holes and galaxies','/science/cosmology-and-astronomy/stellar-life-topic'),
 cos_earth:u('cos_earth','Cosmology and astronomy','Earth geological and climatic history','/science/cosmology-and-astronomy/earth-history-topic'),
 cos_life:u('cos_life','Cosmology and astronomy','Life on earth and in the universe','/science/cosmology-and-astronomy/life-earth-universe'),
 wh_nineteenth:u('wh_nineteenth','World history','The Long Nineteenth Century (1750 to 1914 CE)','/humanities/world-history/x66f79d8a:the-long-nineteenth-century'),
 wh_conflict:u('wh_conflict','World history','Global Conflict (1914 to 1991 CE)','/humanities/world-history/x66f79d8a:global-conflict'),
 wh_global:u('wh_global','World history','Globalization (1900 CE to the Present)','/humanities/world-history/x66f79d8a:globalization')
} as const satisfies Record<string,CollegeUnit>;
export type CollegeUnitId=keyof typeof COLLEGE_UNITS;
export const collegeUnitUrl=(id:CollegeUnitId)=>KHAN+COLLEGE_UNITS[id].path;

const v=(id:string,title:string,path:string):CollegeVideo=>({id,title,url:KHAN+path});
/** Each a full Khan Academy video, title and YouTube id read on its own page. */
export const COLLEGE_VIDEOS={
 limits:v('riXcZT2ICjA','Introducing limits','/math/calculus-1/cs1-limits-and-continuity/cs1-limits-intro/v/introduction-to-limits-hd'),
 uSub:v('b76wePnIBdU','Introducing u-substitution','/math/calculus-2/cs2-integration-techniques/cs2-integrating-with-u-substitution/v/u-substitution'),
 multivariable:v('TrcCbdWwCBc','Multivariable functions','/math/multivariable-calculus/thinking-about-multivariable-function/introduction-to-multivariable-calculus/v/multivariable-functions'),
 diffeq:v('6o7b9yyhH7k','Introducing differential equations','/math/differential-equations/first-order-differential-equations/differential-equations-intro/v/differential-equation-introduction'),
 vectors:v('br7tS1t2SFE','Vector intro for linear algebra','/math/linear-algebra/vectors-and-spaces/vectors/v/vector-introduction-linear-algebra'),
 complexPlane:v('kGzXIbauGQk','Plotting numbers on the complex plane','/math/precalculus/x9e81a4f98389efdf:complex/x9e81a4f98389efdf:complex-plane/v/plotting-complex-numbers-on-the-complex-plane'),
 permutations:v('DROZVHObeko','Permutation formula','/math/statistics-probability/counting-permutations-and-combinations/permutation-lib/v/permutation-formula'),
 randomVariables:v('3v9w79NhsfI','Random variables','/math/statistics-probability/random-variables-stats-library/random-variables-discrete/v/random-variables'),
 normal:v('79duxPXpyKQ','Qualitative sense of normal distributions','/math/statistics-probability/modeling-distributions-of-data/normal-distributions-library/v/ck12-org-normal-distribution-problems-qualitative-sense-of-normal-distributions'),
 confidence:v('hlM7zdf7zwU','Confidence intervals and margin of error','/math/statistics-probability/confidence-intervals-one-sample/introduction-to-confidence-intervals/v/confidence-intervals-and-margin-of-error'),
 hypothesis:v('5D1gV37bKXY','Simple hypothesis testing','/math/statistics-probability/significance-tests-one-sample/idea-of-significance-tests/v/simple-hypothesis-testing'),
 correlation:v('-Y-M9aD_ccQ','Example: Correlation coefficient intuition','/math/statistics-probability/describing-relationships-quantitative-data/scatterplots-and-correlation/v/correlation-coefficient-intuition-examples'),
 samples:v('aKAw-DyZa6g','Reasonable samples','/math/statistics-probability/designing-studies/sampling-and-surveys/v/reasonable-samples'),
 anova:v('EFdlFoHI_0I','ANOVA 1: Calculating SST (total sum of squares)','/math/statistics-probability/analysis-of-variance-anova-library/analysis-of-variance-anova/v/anova-1-calculating-sst-total-sum-of-squares'),
 whatIsCs:v('5LeZflr8Zfs','What is computer science?','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:computational-thinking-with-variables/x5279a44ae0ab15d6:the-programming-platform/v/what-is-computer-science'),
 programming:v('FCMxA3m_Imc','What is Programming?','/computing/computer-programming/programming/intro-to-programming/v/programming-intro'),
 classes:v('ocWCzDAH5lI','Classes and objects','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:building-software-with-classes/x5279a44ae0ab15d6:attributes/v/classes-and-objects'),
 algorithms:v('CvSOaYi89B4','What is an algorithm and why should you care?','/computing/computer-science/algorithms/intro-to-algorithms/v/what-are-algorithms'),
 web:v('jHPr-CuvHhs','Welcome to the web!','/computing/computer-programming/html-css/intro-to-html/v/making-webpages-intro'),
 sql:v('IXycPq7MnwE','Welcome to SQL','/computing/computer-programming/sql/sql-basics/v/welcome-to-sql'),
 datasets:v('WZQRJjeG6lo','Datasets and data structures','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:analyzing-data-with-dictionaries/x5279a44ae0ab15d6:dictionaries/v/datasets-and-data-structures'),
 simulation:v('YeYW8TIWLG8','Hair simulation overview','/computing/pixar/simulation/hair-simulation-101/v/hair-simulation-intro'),
 internet:v('Dxcc6ycZ73M','What is the Internet?','/computing/computers-and-internet/xcae6f4a7ff015e7d:the-internet/xcae6f4a7ff015e7d:introducing-the-internet/v/what-is-the-internet'),
 cryptography:v('Kf9KjCKmDcU','What is cryptography?','/computing/computer-science/cryptography/crypt/v/intro-to-cryptography'),
 publicKey:v('MsqqpO9R5Hc','Public key cryptography: What is it?','/computing/computer-science/cryptography/modern-crypt/v/diffie-hellman-key-exchange-part-1'),
 equilibrium:v('zaHM74k9Z1w','Dynamic equilibrium','/science/ap-chemistry-beta/x2eef969c74e0d802:equilibrium/x2eef969c74e0d802:introduction-to-equilibrium/v/dynamic-equilibrium'),
 hybrid:v('u1eGSL6J6Fo','sp3 hybridized orbitals and sigma bonds','/science/organic-chemistry/gen-chem-review/hybrid-orbitals-jay/v/sp3-hybridized-orbitals-and-sigma-bonds'),
 aminoAcids:v('BbZB-WBVFSk','Amino acid structure','/test-prep/mcat/biomolecules/amino-acids-and-proteins1/v/amino-acid-structure'),
 organelles:v('bWPQvxElpLY','Organelles in eukaryotic cells','/science/ap-biology/cell-structure-and-function/cell-structures-and-their-functions/v/organelles-in-eukaryotic-cells'),
 meiosis:v('XGWL9jfPHJ8','Phases of meiosis I','/science/ap-biology/heredity/meiosis-and-genetic-diversity/v/phases-of-meiosis-i'),
 evolution:v('GcjgWov7mTM','Introduction to evolution and natural selection','/science/ap-biology/natural-selection/natural-selection-ap/v/introduction-to-evolution-and-natural-selection'),
 bacteria:v('TDoGrbpJJ14','Bacteria','/science/biology/bacteria-archaea/prokaryote-structure/v/bacteria'),
 heart:v('Vi1JK6IYVt8','Meet the heart!','/science/health-and-medicine/human-anatomy-and-physiology/heart-introduction/v/meet-the-heart'),
 physics1:v('21p-yiQ9xy4','Introduction to AP Physics 1','/science/ap-college-physics-1/xf557a762645cccc5:kinematics/xf557a762645cccc5:scalars-and-vectors-in-1d/v/introduction-to-ap-physics-1'),
 charge:v('lU8qZ0UyZUk','Electric charge and electric force','/science/ap-physics-2/x0e2f5a2c:electric-force-field-and-potential/x0e2f5a2c:electric-charge-and-electric-force/v/electric-charge-and-electric-force'),
 kineticTheory:v('HkSXiHz9vUc','The kinetic molecular theory of gases','/science/ap-physics-2/x0e2f5a2c:thermodynamics/x0e2f5a2c:gases/v/the-kinetic-molecular-theory-of-gases'),
 circuitElements:v('l-h72j2-X0o','Ideal circuit elements','/science/electrical-engineering/ee-circuit-analysis-topic/circuit-elements/v/ideal-circuit-elements'),
 fluidFlow:v('ZBvQfi3P0l4','Fluid flow','/science/ap-college-physics-1/xf557a762645cccc5:fluids/xf557a762645cccc5:fluid-flow/v/fluid-flow'),
 carbonCycle:v('_dYkByQ9Kmg','The carbon cycle','/science/ap-college-environmental-science/x0b0e430a38ebd23f:the-living-world-ecosystems-and-biodiversity/x0b0e430a38ebd23f:biogeochemical-cycles/v/carbon-cycle'),
 scale:v('5FEjrStgcF8','Scale of the large','/science/cosmology-and-astronomy/universe-scale-topic/scale-earth-galaxy-tutorial/v/scale-of-the-large'),
 weber:v('O_nY1TM2RZM','Weber’s law and thresholds','/test-prep/mcat/processing-the-environment/sensory-perception/v/webers-law-and-thresholds'),
 nervousSystem:v('jmD0LBdAvlE','Structure of the nervous system','/test-prep/mcat/behavior/biological-basis-of-behavior-ner/v/structure-of-the-nervous-system'),
 piaget:v('Jt3-PIC2nCs','Piaget’s stages of cognitive development','/science/health-and-medicine/executive-systems-of-the-brain/cognition-lesson/v/piagets-stages-of-cognitive-development'),
 selfConcept:v('PaA0mLVQd3k','Self concept, self identity, and social identity','/test-prep/mcat/individuals-and-society/self-identity/v/self-concept-self-identity-social-identity'),
 sociology:v('-BVeSykcQeE','Macrosociology vs microsociology','/test-prep/mcat/society-and-culture/social-structures/v/macrosociology-vs-microsociology'),
 inequality:v('JYxspCbwZVs','Overview of social inequality','/test-prep/mcat/social-inequality/social-class/v/overview-of-social-inequality'),
 globalization:v('5SnR-e0S6Ic','Globalization I: The Upside','/humanities/world-history/x66f79d8a:globalization/x66f79d8a:is-globalization-good-or-bad-9-2/v/globalization-i-the-upside-crash-course-world-history-41-beta')
} as const satisfies Record<string,CollegeVideo>;
const V=COLLEGE_VIDEOS;

const s=(x:CollegeSubject)=>x;
/** Append new subjects; ids are saved in links and must match \w+. */
export const SUBJECTS:CollegeSubject[]=[
 // Mathematics
 s({id:'calculus1',title:'Calculus I',kind:'math',level:'First year',summary:'Limits and derivatives: the language of change that physics, engineering, statistics and computing all assume.',
  topics:['Limits and continuity','The derivative as a rate of change','Power, product, quotient and chain rules','Implicit differentiation and related rates','Optimisation and curve sketching','Antiderivatives and the definite integral'],
  units:['c1_limits','c1_rules','c1_chain','c1_apply','c1_analyze','c1_integrals'],videos:[V.limits],buildsOn:['lines_functions','exponents_polynomials','trigonometry'],engine:'graphs'}),
 s({id:'calculus2',title:'Calculus II',kind:'math',level:'First year',summary:'Integration and infinite series: areas, volumes, accumulated change and approximating functions with polynomials.',
  topics:['Substitution and integration by parts','Partial fractions and improper integrals','Areas, volumes and arc length','Separable differential equations','Parametric and polar curves','Sequences, series and Taylor polynomials'],
  units:['c2_techniques','c2_apply','c2_diffeq','c2_polar','c2_series'],videos:[V.uSub],buildsOn:['exponents_polynomials','geometry','sequences']}),
 s({id:'multivariable',title:'Multivariable calculus',kind:'math',level:'Second year',summary:'Calculus in three dimensions: surfaces, gradients and the integrals behind fluid flow, fields and optimisation.',
  topics:['Functions of several variables','Partial derivatives and the gradient','Tangent planes and linear approximation','Optimisation and Lagrange multipliers','Double and triple integrals','Line integrals and the theorems of Green and Stokes'],
  units:['mv_functions','mv_derivatives','mv_apply','mv_integrals','mv_theorems'],videos:[V.multivariable],buildsOn:['lines_functions','geometry','trigonometry']}),
 s({id:'diffeq',title:'Differential equations',kind:'math',level:'Second year',summary:'Equations that describe how things change: population growth, cooling, circuits, springs and vibrations.',
  topics:['Modelling with differential equations','Slope fields and Euler’s method','Separable and first-order linear equations','Second-order linear equations','Oscillation and damping','The Laplace transform'],
  units:['de_first','de_second','de_laplace','c2_diffeq'],videos:[V.diffeq],buildsOn:['lines_functions','exponents_polynomials']}),
 s({id:'linear_algebra',title:'Linear algebra',kind:'math',level:'First year',summary:'Vectors and matrices: the mathematics of graphics, data, machine learning and every system of many equations.',
  topics:['Vectors, span and linear independence','Matrices and matrix operations','Solving systems by row reduction','Determinants and inverses','Linear transformations','Bases, eigenvalues and eigenvectors'],
  units:['la_vectors','la_transforms','la_bases','pc_vectors','pc_matrices'],videos:[V.vectors],buildsOn:['linear_equations','geometry'],engine:'graphs'}),
 s({id:'precalculus',title:'College algebra and trigonometry',kind:'math',level:'First year',summary:'The algebra a first calculus course takes for granted, taken further: inverse, exponential and trigonometric functions, complex numbers and conics.',
  topics:['Composite and inverse functions','Exponential and logarithmic functions','Trigonometric functions and identities','Complex numbers','Conic sections','Sequences and series'],
  units:['ca_functions','ca_logs','pc_trig','pc_complex','pc_conics','pc_series'],videos:[V.complexPlane],buildsOn:['exponents_polynomials','quadratics','trigonometry','lines_functions'],engine:'quadratics'}),
 s({id:'discrete',title:'Discrete mathematics',kind:'math',level:'First year',summary:'The mathematics of computing: counting, logic, primes, recursion and graphs.',
  topics:['Logic, sets and proof','Counting, permutations and combinations','Probability for computing','Modular arithmetic and primes','Recursion and induction','Graphs and trees'],
  units:['sp_counting','pc_probcomb','pc_series','cs_crypto','cs_algorithms'],videos:[V.permutations],buildsOn:['sequences','statistics_probability'],
  gap:'We found no Khan Academy course on logic, sets and proof. The units here cover counting, probability, series, modular arithmetic and graphs.'}),
 // Statistics
 s({id:'describing_data',title:'Descriptive statistics',kind:'statistics',level:'First year',summary:'Summarising and displaying data honestly: the first step of every research methods and statistics course.',
  topics:['Displaying categorical and quantitative data','Centre, spread and shape','Percentiles and z-scores','Density curves and normal models','Comparing distributions','Reporting data without misleading'],
  units:['sp_categorical','sp_displaying','sp_summarizing','sp_modeling'],videos:[V.normal],buildsOn:['statistics_probability','percent_fractions'],engine:'fractions'}),
 s({id:'probability',title:'Probability and random variables',kind:'statistics',level:'First year',summary:'Chance made precise: the models behind games, risk, genetics, quality control and every statistical test.',
  topics:['Probability rules and conditional probability','Counting methods','Discrete and continuous random variables','Binomial and geometric distributions','Expected value and variance','The normal distribution'],
  units:['sp_probability','sp_counting','sp_randomvars','aps_prob'],videos:[V.randomVariables],buildsOn:['statistics_probability','percent_fractions']}),
 s({id:'study_design',title:'Research methods and study design',kind:'statistics',level:'First year',summary:'How good evidence is collected: samples, surveys and experiments, and how bias creeps in.',
  topics:['Statistical questions','Sampling methods and bias','Observational studies and experiments','Random assignment and control groups','Collecting data ethically','Reading a methods section'],
  units:['sp_design','aps_collect'],videos:[V.samples],buildsOn:['statistics_probability','main_idea','inference']}),
 s({id:'inference',title:'Statistical inference',kind:'statistics',level:'Second year',summary:'From a sample to a conclusion about everyone: confidence intervals and hypothesis tests.',
  topics:['Sampling distributions and the central limit theorem','Confidence intervals for proportions and means','Significance tests and P-values','Type I and type II errors','Comparing two groups','Chi-square tests'],
  units:['sp_sampling','sp_ci','sp_tests','sp_twosample','sp_chisq'],videos:[V.confidence,V.hypothesis],buildsOn:['statistics_probability','percent_fractions']}),
 s({id:'regression',title:'Regression and correlation',kind:'statistics',level:'Second year',summary:'Modelling how one variable moves with another, and how far a fitted line can be trusted.',
  topics:['Scatterplots and correlation','Least-squares regression lines','Residuals and model fit','Inference for the slope','Transforming non-linear data','Prediction and its limits'],
  units:['sp_bivariate','sp_regression','aps_regression'],videos:[V.correlation],buildsOn:['lines_functions','linear_equations','statistics_probability'],engine:'graphs'}),
 s({id:'anova',title:'Analysis of variance',kind:'statistics',level:'Second year',summary:'Comparing several groups at once, the workhorse test of experiments in science and psychology.',
  topics:['Comparing several group means','Sums of squares within and between groups','The F statistic','Assumptions and conditions','Following up a significant result'],
  units:['sp_anova','sp_twosample'],videos:[V.anova],buildsOn:['statistics_probability']}),
 // Programming
 s({id:'python',title:'Programming fundamentals in Python',kind:'programming',level:'First year',summary:'Your first programming course: thinking in steps, then writing, tracing and debugging real programs.',
  topics:['Variables, expressions and tracing','Conditionals and Boolean logic','Loops and simulation','Functions and decomposition','Lists','Debugging and testing'],
  units:['py_variables','py_conditionals','py_loops','py_functions','py_lists'],videos:[V.whatIsCs],buildsOn:['linear_equations','sequences','word_problems']}),
 s({id:'javascript',title:'Programming with JavaScript',kind:'programming',level:'First year',summary:'Programming through drawing, animation and games, the language of every web page.',
  topics:['Drawing and animating with code','Variables and functions','Logic and if statements','Loops and arrays','Objects and object-oriented design','Debugging'],
  units:['js_intro','js_games'],videos:[V.programming],buildsOn:['lines_functions','linear_equations']}),
 s({id:'oop',title:'Object-oriented programming',kind:'programming',level:'First year',summary:'Building larger programs from classes and objects that each look after their own data.',
  topics:['Classes and objects','Attributes and methods','Encapsulation and abstraction','Designing classes for a program','Inheritance and polymorphism','Building a larger project'],
  units:['py_classes','js_games'],videos:[V.classes],buildsOn:['word_problems']}),
 s({id:'algorithms',title:'Data structures and algorithms',kind:'programming',level:'Second year',summary:'Choosing how to store data and how to search and sort it, and measuring how fast a solution grows.',
  topics:['Linear and binary search','Asymptotic notation and Big-O','Selection, insertion, merge and quick sort','Recursion','Graphs and breadth-first search','Lists, dictionaries and hashing'],
  units:['cs_algorithms','py_lists','py_dicts'],videos:[V.algorithms],buildsOn:['exponents_polynomials','sequences']}),
 s({id:'web_dev',title:'Web development',kind:'programming',level:'Second year',summary:'Building web pages and making them interactive: structure, style and behaviour.',
  topics:['HTML structure and meaning','CSS styling and layout','The DOM and events','Interactive pages with JavaScript','Using a library such as jQuery','Accessibility and validation'],
  units:['web_htmlcss','web_htmljs','web_jquery'],videos:[V.web],buildsOn:[]}),
 s({id:'databases',title:'Databases and SQL',kind:'programming',level:'Second year',summary:'Storing information in tables and asking it questions, the core of every information system.',
  topics:['Tables, rows and keys','Querying with SELECT and WHERE','Aggregating and grouping','Joining related tables','Changing data safely','Designing a database'],
  units:['sql'],videos:[V.sql],buildsOn:['statistics_probability']}),
 s({id:'data_analysis',title:'Data analysis with code',kind:'programming',level:'Second year',summary:'Using programs to clean, summarise and question real datasets.',
  topics:['Datasets and data structures','Dictionaries and nested data','Cleaning and filtering data','Summarising and visualising','Drawing conclusions from data','Bias and privacy in data'],
  units:['py_dicts','csp_data','sql'],videos:[V.datasets],buildsOn:['statistics_probability','percent_fractions']}),
 s({id:'graphics',title:'Graphics and simulation programming',kind:'programming',level:'Elective',summary:'Programs that imitate the physical world: vectors, forces, particles and the simulations used in film.',
  topics:['Vectors and forces in code','Randomness and noise','Oscillation and particle systems','Spring and mass systems','Physics-based animation','Simulation as a scientific tool'],
  units:['js_sims','pixar_sim','csp_simulations'],videos:[V.simulation],buildsOn:['motion_forces','trigonometry']}),
 // Computing
 s({id:'systems',title:'Computer systems and networks',kind:'computing',level:'First year',summary:'What happens inside a computer and between computers: bits, hardware, the internet and the web.',
  topics:['Bits, bytes and binary','How a computer is built','Networks, IP addresses and DNS','Packets, routing and reliability','HTTP and the web','Compression and information'],
  units:['ci_digital','ci_computers','ci_internet','cs_info'],videos:[V.internet],buildsOn:['exponents_polynomials']}),
 s({id:'security',title:'Cryptography and cybersecurity',kind:'computing',level:'Second year',summary:'Keeping information secret and trustworthy, from ancient ciphers to the public-key systems behind every login.',
  topics:['Classical ciphers','Perfect secrecy and the one-time pad','Modular arithmetic and primes','Public-key cryptography and RSA','Online data security','Protecting personal data'],
  units:['cs_crypto','ci_security'],videos:[V.cryptography,V.publicKey],buildsOn:['exponents_polynomials','statistics_probability']}),
 // Science
 s({id:'gen_chem',title:'General chemistry',kind:'science',level:'First year',summary:'Atoms, bonds and reactions with the quantitative reasoning that every laboratory course expects.',
  topics:['Atomic structure and periodic trends','Bonding and molecular shape','Intermolecular forces and solutions','Reactions and stoichiometry','Kinetics and equilibrium','Thermodynamics, acids and bases'],
  units:['apc_atomic','apc_bonding','apc_imf','apc_reactions','apc_kinetics','apc_equilibrium','apc_acids','apc_thermo'],videos:[V.equilibrium],buildsOn:['moles_formulas','solutions_acids','matter_measurement'],engine:'moles'}),
 s({id:'organic_chem',title:'Organic chemistry',kind:'science',level:'Second year',summary:'The chemistry of carbon: how molecules are shaped and why they react the way they do.',
  topics:['Bonding, hybridisation and resonance','Functional groups and naming','Stereochemistry','Substitution and elimination','Aromatic compounds','Carbonyl chemistry and spectroscopy'],
  units:['oc_structure','oc_resonance','oc_alkanes','oc_stereo','oc_substitution','oc_aromatic','oc_carbonyl','oc_spectroscopy'],videos:[V.hybrid],buildsOn:['moles_formulas']}),
 s({id:'biochemistry',title:'Biochemistry',kind:'science',level:'Second year',summary:'The molecules of life: proteins, enzymes, carbohydrates, lipids and the chemistry of metabolism.',
  topics:['Amino acids and protein structure','Enzymes and their kinetics','Carbohydrates, lipids and nucleic acids','Metabolism and cellular energy','Water, pH and buffers','Laboratory techniques'],
  units:['mcat_biomolecules','apb_chemlife','bio_macro','bio_enzymes'],videos:[V.aminoAcids],buildsOn:['cells_life','moles_formulas','solutions_acids']}),
 s({id:'cell_bio',title:'Cell and molecular biology',kind:'science',level:'First year',summary:'How cells are built and run: membranes, energy, signalling and the flow of genetic information.',
  topics:['Cell structure and organelles','Membranes and transport','Respiration and photosynthesis','Cell signalling and the cell cycle','Gene expression and regulation','Biotechnology'],
  units:['apb_cells','apb_energetics','apb_signaling','apb_expression','bio_biotech'],videos:[V.organelles],buildsOn:['cells_life','genetics']}),
 s({id:'genetics',title:'Genetics',kind:'science',level:'Second year',summary:'How traits pass between generations and how DNA becomes a working organism.',
  topics:['Meiosis and genetic diversity','Mendelian inheritance','Linked genes and pedigrees','Mutations and chromosomes','DNA to RNA to protein','Probability in genetic crosses'],
  units:['apb_heredity','bio_genetics','bio_dogma'],videos:[V.meiosis],buildsOn:['genetics','statistics_probability','cells_life']}),
 s({id:'evolution_ecology',title:'Evolution and ecology',kind:'science',level:'First year',summary:'Why living things are the way they are, and how populations and ecosystems work.',
  topics:['Natural selection and adaptation','Population genetics and speciation','The tree of life','Population growth','Communities and ecosystems','Biodiversity and conservation'],
  units:['apb_selection','apb_ecology','bio_tree','bio_biodiversity'],videos:[V.evolution],buildsOn:['genetics','cells_life']}),
 s({id:'microbiology',title:'Microbiology and infectious disease',kind:'science',level:'Second year',summary:'Bacteria, viruses and the diseases they cause, with the body’s defences against them.',
  topics:['Prokaryote structure','Bacterial growth and genetics','Viruses and how they replicate','The immune response','Infectious diseases','Antibiotics and resistance'],
  units:['bio_bacteria','bio_viruses','hm_infectious','mcat_organs'],videos:[V.bacteria],buildsOn:['cells_life','genetics']}),
 s({id:'anatomy',title:'Human anatomy and physiology',kind:'science',level:'First year',summary:'How the body’s systems are built and how they keep it alive, the backbone of every health course.',
  topics:['Body organisation and homeostasis','Circulatory and respiratory systems','Nervous and endocrine systems','Digestive system','Musculoskeletal system','How the systems fail in disease'],
  units:['hm_intro','hm_circulatory','hm_respiratory','hm_nervous','hm_endocrine','hm_gi','hm_musculo','mcat_organs'],videos:[V.heart],buildsOn:['cells_life']}),
 s({id:'physics_mechanics',title:'Physics I: mechanics',kind:'science',level:'First year',summary:'Motion, forces and energy, with the vectors and calculus that engineering courses build on.',
  topics:['Kinematics in one and two dimensions','Newton’s laws and free-body diagrams','Work, energy and power','Momentum and collisions','Rotation and torque','Oscillations'],
  units:['ap1_kinematics','ap1_forces','ap1_energy','ap1_momentum','ap1_torque','ap1_oscillations','apcm'],videos:[V.physics1],buildsOn:['motion_forces','energy_heat','trigonometry'],engine:'forces'}),
 s({id:'physics_em',title:'Physics II: electricity, magnetism and waves',kind:'science',level:'Second year',summary:'Charges, fields, circuits, magnetism and light: the physics behind electronics and communication.',
  topics:['Electric charge, field and potential','Capacitance and current','Direct-current circuits','Magnetism and induction','Geometric and wave optics','Modern physics'],
  units:['ap2_electric','ap2_circuits','ap2_magnetism','ap2_optics','ap2_waves','ap2_modern'],videos:[V.charge],buildsOn:['electricity_waves','motion_forces','energy_heat']}),
 s({id:'thermodynamics',title:'Thermodynamics',kind:'science',level:'Second year',summary:'Heat, work and energy flow in gases, engines and chemical reactions.',
  topics:['Temperature and heat','Ideal gases and kinetic theory','The first law','Heat engines and the second law','Entropy and free energy','Thermochemistry'],
  units:['ap2_thermo','apc_thermo','apc_appthermo'],videos:[V.kineticTheory],buildsOn:['energy_heat','gases','matter_measurement']}),
 s({id:'circuits',title:'Circuit analysis and electronics',kind:'science',level:'Second year',summary:'Analysing electrical circuits and the devices inside them, the first course of electrical and electronics engineering.',
  topics:['Circuit elements and sources','Ohm’s and Kirchhoff’s laws','Node and mesh analysis','Capacitors, inductors and transients','AC analysis','Diodes, transistors and amplifiers'],
  units:['ee_intro','ee_circuits','ee_amplifiers','ee_semiconductors','ee_signals'],videos:[V.circuitElements],buildsOn:['electricity_waves','linear_equations']}),
 s({id:'health_physics',title:'Physics for the health sciences',kind:'science',level:'First year',summary:'The physics inside medicine: blood flow, pressure, sound, light, electricity and radiation.',
  topics:['Forces and motion in the body','Fluids, pressure and blood flow','Waves, sound and ultrasound','Light, lenses and the eye','Electricity in nerves and the heart','Radiation and imaging'],
  units:['ap1_fluids','ap1_oscillations','ap2_waves','ap2_optics','ap2_modern','mcat_physical'],videos:[V.fluidFlow],buildsOn:['motion_forces','energy_heat','matter_measurement','nuclear']}),
 s({id:'environmental',title:'Environmental science',kind:'science',level:'Elective',summary:'How ecosystems, resources and pollution connect, with the data behind climate change.',
  topics:['Ecosystems and biogeochemical cycles','Populations and resources','Land and water use','Energy resources','Air, water and soil pollution','Global climate change'],
  units:['apes_living','apes_populations','apes_earth','apes_land','apes_energy','apes_air','apes_aquatic','apes_global'],videos:[V.carbonCycle],buildsOn:['earth_space','cells_life']}),
 s({id:'astronomy',title:'Astronomy and cosmology',kind:'science',level:'Elective',summary:'The scale and history of the universe, from stars and galaxies to the story of the Earth.',
  topics:['The scale of the universe','Stars and their life cycles','Black holes and galaxies','The Big Bang and cosmic time','The Earth’s geological history','Life in the universe'],
  units:['cos_scale','cos_stars','cos_earth','cos_life'],videos:[V.scale],buildsOn:['earth_space','exponents_polynomials']}),
 // Social science
 s({id:'psychology',title:'Introduction to psychology',kind:'social',level:'First year',summary:'How people sense, think, learn and feel, studied with scientific methods.',
  topics:['Sensation and perception','Attention, memory and cognition','Learning and conditioning','Motivation and emotion','Personality','Psychological disorders'],
  units:['mcat_environment','mcat_behavior','hm_brain'],videos:[V.weber],buildsOn:['main_idea','inference','statistics_probability']}),
 s({id:'biopsych',title:'Brain and behaviour',kind:'social',level:'Second year',summary:'The biology underneath behaviour: neurons, brain systems, sleep, drugs and mental health.',
  topics:['Neurons and the nervous system','Brain structure and function','Sleep and consciousness','Drugs and the brain','Stress and health','Mental health and treatment'],
  units:['mcat_behavior','hm_nervous','hm_brain'],videos:[V.nervousSystem],buildsOn:['cells_life']}),
 s({id:'development',title:'Human development and cognition',kind:'social',level:'Second year',summary:'How thinking, language and identity change from childhood to old age.',
  topics:['Theories of development','Cognitive development','Language and thought','Problem solving and decision making','Intelligence','Identity across the life span'],
  units:['hm_brain','mcat_individuals','mcat_environment'],videos:[V.piaget],buildsOn:['main_idea','inference']}),
 s({id:'social_psych',title:'Social psychology',kind:'social',level:'Second year',summary:'How other people shape what we think and do.',
  topics:['Self-concept and identity','Attribution and social perception','Attitudes and persuasion','Conformity, obedience and groups','Prejudice and discrimination','Helping and aggression'],
  units:['mcat_individuals','mcat_society'],videos:[V.selfConcept],buildsOn:['inference','author_purpose']}),
 s({id:'sociology',title:'Introduction to sociology',kind:'social',level:'First year',summary:'Societies as systems: institutions, culture, inequality and social change.',
  topics:['Sociological perspectives','Social structure and institutions','Culture and socialisation','Demographics and social change','Social class and mobility','Health and inequality'],
  units:['mcat_society','mcat_inequality'],videos:[V.sociology,V.inequality],buildsOn:['main_idea','inference','statistics_probability']}),
 s({id:'world_history',title:'Modern world history',kind:'social',level:'First year',summary:'Revolutions, empires, world wars and globalisation: the background to modern politics and society.',
  topics:['Revolutions and the long nineteenth century','Industrialisation and empire','The world wars and the Cold War','Decolonisation','Globalisation','Human rights and global communities'],
  units:['wh_nineteenth','wh_conflict','wh_global'],videos:[V.globalization],buildsOn:['main_idea','author_purpose','inference']})
];
export const SUBJECT_BY_ID:Record<string,CollegeSubject>=Object.fromEntries(SUBJECTS.map(x=>[x.id,x]));
export const allSubjectVideos=()=>SUBJECTS.flatMap(x=>x.videos);
