/** Optional Khan Academy articles for the UPCAT pilot lessons ("Read Next").
 * Every title and address was read on the rendered Khan page on 2026-10-08; receipts are in
 * docs/THIRD_PARTY_MATERIALS.md, "Lesson readings". Opening a reading writes nothing and is
 * never learning evidence. Append only; never infer or construct an address. */
export type LessonReading={title:string;url:string;checked:string;why:string};

export const LESSON_READINGS:Readonly<Record<string,readonly LessonReading[]>>={
 'outline-upcat-the-real-number-system':[
  {title:'Classifying numbers review (article) | Khan Academy',url:'https://www.khanacademy.org/math/als-k-to-12-math/x54b4346ef80b5dcc:performance-standard-b/x54b4346ef80b5dcc:real-numbers/a/classifying-numbers-review',checked:'2026-10-08',why:'Reviews whole numbers, integers, rational and irrational numbers with worked classification examples.'},
  {title:'Irrational numbers: FAQ (article) | Khan Academy',url:'https://www.khanacademy.org/math/algebra/x2f8bb11595b61c86:irrational-numbers/x2f8bb11595b61c86:proofs-concerning-irrational-numbers/a/irrational-numbers-faq',checked:'2026-10-08',why:'Short questions and answers on what makes a number irrational, extending the video\'s examples.'}],
 'outline-upcat-integers-and-the-order-of-operations':[
  {title:'Order of operations review (article) | Khan Academy',url:'https://www.khanacademy.org/math/4th-grade-philippines/x178724567c9e5e1b:1st-quarter/x178724567c9e5e1b:performing-series-of-operations-using-mdas-rules/a/order-of-operations-review',checked:'2026-10-08',why:'Written review of the agreed order with worked examples; same rule as the video.'},
  {title:'Order of operations with rational numbers (article) | Khan Academy',url:'https://www.khanacademy.org/math/cc-seventh-grade-math/cc-7th-negative-numbers-multiply-and-divide/cc-7th-order-of-operations/a/order-of-operations-with-rational-numbers',checked:'2026-10-08',why:'Extends the order of operations to negative numbers and fractions, which the lesson title (integers) covers.'}],
 'outline-upcat-factors-multiples-and-divisibility':[
  {title:'Factors and multiples (article) | Khan Academy',url:'https://www.khanacademy.org/math/4th-grade-philippines/x178724567c9e5e1b:2nd-quarter/x178724567c9e5e1b:factors-multiples-and-prime-composite-numbers/a/factors-and-multiples',checked:'2026-10-08',why:'Explains factors and multiples and how they relate; a readable alternative while the matched video has no transcript.'},
  {title:'Least common multiple review (article) | Khan Academy',url:'https://www.khanacademy.org/math/als-k-to-12-math/x54b4346ef80b5dcc:performance-standard-b/x54b4346ef80b5dcc:common-factors-greatest-common-factor-gcf-least-common-multiple-lcm/a/least-common-multiple-review',checked:'2026-10-08',why:'From the matched video\'s own Khan lesson; worked LCM examples.'}],
 'outline-upcat-fractions-and-decimals':[
  {title:'Add and subtract fractions: FAQ (article) | Khan Academy',url:'https://www.khanacademy.org/math/6th-grade-philippines/x70c18de4d40c85c8:unit-1/x70c18de4d40c85c8:lesson-1/a/add-and-subtract-fractions-faq-2',checked:'2026-10-08',why:'Answers common questions on common denominators, the video\'s core step.'},
  {title:'Writing fractions as decimals review (article) | Khan Academy',url:'https://www.khanacademy.org/math/5th-grade-math-revised-k-to-10-3-terms/xb7372133ebd782e9:2nd-quarter/xb7372133ebd782e9:decimal-conversions-comparison-and-rounding/a/writing-fractions-as-decimals-review',checked:'2026-10-08',why:'Covers the decimals half of the lesson title, which the matched video does not.'}],
 'outline-upcat-percent':[
  {title:'Multi-step ratio and percent problems (article) | Khan Academy',url:'https://www.khanacademy.org/math/7th-grade-matatag/x065dcf1640354e81:1st-quarter/x065dcf1640354e81:percentages/a/multi-step-ratio-and-proportion-problems',checked:'2026-10-08',why:'Worked percent word problems that go one step beyond the video\'s base-finding example.'},
  {title:'Rates and percentages FAQ (article) | Khan Academy',url:'https://www.khanacademy.org/math/6th-grade-philippines/x70c18de4d40c85c8:2nd-quarter/x70c18de4d40c85c8:percentage-rate-percent/a/rates-and-percentages-faq',checked:'2026-10-08',why:'Questions and answers on percent, base and rate in the Philippine 6th-grade (MELCS) course.'}],
 'outline-upcat-ratio-and-proportion':[
  {title:'Ratio tables (article) | 2nd quarter | Khan Academy',url:'https://www.khanacademy.org/math/6th-grade-matatag/xb8e22b8c4894c878:2nd-quarter/xb8e22b8c4894c878:ratio-and-proportion/a/ratio-tables',checked:'2026-10-08',why:'From the matched video\'s own lesson; filling ratio tables is exactly the video\'s method.'},
  {title:'Ratios and proportions | Lesson (article) | Khan Academy',url:'https://www.khanacademy.org/math/6th-grade-matatag/xb8e22b8c4894c878:2nd-quarter/xb8e22b8c4894c878:ratio-and-proportion/a/gtp--praxis-math--article--ratios-and-proportions--lesson',checked:'2026-10-08',why:'Same lesson; a fuller written lesson on ratios and proportions with worked problems.'}],
 'outline-upcat-algebraic-expressions-and-laws-of-exponents':[
  {title:'Exponent properties review (article) | Khan Academy',url:'https://www.khanacademy.org/math/als-k-to-12-math/x54b4346ef80b5dcc:performance-standard-e/x54b4346ef80b5dcc:exponents/a/exponent-properties-review',checked:'2026-10-08',why:'From the matched video\'s own Khan lesson; a written summary of the exponent properties the video derives.'}],
 'outline-upcat-polynomials-special-products-and-factoring':[
  {title:'Factoring perfect square trinomials (article) | Khan Academy',url:'https://www.khanacademy.org/math/8th-grade-math-revised-k-to-10-3-terms/x39ed6d789992bb2a:unit-1/x39ed6d789992bb2a:factoring-polynomials/a/factoring-quadratics-perfect-squares',checked:'2026-10-08',why:'Same Khan lesson as the video; the written version of factoring perfect square trinomials.'},
  {title:'Difference of squares | Factoring quadratics (article) | Khan Academy',url:'https://www.khanacademy.org/math/8th-grade-math-revised-k-to-10-3-terms/x39ed6d789992bb2a:unit-1/x39ed6d789992bb2a:factoring-polynomials/a/factoring-quadratics-difference-of-squares',checked:'2026-10-08',why:'Same lesson; covers the other special product in the lesson title, which the video does not.'}],
 'outline-upcat-rational-expressions':[
  {title:'Reducing rational expressions to lowest terms (article) | Khan Academy',url:'https://www.khanacademy.org/math/pisa-2025-math-supplement/x092b0b93d51c9e96:1/x092b0b93d51c9e96:untitled-2/a/reducing-rational-expressions-to-lowest-terms',checked:'2026-10-08',why:'The article that follows the matched video in its Khan lesson; same skill.'},
  {title:'Intro to rational expressions (article) | Khan Academy',url:'https://www.khanacademy.org/math/8th-grade-math-revised-k-to-10-3-terms/x39ed6d789992bb2a:unit-1/x39ed6d789992bb2a:rational-algebraic-expressions/a/intro-to-rational-expressions',checked:'2026-10-08',why:'Found through Khan search; what a rational expression is, as background before reducing.'}],
 'outline-upcat-radicals':[
  {title:'How to simplify square roots (review) (article) | Khan Academy',url:'https://www.khanacademy.org/math/10th-grade-math-revised-k-to-10-3-terms/x06a77af3c81397cf:second-quarter/x06a77af3c81397cf:radical-expressions/a/simplifying-square-roots-review',checked:'2026-10-08',why:'From the matched video\'s own lesson; pulling perfect-square factors out of a root.'}],
 'outline-upcat-linear-equations-and-inequalities':[
  {title:'Two-step equations review (article) | Khan Academy',url:'https://www.khanacademy.org/math/8th-grade-math-revised-k-to-10-3-terms/x39ed6d789992bb2a:2nd-quarter/x39ed6d789992bb2a:linear-equations-in-one-variable/a/two-step-equations-review',checked:'2026-10-08',why:'From the matched video\'s own lesson; two-step equations like the balance example.'}],
 'outline-upcat-systems-of-linear-equations':[
  {title:'Substitution method review (systems of equations) (article) | Khan Academy',url:'https://www.khanacademy.org/math/8th-grade-math-revised-k-to-10-3-terms/x39ed6d789992bb2a:3rd-quarter/x39ed6d789992bb2a:systems-of-linear-equations-in-two-variables/a/substitution-method-review-systems-of-equations',checked:'2026-10-08',why:'Same Khan lesson as the video; the substitution method in writing.'},
  {title:'Elimination method review (systems of linear equations) (article) | Khan Academy',url:'https://www.khanacademy.org/math/8th-grade-math-revised-k-to-10-3-terms/x39ed6d789992bb2a:3rd-quarter/x39ed6d789992bb2a:systems-of-linear-equations-in-two-variables/a/elimination-method-review',checked:'2026-10-08',why:'Same lesson; the video compares its answer with elimination, which this article teaches.'}],
 'outline-upcat-quadratic-equations':[
  {title:'Quadratic formula explained (article) | Khan Academy',url:'https://www.khanacademy.org/math/9th-grade-math-revised-k-to-10-3-terms/x1e64c39423990571:2nd-quarter/x1e64c39423990571:solving-quadratic-equations/a/quadratic-formula-explained-article',checked:'2026-10-08',why:'Same Khan lesson as the video; explains the formula.'},
  {title:'Quadratic formula review (article) | Khan Academy',url:'https://www.khanacademy.org/math/9th-grade-math-revised-k-to-10-3-terms/x1e64c39423990571:2nd-quarter/x1e64c39423990571:solving-quadratic-equations/a/quadratic-formula-review',checked:'2026-10-08',why:'Same lesson; short review.'}],
 'outline-upcat-the-coordinate-plane-lines-and-slope':[
  {title:'Intro to slope (article) | Equations | Khan Academy',url:'https://www.khanacademy.org/math/pisa-2025-math-supplement/x092b0b93d51c9e96:1/x092b0b93d51c9e96:equations/a/slope-from-two-points',checked:'2026-10-08',why:'Next item after the matched video in its Khan lesson; slope from two points.'}],
 'outline-upcat-exponents-and-logarithms':[
  {title:'Intro to logarithms (article) | Logarithms | Khan Academy',url:'https://www.khanacademy.org/math/algebra2/x2ec2f6f830c9fb89:logs/x2ec2f6f830c9fb89:log-intro/a/intro-to-logarithms',checked:'2026-10-08',why:'Found through Khan search; what a logarithm is and how to evaluate one, matching the video\'s rewriting.'}],
 'outline-upcat-sequences-and-series':[
  {title:'Arithmetic series (article) | 1st quarter | Khan Academy',url:'https://www.khanacademy.org/math/strengthened-shs-general-math/x24dc5a0902f75de5:first-quarter/x24dc5a0902f75de5:series/a/evaluating-arithmetic-series-guided-practice',checked:'2026-10-08',why:'Same Khan lesson as the video; summing arithmetic series.'},
  {title:'Series: FAQ (article) | Series | Khan Academy',url:'https://www.khanacademy.org/math/strengthened-shs-general-math/x24dc5a0902f75de5:first-quarter/x24dc5a0902f75de5:series/a/series-faq',checked:'2026-10-08',why:'Same lesson; common questions about series.'}],
 'outline-upcat-word-problems':[
  {title:'Average velocity and speed review (article) | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-physics-1/x5eb5cea12d2cf683:introduction-to-physics/x5eb5cea12d2cf683:descriptors-of-motion/a/review-article-velocity-speed-no-graphs',checked:'2026-10-08',why:'Same Khan lesson as the matched video; velocity and speed problems.'},
  {title:'What is velocity? (article) | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-physics-1/x5eb5cea12d2cf683:introduction-to-physics/x5eb5cea12d2cf683:descriptors-of-motion/a/what-is-velocity',checked:'2026-10-08',why:'Same lesson; why velocity carries a direction.'}],
 'outline-upcat-imaginary-and-complex-numbers':[
  {title:'Intro to the imaginary numbers (article) | Khan Academy',url:'https://www.khanacademy.org/math/algebra2/x2ec2f6f830c9fb89:complex/x2ec2f6f830c9fb89:imaginary/a/intro-to-the-imaginary-numbers',checked:'2026-10-08',why:'Article companion to the matched video in the same Khan lesson.'},
  {title:'Powers of the imaginary unit (article) | Khan Academy',url:'https://www.khanacademy.org/math/algebra2/x2ec2f6f830c9fb89:complex/x2ec2f6f830c9fb89:imaginary/a/powers-of-the-imaginary-unit',checked:'2026-10-08',why:'Same lesson; the repeating powers of i that the quiz checks.'}],
 'outline-upcat-lines-angles-and-their-properties':[
  {title:'Parallel and perpendicular lines review (article) | Khan Academy',url:'https://www.khanacademy.org/math/9th-grade-math-revised-k-to-10-3-terms/x1e64c39423990571:unit-1/x1e64c39423990571:parallel-and-perpendicular-lines/a/parallel-perpendicular-review',checked:'2026-10-08',why:'From the matched video\'s own Khan lesson.'}],
 'outline-upcat-triangles-congruence-and-similarity':[
  {title:'Triangle similarity review (article) | Khan Academy',url:'https://www.khanacademy.org/math/9th-grade-math-revised-k-to-10-3-terms/x1e64c39423990571:3rd-quarter/x1e64c39423990571:polygon-similiarity/a/triangle-similarity-review',checked:'2026-10-08',why:'Same Khan lesson as the video.'},
  {title:'Angle-angle triangle similarity criterion (article) | Khan Academy',url:'https://www.khanacademy.org/math/9th-grade-math-revised-k-to-10-3-terms/x1e64c39423990571:3rd-quarter/x1e64c39423990571:polygon-similiarity/a/angle-angle-triangle-similarity-criterion',checked:'2026-10-08',why:'Same lesson; why two equal angles are enough for similarity.'}],
 'outline-upcat-right-triangles-and-the-pythagorean-theorem':[
  {title:'Pythagorean theorem intro problems (article) | Khan Academy',url:'https://www.khanacademy.org/math/pisa-2025-math-supplement/x092b0b93d51c9e96:space-and-shape/x092b0b93d51c9e96:measurement-of-distance-and-lengths-including-pythagorean-theorem/a/pythagorean-theorem-intro',checked:'2026-10-08',why:'Same Khan lesson as the video; intro problems.'}],
 'outline-upcat-perimeter-and-area-of-plane-figures':[
  {title:'Area of triangles (article) | Khan Academy',url:'https://www.khanacademy.org/math/pisa-2025-math-supplement/x092b0b93d51c9e96:space-and-shape/x092b0b93d51c9e96:measurement-of-area/a/area-of-triangle',checked:'2026-10-08',why:'The article right after the matched video in its Khan lesson.'},
  {title:'Area of parallelograms (article) | Khan Academy',url:'https://www.khanacademy.org/math/pisa-2025-math-supplement/x092b0b93d51c9e96:space-and-shape/x092b0b93d51c9e96:measurement-of-area/a/area-of-parallelogram',checked:'2026-10-08',why:'Same lesson; the parallelogram the video uses to explain half of base times height.'}],
 'outline-upcat-circles':[
  {title:'Area of circles review (article) | Khan Academy',url:'https://www.khanacademy.org/math/pisa-2025-math-supplement/x092b0b93d51c9e96:space-and-shape/x092b0b93d51c9e96:measurement-of-area/a/area-of-circles-review',checked:'2026-10-08',why:'Same Khan lesson as the video.'},
  {title:'Radius, diameter, & circumference | Circles (article) | Khan Academy',url:'https://www.khanacademy.org/math/pisa-2025-math-supplement/x092b0b93d51c9e96:space-and-shape/x092b0b93d51c9e96:measurement-of-area/a/radius-diameter-circumference',checked:'2026-10-08',why:'Same lesson; the radius and diameter distinction the quiz\'s common trap tests.'}],
 'outline-upcat-surface-area-and-volume-of-solids':[
  {title:'Volume formulas review (article) | Khan Academy',url:'https://www.khanacademy.org/math/pisa-2025-math-supplement/x092b0b93d51c9e96:space-and-shape/x092b0b93d51c9e96:geometric-approximations/a/volume-formulas-review',checked:'2026-10-08',why:'Found through Khan search; volume formulas including cylinders (search snippet).'},
  {title:'Surface area review (article) | Khan Academy',url:'https://www.khanacademy.org/math/pisa-2025-math-supplement/x092b0b93d51c9e96:space-and-shape/x092b0b93d51c9e96:measurement-of-surface-area/a/surface-area-review',checked:'2026-10-08',why:'Found through Khan search; surface area review.'}],
 'outline-upcat-converting-units-of-measurement':[
  {title:'Metric units of length review (mm, cm, m, & km) (article) | Khan Academy',url:'https://www.khanacademy.org/math/7th-grade-foundations-matatag/x1e2e8b1648d78e6f:unit-1/x1e2e8b1648d78e6f:conversion-of-units-of-measure/a/metric-units-of-length-review',checked:'2026-10-08',why:'Found through Khan search; metric length units, used in the quiz\'s kilometre-to-centimetre item.'},
  {title:'Metric units of volume review (L and mL) (article) | Khan Academy',url:'https://www.khanacademy.org/math/pisa-2025-math-supplement/x092b0b93d51c9e96:quantity/x092b0b93d51c9e96:converting-between-number-systems/a/metric-units-of-volume-review',checked:'2026-10-08',why:'Found through Khan search; litres and millilitres, the units the video converts.'}],
 'outline-upcat-quadrilaterals-and-polygons':[
  {title:'Polygons review (article) | 1st quarter | Khan Academy',url:'https://www.khanacademy.org/math/7th-grade-matatag/x065dcf1640354e81:1st-quarter/x065dcf1640354e81:angles/a/polygons-review',checked:'2026-10-08',why:'From the matched video\'s own Khan lesson.'},
  {title:'Properties of shapes: FAQ (article) | Khan Academy',url:'https://www.khanacademy.org/math/7th-grade-matatag/x065dcf1640354e81:1st-quarter/x065dcf1640354e81:angles/a/properties-of-shapes-faq',checked:'2026-10-08',why:'Same lesson; common questions about classifying shapes.'}],
 'outline-upcat-the-six-trigonometric-ratios':[
  {title:'Trigonometric ratios in right triangles (article) | Khan Academy',url:'https://www.khanacademy.org/math/9th-grade-math-revised-k-to-10-3-terms/x1e64c39423990571:3rd-quarter/x1e64c39423990571:trigonometric-ratios/a/finding-trig-ratios-in-right-triangles',checked:'2026-10-08',why:'Same Khan lesson as the video.'},
  {title:'Right triangle trigonometry review (article) | Khan Academy',url:'https://www.khanacademy.org/math/9th-grade-math-revised-k-to-10-3-terms/x1e64c39423990571:3rd-quarter/x1e64c39423990571:trigonometric-ratios/a/right-triangle-trigonometry-review',checked:'2026-10-08',why:'Same lesson; short review.'}],
 'outline-upcat-special-angles-and-the-unit-circle':[
  {title:'Trig unit circle review (article) | Khan Academy',url:'https://www.khanacademy.org/math/senior-high-school-precalculus/x3589147324a289c1:trigonometry/x3589147324a289c1:circular-functions/a/trig-unit-circle-review',checked:'2026-10-08',why:'The article after the matched video in its Khan lesson.'},
  {title:'Trig ratios of special triangles (article) | Khan Academy',url:'https://www.khanacademy.org/math/9th-grade-math-revised-k-to-10-3-terms/x1e64c39423990571:3rd-quarter/x1e64c39423990571:trigonometric-ratios/a/trig-ratios-of-special-triangles',checked:'2026-10-08',why:'Covers the special angles in the lesson title, which the matched video does not.'}],
 'outline-upcat-angles-of-elevation-and-depression':[
  {title:'Angles of elevation and depression (article) | Khan Academy',url:'https://www.khanacademy.org/math/9th-grade-math-revised-k-to-10-3-terms/x1e64c39423990571:3rd-quarter/x1e64c39423990571:trigonometric-ratios/a/angles-of-elevation-and-depression',checked:'2026-10-08',why:'Same Khan lesson as the video; a written treatment of the exact topic.'}],
 'outline-upcat-trigonometric-identities':[
  {title:'Trig identity reference (article) | Khan Academy',url:'https://www.khanacademy.org/math/precalculus/x9e81a4f98389efdf:trig/x9e81a4f98389efdf:using-trig-id/a/trig-identity-reference',checked:'2026-10-08',why:'Found through Khan search, same course as the video; a reference sheet of trig identities.'}],
 'outline-upcat-laws-of-sines-and-cosines':[
  {title:'Laws of sines and cosines review (article) | Khan Academy',url:'https://www.khanacademy.org/math/10th-grade-math-revised-k-to-10-3-terms/x06a77af3c81397cf:unit-1/x06a77af3c81397cf:laws-of-sines-and-its-ambiguous-cases/a/laws-of-sines-and-cosines-review',checked:'2026-10-08',why:'From the matched video\'s own lesson; both laws, which the quiz covers only in part.'}],
 'outline-upcat-mean-median-and-mode':[
  {title:'Measures of center: choosing the "best" option (article) | Khan Academy',url:'https://www.khanacademy.org/math/pisa-2025-math-supplement/x092b0b93d51c9e96:uncertainty-and-data/x092b0b93d51c9e96:data-variability/a/choosing-the-best-measure-of-center',checked:'2026-10-08',why:'Same Khan lesson; when to prefer the median, the video\'s closing point.'},
  {title:'Calculating the mean (article) | Khan Academy',url:'https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics/mean-and-median/a/calculating-the-mean',checked:'2026-10-08',why:'Linked from the matched video\'s page; calculating the mean.'}],
 'outline-upcat-probability-of-events':[
  {title:'Conditional probability and independence (article) | Khan Academy',url:'https://www.khanacademy.org/math/pisa-2025-math-supplement/x092b0b93d51c9e96:uncertainty-and-data/x092b0b93d51c9e96:chance-and-probability/a/check-independence-conditional-probability',checked:'2026-10-08',why:'Found through Khan search; one step beyond the video: checking whether events are independent. Optional extension.'}],
 'outline-upcat-reading-tables-and-graphs':[
  {title:'Double bar graphs (article) | Khan Academy',url:'https://www.khanacademy.org/math/10th-grade-math-foundations/x6c7b196f1c375936:data-and-probability/x6c7b196f1c375936:data-collection-and-sampling-techniques-and-the-presentation-of-data-in-appropriate-tables-and-graphs/a/double-bar-graphs',checked:'2026-10-08',why:'Same Khan lesson as the video; reading bar graphs.'}],
 'outline-upcat-variance-standard-deviation-and-percentiles':[
  {title:'The idea of spread and standard deviation (article) | Khan Academy',url:'https://www.khanacademy.org/math/statistics-probability/summarizing-quantitative-data/variance-standard-deviation-population/a/introduction-to-standard-deviation',checked:'2026-10-08',why:'Same Khan lesson as the video; what spread means.'},
  {title:'Standard deviation: calculating step by step (article) | Khan Academy',url:'https://www.khanacademy.org/math/statistics-probability/summarizing-quantitative-data/variance-standard-deviation-population/a/calculating-standard-deviation-step-by-step',checked:'2026-10-08',why:'Same lesson; the step-by-step computation.'}],
 'outline-upcat-propositions-and-truth-tables':[
  {title:'The converse, inverse and contrapositive of an if-then statement (article) | Khan Academy',url:'https://www.khanacademy.org/math/8th-grade-philippines/xa5b1424237e0f2b8:2nd-quarter/xa5b1424237e0f2b8:conditional-statements/a/the-converse-inverse-and-contrapositive-of-an-if-then-statement',checked:'2026-10-08',why:'Found through Khan search (Philippine 8th-grade course); the three forms the video and quiz cover.'}],
 'outline-upcat-limits':[
  {title:'Limits intro (article) | Limit of a function | Khan Academy',url:'https://www.khanacademy.org/math/senior-high-school-basic-calculus/x7f730b2f064f7e01:unit-1/x7f730b2f064f7e01:lesson-1/a/limits-intro',checked:'2026-10-08',why:'The article after the matched video in its Khan lesson.'},
  {title:'Using tables to approximate limit values (article) | Khan Academy',url:'https://www.khanacademy.org/math/senior-high-school-basic-calculus/x7f730b2f064f7e01:unit-1/x7f730b2f064f7e01:lesson-1/a/review-approximating-limits-from-tables',checked:'2026-10-08',why:'Same lesson; the numerical approach the video ends with.'}],
 'outline-upcat-simple-derivatives-and-integrals':[
  {title:'Antiderivatives and indefinite integrals review (article) | Khan Academy',url:'https://www.khanacademy.org/math/senior-high-school-basic-calculus/x7f730b2f064f7e01:integrals/x7f730b2f064f7e01:antiderivatives/a/antiderivatives-and-indefinite-integrals-review',checked:'2026-10-08',why:'Found through Khan search (Philippine Basic Calculus course); antiderivatives and the constant of integration.'},
  {title:'Power rule review (article) | Derivatives | Khan Academy',url:'https://www.khanacademy.org/math/senior-high-school-basic-calculus/x7f730b2f064f7e01:derivatives/x7f730b2f064f7e01:differentiation/a/power-rule-review',checked:'2026-10-08',why:'Found through Khan search; pairs with the lesson\'s second video (power rule).'}],
 'outline-upcat-characteristics-of-life-and-the-scientific-method':[
  {title:'The scientific method (article) | Khan Academy',url:'https://www.khanacademy.org/science/als-k-to-12-science/x46c2fc9f8e023990:1st-quarter/x46c2fc9f8e023990:understanding-the-components-of-a-scientific-investigation/a/the-science-of-biology',checked:'2026-10-08',why:'The article after the matched video in its Khan lesson; same method in writing.'}],
 'outline-upcat-biomolecules':[
  {title:'Learn: Macromolecules review (article) | Khan Academy',url:'https://www.khanacademy.org/science/shs-physical-science/x0492729e402f0c6b:unit-1-name/x0492729e402f0c6b:properties-and-structure-of-biomolecules/a/hs-biological-macromolecules-review',checked:'2026-10-08',why:'The article after the matched video in its lesson; a readable route while that video has no transcript.'},
  {title:'Learn: Carbohydrates (article) | Khan Academy',url:'https://www.khanacademy.org/science/shs-physical-science/x0492729e402f0c6b:unit-1-name/x0492729e402f0c6b:properties-and-structure-of-biomolecules/a/carbohydrates',checked:'2026-10-08',why:'Same lesson; one biomolecule class in depth.'}],
 'outline-upcat-cell-structure-and-transport':[
  {title:'Learn: The fluid mosaic model (article) | Khan Academy',url:'https://www.khanacademy.org/science/shs-biology-1/xca2b82fdfba136b8:unit-1-name/xca2b82fdfba136b8:cellular-transport/a/fluid-mosaic-model-cell-membranes-article',checked:'2026-10-08',why:'Same Khan lesson; the membrane structure behind selective permeability.'},
  {title:'Learn: Osmosis and tonicity (article) | Khan Academy',url:'https://www.khanacademy.org/science/shs-biology-1/xca2b82fdfba136b8:unit-1-name/xca2b82fdfba136b8:cellular-transport/a/osmosis',checked:'2026-10-08',why:'Same lesson; water movement, the in-between case the video mentions.'}],
 'outline-upcat-photosynthesis-and-cellular-respiration':[
  {title:'Learn: Introduction to photosynthesis (article) | Khan Academy',url:'https://www.khanacademy.org/science/8th-grade-science-revised-k-to-10-3-terms/x7174210a6d38b11d:1st-quarter/x7174210a6d38b11d:photosynthesis-and-cellular-respiration/a/intro-to-photosynthesis',checked:'2026-10-08',why:'Same Khan lesson as the video.'},
  {title:'Learn: Introduction to cellular respiration and redox (article) | Khan Academy',url:'https://www.khanacademy.org/science/8th-grade-science-revised-k-to-10-3-terms/x7174210a6d38b11d:1st-quarter/x7174210a6d38b11d:photosynthesis-and-cellular-respiration/a/intro-to-cellular-respiration-and-redox',checked:'2026-10-08',why:'Same lesson; covers cellular respiration, the half of the lesson title the video and quiz skip.'}],
 'outline-upcat-mitosis-and-meiosis':[
  {title:'Learn: Phases of mitosis (article) | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-biology-1/x12d91beacfa56326:cell-biology/x12d91beacfa56326:the-cell-cycle/a/phases-of-mitosis',checked:'2026-10-08',why:'Same Khan lesson as the video.'},
  {title:'Learn: Meiosis (article) | The cell cycle | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-biology-1/x12d91beacfa56326:cell-biology/x12d91beacfa56326:the-cell-cycle/a/phases-of-meiosis',checked:'2026-10-08',why:'Same lesson; the article after the video.'}],
 'outline-upcat-dna-rna-and-protein-synthesis':[
  {title:'Learn: Introduction to gene expression (central dogma) (article) | Khan Academy',url:'https://www.khanacademy.org/science/shs-biology-2/x2ea931c66bba6acd:3rd-quarter/x2ea931c66bba6acd:lesson-3-genetics-central-dogma/a/intro-to-gene-expression-central-dogma',checked:'2026-10-08',why:'Same Khan lesson; DNA to RNA to protein in one overview.'},
  {title:'Learn: Overview of transcription (article) | Khan Academy',url:'https://www.khanacademy.org/science/shs-biology-2/x2ea931c66bba6acd:3rd-quarter/x2ea931c66bba6acd:lesson-3-genetics-central-dogma/a/overview-of-transcription',checked:'2026-10-08',why:'Same lesson; the step the quiz\'s apply item practises.'}],
 'outline-upcat-inheritance-and-punnett-squares':[
  {title:'Key points: Genetics vocabulary and Punnett squares (article) | Khan Academy',url:'https://www.khanacademy.org/science/ms-biology/x0c5bb03129646fd6:inheritance-and-variation/x0c5bb03129646fd6:reproduction-and-genetic-variation/a/genetics-vocabulary-and-punnett-squares',checked:'2026-10-08',why:'Found through Khan search; the vocabulary (allele, genotype, phenotype) the video uses.'},
  {title:'Learn and try: The law of segregation (article) | Khan Academy',url:'https://www.khanacademy.org/science/shs-biology-2/x2ea931c66bba6acd:3rd-quarter/x2ea931c66bba6acd:lesson-1-genetics/a/the-law-of-segregation',checked:'2026-10-08',why:'Found through Khan search; same lesson as the quiz\'s practice page.'}],
 'outline-upcat-evolution-and-natural-selection':[
  {title:'Key points: Evolution (article) | Khan Academy',url:'https://www.khanacademy.org/science/als-k-to-12-science/x46c2fc9f8e023990:performance-standard-d-relate-how-science-and-technology-affect-people-s-beliefs-practices-and-ways-of-thinking/x46c2fc9f8e023990:evolution-adaptation-and-the-causes-of-extinction/a/evolution',checked:'2026-10-08',why:'Same Khan lesson as the video.'},
  {title:'Learn: Darwin, evolution, and natural selection (article) | Khan Academy',url:'https://www.khanacademy.org/science/als-k-to-12-science/x46c2fc9f8e023990:performance-standard-d-relate-how-science-and-technology-affect-people-s-beliefs-practices-and-ways-of-thinking/x46c2fc9f8e023990:evolution-adaptation-and-the-causes-of-extinction/a/darwin-evolution-natural-selection',checked:'2026-10-08',why:'Same lesson.'}],
 'outline-upcat-classification-and-biodiversity':[
  {title:'Phylogenetic trees (article) | 3rd quarter | Khan Academy',url:'https://www.khanacademy.org/science/shs-biology-2/x2ea931c66bba6acd:3rd-quarter/x2ea931c66bba6acd:lesson-3-systematics-based-on-evolutionary-relationships/a/tree-of-life',checked:'2026-10-08',why:'Same Khan lesson; how relatedness is drawn, matching the quiz\'s practice page (Phylogeny).'}],
 'outline-upcat-human-body-systems':[
  {title:'Learn: The circulatory system review (article) | Khan Academy',url:'https://www.khanacademy.org/science/shs-biology-2/x2ea931c66bba6acd:unit-1-name/x2ea931c66bba6acd:animal-circulatory-system/a/hs-the-circulatory-system-review',checked:'2026-10-08',why:'Same Khan lesson as the video.'}],
 'outline-upcat-ecosystems-and-energy-flow':[
  {title:'Learn: Food chains and food webs (article) | Khan Academy',url:'https://www.khanacademy.org/science/7th-grade-science-revised-k-to-10-3-terms/x7a95920ff531ae11:2nd-quarter/x7a95920ff531ae11:trophic-levels-and-food-pyramid/a/producers-and-consumers',checked:'2026-10-08',why:'Same Khan lesson as the matched video, which has no transcript.'},
  {title:'Learn: Trophic levels and energy loss (article) | Khan Academy',url:'https://www.khanacademy.org/science/7th-grade-science-revised-k-to-10-3-terms/x7a95920ff531ae11:2nd-quarter/x7a95920ff531ae11:trophic-levels-and-food-pyramid/a/matter-and-energy-in-ecosystems',checked:'2026-10-08',why:'Same lesson; energy flow between levels.'}],
 'outline-upcat-enzymes-and-cellular-metabolism':[
  {title:'Learn: Enzymes and the active site (article) | Khan Academy',url:'https://www.khanacademy.org/science/shs-biology-1/xca2b82fdfba136b8:unit-1-name/xca2b82fdfba136b8:enzymes/a/enzymes-and-the-active-site',checked:'2026-10-08',why:'Same Khan lesson as the video.'},
  {title:'Learn: Enzymes review (article) | Enzymes | Khan Academy',url:'https://www.khanacademy.org/science/shs-biology-1/xca2b82fdfba136b8:unit-1-name/xca2b82fdfba136b8:enzymes/a/hs-enzymes-review',checked:'2026-10-08',why:'Same lesson; short review.'}],
 'outline-upcat-nutrient-cycles-in-ecosystems':[
  {title:'Key points: The nitrogen cycle (article) | Khan Academy',url:'https://www.khanacademy.org/science/ap-college-environmental-science/x0b0e430a38ebd23f:the-living-world-ecosystems-and-biodiversity/x0b0e430a38ebd23f:biogeochemical-cycles/a/ap-es-the-nitrogen-cycle',checked:'2026-10-08',why:'The article after the matched video in its Khan lesson.'},
  {title:'Learn: The carbon cycle (article) | Khan Academy',url:'https://www.khanacademy.org/science/ap-college-environmental-science/x0b0e430a38ebd23f:the-living-world-ecosystems-and-biodiversity/x0b0e430a38ebd23f:biogeochemical-cycles/a/the-carbon-cycle-article',checked:'2026-10-08',why:'Same lesson; a second nutrient cycle the lesson title covers.'}],
 'outline-upcat-atomic-structure':[
  {title:'Atomic number, atomic mass, and isotopes (article) | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-chemistry-1/x174677b2bfa4bea2:1st-quarter/x174677b2bfa4bea2:untitled-75/a/atomic-number-atomic-mass-and-isotopes-article',checked:'2026-10-08',why:'Found through Khan search; extends the particle counts in the video to atomic number and isotopes.'},
  {title:'Discovery of the electron and nucleus (article) | Khan Academy',url:'https://www.khanacademy.org/science/8th-grade-science-revised-k-to-10-3-terms/x7174210a6d38b11d:1st-quarter/x7174210a6d38b11d:atom/a/discovery-of-the-electron-and-nucleus',checked:'2026-10-08',why:'Same Khan lesson as the video.'}],
 'outline-upcat-the-periodic-table-and-periodic-trends':[
  {title:'Learn: The periodic table, electron shells, and orbitals (article) | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-chemistry-1/x174677b2bfa4bea2:1st-quarter/x174677b2bfa4bea2:atomic-orbitals/a/the-periodic-table-electron-shells-and-orbitals-article',checked:'2026-10-08',why:'Found through Khan search; why the table\'s rows follow electron shells, the basis of the radius trend. Not a trends article.'}],
 'outline-upcat-chemical-bonding-and-naming-compounds':[
  {title:'Naming ions and ionic compounds (article) | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-chemistry-1/x174677b2bfa4bea2:measurements-in-chemistry/x174677b2bfa4bea2:naming-compounds/a/naming-ions-and-ionic-compounds',checked:'2026-10-08',why:'Same Khan lesson; same skill as the video.'},
  {title:'Polyatomic ions (article) | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-chemistry-1/x174677b2bfa4bea2:measurements-in-chemistry/x174677b2bfa4bea2:naming-compounds/a/polyatomic-ions-article',checked:'2026-10-08',why:'Same lesson; the next naming step.'}],
 'outline-upcat-chemical-reactions-and-balancing-equations':[
  {title:'Learn and try: Balancing chemical equations (article) | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-chemistry-2/xab97f50f38d5ef09:4th-quarter/xab97f50f38d5ef09:balancing-chemical-equations/a/balancing-chemical-equations',checked:'2026-10-08',why:'Same Khan lesson as the matched video, which has no transcript.'}],
 'outline-upcat-stoichiometry':[
  {title:'Learn: Limiting reactant and reaction yields (article) | Khan Academy',url:'https://www.khanacademy.org/science/shs-physical-science/x0492729e402f0c6b:unit-1-name/x0492729e402f0c6b:stoichiometry/a/limiting-reagents-and-percent-yield',checked:'2026-10-08',why:'Same Khan lesson; the limiting-reactant idea in the quiz\'s common trap.'}],
 'outline-upcat-gas-laws':[
  {title:'Learn: What is the ideal gas law? (article) | Khan Academy',url:'https://www.khanacademy.org/science/shs-general-physics-1/x83bcf7a5ed7a2fbc:2nd-quarter/x83bcf7a5ed7a2fbc:properties-of-ideal-gas-and-ideal-gas-law/a/what-is-the-ideal-gas-law',checked:'2026-10-08',why:'Found through Khan search; the same law in writing.'}],
 'outline-upcat-solutions-and-concentration':[
  {title:'How to calculate molarity (article) | Khan Academy',url:'https://www.khanacademy.org/science/shs-general-chemistry-2/x8e72aa8e889b96da:unit-1-name/x8e72aa8e889b96da:solution-chemistry-and-colligative-properties/a/molarity',checked:'2026-10-08',why:'Same Khan lesson as the video.'}],
 'outline-upcat-acids-bases-and-ph':[
  {title:'pH, acids, and bases review (article) | Khan Academy',url:'https://www.khanacademy.org/science/shs-general-chemistry-2/x8e72aa8e889b96da:2nd-quarter/x8e72aa8e889b96da:acids-bases-and-ph-calculations/a/hs-ph-acids-and-bases-review',checked:'2026-10-08',why:'Same Khan lesson as the video.'},
  {title:'pH, pOH, and the pH scale (article) | Khan Academy',url:'https://www.khanacademy.org/science/shs-general-chemistry-2/x8e72aa8e889b96da:2nd-quarter/x8e72aa8e889b96da:acids-bases-and-ph-calculations/a/ph-poh-and-the-ph-scale',checked:'2026-10-08',why:'Same lesson; the scale and tenfold steps.'}],
 'outline-upcat-heat-in-chemical-reactions':[
  {title:'Endothermic vs. exothermic reactions (article) | Khan Academy',url:'https://www.khanacademy.org/science/10th-grade-science-matatag/xaf924d0c475e22d4:3rd-quarter-science-of-materials/xaf924d0c475e22d4:energy-of-chemical-reactions/a/endothermic-vs-exothermic-reactions',checked:'2026-10-08',why:'Same Khan lesson as the video.'}],
 'outline-upcat-carbon-compounds-and-biochemistry':[
  {title:'Learn: Carbon and hydrocarbons (article) | Khan Academy',url:'https://www.khanacademy.org/science/9th-grade-melcs/x48ae216379e0830b:2nd-quarter/x48ae216379e0830b:carbon-compounds/a/carbon-and-hydrocarbons',checked:'2026-10-08',why:'Same Khan lesson; why carbon forms so many compounds.'}],
 'outline-upcat-elements-compounds-and-mixtures':[
  {title:'Mixtures (article) | Khan Academy',url:'https://www.khanacademy.org/science/ms-chemistry/xc370bc422b7f75fc:classifying-matter/xc370bc422b7f75fc:mixtures/a/mixtures',checked:'2026-10-08',why:'Found through Khan search; mixtures, the second half of the video.'},
  {title:'Learn and try: Molecules, compounds, and chemical formulas (article) | Khan Academy',url:'https://www.khanacademy.org/science/ms-chemistry/xc370bc422b7f75fc:classifying-matter/xc370bc422b7f75fc:compounds/a/compounds-and-chemical-formulas',checked:'2026-10-08',why:'Found through Khan search; the molecule-versus-compound distinction the video draws.'}],
 'outline-upcat-electron-configuration-and-quantum-numbers':[
  {title:'Electron configurations article (article) | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-chemistry-1/x174677b2bfa4bea2:1st-quarter/x174677b2bfa4bea2:electron-configurations/a/electron-configurations-article',checked:'2026-10-08',why:'The article after the matched video in its Khan lesson.'}],
 'outline-upcat-oxidation-reduction-and-electrochemistry':[
  {title:'Learn: Balancing redox equations (article) | Khan Academy',url:'https://www.khanacademy.org/science/shs-general-chemistry-2/x8e72aa8e889b96da:2nd-quarter/x8e72aa8e889b96da:electrochemistry/a/oxidation-reduction-redox-reactions',checked:'2026-10-08',why:'Same Khan lesson; uses the oxidation states the video introduces (a step further).'}],
 'outline-upcat-measurement-units-and-density':[
  {title:'Learn and try: Density (article) | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-chemistry-1/x174677b2bfa4bea2:1st-quarter/x174677b2bfa4bea2:density-of-matter/a/density',checked:'2026-10-08',why:'Found through Khan search (same course as the video); density as mass per volume.'}],
 'outline-upcat-scalars-and-vectors':[
  {title:'Recognizing vectors practice (article) | Khan Academy',url:'https://www.khanacademy.org/science/als-k-to-12-science/x46c2fc9f8e023990:4th-quarter/x46c2fc9f8e023990:differentiating-quantities-based-on-magnitude-and-direction/a/recognizing-vectors',checked:'2026-10-08',why:'Same Khan lesson; sorting quantities into vectors and scalars.'}],
 'outline-upcat-speed-velocity-and-acceleration':[
  {title:'What is velocity? (article) | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-physics-1/x5eb5cea12d2cf683:introduction-to-physics/x5eb5cea12d2cf683:descriptors-of-motion/a/what-is-velocity',checked:'2026-10-08',why:'Same Khan lesson as the video.'},
  {title:'What is acceleration? (article) | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-physics-1/x5eb5cea12d2cf683:introduction-to-physics/x5eb5cea12d2cf683:descriptors-of-motion/a/acceleration-article',checked:'2026-10-08',why:'Same lesson; covers acceleration, which the video and quiz do not.'}],
 'outline-upcat-newton-s-laws-and-friction':[
  {title:'Learn and try: Newton\'s first and second laws (article) | Khan Academy',url:'https://www.khanacademy.org/science/als-k-to-12-science/x46c2fc9f8e023990:4th-quarter/x46c2fc9f8e023990:understanding-the-interrelationship-between-force-motion-and-energy/a/what-is-newtons-second-law',checked:'2026-10-08',why:'Same Khan lesson as the video.'}],
 'outline-upcat-projectile-motion':[
  {title:'Learn and try: Projectile motion (article) | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-physics-1/x5eb5cea12d2cf683:introduction-to-physics/x5eb5cea12d2cf683:kinematics-projectile-motion/a/what-is-2d-projectile-motion',checked:'2026-10-08',why:'Same Khan lesson as the video.'},
  {title:'Horizontally launched projectile review (article) | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-physics-1/x5eb5cea12d2cf683:introduction-to-physics/x5eb5cea12d2cf683:kinematics-projectile-motion/a/projectile-kinematics-in-2d',checked:'2026-10-08',why:'Same lesson; the case in the quiz\'s apply item.'}],
 'outline-upcat-work-energy-and-power':[
  {title:'Work can be negative! (article) | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-physics-1/x5eb5cea12d2cf683:kinematics/x5eb5cea12d2cf683:work-and-power/a/work-can-be-negative',checked:'2026-10-08',why:'Same Khan lesson as the video.'},
  {title:'What is power? (article) | Work and Power | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-physics-1/x5eb5cea12d2cf683:kinematics/x5eb5cea12d2cf683:work-and-power/a/what-is-power',checked:'2026-10-08',why:'Same lesson; covers power, which the matched first video does not.'}],
 'outline-upcat-momentum-and-impulse':[
  {title:'Linear momentum review (article) | Khan Academy',url:'https://www.khanacademy.org/science/9th-grade-melcs/x48ae216379e0830b:4th-quarter/x48ae216379e0830b:momentum-impulse-and-collision/a/intro-to-linear-momentum-ap1',checked:'2026-10-08',why:'Same Khan lesson as the video.'},
  {title:'Impulse review (article) | Khan Academy',url:'https://www.khanacademy.org/science/9th-grade-melcs/x48ae216379e0830b:4th-quarter/x48ae216379e0830b:momentum-impulse-and-collision/a/impulse-ap1',checked:'2026-10-08',why:'Same lesson; the article after the video.'}],
 'outline-upcat-pressure-and-buoyancy-in-fluids':[
  {title:'Pressure (article) | Physics of fluids | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-general-science-3-terms/x381269a1083161e8:physics/x381269a1083161e8:physics-of-fluids/a/pressure-article',checked:'2026-10-08',why:'Same Khan lesson as the video.'},
  {title:'Buoyant force (article) | Physics of fluids | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-general-science-3-terms/x381269a1083161e8:physics/x381269a1083161e8:physics-of-fluids/a/buoyant-force-and-archimedes-principle-article',checked:'2026-10-08',why:'Same lesson; Archimedes\' principle in writing.'}],
 'outline-upcat-heat-and-temperature':[
  {title:'Learn: Specific heat, heat of vaporization, and density of water (article) | Khan Academy',url:'https://www.khanacademy.org/science/ap-biology/chemistry-of-life/structure-of-water-and-hydrogen-bonding/a/specific-heat-heat-of-vaporization-and-freezing-of-water',checked:'2026-10-08',why:'Found through Khan search; why water\'s specific heat is high. An AP Biology article, so optional.'}],
 'outline-upcat-waves-and-sound':[
  {title:'Wave properties review (article) | Waves | Khan Academy',url:'https://www.khanacademy.org/science/6th-grade-science-matatag/x1c42f0f13f909d5b:3rd-quarter/x1c42f0f13f909d5b:waves/a/wave-properties-review',checked:'2026-10-08',why:'Same Khan lesson as the video.'},
  {title:'Sound is a longitudinal wave (article) | Khan Academy',url:'https://www.khanacademy.org/science/6th-grade-science-matatag/x1c42f0f13f909d5b:3rd-quarter/x1c42f0f13f909d5b:waves/a/sound-is-a-longitudinal-wave',checked:'2026-10-08',why:'Same lesson; sound, the second half of the lesson title.'}],
 'outline-upcat-light-mirrors-and-lenses':[
  {title:'"Objects in the mirror are ..." actually images in the mirror (article) | Khan Academy',url:'https://www.khanacademy.org/science/10th-grade-melcs/x1cfbe2e54160ac98:2nd-quarter/x1cfbe2e54160ac98:image-formation-by-mirrors-and-lenses/a/objects-in-the-mirror-are-actually-images-in-the-mirror',checked:'2026-10-08',why:'Found through Khan search (same course as the video); covers mirrors, which the lens-only video skips.'},
  {title:'Thin lens sign conventions (article) | Khan Academy',url:'https://www.khanacademy.org/science/10th-grade-melcs/x1cfbe2e54160ac98:2nd-quarter/x1cfbe2e54160ac98:image-formation-by-lenses/a/thin-lens-sign-conventions',checked:'2026-10-08',why:'Same Khan lesson as the video; an optional step beyond it.'}],
 'outline-upcat-electric-circuits':[
  {title:'Current, resistance, and resistivity review (article) | Khan Academy',url:'https://www.khanacademy.org/science/9th-grade-science-matatag/xc6c9cbcd628f26fe:1st-quarter/xc6c9cbcd628f26fe:ohm-s-law/a/resistance-and-resistivity-ap1',checked:'2026-10-08',why:'Same Khan lesson as the video.'}],
 'outline-upcat-magnetism-and-electromagnetism':[
  {title:'Learn and try: Magnetic flux and Faraday\'s law (article) | Khan Academy',url:'https://www.khanacademy.org/science/shs-physical-science/x0492729e402f0c6b:4th-quarter/x0492729e402f0c6b:light-as-a-wave-and-a-particle/a/what-is-magnetic-flux',checked:'2026-10-08',why:'Found through Khan search; Faraday\'s law, the rule the video ends on.'}],
 'outline-upcat-radioactivity-and-half-life':[
  {title:'Decay graphs and half lives article (article) | Khan Academy',url:'https://www.khanacademy.org/science/shs-general-physics-2/xe75071a1e6b5ff51:4th-quarter/xe75071a1e6b5ff51:radioactive-decay/a/decay-graphs-and-half-lives-article',checked:'2026-10-08',why:'Found through Khan search; same lesson as the quiz\'s practice page.'}],
 'outline-upcat-thermodynamics-and-heat-transfer':[
  {title:'Learn and try: What is thermal conductivity? (article) | Khan Academy',url:'https://www.khanacademy.org/science/ap-physics-2/x0e2f5a2c:thermodynamics/x0e2f5a2c:thermal-energy-and-thermal-equilibrium/a/what-is-thermal-conductivity',checked:'2026-10-08',why:'Same Khan lesson; heat transfer, the second half of the lesson title.'}],
 'outline-upcat-rocks-and-minerals':[
  {title:'Key points: The rock cycle (article) | Khan Academy',url:'https://www.khanacademy.org/science/shs-earth-and-life-science/x901efce4a07b98a5:unit-1/x901efce4a07b98a5:minerals-and-rocks/a/the-rock-cycle',checked:'2026-10-08',why:'The article after the matched video in its Khan lesson.'}],
 'outline-upcat-plate-tectonics-earthquakes-and-volcanoes':[
  {title:'Key points: Plate tectonics and the ocean floor (article) | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-earth-and-space-science-1/x006d5d274c051fd7:origin-and-structure-of-the-earth/x006d5d274c051fd7:inside-the-earth/a/plate-tectonics-the-ocean-floor',checked:'2026-10-08',why:'Same Khan course and unit as the video.'},
  {title:'Volcanoes 101 (article) | Inside the Earth | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-earth-and-space-science-1/x006d5d274c051fd7:origin-and-structure-of-the-earth/x006d5d274c051fd7:inside-the-earth/a/volcanoes-101',checked:'2026-10-08',why:'Same unit; volcanoes, part of the lesson title.'}],
 'outline-upcat-weathering-erosion-and-landforms':[
  {title:'Key points: Weathering and erosion (article) | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-earth-and-space-science-2/x21bb710e6de17395:plate-tectonics-and-earth-s-processes/x21bb710e6de17395:weathering-erosion-and-sedimentation/a/weathering-and-erosion',checked:'2026-10-08',why:'The article after the matched video in its Khan lesson.'}],
 'outline-upcat-fossils-and-the-geologic-time-scale':[
  {title:'Key points: Earth\'s fossil record (article) | Khan Academy',url:'https://www.khanacademy.org/science/9th-grade-science-matatag/xc6c9cbcd628f26fe:2nd-quarter-earth-and-space-science/xc6c9cbcd628f26fe:geologic-time-scale/a/earth-s-fossil-record',checked:'2026-10-08',why:'Found through Khan search; from a geologic-time-scale lesson.'}],
 'outline-upcat-weather-climate-and-the-atmosphere':[
  {title:'Key points: Earth\'s atmosphere (article) | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-earth-and-space-science-1/x006d5d274c051fd7:origin-and-structure-of-the-earth/x006d5d274c051fd7:earth-s-place-in-the-solar-system/a/earth-s-atmosphere',checked:'2026-10-08',why:'Same Khan lesson as the video.'}],
 'outline-upcat-rock-layers-and-relative-dating':[
  {title:'Key points: Fossils and rock layers (article) | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-earth-and-space-science-1/x006d5d274c051fd7:origin-and-structure-of-the-earth/x006d5d274c051fd7:inside-the-earth/a/fossils-and-rock-layers',checked:'2026-10-08',why:'Same Khan lesson as the matched video (Fossils and rock layers).'}],
 'outline-upcat-the-solar-system-and-its-planets':[
  {title:'Key points: The solar system (article) | Khan Academy',url:'https://www.khanacademy.org/science/strengthened-shs-earth-and-space-science-1/x006d5d274c051fd7:origin-and-structure-of-the-earth/x006d5d274c051fd7:what-the-universe-is-made-of/a/the-solar-system',checked:'2026-10-08',why:'The article after the matched video in its Khan lesson.'}],
 'outline-upcat-earth-s-rotation-revolution-and-the-seasons':[
  {title:'Key points: Solar radiation and Earth\'s seasons (article) | Khan Academy',url:'https://www.khanacademy.org/science/6th-grade-science-matatag/x1c42f0f13f909d5b:4th-quarter/x1c42f0f13f909d5b:earth-s-revolution-and-rotation/a/solar-radiation-and-earths-seasons',checked:'2026-10-08',why:'Found through Khan search; same lesson as the quiz\'s practice page.'}],
 'outline-upcat-phases-of-the-moon-and-eclipses':[
  {title:'Types of lunar eclipses (article) | Khan Academy',url:'https://www.khanacademy.org/science/shs-physical-science/x0492729e402f0c6b:4th-quarter/x0492729e402f0c6b:evolving-models-of-the-universe/a/typs-of-lunar-eclipses',checked:'2026-10-08',why:'Same Khan lesson; covers eclipses, which the video and quiz skip.'},
  {title:'Orbital cycles (article) | Khan Academy',url:'https://www.khanacademy.org/science/shs-physical-science/x0492729e402f0c6b:4th-quarter/x0492729e402f0c6b:evolving-models-of-the-universe/a/orbital-cycles',checked:'2026-10-08',why:'Same lesson.'}],
 'outline-upcat-stars-and-constellations':[
  {title:'READ: Gallery — Stars (article) | Khan Academy',url:'https://www.khanacademy.org/science/als-k-to-12-science/x46c2fc9f8e023990:4th-quarter/x46c2fc9f8e023990:characteristics-of-stars-understanding-stars-based-on-the-sun/a/gallery-stars',checked:'2026-10-08',why:'Found through Khan search; a readable route on stars while the matched video has no transcript. Not about constellations.'}],
 'outline-upcat-the-origin-of-the-universe':[
  {title:'The Universe (article) | 1st quarter | Khan Academy',url:'https://www.khanacademy.org/science/shs-earth-science/xecff05e2330f305a:unit-1-name/xecff05e2330f305a:universe-and-the-solar-system/a/the-universe',checked:'2026-10-08',why:'The article after the matched video in its Khan lesson.'}],
 'outline-upcat-the-formation-of-earth':[
  {title:'READ: How Our Solar System Formed (article) | Khan Academy',url:'https://www.khanacademy.org/science/shs-earth-science/xecff05e2330f305a:unit-1-name/xecff05e2330f305a:universe-and-the-solar-system/a/how-our-solar-system-formed',checked:'2026-10-08',why:'From the Big Bang video\'s lesson; the cloud-to-planets story the formation video tells.'}],
 'outline-upcat-galaxies-and-other-objects-in-space':[
  {title:'What Is a Galaxy? (article) | Galaxies | Khan Academy',url:'https://www.khanacademy.org/partner-content/amnh/the-universe/galaxies/a/what-is-a-galaxy',checked:'2026-10-08',why:'Found through Khan search; American Museum of Natural History partner content hosted on Khan.'}],
};

/** Pilot lessons searched on 2026-10-08 with no fitting Khan article. */
export const NO_READING:readonly string[]=['outline-upcat-functions-and-their-graphs','outline-upcat-sets-and-venn-diagrams','outline-upcat-geometric-reasoning-and-proofs','outline-upcat-permutations-and-combinations','outline-upcat-fundamental-counting-principle-and-factorials','outline-upcat-plant-structure-and-function','outline-upcat-matter-its-properties-and-changes','outline-upcat-formulas-molar-mass-and-the-mole','outline-upcat-reaction-rates-and-equilibrium','outline-upcat-accuracy-precision-and-experimental-uncertainty','outline-upcat-nuclear-reactions','outline-upcat-relative-motion-and-velocities','outline-upcat-special-relativity','outline-upcat-earth-s-layers-and-composition','outline-upcat-depositional-landforms-and-bodies-of-water'];

export const readingsFor=(lessonId:string):readonly LessonReading[]=>Object.hasOwn(LESSON_READINGS,lessonId)?LESSON_READINGS[lessonId]:[];

/** The article's own name: Khan's page title without its kind, unit and site suffixes. */
export const readingLabel=(r:LessonReading)=>r.title.replace(/ \(article\).*$/,'').split(' | ')[0].replace(/^(?:Learn(?: and try)?|READ): /,'');
