import type {ExamId} from './admissions.ts';
import {VIDEOS as Q,type KhanVideo} from './khan-videos.ts';
import {EXAM_OUTLINES} from './exam-outline.ts';
export type {KhanVideo};

/** Khan Academy videos for every UPCAT reviewer topic and every college subject topic. Each page
 *  was opened in the in-app browser on its check date: its rendered title named the video as
 *  "(video)" on Khan Academy and its player was a youtube-nocookie embed of the listed id. Nothing
 *  is guessed from a URL pattern. The log is in docs/THIRD_PARTY_MATERIALS.md under "Topic videos".
 *  Question videos (khan-videos.ts) are reused where the same video fits the topic.
 *
 *  A topic Khan has no matching video for is listed in a NO_VIDEO list and the page says so. The
 *  Filipino grammar and vocabulary topics are there on purpose: an English video is never offered
 *  for a Filipino topic (owner, 7 October 2026). Watching is activity, never learning evidence. */
export const TOPIC_VIDEOS_CHECKED='2026-10-07';
const KHAN='https://www.khanacademy.org';
const v=(id:string,title:string,path:string):KhanVideo=>({id,title,url:KHAN+path,checked:TOPIC_VIDEOS_CHECKED});

const T={
 usingContextCluesToFigure:v('CiNggzdWkIo','Using context clues to figure out new words','/ela/pisa-2025-english-supplement/x0fbe4cb2373ed873:7th-grade-reading-vocabulary/x0fbe4cb2373ed873:living-tongues/v/using-context-clues-to-figure-out-new-words-reading'),
 latinAndGreekRootsAnd:v('fiaPqgwJFo4','Latin and Greek roots and affixes','/ela/pisa-2025-english-supplement/x0fbe4cb2373ed873:7th-grade-reading-vocabulary/x0fbe4cb2373ed873:living-tongues/v/latin-and-greek-roots-and-affixes-reading'),
 figurativeLanguage:v('lzKj-bLvrYQ','Figurative language','/ela/pisa-2025-english-supplement/x0fbe4cb2373ed873:8th-grade-reading-vocabulary/x0fbe4cb2373ed873:crossing-the-line/v/figurative-language-reading'),
 introductionToGrammar:v('O-6q-siuMik','Introduction to grammar','/humanities/grammar/parts-of-speech-the-noun/welcome-to-grammar-subject/v/introduction-to-grammar'),
 introductionToVerbTense:v('faUvT7zfsyk','Introduction to verb tense','/humanities/grammar/parts-of-speech-the-verb/the-tenses/v/introduction-to-verb-tense-the-parts-of-speech-grammar'),
 whatIsAnAdverbIntro:v('b3RaBB7IDZc','What is an adverb? | Intro to adverbs','/humanities/grammar/parts-of-speech-the-modifier/introduction-to-adverbs/v/intro-to-adverbs'),
 meetThePreposition:v('D3wQ5dgFPms','Meet the preposition','/humanities/grammar/parts-of-speech-the-preposition-and-the-conjunction/introduction-to-prepositions/v/meet-the-preposition'),
 meetTheComma:v('Wk0k2FLjM1c','Meet the comma','/humanities/grammar/punctuation-the-comma-and-the-apostrophe/introduction-to-commas/v/meet-the-comma-the-comma-punctuation-khan-academy'),
 runOnsAndCommaSplices:v('Fh45mhVsZrU','Run-ons and comma splices','/humanities/grammar/syntax-conventions-of-standard-english/fragments-and-run-ons/v/run-ons-and-comma-splices-syntax-khan-academy'),
 danglingModifiers:v('SjunMcrXgE0','Dangling modifiers','/humanities/grammar/syntax-conventions-of-standard-english/dangling-modifiers-and-parallel-structure/v/dangling-modifiers-syntax-khan-academy'),
 parallelStructure:v('2l2FgUrln1A','Parallel structure','/humanities/grammar/syntax-conventions-of-standard-english/dangling-modifiers-and-parallel-structure/v/parallel-structure-syntax-khan-academy'),
 simpleAndCompoundSentences:v('3DGKY3eM9PY','Simple and compound sentences','/humanities/grammar/syntax-sentences-and-clauses/types-of-sentences/v/simple-and-compound-sentences-syntax-khan-academy'),
 commasInDialogue:v('uYoX_Qyknao','Commas in dialogue','/humanities/grammar/punctuation-the-comma-and-the-apostrophe/more-ways-to-use-commas/v/commas-in-dialogue-the-comma-punctuation-khan-academy'),
 theStructuresOfInformationalTexts:v('D0YUpfLofgQ','The structures of informational texts','/ela/5th-grade-english-foundations/xc1f7df3d387fd7d1:1st-quarter/xc1f7df3d387fd7d1:text-types/v/the-structures-of-informational-texts-reading'),
 factOrOpinionWorkedExample:v('GNDZ3ANLQps','Fact or opinion | Worked example','/ela/flemms-supplement/x3c3bbc36e759a314:reading-comprehending-texts/x3c3bbc36e759a314:distinguishing-fact-from-opinion/v/gtp--praxis-reading--video-fact-or-opinion'),
 analyzingAnAuthorSPurpose:v('R_bgo8j6jxc','Analyzing an author\'s purpose','/ela/pisa-2025-english-supplement/x0fbe4cb2373ed873:7th-grade-reading-vocabulary/x0fbe4cb2373ed873:living-tongues/v/analyzing-an-author-s-purpose-reading'),
 analyzingToneThroughWordChoice:v('l3yWmXbC36s','Analyzing tone through word choice','/ela/pisa-2025-english-supplement/x0fbe4cb2373ed873:8th-grade-reading-vocabulary/x0fbe4cb2373ed873:crossing-the-line/v/analyzing-tone-through-word-choice-reading'),
 whatIsAnArgument:v('NXO3KT8bne4','What is an argument?','/ela/pisa-2025-english-supplement/x0fbe4cb2373ed873:8th-grade-reading-vocabulary/x0fbe4cb2373ed873:crossing-the-line/v/what-is-an-argument-reading'),
 theElementsOfAStory:v('Zr1xLtSMMLo','The elements of a story','/ela/pisa-2025-english-supplement/x0fbe4cb2373ed873:7th-grade-reading-vocabulary/x0fbe4cb2373ed873:mysteries-of-the-past/v/the-elements-of-a-story-reading'),
 theElementsOfAPoem:v('LO21tYrTD8Y','The elements of a poem','/ela/pisa-2025-english-supplement/x0fbe4cb2373ed873:7th-grade-reading-vocabulary/x0fbe4cb2373ed873:living-tongues/v/the-elements-of-a-poem-reading'),
 quantitativeInformationInTexts:v('WzQGeCzOTyk','Quantitative information in texts','/ela/pisa-2025-english-supplement/x0fbe4cb2373ed873:8th-grade-reading-vocabulary/x0fbe4cb2373ed873:crossing-the-line/v/quantitative-information-in-texts-reading'),
 introToRationalIrrationalNumbers:v('cLP7INqs3JM','Intro to rational & irrational numbers | Algebra','/math/7th-grade-matatag/x065dcf1640354e81:1st-quarter/x065dcf1640354e81:rational-numbers/v/introduction-to-rational-and-irrational-numbers'),
 introToOrderOfOperations:v('ClYdw4d4OmA','Intro to order of operations','/math/7th-grade-matatag/x065dcf1640354e81:3rd-quarter/x065dcf1640354e81:order-of-operations/v/introduction-to-order-of-operations'),
 commonFactorsAndCommonMultiples:v('eTvTj1j2cSI','Common factors and common multiples','/math/als-k-to-12-math/x54b4346ef80b5dcc:performance-standard-b/x54b4346ef80b5dcc:common-factors-greatest-common-factor-gcf-least-common-multiple-lcm/v/common-factors-and-common-multiples'),
 solvingPercentProblems:v('TvSKeTFsaj4','Solving percent problems','/math/7th-grade-foundations-matatag/x1e2e8b1648d78e6f:numbers-algebra/x1e2e8b1648d78e6f:percentage-rate-and-percent/v/solving-percent-problems'),
 perfectSquareFactorizationIntro:v('JX5Zvh6swmo','Perfect square factorization intro','/math/8th-grade-math-revised-k-to-10-3-terms/x39ed6d789992bb2a:unit-1/x39ed6d789992bb2a:factoring-polynomials/v/perfect-square-factorization-intro'),
 reducingRationalExpressionsToLowest:v('7Uos1ED3KHI','Reducing rational expressions to lowest terms','/math/pisa-2025-math-supplement/x092b0b93d51c9e96:1/x092b0b93d51c9e96:untitled-2/v/simplifying-rational-expressions-introduction'),
 simplifyingSquareRootExpressionsNo:v('74iuGIaBgRc','Simplifying square-root expressions: no variables','/math/10th-grade-math-revised-k-to-10-3-terms/x06a77af3c81397cf:second-quarter/x06a77af3c81397cf:radical-expressions/v/simplifying-square-root-expressions-no-variables'),
 systemsOfEquationsWithSubstitution:v('2EwPpga_XPw','Systems of equations with substitution: potato chips','/math/8th-grade-math-revised-k-to-10-3-terms/x39ed6d789992bb2a:3rd-quarter/x39ed6d789992bb2a:systems-of-linear-equations-in-two-variables/v/solving-systems-with-substitution'),
 theQuadraticFormulaAlgebra:v('i7idZfS8t8w','The quadratic formula | Algebra','/math/9th-grade-math-revised-k-to-10-3-terms/x1e64c39423990571:2nd-quarter/x1e64c39423990571:solving-quadratic-equations/v/using-the-quadratic-formula'),
 relationshipBetweenExponentialsLogarithms:v('Obch1OP5QyA','Relationship between exponentials & logarithms','/math/senior-high-school-general-math/xc1934d16446a5789:unit-1/xc1934d16446a5789:logarithmic-functions/v/exponential-to-logarithmic-form'),
 arithmeticSeriesIntro:v('cYw4MFWsB6c','Arithmetic series intro','/math/strengthened-shs-general-math/x24dc5a0902f75de5:first-quarter/x24dc5a0902f75de5:series/v/sum-of-arithmetic-sequence-arithmetic-series'),
 anglesParallelLinesTransversals:v('H-E5rlpCVu4','Angles, parallel lines, & transversals','/math/9th-grade-math-revised-k-to-10-3-terms/x1e64c39423990571:unit-1/x1e64c39423990571:parallel-and-perpendicular-lines/v/angles-formed-by-parallel-lines-and-transversals'),
 introToTriangleSimilarity:v('9ThXDY9Y3oU','Intro to triangle similarity','/math/9th-grade-math-revised-k-to-10-3-terms/x1e64c39423990571:3rd-quarter/x1e64c39423990571:polygon-similiarity/v/similar-triangle-basics'),
 cylinderVolumeSurfaceArea:v('gL3HxBQyeg0','Cylinder volume & surface area','/math/7th-grade-matatag/x065dcf1640354e81:2nd-quarter/x065dcf1640354e81:volume-of-pyramids/v/cylinder-volume-and-surface-area'),
 conversionBetweenMetricUnits:v('SYkmadc2wOI','Conversion between metric units','/math/pisa-2025-math-supplement/x092b0b93d51c9e96:space-and-shape/x092b0b93d51c9e96:geometric-approximations/v/conversion-between-metric-units'),
 unitCircle:v('1m9p9iubMLU','Unit circle','/math/senior-high-school-precalculus/x3589147324a289c1:trigonometry/x3589147324a289c1:circular-functions/v/unit-circle-definition-of-trig-functions-1'),
 introToHeightsAndDistances:v('TgQs7k5p2Ag','Intro to heights and distances','/math/9th-grade-math-revised-k-to-10-3-terms/x1e64c39423990571:3rd-quarter/x1e64c39423990571:trigonometric-ratios/v/intro-to-heights-and-distances'),
 statisticsIntroMeanMedianMode:v('h8EYEJ32oQ8','Statistics intro: Mean, median, & mode','/math/pisa-2025-math-supplement/x092b0b93d51c9e96:uncertainty-and-data/x092b0b93d51c9e96:data-variability/v/statistics-intro-mean-median-and-mode'),
 permutationFormula:v('DROZVHObeko','Permutation formula','/math/pisa-2025-math-supplement/x092b0b93d51c9e96:quantity/x092b0b93d51c9e96:counting-principles/v/permutation-formula'),
 compoundProbabilityOfIndependentEvents:v('xSc4oLA9e8o','Compound probability of independent events','/math/10th-grade-math-revised-k-to-10-3-terms/x06a77af3c81397cf:third-term/x06a77af3c81397cf:probability-of-compound-events/v/compound-probability-of-independent-events'),
 readingBarGraphsMovies:v('R48KimqkYTA','Reading bar graphs: movies','/math/10th-grade-math-foundations/x6c7b196f1c375936:data-and-probability/x6c7b196f1c375936:data-collection-and-sampling-techniques-and-the-presentation-of-data-in-appropriate-tables-and-graphs/v/more-solving-problems-with-bar-graphs'),
 conditionalStatementsAndLogicalEquivalence:v('5kojy1CHuyI','Conditional statements and logical equivalence','/math/strengthened-shs-general-math/x24dc5a0902f75de5:fourth-quarter/x24dc5a0902f75de5:propositions/v/conditional-statements-and-logical-equivalence'),
 introducingLimits:v('riXcZT2ICjA','Introducing limits','/math/senior-high-school-basic-calculus/x7f730b2f064f7e01:unit-1/x7f730b2f064f7e01:lesson-1/v/introduction-to-limits-hd'),
 derivativeTheDirectionOfA:v('CpDfay5NeCg','Derivative & the direction of a function','/math/senior-high-school-basic-calculus/x7f730b2f064f7e01:derivatives/x7f730b2f064f7e01:derivative-of-a-function/v/interpreting-slope-of-a-curve-exercise'),
 theScientificMethod:v('N6IAzlugWw0','The scientific method','/science/als-k-to-12-science/x46c2fc9f8e023990:1st-quarter/x46c2fc9f8e023990:understanding-the-components-of-a-scientific-investigation/v/the-scientific-method'),
 introductionToBiomolecules:v('j5VA6YrqTNs','Introduction to biomolecules','/science/shs-physical-science/x0492729e402f0c6b:unit-1-name/x0492729e402f0c6b:properties-and-structure-of-biomolecules/v/introduction-to-biomolecules'),
 passiveTransportAndSelectivePermeability:v('jQN07Hvq6WI','Passive transport and selective permeability','/science/shs-biology-1/xca2b82fdfba136b8:unit-1-name/xca2b82fdfba136b8:cellular-transport/v/passive-transport-and-selective-permeability'),
 comparingMitosisAndMeiosis:v('IQJ4DBkCnco','Comparing mitosis and meiosis','/science/strengthened-shs-biology-1/x12d91beacfa56326:cell-biology/x12d91beacfa56326:the-cell-cycle/v/comparing-mitosis-and-meiosis'),
 dnaReplicationAndRnaTranscription:v('6gUY5NoX1Lk','DNA replication and RNA transcription and translation','/science/shs-biology-2/x2ea931c66bba6acd:3rd-quarter/x2ea931c66bba6acd:lesson-3-genetics-central-dogma/v/rna-transcription-and-translation'),
 introductionToEvolutionAndNatural:v('GcjgWov7mTM','Introduction to evolution and natural selection','/science/als-k-to-12-science/x46c2fc9f8e023990:performance-standard-d-relate-how-science-and-technology-affect-people-s-beliefs-practices-and-ways-of-thinking/x46c2fc9f8e023990:evolution-adaptation-and-the-causes-of-extinction/v/introduction-to-evolution-and-natural-selection'),
 taxonomyAndTheTreeOf:v('oHvLlS_Sc54','Taxonomy and the tree of life','/science/shs-biology-2/x2ea931c66bba6acd:3rd-quarter/x2ea931c66bba6acd:lesson-3-systematics-based-on-evolutionary-relationships/v/taxonomy-and-the-tree-of-life'),
 circulatorySystemAndTheHeart:v('QhiVnFvshZg','Circulatory system and the heart','/science/shs-biology-2/x2ea931c66bba6acd:unit-1-name/x2ea931c66bba6acd:animal-circulatory-system/v/circulatory-system-and-the-heart'),
 xylemTranspiration:v('d60lqIfGeQw','Xylem & transpiration','/science/shs-biology-2/x2ea931c66bba6acd:unit-1-name/x2ea931c66bba6acd:plant-transportation/v/xylem-transpiration-life-processes-biology-khan-academy'),
 energyFlowInFoodChains:v('1z6hrVdDDb4','Energy flow in food chains & webs','/science/7th-grade-science-revised-k-to-10-3-terms/x7a95920ff531ae11:2nd-quarter/x7a95920ff531ae11:trophic-levels-and-food-pyramid/v/energy-flow-in-food-chains-webs'),
 physicalAndChemicalChanges:v('n5cZ5CWuUJA','Physical and chemical changes','/science/strengthened-shs-chemistry-1/x174677b2bfa4bea2:measurements-in-chemistry/x174677b2bfa4bea2:types-of-chemical-bonding/v/physical-and-chemical-changes'),
 protonsNeutronsAndElectronsIn:v('lz_gMkQr7YE','Protons, neutrons, and electrons in atoms','/science/8th-grade-science-revised-k-to-10-3-terms/x7174210a6d38b11d:1st-quarter/x7174210a6d38b11d:atom/v/protons-neutrons-and-electrons-in-atoms'),
 atomicRadiusTrendsOnPeriodic:v('q--2WP8wXtk','Atomic radius trends on periodic table','/science/strengthened-shs-chemistry-1/x174677b2bfa4bea2:1st-quarter/x174677b2bfa4bea2:periodic-trends-atomic-radius/v/atomic-radius-trend'),
 namingIonsAndIonicCompounds:v('ptAw20kem90','Naming ions and ionic compounds','/science/strengthened-shs-chemistry-1/x174677b2bfa4bea2:measurements-in-chemistry/x174677b2bfa4bea2:naming-compounds/v/naming-ions-and-ionic-compounds'),
 balancingChemicalEquations:v('iWjQbfDMJ00','Balancing chemical equations','/science/strengthened-shs-chemistry-2/xab97f50f38d5ef09:4th-quarter/xab97f50f38d5ef09:balancing-chemical-equations/v/balancing-chemical-equations'),
 stoichiometryMassToMassAnd:v('5O083FL_9u8','Stoichiometry: Mass-to-mass and limiting reagent','/science/shs-physical-science/x0492729e402f0c6b:unit-1-name/x0492729e402f0c6b:stoichiometry/v/stoichiometry-mass-to-mass-and-limiting-reagent'),
 theIdealGasLawPv:v('qObcdZj8YTM','The ideal gas law (PV = nRT)','/science/10th-grade-melcs/x1cfbe2e54160ac98:4th-quarter/x1cfbe2e54160ac98:gas-laws/v/ideal-gas-equation-pv-nrt'),
 factorsAffectingReactionRates:v('CoNHV7786Hg','Factors affecting reaction rates','/science/shs-physical-science/x0492729e402f0c6b:unit-1-name/x0492729e402f0c6b:rates-of-reaction/v/factors-affecting-reaction-rates'),
 exothermicAndEndothermicReactions:v('NOmoGxniQoM','Exothermic and endothermic reactions','/science/10th-grade-science-matatag/xaf924d0c475e22d4:3rd-quarter-science-of-materials/xaf924d0c475e22d4:energy-of-chemical-reactions/v/exothermic-and-endothermic-reactions-chemical-reactions-chemistry-khan-academy'),
 functionalGroups:v('FYTfo4y91TI','Functional groups','/science/9th-grade-melcs/x48ae216379e0830b:2nd-quarter/x48ae216379e0830b:carbon-compounds/v/functional-groups-first'),
 introToVectorsAndScalars:v('ihNZlp7iUHE','Intro to vectors and scalars','/science/als-k-to-12-science/x46c2fc9f8e023990:4th-quarter/x46c2fc9f8e023990:differentiating-quantities-based-on-magnitude-and-direction/v/introduction-to-vectors-and-scalars'),
 projectileMotion:v('txJP95lBv98','Projectile motion','/science/strengthened-shs-physics-1/x5eb5cea12d2cf683:introduction-to-physics/x5eb5cea12d2cf683:kinematics-projectile-motion/v/projectile-motion'),
 impulseAndMomentumExample:v('uMYAc04D0ak','Impulse and momentum example','/science/9th-grade-melcs/x48ae216379e0830b:4th-quarter/x48ae216379e0830b:momentum-impulse-and-collision/v/impulse-and-momentum-dodgeball-example'),
 archimedesPrincipleAndBuoyantForce:v('vzID7ds600c','Archimedes principle and buoyant force','/science/strengthened-shs-general-science-3-terms/x381269a1083161e8:physics/x381269a1083161e8:physics-of-fluids/v/fluids-part-5'),
 convexLenses:v('K0sjZ5nqQ7g','Convex lenses','/science/10th-grade-melcs/x1cfbe2e54160ac98:2nd-quarter/x1cfbe2e54160ac98:image-formation-by-lenses/v/convex-lenses'),
 electromagneticInduction:v('yU--8Zk57-Y','Electromagnetic induction','/science/10th-grade-melcs/x1cfbe2e54160ac98:2nd-quarter/x1cfbe2e54160ac98:electromagnetic/v/electromagnetic-induction-faradays-experiments'),
 watchIntroductionToTheGeologic:v('UZ1YE68HszU','WATCH: Introduction to the Geologic Time Chart','/science/shs-earth-and-life-science/x901efce4a07b98a5:unit-1/x901efce4a07b98a5:history-of-the-earth/v/bhp-intro-geologic-timechart'),
 theSunSEnergyAnd:v('JMaqaspDpr0','The Sun\'s energy and Earth\'s weather','/science/strengthened-shs-earth-and-space-science-1/x006d5d274c051fd7:origin-and-structure-of-the-earth/x006d5d274c051fd7:earth-s-place-in-the-solar-system/v/the-sun-s-energy-and-earth-s-weather'),
 introToMoonPhases:v('ZQcf9xLABa0','Intro to Moon phases','/science/shs-physical-science/x0492729e402f0c6b:4th-quarter/x0492729e402f0c6b:evolving-models-of-the-universe/v/intro-to-moon-phases'),
 constellations:v('YmDO8yXk1sg','Constellations','/science/6th-grade-science-matatag/x1c42f0f13f909d5b:4th-quarter/x1c42f0f13f909d5b:constellations/v/constellations'),
 bigBangIntroduction:v('eUF59jCFcyQ','Big bang introduction','/science/shs-earth-science/xecff05e2330f305a:unit-1-name/xecff05e2330f305a:universe-and-the-solar-system/v/big-bang-introduction'),
 exploringContinuityAtAPoint:v('3KMqU5j7irw','Exploring continuity at a point','/math/calculus-1/cs1-limits-and-continuity/cs1-continuity-at-a-point/v/continuity-at-a-point'),
 exploringDerivativesAsAConcept:v('N2PpRnFqnqY','Exploring derivatives as a concept','/math/calculus-1/cs1-derivatives-definition-and-basic-rules/cs1-average-vs-instantaneous-rate-of-change/v/derivative-as-a-concept'),
 exploringThePowerRule:v('bRZmfc1YFsQ','Exploring the power rule','/math/calculus-1/cs1-derivatives-definition-and-basic-rules/cs1-power-rule/v/power-rule'),
 implicitDifferentiationExampleWalkthrough:v('mSVrqKZDRF4','Implicit differentiation (example walkthrough)','/math/calculus-1/cs1-derivatives-chain-rule-and-other-advanced-topics/cs1-implicit-differentiation/v/implicit-differentiation-1'),
 applyingOptimizationBoxVolumePart:v('MC0tq6fNRwU','Applying optimization: box volume (Part 1)','/math/calculus-1/cs1-analyzing-functions/cs1-solving-optimization-problems/v/optimizing-box-volume-graphically'),
 exploringAntiderivativesAndIndefiniteIntegrals:v('MMv-027KEqU','Exploring antiderivatives and indefinite integrals','/math/calculus-1/cs1-integrals/cs1-fundamental-theorem-of-calculus-and-definite-integrals/v/antiderivatives-and-indefinite-integrals'),
 integrationByPartsIntro:v('dh__n9FVKA0','Integration by parts intro','/math/calculus-2/cs2-integration-techniques/cs2-integration-by-parts/v/deriving-integration-by-parts-formula'),
 integrationWithPartialFractions:v('Mt92Ozs7aJg','Integration with partial fractions','/math/calculus-2/cs2-integration-techniques/cs2-integrating-using-linear-partial-fractions/v/integration-with-partial-fractions'),
 calculatingTheAreaBetweenCurves:v('wQXYtsyfbqg','Calculating the area between curves','/math/calculus-2/cs2-applications-of-integrals/cs2-area-vertical-area-between-curves/v/area-between-curves'),
 separableEquationsIntroductionDifferentialEquations:v('DL-ozRGDlkY','Separable equations introduction | Differential equations','/math/calculus-2/cs2-differential-equations/cs2-separation-of-variables/v/separable-differential-equations-introduction'),
 parametricEquationsIntro:v('m6c6dlmUT1c','Parametric equations intro','/math/calculus-2/cs2-parametric-equations-polar-coordinates-and-vector-valued-functions/cs2-parametric-equations-intro/v/parametric-equations-1'),
 taylorMaclaurinSeriesFormulaIntro:v('epgwuzzDHsQ','Taylor & Maclaurin series formula (intro)','/math/calculus-2/cs2-series/cs2-taylor-and-maclaurin-polynomials-intro/v/maclaurin-and-taylor-series-intuition'),
 introductionTo3dGraphs:v('2DRmfxkH_VI','Introduction to 3d graphs','/math/multivariable-calculus/thinking-about-multivariable-function/visualizing-scalar-valued-functions/v/introduction-to-3d-graphs'),
 partialDerivativesIntroduction:v('AXqhWeUEtQU','Partial derivatives, introduction','/math/multivariable-calculus/multivariable-derivatives/partial-derivatives/v/partial-derivatives-introduction'),
 whatIsATangentPlane:v('cHNT7_F8m1Y','What is a tangent plane','/math/multivariable-calculus/applications-of-multivariable-derivatives/tangent-planes-and-local-linearization/v/what-is-a-tangent-plane'),
 constrainedOptimizationIntroduction:v('vwUV2IDLP8Q','Constrained optimization introduction','/math/multivariable-calculus/applications-of-multivariable-derivatives/lagrange-multipliers-and-constrained-optimization/v/constrained-optimization-introduction'),
 doubleIntegral1:v('85zGYB-34jQ','Double integral 1','/math/multivariable-calculus/integrating-multivariable-functions/double-integrals-topic/v/double-integral-1'),
 introductionToTheLineIntegral:v('_60sKaoRmhU','Introduction to the line integral','/math/multivariable-calculus/integrating-multivariable-functions/line-integrals/v/introduction-to-the-line-integral'),
 writingADifferentialEquation:v('H9h-Xg7zjPU','Writing a differential equation','/math/differential-equations/first-order-differential-equations/differential-equations-intro/v/writing-a-differential-equation'),
 slopeFieldsIntroductionDifferentialEquations:v('8Amgakx5aII','Slope fields introduction | Differential equations','/math/differential-equations/first-order-differential-equations/slope-fields/v/creating-a-slope-field'),
 integratingFactors1:v('j511hg7Hlbg','Integrating factors 1','/math/differential-equations/first-order-differential-equations/exact-equations/v/integrating-factors-1'),
 v2ndOrderLinearHomogeneousDifferential:v('UFWAu8Ptth0','2nd order linear homogeneous differential equations 1','/math/differential-equations/second-order-differential-equations/linear-homogeneous-2nd-order/v/2nd-order-linear-homogeneous-differential-equations-1'),
 complexRootsOfTheCharacteristic:v('6xEO4BeawzA','Complex roots of the characteristic equations 1','/math/differential-equations/second-order-differential-equations/complex-roots-characteristic-equation/v/complex-roots-of-the-characteristic-equations-1'),
 laplaceTransformIntroDifferentialEquations:v('OiNh2DswFt4','Laplace transform intro | Differential equations','/math/differential-equations/laplace-transform/laplace-transform-tutorial/v/laplace-transform-1'),
 linearCombinationsAndSpan:v('Qm_OS-8COwU','Linear combinations and span','/math/linear-algebra/vectors-and-spaces/linear-combinations/v/linear-combinations-and-span'),
 matrixProductExamples:v('x1z0hOyjapU','Matrix product examples','/math/linear-algebra/matrix-transformations/composition-of-transformations/v/linear-algebra-matrix-product-examples'),
 solvingLinearSystemsWithMatrices:v('lP1DGtZ8Wys','Solving linear systems with matrices','/math/linear-algebra/vectors-and-spaces/matrices-elimination/v/matrices-reduced-row-echelon-form-2'),
 formulaFor2x2Inverse:v('eEUK_ThrHuQ','Formula for 2x2 inverse','/math/linear-algebra/matrix-transformations/inverse-of-matrices/v/linear-algebra-formula-for-2x2-inverse'),
 linearTransformations:v('4PCktDZJH8E','Linear transformations','/math/linear-algebra/matrix-transformations/linear-transformations/v/linear-transformations'),
 introductionToEigenvaluesAndEigenvectors:v('PhfbEr2btGQ','Introduction to eigenvalues and eigenvectors','/math/linear-algebra/alternate-bases/eigen-everything/v/linear-algebra-introduction-to-eigenvalues-and-eigenvectors'),
 introToInverseFunctions:v('W84lObmOp8M','Intro to inverse functions','/math/college-algebra/xa5dd2923c88e7aa8:functions/xa5dd2923c88e7aa8:intro-to-inverse-functions/v/introduction-to-function-inverses'),
 introToLogarithms:v('Z5myJ8dg_rM','Intro to logarithms','/math/college-algebra/xa5dd2923c88e7aa8:logarithms/xa5dd2923c88e7aa8:introduction-to-logarithms/v/logarithms'),
 trigAngleAdditionIdentities:v('a70-dYvDJZY','Trig angle addition identities','/math/precalculus/x9e81a4f98389efdf:trig/x9e81a4f98389efdf:angle-addition/v/trigonometry-identity-review-fun'),
 polarRectangularFormsOfComplex:v('8RasCV_Lggg','Polar & rectangular forms of complex numbers','/math/precalculus/x9e81a4f98389efdf:complex/x9e81a4f98389efdf:complex-polar/v/polar-form-complex-number'),
 introToConicSections:v('0A7RR0oy2ho','Intro to conic sections','/math/precalculus/x9e81a4f98389efdf:conics/x9e81a4f98389efdf:conics-intro/v/introduction-to-conic-sections'),
 geometricSeriesIntroduction:v('BdsURIUQ04k','Geometric series introduction','/math/precalculus/x9e81a4f98389efdf:series/x9e81a4f98389efdf:geo-series/v/geo-series-intro'),
 introToCombinations:v('iKy-d5_erhI','Intro to combinations','/math/statistics-probability/counting-permutations-and-combinations/combinations-lib/v/introduction-to-combinations'),
 randomizedAlgorithmsIntro:v('WGMn16TDTjE','Randomized algorithms (intro)','/computing/computer-science/cryptography/random-algorithms-probability/v/randomized-algorithms-prime-adventure-part-8'),
 theFundamentalTheoremOfArithmetic:v('8CluknrLeys','The fundamental theorem of arithmetic','/computing/computer-science/cryptography/modern-crypt/v/the-fundamental-theorem-of-arithmetic-1'),
 representingData:v('0ZKtsUkrgFQ','Representing data','/math/statistics-probability/displaying-describing-data/quantitative-data-graphs/v/ways-to-represent-data'),
 measuresOfSpreadRangeVariance:v('E4HAYd0QnRc','Measures of spread: range, variance & standard deviation','/math/statistics-probability/summarizing-quantitative-data/variance-standard-deviation-population/v/range-variance-and-standard-deviation-as-measures-of-dispersion'),
 zScoreIntroduction:v('5S-Zfa-vOXs','Z-score introduction','/math/ap-statistics/xfb5d8e68:exploring-one-variable-data-and-collecting-data/xfb5d8e68:comparisons-of-the-distributions-for-one-quantitative-variable/v/z-score-introduction'),
 densityCurves:v('PUvUQMQ7xQk','Density Curves','/math/statistics-probability/modeling-distributions-of-data/density-curve/v/density-curves'),
 exampleComparingDistributions:v('lT3LRjtSbJc','Example: Comparing distributions','/math/statistics-probability/displaying-describing-data/comparing-features-distributions/v/comparing-distributions'),
 misleadingLineGraphs:v('gs-OPF3KEGU','Misleading line graphs','/math/statistics-probability/displaying-describing-data/more-on-data-displays/v/misleading-line-graphs'),
 calculatingConditionalProbability:v('6xPkG2pA-TU','Calculating conditional probability','/math/statistics-probability/probability-library/conditional-probability-independence/v/calculating-conditional-probability'),
 countOutcomesUsingTreeDiagram:v('Zxvc6iPKdec','Count outcomes using tree diagram','/math/statistics-probability/counting-permutations-and-combinations/counting-principle-factorial/v/tree-diagram-to-count-outcomes'),
 discreteAndContinuousRandomVariables:v('dOr0NKyD31Q','Discrete and continuous random variables','/math/statistics-probability/random-variables-stats-library/random-variables-discrete/v/discrete-and-continuous-random-variables'),
 binomialDistribution:v('WWv0RUxDfbs','Binomial distribution','/math/statistics-probability/random-variables-stats-library/binomial-random-variables/v/binomial-distribution'),
 meanExpectedValueOfA:v('qafPcWNUiM8','Mean (expected value) of a discrete random variable','/math/statistics-probability/random-variables-stats-library/random-variables-discrete/v/expected-value-of-a-discrete-random-variable'),
 normalDistributionProblemsEmpiricalRule:v('OhRr26AfFBU','Normal distribution problems: Empirical rule','/math/statistics-probability/modeling-distributions-of-data/normal-distributions-library/v/ck12-org-normal-distribution-problems-empirical-rule'),
 statisticalQuestions:v('OjzfQDFf7Uk','Statistical questions','/math/statistics-probability/designing-studies/statistics-overview/v/understanding-statistical-questions'),
 techniquesForRandomSamplingAnd:v('PdXDLNNXPik','Techniques for random sampling and avoiding bias','/math/statistics-probability/designing-studies/sampling-methods-stats/v/techniques-for-random-sampling-and-avoiding-bias'),
 typesOfStatisticalStudies:v('SaP1O0i1bdc','Types of statistical studies','/math/statistics-probability/designing-studies/types-studies-experimental-observational/v/types-of-statistical-studies'),
 introductionToExperimentDesign:v('DaBq0naj0YY','Introduction to experiment design','/math/statistics-probability/designing-studies/experiments-stats-library/v/introduction-to-experiment-design'),
 centralLimitTheorem:v('JNm3M9cqWyc','Central limit theorem','/math/statistics-probability/sampling-distributions-library/sample-means/v/central-limit-theorem'),
 exampleConstructingAndInterpretingA:v('sjG9Ns_8x6c','Example constructing and interpreting a confidence interval for p','/math/statistics-probability/confidence-intervals-one-sample/estimating-population-proportion/v/example-calculating-confidence-interval'),
 pValuesAndSignificanceTests:v('KS6KEWaoOOE','P-values and significance tests','/math/statistics-probability/significance-tests-one-sample/idea-of-significance-tests/v/p-values-and-significance-tests'),
 introductionToTypeIAnd:v('Hdbbx7DIweQ','Introduction to Type I and Type II errors','/math/statistics-probability/significance-tests-one-sample/error-probabilities-and-power/v/introduction-to-type-i-and-type-ii-errors'),
 hypothesisTestForDifferenceOf:v('N984XGLjQfs','Hypothesis test for difference of means','/math/statistics-probability/significance-tests-confidence-intervals-two-samples/comparing-two-means/v/hypothesis-test-for-difference-of-means'),
 pearsonSChiSquareTest:v('2QeDRsxSF9M','Pearson\'s chi square test (goodness of fit)','/math/statistics-probability/inference-categorical-data-chi-square-tests/chi-square-goodness-of-fit-tests/v/pearson-s-chi-square-test-goodness-of-fit'),
 bivariateRelationshipLinearityStrengthAnd:v('30LcZqRfPRY','Bivariate relationship linearity, strength and direction','/math/statistics-probability/describing-relationships-quantitative-data/introduction-to-scatterplots/v/bivariate-relationship-linearity-strength-and-direction'),
 introductionToResidualsAndLeast:v('yMgFHbjbAW8','Introduction to residuals and least squares regression','/math/statistics-probability/describing-relationships-quantitative-data/regression-library/v/introduction-to-residuals-and-least-squares-regression'),
 residualPlots:v('VamMrPZ-8fc','Residual plots','/math/statistics-probability/describing-relationships-quantitative-data/assessing-the-fit-in-least-squares-regression/v/residual-plots'),
 introductionToInferenceAboutSlope:v('Pzglbt9_xCI','Introduction to inference about slope in linear regression','/math/statistics-probability/advanced-regression-inference-transforming/inference-on-slope/v/intro-inference-slope'),
 transformingNonlinearData:v('A1H4j97paI4','Transforming nonlinear data','/math/statistics-probability/advanced-regression-inference-transforming/nonlinear-regression/v/transforming-nonlinear-data'),
 estimatingWithLinearRegressionLinear:v('TWkYalFn8lo','Estimating with linear regression (linear models)','/math/statistics-probability/describing-relationships-quantitative-data/introduction-to-trend-lines/v/example-estimating-from-regression-line'),
 anova1CalculatingSstTotal:v('EFdlFoHI_0I','ANOVA 1: Calculating SST (total sum of squares)','/math/statistics-probability/analysis-of-variance-anova-library/analysis-of-variance-anova/v/anova-1-calculating-sst-total-sum-of-squares'),
 anova2CalculatingSswAnd:v('j9ZPMlVHJVs','ANOVA 2: Calculating SSW and SSB (total sum of squares within and between)','/math/statistics-probability/analysis-of-variance-anova-library/analysis-of-variance-anova/v/anova-2-calculating-ssw-and-ssb-total-sum-of-squares-within-and-between-avi'),
 anova3HypothesisTestWith:v('Xg8_iSkJpAE','ANOVA 3: Hypothesis test with F-statistic','/math/statistics-probability/analysis-of-variance-anova-library/analysis-of-variance-anova/v/anova-3-hypothesis-test-with-f-statistic'),
 variablesAndAssignment:v('52RHZdBSjTw','Variables and assignment','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:computational-thinking-with-variables/x5279a44ae0ab15d6:variables/v/what-is-a-variable-python'),
 ifStatements:v('7o1wX-jEnP8','if statements','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:designing-algorithms-with-conditionals/x5279a44ae0ab15d6:boolean-conditions/v/if-statements'),
 whileLoops:v('KsiWTrZQFXg','while loops','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:simulating-phenomena-with-loops/x5279a44ae0ab15d6:while-loops/v/while-loops'),
 functions:v('UmNKiV7Lekk','Functions','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:playing-games-with-functions/x5279a44ae0ab15d6:function-definitions/v/functions'),
 lists:v('IaEcrHxjoCM','Lists','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:automating-tasks-with-lists/x5279a44ae0ab15d6:list-indices/v/lists'),
 debuggingWithTestCases:v('eNmRjbVIZ0s','Debugging with test cases','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:playing-games-with-functions/x5279a44ae0ab15d6:edge-cases/v/debugging-with-test-cases'),
 debuggingWebpagesWithTheBrowser:v('JuVOwU0RcdA','Debugging webpages with the browser console','/computing/computer-programming/html-css-js/js-and-the-dom/v/debugging-webpages-with-the-browser-console'),
 classesAndObjects:v('ocWCzDAH5lI','Classes and objects','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:building-software-with-classes/x5279a44ae0ab15d6:attributes/v/classes-and-objects'),
 methodsAndEncapsulation:v('yGVBaM8o02E','Methods and encapsulation','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:building-software-with-classes/x5279a44ae0ab15d6:methods/v/methods'),
 softwareAndAbstraction:v('9oDAsFhSR5k','Software and abstraction','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:building-software-with-classes/x5279a44ae0ab15d6:attributes/v/software-and-abstraction'),
 programDesignCourseEnrollment:v('HrbXJZ7DTf4','Program design: course enrollment','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:building-software-with-classes/x5279a44ae0ab15d6:class-design/v/program-design-course-enrollment'),
 objectComposition:v('oV7lRiLg7_U','Object composition','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:building-software-with-classes/x5279a44ae0ab15d6:composition/v/object-composition'),
 algorithmicEfficiency:v('oYUzKAfrx0w','Algorithmic efficiency','/computing/computer-science/cryptography/comp-number-theory/v/algorithmic-efficiency'),
 dictionaryHashing:v('SOmCvHKmfYI','Dictionary hashing','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:analyzing-data-with-dictionaries/x5279a44ae0ab15d6:dictionaries/v/dictionary-hashing'),
 welcomeToTheWeb:v('jHPr-CuvHhs','Welcome to the web!','/computing/computer-programming/html-css/intro-to-html/v/making-webpages-intro'),
 cssZenGarden:v('yTOS61GFq0g','CSS Zen Garden','/computing/computer-programming/html-css/css-text-properties/v/css-zen-garden'),
 makingWebpagesInteractiveWithEvents:v('2pE7GUzW6-4','Making webpages interactive with events','/computing/computer-programming/html-css-js/html-js-dom-events/v/making-webpages-interactive-with-events'),
 welcomeToMakingWebpagesInteractive:v('c-szOdzJiWM','Welcome to making webpages interactive','/computing/computer-programming/html-css-js/html-css-js-intro/v/welcome-to-making-webpages-interactive'),
 whatIsJquery:v('T2mFyPxL-fU','What is jQuery?','/computing/computer-programming/html-js-jquery/jquery-intro/v/what-is-jquery'),
 htmlValidation:v('qrU3ghYJjEw','HTML validation','/computing/computer-programming/html-css/html-css-further-learning/v/html-validation'),
 datasetsAndDataStructures:v('WZQRJjeG6lo','Datasets and data structures','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:analyzing-data-with-dictionaries/x5279a44ae0ab15d6:dictionaries/v/datasets-and-data-structures'),
 accessingNestedData:v('ygDNNF1LEhI','Accessing nested data','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:analyzing-data-with-dictionaries/x5279a44ae0ab15d6:nested-data-structures/v/nested-data-access'),
 algorithmicBias:v('xYAdMDT2IyE','Algorithmic bias','/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:designing-algorithms-with-conditionals/x5279a44ae0ab15d6:nested-conditionals/v/algorithmic-bias'),
 startingWithParticles:v('MeQa3xMnAmw','Starting with particles','/computing/pixar/simulation/hair-simulation-code/v/particles'),
 springMassSystem:v('BXRIQHvU9Fs','Spring-mass system','/computing/pixar/simulation/hair-simulation-101/v/sim2-fix'),
 caseStudyTheGoodDinosaur:v('1EKs0YXIpUs','Case study: The Good Dinosaur','/computing/pixar/simulation/hair-simulation-101/v/video5-launch'),
 theBinaryNumberSystemAp:v('sXxwr66Y79Y','The binary number system | AP CSP','/computing/computers-and-internet/xcae6f4a7ff015e7d:digital-information/xcae6f4a7ff015e7d:binary-numbers/v/the-binary-number-system'),
 cpuMemoryInputOutput:v('MMzdKTtUIFM','CPU, memory, input & output','/computing/computers-and-internet/xcae6f4a7ff015e7d:computers/xcae6f4a7ff015e7d:computer-components/v/khan-academy-and-codeorg-cpu-memory-input-output'),
 ipAddressesAndDns:v('MwxMsaFFycg','IP addresses and DNS','/computing/computers-and-internet/xcae6f4a7ff015e7d:the-internet/xcae6f4a7ff015e7d:addressing-the-internet/v/the-internet-ip-addresses-and-dns'),
 packetsRoutersAndReliability:v('aD_yi5VjF78','Packets, routers, and reliability','/computing/computers-and-internet/xcae6f4a7ff015e7d:the-internet/xcae6f4a7ff015e7d:routing-with-redundancy/v/the-internet-packet-routers-and-reliability'),
 httpAndHtml:v('1K64fWX5z4U','HTTP and HTML','/computing/computers-and-internet/xcae6f4a7ff015e7d:the-internet/xcae6f4a7ff015e7d:web-protocols/v/the-internet-http-and-html'),
 compressionCodes:v('TxkA5UX4kis','Compression codes','/computing/computer-science/informationtheory/moderninfotheory/v/compressioncodes'),
 theCaesarCipher:v('sMOZf4GN3oc','The Caesar cipher','/computing/computer-science/cryptography/crypt/v/caesar-cipher'),
 theOneTimePad:v('FlIG3TvQCBQ','The one-time pad','/computing/computer-science/cryptography/crypt/v/one-time-pad'),
 theDiscreteLogarithmProblem:v('SL7J8hPKEWY','The discrete logarithm problem','/computing/computer-science/cryptography/modern-crypt/v/discrete-logarithm-problem'),
 rsaEncryptionStep1:v('EPXilYOa71c','RSA encryption: Step 1','/computing/computer-science/cryptography/modern-crypt/v/intro-to-rsa-encryption'),
 cybersecurityAndCrime:v('5k24We8pED8','Cybersecurity and crime','/computing/computers-and-internet/xcae6f4a7ff015e7d:online-data-security/xcae6f4a7ff015e7d:cyber-attacks/v/the-internet-cybersecurity-and-crime'),
 howNotToGetHacked:v('qLMIK5YVgfA','How Not To Get Hacked: Passwords','/computing/computers-and-internet/xcae6f4a7ff015e7d:online-data-security/xcae6f4a7ff015e7d:user-authentication-methods/v/how-not-to-get-hacked-passwords'),
 periodicTrendsAndCoulombS:v('gi2Y-kbrjCw','Periodic trends and Coulomb\'s law','/science/ap-chemistry-beta/x2eef969c74e0d802:atomic-structure-and-properties/x2eef969c74e0d802:periodic-trends/v/periodic-trends-and-coulombs-law'),
 vseprFor4ElectronClouds:v('ka8Yt4bTODs','VSEPR for 4 electron clouds','/science/ap-chemistry-beta/x2eef969c74e0d802:molecular-and-ionic-compound-structure-and-properties/x2eef969c74e0d802:vsepr/v/vsepr-for-4-electron-clouds'),
 solubilityAndIntermolecularForces:v('ccDKr4TIWfk','Solubility and intermolecular forces','/science/ap-chemistry-beta/x2eef969c74e0d802:intermolecular-forces-and-properties/x2eef969c74e0d802:solubility/v/solubility-and-intermolecular-forces'),
 calculatingAmountsOfReactantsAnd:v('9ujy3qfa7jI','Calculating amounts of reactants and products (worked example)','/science/ap-chemistry-beta/x2eef969c74e0d802:chemical-reactions/x2eef969c74e0d802:stoichiometry/v/worked-example-calculating-amounts-of-reactants-and-products'),
 introductionToReactionRates:v('8wIodo1HD4Y','Introduction to reaction rates','/science/ap-chemistry-beta/x2eef969c74e0d802:kinetics/x2eef969c74e0d802:reaction-rates/v/rate-of-reaction'),
 enthalpyOfReaction:v('cEzN33gfgVs','Enthalpy of reaction','/science/ap-chemistry-beta/x2eef969c74e0d802:thermodynamics/x2eef969c74e0d802:introduction-to-enthalpy-of-reaction/v/enthalpy-of-reaction'),
 resonanceStructures:v('7BgiKyvviyU','Resonance structures','/science/organic-chemistry/organic-structures/formal-charge-resonance/v/resonance-intro-jay'),
 functionalGroups2:v('FYTfo4y91TI','Functional groups','/science/organic-chemistry/bond-line-structures-alkanes-cycloalkanes/functional-groups/v/functional-groups-first'),
 introductionToChirality:v('tk-SNvCPLCE','Introduction to chirality','/science/organic-chemistry/stereochemistry-topic/chirality-r-s-system/v/introduction-to-chirality'),
 comparingE2E1Sn2Sn1:v('12Rvts2NR7M','Comparing E2, E1, Sn2, Sn1 reactions','/science/organic-chemistry/substitution-elimination-reactions/sn1-sn2-e1-e2-sal/v/comparing-e2-e1-sn2-sn1-reactions'),
 electrophilicAromaticSubstitution:v('fpq0eICjuSI','Electrophilic aromatic substitution','/science/organic-chemistry/aromatic-compounds/reactions-benzene/v/electrophilic-aromatic-substitution'),
 reactivityOfAldehydesAndKetones:v('BlBQBOb0OQ4','Reactivity of aldehydes and ketones','/science/organic-chemistry/aldehydes-ketones/nomenclature-aldehyde-ketone/v/reactivity-of-aldehydes-and-ketones'),
 fourLevelsOfProteinStructure:v('O5gN-IK6uKs','Four levels of protein structure','/test-prep/mcat/biomolecules/amino-acids-and-proteins1/v/four-levels-of-protein-structure'),
 anIntroductionToEnzymeKinetics:v('X_YXTWU2maY','An introduction to enzyme kinetics','/test-prep/mcat/biomolecules/enzyme-kinetics/v/an-introduction-to-enzyme-kinetics'),
 introductionToCarbohydrates:v('6o4WL5jlpn0','Introduction to carbohydrates','/science/biology/macromolecules/carbohydrates-and-sugars/v/introduction-to-carbohydrates'),
 metabolismOverviewAnabolismAndCatabolism:v('ST1UWnenOo0','Metabolism overview: anabolism and catabolism','/test-prep/mcat/biomolecules/overview-metabolism/v/overview-of-metabolism-anabolism-and-catabolism'),
 propertiesOfBuffers:v('tZH6zvQ8Wl8','Properties of buffers','/science/ap-chemistry-beta/x2eef969c74e0d802:acids-and-bases/x2eef969c74e0d802:buffers/v/properties-of-buffers'),
 basicsOfChromatography:v('SnbXQTTHGs4','Basics of chromatography','/test-prep/mcat/biomolecules/x04f6bc56:protein-analysis-techniques/v/basics-of-chromatography'),
 prokaryoticAndEukaryoticCells:v('xTnNv7YplSo','Prokaryotic and eukaryotic cells','/science/ap-biology/cell-structure-and-function/cell-compartmentalization-and-its-origins/v/prokaryotic-and-eukaryotic-cells'),
 introductionToPassiveAndActive:v('TsoAA7zOyj8','Introduction to passive and active transport','/science/ap-biology/cell-structure-and-function/membrane-transport/v/introduction-to-passive-and-active-transport'),
 cellularRespirationIntroduction:v('2f7YwCtHcgk','Cellular respiration introduction','/science/ap-biology/cellular-energetics/cellular-respiration-ap/v/introduction-to-cellular-respiration'),
 overviewOfCellSignaling:v('FQFBygnIONU','Overview of cell signaling','/science/ap-biology/cell-communication-and-cell-cycle/cell-communication/v/overview-of-cell-signaling'),
 regulationOfTranscription:v('ypH-hDKpCY0','Regulation of transcription','/science/ap-biology/gene-expression-and-regulation/regulation-of-gene-expression-and-cell-specialization/v/regulation-of-transcription'),
 introductionToGeneticEngineering:v('JNgONZ8Dq9I','Introduction to genetic engineering','/science/biology/biotech-dna-technology/intro-to-biotech-tutorial/v/introduction-to-genetic-engineering'),
 chromosomalCrossoverInMeiosisI:v('04gQ0bQu6xk','Chromosomal crossover in meiosis I','/science/ap-biology/heredity/meiosis-and-genetic-diversity/v/chromosomal-crossover-in-meiosis-i'),
 introductionToHeredity:v('eEUvRrhmcxM','Introduction to heredity','/science/ap-biology/heredity/mendelian-genetics-ap/v/introduction-to-heredity'),
 pedigrees:v('11s5Biyi9q4','Pedigrees','/science/ap-biology/heredity/mendelian-genetics-ap/v/pedigrees'),
 anIntroductionToGeneticMutations:v('g02RnGXCXrQ','An introduction to genetic mutations','/science/ap-biology/gene-expression-and-regulation/mutations-ap/v/an-introduction-to-genetic-mutations'),
 dnaReplicationAndRnaTranscription2:v('6gUY5NoX1Lk','DNA replication and RNA transcription and translation','/science/ap-biology/gene-expression-and-regulation/translation/v/rna-transcription-and-translation'),
 workedExamplePunnettSquares:v('D5ymMYcLtv0','Worked example: Punnett squares','/science/ap-biology/heredity/mendelian-genetics-ap/v/punnett-square-fun'),
 environmentalChangeAndAdaptationIn:v('0G2uDKYBX-c','Environmental change and adaptation in Galápagos finches','/science/ap-biology/natural-selection/speciation/v/environmental-change-and-adaptation-in-galapagos-finches'),
 speciation:v('gnku5AksWvU','Speciation','/science/ap-biology/natural-selection/speciation/v/allopatric-and-sympatric-speciation'),
 understandingAndBuildingPhylogeneticTrees:v('6_XMKmFQ_w8','Understanding and building phylogenetic trees','/science/ap-biology/natural-selection/phylogeny/v/understanding-and-building-phylogenetic-trees-or-cladograms'),
 exponentialAndLogisticGrowthIn:v('KyAKEisg2PQ','Exponential and logistic growth in populations','/science/ap-biology/ecology-ap/population-ecology-ap/v/exponential-and-logistic-growth-in-populations'),
 flowOfEnergyAndMatter:v('TitrRpMUt0I','Flow of energy and matter through ecosystems','/science/ap-biology/ecology-ap/energy-flow-through-ecosystems/v/flow-of-energy-and-matter-through-ecosystems'),
 humanActivitiesThatThreatenBiodiversity:v('2RC3Hsk90t8','Human activities that threaten biodiversity','/science/ap-biology/ecology-ap/disruptions-to-ecosystems/v/human-activities-that-threaten-biodiversity'),
 prokaryoticAndEukaryoticCells2:v('xTnNv7YplSo','Prokaryotic and eukaryotic cells','/science/biology/bacteria-archaea/prokaryote-structure/v/prokaryotic-and-eukaryotic-cells'),
 viralReplicationLyticVsLysogenic:v('J4BN4dARpio','Viral replication: lytic vs lysogenic','/science/health-and-medicine/infectious-diseases/x6e556f83:bacteria-and-viruses/v/viral-replicaiton-lytic-vs-lysogenic'),
 typesOfImmuneResponsesInnate:v('rp7T4IItbtM','Types of immune responses: Innate and adaptive, humoral vs. cell-mediated','/test-prep/mcat/organ-systems/the-immune-system/v/types-of-immune-responses-innate-and-adaptive-humoral-vs-cell-mediated'),
 whatIsTb:v('wV1pllyOaj8','What is TB?','/science/health-and-medicine/infectious-diseases/tuberculosis/v/what-is-tb'),
 drugResistantTb:v('vce3BZFo27Y','Drug-resistant TB','/science/health-and-medicine/infectious-diseases/tuberculosis/v/drug-resistant-tb'),
 homeostasis:v('rSBbnHLR_cg','Homeostasis','/science/ap-biology/cell-communication-and-cell-cycle/feedback/v/homeostasis'),
 meetTheLungs:v('qGiPZf7njqY','Meet the lungs!','/science/health-and-medicine/human-anatomy-and-physiology/lung-introduction/v/meet-the-lungs'),
 introductionToTheEndocrineSystem:v('f_Z1zsR9lFM','Introduction to the endocrine system','/science/health-and-medicine/advanced-endocrine-system/endocrine-system-introduction/v/intro-to-the-endocrine-system'),
 meetTheGastrointestinalTract:v('Oh_Pt_UrtEE','Meet the gastrointestinal tract!','/science/health-and-medicine/gastro-intestinal-system/gastrointestinal-intro/v/meet-the-gastrointestinal-tract'),
 skeletalStructureAndFunction:v('-lrKDRAbP38','Skeletal structure and function','/science/health-and-medicine/advanced-muscular-system/skeletal-system-introduction/v/skeletal-structure-and-function'),
 whatIsDiabetesMellitus:v('ulxyWZf7BWc','What is diabetes mellitus?','/science/health-and-medicine/advanced-endocrine-system/diabetes/v/what-is-diabetes-mellitus'),
 positionVelocityAndSpeed:v('vOipqtdR23s','Position, velocity, and speed','/science/ap-college-physics-1/xf557a762645cccc5:kinematics/xf557a762645cccc5:scalars-and-vectors-in-1d/v/position_velocity_speed'),
 forcesAndFreeBodyDiagrams:v('i447NWNpScM','Forces and free-body diagrams','/science/ap-college-physics-1/xf557a762645cccc5:force-and-translational-dynamics/xf557a762645cccc5:forces-and-systems/v/forces-and-free-body-diagrams'),
 workEnergyTheoremExample:v('BYkxKrbETb4','Work-energy theorem example','/science/ap-college-physics-1/xf557a762645cccc5:work-energy-and-power/xf557a762645cccc5:translational-kinetic-energy-and-work/v/work-energy-principle-example'),
 conservationOfLinearMomentum:v('zQLxbN8dxJg','Conservation of linear momentum','/science/ap-college-physics-1/xf557a762645cccc5:linear-momentum/xf557a762645cccc5:untitled-303/v/conservation-of-linear-momentum'),
 introToTorque:v('TQQXpFhACSU','Intro to torque','/science/ap-college-physics-1/xf557a762645cccc5:torque-and-rotational-dynamics/xf557a762645cccc5:torque/v/torque-basics'),
 shmOfSpringMassOscillators:v('eRZSzGKDfwU','SHM of spring-mass oscillators','/science/ap-college-physics-1/xf557a762645cccc5:oscillations/xf557a762645cccc5:spring-mass-oscillators/v/shm-of-spring-mass-oscillators'),
 electricPotential:v('Fj_G5tN84Eg','Electric potential','/science/ap-physics-2/x0e2f5a2c:electric-force-field-and-potential/electric-potential-energy-electric-potential-and-voltage/v/electric-potential'),
 capacitorsAndCapacitance:v('u-jigaMJT10','Capacitors and capacitance','/science/ap-physics-2/x0e2f5a2c:electric-circuits/x0e2f5a2c:circuits-with-capacitors/v/capacitors-and-capacitance'),
 seriesAndParallelCircuits:v('1ASc6piVKhQ','Series and parallel circuits','/science/ap-physics-2/x0e2f5a2c:electric-circuits/x0e2f5a2c:circuits-oms-kirchhoffs-laws/v/electric-circuits-part-2'),
 faradaySLaw:v('MHRBjGCgb4U','Faraday\'s Law','/science/ap-physics-2/x0e2f5a2c:magnetism-and-electromagnetism/x0e2f5a2c:electromagnetic-induction/v/faraday-s-law-n-t'),
 refractionAndSnellSLaw:v('y55tzg_jW9I','Refraction and Snell\'s law','/science/ap-physics-2/x0e2f5a2c:geometric-optics/x0e2f5a2c:refraction/v/refraction-and-snell-s-law'),
 thePhotoelectricAndPhotovoltaicEffects:v('HCCm0lFwqNw','The photoelectric and photovoltaic effects','/science/ap-physics-2/x0e2f5a2c:modern-physics/x0e2f5a2c:atoms-and-light/v/the_photoelectric_and_photovoltaic_effects'),
 thermalEnergyTemperatureAndHeat:v('-7Gl-yKF6Y4','Thermal energy, temperature, and heat','/science/ap-physics-2/x0e2f5a2c:thermodynamics/x0e2f5a2c:thermal-energy-and-thermal-equilibrium/v/thermal-energy-temperature-and-heat'),
 theIdealGasLawPv2:v('qObcdZj8YTM','The ideal gas law (PV = nRT)','/science/ap-physics-2/x0e2f5a2c:thermodynamics/x0e2f5a2c:gases/v/ideal-gas-equation-pv-nrt'),
 firstLawOfThermodynamicsEquation:v('u4-HYwo0Gsc','First law of thermodynamics equation','/science/ap-physics-2/x0e2f5a2c:thermodynamics/x0e2f5a2c:thermodynamic-processes/v/first-law-of-thermodynamics'),
 firstAndSecondLawsOf:v('f1OokOgtcqg','First and second laws of thermodynamics','/science/ap-physics-2/x0e2f5a2c:thermodynamics/x0e2f5a2c:thermal-energy-and-thermal-equilibrium/v/first-and-second-laws-of-thermodynamics'),
 introductionToGibbsFreeEnergy:v('_ikwCBn8wLE','Introduction to Gibbs free energy','/science/ap-chemistry-beta/x2eef969c74e0d802:applications-of-thermodynamics/x2eef969c74e0d802:gibbs-free-energy-and-thermodynamic-favorability/v/introduction-to-gibbs-free-energy'),
 hessSLaw:v('QU3zVec5I_M','Hess\'s law','/science/ap-chemistry-beta/x2eef969c74e0d802:thermodynamics/x2eef969c74e0d802:hess-s-law/v/hess-s-law-intro'),
 idealSources:v('CBlfcuUXzUY','Ideal sources','/science/electrical-engineering/ee-circuit-analysis-topic/circuit-elements/v/ee-ideal-sources'),
 kirchhoffSVoltageLaw:v('Bt6V7D5av9A','Kirchhoff\'s voltage law','/science/electrical-engineering/ee-circuit-analysis-topic/ee-dc-circuit-analysis/v/ee-kirchhoffs-voltage-law'),
 nodeVoltageMethodSteps1:v('2lY757QaaKs','Node voltage method (steps 1 to 4)','/science/electrical-engineering/ee-circuit-analysis-topic/ee-dc-circuit-analysis/v/ee-node-voltage-method-steps-1-to-4'),
 rcNaturalResponseIntuition:v('PZM6acXvsoQ','RC natural response - intuition','/science/electrical-engineering/ee-circuit-analysis-topic/ee-natural-and-forced-response/v/ee-rc-natural-response-intuition'),
 acAnalysisIntro1:v('7UJi2GQCi00','AC analysis intro 1','/science/electrical-engineering/ee-circuit-analysis-topic/ee-ac-analysis/v/ee-ac-analysis-intro1'),
 whatIsAnOperationalAmplifier:v('lJDjWZqhpVc','What is an operational amplifier?','/science/electrical-engineering/ee-amplifiers/ee-opamp/v/ee-opamp-intro'),
 introductionToMechanicalAdvantage:v('pfzJ-z5Ij48','Introduction to mechanical advantage','/test-prep/mcat/physical-processes/work-and-energy-mcat/v/introduction-to-mechanical-advantage'),
 puttingItAllTogetherPressure:v('F2uzWHppVrk','Putting it all together: Pressure, flow, and resistance','/test-prep/mcat/physical-processes/fluids-in-motion/v/putting-it-all-together-pressure-flow-and-resistance'),
 ultrasoundMedicalImaging:v('sTcqtljxLOk','Ultrasound medical imaging','/test-prep/mcat/physical-processes/sound/v/ultrasound-medical-imaging'),
 dioptersAberrationAndTheHuman:v('eji8zKa7H7s','Diopters, Aberration, and the Human Eye','/test-prep/mcat/physical-processes/thin-lenses/v/diopters-aberration-and-the-human-eye'),
 electricalSystemOfTheHeart:v('7K2icszdxQc','Electrical system of the heart','/science/health-and-medicine/circulatory-system/heart-depolarization/v/electrical-system-of-the-heart'),
 introToRadioactiveDecay:v('P_SD5Rt6XMk','Intro to radioactive decay','/science/ap-physics-2/x0e2f5a2c:modern-physics/x0e2f5a2c:nuclear-physics/v/intro-to-radioactive-decay'),
 theNitrogenCycle:v('DsCMYyQ0NWU','The nitrogen cycle','/science/ap-college-environmental-science/x0b0e430a38ebd23f:the-living-world-ecosystems-and-biodiversity/x0b0e430a38ebd23f:biogeochemical-cycles/v/nitrogen-cycle'),
 humanPopulationDynamics:v('jKfojKK-8Zk','Human population dynamics','/science/ap-college-environmental-science/x0b0e430a38ebd23f:populations/x0b0e430a38ebd23f:human-populations/v/human-population-dynamics'),
 tragedyOfTheCommons:v('0b2Tl0x-niw','Tragedy of the commons','/science/ap-college-environmental-science/x0b0e430a38ebd23f:land-and-water-use/x0b0e430a38ebd23f:intro-to-land-and-water-use/v/tragedy-of-the-commons'),
 renewableAndNonrenewableEnergyResources:v('G2lQFo69_hc','Renewable and nonrenewable energy resources','/science/ap-college-environmental-science/x0b0e430a38ebd23f:energy-resources-and-consumption/x0b0e430a38ebd23f:intro-to-energy-resources-and-consumption/v/renewable-and-nonrenewable-energy-resources'),
 pollutionAndHumanHealth:v('miaewHG2-X0','Pollution and human health','/science/ap-college-environmental-science/x0b0e430a38ebd23f:aquatic-and-terrestrial-pollution/x0b0e430a38ebd23f:pollution-and-health/v/pollution-and-human-health'),
 greenhouseEffectAndGreenhouseGases:v('YpfxiDktSoI','Greenhouse effect and greenhouse gases','/science/ap-college-environmental-science/x0b0e430a38ebd23f:global-change/x0b0e430a38ebd23f:greenhouse-effect/v/greenhouse-effect-and-greenhouse-gases'),
 scaleOfTheGalaxy:v('rcLnMe1ELPA','Scale of the galaxy','/science/cosmology-and-astronomy/universe-scale-topic/scale-earth-galaxy-tutorial/v/scale-of-the-galaxy'),
 birthOfStars:v('i-NNWI8Ccas','Birth of stars','/science/cosmology-and-astronomy/stellar-life-topic/stellar-life-death-tutorial/v/birth-of-stars'),
 blackHoles:v('JoL2pO3O0rg','Black holes','/science/cosmology-and-astronomy/stellar-life-topic/stellar-life-death-tutorial/v/black-holes'),
 bigBangIntroduction2:v('eUF59jCFcyQ','Big bang introduction','/science/cosmology-and-astronomy/universe-scale-topic/big-bang-expansion-topic/v/big-bang-introduction'),
 earthFormation:v('VbNXh0GaLYo','Earth formation','/science/cosmology-and-astronomy/life-earth-universe/history-life-earth-tutorial/v/earth-formation'),
 detectableCivilizationsInOurGalaxy:v('YYEgq1bweN4','Detectable civilizations in our galaxy 1','/science/cosmology-and-astronomy/life-earth-universe/life-in-universe-topic/v/detectable-civilizations-in-our-galaxy-1'),
 bottomUpVsTopDown:v('aJy5_p_LAhQ','Bottom-up vs. top-down processing','/test-prep/mcat/processing-the-environment/sensory-perception/v/bottom-up-versus-top-down-processing'),
 informationProcessingModelSensoryWorking:v('pMMRE4Q2FGk','Information processing model: Sensory, working, and long term memory','/test-prep/mcat/processing-the-environment/memory/v/information-processing-model-sensory-working-and-long-term-memory'),
 classicalConditioningNeutralConditionedAnd:v('-6KzZKuQ1lk','Classical conditioning: Neutral, conditioned, and unconditioned stimuli and responses','/test-prep/mcat/behavior/learning-slug/v/classical-conditioning-neutral-conditioned-and-unconditioned-stimuli-and-responses'),
 theoriesOfEmotion:v('FkDVucEoJpU','Theories of Emotion','/test-prep/mcat/processing-the-environment/emotion/v/theories-of-emotion'),
 traitTheory:v('Hxk6GCKUiZI','Trait theory','/test-prep/mcat/behavior/theories-personality/v/trait-theory'),
 introductionToMentalDisorders:v('FxPXC8t-2ls','Introduction to mental disorders','/test-prep/mcat/behavior/psychological-disorders/v/introduction-to-mental-disorders'),
 overviewOfNeuronFunction:v('BY8DJeX_tGc','Overview of neuron function','/science/health-and-medicine/nervous-system-and-sensory-infor/nervous-system-introduction-ddp/v/overview-of-neuron-function'),
 overviewOfTheFunctionsOf:v('X-m0JDCw6TE','Overview of the functions of the cerebral cortex','/test-prep/mcat/behavior/biological-basis-of-behavior-ner/v/overview-of-the-functions-of-the-cerebral-cortex'),
 sleepStagesAndCircadianRhythms:v('fNlp0UMqUtM','Sleep stages and circadian rhythms','/test-prep/mcat/processing-the-environment/sleep-and-consciousness/v/sleep-stages-and-circadian-rhythms'),
 rewardPathwayInTheBrain:v('YzCYuKX6zp8','Reward pathway in the brain','/test-prep/mcat/processing-the-environment/drug-dependence/v/reward-pathway-in-the-brain'),
 physicalEffectsOfStress:v('oUqJ-AKSsuE','Physical effects of stress','/test-prep/mcat/processing-the-environment/stress/v/physical-effects-of-stress'),
 treatmentsForDepressionPsychologicalTherapies:v('DKXAHh9PZJQ','Treatments for depression - Psychological therapies','/science/health-and-medicine/executive-systems-of-the-brain/depression-and-related-disorders/v/treatments-for-depression-psychological-therapies'),
 overviewOfTheoriesOfDevelopment:v('WMv8A9qg6jY','Overview of theories of development','/test-prep/mcat/individuals-and-society/self-identity/v/overview-of-theories-of-development'),
 vygotskySocioculturalDevelopment:v('-p_-0n2f35o','Vygotsky sociocultural development','/test-prep/mcat/individuals-and-society/self-identity/v/vygotsky-sociocultural-development'),
 theoriesOfLanguageAndCognition:v('RgvmKfvCwps','Theories of language and cognition','/test-prep/mcat/processing-the-environment/language/v/language-and-cognition'),
 problemSolving:v('J3GGx9wy07w','Problem solving','/test-prep/mcat/processing-the-environment/cognition/v/problem-solving'),
 theoriesOfIntelligence:v('oaJ01Ex7DLw','Theories of intelligence','/test-prep/mcat/processing-the-environment/cognition/v/theories-of-intelligence'),
 eriksonSStagesOfPsychosocial:v('SIoKwUcmivk','Erikson\'s stages of psychosocial development','/test-prep/mcat/individuals-and-society/self-identity/v/eriksons-psychosocial-development'),
 selfEsteemSelfEfficacyAnd:v('xcLKlPTG97k','Self esteem, self efficacy, and locus of control','/test-prep/mcat/individuals-and-society/self-identity/v/self-esteem-self-efficacy-and-locus-of-control'),
 attributionTheoryBasicCovariation:v('nB2ZRHS2RUE','Attribution Theory - Basic covariation','/test-prep/mcat/individuals-and-society/perception-prejudice-and-bias/v/attribution-theory-basic-covariation'),
 persuasionAttitudeChangeAndThe:v('o6oyCeYQWPE','Persuasion, attitude change, and the elaboration likelihood model','/test-prep/mcat/behavior/theories-of-attitude-and-behavior-change/v/persuasion-attitude-change-and-the-elaboration-likelihood-model'),
 conformityAndObedience:v('Loy1zLkbuF0','Conformity and obedience','/test-prep/mcat/behavior/social-psychology/v/conformity-and-obedience'),
 prejudiceVsDiscrimination:v('Lto6oQcGF_8','Prejudice vs discrimination','/test-prep/mcat/individuals-and-society/social-interactions/v/prejudice-vs-discrimination'),
 altruism:v('ZgJHEp7XwAs','Altruism','/test-prep/mcat/individuals-and-society/social-behavior/v/altruism'),
 socialTheoriesOverviewPart1:v('KpaLchFpJZ8','Social theories overview (part 1)','/test-prep/mcat/society-and-culture/social-structures/v/social-theories-overview'),
 socialInstitutions:v('9KR1bad76qg','Social institutions','/test-prep/mcat/society-and-culture/social-structures/v/institutions'),
 overviewOfCulture:v('Vo6W4kDv0cA','Overview of culture','/test-prep/mcat/society-and-culture/culture/v/overview-of-culture'),
 demographicTransition:v('6P2bsPWCRvM','Demographic transition','/test-prep/mcat/society-and-culture/demographics/v/demographic-transition'),
 upwardAndDownwardMobilityMeritocracy:v('khRX1Oo93AY','Upward and downward mobility, meritocracy','/test-prep/mcat/social-inequality/social-class/v/upward-and-downward-mobility-meritocracy'),
 healthAndHealthcareDisparitiesIn:v('7qAld9bGwlA','Health and healthcare disparities in the US','/test-prep/mcat/social-inequality/social-class/v/health-and-healthcare-disparities-in-the-us'),
 frenchRevolutionPart1:v('BDWqwcTtZa0','French Revolution (part 1)','/humanities/world-history/x66f79d8a:the-long-nineteenth-century/x66f79d8a:atlantic-revolutions-7-3/v/french-revolution-part-1'),
 industrializationAndImperialism:v('fUDwPz9VmL0','Industrialization and imperialism','/humanities/world-history/x66f79d8a:the-long-nineteenth-century/x66f79d8a:industrial-imperialism-7-9/v/industrialization-and-imperialism'),
 whatWasTheColdWar:v('py0bazbFt6c','What Was the Cold War?','/humanities/world-history/x66f79d8a:global-conflict/x66f79d8a:the-cold-war-8-8/v/what-was-the-cold-war'),
 independenceMovementsInThe20th:v('8xIA10NQakI','Independence movements in the 20th Century','/humanities/world-history/x66f79d8a:global-conflict/x66f79d8a:decolonization-8-9/v/independence-movements-in-the-20th-century'),
 globalizationITheUpside:v('5SnR-e0S6Ic','Globalization I: The Upside','/humanities/world-history/x66f79d8a:globalization/x66f79d8a:is-globalization-good-or-bad-9-2/v/globalization-i-the-upside-crash-course-world-history-41-beta'),
 internationalHumanRights:v('5CZ0oZ_lXSY','International Human Rights','/humanities/world-history/x66f79d8a:globalization/x66f79d8a:global-communities-9-5/v/international-human-rights'),
};

/** UPCAT outline topics by their exact title in EXAM_OUTLINES.upcat. */
export const UPCAT_TOPIC_VIDEOS:Record<string,KhanVideo>={
 'Word meaning from context clues':T.usingContextCluesToFigure,
 'Roots, prefixes and suffixes':T.latinAndGreekRootsAnd,
 'Commonly confused words':Q.affectEffect,
 'Idioms and figurative expressions':T.figurativeLanguage,
 'Parts of speech':T.introductionToGrammar,
 'Subject-verb agreement':Q.agreement,
 'Verb tenses and forms':T.introductionToVerbTense,
 'Pronoun case and agreement':Q.subjectObjectPronouns,
 'Adjectives and adverbs':T.whatIsAnAdverbIntro,
 'Prepositions and articles':T.meetThePreposition,
 'Punctuation and capitalization':T.meetTheComma,
 'Fragments and run-on sentences':T.runOnsAndCommaSplices,
 'Misplaced and dangling modifiers':T.danglingModifiers,
 'Parallel structure':T.parallelStructure,
 'Combining and ordering sentences':T.simpleAndCompoundSentences,
 'Direct and reported speech':T.commasInDialogue,
 'Main idea and best title':Q.centralIdeas,
 'Stated details':Q.centralIdeas,
 'Sequence of events':T.theStructuresOfInformationalTexts,
 'Fact and opinion':T.factOrOpinionWorkedExample,
 'Inferences and conclusions':Q.inferences,
 'Cause and effect':T.theStructuresOfInformationalTexts,
 'Word meaning in a passage':Q.wordsInContext,
 'Purpose and point of view':T.analyzingAnAuthorSPurpose,
 'Tone and mood':T.analyzingToneThroughWordChoice,
 'How the passage is organized':Q.textStructure,
 'Figurative language in a passage':T.figurativeLanguage,
 'Essays and articles':T.whatIsAnArgument,
 'Short stories':T.theElementsOfAStory,
 'Poems':T.theElementsOfAPoem,
 'Tables, graphs and diagrams':T.quantitativeInformationInTexts,
 'The real number system':T.introToRationalIrrationalNumbers,
 'Integers and the order of operations':T.introToOrderOfOperations,
 'Factors, multiples and divisibility':T.commonFactorsAndCommonMultiples,
 'Fractions and decimals':Q.fractionsAdd,
 'Percent':T.solvingPercentProblems,
 'Ratio and proportion':Q.ratioPart,
 'Algebraic expressions and laws of exponents':Q.exponentProducts,
 'Polynomials, special products and factoring':T.perfectSquareFactorizationIntro,
 'Rational expressions':T.reducingRationalExpressionsToLowest,
 'Radicals':T.simplifyingSquareRootExpressionsNo,
 'Linear equations and inequalities':Q.twoStep,
 'Systems of linear equations':T.systemsOfEquationsWithSubstitution,
 'Quadratic equations':T.theQuadraticFormulaAlgebra,
 'Functions and their graphs':Q.evaluateFunction,
 'The coordinate plane, lines and slope':Q.slope,
 'Exponents and logarithms':T.relationshipBetweenExponentialsLogarithms,
 'Sequences and series':T.arithmeticSeriesIntro,
 'Word problems':Q.averageSpeed,
 'Lines, angles and their properties':T.anglesParallelLinesTransversals,
 'Triangles, congruence and similarity':T.introToTriangleSimilarity,
 'Right triangles and the Pythagorean theorem':Q.pythagoras,
 'Perimeter and area of plane figures':Q.triangleArea,
 'Circles':Q.circleArea,
 'Surface area and volume of solids':T.cylinderVolumeSurfaceArea,
 'Converting units of measurement':T.conversionBetweenMetricUnits,
 'The six trigonometric ratios':Q.trigRatios,
 'Special angles and the unit circle':T.unitCircle,
 'Angles of elevation and depression':T.introToHeightsAndDistances,
 'Mean, median and mode':T.statisticsIntroMeanMedianMode,
 'Permutations and combinations':T.permutationFormula,
 'Probability of events':T.compoundProbabilityOfIndependentEvents,
 'Reading tables and graphs':T.readingBarGraphsMovies,
 'Propositions and truth tables':T.conditionalStatementsAndLogicalEquivalence,
 'Limits':T.introducingLimits,
 'Simple derivatives and integrals':T.derivativeTheDirectionOfA,
 'Characteristics of life and the scientific method':T.theScientificMethod,
 'Biomolecules':T.introductionToBiomolecules,
 'Cell structure and transport':T.passiveTransportAndSelectivePermeability,
 'Photosynthesis and cellular respiration':Q.photosynthesis,
 'Mitosis and meiosis':T.comparingMitosisAndMeiosis,
 'DNA, RNA and protein synthesis':T.dnaReplicationAndRnaTranscription,
 'Inheritance and Punnett squares':Q.punnett,
 'Evolution and natural selection':T.introductionToEvolutionAndNatural,
 'Classification and biodiversity':T.taxonomyAndTheTreeOf,
 'Human body systems':T.circulatorySystemAndTheHeart,
 'Plant structure and function':T.xylemTranspiration,
 'Ecosystems and energy flow':T.energyFlowInFoodChains,
 'Matter, its properties and changes':T.physicalAndChemicalChanges,
 'Atomic structure':T.protonsNeutronsAndElectronsIn,
 'The periodic table and periodic trends':T.atomicRadiusTrendsOnPeriodic,
 'Chemical bonding and naming compounds':T.namingIonsAndIonicCompounds,
 'Formulas, molar mass and the mole':Q.moles,
 'Chemical reactions and balancing equations':T.balancingChemicalEquations,
 'Stoichiometry':T.stoichiometryMassToMassAnd,
 'Gas laws':T.theIdealGasLawPv,
 'Solutions and concentration':Q.molarity,
 'Acids, bases and pH':Q.ph,
 'Reaction rates and equilibrium':T.factorsAffectingReactionRates,
 'Heat in chemical reactions':T.exothermicAndEndothermicReactions,
 'Carbon compounds and biochemistry':T.functionalGroups,
 'Measurement, units and density':Q.density,
 'Scalars and vectors':T.introToVectorsAndScalars,
 'Speed, velocity and acceleration':Q.speed,
 'Newton’s laws and friction':Q.newtonSecond,
 'Projectile motion':T.projectileMotion,
 'Work, energy and power':Q.work,
 'Momentum and impulse':T.impulseAndMomentumExample,
 'Pressure and buoyancy in fluids':T.archimedesPrincipleAndBuoyantForce,
 'Heat and temperature':Q.specificHeat,
 'Waves and sound':Q.waves,
 'Light, mirrors and lenses':T.convexLenses,
 'Electric circuits':Q.ohm,
 'Magnetism and electromagnetism':T.electromagneticInduction,
 'Radioactivity and half-life':Q.halfLife,
 'Earth’s layers and composition':Q.earthLayers,
 'Rocks and minerals':Q.rockCycle,
 'Plate tectonics, earthquakes and volcanoes':Q.convergentBoundaries,
 'Weathering, erosion and landforms':Q.weathering,
 'Fossils and the geologic time scale':T.watchIntroductionToTheGeologic,
 'Weather, climate and the atmosphere':T.theSunSEnergyAnd,
 'The solar system and its planets':Q.solarSystem,
 'Earth’s rotation, revolution and the seasons':Q.seasons,
 'Phases of the Moon and eclipses':T.introToMoonPhases,
 'Stars and constellations':T.constellations,
 'The origin of the universe':T.bigBangIntroduction,
};
/** UPCAT topics searched on Khan Academy with no fitting video. */
export const UPCAT_NO_VIDEO:ReadonlySet<string>=new Set(['Synonyms and antonyms','Spelling','Active and passive voice','Ng at nang, din at rin, at iba pang madalas mapagpalit','Aspekto ng pandiwa','Pokus ng pandiwa','Panghalip','Pang-ugnay: pangatnig at pang-ukol','Wastong baybay at bantas','Kahulugan ayon sa konteksto','Kasingkahulugan at kasalungat','Sawikain at idyoma','Salawikain at tayutay','Speeches']);

/** College subject topics by subject id, then by the topic's exact text in SUBJECTS. */
export const SUBJECT_TOPIC_VIDEOS:Record<string,Record<string,KhanVideo>>={
 calculus1:{'Limits and continuity':T.exploringContinuityAtAPoint,'The derivative as a rate of change':T.exploringDerivativesAsAConcept,'Power, product, quotient and chain rules':T.exploringThePowerRule,'Implicit differentiation and related rates':T.implicitDifferentiationExampleWalkthrough,'Optimisation and curve sketching':T.applyingOptimizationBoxVolumePart,'Antiderivatives and the definite integral':T.exploringAntiderivativesAndIndefiniteIntegrals},
 calculus2:{'Substitution and integration by parts':T.integrationByPartsIntro,'Partial fractions and improper integrals':T.integrationWithPartialFractions,'Areas, volumes and arc length':T.calculatingTheAreaBetweenCurves,'Separable differential equations':T.separableEquationsIntroductionDifferentialEquations,'Parametric and polar curves':T.parametricEquationsIntro,'Sequences, series and Taylor polynomials':T.taylorMaclaurinSeriesFormulaIntro},
 multivariable:{'Functions of several variables':T.introductionTo3dGraphs,'Partial derivatives and the gradient':T.partialDerivativesIntroduction,'Tangent planes and linear approximation':T.whatIsATangentPlane,'Optimisation and Lagrange multipliers':T.constrainedOptimizationIntroduction,'Double and triple integrals':T.doubleIntegral1,'Line integrals and the theorems of Green and Stokes':T.introductionToTheLineIntegral},
 diffeq:{'Modelling with differential equations':T.writingADifferentialEquation,'Slope fields and Euler’s method':T.slopeFieldsIntroductionDifferentialEquations,'Separable and first-order linear equations':T.integratingFactors1,'Second-order linear equations':T.v2ndOrderLinearHomogeneousDifferential,'Oscillation and damping':T.complexRootsOfTheCharacteristic,'The Laplace transform':T.laplaceTransformIntroDifferentialEquations},
 linear_algebra:{'Vectors, span and linear independence':T.linearCombinationsAndSpan,'Matrices and matrix operations':T.matrixProductExamples,'Solving systems by row reduction':T.solvingLinearSystemsWithMatrices,'Determinants and inverses':T.formulaFor2x2Inverse,'Linear transformations':T.linearTransformations,'Bases, eigenvalues and eigenvectors':T.introductionToEigenvaluesAndEigenvectors},
 precalculus:{'Composite and inverse functions':T.introToInverseFunctions,'Exponential and logarithmic functions':T.introToLogarithms,'Trigonometric functions and identities':T.trigAngleAdditionIdentities,'Complex numbers':T.polarRectangularFormsOfComplex,'Conic sections':T.introToConicSections,'Sequences and series':T.geometricSeriesIntroduction},
 discrete:{'Logic, sets and proof':T.conditionalStatementsAndLogicalEquivalence,'Counting, permutations and combinations':T.introToCombinations,'Probability for computing':T.randomizedAlgorithmsIntro,'Modular arithmetic and primes':T.theFundamentalTheoremOfArithmetic},
 describing_data:{'Displaying categorical and quantitative data':T.representingData,'Centre, spread and shape':T.measuresOfSpreadRangeVariance,'Percentiles and z-scores':T.zScoreIntroduction,'Density curves and normal models':T.densityCurves,'Comparing distributions':T.exampleComparingDistributions,'Reporting data without misleading':T.misleadingLineGraphs},
 probability:{'Probability rules and conditional probability':T.calculatingConditionalProbability,'Counting methods':T.countOutcomesUsingTreeDiagram,'Discrete and continuous random variables':T.discreteAndContinuousRandomVariables,'Binomial and geometric distributions':T.binomialDistribution,'Expected value and variance':T.meanExpectedValueOfA,'The normal distribution':T.normalDistributionProblemsEmpiricalRule},
 study_design:{'Statistical questions':T.statisticalQuestions,'Sampling methods and bias':T.techniquesForRandomSamplingAnd,'Observational studies and experiments':T.typesOfStatisticalStudies,'Random assignment and control groups':T.introductionToExperimentDesign},
 inference:{'Sampling distributions and the central limit theorem':T.centralLimitTheorem,'Confidence intervals for proportions and means':T.exampleConstructingAndInterpretingA,'Significance tests and P-values':T.pValuesAndSignificanceTests,'Type I and type II errors':T.introductionToTypeIAnd,'Comparing two groups':T.hypothesisTestForDifferenceOf,'Chi-square tests':T.pearsonSChiSquareTest},
 regression:{'Scatterplots and correlation':T.bivariateRelationshipLinearityStrengthAnd,'Least-squares regression lines':T.introductionToResidualsAndLeast,'Residuals and model fit':T.residualPlots,'Inference for the slope':T.introductionToInferenceAboutSlope,'Transforming non-linear data':T.transformingNonlinearData,'Prediction and its limits':T.estimatingWithLinearRegressionLinear},
 anova:{'Comparing several group means':T.anova1CalculatingSstTotal,'Sums of squares within and between groups':T.anova2CalculatingSswAnd,'The F statistic':T.anova3HypothesisTestWith},
 python:{'Variables, expressions and tracing':T.variablesAndAssignment,'Conditionals and Boolean logic':T.ifStatements,'Loops and simulation':T.whileLoops,'Functions and decomposition':T.functions,'Lists':T.lists,'Debugging and testing':T.debuggingWithTestCases},
 javascript:{'Debugging':T.debuggingWebpagesWithTheBrowser},
 oop:{'Classes and objects':T.classesAndObjects,'Attributes and methods':T.methodsAndEncapsulation,'Encapsulation and abstraction':T.softwareAndAbstraction,'Designing classes for a program':T.programDesignCourseEnrollment,'Building a larger project':T.objectComposition},
 algorithms:{'Asymptotic notation and Big-O':T.algorithmicEfficiency,'Lists, dictionaries and hashing':T.dictionaryHashing},
 web_dev:{'HTML structure and meaning':T.welcomeToTheWeb,'CSS styling and layout':T.cssZenGarden,'The DOM and events':T.makingWebpagesInteractiveWithEvents,'Interactive pages with JavaScript':T.welcomeToMakingWebpagesInteractive,'Using a library such as jQuery':T.whatIsJquery,'Accessibility and validation':T.htmlValidation},
 databases:{},
 data_analysis:{'Datasets and data structures':T.datasetsAndDataStructures,'Dictionaries and nested data':T.accessingNestedData,'Bias and privacy in data':T.algorithmicBias},
 graphics:{'Oscillation and particle systems':T.startingWithParticles,'Spring and mass systems':T.springMassSystem,'Physics-based animation':T.caseStudyTheGoodDinosaur},
 systems:{'Bits, bytes and binary':T.theBinaryNumberSystemAp,'How a computer is built':T.cpuMemoryInputOutput,'Networks, IP addresses and DNS':T.ipAddressesAndDns,'Packets, routing and reliability':T.packetsRoutersAndReliability,'HTTP and the web':T.httpAndHtml,'Compression and information':T.compressionCodes},
 security:{'Classical ciphers':T.theCaesarCipher,'Perfect secrecy and the one-time pad':T.theOneTimePad,'Modular arithmetic and primes':T.theDiscreteLogarithmProblem,'Public-key cryptography and RSA':T.rsaEncryptionStep1,'Online data security':T.cybersecurityAndCrime,'Protecting personal data':T.howNotToGetHacked},
 gen_chem:{'Atomic structure and periodic trends':T.periodicTrendsAndCoulombS,'Bonding and molecular shape':T.vseprFor4ElectronClouds,'Intermolecular forces and solutions':T.solubilityAndIntermolecularForces,'Reactions and stoichiometry':T.calculatingAmountsOfReactantsAnd,'Kinetics and equilibrium':T.introductionToReactionRates,'Thermodynamics, acids and bases':T.enthalpyOfReaction},
 organic_chem:{'Bonding, hybridisation and resonance':T.resonanceStructures,'Functional groups and naming':T.functionalGroups2,'Stereochemistry':T.introductionToChirality,'Substitution and elimination':T.comparingE2E1Sn2Sn1,'Aromatic compounds':T.electrophilicAromaticSubstitution,'Carbonyl chemistry and spectroscopy':T.reactivityOfAldehydesAndKetones},
 biochemistry:{'Amino acids and protein structure':T.fourLevelsOfProteinStructure,'Enzymes and their kinetics':T.anIntroductionToEnzymeKinetics,'Carbohydrates, lipids and nucleic acids':T.introductionToCarbohydrates,'Metabolism and cellular energy':T.metabolismOverviewAnabolismAndCatabolism,'Water, pH and buffers':T.propertiesOfBuffers,'Laboratory techniques':T.basicsOfChromatography},
 cell_bio:{'Cell structure and organelles':T.prokaryoticAndEukaryoticCells,'Membranes and transport':T.introductionToPassiveAndActive,'Respiration and photosynthesis':T.cellularRespirationIntroduction,'Cell signalling and the cell cycle':T.overviewOfCellSignaling,'Gene expression and regulation':T.regulationOfTranscription,'Biotechnology':T.introductionToGeneticEngineering},
 genetics:{'Meiosis and genetic diversity':T.chromosomalCrossoverInMeiosisI,'Mendelian inheritance':T.introductionToHeredity,'Linked genes and pedigrees':T.pedigrees,'Mutations and chromosomes':T.anIntroductionToGeneticMutations,'DNA to RNA to protein':T.dnaReplicationAndRnaTranscription2,'Probability in genetic crosses':T.workedExamplePunnettSquares},
 evolution_ecology:{'Natural selection and adaptation':T.environmentalChangeAndAdaptationIn,'Population genetics and speciation':T.speciation,'The tree of life':T.understandingAndBuildingPhylogeneticTrees,'Population growth':T.exponentialAndLogisticGrowthIn,'Communities and ecosystems':T.flowOfEnergyAndMatter,'Biodiversity and conservation':T.humanActivitiesThatThreatenBiodiversity},
 microbiology:{'Prokaryote structure':T.prokaryoticAndEukaryoticCells2,'Viruses and how they replicate':T.viralReplicationLyticVsLysogenic,'The immune response':T.typesOfImmuneResponsesInnate,'Infectious diseases':T.whatIsTb,'Antibiotics and resistance':T.drugResistantTb},
 anatomy:{'Body organisation and homeostasis':T.homeostasis,'Circulatory and respiratory systems':T.meetTheLungs,'Nervous and endocrine systems':T.introductionToTheEndocrineSystem,'Digestive system':T.meetTheGastrointestinalTract,'Musculoskeletal system':T.skeletalStructureAndFunction,'How the systems fail in disease':T.whatIsDiabetesMellitus},
 physics_mechanics:{'Kinematics in one and two dimensions':T.positionVelocityAndSpeed,'Newton’s laws and free-body diagrams':T.forcesAndFreeBodyDiagrams,'Work, energy and power':T.workEnergyTheoremExample,'Momentum and collisions':T.conservationOfLinearMomentum,'Rotation and torque':T.introToTorque,'Oscillations':T.shmOfSpringMassOscillators},
 physics_em:{'Electric charge, field and potential':T.electricPotential,'Capacitance and current':T.capacitorsAndCapacitance,'Direct-current circuits':T.seriesAndParallelCircuits,'Magnetism and induction':T.faradaySLaw,'Geometric and wave optics':T.refractionAndSnellSLaw,'Modern physics':T.thePhotoelectricAndPhotovoltaicEffects},
 thermodynamics:{'Temperature and heat':T.thermalEnergyTemperatureAndHeat,'Ideal gases and kinetic theory':T.theIdealGasLawPv2,'The first law':T.firstLawOfThermodynamicsEquation,'Heat engines and the second law':T.firstAndSecondLawsOf,'Entropy and free energy':T.introductionToGibbsFreeEnergy,'Thermochemistry':T.hessSLaw},
 circuits:{'Circuit elements and sources':T.idealSources,'Ohm’s and Kirchhoff’s laws':T.kirchhoffSVoltageLaw,'Node and mesh analysis':T.nodeVoltageMethodSteps1,'Capacitors, inductors and transients':T.rcNaturalResponseIntuition,'AC analysis':T.acAnalysisIntro1,'Diodes, transistors and amplifiers':T.whatIsAnOperationalAmplifier},
 health_physics:{'Forces and motion in the body':T.introductionToMechanicalAdvantage,'Fluids, pressure and blood flow':T.puttingItAllTogetherPressure,'Waves, sound and ultrasound':T.ultrasoundMedicalImaging,'Light, lenses and the eye':T.dioptersAberrationAndTheHuman,'Electricity in nerves and the heart':T.electricalSystemOfTheHeart,'Radiation and imaging':T.introToRadioactiveDecay},
 environmental:{'Ecosystems and biogeochemical cycles':T.theNitrogenCycle,'Populations and resources':T.humanPopulationDynamics,'Land and water use':T.tragedyOfTheCommons,'Energy resources':T.renewableAndNonrenewableEnergyResources,'Air, water and soil pollution':T.pollutionAndHumanHealth,'Global climate change':T.greenhouseEffectAndGreenhouseGases},
 astronomy:{'The scale of the universe':T.scaleOfTheGalaxy,'Stars and their life cycles':T.birthOfStars,'Black holes and galaxies':T.blackHoles,'The Big Bang and cosmic time':T.bigBangIntroduction2,'The Earth’s geological history':T.earthFormation,'Life in the universe':T.detectableCivilizationsInOurGalaxy},
 psychology:{'Sensation and perception':T.bottomUpVsTopDown,'Attention, memory and cognition':T.informationProcessingModelSensoryWorking,'Learning and conditioning':T.classicalConditioningNeutralConditionedAnd,'Motivation and emotion':T.theoriesOfEmotion,'Personality':T.traitTheory,'Psychological disorders':T.introductionToMentalDisorders},
 biopsych:{'Neurons and the nervous system':T.overviewOfNeuronFunction,'Brain structure and function':T.overviewOfTheFunctionsOf,'Sleep and consciousness':T.sleepStagesAndCircadianRhythms,'Drugs and the brain':T.rewardPathwayInTheBrain,'Stress and health':T.physicalEffectsOfStress,'Mental health and treatment':T.treatmentsForDepressionPsychologicalTherapies},
 development:{'Theories of development':T.overviewOfTheoriesOfDevelopment,'Cognitive development':T.vygotskySocioculturalDevelopment,'Language and thought':T.theoriesOfLanguageAndCognition,'Problem solving and decision making':T.problemSolving,'Intelligence':T.theoriesOfIntelligence,'Identity across the life span':T.eriksonSStagesOfPsychosocial},
 social_psych:{'Self-concept and identity':T.selfEsteemSelfEfficacyAnd,'Attribution and social perception':T.attributionTheoryBasicCovariation,'Attitudes and persuasion':T.persuasionAttitudeChangeAndThe,'Conformity, obedience and groups':T.conformityAndObedience,'Prejudice and discrimination':T.prejudiceVsDiscrimination,'Helping and aggression':T.altruism},
 sociology:{'Sociological perspectives':T.socialTheoriesOverviewPart1,'Social structure and institutions':T.socialInstitutions,'Culture and socialisation':T.overviewOfCulture,'Demographics and social change':T.demographicTransition,'Social class and mobility':T.upwardAndDownwardMobilityMeritocracy,'Health and inequality':T.healthAndHealthcareDisparitiesIn},
 world_history:{'Revolutions and the long nineteenth century':T.frenchRevolutionPart1,'Industrialisation and empire':T.industrializationAndImperialism,'The world wars and the Cold War':T.whatWasTheColdWar,'Decolonisation':T.independenceMovementsInThe20th,'Globalisation':T.globalizationITheUpside,'Human rights and global communities':T.internationalHumanRights},
};
/** Subject topics searched in the subject's own Khan units and on Khan's search with no fitting video. */
export const SUBJECT_NO_VIDEO:Record<string,readonly string[]>={
 discrete:['Recursion and induction','Graphs and trees'],
 study_design:['Collecting data ethically','Reading a methods section'],
 anova:['Assumptions and conditions','Following up a significant result'],
 javascript:['Drawing and animating with code','Variables and functions','Logic and if statements','Loops and arrays','Objects and object-oriented design'],
 oop:['Inheritance and polymorphism'],
 algorithms:['Linear and binary search','Selection, insertion, merge and quick sort','Recursion','Graphs and breadth-first search'],
 databases:['Tables, rows and keys','Querying with SELECT and WHERE','Aggregating and grouping','Joining related tables','Changing data safely','Designing a database'],
 data_analysis:['Cleaning and filtering data','Summarising and visualising','Drawing conclusions from data'],
 graphics:['Vectors and forces in code','Randomness and noise','Simulation as a scientific tool'],
 microbiology:['Bacterial growth and genetics'],
};

const own=<V,>(map:Record<string,V>,key:string|undefined)=>key!==undefined&&Object.hasOwn(map,key)?map[key]:undefined;
const BY_EXAM:Partial<Record<ExamId,Record<string,KhanVideo>>>={upcat:UPCAT_TOPIC_VIDEOS};

/** The Khan video for one reviewer outline topic, or undefined. Only the UPCAT outline is mapped. */
export const outlineVideo=(exam:ExamId,title:string)=>own(BY_EXAM[exam]??{},title);
/** The Khan video for one college subject topic, or undefined. */
export const subjectTopicVideo=(subject:string,topic:string)=>own(own(SUBJECT_TOPIC_VIDEOS,subject)??{},topic);
/** The UPCAT topics a reviewer summary teaches, each with its video, one row per distinct video. */
export function conceptVideos(concept:string):{topic:string;video:KhanVideo}[]{
 const seen=new Set<string>(),out:{topic:string;video:KhanVideo}[]=[];
 for(const groups of Object.values(EXAM_OUTLINES.upcat?.sections??{}))for(const g of groups)for(const t of g.topics){
  const video=t.concepts?.includes(concept)?UPCAT_TOPIC_VIDEOS[t.title]:undefined;
  if(video&&!seen.has(video.id)){seen.add(video.id);out.push({topic:t.title,video});}
 }
 return out;
}
