import {initialRecovery, type Topic, type Skill} from './recovery.ts';
import {khanMaterial} from './khan-materials.ts';
import {khanEntry} from './khan-entry.ts';

export type ExploreGroup='numbers'|'algebra'|'graphs';
export type ExploreScene='mixture'|'fractions'|'distribution'|'factors'|'roots'|'graph';
export type ExploreItem={id:string;group:ExploreGroup;format:'play'|'khan';title:string;intro:string;topic:Topic;skill:Skill;entryId:string;scene?:ExploreScene;question:string;choices:string[];answer:number;explanation:string;next:string;exposures?:string[];pairs?:[number,number][]};
export const EXPLORE_ITEMS:ExploreItem[]=[
 {id:'same-mix',group:'numbers',format:'play',scene:'mixture',title:'More drink. Same taste?',intro:'Make a bigger batch without changing the recipe.',topic:'ratios',skill:'unit_rate',entryId:'unit-rates',question:'Double both ingredients. What happens to the syrup share?',choices:['It doubles','It stays the same','It halves'],answer:1,explanation:'Both amounts grow by the same multiplier. The syrup is still 2 out of every 5 parts. This is the idea behind scaling a recipe.',next:'Explore rates and proportions on Khan Academy.'},
 {id:'same-amount',group:'numbers',format:'play',scene:'fractions',title:'More pieces. More chocolate?',intro:'Divide the same bar into smaller pieces.',topic:'fractions',skill:'equivalent',entryId:'unlike-fractions',question:'If each piece is split in two, do you have more chocolate?',choices:['Yes, twice as much','No, the amount stays the same'],answer:1,explanation:'The pieces get smaller, but the shaded amount stays fixed. One half and two quarters describe the same amount of the same whole.',next:'Use equal-sized pieces to add fractions on Khan Academy.',exposures:['1/2 = 2/4','1/2 = 3/6','1/2 = 4/8']},
 {id:'every-term',group:'algebra',format:'play',scene:'distribution',title:'Does the 3 reach everything?',intro:'Open three identical bags. Keep track of every item.',topic:'brackets',skill:'expand',entryId:'bracket-equations',question:'Each bag holds x + 4. What is in all three bags?',choices:['3x + 4','3x + 12','x + 12'],answer:1,explanation:'Three copies of x make 3x. Three copies of 4 make 12. Multiplying a group means multiplying every term inside it.',next:'Watch Khan Academy explain the distributive property.',exposures:['3(x + 4)','3(x + 4) = 3x + 12']},
 {id:'khan-open-brackets',group:'algebra',format:'khan',title:'Open the brackets with Khan',intro:'A focused moment from an original Khan Academy lesson.',topic:'brackets',skill:'expand',entryId:'bracket-equations',question:'In 2(x + 5), which parts does the 2 multiply?',choices:['Only x','Only 5','Both x and 5'],answer:2,explanation:'The outside factor multiplies the whole group: 2x + 10. Try the movement, watch the explanation, or continue to the original exercise.',next:'Practise distribution on Khan Academy.',exposures:['2(x + 5)','2x + 10']},
 {id:'khan-like-terms',group:'algebra',format:'khan',title:'Which terms belong together?',intro:'Khan Academy shows why matching terms can be combined.',topic:'quadratics',skill:'terms',entryId:'factor-quadratics',question:'Which pair combines into one x term?',choices:['3x and 2x','3x and 2','3x and 2x²'],answer:0,explanation:'Three copies of x plus two copies of x make five copies of x. A number or an x² term is a different kind of quantity.',next:'Try combining like terms on Khan Academy.',exposures:['3x + 2x','5x']},
 {id:'four-pieces',group:'algebra',format:'play',scene:'factors',title:'A rectangle hiding in an equation',intro:'Separate the four parts, then bring them together.',topic:'quadratics',skill:'distribute',entryId:'factor-quadratics',question:'Why is the middle term 7x in (x + 3)(x + 4)?',choices:['3x + 4x makes 7x','3 × 4 makes 7','x × x makes 7x'],answer:0,explanation:'The four contributions are x², 3x, 4x and 12. The two x terms combine into 7x. The drawing uses a positive x so every side has a positive length.',next:'See Khan Academy work through the four products.',exposures:['(x + 3)(x + 4)','x² + 7x + 12'],pairs:[[3,4]]},
 {id:'khan-four-products',group:'algebra',format:'khan',title:'Find all four products',intro:'Follow the same idea in Khan Academy’s original explanation.',topic:'quadratics',skill:'distribute',entryId:'factor-quadratics',question:'Multiplying two binomials gives how many products before combining?',choices:['Two','Three','Four'],answer:2,explanation:'Each of the two terms in the first bracket multiplies each of the two terms in the second: 2 × 2 = 4 products.',next:'Practise multiplying binomials on Khan Academy.'},
 {id:'khan-factor-pairs',group:'algebra',format:'khan',title:'A factor pair has two jobs',intro:'Khan Academy connects the middle term and the constant.',topic:'quadratics',skill:'factor',entryId:'factor-quadratics',question:'For x² + 7x + 12, what must the pair do?',choices:['Only multiply to 12','Add to 7 and multiply to 12','Only add to 7'],answer:1,explanation:'Both conditions matter. The pair 3 and 4 adds to 7 and multiplies to 12. The pair 2 and 6 has the right product but the wrong sum.',next:'Choose a new pair in Khan Academy’s factoring practice.',exposures:['x² + 7x + 12'],pairs:[[3,4],[2,6]]},
 {id:'find-the-zero',group:'algebra',format:'play',scene:'roots',title:'Why does the sign change?',intro:'Move x until one factor becomes zero.',topic:'quadratics',skill:'zero',entryId:'solve-quadratics',question:'Which x makes x + 3 equal zero?',choices:['3','−3','0'],answer:1,explanation:'At x = −3, the first factor is zero. Then the product is zero. At x = −4, the second factor is zero. The constants 3 and 4 are different from the solutions −3 and −4.',next:'Solve quadratics by factoring on Khan Academy.',exposures:['(x + 3)(x + 4) = 0','x² + 7x + 12 = 0'],pairs:[[3,4]]},
 {id:'read-the-graph',group:'graphs',format:'play',scene:'graph',title:'A line tells a filling story',intro:'Move time and read the amount from the graph.',topic:'graphs',skill:'goal',entryId:'graph-values',question:'The tank starts at 6 litres and gains 2 litres each minute. At 3 minutes?',choices:['6 litres','8 litres','12 litres'],answer:2,explanation:'Start with 6 litres, then add 2 litres three times: 6 + 2 × 3 = 12 litres. The point and the water level show the same quantity.',next:'Read a function’s value from its graph on Khan Academy.',exposures:['y = 2x + 6','V = 6 + 2t']}
];
export const exploreItem=(id?:string|null)=>EXPLORE_ITEMS.find(item=>item.id===id);
export const isExploreReturnPath=(path:string)=>EXPLORE_ITEMS.some(item=>path===`/explore?item=${item.id}`);
export function exploreMaterial(item:ExploreItem){
 const material=khanMaterial({...initialRecovery(item.topic),active:item.skill});
 const entry=khanEntry(item.entryId)!;
 return {...material,learning:material.id?{title:material.title,url:material.source}:entry.learning,practice:material.resources.find(r=>r.kind==='exercise')??entry.practice};
}
export type ExploreState={last?:string;saved:string[];answers:Record<string,number>;values:Record<string,number>};
export const emptyExplore=():ExploreState=>({saved:[],answers:{},values:{}});
const object=(x:unknown):x is Record<string,unknown>=>!!x&&typeof x==='object'&&!Array.isArray(x);
export function validExplore(x:unknown):x is ExploreState{
 if(!object(x)||!Array.isArray(x.saved)||x.saved.length>100||!x.saved.every(v=>typeof v==='string'&&v.length<80)||!object(x.answers)||!object(x.values))return false;
 if(x.last!==undefined&&(typeof x.last!=='string'||x.last.length>80))return false;
 return [x.answers,x.values].every(map=>Object.keys(map).length<=200&&Object.entries(map).every(([k,v])=>k.length<100&&typeof v==='number'&&Number.isFinite(v)&&Math.abs(v)<=1000));
}
export function savedExplore(s?:ExploreState):ExploreState{
 if(!s||!validExplore(s))return emptyExplore();
 return {last:exploreItem(s.last)?.id,saved:[...new Set(s.saved.filter(id=>exploreItem(id)))],answers:Object.fromEntries(Object.entries(s.answers).filter(([id,n])=>{const item=exploreItem(id);return !!item&&Number.isInteger(n)&&n>=-1&&n<item.choices.length;})),values:s.values};
}
export function exploreValue(s:ExploreState,id:string,fallback:number,min:number,max:number){const n=s.values[id];return typeof n==='number'&&Number.isFinite(n)?Math.round(Math.min(max,Math.max(min,n))):fallback;}
