import type {Problem,Recovery} from './recovery.ts';
/** Version 3 adds structure. Earlier generator versions remain readable unchanged. */
export function mathsFamily(s:Recovery):Problem|undefined{
 const v=s.serial,k=2+Math.floor(v/3),f=v%3,id=`${s.topic}:${s.active}:${v}`;
 const make=(family:string,expression:string,prompt:string,labels:string[],expected:number[],hint:string,explanation:string,extra:Partial<Problem>={}):Problem=>({id,family,expression,prompt,labels,expected,hint,explanation,...extra});
 if(s.active==='expand'){
  const a=f===1?-k:k,b=f===1?-3:3,letter=f===2?'y':'x';
  return make(['positive-distribution','signed-distribution','missing-constant'][f],`${a}(${letter} ${b<0?'−':'+'} ${Math.abs(b)})`,f===2?`An expansion is ${a}${letter} + c. Find c.`:'Expand the brackets.',f===2?['Constant c']:[`Coefficient of ${letter}`,'Constant'],f===2?[a*b]:[a,a*b],'Every term in every group must be counted.',`${a} × ${letter} + (${a}) × (${b}) = ${a}${letter} ${a*b<0?'−':'+'} ${Math.abs(a*b)}. A single multiplication would leave groups uncounted.`);
 }
 if(s.active==='factor'||s.active==='zero'||(s.topic==='quadratics'&&s.active==='goal'&&v>0)){
  const p=f===1?-k:f===0&&Math.floor(v/3)%2?-k:k,q=f===2?p:f===1?k+3:p+Math.sign(p),sum=p+q,prod=p*q;
  const term=(n:number,l='')=>n===0?'':` ${n<0?'−':'+'} ${Math.abs(n)}${l}`;
  const poly=`x²${term(sum,'x')}${term(prod)}`,factors=`(x${term(p)})(x${term(q)})`;
  if(s.active==='factor')return make(['sum-product','signed-factors','square-factor'][f],poly,'Write the two constants in (x + p)(x + q).',['p','q'],[p,q],`Match both sum ${sum} and product ${prod}.`,`${p} + (${q}) = ${sum} and (${p}) × (${q}) = ${prod}, so ${poly} = ${factors}.`,{unordered:true,factorPair:[p,q],widget:'factors'});
  return make(['expanded-roots','signed-roots','repeated-root'][f],`${s.active==='zero'?factors:poly} = 0`,p===q?'Find the single distinct solution.':'Find the two solutions.',p===q?['Solution']:['First solution','Second solution'],p===q?[-p]:[-p,-q],'Set each factor equal to zero. The constants are not the solutions.',`${factors} = 0. ${p===q?`Both factors become zero at x = ${-p}; this is one distinct solution.`:`x = ${-p} or x = ${-q}. Substituting either value makes at least one factor zero.`}`,{unordered:true,factorPair:[p,q]});
 }
 if(s.active==='equivalent')return f===0?make('missing-numerator',`\\frac{2}{${k+3}} = \\frac{x}{${(k+3)*3}}`,'Find the missing numerator.',['Numerator'],[6],'Scale both numerator and denominator by the same nonzero factor.','The denominator triples, so the numerator triples: 2 × 3 = 6.'):f===1?make('missing-denominator',`\\frac{3}{${k+4}} = \\frac{12}{x}`,'Find the missing denominator.',['Denominator'],[(k+4)*4],'The numerator was multiplied by 4.','Multiplying both parts by 4 keeps the fraction unchanged.'):make('simplify-fraction',`\\frac{${2*k}}{${3*k}}`,'Write an equivalent fraction. You may simplify it.',['Numerator','Denominator'],[2,3],'Divide both parts by a common nonzero factor.',`Divide the top and bottom by ${k}: 2/3.`,{format:'fraction'});
 if(s.topic==='fractions'&&s.active==='goal'&&v>0){const a=f===2?k+1:1,b=k+2,c=f===2?3:2,d=f===1?2*b:4;return make(['unlike-parts','nested-denominators','beyond-one'][f],`\\frac{${a}}{${b}} + \\frac{${c}}{${d}}`,'Add the fractions. Equivalent answers are accepted.',['Numerator','Denominator'],[a*d+c*b,b*d],'Use equal-sized pieces before counting them together.',`A common denominator is ${b*d}. The sum is ${a*d}/${b*d} + ${c*b}/${b*d} = ${a*d+c*b}/${b*d}. The original amounts do not change.`,{format:'fraction'});}
 if(s.topic==='ratios'&&s.active==='goal'&&v>0)return f===0?make('unit-price',`${k}\\,\\mathrm{items}:\\,\\mathrm{PHP}\\,${k*7}`,`${k} items cost PHP ${k*7}. At the same unit price, what do 5 items cost?`,['Cost'],[35],'Find one item, then scale.','Each item costs PHP 7. Five cost PHP 35.',{speak:`${k} items cost ${k*7} Philippine pesos`,fields:[{label:'Cost',unit:'PHP'}]}):f===1?make('mixture-total',`2 : 3,\\,\\mathrm{total} = ${5*k}`,'Keep the mixture. How many of each part?',['First part','Second part'],[2*k,3*k],'The total 5 parts scales by the same factor as both amounts.',`The scale factor is ${k}. Both amounts multiply by ${k}: ${2*k} and ${3*k}.`):make('reverse-proportion',`${k}\\,\\mathrm{notebooks}:\\,\\mathrm{PHP}\\,${k*9}`,`${k} notebooks cost PHP ${k*9}. How many can PHP 45 buy at the same price?`,['Notebooks'],[5],'First find the price of one notebook.','One costs PHP 9, and 45 ÷ 9 = 5.',{speak:`${k} notebooks cost ${k*9} Philippine pesos`});
 if(s.topic==='graphs'&&s.active==='goal'&&v>0){const m=f===1?-2:f===2?0:2,c=k+1;return f===0?make('recover-rule',`(0, ${c}), (3, ${c+3*m})`,'Find m and b for the line y = mx + b through these points.',['Slope m','Intercept b'],[m,c],'Rate is change in y divided by change in x.','The change in y is 6 over 3 units of x, so m = 2. At x = 0, y gives b.'):make(f===1?'signed-rule':'horizontal-line',`y = ${m}x + ${c}, x = ${k}`,'Use this rule to find y.',['Value of y'],[m*k+c],'Substitute x. A zero rate leaves the value unchanged.',`${m} × ${k} + ${c} = ${m*k+c}.`,{graph:f===2?{kind:'line',x:k,slope:m,intercept:c}:undefined});}
 if(s.topic==='brackets'&&s.active==='goal'&&v>0){const answer=k,c=f===1?-3:3,a=f===2?2:4,rhs=a*(answer+c);return make(['equation-brackets','signed-inner-term','brackets-both-sides'][f],f===2?`2(y + 3) = y + ${answer+6}`:`${a}(y ${c<0?'−':'+'} ${Math.abs(c)}) = ${rhs}`,'Solve for y.',['Value of y'],[answer],'Distribute to every term, then keep both sides equal.',f===2?`2y + 6 = y + ${answer+6}. Subtract y and 6 to get y = ${answer}.`:`${a}y + (${a*c}) = ${rhs}. Subtract ${a*c}, then divide by ${a}: y = ${answer}.`);}
}
