'use client';
import {useEffect,useRef,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {findChallenge,CHALLENGES,type Challenge} from '@/lib/challenges';
import {isCorrect,answerInputIssue,pairKey} from '@/lib/recovery';
import {khanEntry} from '@/lib/khan-entry';
import {packFromKhan,beginSession,planSession,skillKey} from '@/lib/study';
import {useStudy} from './StudyProvider';
import {MathText} from '@/components/math/Math';
import {ErrorReplay} from '@/components/product/ErrorReplay';
import {ConceptLab} from './ConceptLab';
import {PackKhanResources} from './PackKhanResources';
export function ChallengeExperience(){const params=useSearchParams(),challenge=findChallenge(params.get('code')??''),router=useRouter();const [code,setCode]=useState('');return challenge?<ChallengeRound key={challenge.code} challenge={challenge}/>:<div className="study-space challenge-missing"><h1>Find your challenge.</h1><p>Enter the short code from the video or shared link.</p><form className="challenge-code" onSubmit={e=>{e.preventDefault();router.push(`/challenge?code=${encodeURIComponent(code.trim().toUpperCase())}`);}}><label>Challenge code<input value={code} onChange={e=>setCode(e.target.value)} maxLength={8} placeholder="FQ1"/></label><button className="button-primary">Open challenge</button></form>{params.has('code')&&<p role="status">That code did not match. Check its letters and numbers.</p>}<div className="challenge-suggestions">{[CHALLENGES[0],CHALLENGES[4],CHALLENGES[8]].map(c=><Link key={c.code} href={`/challenge?code=${c.code}`}>{c.title} ↗</Link>)}</div></div>;}
function ChallengeRound({challenge:c}:{challenge:Challenge}){const {state,ready,update}=useStudy(),router=useRouter();const [values,setValues]=useState(c.question.labels.map(()=>'')),[checked,setChecked]=useState(false),[error,setError]=useState(''),[explain,setExplain]=useState(false);const logged=useRef(false);const entry=khanEntry(c.khanId)!,pack=packFromKhan(entry),correct=checked&&isCorrect(c.question,values);
 useEffect(()=>{if(!ready||logged.current)return;logged.current=true;update(s=>({...s,seen:[...new Set([...s.seen,`${skillKey(entry.topic,entry.skill)}:${c.question.expression}`])],cursors:{...s.cursors,[entry.topic]:Math.max(s.cursors[entry.topic]??0,1)},pairs:c.family==='factors'?{...s.pairs,quadratics:[...new Set([...(s.pairs.quadratics??[]),pairKey([3,4])])]}:s.pairs,events:[...s.events,{kind:'challenge_open' as const,at:Date.now(),detail:c.code}].slice(-1000),updatedAt:Date.now()}));},[ready,c.code,update,entry.topic,entry.skill,c.family,c.question.expression]);
 function begin(){update(s=>{const exposed={...s,cursors:{...s.cursors,[entry.topic]:Math.max(s.cursors[entry.topic]??0,1)},pairs:c.family==='factors'?{...s.pairs,quadratics:[...new Set([...(s.pairs.quadratics??[]),pairKey([3,4])])]}:s.pairs};return beginSession({...exposed,packs:[...s.packs.filter(p=>p.id!==pack.id),pack]},planSession(exposed,pack,5,'review',Date.now()),Date.now());});router.push('/study/session');}
 return <div className="study-space challenge-page"><div className="challenge-heading"><div><p className="eyebrow">Challenge {c.code}</p><h1>{c.title}</h1><p>{c.hook}</p></div><Link className="button-text" href="/packs">My packs ↗</Link></div><section className="source-challenge"><h2>{c.question.prompt}</h2><MathText size="hero">{c.question.expression}</MathText><form onSubmit={e=>{e.preventDefault();const issue=answerInputIssue(c.question,values);if(issue){setError(issue);return;}setError('');setChecked(true);update(s=>({...s,events:[...s.events,{kind:'challenge_attempt' as const,at:Date.now(),detail:`${c.code}:${isCorrect(c.question,values)?'correct':'needs-support'}`}].slice(-1000),updatedAt:Date.now()}));}}><div className="answer-inputs">{c.question.labels.map((label,i)=><label className="number-field" key={label}><span>{label}</span><input value={values[i]} onChange={e=>{setValues(xs=>xs.map((x,j)=>i===j?e.target.value:x));setChecked(false);setError('');}} maxLength={18} autoComplete="off" inputMode="text"/></label>)}</div>{error&&<p role="alert">{error}</p>}<button className="button-primary" disabled={!ready||values.some(x=>!x.trim())}>Check this answer</button></form>{checked&&<div className="challenge-feedback" role="status"><h3>{correct?'That fits. Ready for a new version?':'Let’s look at the step together.'}</h3><p>{c.insight}</p><div><button className={correct?'button-primary':'button-secondary'} onClick={begin}>Try a fresh question ↗</button><button className={correct?'button-text':'button-primary'} onClick={()=>setExplain(!explain)}>{explain?'Close explanation':'Make the idea click'}</button></div><small>The question from the challenge is practice. Your study round uses fresh numbers.</small></div>}</section>{explain&&(c.family==='factors'?<ErrorReplay model={{kind:'factors',pair:[3,4],attempt:values.map(Number) as [number,number],fromAttempt:true}} onExpose={pair=>update(s=>({...s,pairs:{...s.pairs,quadratics:[...new Set([...(s.pairs.quadratics??[]),pairKey(pair)])]},updatedAt:Date.now()}))} onContinue={begin}/>:<ConceptLab kind={c.family} onContinue={begin}/>)}<section className="challenge-next"><h2>Keep going with this Khan activity.</h2><p>{entry.title}. The same learning goal continues into your pack and reviewer.</p><PackKhanResources pack={pack}/><button className="button-text" onClick={()=>{update(s=>({...s,packs:[...s.packs.filter(x=>x.id!==pack.id),pack],activePack:pack.id,updatedAt:Date.now()}));router.push('/packs');}}>Save this study pack ↗</button></section></div>;
}
