'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {KHAN_ENTRIES,resolveKhanUrl,type KhanEntry as Entry} from '@/lib/khan-entry';
import {packFromKhan,beginSession,planSession} from '@/lib/study';
import {useStudy} from './StudyProvider';
import {MathText} from '@/components/math/Math';
export function KhanEntry(){const {state,ready,update}=useStudy(),router=useRouter();const [url,setUrl]=useState(''),[selected,setSelected]=useState<Entry>(),[error,setError]=useState('');
  function begin(entry:Entry,learn:boolean){const pack=packFromKhan(entry);update(s=>beginSession({...s,packs:[...s.packs.filter(p=>p.id!==pack.id),pack]},planSession(s,pack,s.settings.minutes,learn?'learn':'review',Date.now()),Date.now()));router.push('/study/session');}
  return <div className="study-space khan-entry-page"><img className="entry-khan-logo" src="/khan-academy.svg" alt="Khan Academy" width="180" height="30"/><p className="eyebrow">Start from the activity you’re learning</p><h1>Bring your Khan goal with you.</h1><p className="khan-entry-intro">Choose an activity or paste its Khan link. We’ll connect it to a useful check, focused help, and your next review.</p><form className="khan-url-form" onSubmit={e=>{e.preventDefault();const found=resolveKhanUrl(url);setSelected(found);setError(found?'':'That link is not one of the mapped activities here. Choose its topic below.');}}><label htmlFor="khan-activity-url">Khan lesson or practice link</label><div><input id="khan-activity-url" value={url} onChange={e=>{setUrl(e.target.value);setError('');}} placeholder="https://www.khanacademy.org/math/…" autoComplete="off"/><button className="button-secondary">Find my activity</button></div></form>{error&&<p role="alert" className="input-error">{error}</p>}{selected&&<section className="matched-khan-entry"><span className="eyebrow">Activity matched</span><h2>{selected.title}</h2><MathText>{selected.expression}</MathText><div><button className="button-primary" onClick={()=>begin(selected,false)} disabled={!ready}>Build my session ↗</button><button className="button-text" onClick={()=>begin(selected,true)} disabled={!ready}>Start with an explanation</button></div></section>}<h2 className="entry-list-title">Supported activities</h2><div className="khan-activity-grid">{KHAN_ENTRIES.map(entry=><article key={entry.id}><h3>{entry.title}</h3><MathText size="sm">{entry.expression}</MathText><p><a href={entry.learning.url} target="_blank" rel="noopener noreferrer">Official Khan activity ↗</a></p><button className="button-primary" disabled={!ready} onClick={()=>begin(entry,false)}>Study this activity ↗</button><button className="button-text" disabled={!ready} onClick={()=>begin(entry,true)}>Learn it first</button></article>)}</div></div>;
}
