'use client';
import {useEffect,useRef,useState} from 'react';
import {useReducedMotion} from 'motion/react';
import {SceneNumber} from './SceneNumber';
import {useStudy} from './StudyProvider';
import {motion} from 'motion/react';
import {FractionScene} from './FractionScene';
import {RatioMixture,RatioNumberLines} from './RatioScene';
import {DistributionScene} from './DistributionScene';
import {FactorScene} from './FactorScene';
import {FillingScene} from './FillingScene';
import {LessonCompanion} from './LessonCompanion';
import {MathText} from '@/components/math/Math';
import {factorText,quadraticText} from '@/lib/recovery';
import {freshLab,distribution,partition,mixture,lineValue,type MathsKind,type LabSave} from '@/lib/visual-maths';

const SCRIPT:Record<MathsKind,{title:string;question:string;options:string[];reason:string;words:string;stages:string[]}>= {
 brackets:{title:'Every term travels with its group.',question:'Which parts of 3(x + 4) are multiplied by 3?',options:['Only x','Only 4','Both x and 4'],reason:'Each of the three groups contains an x and four units. Removing the brackets cannot remove two groups of units.',words:'A term is one part separated by + or −. The coefficient tells how many copies of a term there are.',stages:['Three equal groups','Collect the x tiles','Collect the unit tiles','Connect both products']},
 factors:{title:'Two edges. Four contributions.',question:'For (x + 2)(x + 6), which part matches x² + 7x + 12?',options:['The x term','The constant','Both','Neither'],reason:'Every part of one bracket multiplies every part of the other. The two middle contributions add; the corner gives the constant.',words:'A factor is an expression being multiplied. The coefficient of x counts the middle x terms.',stages:['Read the edges','Multiply each pair','Join the middle terms','Match both constraints']},
 roots:{title:'A factor is zero. The product is zero.',question:'Which x makes x + 3 equal zero?',options:['3','−3','0'],reason:'For a product to be zero, at least one factor must be zero. Solve each factor equation; never divide by a factor that might be zero.',words:'A root is a value of x that makes the original polynomial zero. A factor is an expression, not a solution.',stages:['Choose a value of x','Evaluate both factors','Read their product','Connect to the intercepts']},
 fractions:{title:'New pieces. The same amount.',question:'Does adding the tops and bottoms preserve 2/3 + 1/4?',options:['Yes, it gives 3/7','No, the pieces have different sizes'],reason:'The pieces now have the same size. That is what lets us count them together. Repartitioning changes the unit, not the amount.',words:'The denominator names the size of each equal piece. The numerator counts how many pieces we have.',stages:['Equal-sized wholes','Partition the first amount','Partition the second amount','Count equal-sized pieces']},
 ratios:{title:'Scale the mixture, keep its share.',question:'Which keeps a 2 : 3 mixture the same?',options:['Add 2 to each amount','Double both amounts'],reason:'Multiplying both amounts by the same factor preserves the share of each part. Adding the same number usually changes the mixture.',words:'A ratio compares amounts. A share compares one amount with the total.',stages:['Start with 2 : 3','Compare equal addition','Compare multiplication','Build a target mixture']},
 graphs:{title:'Starting value and rate do different jobs.',question:'If the filling rate doubles, what stays the same?',options:['The initial 6 litres','The volume added each minute'],reason:'Changing the rate rotates the line about the starting point. Changing the starting value shifts it in parallel. Compare rates using the axis units, not apparent steepness.',words:'The intercept is the value at time zero. The slope is change in volume divided by change in time.',stages:['Start with 6 litres','Add 2 litres each minute','Change only the rate','Change only the start']}
};

export function MathsLab({kind,onContinue,initial,onSave,onEvent,onExposePair,pair:targetPair=[3,4],attempt=[2,6]}:{kind:MathsKind;onContinue:()=>void;initial?:LabSave;onSave?:(s:LabSave)=>void;onEvent?:(kind:'visual_prediction'|'reflection'|'counterfactual',detail:string)=>void;onExposePair?:(pair:[number,number])=>void;pair?:[number,number];attempt?:[number,number]}){
 const {state:studyState}=useStudy();
 const [s,set]=useState<LabSave>(initial??freshLab),[playing,setPlaying]=useState(false),[revealPoint,setRevealPoint]=useState(false),[reverse,setReverse]=useState(false),[reverseAnswer,setReverseAnswer]=useState(''),[reverseChecked,setReverseChecked]=useState(false);
 const [pointing,setPointing]=useState(false);
 const reduced=useReducedMotion(),script=SCRIPT[kind],save=useRef(onSave),expose=useRef(onExposePair);save.current=onSave;expose.current=onExposePair;
 useEffect(()=>{save.current?.(s);},[s]);
 useEffect(()=>{if(!playing||s.step>=4||reduced||s.static){setPlaying(false);return;}const id=setTimeout(()=>set(v=>({...v,step:Math.min(4,v.step+1)})),1800);return()=>clearTimeout(id);},[playing,s.step,reduced,s.static]);
 const val=(name:string,fallback:number)=>s.values[name]??fallback;
 function value(name:string,n:number){if(Number.isFinite(n))set(v=>({...v,values:{...v.values,[name]:Math.round(n)}}));}
 function bump(name:string,fallback:number,by:number,min:number,max:number){set(v=>({...v,values:{...v.values,[name]:Math.min(max,Math.max(min,(v.values[name]??fallback)+by))}}));}
 const p=val('p',attempt[0]),q=val('q',attempt[1]),signed=val('signed',0)===1,x=val('x',0),a=signed?-2:3,b=signed?-3:4;
 const denom=val('denom',12),over=val('over',0)===1,n1=over?5:2,d1=over?6:3,n2=over?3:1,d2=4;
 const rate=val('rate',2),start=val('start',6),time=val('time',0),abstract=val('abstract',0)===1;
 const rp: [number,number]=val('repeat',0)?[-2,-2]:targetPair;
 useEffect(()=>{if(kind==='factors'){expose.current?.([p,q]);expose.current?.(targetPair);}if(kind==='roots')expose.current?.(rp);},[kind,p,q,rp[0],rp[1]]);
 const step=s.step,shown=step>0;
 const question=kind==='factors'?`For ${factorText(attempt[0])}${factorText(attempt[1])}, which part matches ${quadraticText(...targetPair)}?`:kind==='roots'?`Which x makes x ${rp[0]<0?'−':'+'} ${Math.abs(rp[0])} equal zero?`:script.question;
 const options=kind==='roots'?[String(rp[0]),String(-rp[0]),'0']:script.options;
 function controls(name:string,label:string,fallback:number,min:number,max:number){return <label className="math-control"><span>{label}</span><div><button type="button" aria-label={`Decrease ${label}`} disabled={val(name,fallback)<=min} onClick={()=>bump(name,fallback,-1,min,max)}>−</button><SceneNumber label={label} min={min} max={max} value={val(name,fallback)} onChange={n=>value(name,n)}/><button type="button" aria-label={`Increase ${label}`} disabled={val(name,fallback)>=max} onClick={()=>bump(name,fallback,1,min,max)}>+</button></div></label>;}
 return <section className="maths-lab" data-static={!!reduced||s.static} aria-label={`${kind} visual guide`}>
  <div className="repair-kicker"><span>Dunlo visual guide</span><span>Predict → explore → explain</span></div><h3>{script.title}</h3><LessonCompanion kind={kind} step={s.step} onPoint={()=>setPointing(!pointing)} onExample={()=>set(v=>({...v,step:1}))}/>
  {!shown?<div className="math-prediction"><fieldset><legend>{question}</legend>{options.map(o=><button key={o} type="button" aria-pressed={s.prediction===o} onClick={()=>{set(v=>({...v,prediction:o}));onEvent?.('visual_prediction',o);}}>{o}</button>)}</fieldset>{s.prediction&&<p role="status">Prediction saved. Explore the relationship to test your idea.</p>}<div className="math-actions"><button className="button-primary" disabled={!s.prediction} onClick={()=>set(v=>({...v,step:1}))}>Test my prediction ↗</button><button className="button-text" onClick={()=>{onEvent?.('visual_prediction','I don’t know yet');set(v=>({...v,step:1,prediction:'I don’t know yet'}));}}>I don’t know yet</button><button className="button-text" onClick={()=>set(v=>({...v,step:1}))}>Show me an example first</button></div></div>:<>
  <div className="math-timeline" aria-label="Explanation steps">{script.stages.map((label,i)=><button key={label} aria-current={step===i+1?'step':undefined} onClick={()=>{setPlaying(false);set(v=>({...v,step:i+1}));}}><span>{i+1}</span>{label}</button>)}</div>
  <div className="math-workspace" data-pointed={pointing}>
  {kind==='brackets'&&<><MathText size="lg">{`${a}(x ${b<0?'−':'+'} ${Math.abs(b)})`}</MathText>{!signed?<DistributionScene staticMode={s.static} collected={step>=3} emphasizeX={step===2}/>:<div className="signed-contributions"><p>Signed contributions · these are values, not negative lengths.</p><div><strong>−2 × x = −2x</strong><strong>−2 × (−3) = +6</strong></div><p>Multiplying by −2 reverses the sign and doubles the magnitude of every term.</p></div>}<div className="math-actions"><button className="button-secondary" draggable={!signed} onDragEnd={()=>set(v=>({...v,step:3}))} onClick={()=>set(v=>({...v,step:3}))}>Collect the groups</button><button className="button-text" onClick={()=>value('signed',signed?0:1)}>{signed?'Positive groups':'Explore −2(x − 3)'}</button></div>{step>=3&&<MathText size="lg">{`${a}(x ${b<0?'−':'+'} ${Math.abs(b)}) = ${a}x + ${a*b}`}</MathText>}{step===4&&<div className="math-comparison"><h4>Test the incomplete expansion</h4>{controls('testx','Test value of x',2,-5,5)}<p>Original: <strong>{distribution(a,b,val('testx',2)).original}</strong> · Only the first term multiplied: <strong>{distribution(a,b,val('testx',2)).incomplete}</strong></p><p>Only one term was multiplied. The two expressions now give different values. One counterexample disproves equivalence; one matching value cannot prove it for every x.</p></div>}</>}
  {kind==='factors'&&<><div className="math-target"><span>Target</span><MathText size="lg">{quadraticText(...targetPair)}</MathText></div><div className="math-controls">{controls('p','First factor number',attempt[0],-12,12)}{controls('q','Second factor number',attempt[1],-12,12)}</div><FactorArea staticMode={s.static} p={p} q={q} join={step>=3}/>{step>=2&&<MathText size="md">{`${factorText(p)}${factorText(q)} = ${quadraticText(p,q)}`}</MathText>}<div className="math-constraints" aria-live="polite"><p><span>Product</span><strong>{p*q}</strong>{p*q===targetPair[0]*targetPair[1]?'✓ Matches':`Target ${targetPair[0]*targetPair[1]}`}</p><p><span>Sum</span><strong>{p+q}</strong>{p+q===targetPair[0]+targetPair[1]?'✓ Matches':`Target ${targetPair[0]+targetPair[1]}`}</p></div><button className="button-text" onClick={()=>{value('p',targetPair[0]);value('q',targetPair[1]);}}>Show one matching pair</button><button className="button-text" onClick={()=>setReverse(!reverse)}>What would make this answer true?</button>{reverse&&<div className="math-comparison"><h4>Keep 2 and 6. Change the problem.</h4><label>In x² + bx + 12, what should b be?<input type="number" value={reverseAnswer} onChange={e=>{setReverseAnswer(e.target.value);setReverseChecked(false);}}/></label><button className="button-secondary" onClick={()=>{setReverseChecked(true);onEvent?.('counterfactual',`Factor reconstruction: ${reverseAnswer}`);}}>Check my reconstruction</button>{reverseChecked&&<p role="status">{Number(reverseAnswer)===8?'Yes: x² + 8x + 12. The product stays 12, but the middle coefficient changes.':'Expand the two middle contributions: 2x + 6x. What coefficient do they make?'}</p>}<p>Return to the original target above. Your independent follow-up uses a different problem.</p></div>}</>}
  {kind==='roots'&&<><MathText size="lg">{`${factorText(rp[0])}${factorText(rp[1])} = 0`}</MathText><p>Factor constants: {rp.join(' and ')}. The solutions must make a factor zero.</p>{controls('x','Value of x',0,-12,12)}<svg viewBox="0 0 560 90" role="img" aria-label={`Number line: selected x is ${x}`}><path d="M25 40H535" stroke="#0A2A66"/>{Array.from({length:13},(_,i)=>i*2-12).map(n=><g key={n}><path d={`M${280+n*21} 34v12`} stroke="#0A2A66"/><text x={280+n*21} y="68" textAnchor="middle">{n}</text></g>)}<circle className="moving-tile" cx={280+x*21} cy="40" r="9" fill="#14BF96" stroke="#0A2A66"/></svg><div className="math-constraints" aria-live="polite">{rp.map((n,i)=><p key={i}><span>x {n<0?'−':'+'} {Math.abs(n)}</span><strong>{x+n}</strong>{x+n===0?'✓ Zero factor':'Nonzero factor'}</p>)}<p><span>Product</span><strong>{(x+rp[0])*(x+rp[1])}</strong>{(x+rp[0])*(x+rp[1])===0?'✓ Solution':'Not a solution'}</p></div>{step===4&&<><RootGraph pair={rp} x={x} staticMode={s.static||!!reduced||studyState.settings.quiet}/><p>Substitution into {quadraticText(...rp)} gives {(x+rp[0])*(x+rp[1])}. Roots sit at the x-intercepts.</p></>}<div className="math-actions">{[...new Set(rp.map(n=>-n))].map(n=><button className="button-secondary" key={n} onClick={()=>value('x',n)}>Try x = {n}</button>)}<button className="button-text" onClick={()=>value('repeat',val('repeat',0)?0:1)}>Explore a repeated root</button></div>{rp[0]===rp[1]&&<p>(x − 2)² = 0 has one distinct solution: 2. Both factors vanish at the same value.</p>}<p>These examples factor into integers. Some quadratics need other methods.</p></>}
  {kind==='fractions'&&<><MathText size="lg">{`\\frac{${n1}}{${d1}} + \\frac{${n2}}{${d2}}`}</MathText><label className="math-control">Choose a common partition<select value={denom} onChange={e=>value('denom',Number(e.target.value))}><option value="12">Twelfths (12)</option><option value="24">Twenty-fourths (24)</option></select></label><FractionBar staticMode={s.static} amount={n1/d1} parts={step>=2?denom:d1} label={step>=2?`${partition(n1,d1,denom).numerator}/${denom}`:`${n1}/${d1}`}/><FractionBar staticMode={s.static} amount={n2/d2} parts={step>=3?denom:d2} label={step>=3?`${partition(n2,d2,denom).numerator}/${denom}`:`${n2}/${d2}`}/>{step===4&&<><FractionBar staticMode={s.static} amount={n1/d1+n2/d2} parts={denom} label={`Sum: ${n1*denom/d1+n2*denom/d2}/${denom}`}/><p>Both wholes kept the same length. {denom===24?'24 is a common denominator too; it does not need to be the least one. Simplifying is a separate step.':'A common denominator lets us count equal-sized pieces.'}</p></>}<button className="button-text" onClick={()=>value('over',over?0:1)}>{over?'Return to 2/3 + 1/4':'Explore a sum beyond one whole'}</button></>}
  {kind==='ratios'&&<><Mixture staticMode={s.static} a={2} b={3} label="Original mixture"/>{step>=2&&<Mixture staticMode={s.static} a={4} b={5} label="Add 2 to both"/>}{step>=3&&<><Mixture staticMode={s.static} a={4} b={6} label="Double both"/><RatioNumberLines staticMode={s.static} scale={step===4?val('scale',1):2}/></>}{step===4&&<><h4>Keep the same mixture; make 20 parts.</h4>{controls('scale','Scale factor',1,1,6)}<Mixture staticMode={s.static} a={2*val('scale',1)} b={3*val('scale',1)} label="Your mixture"/><p role="status">{val('scale',1)===4?'✓ 8 : 12 makes 20 parts with the same 2/5 share.':`${5*val('scale',1)} parts so far. The total scales from 5.`}</p></>}</>}
  {kind==='graphs'&&(!abstract?<><FillingScene staticMode={s.static} autoplay saved={{rate:s.values.rate,start:s.values.start,time:s.values.time}} onChange={values=>set(v=>({...v,values:{...v.values,...values}}))}/><button className="button-text" onClick={()=>{value('abstract',1);value('rate',-2);value('start',3);}}>Explore y = −2x + 3</button></>:<><p>{abstract?'Abstract signed rule. No physical volume is implied.':'A container starts at 6 L. We observe continuous filling over 0–5 minutes.'}</p><div className="math-controls">{controls('rate',abstract?'Slope':'Rate (L/min)',2,abstract?-4:0,4)}{controls('start',abstract?'Intercept':'Initial volume (L)',6,abstract?-6:0,10)}{controls('time',abstract?'Input x':'Time (min)',0,0,5)}</div><p className="math-live-value" role="status">{abstract?`At x = ${time}, y = ${lineValue(start,rate,time)}.`:`At ${time} minutes, volume is ${lineValue(start,rate,time)} litres.`}</p><div className="linked-graph">{!abstract&&<svg viewBox="0 0 150 230" role="img" aria-label={`At ${time} minutes, volume is ${lineValue(start,rate,time)} litres. The drawing has capacity 30 litres.`}><path d="M25 15V205H125V15" fill="none" stroke="#0A2A66" strokeWidth="4"/><rect className="moving-tile" x="28" y={202-lineValue(start,rate,time)*6} width="94" height={lineValue(start,rate,time)*6} fill="#14BF96"/><text x="75" y="225" textAnchor="middle">{lineValue(start,rate,time)} L</text></svg>}<LineGraph rate={rate} start={start} time={time} abstract={abstract}/></div><MathText size="lg">{`${abstract?'y':'V'} = ${start} ${rate<0?'−':'+'} ${Math.abs(rate)}${abstract?'x':'t'}`}</MathText><div className="math-value-table" role="table" aria-label="Input and output values"><div role="row"><strong role="columnheader">{abstract?'x':'Minutes'}</strong>{[0,1,2].map(n=><span key={n} role="cell">{n}</span>)}</div><div role="row"><strong role="rowheader">{abstract?'y':'Litres'}</strong>{[0,1,2].map(n=><span key={n} role="cell">{lineValue(start,rate,n)}</span>)}</div></div><details><summary>Predict an unshown point</summary><label>At {abstract?'x = 4':'4 minutes'}, what is the value?<input type="number" value={s.values.point??''} onChange={e=>value('point',Number(e.target.value))}/></label><button className="button-secondary" onClick={()=>setRevealPoint(true)}>Reveal and compare</button>{revealPoint&&<p>{start} + {rate} × 4 = {lineValue(start,rate,4)}. Compare with your prediction.</p>}</details><button className="button-text" onClick={()=>{value('abstract',abstract?0:1);value('rate',abstract?2:-2);value('start',abstract?6:3);}}>{abstract?'Return to filling':'Explore y = −2x + 3'}</button></>)}
  </div><div className="math-playback"><span hidden={kind==='graphs'&&!abstract}><button className="button-secondary" disabled={!!reduced||s.static||step>=4} onClick={()=>setPlaying(!playing)}>{playing?'Pause':'Play'}</button><button className="button-secondary" disabled={step>=4} onClick={()=>{setPlaying(false);set(v=>({...v,step:v.step+1}));}}>Next step</button><button className="button-text" onClick={()=>{setPlaying(false);set(v=>({...v,step:1}));}}>Replay</button></span><label><input type="checkbox" checked={s.static||!!reduced} onChange={e=>set(v=>({...v,static:e.target.checked}))}/> Static view</label></div>
  <p className="math-principle">{script.reason}</p><details><summary>Explain the words</summary><p>{script.words}</p></details><details><summary>Explain the idea in your own words</summary><label>What changed, and what stayed the same?<textarea value={s.reflection} maxLength={1500} onChange={e=>set(v=>({...v,reflection:e.target.value}))} onBlur={()=>s.reflection&&onEvent?.('reflection',s.reflection)}/></label><small>Your reflection is saved as your own reasoning. It is not automatically graded.</small></details>
  </>}
  <button className="button-primary math-exit" onClick={onContinue}>{shown?'Try without the visual ↗':'Try the independent check directly ↗'}</button><p className="fine-print">Exploration and revealed answers are support. Fresh checks provide separate evidence.</p>
 </section>;
}

export function FactorArea({p,q,join,staticMode=false}:{p:number;q:number;join:boolean;staticMode?:boolean}){return <FactorScene p={p} q={q} join={join} staticMode={staticMode}/>;}
function FractionBar(props:{amount:number;parts:number;label:string;staticMode?:boolean}){return <FractionScene {...props}/>;}
function Mixture(props:{a:number;b:number;label:string;staticMode?:boolean}){return <RatioMixture {...props}/>;}

function LineGraph({rate,start,time,abstract}:{rate:number;start:number;time:number;abstract:boolean}){const xx=(n:number)=>50+n*65,yy=(n:number)=>abstract?185-n*4:270-n*7;return <svg viewBox="0 0 450 340" role="img" aria-label={`Line with starting value ${start}, rate ${rate}. At input ${time}, output is ${start+rate*time}. Dashed reference has start 6 and rate 2.`}>{(abstract?[-30,-20,-10,0,10,20,30]:[0,5,10,15,20,25,30]).map(n=><g key={n}><path d={`M50 ${yy(n)}H395`} stroke="#d6deea"/><text x="40" y={yy(n)+5} textAnchor="end">{n}</text></g>)}<path d={`M50 20V310 M50 ${yy(0)}H405`} stroke="#0A2A66"/>{[0,1,2,3,4,5].map(n=><text key={n} x={xx(n)} y={yy(0)+22} textAnchor="middle">{n}</text>)}<path d={`M50 ${yy(6)}L${xx(5)} ${yy(16)}`} stroke="#667e9f" strokeWidth="2" strokeDasharray="5 4"/><path className="moving-tile" d={`M50 ${yy(start)}L${xx(5)} ${yy(start+rate*5)}`} stroke="#0A2A66" strokeWidth="4"/><path d={`M${xx(1)} ${yy(start+rate)}H${xx(2)}V${yy(start+2*rate)}`} stroke="#087b61" strokeWidth="2" fill="none"/><circle className="moving-tile" cx={xx(time)} cy={yy(start+rate*time)} r="7" fill="#14BF96" stroke="#0A2A66"/><text x="60" y="20">{abstract?'y':'Volume (L)'}</text><text x="240" y="320">{abstract?'x':'Time (min)'}</text><text x="65" y="42" fontSize="12">Dashed: {abstract?'y = 6 + 2x':'V = 6 + 2t'}</text><text x="65" y="60" fontSize="12">{abstract?'Triangle: Δy / Δx':'Triangle: ΔV / Δt'} = {rate} / 1</text></svg>;}
function RootGraph({pair,x,staticMode}:{pair:[number,number];x:number;staticMode:boolean}){const roots=pair.map(n=>-n),lo=Math.min(...roots)-3,hi=Math.max(...roots)+3,xx=(n:number)=>40+(n-lo)/(hi-lo)*460,low=-Math.pow((pair[0]-pair[1])/2,2)-2,high=Math.max((lo+pair[0])*(lo+pair[1]),(hi+pair[0])*(hi+pair[1]))+2,yy=(n:number)=>195-(n-low)/(high-low)*165;const points=Array.from({length:101},(_,i)=>{const v=lo+(hi-lo)*i/100;return `${xx(v)},${yy((v+pair[0])*(v+pair[1]))}`;}).join(' ');return <svg viewBox="0 0 540 240" role="img" aria-label={`Parabola has ${new Set(roots).size} distinct x-intercepts: ${[...new Set(roots)].join(', ')}`}><path d={`M20 ${yy(0)}H520`} stroke="#0A2A66"/>{lo<=0&&hi>=0&&<path d={`M${xx(0)} 25V200`} stroke="#0A2A66"/>}<text x="510" y={yy(0)+22}>x</text><text x="20" y={yy(0)-8}>0</text><text x="20" y="25">Product</text><polyline points={points} stroke="#0A2A66" strokeWidth="3" fill="none"/>{[...new Set(roots)].map(n=><g key={n}><circle cx={xx(n)} cy={yy(0)} r="6" fill="#14BF96" stroke="#0A2A66"/><text x={xx(n)} y={yy(0)+23} textAnchor="middle">{n}</text></g>)}{x>=lo&&x<=hi&&<motion.circle initial={false} animate={{cx:xx(x),cy:yy((x+pair[0])*(x+pair[1]))}} transition={{duration:staticMode?0:.45}} r="6" fill="#0A2A66"/>}<text x="25" y="222">Height = (x {pair[0]<0?'−':'+'} {Math.abs(pair[0])})(x {pair[1]<0?'−':'+'} {Math.abs(pair[1])})</text></svg>;}
