'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useStudy} from './StudyProvider';
import {Companion} from './Companion';
import {initialRecovery,problemFor,isCorrect,answerInputIssue,nextFreshSerial,pairKey,TOPICS,type Topic} from '@/lib/recovery';
import {DEVICE_RESET_KEY} from '@/lib/device-data';
import {skillKey} from '@/lib/study';
import {khanEntry,KHAN_ENTRIES} from '@/lib/khan-entry';
import {MathText} from '@/components/math/Math';
import {GraphBoard} from '@/components/product/GraphBoard';
import {AnswerFields} from '@/components/product/AnswerFields';
type Turn={correct:boolean;help:boolean};type Game={version:1;players:string[];topic:Topic;serial:number;turns:Turn[];limit:number};
const KEY='backtrack.together.v1';
const valid=(v:unknown):v is Game=>{if(!v||typeof v!=='object')return false;const g=v as Game;return g.version===1&&Array.isArray(g.players)&&g.players.length>=2&&g.players.length<=4&&g.players.every(p=>typeof p==='string'&&p.length>0&&p.length<=24)&&Object.hasOwn(TOPICS,g.topic)&&Number.isInteger(g.serial)&&g.serial>=0&&g.serial<100000&&Array.isArray(g.turns)&&g.turns.length<=8&&g.turns.every(t=>!!t&&typeof t.correct==='boolean'&&typeof t.help==='boolean')&&Number.isInteger(g.limit)&&g.limit>=2&&g.limit<=8;};
export function StudyTogether(){
 const {state,ready,update}=useStudy();const [players,setPlayers]=useState(''),[topic,setTopic]=useState<Topic>('quadratics'),[game,setGame]=useState<Game>(),[loaded,setLoaded]=useState(false),[values,setValues]=useState<string[]>([]),[help,setHelp]=useState(false),[checked,setChecked]=useState(false),[error,setError]=useState(''),[reaction,setReaction]=useState('');
 useEffect(()=>{try{const raw=JSON.parse(localStorage.getItem(KEY)??'null');if(valid(raw))setGame(raw);}catch{}setLoaded(true);const clear=()=>setGame(undefined);const sync=(e:StorageEvent)=>{if(e.key===DEVICE_RESET_KEY)clear();};window.addEventListener('backtrack:cleared',clear);window.addEventListener('storage',sync);return()=>{window.removeEventListener('backtrack:cleared',clear);window.removeEventListener('storage',sync);};},[]);
 useEffect(()=>{if(!loaded)return;try{if(game)localStorage.setItem(KEY,JSON.stringify(game));else localStorage.removeItem(KEY);}catch{}},[game,loaded]);
 const active=game?{...initialRecovery(game.topic),serial:game.serial,exposedPairs:state.pairs[game.topic]??[],sharedSerialFloor:state.cursors[game.topic]??0}:undefined;
 const question=active?problemFor(active):undefined;
 useEffect(()=>{setValues(question?.labels.map(()=>'')??[]);setHelp(false);setChecked(false);setReaction('');},[question?.id]);
 function reserve(){if(!game||!question)return;update(s=>({...s,seen:[...new Set([...s.seen,`${skillKey(game.topic,'goal')}:${question.expression}`])],pairs:question.factorPair?{...s.pairs,[game.topic]:[...new Set([...(s.pairs[game.topic]??[]),pairKey(question.factorPair)])]}:s.pairs,cursors:{...s.cursors,[game.topic]:Math.max(s.cursors[game.topic]??0,game.serial+1)},updatedAt:Date.now()}));}
 function next(){if(!game||!question)return;const turns=[...game.turns,{correct:isCorrect(question,values),help}];reserve();const nextState={...initialRecovery(game.topic),exposedPairs:state.pairs[game.topic]??[],sharedSerialFloor:state.cursors[game.topic]??0};setGame({...game,turns,serial:nextFreshSerial(nextState,game.serial+1)});}
 if(!loaded||!ready)return <p className="study-loading">Opening the study table…</p>;
 if(!game)return <div className="study-space together-page"><p className="eyebrow">Study together</p><h1>One screen.<br/>A few useful turns.</h1><p className="together-intro">Take turns with someone beside you. Talk through the difficult bits and finish a short round together.</p><div className="together-setup"><Companion size={150}/><form onSubmit={e=>{e.preventDefault();const names=players.split(',').map(x=>x.trim()).filter(Boolean);if(names.length<2||names.length>4||names.some(n=>n.length>24)){setError('Add two to four short names, separated by commas.');return;}const base={...initialRecovery(topic),exposedPairs:state.pairs[topic]??[],sharedSerialFloor:state.cursors[topic]??0};setGame({version:1,players:names,topic,serial:nextFreshSerial(base,Math.max(1,state.cursors[topic]??0)),turns:[],limit:names.length*2});setError('');}}><label>Who is at the study table?<input value={players} onChange={e=>setPlayers(e.target.value)} placeholder="Name, name" maxLength={100} required/></label><label>Choose a topic<select value={topic} onChange={e=>setTopic(e.target.value as Topic)}>{[['maths','Mathematics'],['chemistry','Chemistry'],['physics','Physics']].map(([subject,heading])=><optgroup key={subject} label={heading}>{Object.entries(TOPICS).filter(([,t])=>t.subject===subject).map(([id,t])=><option key={id} value={id}>{t.label}</option>)}</optgroup>)}</select></label>{error&&<p role="alert">{error}</p>}<button className="button-primary">Start taking turns ↗</button></form></div><div className="together-share-note"><h2>Studying on different devices?</h2><p>Share the same pack. Everyone gets their own checks, help, and reviewer.</p><Link className="button-secondary" href="/packs">Choose a pack to share ↗</Link></div></div>;
 if(game.turns.length>=game.limit)return <div className="session-complete"><Companion size={145}/><p className="eyebrow">Round finished together</p><h1>You gave the topic a proper go.</h1><p>{game.turns.length} turns completed · {game.turns.filter(t=>t.correct&&!t.help).length} correct without the explanation · {game.turns.filter(t=>t.help).length} with help.</p><p>Take the ideas into your own fresh study round when you are ready.</p><div className="session-finish-actions"><Link className="button-primary" href="/study">Study on my own ↗</Link><button className="button-secondary" onClick={()=>setGame(undefined)}>Another study table</button><Link className="button-text" href="/">Done for now</Link></div></div>;
 const entry=KHAN_ENTRIES.find(e=>e.topic===game.topic&&e.skill==='goal');
 return <div className="study-space together-round"><div className="together-turn"><div><p className="eyebrow">{TOPICS[game.topic].label} · Turn {game.turns.length+1} of {game.limit}</p><h1>{game.players[game.turns.length%game.players.length]}’s turn.</h1></div><button className="button-text" onClick={()=>setGame(undefined)}>Finish here</button></div><p className="quiet">Pass the screen when the turn is finished. There is no timer.</p><progress value={game.turns.length} max={game.limit} aria-label="Group turns finished"/><section className="together-question"><h2>{question!.prompt}</h2>{question!.graph?<GraphBoard graph={question!.graph} guide={help}/>:<MathText size="hero" speak={question!.speak}>{question!.expression}</MathText>}<form onSubmit={e=>{e.preventDefault();const issue=answerInputIssue(question!,values);if(issue){setError(issue);return;}reserve();setError('');setChecked(true);}}><div className={`answer-inputs ${question!.fields?.some(f=>f.kind==='choice')?'stacked-answers':''}`}><AnswerFields p={question!} values={values} onChange={(i,v)=>{setValues(xs=>xs.map((x,j)=>i===j?v:x));setChecked(false);}}/></div>{error&&<p role="alert">{error}</p>}<button className="button-primary">Check together</button><button type="button" className="button-text" onClick={()=>{reserve();setHelp(true);}}>Work through it together</button></form>{help&&<p className="concept-explanation">{question!.explanation}</p>}{checked&&<div className="challenge-feedback"><h3>{isCorrect(question!,values)?'That answer fits.':'Here is the step to revisit.'}</h3>{!isCorrect(question!,values)&&<p>{question!.hint}</p>}<button className="button-primary" onClick={next}>Pass the turn ↗</button></div>}</section><div className="together-encouragement">{['Nice catch','Let’s try it together','Your turn'].map(text=><button key={text} onClick={()=>setReaction(text)}>{text}</button>)}<span role="status">{reaction}</span></div>{entry?<p className="together-khan">Want another explanation? <a href={entry.learning.url} target="_blank" rel="noopener noreferrer">Open the matched Khan activity ↗</a></p>:<p className="together-khan">No reviewed Khan Academy activity is matched to this topic yet. Work through the explanation here together.</p>}</div>;
}
