'use client';
import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Companion} from './Companion';
import {useStudy} from './StudyProvider';
const STEPS=[
 {selector:'.intent-choices',title:'Choose what would help today.',body:'Start with something new, prepare your quiz scope, or work through one step. You can use Dunlo before you get stuck.'},
 {selector:'a[href="/packs"]',title:'Keep your topics in a pack.',body:'My packs keeps your topics, quiz date and source notes together. Check the coverage receipt so missing topics stay visible.'},
 {selector:'a[href="/review"]',title:'Come back for a fresh question.',body:'Review keeps useful steps for another look. Your place is saved in this browser; a missed day does not erase your work.'}
];
export function WelcomeTour(){const {ready,state,update}=useStudy();const [step,setStep]=useState(-2),[rect,setRect]=useState<{x:number;y:number;w:number;h:number}>(),[size,setSize]=useState({w:typeof window==='undefined'?390:window.innerWidth,h:typeof window==='undefined'?844:window.innerHeight}),[tipHeight,setTipHeight]=useState(350);const dialog=useRef<HTMLDivElement>(null),target=useRef<HTMLElement|null>(null),previous=useRef<HTMLElement|null>(null);
 const active=step>=-1;
 function close(){setStep(-2);const url=new URL(window.location.href);if(url.searchParams.has('tour')){url.searchParams.delete('tour');history.replaceState(history.state,'',url.href);}update(s=>({...s,settings:{...s.settings,tourDone:true},updatedAt:Date.now()}));previous.current?.focus();}
 useEffect(()=>{if(ready&&(!state.settings.tourDone||new URLSearchParams(window.location.search).get('tour')==='1')){previous.current=document.activeElement as HTMLElement;setStep(-1);}const replay=()=>{previous.current=document.activeElement as HTMLElement;setStep(-1);};window.addEventListener('dunlo:tour',replay);return()=>window.removeEventListener('dunlo:tour',replay);},[ready]);
 useEffect(()=>{if(!active)return;
  const measure=()=>{if(dialog.current)setTipHeight(dialog.current.getBoundingClientRect().height);setSize({w:innerWidth,h:innerHeight});const el=step>=0?Array.from(document.querySelectorAll<HTMLElement>(STEPS[step].selector)).find(el=>el.getBoundingClientRect().width>0):undefined;target.current=el??null;const r=el?.getBoundingClientRect();setRect(r?{x:Math.max(5,r.x-8),y:Math.max(5,r.y-8),w:Math.min(innerWidth-10,r.width+16),h:r.height+16}:undefined);};
  if(step>=0){const el=Array.from(document.querySelectorAll<HTMLElement>(STEPS[step].selector)).find(el=>el.getBoundingClientRect().width>0);el?.scrollIntoView({block:'center',behavior:'instant'});}measure();dialog.current?.querySelector<HTMLButtonElement>('button')?.focus({preventScroll:true});
  function keys(e:KeyboardEvent){if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Tab'){const nodes=[...Array.from(dialog.current?.querySelectorAll<HTMLElement>('button')??[]),...(target.current?.matches('a,button')?[target.current]:Array.from(target.current?.querySelectorAll<HTMLElement>('a,button')??[]))];const index=nodes.indexOf(document.activeElement as HTMLElement);e.preventDefault();nodes[(index+(e.shiftKey?-1:1)+nodes.length)%nodes.length]?.focus({preventScroll:true});}}
  const chosen=()=>close();target.current?.addEventListener('click',chosen);window.addEventListener('keydown',keys);window.addEventListener('resize',measure);window.addEventListener('scroll',measure,{passive:true});return()=>{target.current?.removeEventListener('click',chosen);window.removeEventListener('keydown',keys);window.removeEventListener('resize',measure);window.removeEventListener('scroll',measure);};
 },[active,step]);
 if(!ready||!active||typeof document==='undefined')return null;
 const tipWidth=Math.min(360,size.w-28),top=rect?(rect.y+rect.h+tipHeight+32<size.h?rect.y+rect.h+16:Math.max(16,rect.y-tipHeight-18)):Math.max(20,(size.h-tipHeight)/2),left=rect?Math.min(size.w-tipWidth-14,Math.max(14,rect.x)):Math.max(14,(size.w-tipWidth)/2);
 return createPortal(<div className={`welcome-tour ${state.settings.quiet?'quiet-tour':''}`}>{rect?<><div className="tour-shade" style={{top:0,left:0,right:0,height:rect.y}}/><div className="tour-shade" style={{top:rect.y+rect.h,left:0,right:0,bottom:0}}/><div className="tour-shade" style={{left:0,top:rect.y,width:rect.x,height:rect.h}}/><div className="tour-shade" style={{left:rect.x+rect.w,right:0,top:rect.y,height:rect.h}}/><div className="tour-spotlight" style={{left:rect.x,top:rect.y,width:rect.w,height:rect.h}}/></>:<div className="tour-shade" style={{inset:0}}/>}<div ref={dialog} className="tour-dialog" role="dialog" aria-modal="true" aria-labelledby="tour-title" aria-describedby="tour-description" style={{top,left,width:tipWidth}}><button className="tour-close" aria-label="Close introduction" onClick={close}>×</button><div className={`tour-mascot ${step<0?'tour-intro':''}`}><Companion size={step<0?110:65}/></div><small>{step<0?'Meet your bookmark buddy':`${step+1} of 3 · A quick look around`}</small><h2 id="tour-title">{step<0?'Hi! Let’s find your next step.':STEPS[step].title}</h2><p id="tour-description">{step<0?'I’m your Dunlo bookmark buddy. I’ll keep your place, point to a useful idea, and help you try it on your own. Want a quick look around?':STEPS[step].body}</p><div className="tour-actions">{step>0&&<button className="button-text" onClick={()=>setStep(step-1)}>Back</button>}<button className="button-primary" onClick={()=>step===2?close():setStep(step+1)}>{step<0?'Show me around':step===2?'Ready to start':'Next pointer'}</button><button className="button-text" onClick={close}>{step<0?'Explore on my own':'Skip tour'}</button></div><small>You can replay this in My study space.</small></div></div>,document.body);
}
