'use client';
import {Headline} from './Headline';
import {useState} from 'react';
import {EXAMS,type ExamId} from '@/lib/program/admissions';
import type {CETPreferences} from '@/lib/program/store';
import {btn,cx} from './ui';

const field='min-h-11 min-w-0 w-full rounded-xl border border-navy/20 bg-white px-3 text-base text-navy focus:border-navy focus:outline-none';
/** Targets personalize planning, while the reviewer keeps one shared skill bank. */
export function CETPicker({value,onChange,today}:{value:CETPreferences;onChange:(value:CETPreferences)=>void;today:string}){
 const [adding,setAdding]=useState(false),[name,setName]=useState(''),[error,setError]=useState('');
 const toggle=(exam:ExamId)=>{const exists=value.targets.some(t=>t.exam===exam);if(!exists&&value.targets.length>=12){setError('You can keep up to 12 exam targets.');return;}setError('');const targets=exists?value.targets.filter(t=>t.exam!==exam):[...value.targets,{key:exam,exam,name:EXAMS[exam].name}];onChange({general:targets.length===0,targets});};
 return <div>
  <button type="button" aria-label="General CET review" aria-pressed={value.general} onClick={()=>onChange({...value,general:!value.general})} className="flex min-h-16 w-full items-center justify-between gap-3 rounded-2xl border-2 border-navy/15 px-4 py-3 text-left aria-pressed:border-green aria-pressed:bg-mint"><span><span className="block font-bold">General CET review</span><span className="mt-1 block text-sm text-ink-soft">Build foundations across entrance exams.</span></span><span aria-hidden="true" className="text-xl">{value.general?'✓':'+'}</span></button>
  <p className="mt-5 font-bold">Add the exams you’re preparing for</p><p className="mt-1 text-sm text-ink-soft">Choose more than one. Dates can wait.</p>
  <div role="group" aria-label="CET targets" className="mt-3 grid grid-cols-2 gap-2">{(Object.keys(EXAMS) as ExamId[]).map(exam=><button type="button" key={exam} aria-pressed={value.targets.some(t=>t.exam===exam)} onClick={()=>toggle(exam)} className="flex min-h-12 items-center justify-between gap-2 rounded-xl border border-navy/20 px-3 font-bold text-navy aria-pressed:border-green aria-pressed:bg-mint"><span>{EXAMS[exam].name}</span><span aria-hidden="true">{value.targets.some(t=>t.exam===exam)?'✓':'+'}</span></button>)}</div>
  {value.targets.length>0&&<ul className="mt-4 grid gap-3">{value.targets.map(target=><li key={target.key} className="rounded-xl bg-sky p-3"><div className="flex items-center justify-between gap-2"><span className="min-w-0 break-words font-bold">{target.name}</span><button type="button" aria-label={`Remove ${target.name}`} className="grid h-11 w-11 shrink-0 place-items-center rounded-full text-xl hover:bg-white" onClick={()=>{const targets=value.targets.filter(t=>t.key!==target.key);onChange({...value,general:targets.length===0||value.general,targets});}}>×</button></div><label className="mt-1 grid gap-1 text-sm font-semibold">{value.targets.length===1?'Planning date, if you have one':`${target.name} planning date`}<input data-cet-key={target.key} type="date" min={today} className={field} value={target.date??''} onInput={e=>onChange({...value,targets:value.targets.map(t=>t.key===target.key?{...t,date:e.currentTarget.value||undefined}:t)})} onChange={e=>onChange({...value,targets:value.targets.map(t=>t.key===target.key?{...t,date:e.target.value||undefined}:t)})}/></label></li>)}</ul>}
  {adding?<div className="mt-3 grid gap-2 rounded-xl border border-navy/15 p-3"><label className="grid gap-1 text-sm font-semibold">CET or school name<input className={field} value={name} maxLength={60} autoFocus placeholder="For example, your school’s entrance exam" onChange={e=>setName(e.target.value)}/></label><div className="flex flex-wrap gap-2"><button type="button" className={btn.dark} onClick={()=>{const clean=name.trim();if(!clean)return setError('Enter an exam or school name.');if(value.targets.some(t=>t.name.toLowerCase()===clean.toLowerCase()))return setError('That exam is already in your list.');if(value.targets.length>=12)return setError('You can keep up to 12 exam targets.');const known=(Object.keys(EXAMS) as ExamId[]).find(id=>EXAMS[id].name.toLowerCase()===clean.toLowerCase());onChange({general:false,targets:[...value.targets,known?{key:known,name:EXAMS[known].name,exam:known}:{key:`own-${crypto.randomUUID()}`,name:clean}]});setName('');setAdding(false);setError('');}}><Headline>Add CET</Headline></button><button type="button" className={btn.ghost} onClick={()=>{setAdding(false);setError('');}}><Headline>Cancel</Headline></button></div>{error&&<p role="alert" className="text-sm font-semibold">{error}</p>}</div>:<button type="button" className={cx(btn.text,'mt-2')} onClick={()=>setAdding(true)}><Headline>+ Add another CET</Headline></button>}
  {!adding&&error&&<p role="alert" className="mt-2 text-sm font-semibold">{error}</p>}<p className="mt-3 text-xs leading-relaxed text-ink-soft">Review and practice cover shared foundations, not each exam’s exact format. Your targets are personal planning dates.</p>
 </div>;
}
