'use client';
import {Headline} from './Headline';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {useCallback,useEffect,useRef,useState} from 'react';
import {useProgram} from './ProgramProvider';
import {PageBand,Sheet,btn,cx,pageBody,Pill} from './ui';
import {GroupError,groupAction,groupCode,type GroupAction,type GroupSnapshot} from '@/lib/groups';
import {addDays,parseDay} from '@/lib/program/planner';
import {formFromKey} from '@/lib/mock/forms';
import {scoreAttempt} from '@/lib/mock/scoring';
import {shareCardPng} from '@/lib/share-card';

const field='min-h-12 min-w-0 w-full rounded-xl border border-navy/20 bg-white px-3 text-base text-navy focus:border-navy focus:outline-none';
const disabled='disabled:cursor-wait disabled:opacity-50';

export function LiveStudyGroup(){
 const {state,update,today}=useProgram(),params=useSearchParams();
 const [snapshot,setSnapshot]=useState<GroupSnapshot|null>(null),[loading,setLoading]=useState(!!state.group),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [nickname,setNickname]=useState(''),[name,setName]=useState(''),[goal,setGoal]=useState('4'),[invite,setInvite]=useState(params.get('join')??state.group?.code??'');
 const [include,setInclude]=useState({days:true,missions:false,mock:false}),[editing,setEditing]=useState<'name'|'goal'|null>(null),[leaving,setLeaving]=useState(false),[joinHere,setJoinHere]=useState(false);
 const [synced,setSynced]=useState('');
 const mounted=useRef(true),fetching=useRef(false),code=state.group?.code,currentCode=useRef(code);
 currentCode.current=code;
 const incoming=params.get('join')?.toUpperCase();
 const apply=useCallback((data:GroupSnapshot)=>{
  setSnapshot(data);currentCode.current=data.group.code;setSynced(new Date().toLocaleTimeString('en-PH',{timeZone:'Asia/Manila',hour:'numeric',minute:'2-digit'}));
  update(s=>s.group?.code===data.group.code&&s.group.goal===data.group.goal?s:{...s,group:{code:data.group.code,goal:data.group.goal,joinedAt:s.group?.code===data.group.code?s.group.joinedAt:Date.now()}});
 },[update]);
 const refresh=useCallback(async()=>{
  if(!code||fetching.current)return;fetching.current=true;
  try{const data=await groupAction('snapshot',{code});if(mounted.current&&data&&currentCode.current===code){apply(data);setError('');}}
  catch(e){if(mounted.current&&currentCode.current===code){setError(e instanceof GroupError&&e.status===404?'That saved code is from the earlier on-device group flow. Create a live group or use a friend’s new invite.':e instanceof Error?e.message:'Couldn’t open your group.');if(e instanceof GroupError&&(e.status===403||e.status===404)){setJoinHere(true);setSnapshot(null);}}}
  finally{fetching.current=false;if(mounted.current)setLoading(false);}
 },[code,apply]);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 useEffect(()=>{if(incoming&&groupCode(incoming)&&new URL(location.href).searchParams.get('join')?.toUpperCase()===incoming){setInvite(incoming);if(code&&incoming!==code)setJoinHere(true);}},[incoming,code]);
 useEffect(()=>{
  if(!code){setLoading(false);setSnapshot(null);return;}void refresh();
  const tick=()=>{if(document.visibilityState==='visible'&&!fetching.current)void refresh();};
  const timer=setInterval(tick,15000);document.addEventListener('visibilitychange',tick);window.addEventListener('focus',tick);
  return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',tick);window.removeEventListener('focus',tick);};
 },[code,refresh]);
 async function run(action:GroupAction,payload:Record<string,unknown>,success:string){
  if(busy)return;if(['create','join','rename'].includes(action)&&(typeof payload.nickname!=='string'||!payload.nickname.trim())){setError('Choose a nickname so your friends know who joined.');return false;}setBusy(true);setError('');setMessage('');
  try{if(action==='create'){const signature=JSON.stringify(payload);let pending;try{pending=JSON.parse(localStorage.getItem('backtrack.group-create.pending')||'null');}catch{}const requestId=pending?.signature===signature&&typeof pending.requestId==='string'?pending.requestId:crypto.randomUUID();localStorage.setItem('backtrack.group-create.pending',JSON.stringify({signature,requestId}));payload={...payload,requestId};}const data=await groupAction(action,payload);if(action==='create')localStorage.removeItem('backtrack.group-create.pending');if(action==='leave'){currentCode.current=undefined;update(s=>({...s,group:undefined}));setSnapshot(null);setJoinHere(false);setLeaving(false);setInvite('');setMessage('You left the group.');}else if(data){apply(data);setJoinHere(false);setMessage(success);setEditing(null);const url=new URL(location.href);if(url.searchParams.has('join')){url.searchParams.delete('join');history.replaceState(history.state,'',url.href);}}if(['create','join','leave'].includes(action))window.scrollTo({top:0,behavior:'instant'});return true;}
  catch(e){if(action==='create'&&e instanceof GroupError&&e.status===409&&e.message.startsWith('Please try'))try{localStorage.removeItem('backtrack.group-create.pending');}catch{}setError(e instanceof Error?e.message:'The group action could not be completed.');return false;}
  finally{setBusy(false);}
 }
 const g=snapshot?.group,me=snapshot?.members.find(m=>m.isMe),week=snapshot?.weekStart??today,end=addDays(week,6);
 const days=state.studyDays.filter(d=>d>=week&&d<=end).length;
 const missions=Object.entries(state.missions).filter(([d,v])=>d>=week&&d<=end&&v.recall&&v.khan&&v.exit).length;
 const latest=state.attempts.filter(a=>a.submittedAt&&['full','section','fixed'].includes(formFromKey(a.formKey)?.kind??'')).sort((a,b)=>b.submittedAt!-a.submittedAt!)[0],form=latest?formFromKey(latest.formKey):null;
 const mock=latest&&form?scoreAttempt(form,latest).total:undefined;
 const link=g&&typeof window!=='undefined'?`${location.origin}/group?join=${g.code}`:'';
 const connect=!snapshot||joinHere;
 const shareValues={studyDays:include.days?days:null,missions:include.missions?missions:null,mockCorrect:include.mock&&mock?mock.correct:null,mockTotal:include.mock&&mock?mock.total:null};
 async function card(){setError('');const lines=[];if(include.days)lines.push({label:'Study days this week',value:`${days}/${g?.goal??4}`,fill:days/(g?.goal??4)});if(include.missions)lines.push({label:'Full missions',value:String(missions)});if(include.mock&&mock)lines.push({label:'Latest mock',value:`${mock.correct}/${mock.total}`,fill:mock.correct/mock.total});try{const blob=await shareCardPng({title:'My weekly check-in',subtitle:g?.name??'Study group',lines,footer:'Khanpanion · Practice for what comes next.'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='khanpanion-check-in.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Card downloaded.');}catch{setError('The card could not be made. Your group check-in is still here.');}}
 return <><PageBand title={g&&!joinHere?g.name:'Study with friends'} lead={g&&!joinHere?`${snapshot!.members.length} ${snapshot!.members.length===1?'member':'members'} · ${g.goal} study days a week`:'Create a group or join with an invite. Set a shared weekly goal and see the check-ins your friends post.'}/><div className={pageBody}>
  {error&&<div role="alert" className="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-mint p-4 font-semibold text-navy"><p>{error}</p>{code&&!joinHere&&<button className={btn.text} onClick={()=>void refresh()}><Headline>Try again</Headline></button>}</div>}
  {message&&<p role="status" className="mb-5 rounded-2xl bg-mint px-4 py-3 font-semibold text-navy">{message}</p>}
  {loading&&!snapshot?<Sheet><p role="status">Opening your shared group…</p></Sheet>:connect?<>
   <Sheet className="mb-5"><label className="grid max-w-md gap-2 font-bold">Your nickname<input className={field} maxLength={32} value={nickname} onChange={e=>setNickname(e.target.value)} placeholder="What should your friends call you?" autoComplete="nickname"/></label><p className="mt-2 text-sm text-ink-soft">Your nickname and posted check-ins are visible to the group. Your answers and notes stay on this device.</p>{g&&joinHere&&<button className={cx(btn.text,'mt-3')} onClick={()=>setJoinHere(false)}><Headline>Return to {g.name}</Headline></button>}</Sheet>
   <div className="grid gap-5 md:grid-cols-2"><Sheet><h2 className="text-2xl font-extrabold"><Headline>Start a group</Headline></h2><form className="mt-5 grid gap-4" onSubmit={e=>{e.preventDefault();void run('create',{name,nickname,goal:Number(goal)},'Your group is ready. Share its invite with your friends.');}}><label className="grid gap-2 font-semibold">Group name<input className={field} required maxLength={60} value={name} onChange={e=>setName(e.target.value)} placeholder="For example, Friday review"/></label><label className="grid gap-2 font-semibold">Study days each week, per person<input type="number" min={1} max={7} required className={field} value={goal} onChange={e=>setGoal(e.target.value)}/></label><button disabled={busy} className={cx(btn.primary,disabled,'justify-self-start')}><Headline>{busy?'Connecting…':'Create my group'}</Headline></button></form></Sheet>
    <Sheet><h2 className="text-2xl font-extrabold"><Headline>Join your friends</Headline></h2><p className="mt-2 text-ink-soft">Paste their six-character code or invite link.</p><form className="mt-5 grid gap-4" onSubmit={e=>{e.preventDefault();const parsed=groupCode(invite);if(!parsed)return setError('Paste a six-character code or a group invite link.');void run('join',{code:parsed,nickname},'You joined the group.');}}><label className="grid gap-2 font-semibold">Group code or invite link<input className={field} required value={invite} maxLength={300} onChange={e=>setInvite(e.target.value)} placeholder="ABC234 or a group invite link" autoComplete="off"/></label><button disabled={busy} className={cx(btn.dark,disabled,'justify-self-start')}><Headline>{busy?'Connecting…':'Join group'}</Headline></button></form></Sheet></div>
  </>:g&&snapshot?<div className="grid min-w-0 gap-5 lg:grid-cols-[1.2fr_1fr]">
   <div className="grid min-w-0 content-start gap-5"><Sheet className="min-w-0"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-extrabold"><Headline>Your group this week</Headline></h2><button className={btn.text} disabled={busy} onClick={()=>void refresh()}><Headline>Refresh</Headline></button></div><p className="mt-1 text-sm text-ink-soft">Week of {parseDay(week).toLocaleDateString('en-PH',{month:'short',day:'numeric'})}. Updates while this page is open.{synced?` Last checked ${synced}.`:''}</p>
    <ul className="mt-5 divide-y divide-navy/10">{snapshot.members.map(member=><li key={member.id} className="py-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="break-words font-bold">{member.nickname}{member.isMe?' (you)':''}</p>{member.isOwner&&<Pill>Group leader</Pill>}</div>{member.checkin?<><div className="mt-2 flex flex-wrap gap-3 text-sm text-ink-soft">{member.checkin.studyDays!==null&&<span>{member.checkin.studyDays} of {g.goal} study days</span>}{member.checkin.missions!==null&&<span>{member.checkin.missions} missions</span>}{member.checkin.mockTotal!==null&&<span>Latest mock: {member.checkin.mockCorrect}/{member.checkin.mockTotal}</span>}</div>{member.checkin.studyDays!==null&&<div className="mt-3"><div role="img" aria-label={`${member.nickname}: ${member.checkin.studyDays} of ${g.goal} days`} className="flex gap-1">{Array.from({length:g.goal},(_,i)=><span key={i} className={cx('h-1.5 w-7 rounded-sm',i<Math.min(member.checkin?.studyDays??0,g.goal)?'bg-green':'bg-navy/15')}/>)}</div></div>}</>:<p className="mt-2 text-sm text-ink-soft">No check-in posted yet.</p>}</li>)}</ul><p className="mt-3 text-xs text-ink-soft">These are the check-ins members chose to share.</p></Sheet>
    <Sheet className="min-w-0"><h2 className="text-xl font-extrabold"><Headline>Invite a friend</Headline></h2><div className="mt-3 flex flex-wrap items-center gap-3"><code className="text-2xl font-bold tracking-[.15em]">{g.code}</code><button className={btn.ghost} onClick={async()=>{try{await navigator.clipboard.writeText(link);setMessage('Invite link copied.');}catch{setMessage('Copy the invite link below.');}}}><Headline>Copy invite link</Headline></button></div><input aria-label="Your group invite link" className={cx(field,'mt-3 text-sm')} readOnly value={link}/></Sheet>
   </div>
   <div className="grid min-w-0 content-start gap-5"><Sheet className="min-w-0"><h2 className="text-xl font-extrabold"><Headline>Post your weekly check-in</Headline></h2><p className="mt-2 text-sm text-ink-soft">Choose what your friends can see. Posting updates your check-in for this week.</p><div className="mt-4 grid gap-2">{([['days',`Study days: ${days} of ${g.goal}`],['missions',`Full missions: ${missions}`],['mock',mock?`Latest mock: ${mock.correct}/${mock.total}`:'Latest mock: no result yet']] as const).map(([key,label])=><label key={key} className="flex min-h-12 items-center gap-3"><input type="checkbox" checked={include[key]} disabled={key==='mock'&&!mock} onChange={e=>setInclude({...include,[key]:e.target.checked})} className="h-5 w-5 accent-[#14bf96]"/>{label}</label>)}</div><div className="mt-5 flex flex-wrap gap-2"><button className={cx(btn.primary,disabled)} disabled={busy||!Object.values(shareValues).some(v=>v!==null)} onClick={()=>void run('checkin',{code:g.code,...shareValues},'Your check-in is visible to your group.')}><Headline>{busy?'Working…':me?.checkin?'Update my check-in':'Post my check-in'}</Headline></button><button className={btn.ghost} disabled={busy} onClick={()=>void card()}><Headline>Download a card</Headline></button></div></Sheet>
    <Sheet className="min-w-0"><h2 className="text-xl font-extrabold"><Headline>Group settings</Headline></h2>{editing?<form className="mt-4 grid gap-3" onSubmit={e=>{e.preventDefault();void run(editing==='name'?'rename':'goal',{code:g.code,...(editing==='name'?{nickname}:{goal:Number(goal)})},'Group settings updated.');}}><label className="grid gap-2 font-semibold">{editing==='name'?'Your new nickname':'Shared study days each week'}<input className={field} type={editing==='name'?'text':'number'} min={editing==='goal'?1:undefined} max={editing==='goal'?7:undefined} maxLength={editing==='name'?32:undefined} required value={editing==='name'?nickname:goal} onChange={e=>editing==='name'?setNickname(e.target.value):setGoal(e.target.value)}/></label><div className="flex gap-2"><button disabled={busy} className={btn.dark}><Headline>Save changes</Headline></button><button type="button" className={btn.ghost} onClick={()=>setEditing(null)}><Headline>Cancel</Headline></button></div></form>:<div className="mt-3 grid justify-items-start gap-1"><button className={btn.text} onClick={()=>{setNickname(me?.nickname??'');setEditing('name');}}><Headline>Change my nickname</Headline></button>{g.isOwner&&<button className={btn.text} onClick={()=>{setGoal(String(g.goal));setEditing('goal');}}><Headline>Change the shared goal</Headline></button>}<button className={btn.text} onClick={()=>{setJoinHere(true);setNickname(me?.nickname??'');setInvite('');}}><Headline>Join another group</Headline></button>{leaving?<div className="mt-2 rounded-xl bg-sky p-3"><p className="text-sm">Leave this group? If you lead it, the next member becomes leader. You can rejoin with its code.</p><div className="mt-3 flex flex-wrap gap-2"><button className={btn.dark} disabled={busy} onClick={()=>void run('leave',{code:g.code},'You left the group.')}><Headline>Yes, leave group</Headline></button><button className={btn.ghost} onClick={()=>setLeaving(false)}><Headline>Stay</Headline></button></div></div>:<button className={btn.text} onClick={()=>setLeaving(true)}><Headline>Leave this group</Headline></button>}</div>}</Sheet>
   </div>
  </div>:null}
  <Sheet className="mt-5"><h2 className="text-xl font-extrabold"><Headline>Study together in person</Headline></h2><div className="mt-3 flex flex-wrap gap-2"><Link className={btn.ghost} href="/together"><Headline>Take turns on one phone</Headline></Link><Link className={btn.ghost} href="/challenge"><Headline>Send a challenge</Headline></Link><Link className={btn.ghost} href={`/mock/print?f=full~${today.replace(/-/g,'')}`}><Headline>Print a mock for a study session</Headline></Link></div></Sheet>
 </div></>;
}
