/** Reference sheets and handbooks in the reviewer. Drafts until the team signs off. */
export type Extra={id:string;title:string;blurb:string;sections:{heading:string;rows?:[string,string][];items?:string[]}[];author:string;reviewer:string;status:'draft'|'reviewed';createdAt:string};
const X=(e:Omit<Extra,'author'|'reviewer'|'status'|'createdAt'>):Extra=>({...e,author:'Khanpanion team',reviewer:'',status:'draft',createdAt:'2026-09-30'});

export const EXTRAS:Extra[]=[
 X({id:'x_formulas_math',title:'Math formula sheet',blurb:'Every formula the math subtest leans on, on one printable page.',sections:[
  {heading:'Numbers and percent',rows:[['Percent of a number','$r\\%\\text{ of }N = N \\times \\frac{r}{100}$'],['Percent change','$(\\text{new} - \\text{old}) \\div \\text{old} \\times 100$'],['Increase by $r\\%$','$\\times \\left(1 + \\frac{r}{100}\\right)$'],['Decrease by $r\\%$','$\\times \\left(1 - \\frac{r}{100}\\right)$'],['Simple interest','$I = Prt$'],['Compound interest','$A = P(1 + r)^{t}$'],['Ratio share','$\\text{total} \\times \\text{part} \\div \\text{sum of parts}$']]},
  {heading:'Algebra',rows:[['Exponents','$x^{a}x^{b} = x^{a + b}$, $x^{a} \\div x^{b} = x^{a - b}$, $(x^{a})^{b} = x^{ab}$, $x^{0} = 1$'],['Square of a sum','$(a + b)^2 = a^2 + 2ab + b^2$'],['Difference of squares','$a^2 - b^2 = (a + b)(a - b)$'],['Quadratic formula','$x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}$'],['Sum and product of roots','$\\text{sum} = -\\frac{b}{a}$, $\\text{product} = \\frac{c}{a}$'],['Arithmetic sequence','$a_n = a_1 + (n - 1)d$, $S_n = \\frac{n(a_1 + a_n)}{2}$'],['Geometric sequence','$a_n = a_1r^{n - 1}$']]},
  {heading:'Lines and functions',rows:[['Slope','$m = \\frac{y_2 - y_1}{x_2 - x_1}$'],['Slope-intercept form','$y = mx + b$'],['Point-slope form','$y - y_1 = m(x - x_1)$'],['Parallel, perpendicular','same $m$; $m_1m_2 = -1$'],['Distance','$\\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$'],['Midpoint','$\\left(\\frac{x_1 + x_2}{2}, \\frac{y_1 + y_2}{2}\\right)$']]},
  {heading:'Geometry',rows:[['Triangle','$A = \\frac{1}{2}bh$; angles sum to $180^\\circ$'],['Pythagorean theorem','$a^2 + b^2 = c^2$'],['Circle','$A = \\pi r^2$, $C = 2\\pi r$'],['Trapezoid','$A = \\frac{1}{2}(a + b)h$'],['Polygon interior angles','$(n - 2) \\times 180^\\circ$'],['Cylinder, cone','$V = \\pi r^2h$, $V = \\frac{1}{3}\\pi r^2h$'],['Sphere','$V = \\frac{4}{3}\\pi r^3$, $\\mathrm{SA} = 4\\pi r^2$']]},
  {heading:'Trigonometry',rows:[['SOH CAH TOA','$\\sin = \\frac{O}{H}$, $\\cos = \\frac{A}{H}$, $\\tan = \\frac{O}{A}$'],['Special angles','$\\sin 30^\\circ = \\frac{1}{2}$, $\\cos 60^\\circ = \\frac{1}{2}$, $\\sin 45^\\circ = \\cos 45^\\circ = \\frac{\\sqrt{2}}{2}$, $\\tan 45^\\circ = 1$'],['Identity','$\\sin^2\\theta + \\cos^2\\theta = 1$']]},
  {heading:'Statistics and probability',rows:[['Mean','$\\text{sum} \\div \\text{count}$'],['Median','middle value after sorting'],['Probability','$\\text{favourable} \\div \\text{total}$'],['And (independent)','$P(A) \\times P(B)$'],['Or (exclusive)','$P(A) + P(B)$'],['Counting','$m$ ways then $n$ ways gives $m \\times n$ ways']]}]}),
 X({id:'x_formulas_science',title:'Science formulas and constants',blurb:'Physics and chemistry equations with the units that keep them straight.',sections:[
  {heading:'Motion and forces',rows:[['Speed','$v = \\frac{d}{t}$'],['Acceleration','$a = \\frac{v - u}{t}$'],['Uniform acceleration','$v = u + at$, $d = ut + \\frac{1}{2}at^2$, $v^2 = u^2 + 2ad$'],['Newton’s second law','$F = ma$'],['Weight','$W = mg$, $g = 9.8\\,\\mathrm{m/s^{2}}$'],['Momentum','$p = mv$']]},
  {heading:'Energy',rows:[['Work','$W = Fd$'],['Kinetic energy','$\\mathrm{KE} = \\frac{1}{2}mv^2$'],['Potential energy','$\\mathrm{PE} = mgh$'],['Power','$P = \\frac{W}{t}$'],['Heat','$Q = mc\\Delta T$, $c_{\\text{water}} = 4.18\\,\\mathrm{J/(g\\,^{\\circ}C)}$']]},
  {heading:'Electricity and waves',rows:[['Ohm’s law','$V = IR$'],['Electric power','$P = VI$'],['Series resistors','$R = R_1 + R_2$'],['Parallel resistors','$\\frac{1}{R} = \\frac{1}{R_1} + \\frac{1}{R_2}$'],['Wave speed','$v = f\\lambda$']]},
  {heading:'Chemistry',rows:[['Moles','$n = \\frac{m}{M}$'],['Molarity','$M = \\frac{\\text{mol}}{\\text{L}}$'],['Dilution','$M_1V_1 = M_2V_2$'],['Boyle’s law','$P_1V_1 = P_2V_2$'],['Charles’s law','$\\frac{V_1}{T_1} = \\frac{V_2}{T_2}$ (kelvin)'],['Ideal gas','$PV = nRT$'],['pH','$\\mathrm{pH} = -\\log[\\mathrm{H^{+}}]$; $\\mathrm{pH} + \\mathrm{pOH} = 14$'],['Avogadro’s number','$6.02 \\times 10^{23}$ per mole'],['Kelvin','$K = {}^{\\circ}\\mathrm{C} + 273$']]},
  {heading:'Atomic masses used in Khanpanion questions',rows:[['H 1, C 12, N 14, O 16','Na 23, Mg 24, Al 27, S 32, Cl 35.5, Ca 40']]}]}),
 X({id:'x_grammar_en',title:'English grammar guide',blurb:'The rules language questions test most, with one example each.',sections:[
  {heading:'Agreement',rows:[['Find the real subject','The box of pencils is on the desk.'],['Each, every, one: singular','Each of the students has a locker.'],['Or, nor: nearer subject','Neither the coach nor the players are ready.'],['Pronoun agreement','Every student should bring his or her ID.']]},
  {heading:'Verbs',rows:[['Past perfect for the earlier past','She had left before we arrived.'],['Unreal condition','If I were you, I would rest.'],['After a preposition, -ing','I look forward to seeing you.'],['Modal + have + past participle','You should have called.']]},
  {heading:'Sentences',rows:[['Comma splice','Wrong: I studied, I passed. Right: I studied, so I passed.'],['Fragment','Wrong: Because I was late. Right: I ran because I was late.'],['Dangling modifier','Wrong: Walking home, the rain fell. Right: Walking home, I got caught in the rain.'],['Parallelism','She likes reading, swimming, and biking.']]},
  {heading:'Usage',rows:[['affect / effect','The rain affected the game. The effect was a delay.'],['fewer / less','fewer people, less time'],['its / it’s','its cover; it’s late'],['between you and me','Prepositions take object pronouns.'],['good / well','She did well. The food is good.']]}]}),
 X({id:'x_grammar_fil',title:'Gabay sa gramatikang Filipino',blurb:'Ng at nang, din at rin, aspekto at pokus, sa isang pahina.',sections:[
  {heading:'Ng at nang',rows:[['Ng: layon','Bumili ng tinapay.'],['Ng: pagmamay-ari','Aklat ng guro.'],['Nang: paraan','Tumakbo nang mabilis.'],['Nang: noong','Nang dumating siya, umulan.'],['Nang: pag-uulit','Kain nang kain.']]},
  {heading:'Din/rin, daw/raw, dito/rito',rows:[['Pagkatapos ng patinig o w, y','rin, raw, rito, roon: ako rin, ikaw raw'],['Pagkatapos ng katinig','din, daw, dito, doon: aalis din, bukas daw']]},
  {heading:'Aspekto ng pandiwa',rows:[['Perpektibo','kumain, naglaro'],['Imperpektibo','kumakain, naglalaro'],['Kontemplatibo','kakain, maglalaro']]},
  {heading:'Pokus ng pandiwa',rows:[['Aktor','Nagluto si Nanay ng adobo.'],['Layon','Niluto ni Nanay ang adobo.'],['Ganapan','Pinaglutuan ni Nanay ng adobo ang kaldero.'],['Tagatanggap','Ipinagluto ni Nanay ng adobo si Ben.'],['Gamit','Ipinangluto ni Nanay ang bagong kaldero.']]},
  {heading:'Gitling',items:['Sa pagitan ng panlaping nagtatapos sa katinig at salitang-ugat na nagsisimula sa patinig: mag-aral, pag-asa.','Sa pag-uulit ng salita: araw-araw, isa-isa.','Sa pagitan ng panlapi at pangngalang pantangi: maka-Rizal.']}]}),
 X({id:'x_vocab',title:'Vocabulary list',blurb:'Sixty words that show up in academic reading, with plain meanings.',sections:[
  {heading:'A to E',rows:[['abate','become less intense'],['abundant','plentiful'],['adverse','harmful, unfavourable'],['advocate','support publicly; a supporter'],['ambiguous','having more than one meaning'],['ambivalent','having mixed feelings'],['anomaly','something unusual'],['arbitrary','based on chance, not reason'],['benevolent','kind, generous'],['brevity','shortness'],['candid','honest, frank'],['coherent','logical and consistent'],['concede','admit something is true'],['conspicuous','easy to notice'],['contemporary','of the present time'],['corroborate','confirm with evidence'],['deter','discourage'],['diligent','hardworking and careful'],['discern','notice or understand'],['elusive','hard to find or grasp'],['ephemeral','short-lived'],['erratic','unpredictable']]},
  {heading:'F to O',rows:[['feasible','possible to do'],['frugal','careful with money'],['futile','useless'],['garrulous','very talkative'],['hinder','get in the way of'],['imminent','about to happen'],['impartial','fair, not taking sides'],['incessant','never stopping'],['indifferent','not caring'],['inevitable','certain to happen'],['lucid','clear'],['meticulous','very careful and precise'],['mitigate','make less severe'],['novice','beginner'],['obsolete','no longer used'],['ominous','threatening'],['opaque','not see-through; hard to understand']]},
  {heading:'P to Z',rows:[['pragmatic','practical'],['precarious','unstable, risky'],['prevalent','widespread'],['profound','deep'],['prolific','producing a lot'],['reluctant','unwilling'],['resilient','able to recover'],['scrutinize','examine closely'],['skeptical','doubtful'],['sporadic','happening now and then'],['substantiate','prove with evidence'],['succinct','brief and clear'],['superfluous','more than needed'],['tenacious','persistent'],['terse','brief and abrupt'],['trivial','unimportant'],['ubiquitous','found everywhere'],['undermine','weaken gradually'],['verbose','using too many words'],['viable','workable'],['vindicate','clear from blame']]}]}),
 X({id:'x_reading',title:'Reading strategy guide',blurb:'How to read a passage fast without missing what the questions ask.',sections:[
  {heading:'Before you read',items:['Skim the question stems (not the choices) so you know what to look for.','Note the passage type: science article, fiction, history, argument.']},
  {heading:'While you read',items:['Summarise each paragraph in six words in your head.','Mark turns: however, but, although. The author’s point often follows.','Do not stop on one hard word; the questions may not need it.']},
  {heading:'Answering',items:['Main idea: covers every paragraph, adds nothing.','Detail: point to the line before you choose.','Inference: the safest conclusion the clues support.','Vocabulary: replace the word with each choice and reread.','Purpose: name the paragraph’s job in three words.']},
  {heading:'Traps',items:['A true detail offered as the main idea.','An answer true in real life but not in the passage.','Extreme words: always, never, all, only.','A choice that repeats passage words but changes their meaning.']}]}),
 X({id:'x_strategy',title:'Test-day handbook',blurb:'Pacing, elimination, the night before, the day itself, and the application.',sections:[
  {heading:'Pacing',items:['Divide the section minutes by the number of questions to know your per-question budget. Khanpanion’s pace check shows it after every timed mock.','First pass: answer what you know, flag what takes long. Second pass: return to flags.','Never leave the easy points at the end of a section unread.']},
  {heading:'Elimination',items:['Cross out choices that fail an estimate or have the wrong unit.','If two choices are opposites, one is often the answer.','In reading, eliminate choices that go further than the passage.']},
  {heading:'Guessing',items:['Know the scoring rule for your exam from its official instructions before test day. Khanpanion’s practice scoring counts only correct answers, so a blank never costs extra here.','A guess after eliminating two choices is a 50 percent chance, not a coin flip on four.']},
  {heading:'The week before',items:['Take one full simulation at the real start time.','Sleep at your normal time. Memories settle overnight.','Review your mistake notebook, not new chapters.']},
  {heading:'The night before and the day',items:['Prepare what the official instructions list: test permit, valid ID, pencils as required. Check the official page for the exact list.','Know your route and leave early; traffic and rain are the usual delays.','Eat, bring water if allowed, and wear layers for cold rooms.','If a question rattles you, flag it, breathe, and move on.']},
  {heading:'Applications',items:['Follow the official admissions page for your exam; dates and requirements change each year.','Prepare documents early: grades, certificates, photos, and any income documents for fee waivers or scholarships.','Apply to more than one school and scholarship. Khanpanion’s exam dates page lists the ones in the calendar.']}]})
];
export const EXTRA_BY_ID:Record<string,Extra>=Object.fromEntries(EXTRAS.map(e=>[e.id,e]));
