/** Reference sheets and handbooks in the reviewer. Drafts until the team signs off. */
export type Extra={id:string;title:string;blurb:string;sections:{heading:string;rows?:[string,string][];items?:string[]}[];author:string;reviewer:string;status:'draft'|'reviewed';createdAt:string};
const X=(e:Omit<Extra,'author'|'reviewer'|'status'|'createdAt'>):Extra=>({...e,author:'Khanpanion team',reviewer:'',status:'draft',createdAt:'2026-09-30'});

export const EXTRAS:Extra[]=[
 X({id:'x_formulas_math',title:'Math formula sheet',blurb:'Every formula the math subtest leans on, on one printable page.',sections:[
  {heading:'Numbers and percent',rows:[['Percent of a number','r% of N = N × r/100'],['Percent change','(new − old) ÷ old × 100'],['Increase by r%','× (1 + r/100)'],['Decrease by r%','× (1 − r/100)'],['Simple interest','I = Prt'],['Compound interest','A = P(1 + r)ᵗ'],['Ratio share','total × part ÷ sum of parts']]},
  {heading:'Algebra',rows:[['Exponents','xᵃxᵇ = xᵃ⁺ᵇ, xᵃ ÷ xᵇ = xᵃ⁻ᵇ, (xᵃ)ᵇ = xᵃᵇ, x⁰ = 1'],['Square of a sum','(a + b)² = a² + 2ab + b²'],['Difference of squares','a² − b² = (a + b)(a − b)'],['Quadratic formula','x = (−b ± √(b² − 4ac)) ÷ 2a'],['Sum and product of roots','sum = −b/a, product = c/a'],['Arithmetic sequence','aₙ = a₁ + (n − 1)d, Sₙ = n(a₁ + aₙ)/2'],['Geometric sequence','aₙ = a₁rⁿ⁻¹']]},
  {heading:'Lines and functions',rows:[['Slope','m = (y₂ − y₁)/(x₂ − x₁)'],['Slope-intercept form','y = mx + b'],['Point-slope form','y − y₁ = m(x − x₁)'],['Parallel, perpendicular','same m; m₁m₂ = −1'],['Distance','√((x₂ − x₁)² + (y₂ − y₁)²)'],['Midpoint','((x₁ + x₂)/2, (y₁ + y₂)/2)']]},
  {heading:'Geometry',rows:[['Triangle','A = ½bh; angles sum to 180°'],['Pythagorean theorem','a² + b² = c²'],['Circle','A = πr², C = 2πr'],['Trapezoid','A = ½(a + b)h'],['Polygon interior angles','(n − 2) × 180°'],['Cylinder, cone','V = πr²h, V = ⅓πr²h'],['Sphere','V = 4/3 πr³, SA = 4πr²']]},
  {heading:'Trigonometry',rows:[['SOH CAH TOA','sin = O/H, cos = A/H, tan = O/A'],['Special angles','sin 30° = ½, cos 60° = ½, sin 45° = cos 45° = √2/2, tan 45° = 1'],['Identity','sin²θ + cos²θ = 1']]},
  {heading:'Statistics and probability',rows:[['Mean','sum ÷ count'],['Median','middle value after sorting'],['Probability','favourable ÷ total'],['And (independent)','P(A) × P(B)'],['Or (exclusive)','P(A) + P(B)'],['Counting','m ways then n ways gives m × n ways']]}]}),
 X({id:'x_formulas_science',title:'Science formulas and constants',blurb:'Physics and chemistry equations with the units that keep them straight.',sections:[
  {heading:'Motion and forces',rows:[['Speed','v = d/t'],['Acceleration','a = (v − u)/t'],['Uniform acceleration','v = u + at, d = ut + ½at², v² = u² + 2ad'],['Newton’s second law','F = ma'],['Weight','W = mg, g = 9.8 m/s²'],['Momentum','p = mv']]},
  {heading:'Energy',rows:[['Work','W = Fd'],['Kinetic energy','KE = ½mv²'],['Potential energy','PE = mgh'],['Power','P = W/t'],['Heat','Q = mcΔT, c(water) = 4.18 J/g°C']]},
  {heading:'Electricity and waves',rows:[['Ohm’s law','V = IR'],['Electric power','P = VI'],['Series resistors','R = R₁ + R₂'],['Parallel resistors','1/R = 1/R₁ + 1/R₂'],['Wave speed','v = fλ']]},
  {heading:'Chemistry',rows:[['Moles','n = m/M'],['Molarity','M = mol/L'],['Dilution','M₁V₁ = M₂V₂'],['Boyle’s law','P₁V₁ = P₂V₂'],['Charles’s law','V₁/T₁ = V₂/T₂ (kelvin)'],['Ideal gas','PV = nRT'],['pH','pH = −log[H⁺]; pH + pOH = 14'],['Avogadro’s number','6.02 × 10²³ per mole'],['Kelvin','K = °C + 273']]},
  {heading:'Atomic masses used in Khanpanion questions',rows:[['H 1, C 12, N 14, O 16','Na 23, Mg 24, Al 27, S 32, Cl 35.5, Ca 40']]}]}),
 X({id:'x_grammar_en',title:'English grammar guide',blurb:'The rules language questions test most, with one example each.',sections:[
  {heading:'Agreement',rows:[['Find the real subject','The box of pencils is on the desk.'],['Each, every, one: singular','Each of the students has a locker.'],['Or, nor: nearer subject','Neither the coach nor the players are ready.'],['Pronoun agreement','Every student should bring his or her ID.']]},
  {heading:'Verbs',rows:[['Past perfect for the earlier past','She had left before we arrived.'],['Unreal condition','If I were you, I would rest.'],['After a preposition, -ing','I look forward to seeing you.'],['Modal + have + past participle','You should have called.']]},
  {heading:'Sentences',rows:[['Comma splice','Wrong: I studied, I passed. Right: I studied, so I passed.'],['Fragment','Wrong: Because I was late. Right: I ran because I was late.'],['Dangling modifier','Wrong: Walking home, the rain fell. Right: Walking home, I got caught in the rain.'],['Parallelism','She likes reading, swimming, and biking.']]},
  {heading:'Usage',rows:[['affect / effect','The rain affected the game. The effect was a delay.'],['fewer / less','fewer people, less time'],['its / it’s','its cover; it’s late'],['between you and me','Prepositions take object pronouns.'],['good / well','She did well. The food is good.']]}]}),
 X({id:'x_grammar_fil',title:'Gabay sa gramatikang Filipino',blurb:'Ng at nang, din at rin, aspekto at pokus, sa isang pahina.',sections:[
  {heading:'Ng at nang',rows:[['Ng: layon','Bumili ng tinapay.'],['Ng: pagmamay-ari','Aklat ng guro.'],['Nang: paraan','Tumakbo nang mabilis.'],['Nang: noong','Nang dumating siya, umulan.'],['Nang: pag-uulit','Kain nang kain.']]},
  {heading:'Din/rin, daw/raw, dito/rito',rows:[['Pagkatapos ng patinig o w, y','rin, raw, rito, roon: ako rin, ikaw raw'],['Pagkatapos ng katinig','din, daw, dito, doon: aalis din, bukas daw']]},
  {heading:'Aspekto ng pandiwa',rows:[['Perpektibo','kumain, naglaro'],['Imperpektibo','kumakain, naglalaro'],['Kontemplatibo','kakain, maglalaro']]},
  {heading:'Pokus ng pandiwa',rows:[['Aktor','Nagluto si Nanay ng adobo.'],['Layon','Niluto ni Nanay ang adobo.'],['Ganapan','Pinaglutuan ni Nanay ng adobo ang kaldero.'],['Tagatanggap','Ipinagluto ni Nanay ng adobo si Ben.'],['Gamit','Ipinangluto ni Nanay ang bagong kaldero.']]},
  {heading:'Gitling',items:['Sa pagitan ng panlaping nagtatapos sa katinig at salitang-ugat na nagsisimula sa patinig: mag-aral, pag-asa.','Sa pag-uulit ng salita: araw-araw, isa-isa.','Sa pagitan ng panlapi at pangngalang pantangi: maka-Rizal.']}]}),
 X({id:'x_vocab',title:'Vocabulary list',blurb:'Sixty words that show up in academic reading, with plain meanings.',sections:[
  {heading:'A to E',rows:[['abate','become less intense'],['abundant','plentiful'],['adverse','harmful, unfavourable'],['advocate','support publicly; a supporter'],['ambiguous','having more than one meaning'],['ambivalent','having mixed feelings'],['anomaly','something unusual'],['arbitrary','based on chance, not reason'],['benevolent','kind, generous'],['brevity','shortness'],['candid','honest, frank'],['coherent','logical and consistent'],['concede','admit something is true'],['conspicuous','easy to notice'],['contemporary','of the present time'],['corroborate','confirm with evidence'],['deter','discourage'],['diligent','hardworking and careful'],['discern','notice or understand'],['elusive','hard to find or grasp'],['ephemeral','short-lived'],['erratic','unpredictable']]},
  {heading:'F to O',rows:[['feasible','possible to do'],['frugal','careful with money'],['futile','useless'],['garrulous','very talkative'],['hinder','get in the way of'],['imminent','about to happen'],['impartial','fair, not taking sides'],['incessant','never stopping'],['indifferent','not caring'],['inevitable','certain to happen'],['lucid','clear'],['meticulous','very careful and precise'],['mitigate','make less severe'],['novice','beginner'],['obsolete','no longer used'],['ominous','threatening'],['opaque','not see-through; hard to understand']]},
  {heading:'P to Z',rows:[['pragmatic','practical'],['precarious','unstable, risky'],['prevalent','widespread'],['profound','deep'],['prolific','producing a lot'],['reluctant','unwilling'],['resilient','able to recover'],['scrutinize','examine closely'],['skeptical','doubtful'],['sporadic','happening now and then'],['substantiate','prove with evidence'],['succinct','brief and clear'],['superfluous','more than needed'],['tenacious','persistent'],['terse','brief and abrupt'],['trivial','unimportant'],['ubiquitous','found everywhere'],['undermine','weaken gradually'],['verbose','using too many words'],['viable','workable'],['vindicate','clear from blame']]}]}),
 X({id:'x_reading',title:'Reading strategy guide',blurb:'How to read a passage fast without missing what the questions ask.',sections:[
  {heading:'Before you read',items:['Skim the question stems (not the choices) so you know what to look for.','Note the passage type: science article, fiction, history, argument.']},
  {heading:'While you read',items:['Summarise each paragraph in six words in your head.','Mark turns: however, but, although. The author’s point often follows.','Do not stop on one hard word; the questions may not need it.']},
  {heading:'Answering',items:['Main idea: covers every paragraph, adds nothing.','Detail: point to the line before you choose.','Inference: the safest conclusion the clues support.','Vocabulary: replace the word with each choice and reread.','Purpose: name the paragraph’s job in three words.']},
  {heading:'Traps',items:['A true detail offered as the main idea.','An answer true in real life but not in the passage.','Extreme words: always, never, all, only.','A choice that repeats passage words but changes their meaning.']}]}),
 X({id:'x_strategy',title:'Test-day handbook',blurb:'Pacing, elimination, the night before, the day itself, and the application.',sections:[
  {heading:'Pacing',items:['Divide the section minutes by the number of questions to know your per-question budget. Khanpanion’s pace check shows it after every timed mock.','First pass: answer what you know, flag what takes long. Second pass: return to flags.','Never leave the easy points at the end of a section unread.']},
  {heading:'Elimination',items:['Cross out choices that fail an estimate or have the wrong unit.','If two choices are opposites, one is often the answer.','In reading, eliminate choices that go further than the passage.']},
  {heading:'Guessing',items:['Know the scoring rule for your exam from its official instructions before test day. Khanpanion’s practice scoring counts only correct answers, so a blank never costs extra here.','A guess after eliminating two choices is a 50 percent chance, not a coin flip on four.']},
  {heading:'The week before',items:['Take one full simulation at the real start time.','Sleep at your normal time. Memories settle overnight.','Review your mistake notebook, not new chapters.']},
  {heading:'The night before and the day',items:['Prepare what the official instructions list: test permit, valid ID, pencils as required. Check the official page for the exact list.','Know your route and leave early; traffic and rain are the usual delays.','Eat, bring water if allowed, and wear layers for cold rooms.','If a question rattles you, flag it, breathe, and move on.']},
  {heading:'Applications',items:['Follow the official admissions page for your exam; dates and requirements change each year.','Prepare documents early: grades, certificates, photos, and any income documents for fee waivers or scholarships.','Apply to more than one school and scholarship. Khanpanion’s exam dates page lists the ones in the calendar.']}]})
];
export const EXTRA_BY_ID:Record<string,Extra>=Object.fromEntries(EXTRAS.map(e=>[e.id,e]));
