'use client';
import {useState} from 'react';
import {problemFor,isCorrect,answerInputIssue,TOPICS,type Recovery} from '@/lib/recovery';
import {MathText} from '@/components/math/Math';
import {GraphBoard} from './GraphBoard';
import {AnswerFields} from './AnswerFields';
const FOCUS:Record<string,string>={quadratics:'Factor first. Then make each factor zero.',brackets:'Expand, combine, then solve for x.',factor:'Match the sum and the product.',distribute:'Multiply all four pairs, including the middle terms.',expand:'The outside number multiplies every term inside.',terms:'Keep the variable. Add its coefficients.',zero:'Find the x-value that makes each factor zero.',linear:'Keep both sides equal as you undo multiplication.',equivalent:'Scale the top and bottom by the same number.',same_denominator:'Add equal-sized parts without changing their size.',unit_rate:'Find one before finding many.',coordinates:'Read across for x, then up for y.',substitute:'Replace x, multiply first, then add.',multiply:'Use equal groups to check the product.',fractions:'Make the denominators match before adding.',ratios:'Find the unit rate, then scale to the amount you need.',graphs:'Match the horizontal input to the height of the line.',atom_count:'A subscript counts atoms inside one unit; the number in front counts the units.',formula_mass:'Add every atom in the formula once, then scale to the amount you have.',unit_convert:'The quantity does not change. Only the size of the unit does.',net_force:'Give each force its sign, then add. The sign is the direction.',moles:'Molar mass is the exchange rate between grams and moles.',balancing:'Every element must have the same atom count on both sides. Change coefficients, never subscripts.',motion:'Acceleration adds the same speed each second, on top of the speed already there.',forces:'The net force sets the acceleration. Decide what is missing before you calculate.'};
export function GuidedRepair({state:s,source,onReady,onExpose}:{state:Recovery;source:string;onReady:()=>void;onExpose:()=>void}){
 const [step,setStep]=useState(0);const p=problemFor({...s,serial:s.serial+(step===2?1:0)}),[answers,setAnswers]=useState(p.labels.map(()=>'')),[checked,setChecked]=useState(false);
 const correct=checked&&isCorrect(p,answers);const [inputError,setInputError]=useState('');
 const focus=FOCUS[s.active==='goal'?s.topic:s.active]??'Connect the earlier step to your current goal.';
 return <section className="guided-repair"><div className="repair-kicker"><span>Repair this step</span><span>{step+1} / 3</span></div><h3>{focus}</h3>{s.active!=='goal'&&<p className="repair-connection">For your goal: {TOPICS[s.topic].goal.toLowerCase()}.</p>}{step===2&&<p className="repair-prompt">{p.prompt}</p>}
   {p.graph?<GraphBoard graph={p.graph} guide={step===1||correct}/>:<div className="repair-equation"><MathText size="lg" speak={p.speak}>{p.expression}</MathText></div>}
   {step===0&&<><p>{p.hint}</p><button className="button-secondary" onClick={()=>setStep(1)}>Work through one example</button></>}
   {step===1&&<><p className="repair-explanation">{p.explanation}</p><p>Now use that step with different numbers.</p><button className="button-secondary" onClick={()=>{onExpose();setStep(2);}}>Let me try</button></>}
   {step===2&&<form onSubmit={e=>{e.preventDefault();const issue=answerInputIssue(p,answers);setInputError(issue??'');setChecked(!issue);}}><div className={`answer-inputs ${p.fields?.some(f=>f.kind==='choice')?'stacked-answers':''}`}><AnswerFields p={p} values={answers} ariaLabel={label=>`Guided ${label.toLowerCase()}`} onChange={(i,v)=>{setAnswers(xs=>xs.map((x,j)=>i===j?v:x));setChecked(false);setInputError('');}}/></div><button className="button-secondary" type="submit" disabled={answers.some(a=>!a.trim())}>Check this step</button>{inputError&&<p role="alert">{inputError}</p>}{checked&&<p role="status" className={correct?'accent':'warm'}>{correct?'That works. Ready for fresh numbers?':p.hint}</p>}{correct&&<button className="button-primary" type="button" onClick={onReady}>Try a fresh check ↗</button>}</form>}
   {source?<a href={source} className="repair-source" target="_blank" rel="noopener noreferrer">Khan Academy concept ↗</a>:<p className="repair-source unmatched">No reviewed Khan Academy resource is matched to this step yet. This explanation is Dunlo’s own.</p>}
 </section>;
}
