'use client';

import { useEffect, useReducer, useRef, useState } from 'react';
import Link from 'next/link';
import { MathText } from '@/components/math/Math';
import { khanMaterial } from '@/lib/khan-materials';
import { LABELS, TOPICS, initialRecovery, problemFor, recoveryReducer, recentSuccesses, validRecovery, type Confidence, type Problem, type Recovery, type RecoveryAction, type Topic } from '@/lib/recovery';
import { RouteCanvas } from './RouteCanvas';
import { KhanPlayer } from './KhanPlayer';
import { useRouteTools } from './useRouteTools';

type Send=(action:RecoveryAction)=>void;
export function RecoveryApp({topic='quadratics'}:{topic?:Topic}){
  const [s,send]=useReducer(recoveryReducer,topic,initialRecovery);
  useRouteTools(s,send);
  const [ready,setReady]=useState(false),[saved,setSaved]=useState(true),[offline,setOffline]=useState(false),[historyOpen,setHistoryOpen]=useState(false),[forget,setForget]=useState(false),[mapOpen,setMapOpen]=useState(false);
  const stage=useRef<HTMLDivElement>(null);
  const store=`backtrack.route.v1.${topic}`;
  useEffect(()=>{
    try { const raw=localStorage.getItem(store); if(raw){const parsed=JSON.parse(raw);if(validRecovery(parsed)&&parsed.topic===topic){const old=Date.now()-parsed.updatedAt>7*86400000&&parsed.phase!=='setup';send({type:'restore',state:old?{...parsed,phase:'return',next:parsed.phase,nextSkill:parsed.active}:parsed});}} } catch {setSaved(false);}
    setReady(true);setOffline(!navigator.onLine);
    const online=()=>setOffline(!navigator.onLine);window.addEventListener('online',online);window.addEventListener('offline',online);
    return ()=>{window.removeEventListener('online',online);window.removeEventListener('offline',online);};
  },[store,topic]);
  useEffect(()=>{if(!ready)return;try{localStorage.setItem(store,JSON.stringify(s));setSaved(true);}catch{setSaved(false);}},[s,store,ready]);
  useEffect(()=>{if(!ready)return;const el=stage.current?.querySelector('h1,h2');if(el instanceof HTMLElement){el.setAttribute('tabindex','-1');el.focus({preventScroll:true});}},[s.phase,s.active,ready]);
  const now=()=>Date.now();
  function exportRoute(){const blob=new Blob([JSON.stringify({...s,notice:'Device-local activity. Not independently verified learning or Khan completion.'},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`backtrack-${topic}-route.json`;a.click();URL.revokeObjectURL(url);}
  if(!ready)return <div className="route-loading wrap" role="status">Opening your route…</div>;
  return <div className="product-shell">
    <div className="goal-bar"><div><span className="eyebrow">{s.mode==='class'?'Class destination':'Your destination'}</span><strong>{TOPICS[topic].label}</strong></div><Link href="/start">Change goal ↗</Link>{s.phase!=='setup'&&<span className="session-label">{s.budget} min session</span>}<button className="route-toggle" aria-expanded={mapOpen} aria-controls="learner-route-map" onClick={()=>setMapOpen(!mapOpen)}><span>{s.goalPassed?'Back on track':s.suspected.length?'Recalculating':LABELS[s.active]} · {s.passed.length} {s.passed.length===1?'step':'steps'} checked</span><span>{mapOpen?'Close route −':'See route +'}</span></button></div>
    {offline&&<p className="service-note">You’re offline. This open page still works. Khan Academy needs a connection.</p>}
    {!saved&&<p className="service-note">This browser cannot save your route. Download it before leaving.</p>}
    <div className={`learning-layout ${s.phase==='setup'?'setup-layout':''}`}>
      <div className="learning-stage" ref={stage}>
        <Stage s={s} send={send}/>
      </div>
      <aside id="learner-route-map" className={`learning-map ${mapOpen?'map-expanded':''}`} aria-label="Your route"><div className="map-goal"><span className="eyebrow">The destination stays.</span><MathText size="lg">{TOPICS[topic].example}</MathText></div><RouteCanvas state={s}/><div className="map-foot"><span>{s.passed.filter(x=>x!=='goal').length} steps demonstrated</span><button onClick={()=>setHistoryOpen(!historyOpen)} aria-expanded={historyOpen}>Evidence {historyOpen?'−':'+'}</button></div>{historyOpen&&<div className="evidence-drawer"><h3>Your route history</h3>{s.evidence.length===0?<p>No checks yet. Your answers will appear here.</p>:<ol>{s.evidence.slice(-12).map(e=><li key={e.id}><span>{LABELS[e.skill]}</span><small>{e.correct?'Correct':'Needs another look'}{e.assisted?' · With support':' · No hint'} · {e.confidence}</small></li>)}</ol>}<p>{s.events.filter(e=>e.kind==='khan_open').length} Khan resource opens. Opens do not verify practice completion.</p><button className="button-text" onClick={exportRoute}>Download route record ↗</button></div>}</aside>
    </div>
    <div className="product-bottom"><span>{saved?'Saved in this browser':'Local saving unavailable'}</span><div>{s.phase!=='setup'&&s.phase!=='pause'&&<button onClick={()=>send({type:'pause',now:now()})}>Pause here</button>}<button onClick={()=>setForget(!forget)} aria-expanded={forget}>Shared device?</button></div></div>
    {forget&&<div className="forget-panel"><p>Clear the saved answers for this destination before someone else uses this device. The other destination has its own saved route.</p><button className="button-secondary" onClick={()=>{try{localStorage.removeItem(store);}catch{}send({type:'restart',topic});setForget(false);}}>Clear this route</button><button className="button-text" onClick={()=>setForget(false)}>Keep it</button></div>}
  </div>;
}

function Stage({s,send}:{s:Recovery;send:Send}){
  const now=()=>Date.now();
  if(s.phase==='setup')return <Setup s={s} send={send}/>;
  if(s.phase==='check')return <Question key={`${s.active}:${s.serial}`} s={s} send={send}/>;
  if(s.phase==='learn')return <Learn key={s.active} s={s} send={send}/>;
  if(s.phase==='feedback'||s.phase==='moment'){
    const prev=problemFor({...s,serial:s.serial-1});
    const title=s.extension?'Next turn, saved.':s.phase==='moment'?(s.active==='goal'?'Back on track.':s.learned.includes(s.active)?'That step is yours.':'One review removed.'):s.correct?(s.assisted?'Now try without a hint.':'That works.'):s.nextSkill!==s.active?'Let’s check one step back.':'Let’s work on this step.';
    return <div className="feedback-stage"><p className={`eyebrow ${s.correct?'accent':'warm'}`}>{s.phase==='moment'?(s.active==='goal'?'Destination check':s.learned.includes(s.active)?'New capability':'Shortcut found'):s.correct?'Answer checked':'Recalculating…'}</p><h2>{title}</h2>{s.phase==='feedback'&&<><div className="feedback-equation"><MathText size="lg">{prev.expression}</MathText></div><p className="quiet">{s.correct?'Fresh numbers next.':s.evidence.at(-1)?.answer.every(x=>x==='')?`Next: ${LABELS[s.nextSkill].toLowerCase()}.`:prev.hint}</p></>}{s.phase==='moment'&&<p className="quiet">{s.extension?s.message:s.active==='goal'?'Two fresh destination problems, solved.':`${LABELS[s.active]}: two fresh checks passed.`}</p>}<button className="button-primary" onClick={()=>send({type:'continue',now:now()})}>{s.next==='complete'?'See your progress':s.blockCount>=s.blockLimit?'Save this block':s.next==='learn'?'Learn this step':s.next==='support'?'Get support':'Continue'} <span aria-hidden="true">↗</span></button>{s.phase==='moment'&&s.active!=='goal'&&<p className="fine-print">Your earlier progress stays saved.</p>}</div>;
  }
  if(s.phase==='pause')return <div className="pause-stage"><p className="eyebrow">A good place to stop</p><h2>Your route<br/><em>will be here.</em></h2><p className="quiet">{s.blockCount===0?'That’s your next block saved.':'Your progress is saved.'} Next: {LABELS[s.nextSkill].toLowerCase()}. You don’t need to start over.</p><button className="button-primary" onClick={()=>send({type:'resume',now:now()})}>Continue when you’re ready ↗</button><Link className="button-text" href="/">Done for now</Link></div>;
  if(s.phase==='return')return <div><p className="eyebrow">Welcome back</p><h2>Life happened.<br/><em>Let’s recalculate.</em></h2><p className="quiet">Your previous work stays. Two short retrieval checks can show where to pick up.</p><button className="button-primary" onClick={()=>send({type:'return',now:now()})}>Find my next step ↗</button><button className="button-text" onClick={()=>send({type:'resume',now:now()})}>Resume saved activity</button></div>;
  if(s.phase==='support')return <div><p className="eyebrow warm">A person can help here</p><h2>Let’s change<br/>the support.</h2><p className="quiet">This step is still difficult after several attempts. Ask a teacher or someone you trust to work through one example with you.</p><p className="support-prompt">“I’m working on {TOPICS[s.topic].label.toLowerCase()}. Can we look at {LABELS[s.active].toLowerCase()} together?”</p><button className="button-primary" onClick={()=>send({type:'learn',now:now()})}>Open a worked example ↗</button><button className="button-text" onClick={()=>send({type:'pause',now:now()})}>Pause here</button></div>;
  return <div className="completion"><p className="eyebrow accent">{s.goalPassed?'Back on track':'Your route is saved'}</p><h2>{s.goalPassed?<>You can do<br/><em>the thing you came for.</em></>:<>Keep what worked.<br/><em>Return when you’re ready.</em></>}</h2><p className="quiet">{s.goalPassed?'Two fresh destination problems, solved without hints. Come back in a week to see what stayed with you.':'You can pick up your next check whenever you’re ready.'}</p><div className="completion-proof"><strong>{s.evidence.filter(e=>e.skill==='goal'&&e.correct&&!e.assisted).length}</strong><span>unassisted destination answers<br/><small>Fresh problems, no hints</small></span></div>{!s.extension&&<div className="next-turn"><span className="eyebrow">One optional next turn</span><h3>One more check?</h3><p>Try one fresh {s.topic==='quadratics'?'factoring':'brackets'} problem. Then stop with your route saved.</p><button className="button-secondary" onClick={()=>send({type:'next',now:now()})}>Take the next turn ↗</button><Link className="button-text" href="/">Done for now</Link></div>}<button className="button-text" onClick={()=>send({type:'return',now:now()})}>Check again with fresh numbers</button><Link className="button-text" href="/start">Choose another destination</Link></div>;
}

function Setup({s,send}:{s:Recovery;send:Send}){
  const [budget,setBudget]=useState(15),[mode,setMode]=useState<'self'|'class'>('self');
  return <div className="setup-stage"><p className="eyebrow">Start your route</p><h1>How much time<br/>today?</h1><fieldset className="mode-choice"><legend className="sr-only">How are you learning?</legend><button aria-pressed={mode==='self'} onClick={()=>setMode('self')}>On my own</button><button aria-pressed={mode==='class'} onClick={()=>setMode('class')}>For my class</button></fieldset>{mode==='class'&&<p className="quiet">Use the destination your teacher confirmed. <Link href="/start">Change it</Link> if needed.</p>}<fieldset className="budget-choice"><legend className="sr-only">Session time</legend>{[5,15,30,60].map(n=><button key={n} aria-pressed={budget===n} onClick={()=>setBudget(n)}><strong>{n}</strong><span>min</span></button>)}</fieldset><p className="quiet">{budget===5?'One check, then a place to pause.':budget===15?'A few checks, then a place to pause.':budget===30?'Room for a repair and fresh practice.':'Room to explore the route at your pace.'}</p><button className="button-primary" onClick={()=>send({type:'start',budget,mode,now:Date.now()})}>Find my missing step ↗</button><p className="fine-print">This isn’t for a grade. “I don’t know” is a useful answer.</p></div>;
}

function Question({s,send}:{s:Recovery;send:Send}){
  const p=problemFor(s),[values,setValues]=useState<string[]>(p.labels.map(()=>'')),[confidence,setConfidence]=useState<Confidence>('unsure');
  const now=()=>Date.now();
  function setValue(i:number,v:string){setValues(xs=>xs.map((x,j)=>i===j?v:x));}
  return <div className="question-stage"><div className="question-meta"><span className="eyebrow">{s.returnCheck?'Comeback check':s.extension?'One next turn':s.active==='goal'?'Destination check':LABELS[s.active]}</span><span>{s.extension?'Optional':`${Math.min(recentSuccesses(s,s.active)+1,2)} of 2 fresh checks`}</span></div><h2>{p.prompt}</h2><div className="main-equation"><MathText size="hero">{p.expression}</MathText></div><form onSubmit={e=>{e.preventDefault();send({type:'submit',answers:values,confidence,now:now()});}}>
      {p.widget==='factors'?<div className="factor-entry"><span>(<i>x</i> + </span><NumberInput label={p.labels[0]} value={values[0]} onChange={v=>setValue(0,v)} stepper/><span>)(<i>x</i> + </span><NumberInput label={p.labels[1]} value={values[1]} onChange={v=>setValue(1,v)} stepper/><span>)</span></div>:<div className="answer-inputs">{p.labels.map((label,i)=><NumberInput key={label} label={label} value={values[i]} onChange={v=>setValue(i,v)}/>)}</div>}
      <fieldset className="confidence"><legend>How does this feel?</legend>{([['know','I know this'],['unsure','I’m unsure'],['forgot','I forgot'],['never','Never learned it']] as [Confidence,string][]).map(([id,label])=><button key={id} type="button" onClick={()=>setConfidence(id)} aria-pressed={confidence===id}>{label}</button>)}</fieldset>
      <div className="question-actions"><button className="button-primary" type="submit" disabled={values.some(x=>!x.trim())}>Check my answer ↗</button><button className="button-text" type="button" onClick={()=>send({type:'submit',answers:p.labels.map(()=>''),confidence:'never',now:now()})}>I don’t know yet</button></div></form><div className="hint-row"><button onClick={()=>send({type:'hint',now:now()})} disabled={s.assisted}>Show one hint {s.assisted?'✓':'+'}</button><button onClick={()=>send({type:'learn',now:now()})}>Learn this step ↗</button></div>{s.assisted&&<p className="hint-note">{p.hint} <span>We’ll use fresh numbers for your next independent check.</span></p>}</div>;
}
function NumberInput({label,value,onChange,stepper=false}:{label:string;value:string;onChange:(v:string)=>void;stepper?:boolean}){
  return <label className={`number-field ${stepper?'stepper':''}`}><span>{label}</span><div>{stepper&&<button type="button" aria-label={`Decrease ${label.toLowerCase()}`} onClick={()=>onChange(String(Number(value||0)-1))}>−</button>}<input aria-label={label} value={value} onChange={e=>onChange(e.target.value)} inputMode="text" autoComplete="off" maxLength={18}/>{stepper&&<button type="button" aria-label={`Increase ${label.toLowerCase()}`} onClick={()=>onChange(String(Number(value||0)+1))}>+</button>}</div></label>;
}
function Learn({s,send}:{s:Recovery;send:Send}){
  const [lab,setLab]=useState(false),[practice,setPractice]=useState<'yes'|'no'|null>(null);
  const material=khanMaterial(s);
  return <div className="learn-stage"><img className="learn-logo" src="/khan-academy.svg" alt="Khan Academy" width="176" height="28"/><p className="eyebrow accent">Your next learning stop</p><h2>{LABELS[s.active]==='Your destination'?TOPICS[s.topic].goal:LABELS[s.active]}</h2><p className="quiet">Watch here. Practice on Khan. Then try fresh numbers.</p>{material.id&&<KhanPlayer id={material.id} title={material.title} source={material.source} onOpen={()=>send({type:'khan',detail:'embedded-video',now:Date.now()})}/>}<div className="khan-resources">{material.resources.map(r=><a key={r.url} href={r.url} target="_blank" rel="noopener noreferrer" onClick={()=>send({type:'khan',detail:r.kind,now:Date.now()})}><span className="resource-kind">{r.kind==='exercise'?'Practice':r.kind==='video'?'Watch':'Read'}</span><span>{r.title}</span><span aria-hidden="true">↗</span></a>)}</div><div className="practice-return"><h3>Back from practice?</h3><div className="small-options"><button aria-pressed={practice==='yes'} onClick={()=>setPractice('yes')}>I practiced</button><button aria-pressed={practice==='no'} onClick={()=>setPractice('no')}>I couldn’t access it</button></div>{practice==='yes'&&<><button className="button-primary" onClick={()=>send({type:'practice',detail:'self-reported',now:Date.now()})}>Try fresh numbers ↗</button></>}{practice==='no'&&<p className="quiet">Use the worked example below, or pause until you’re connected.</p>}</div><button className="button-text" onClick={()=>setLab(!lab)} aria-expanded={lab}>{lab?'Close':'Open'} a worked example {lab?'−':'+'}</button>{lab&&<LearningLab s={s}/>}<button className="button-text" onClick={()=>send({type:'practice',detail:'other',now:Date.now()})}>I used another explanation. Try a check ↗</button></div>;
}
function LearningLab({s}:{s:Recovery}){
  const [a,setA]=useState(3),[b,setB]=useState(4),[tiles,setTiles]=useState<number[]>([]);
  if(s.active==='factor'||s.active==='distribute')return <div className="learning-lab"><p className="eyebrow">Explore the mathematics</p><MathText size="lg">{`(x + ${a})(x + ${b})`}</MathText><div className="lab-controls"><label>First number<input type="range" min="1" max="9" value={a} onChange={e=>setA(Number(e.target.value))}/><output>{a}</output></label><label>Second number<input type="range" min="1" max="9" value={b} onChange={e=>setB(Number(e.target.value))}/><output>{b}</output></label></div><div className="area-lab">{['x²',`${b}x`,`${a}x`,String(a*b)].map((x,i)=><button key={i} onClick={()=>setTiles(old=>old.includes(i)?old:old.concat(i))} aria-label={`Reveal product ${i+1}`}>{tiles.includes(i)?x:'+'}</button>)}</div><p>The middle coefficient is the <strong>sum: {a+b}</strong>.<br/>The constant is the <strong>product: {a*b}</strong>.</p><MathText size="lg">{`x² + ${a+b}x + ${a*b}`}</MathText></div>;
  const p:Problem=problemFor(s);
  return <div className="learning-lab"><MathText size="lg">{p.expression}</MathText><p>{p.hint}</p><p>{p.explanation}</p><p className="fine-print">This is a worked example. The next check uses different numbers.</p></div>;
}
