'use client';

import { useEffect, useReducer, useRef, useState } from 'react';
import Link from 'next/link';
import { MathText } from '@/components/math/Math';
import { khanMaterial } from '@/lib/khan-materials';
import { LABELS, TOPICS, NEXT_SKILL, initialRecovery, problemFor, recoveryReducer, recentSuccesses, validRecovery, answerInputIssue, type Confidence, type Recovery, type RecoveryAction, type Topic,type Skill } from '@/lib/recovery';
import { RouteCanvas } from './RouteCanvas';
import { KhanPlayer } from './KhanPlayer';
import { GraphBoard } from './GraphBoard';
import { RouteProgress } from './RouteProgress';
import { GuidedRepair } from './GuidedRepair';
import { VERIFIED_CLIPS,clipTime } from '@/lib/video-clips';
import {ConfidenceChoices} from './ConfidenceChoices';
import {ErrorReplay} from './ErrorReplay';
import {replayModel} from '@/lib/error-replay';
import {ReturnTicket} from './ReturnTicket';
import {clearBacktrackActivity,DEVICE_RESET_KEY} from '@/lib/device-data';
import {useStudy} from '@/components/study/StudyProvider';
import {KhanReturnActions} from '@/components/study/KhanReturnActions';
import {recordKhanOpen,type KhanFeedback} from '@/lib/study';
import {ConceptLab} from '@/components/study/ConceptLab';
import {visualKind} from '@/lib/concept-labs';
import {AnswerFields} from './AnswerFields';

import {Companion} from '@/components/study/Companion';
import {LocalHelpCard} from './LocalHelpCard';
import { useRouteTools } from './useRouteTools';

type Send=(action:RecoveryAction)=>void;
export function RecoveryApp({topic='quadratics',sample=false,quick=false,launch,roundSkill,roundStartedAt,onRoundComplete,rehearsal=false,rehearsalLimit=2}:{topic?:Topic;sample?:boolean;quick?:boolean;launch?:{id:string;resume:boolean;initial:Recovery};roundSkill?:Skill;roundStartedAt?:number;onRoundComplete?:(route:Recovery)=>void;rehearsal?:boolean;rehearsalLimit?:number}){
  const [s,send]=useReducer(recoveryReducer,topic,initialRecovery);
  const study=useStudy();const sharedFloor=study.state.cursors[topic]??0;const sharedPairs=study.state.pairs[topic]??[];
  useRouteTools(s,send);
  const [ready,setReady]=useState(false),[saved,setSaved]=useState(true),[offline,setOffline]=useState(false),[historyOpen,setHistoryOpen]=useState(false),[forget,setForget]=useState(false),[mapOpen,setMapOpen]=useState(false);
  const stage=useRef<HTMLDivElement>(null);
  /* The route is written by an effect, and a draft reaches that state through a
     second effect. A reload or a closed tab can land between the keystroke and
     either hop, losing the answer the learner had already typed. These refs hold
     the newest values synchronously so the page can be flushed on its way out. */
  const latest=useRef(s);latest.current=s;const pendingDraft=useRef<Recovery['draft']>(undefined);
  const [clearMessage,setClearMessage]=useState('');
  const store=`backtrack.route.v1.${topic}${launch?`.study.${launch.id}`:quick?'.quick':''}`;
  useEffect(()=>{
    if(!study.ready)return;
    if(launch){let restored=false;if(launch.resume)try{const raw=JSON.parse(localStorage.getItem(store)??'null');if(validRecovery(raw)&&raw.topic===topic&&raw.studyTaskId===launch.id){send({type:'restore',state:raw});restored=true;}}catch{}if(!restored)send({type:'restore',state:launch.initial});}
    else if(sample){send({type:'start',budget:60,mode:'self',now:Date.now()});const turn=new URLSearchParams(window.location.search).get('turn');if(turn==='factors'||turn==='solutions')send({type:'submit',answers:turn==='factors'?['2','6']:['3','4'],confidence:'unsure',now:Date.now()});}
    else try { const raw=localStorage.getItem(store); let restored=false;if(raw){const parsed=JSON.parse(raw);if(validRecovery(parsed)&&parsed.topic===topic){const old=Date.now()-parsed.updatedAt>7*86400000&&parsed.phase!=='setup';send({type:'restore',state:old?{...parsed,phase:'return',next:parsed.phase,nextSkill:parsed.active}:parsed});restored=true;}}if(!restored&&quick){const t=Date.now();send({type:'restore',state:{...initialRecovery(topic),phase:'check',active:'factor',serial:3,startedAt:t,updatedAt:t}});}else if(!restored&&new URLSearchParams(window.location.search).get('mode')==='class'){send({type:'restore',state:{...initialRecovery(topic),mode:'class'}});} } catch {setSaved(false);if(quick){send({type:'restore',state:{...initialRecovery(topic),phase:'check',active:'factor',serial:3,startedAt:Date.now(),updatedAt:Date.now()}});}}
    setReady(true);setOffline(!navigator.onLine);
    const online=()=>setOffline(!navigator.onLine);window.addEventListener('online',online);window.addEventListener('offline',online);
    const resetHere=()=>{send({type:'restart',topic});setClearMessage('Saved activity was cleared on this device.');};const reset=(e:StorageEvent)=>{if(e.key===DEVICE_RESET_KEY)resetHere();};window.addEventListener('storage',reset);window.addEventListener('backtrack:cleared',resetHere);
    return ()=>{window.removeEventListener('online',online);window.removeEventListener('offline',online);window.removeEventListener('storage',reset);window.removeEventListener('backtrack:cleared',resetHere);};
  },[store,topic,sample,quick,launch?.id,study.ready]);
  useEffect(()=>{if(!ready||sample)return;try{localStorage.setItem(store,JSON.stringify(s));setSaved(true);}catch{setSaved(false);}},[s,store,ready,sample]);
  useEffect(()=>{if(!ready||sample)return;
    const flush=()=>{try{localStorage.setItem(store,JSON.stringify({...latest.current,draft:pendingDraft.current??latest.current.draft}));}catch{}};
    const hidden=()=>{if(document.visibilityState==='hidden')flush();};
    window.addEventListener('pagehide',flush);document.addEventListener('visibilitychange',hidden);
    return()=>{window.removeEventListener('pagehide',flush);document.removeEventListener('visibilitychange',hidden);};
  },[ready,sample,store]);
  useEffect(()=>{if(ready&&!sample)study.ingest(s);},[s,ready,sample,study.ingest]);
  useEffect(()=>{if(ready&&!sample)send({type:'shared-context',floor:sharedFloor,pairs:sharedPairs,used:study.state.seen,now:Date.now()});},[ready,sample,sharedFloor,sharedPairs,study.state.seen]);
  useEffect(()=>{if(!ready)return;const el=stage.current?.querySelector('h1,h2');if(el instanceof HTMLElement&&stage.current){el.setAttribute('tabindex','-1');el.focus({preventScroll:true});const goalHeight=(document.querySelector('.goal-bar')?.getBoundingClientRect().height??0)+(launch?(document.querySelector('.session-toolbar')?.getBoundingClientRect().height??0):0);window.scrollTo({top:Math.max(0,window.scrollY+stage.current.getBoundingClientRect().top-goalHeight),behavior:'instant'});}},[s.phase,s.active,s.assisted,ready]);
  const now=()=>Date.now();
  const rehearsalAnswers=s.evidence.filter(e=>e.at>=(roundStartedAt??Infinity)&&e.skill===(s.destinationSkill??'goal')).length;
  const replay=()=>{send({type:'restart',topic});send({type:'start',budget:60,mode:'self',now:now()});};
  const compareOther=()=>{const first=s.evidence.find(e=>e.id===`${topic}:goal:0`);const answers=first?.answer[0]==='2'?['3','4']:['2','6'];replay();send({type:'submit',answers,confidence:'unsure',now:now()});};
  function exportRoute(){const blob=new Blob([JSON.stringify({...s,sampleMode:sample,notice:'Device-local activity. Teacher checks Khan completion separately.'},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`backtrack-${topic}-route.json`;a.click();URL.revokeObjectURL(url);}
  if(!ready)return <div className="route-loading wrap" role="status">Opening your route…</div>;
  return <div className="product-shell">
    <div className="goal-bar"><div><span className="eyebrow">Today’s goal</span><strong>{s.goalTitle??TOPICS[topic].label}</strong></div><Link href={launch?"/packs":"/start"}>Change goal ↗</Link>{sample?<button className="demo-replay" onClick={replay}>Replay demo</button>:!launch&&s.phase!=='setup'&&<span className="session-label">{s.budget} min session</span>}<button className="route-toggle" aria-expanded={mapOpen} aria-controls="learner-route-map" onClick={()=>setMapOpen(!mapOpen)}><span>{s.goalPassed?'Back on track':s.phase==='feedback'&&s.suspected.length?'Route updated':LABELS[s.active]}</span><span>{mapOpen?'Close route −':'See route +'}</span></button>{rehearsal?<div className="goal-progress"><span>{Math.min(rehearsalLimit,rehearsalAnswers)} of {rehearsalLimit} rehearsal questions answered</span><progress value={Math.min(rehearsalLimit,rehearsalAnswers)} max={rehearsalLimit} aria-label="Rehearsal questions answered"/></div>:<RouteProgress state={s}/>}</div>
    {offline&&<p className="service-note">You’re offline. This open page still works. Khan Academy needs a connection.</p>}
    {!saved&&<p className="service-note">This browser cannot save your route. Download it before leaving.</p>}
    <div className={`learning-layout ${s.phase==='setup'?'setup-layout':''} ${rehearsal?'rehearsal-layout':''}`}>
      <div className="learning-stage" ref={stage}>
        <div className="stage-content">{sample&&s.evidence.length>0&&<button className="compare-other" onClick={compareOther}>Compare the other answer ⇄</button>}{quick&&s.evidence.length===0&&<p className="quick-entry-note">New numbers. Try the idea you just saw.</p>}{rehearsal&&onRoundComplete&&['feedback','moment'].includes(s.phase)?<div className="round-moment"><p className="eyebrow">Rehearsal</p><h2>{rehearsalAnswers>=rehearsalLimit?'This part is recorded.':'Answer saved.'}</h2><p>{rehearsalAnswers>=rehearsalLimit?'Your results will shape the next useful review.':'A fresh question comes next. Explanations are available after this round.'}</p><button className="button-primary" onClick={()=>rehearsalAnswers>=rehearsalLimit?onRoundComplete(s):send({type:'rehearsal-next',now:Date.now()})}>{rehearsalAnswers>=rehearsalLimit?'Continue my session ↗':'Next question ↗'}</button></div>:onRoundComplete&&s.phase==='moment'&&s.active===roundSkill?<div className="round-moment"><p className="eyebrow">Fresh checks passed</p><h2>You used the step<br/>without a hint.</h2><p>{LABELS[s.active]} · Two different problems in this round.</p><button className="button-primary" onClick={()=>onRoundComplete(s)}>Continue my session ↗</button><Link className="button-text" href="/">Done for now</Link></div>:<Stage s={s} send={send} sample={sample} rehearsal={rehearsal} onDraft={d=>{pendingDraft.current=d;}}/>} {onRoundComplete&&['learn','support'].includes(s.phase)&&new Set(s.evidence.filter(e=>e.at>=(roundStartedAt??Infinity)).map(e=>e.id)).size>=2&&<div className="supported-round"><button className="button-text" onClick={()=>onRoundComplete(s)}>Keep this step for next time</button><small>This step stays in your reviewer for another look.</small></div>}{s.phase!=='setup'&&s.evidence.length>0&&<ReturnTicket state={s} sample={sample} onDownload={exportRoute}/>}</div>
      </div>
      <aside id="learner-route-map" className={`learning-map ${mapOpen?'map-expanded':''}`} aria-label="Your route"><div className="route-context"><div className="map-goal"><span className="eyebrow">{launch?"What we’re working toward":"The destination stays."}</span>{launch?<h3>{s.goalTitle??TOPICS[topic].label}</h3>:<MathText size="lg" speak={s.goalExpression?undefined:TOPICS[topic].speak}>{s.goalExpression??TOPICS[topic].example}</MathText>}</div><RouteCanvas state={s}/><div className="map-foot"><span>{s.goalPassed?'Two fresh goal checks passed':s.passed.filter(x=>x!==(s.destinationSkill??'goal')).length?`${s.passed.filter(x=>x!==(s.destinationSkill??'goal')).length} earlier steps checked`:'Fresh answers guide your next step'}</span><button onClick={()=>setHistoryOpen(!historyOpen)} aria-expanded={historyOpen}>Evidence {historyOpen?'−':'+'}</button></div>{historyOpen&&<div className="evidence-drawer"><h3>Your route history</h3>{s.evidence.length===0?<p>No checks yet. Your answers will appear here.</p>:<ol>{s.evidence.slice(-12).map(e=><li key={e.id}><span>{LABELS[e.skill]}</span><small>{e.correct?'Correct':'Needs another look'}{e.family==='diagnostic'?' · Routing check':e.classification==='later-retrieval'?' · Later independent retrieval':e.assisted?' · With support':' · Fresh independent'} · {e.confidence}</small></li>)}</ol>}<p>{s.events.filter(e=>e.kind==='khan_open').length} Khan resource opens. Opens do not verify practice completion.</p><button className="button-text" onClick={exportRoute}>Download route record ↗</button></div>}</div></aside>
    </div>
    <div className="product-bottom"><span>{sample?'Interactive sample':saved?'Saved in this browser':'Local saving unavailable'}</span><div>{!sample&&s.phase!=='setup'&&s.phase!=='pause'&&<button onClick={()=>send({type:'pause',now:now()})}>Save & stop</button>}{!sample&&<button onClick={()=>setForget(!forget)} aria-expanded={forget}>Shared device?</button>}</div></div>
    {forget&&<div className="forget-panel"><p>Before someone else uses this device, clear saved answers and progress for all Dunlo topics.</p><button className="button-secondary" onClick={()=>{if(study.clear()){send({type:'restart',topic});setForget(false);setClearMessage('Saved study activity was cleared.');}else{setClearMessage('This browser could not clear all saved activity. Use browser site-data settings.');}}}>Clear all Dunlo activity</button><button className="button-text" onClick={()=>setForget(false)}>Keep my progress</button></div>}{clearMessage&&<p className="device-status" role="status">{clearMessage}</p>}
  </div>;
}

function Stage({s,send,sample=false,rehearsal=false,onDraft}:{s:Recovery;send:Send;sample?:boolean;rehearsal?:boolean;onDraft?:(d:Recovery['draft'])=>void}){
  const now=()=>Date.now();
  if(s.phase==='setup')return <Setup s={s} send={send}/>;
  if(s.phase==='check')return <Question key={`${s.active}:${s.serial}`} s={s} send={send} sample={sample} rehearsal={rehearsal} onDraft={onDraft}/>;
  if(s.phase==='learn')return <Learn key={s.active} s={s} send={send} isolated={sample}/>;
  if(s.phase==='feedback'||s.phase==='moment'){
    const prev=problemFor({...s,serial:s.serial-1});
    const clue=!s.correct&&s.routeClue?.serial===s.serial-1?s.routeClue:undefined;
    const title=clue?'Your answer gives us a clue.':s.extension?'Next turn, saved.':s.phase==='moment'?(s.active==='goal'?'Back on track.':s.learned.includes(s.active)?'That step is yours.':'One review removed.'):s.correct?(s.assisted?'Now try without a hint.':'That works.'):s.nextSkill!==s.active?'Let’s check one step back.':'Let’s work on this step.';
    return <div className="feedback-stage"><div className="feedback-buddy"><Companion size={95} pose={s.correct?'aha':'encourage'}/></div><p className={`eyebrow ${s.correct?'accent':'warm'}`}>{s.phase==='moment'?(s.active==='goal'?'Destination check':s.learned.includes(s.active)?'New capability':'Shortcut found'):s.correct?'Answer checked':clue?'Wrong-turn clue':'Recalculating…'}</p><h2>{title}</h2>{clue&&<p className="clue-answer">You tried <strong>{s.evidence.at(-1)?.answer.join(s.topic==='fractions'?' / ':' and ')}</strong></p>}{s.phase==='feedback'&&<><div className="feedback-equation"><MathText size="lg" speak={prev.speak}>{prev.expression}</MathText></div><p className="quiet">{s.message||clue?.message||prev.hint}</p></>}{s.phase==='moment'&&<p className="quiet">{s.extension?s.message:s.active==='goal'?'Two fresh destination problems, solved.':`${LABELS[s.active]}: two fresh checks passed.`}</p>}<button className="button-primary" onClick={()=>send({type:'continue',now:now()})}>{clue?'Check the possible gap':s.next==='complete'?'See your progress':s.blockCount>=s.blockLimit?'Save this block':s.next==='learn'?'Learn this step':s.next==='support'?'Get support':clue?'Check that step':'Continue'} <span aria-hidden="true">↗</span></button>{<button className="button-text" onClick={()=>send({type:'learn',skill:clue?.skill??s.nextSkill,now:now()})}>Show me the explanation</button>}{s.phase==='moment'&&s.active!=='goal'&&<p className="fine-print">{sample?'Keep going to the original goal.':'Your earlier progress stays saved.'}</p>}</div>;
  }
  if(s.phase==='pause')return <div className="pause-stage"><p className="eyebrow">A good place to stop</p><h2>Your route<br/><em>will be here.</em></h2><p className="quiet">{sample?'Continue from this step.':s.blockCount===0?'That’s your next block saved.':'Your progress is saved.'} Next: {LABELS[s.nextSkill].toLowerCase()}. You don’t need to start over.</p><button className="button-primary" onClick={()=>send({type:'resume',now:now()})}>Continue when you’re ready ↗</button><Link className="button-text" href="/">Done for now</Link></div>;
  if(s.phase==='return')return <div><p className="eyebrow">Welcome back</p><h2>Life happened.<br/><em>Let’s recalculate.</em></h2><p className="quiet">Your previous work stays. Two short retrieval checks can show where to pick up.</p><button className="button-primary" onClick={()=>send({type:'return',now:now()})}>Find my next step ↗</button><button className="button-text" onClick={()=>send({type:'resume',now:now()})}>Resume saved activity</button></div>;
  if(s.phase==='support')return <div><p className="eyebrow warm">A person can help here</p><h2>Let’s change<br/>the support.</h2><p className="quiet">This step is still difficult after several attempts. Ask a teacher or someone you trust to work through one example with you.</p><LocalHelpCard state={s} onQuestion={text=>send({type:'help-question',text,now:Date.now()})}/><p className="support-prompt">“I’m working on {TOPICS[s.topic].label.toLowerCase()}. Can we look at {LABELS[s.active].toLowerCase()} together?”</p><button className="button-primary" onClick={()=>send({type:'learn',now:now()})}>Open a worked example ↗</button><button className="button-text" onClick={()=>send({type:'pause',now:now()})}>Save & stop</button></div>;
  return <div className="completion"><p className="eyebrow accent">{s.goalPassed?'Back on track':'Your route is saved'}</p><h2>{s.goalPassed?<>Today’s goal,<br/><em>checked.</em></>:<>Keep what worked.<br/><em>Return when you’re ready.</em></>}</h2><p className="quiet">{sample?'That’s the full loop: a useful repair, then fresh goal checks. Replay to compare another wrong turn.':s.goalPassed?'Two fresh destination problems, solved without hints. Your reviewer offers editable return dates to see what stayed with you.':'You can pick up your next check whenever you’re ready.'}</p><div className="completion-proof"><strong>{s.evidence.filter(e=>e.skill==='goal'&&e.correct&&!e.assisted).length}</strong><span>unassisted destination answers<br/><small>Fresh problems, no hints</small></span></div>{!sample&&!s.extension&&<div className="next-turn"><span className="eyebrow">One optional next turn</span><h3>One more check?</h3><p>Next: {LABELS[NEXT_SKILL[s.topic]].toLowerCase()}. One check, then stop with your route saved.</p><button className="button-secondary" onClick={()=>send({type:'next',now:now()})}>Take the next turn ↗</button><Link className="button-text" href="/">Done for now</Link></div>}<button className="button-text" onClick={()=>send({type:'return',now:now()})}>Check again with fresh numbers</button><Link className="button-text" href="/start">Choose another destination</Link></div>;
}

function Setup({s,send}:{s:Recovery;send:Send}){
  const [budget,setBudget]=useState(15),[mode,setMode]=useState<'self'|'class'>(s.mode);
  return <div className="setup-stage"><p className="eyebrow">Start your route</p><h1>How much time<br/>today?</h1><fieldset className="mode-choice"><legend className="sr-only">How are you learning?</legend><button aria-pressed={mode==='self'} onClick={()=>setMode('self')}>On my own</button><button aria-pressed={mode==='class'} onClick={()=>setMode('class')}>For my class</button></fieldset>{mode==='class'&&<p className="quiet">Use the destination your teacher confirmed. <Link href="/start">Change it</Link> if needed.</p>}<fieldset className="budget-choice"><legend className="sr-only">Session time</legend>{[5,15,30,60].map(n=><button key={n} aria-pressed={budget===n} onClick={()=>setBudget(n)}><strong>{n}</strong><span>min</span></button>)}</fieldset><p className="quiet">{budget===5?'One check, then a place to pause.':budget===15?'A few checks, then a place to pause.':budget===30?'Room for a repair and fresh practice.':'Room to explore the route at your pace.'}</p><button className="button-primary" onClick={()=>send({type:'start',budget,mode,now:Date.now()})}>Start with a check ↗</button><button className="button-text" onClick={()=>{send({type:'start',budget,mode,now:Date.now()});send({type:'learn',skill:TOPICS[s.topic].path[0],now:Date.now()});}}>Show me an example first</button><p className="fine-print">This isn’t for a grade. “I don’t know” is a useful answer.</p></div>;
}

function Question({s,send,sample=false,rehearsal=false,onDraft}:{s:Recovery;send:Send;sample?:boolean;rehearsal?:boolean;onDraft?:(d:Recovery['draft'])=>void}){
  const p=problemFor(s),[values,setValues]=useState<string[]>(s.draft?.id===p.id?s.draft.answers:p.labels.map(()=>'')),[confidence,setConfidence]=useState<Confidence>(s.draft?.id===p.id?s.draft.confidence:'unsure'),[inputError,setInputError]=useState('');
  const now=()=>Date.now();
  useEffect(()=>{send({type:'draft',id:p.id,answers:values,confidence,now:Date.now()});onDraft?.({id:p.id,answers:values,confidence});},[p.id,values,confidence]);
  /* Submitting clears the draft in the reducer, so the pending copy has to go too. */
  const submit=(answers:string[])=>{onDraft?.(undefined);send({type:'submit',answers,confidence,now:now()});};
  function setValue(i:number,v:string){const next=values.map((x,j)=>i===j?v:x);setValues(next);onDraft?.({id:p.id,answers:next,confidence});setInputError('');}
  if(sample&&s.topic==='quadratics'&&s.active==='goal'&&s.serial===0)return <div className="question-stage">{s.original&&s.active===(s.destinationSkill??'goal')&&s.original.id!==p.id&&<details className="original-return"><summary>Reconnect with your original problem</summary><MathText size="md">{s.original.expression}</MathText><p>Your earlier attempt: {s.original.answer.join(", ")||"I didn’t know yet"}. Revisit it on paper if useful. It is already seen; the different question below supplies fresh evidence.</p></details>}<div className="question-meta"><span className="eyebrow">Compare two wrong turns</span></div><h2>Find both values of x.</h2><div className="main-equation"><MathText size="hero">{p.expression}</MathText></div><p className="quiet">Compare two example wrong turns, start with an explanation, or try your own answer.</p><ConfidenceChoices value={confidence} onChange={setConfidence}/><div className="sample-answers sample-choices">{[['2','6'],['3','4']].map(pair=><button type="button" key={pair.join()} onClick={()=>send({type:'submit',answers:pair,confidence,now:now()})}>Try x = {pair[0]} and {pair[1]}</button>)}</div><button className="button-text" type="button" onClick={()=>send({type:'submit',answers:p.labels.map(()=>''),confidence,now:now()})}>I don’t know yet</button><div className="demo-starts"><Link href="/start/quadratics">I’m ready for a check ↗</Link><button className="button-text" onClick={()=>send({type:'learn',skill:'factor',now:now()})}>Show me an example first</button></div></div>;
  return <div className="question-stage">{s.original&&s.active===(s.destinationSkill??'goal')&&s.original.id!==p.id&&<details className="original-return"><summary>Reconnect with your original problem</summary><MathText size="md">{s.original.expression}</MathText><p>Your earlier attempt: {s.original.answer.join(", ")||"I didn’t know yet"}. Revisit it on paper if useful. It is already seen; the different question below supplies fresh evidence.</p></details>}<div className="question-meta"><span className="eyebrow">{s.returnCheck?'Comeback check':s.extension?'One next turn':s.active==='goal'?'Destination check':LABELS[s.active]}</span><span>{s.extension?'Optional':`${Math.min(recentSuccesses(s,s.active)+1,2)} of 2 fresh checks`}</span></div><h2>{p.prompt}</h2>{p.graph?<GraphBoard graph={p.graph} guide={s.assisted}/>:<div className="main-equation"><MathText size="hero" speak={p.speak}>{p.expression}</MathText></div>}<form onSubmit={e=>{e.preventDefault();const issue=answerInputIssue(p,values);if(issue){setInputError(issue);return;}setInputError('');submit(values);}}>
      <div className={`answer-inputs ${p.widget==='factors'?'factor-answer':''} ${p.fields?.some(f=>f.kind==='choice')?'stacked-answers':''}`}><AnswerFields p={p} values={values} onChange={setValue} stepper={p.widget==='factors'}/></div>{inputError&&<p className="input-error" role="alert">{inputError}</p>}
      <ConfidenceChoices value={confidence} onChange={c=>{setConfidence(c);onDraft?.({id:p.id,answers:values,confidence:c});}}/>
      <div className="question-actions"><button className="button-primary" type="submit" disabled={values.some(x=>!x.trim())}>Check my answer ↗</button><button className="button-text" type="button" onClick={()=>submit(p.labels.map(()=>''))}>I don’t know yet</button></div></form>{!rehearsal&&<div className="hint-row"><button onClick={()=>send({type:'hint',now:now()})} disabled={s.assisted}>Show one hint {s.assisted?'✓':'+'}</button><button onClick={()=>send({type:'learn',now:now()})}>Show me an example first</button></div>}{s.assisted&&<p className="hint-note">{p.hint} <span>We’ll use fresh numbers for your next independent check.</span></p>}</div>;
}
function Learn({s,send,isolated=false}:{s:Recovery;send:Send;isolated?:boolean}){
  const study=useStudy();
  const model=replayModel(s),visual=visualKind(s);
  const [mode,setMode]=useState<'replay'|'repair'|'watch'|'visual'>(model?'replay':visual?'visual':'repair');
  const material=khanMaterial(s),clip=VERIFIED_CLIPS[material.id];
  const practice=material.resources.find(r=>r.kind==='exercise');
  const ready=(detail:string)=>send({type:'practice',detail,now:Date.now()});
  const response=[...s.events].reverse().find(e=>e.kind==='khan_feedback'&&e.skill===s.active)?.detail as KhanFeedback|undefined;
  const activity=practice?{topic:s.topic,skill:s.active,title:practice.title,url:practice.url,returnPath:s.studyTaskId?'/study/session':`/start/${s.topic}`,at:Date.now(),feedback:response}:undefined;
  const watchTitle=s.active==='factor'?'Why sum and product both matter':s.active==='zero'?'How factors become solutions':clip?.label??material.title;
  return <div className="learn-stage">
    <p className="eyebrow accent">Explore a step toward your goal</p>
    <h2>{s.active==='goal'?TOPICS[s.topic].goal:LABELS[s.active]}</h2>
    <div className="repair-modes">{visual&&<button type="button" aria-pressed={mode==='visual'} onClick={()=>setMode('visual')}>See it visually</button>}{model&&<button type="button" aria-pressed={mode==='replay'} onClick={()=>setMode('replay')}>Explore the mistake</button>}<button type="button" aria-pressed={mode==='repair'} onClick={()=>setMode('repair')}>Read & try</button>{material.id&&<button type="button" aria-pressed={mode==='watch'} onClick={()=>setMode('watch')}>Khan explanation{clip?` · ${clipTime(clip.end-clip.start)}`:''}</button>}</div>
    {mode==='replay'&&model&&<ErrorReplay initial={s.labs?.[model.kind]} onSave={value=>send({type:'lab-save',key:model.kind,value,now:Date.now()})} onEvent={(kind,detail)=>send({type:'learning-event',kind,detail,now:Date.now()})} model={model} onExpose={pair=>send({type:'expose-pair',pair,now:Date.now()})} onContinue={()=>ready('interactive-replay')}/>}
    {mode==='visual'&&visual&&<ConceptLab onSave={value=>send({type:'lab-save',key:visual,value,now:Date.now()})} onEvent={(kind,detail)=>send({type:'learning-event',kind,detail,now:Date.now()})} kind={visual} state={s} onExpose={serial=>send({type:'expose',serial,now:Date.now()})} onContinue={()=>ready('visual-guide')}/>}
    {mode==='repair'&&<GuidedRepair state={s} source={material.source} onExpose={()=>send({type:'expose',serial:s.serial+1,now:Date.now()})} onReady={()=>ready('guided-repair')}/>}
    {mode==='watch'&&<><img className="learn-logo" src="/khan-academy.svg" alt="Khan Academy" width="176" height="28"/><h3 className="khan-relevance">{watchTitle}</h3><KhanPlayer id={material.id} title={material.title} source={material.source} onOpen={()=>send({type:'khan',detail:'embedded-video',now:Date.now()})}/><button className="button-secondary" onClick={()=>setMode(model?'replay':'repair')}>Try the step yourself</button></>}
    {practice&&<section className="khan-practice-stop"><img src="/khan-academy.svg" alt="Khan Academy" width="145" height="25"/><h3>Practise this step on Khan Academy</h3><p>{practice.title}. Return here for a fresh problem when you finish.</p><a className="button-secondary" href={practice.url} target="_blank" rel="noopener noreferrer" onClick={()=>{const now=Date.now(),detail=`exercise:${practice.title}`;if(!isolated&&activity)study.update(st=>recordKhanOpen(st,{...activity,at:now},detail));send({type:'khan',detail,now});}}>Open matched Khan practice ↗</a>{s.mode==='class'&&<p className="fine-print">Use the exercise your teacher assigned in your Khan class.</p>}{activity&&<KhanReturnActions activity={activity} isolated={isolated} onReport={(response,now)=>send({type:'khan-feedback',response,now})} onFresh={()=>ready('after-khan-report')} onSupport={()=>setMode(model?'replay':visual?'visual':'repair')}/>}</section>}
    {!material.matched&&<p className="khan-unmatched">No reviewed Khan Academy resource is matched to this step yet. Dunlo’s own explanation above is the one to use; we will add a Khan match only once a reviewer has opened and checked it.</p>}
    <LocalHelpCard state={s} onQuestion={text=>send({type:'help-question',text,now:Date.now()})}/><details><summary>Why this step? Choose another bridge</summary><p>{s.routeClue?.message??'A useful starting point toward your goal. You can choose a different step.'}</p>{TOPICS[s.topic].path.map(skill=><button key={skill} className="button-text" onClick={()=>send({type:'learn',skill,now:Date.now()})}>{LABELS[skill]}</button>)}</details>
    {mode!=='replay'&&(mode!=='visual'||visual==='basics')&&<button className="button-text" onClick={()=>ready('other')}>I’m ready for a fresh check ↗</button>}
  </div>;
}
