'use client';
import {useState} from 'react';
import Link from 'next/link';
import {TOPICS,LABELS,initialRecovery,type Topic} from '@/lib/recovery';
import {khanMaterial} from '@/lib/khan-materials';
import {actionSheetCsv,importRouteRecord,routeSummary,sampleTeacherRows,KHAN_EVIDENCE,type TeacherRow,type KhanEvidence} from '@/lib/teacher-routine';

export function TeacherWorkspace(){
  const [topic,setTopic]=useState<Topic>('quadratics'),[week,setWeek]=useState(1),[sheets,setSheets]=useState<Record<string,{rows:TeacherRow[];illustrative:boolean}>>({}),[message,setMessage]=useState(''),[code,setCode]=useState(''),[manual,setManual]=useState('');
  const sheetKey=`${topic}:${week}`,sheet=sheets[sheetKey]??{rows:[],illustrative:false},rows=sheet.rows,illustrative=sheet.illustrative;
  function setRows(value:TeacherRow[]|((rows:TeacherRow[])=>TeacherRow[])){setSheets(all=>{const old=all[sheetKey]??{rows:[],illustrative:false};return {...all,[sheetKey]:{...old,rows:typeof value==='function'?value(old.rows):value}};});}
  function setIllustrative(value:boolean){setSheets(all=>({...all,[sheetKey]:{...(all[sheetKey]??{rows:[]}),illustrative:value}}));}
  const state=initialRecovery(topic);
  const exercises=TOPICS[topic].path.flatMap(skill=>khanMaterial({...state,active:skill}).resources.filter(x=>x.kind==='exercise').map(x=>({...x,skill}))).filter((x,i,xs)=>xs.findIndex(y=>y.url===x.url)===i);
  async function copyPlan(){const text=`Week ${week} — ${TOPICS[topic].label}\n1. Try the class task: ${location.origin}/start/${topic}?mode=class\n2. In your Khan class, assign the exercise matching the learner’s checked obstacle:\n${exercises.map(x=>`${LABELS[x.skill]}: ${x.title}\n${x.url}`).join('\n')}\n3. Ask learners to return to Dunlo for fresh, unassisted checks.\n4. Review their route record alongside Khan’s assignment report. Set a later check in 7–14 days.\nKhan completion and Dunlo answers are separate records.`;try{await navigator.clipboard.writeText(text);setMessage('Weekly plan copied. Paste it into your class instructions.');setManual('');}catch{setManual(text);setMessage('Select and copy the plan below.');}}
  async function addFile(file:File|undefined){if(!file)return;if(!code.trim()){setMessage('Enter a learner code before adding their record.');return;}if(!/^[A-Za-z0-9 _-]{1,24}$/.test(code)){setMessage('Use a short learner code with letters, numbers, spaces or dashes.');return;}try{if(file.size>1_000_000)throw Error('Use a route record smaller than 1 MB.');const route=importRouteRecord(await file.text());if(route.topic!==topic)throw Error('Choose the same class goal as this learner’s record.');if(illustrative)throw Error('Clear the sample class before adding real learner records.');if(rows.some(r=>r.code===code.trim()))throw Error('That learner code is already listed. Remove its row before adding a replacement.');setRows(xs=>[...xs,{code:code.trim(),route,khan:routeSummary(route).khan,returnDate:''}]);setCode('');setMessage('Route added locally. Check Khan assignment evidence separately.');}catch(e){setMessage(e instanceof Error?e.message:'The file could not be read.');}}
  function download(){const csv=actionSheetCsv(rows,illustrative,week),url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`dunlo-week-${week}-${topic}-actions.csv`;a.click();URL.revokeObjectURL(url);}
  const cleared=rows.filter(r=>routeSummary(r.route).goal).length,support=rows.filter(r=>routeSummary(r.route).support).length;
  return <section className="teacher-workspace" aria-label="Weekly class routine">
    <div className="teacher-plan-controls"><label>Current class goal<select value={topic} onChange={e=>{setTopic(e.target.value as Topic);setMessage('');setManual('');}}>{[['maths','Mathematics'],['chemistry','Chemistry'],['physics','Physics']].map(([subject,heading])=><optgroup key={subject} label={heading}>{Object.entries(TOPICS).filter(([,t])=>t.subject===subject).map(([id,t])=><option key={id} value={id}>{t.label}</option>)}</optgroup>)}</select></label><label>Teaching week<select value={week} onChange={e=>{setWeek(Number(e.target.value));setMessage('');setManual('');}}>{[1,2,3,4].map(n=><option key={n} value={n}>Week {n}</option>)}</select></label></div>
    <ol className="teacher-routine"><li><span>1</span><div><h2>Start with today’s task</h2><p>Confirm the goal, then share its route with your class.</p><Link href={`/start/${topic}?mode=class`}>Open class route ↗</Link></div></li><li><span>2</span><div><h2>Assign the relevant Khan practice</h2><p>Use your existing Khan class. Choose the exercise that fits the checked obstacle.</p>{exercises.length?<ul className="matched-exercises">{exercises.map(x=><li key={x.url}><span>{LABELS[x.skill]}</span><a href={x.url} target="_blank" rel="noopener noreferrer">{x.title} ↗</a></li>)}</ul>:<p className="teacher-local-note">No reviewed Khan Academy exercise is matched to this goal yet. Use your own practice for this week and keep the Dunlo checks as the independent evidence.</p>}</div></li><li><span>3</span><div><h2>Check the return</h2><p>Learners try fresh Dunlo problems. Check Khan assignment records separately, then set a later check.</p><a href="https://support.khanacademy.org/hc/en-us/articles/360031122951-How-do-I-use-the-Assignments-report" target="_blank" rel="noopener noreferrer">Find Khan’s assignment report and CSV export ↗</a></div></li></ol>
    <div className="teacher-plan-actions"><button className="button-primary" type="button" onClick={copyPlan}>Copy this week’s plan</button><Link className="button-text" href="/try/factors">Open a fresh-question entry link ↗</Link></div>{manual&&<textarea className="teacher-copy" aria-label="Weekly plan to copy" readOnly value={manual} onFocus={e=>e.currentTarget.select()}/>}
    <div className="teacher-action-heading"><div><p className="eyebrow">Before the next lesson</p><h2>Who needs what next?</h2></div><button className="button-secondary" type="button" onClick={()=>{if(rows.length&&!illustrative){setMessage('This sheet has learner records. Choose an empty week to explore the sample class.');return;}setRows(sampleTeacherRows(topic,()=>initialRecovery(topic)));setIllustrative(true);setMessage('Sample class loaded. All learner data below is illustrative.');}}>See a sample class</button></div>
    <p className="teacher-local-note">Add learner-downloaded route records to build an action sheet. Files stay in this tab; download the sheet before closing it.</p>
    {illustrative&&<p className="illustrative-banner">Illustrative sample class · These are not real learners or results.</p>}
    <div className="teacher-import"><label>Learner code<input value={code} onChange={e=>setCode(e.target.value)} maxLength={24} placeholder="For example, MATH-01" autoComplete="off"/></label><label className="route-file-label">Add their route record<input type="file" accept=".json,application/json" onChange={e=>{void addFile(e.target.files?.[0]);e.currentTarget.value='';}} disabled={illustrative}/></label>{rows.length>0&&<button type="button" className="button-text" onClick={()=>{setRows([]);setIllustrative(false);setMessage('Action sheet cleared.');}}>Clear this sheet</button>}</div>
    <p role="status" className="teacher-status">{message}</p>
    {rows.length>0?<><div className="teacher-counts"><span><strong>{cleared}</strong> ready for a later check</span><span><strong>{rows.length-cleared-support}</strong> working on a step</span><span><strong>{support}</strong> need a person’s help</span></div><div className="teacher-action-list">{rows.map((row,i)=>{const summary=routeSummary(row.route);return <article key={row.code} className="teacher-learner"><div className="teacher-learner-title"><span>{row.code}</span><button type="button" className="button-text" aria-label={`Remove ${row.code}`} onClick={()=>setRows(xs=>xs.filter((_,j)=>j!==i))}>Remove</button></div><h3>{summary.action}</h3><dl><div><dt>Dunlo checks</dt><dd>{summary.checked.length?summary.checked.map(x=>x==='goal'?'Today’s goal':LABELS[x]).join(', '):'No step has two unassisted checks yet.'}</dd></div></dl><label>Khan assignment evidence<select value={row.khan} onChange={e=>setRows(xs=>xs.map((x,j)=>i===j?{...x,khan:e.target.value as KhanEvidence}:x))}>{Object.entries(KHAN_EVIDENCE).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Next return check<input type="date" value={row.returnDate} onChange={e=>setRows(xs=>xs.map((x,j)=>i===j?{...x,returnDate:e.target.value}:x))}/></label></article>;})}</div><button className="button-primary" type="button" onClick={download}>Download action sheet CSV</button><p className="teacher-local-note">Khan statuses are entered by the teacher. Dunlo does not automatically read a Khan account.</p></>:<div className="teacher-empty"><h3>A next action, not another score.</h3><p>Add a route record or open the sample class to see how checks, Khan practice, and follow-up stay separate.</p></div>}
  </section>;
}
