import {lessonQuiz} from './author.ts';

/** UPCAT Mathematics: Algebra and functions. Original draft items written from Khan's
 * timestamped caption transcripts, read 2026-10-08; pending subject review.
 * Receipts: docs/THIRD_PARTY_MATERIALS.md, "Lesson quiz caption reviews". */
export const MATH_ALGEBRA=[
 lessonQuiz({lesson:'algebraic-expressions-and-laws-of-exponents',video:'zM_p7tfWvLU',reviewed:'2026-10-08',
  keyIdea:'An exponent counts repeated multiplication, so multiplying powers of one base adds the exponents, a power of a power multiplies them, and a power of a product applies to every factor.',
  watchFor:[{at:15,text:'A tempting wrong reading of a small power is named. Notice why it is wrong.'},{at:213,text:'Two powers of the same base are multiplied. Count the factors before using any shortcut.'},{at:434,text:'A power is raised to another power. Watch how writing it out explains the rule.'}],
  practice:{url:'https://www.khanacademy.org/math/als-k-to-12-math/x54b4346ef80b5dcc:performance-standard-e/x54b4346ef80b5dcc:exponents/e/multiply-powers',label:'Multiply powers',checked:'2026-10-08'},
  items:[
   {stem:'What does $2^3$ mean?',choices:['$2 \\times 3$, which is $6$','$2 \\times 2 \\times 2$, which is $8$','$3 \\times 3$, which is $9$','$2 + 2 + 2$, which is $6$'],key:1,
    miss:['exponent_as_multiplier',null,'swap_base_exponent','repeated_addition'],
    why:['The exponent is not a second factor. It says how many times the base is used as a factor.','Correct. The base $2$ is multiplied by itself $3$ times.','This swaps the base and the exponent: $3^2$, not $2^3$.','Repeated addition is multiplication by $3$. An exponent means repeated multiplication.'],
    steps:['$2^3$ means $2$ used as a factor $3$ times.','$2 \\times 2 \\times 2 = 8$.']},
   {stem:'Why is $6^3 \\times 6^6$ equal to $6^9$?',choices:['There are $3$ factors of $6$ followed by $6$ more, so $6$ is a factor $3 + 6 = 9$ times','When powers are multiplied, their exponents are multiplied','The bases multiply as well, so the result is really $36^9$','It is a rule to memorise; counting factors cannot explain it'],key:0,
    miss:[null,'multiply_exponents','multiply_bases','rule_without_reason'],
    why:['Correct. Writing out both powers shows nine factors of $6$ in a row.','Multiplying exponents would give $6^{18}$, which has twice as many factors as there really are.','The base stays $6$; every factor in the product is still a $6$.','Counting the factors is exactly what explains the rule.'],
    steps:['$6^3 = 6 \\times 6 \\times 6$ and $6^6$ is six more factors of $6$.','Altogether $6$ is a factor $9$ times: $6^{3 + 6} = 6^9$.']},
   {stem:'Simplify $(2x)^3 \\cdot x^4$.',choices:['$2x^7$','$8x^{12}$','$6x^7$','$8x^7$'],key:3,
    miss:['power_not_applied_to_coefficient','multiply_exponents','exponent_as_multiplier',null],
    why:['The cube applies to the $2$ as well as the $x$: $2^3 = 8$.','When multiplying $x^3$ by $x^4$, add the exponents; do not multiply them.','$2^3$ is $8$, not $2 \\times 3$.','Correct. $(2x)^3 = 2^3x^3 = 8x^3$, and $8x^3 \\cdot x^4 = 8x^7$.'],
    steps:['A power of a product: $(2x)^3 = 2^3 \\cdot x^3 = 8x^3$.','Same base, multiply: $x^3 \\cdot x^4 = x^{3 + 4} = x^7$.','Result: $8x^7$.']},
   {stem:'A student writes $(a^3)^4 = a^7$. What is the correct simplification?',choices:['$a^7$; the exponents add','$a^{81}$; the exponent is raised to the power','$a^{12}$; the exponents multiply','$4a^3$; the outer exponent multiplies the term'],key:2,
    miss:['add_for_power_of_power','power_the_exponent',null,'exponent_as_multiplier'],
    why:['Adding exponents is for multiplying two powers of the same base, such as $a^3 \\cdot a^4$.','$3^4 = 81$, but the rule multiplies the exponents rather than raising one to the other.','Correct. $(a^3)^4$ is four factors of $a^3$, so $a^{3 + 3 + 3 + 3} = a^{12}$.','The outer exponent means repeated multiplication of $a^3$, not multiplying by $4$.'],
    steps:['$(a^3)^4 = a^3 \\cdot a^3 \\cdot a^3 \\cdot a^3$.','Add the exponents: $3 + 3 + 3 + 3 = 12$, so the result is $a^{12}$.']},
  ]}),
 lessonQuiz({lesson:'polynomials-special-products-and-factoring',video:'JX5Zvh6swmo',reviewed:'2026-10-08',
  keyIdea:'A trinomial such as $x^2 + 6x + 9$ is a perfect square when its constant is $k^2$ and its middle coefficient is $2k$; then it factors as $(x + k)^2$, because $(a + b)^2 = a^2 + 2ab + b^2$.',
  watchFor:[{at:12,text:'Find two numbers with the needed product and sum. Notice that they turn out to be equal.'},{at:79,text:'Three features of the expression are pointed out. Note all three.'},{at:129,text:'A tempting shortcut for squaring a sum is rejected. Watch the distributing that shows why.'}],
  practice:{url:'https://www.khanacademy.org/math/8th-grade-math-revised-k-to-10-3-terms/x39ed6d789992bb2a:unit-1/x39ed6d789992bb2a:factoring-polynomials/e/intro-to-factoring-perfect-squares',label:'Perfect squares intro',checked:'2026-10-08'},
  items:[
   {stem:'Which feature tells you that $x^2 + bx + c$ is a perfect square trinomial?',choices:['$b$ is a perfect square','$c$ is twice $b$','$c$ is a perfect square and $b$ is twice its square root','All three coefficients are even'],key:2,
    miss:['wrong_term_square','reversed_relation',null,'even_coefficients'],
    why:['The squared number appears as the constant, not as the middle coefficient.','The relationship runs the other way: the middle coefficient is twice the square root of the constant.','Correct. For $x^2 + 6x + 9$: $9 = 3^2$ and $6 = 2 \\times 3$.','$x^2 + 6x + 9$ is a perfect square even though $1$ and $9$ are odd, so evenness is not the test.'],
    steps:['$(x + k)^2 = x^2 + 2kx + k^2$.','So the constant must be $k^2$ and the middle coefficient $2k$.']},
   {stem:'Why is $(a + 7)^2$ not equal to $a^2 + 49$?',choices:['Squaring means $(a + 7)(a + 7)$, and distributing gives two middle terms, $7a + 7a = 14a$','It is equal, because squaring distributes over addition','The $49$ should be $14$, because $7$ is doubled','It should be $a^2 + 7a + 49$, with one middle term'],key:0,
    miss:[null,'square_distributes','doubled_constant','single_cross_term'],
    why:['Correct. $(a + 7)^2 = a^2 + 7a + 7a + 49 = a^2 + 14a + 49$.','Squaring does not distribute over a sum. Try $a = 1$: $(1 + 7)^2 = 64$, but $1 + 49 = 50$.','The constant is $7^2 = 49$. Doubling produces the middle coefficient, $14$.','Distributing twice produces $7a$ twice, so the middle term is $14a$.'],
    steps:['$(a + 7)^2 = (a + 7)(a + 7)$.','Distribute: $a^2 + 7a + 7a + 49$.','Combine: $a^2 + 14a + 49$.']},
   {stem:'Factor $y^2 + 18y + 81$.',choices:['$(y + 81)^2$','$(y + 18)^2$','$(y + 9)(y - 9)$','$(y + 9)^2$'],key:3,
    miss:['forgot_square_root','used_middle_coefficient','difference_of_squares',null],
    why:['$(y + 81)^2$ would have constant $81^2$. Use the square root of $81$, which is $9$.','$(y + 18)^2$ expands to $y^2 + 36y + 324$.','$(y + 9)(y - 9) = y^2 - 81$, with no middle term.','Correct. $81 = 9^2$ and $18 = 2 \\times 9$, so the trinomial is $(y + 9)^2$.'],
    steps:['Constant: $81 = 9^2$.','Middle: $18 = 2 \\times 9$, so it is a perfect square.','$y^2 + 18y + 81 = (y + 9)^2$.']},
   {stem:'Is $x^2 + 8x + 64$ a perfect square trinomial?',choices:['Yes; it factors as $(x + 8)^2$','No; $64 = 8^2$, but the middle coefficient would have to be $2 \\times 8 = 16$','Yes, because $8 \\times 8 = 64$','No, because $64$ is not a perfect square'],key:1,
    miss:['constant_only_check',null,'product_check','wrong_reason'],
    why:['$(x + 8)^2 = x^2 + 16x + 64$, which has a different middle term.','Correct. Both conditions must hold. The constant is a square, but $8 \\ne 16$.','A square constant is only one of the two conditions; the middle coefficient must also be $2 \\times 8$.','$64 = 8^2$ is a perfect square. The middle coefficient is what fails.'],
    steps:['Check the constant: $64 = 8^2$.','Check the middle coefficient: it should be $2 \\times 8 = 16$, but it is $8$.','So it is not a perfect square trinomial.']},
  ]}),
 lessonQuiz({lesson:'rational-expressions',video:'7Uos1ED3KHI',reviewed:'2026-10-08',concept:'rational_expressions',chapter:'m_polynomials',
  keyIdea:'Factor the numerator and denominator, cancel a common factor, and keep the condition that excludes any value that made the original denominator zero.',
  watchFor:[{at:39,text:'A number fraction is reduced first. Watch for the common factor that cancels.'},{at:97,text:'Both parts of an algebraic fraction are factored. Find what they share.'},{at:201,text:'After cancelling, a warning follows. Listen for the condition that must be added.'}],
  practice:{url:'https://www.khanacademy.org/math/pisa-2025-math-supplement/x092b0b93d51c9e96:1/x092b0b93d51c9e96:untitled-2/e/simplifying_rational_expressions_2',label:'Reduce rational expressions to lowest terms',checked:'2026-10-08'},
  items:[
   {stem:'When a rational expression is reduced to lowest terms, what is the first step?',choices:['Factor the numerator and the denominator','Cancel any terms that look the same','Multiply both parts by the denominator','Substitute $0$ for the variable'],key:0,
    miss:[null,'cancel_terms','clear_denominator','substitute_zero'],
    why:['Correct. Only common factors cancel, so you need the factored forms to see them.','Matching terms that are added cannot be cancelled; only whole factors can.','Multiplying the numerator and denominator by the same thing does not reduce the expression.','Substituting one value tests a single number; it does not simplify the expression.'],
    steps:['Factor both parts, for example $9x + 3 = 3(3x + 1)$ and $12x + 4 = 4(3x + 1)$.','Cancel the common factor $3x + 1$.']},
   {stem:'After writing $\\frac{x^2 - 9}{5x + 15}$ as $\\frac{x - 3}{5}$, why must the condition $x \\ne -3$ be added?',choices:['Because $x - 3$ equals zero when $x = 3$','The original expression is undefined at $x = -3$, so the simplified form must exclude it to be truly equal','Because cancelling is not allowed with negative numbers','It is not needed; once simplified, the two expressions agree everywhere'],key:1,
    miss:['wrong_excluded_value',null,'negatives_block_cancel','ignore_domain'],
    why:['A zero numerator is allowed. The excluded value comes from the original denominator.','Correct. $5x + 15 = 0$ when $x = -3$, so the original is undefined there while $\\frac{x - 3}{5}$ is not.','Cancelling common factors works regardless of sign.','The simplified form is defined at $x = -3$ but the original is not, so without the condition they differ there.'],
    steps:['$\\frac{x^2 - 9}{5x + 15} = \\frac{(x + 3)(x - 3)}{5(x + 3)}$.','The original denominator is zero at $x = -3$.','So $\\frac{x - 3}{5}$ with $x \\ne -3$.']},
   {stem:'Simplify $\\frac{6x + 12}{9x + 18}$.',choices:['$\\frac{2}{3}$, for every value of $x$','$\\frac{2}{3}$, with $x \\ne 2$','$\\frac{2}{3}$, with $x \\ne -2$','It cannot be simplified'],key:2,
    miss:['ignore_domain','sign_error_excluded',null,'no_common_factor'],
    why:['At $x = -2$ the original denominator is zero, so the expressions are not equal there.','The denominator $9(x + 2)$ is zero at $x = -2$, not $x = 2$.','Correct. $\\frac{6(x + 2)}{9(x + 2)} = \\frac{2}{3}$, excluding $x = -2$.','Both parts share the factor $x + 2$ once you factor out $6$ and $9$.'],
    steps:['Factor: $6x + 12 = 6(x + 2)$ and $9x + 18 = 9(x + 2)$.','Cancel $x + 2$: $\\frac{6}{9} = \\frac{2}{3}$.','Exclude $x = -2$.']},
   {stem:'A student cancels the $x$ in $\\frac{x + 4}{x + 7}$ and writes $\\frac{4}{7}$. What is wrong?',choices:['Nothing; equal letters may always cancel','They should have cancelled the numbers instead, leaving $\\frac{x}{x}$','The answer is right but needs the condition $x \\ne -7$','Only common factors cancel; here $x$ is a term being added, not a factor of the whole numerator and denominator'],key:3,
    miss:['cancel_terms','cancel_numbers','domain_only',null],
    why:['Try $x = 1$: $\\frac{5}{8}$ is not $\\frac{4}{7}$, so the cancelling changed the value.','Numbers that are added cannot be cancelled either.','The cancellation itself is invalid, so adding a condition does not fix it.','Correct. Neither part factors to share $x$, so the expression is already in lowest terms.'],
    steps:['Cancelling divides the numerator and denominator by the same factor.','$x + 4$ and $x + 7$ have no common factor, so nothing cancels.']},
  ]}),
 lessonQuiz({lesson:'radicals',video:'74iuGIaBgRc',reviewed:'2026-10-08',concept:'radicals',chapter:'m_polynomials',
  keyIdea:'Pull perfect-square factors out of a square root using $\\sqrt{ab} = \\sqrt{a}\\sqrt{b}$, then combine terms with the same root the way you combine like terms.',
  watchFor:[{at:36,text:'Look for the perfect square hiding inside each number under the root.'},{at:111,text:'Two terms with the same root are combined. Think of the root as the thing being counted.'},{at:201,text:'Two roots are multiplied into one. Listen for the exponent property that justifies it.'}],
  practice:{url:'https://www.khanacademy.org/math/10th-grade-math-revised-k-to-10-3-terms/x06a77af3c81397cf:second-quarter/x06a77af3c81397cf:radical-expressions/e/simplifying_radicals',label:'Simplify square roots',checked:'2026-10-08'},
  items:[
   {stem:'Which rewriting simplifies $\\sqrt{40}$ correctly?',choices:['$\\sqrt{4} + \\sqrt{10}$','$\\sqrt{20 \\times 2} = 20\\sqrt{2}$','$4\\sqrt{10}$','$\\sqrt{4 \\times 10} = 2\\sqrt{10}$'],key:3,
    miss:['product_as_sum','non_square_extracted','forgot_root_of_square',null],
    why:['$40 = 4 \\times 10$ is a product, so the root splits into a product, not a sum.','$20$ is not a perfect square, so it cannot come out of the root as $20$.','The $4$ comes out as its square root, $2$.','Correct. $4$ is a perfect square factor, and $\\sqrt{4} = 2$.'],
    steps:['$40 = 4 \\times 10$, and $4$ is a perfect square.','$\\sqrt{40} = \\sqrt{4}\\sqrt{10} = 2\\sqrt{10}$.']},
   {stem:'Why does $3\\sqrt{10} - 2\\sqrt{10}$ equal $\\sqrt{10}$?',choices:['The numbers under the roots subtract too, leaving $1\\sqrt{0}$','$3\\sqrt{10}$ means $\\sqrt{30}$, and $\\sqrt{30} - \\sqrt{20}$ is about $\\sqrt{10}$','Both terms count the same thing, $\\sqrt{10}$; three of it minus two of it leaves one','Any two square roots combine by subtracting the numbers in front'],key:2,
    miss:['subtract_radicands','coefficient_inside',null,'unlike_radicals_combine'],
    why:['The root is the thing being counted, like a unit; it does not change.','$3\\sqrt{10}$ means $3$ times $\\sqrt{10}$, not $\\sqrt{30}$.','Correct. This is like $3k - 2k = k$ with $k = \\sqrt{10}$.','Only like roots combine this way; $\\sqrt{2} + \\sqrt{3}$ does not simplify.'],
    steps:['Factor out the common root: $\\sqrt{10}(3 - 2)$.','$3 - 2 = 1$, so the result is $\\sqrt{10}$.']},
   {stem:'Simplify $\\sqrt{75} + \\sqrt{12}$.',choices:['$7\\sqrt{3}$','$\\sqrt{87}$','$29\\sqrt{3}$','$10\\sqrt{3}$'],key:0,
    miss:[null,'add_radicands','square_not_rooted','multiply_coefficients'],
    why:['Correct. $\\sqrt{75} = 5\\sqrt{3}$ and $\\sqrt{12} = 2\\sqrt{3}$, so the sum is $7\\sqrt{3}$.','Roots do not add by adding the numbers inside.','This brings out $25$ and $4$ themselves instead of their roots, $5$ and $2$.','Like terms add their coefficients: $5 + 2 = 7$, not $5 \\times 2$.'],
    steps:['$\\sqrt{75} = \\sqrt{25 \\times 3} = 5\\sqrt{3}$.','$\\sqrt{12} = \\sqrt{4 \\times 3} = 2\\sqrt{3}$.','$5\\sqrt{3} + 2\\sqrt{3} = 7\\sqrt{3}$.']},
   {stem:'A student writes $\\sqrt{9 + 16} = \\sqrt{9} + \\sqrt{16} = 7$. What is the correct value, and why?',choices:['$7$, because a root splits over a sum','$5$, because $\\sqrt{9 + 16} = \\sqrt{25}$; a root splits over a product, not over a sum','$25$, because the root and the sum cancel','$12.5$, half of $25$'],key:1,
    miss:['root_over_sum',null,'dropped_root','halving_as_root'],
    why:['The rule $\\sqrt{ab} = \\sqrt{a}\\sqrt{b}$ is for products only.','Correct. Add first, then take the root: $\\sqrt{25} = 5$.','The root still applies to the sum, $25$.','Halving is not taking a square root; $5 \\times 5 = 25$.'],
    steps:['Add inside the root: $9 + 16 = 25$.','$\\sqrt{25} = 5$.','Splitting the root over a sum would give $7$, which is wrong.']},
  ]}),
 lessonQuiz({lesson:'linear-equations-and-inequalities',video:'_y_Q3_B2Vh8',reviewed:'2026-10-08',
  keyIdea:'Treat an equation like a balanced scale: whatever you do to one side, do to the other, so undo the added number first and then undo the multiplication.',
  watchFor:[{at:27,text:'Before solving, the scale is turned into an equation. Try writing it yourself first.'},{at:108,text:'The small blocks are removed. Notice what must happen on the other side.'},{at:201,text:'One unknown is isolated from three. Watch what fraction of each side is kept.'}],
  practice:{url:'https://www.khanacademy.org/math/8th-grade-math-revised-k-to-10-3-terms/x39ed6d789992bb2a:2nd-quarter/x39ed6d789992bb2a:linear-equations-in-one-variable/e/linear_equations_2',label:'Two-step equations',checked:'2026-10-08'},
  items:[
   {stem:'Three unknown masses of $x$ kg and two $1$ kg blocks balance fourteen $1$ kg blocks. Which equation matches the scale?',choices:['$5x = 14$','$3x + 2 = 14$','$3x = 14 + 2$','$x + 2 = 14$'],key:1,
    miss:['combined_unlike',null,'wrong_side','dropped_coefficient'],
    why:['The $1$ kg blocks are not unknown masses, so $3x$ and $2$ cannot be combined.','Correct. The left pan holds $3x$ kg plus $2$ kg; the right pan holds $14$ kg.','The $2$ kg sits on the left pan with the unknowns, not on the right.','There are three unknown masses, so the left side has $3x$.'],
    steps:['Left pan: three masses of $x$ kg and $2$ kg, so $3x + 2$.','Right pan: $14$ kg.','Balanced: $3x + 2 = 14$.']},
   {stem:'To solve $3x + 2 = 14$, why must you subtract $2$ from both sides rather than only the left?',choices:['Because subtraction must always be done twice','To make both sides equal to zero','Because the right side is always larger','Removing mass from only one side would unbalance the scale, so the sides would no longer be equal'],key:3,
    miss:['ritual_steps','zero_both_sides','bigger_side',null],
    why:['The point is not repeating a step; it is keeping the two sides equal.','The goal is to isolate $x$, not to make each side zero.','Which side is larger is irrelevant; the sides are equal.','Correct. Doing the same thing to both sides keeps the balance, so the equation stays true.'],
    steps:['Start balanced: $3x + 2 = 14$.','Take $2$ from both pans: $3x = 12$, still balanced.']},
   {stem:'Solve $4x + 5 = 33$.',choices:['$9.5$','$28$','$7$','$3.25$'],key:2,
    miss:['added_instead_of_subtracting','stopped_after_one_step',null,'divide_before_subtract'],
    why:['Adding $5$ to $33$ gives $38$; the $5$ must be subtracted to undo it.','$28$ is $4x$, not $x$. One more step remains.','Correct. Subtract $5$: $4x = 28$. Divide by $4$: $x = 7$.','This divides only $33$ by $4$ and then subtracts $5$; every term must be divided.'],
    steps:['Subtract $5$ from both sides: $4x = 28$.','Divide both sides by $4$: $x = 7$.','Check: $4 \\times 7 + 5 = 33$.']},
   {stem:'To solve $3x + 2 = 14$, a student divides only the $3x$ by $3$ and writes $x + 2 = 14$. What went wrong?',choices:['A division must apply to every term on both sides; subtracting $2$ first gives $3x = 12$, so $x = 4$','Nothing; it leads to $x = 12$','They should have multiplied both sides by $3$','They should have divided both sides by $14$'],key:0,
    miss:[null,'partial_division','inverse_confusion','wrong_divisor'],
    why:['Correct. Undo the addition first, then divide both whole sides by $3$.','$x = 12$ does not check: $3 \\times 12 + 2 = 38$, not $14$.','Multiplying by $3$ makes the coefficient larger; dividing undoes it.','Dividing by $14$ does not isolate $x$.'],
    steps:['Subtract $2$ from both sides: $3x = 12$.','Divide both sides by $3$: $x = 4$.']},
  ]}),
 lessonQuiz({lesson:'systems-of-linear-equations',video:'2EwPpga_XPw',reviewed:'2026-10-08',
  keyIdea:'In substitution, solve one equation for a variable, put that expression in place of the variable in the other equation, and solve the single equation that remains.',
  watchFor:[{at:39,text:'One equation is chosen to solve for a variable. Notice which variable it gives.'},{at:132,text:'The expression replaces the variable. Watch exactly where it goes.'},{at:258,text:'Compare this result with the answer from the earlier method.'}],
  practice:{url:'https://www.khanacademy.org/math/8th-grade-math-revised-k-to-10-3-terms/x39ed6d789992bb2a:3rd-quarter/x39ed6d789992bb2a:systems-of-linear-equations-in-two-variables/e/systems_of_equations_with_substitution',label:'Systems of equations with substitution',checked:'2026-10-08'},
  items:[
   {stem:'What is the first step of the substitution method?',choices:['Add the two equations together','Guess a value and check it','Solve one equation for one variable in terms of the other','Set the two left sides equal to each other'],key:2,
    miss:['elimination_step','guess_check',null,'equate_left_sides'],
    why:['Adding equations is part of elimination, a different method.','Guessing may work by luck, but substitution is a systematic method.','Correct. For example, $100m + 400w = 1100$ becomes $m = -4w + 11$.','The left sides are not equal in general; only each equation’s two sides are equal.'],
    steps:['Pick an equation and isolate one variable.','That expression is then substituted into the other equation.']},
   {stem:'Why does substituting $m = -4w + 11$ into $200m + 300w = 1200$ help?',choices:['It leaves one equation with one unknown, $w$, which can be solved','It gives the value of $m$ without solving anything','It only checks that the other equation is correct','It changes the problem into a new system with different solutions'],key:0,
    miss:[null,'substitution_is_answer','check_only','changes_solution'],
    why:['Correct. Every $m$ becomes an expression in $w$, so only $w$ is unknown.','$m$ is still written in terms of $w$; you need $w$ first.','Substitution is a solving step, not just a check.','Replacing $m$ with an equal expression keeps the same solution.'],
    steps:['$200(-4w + 11) + 300w = 1200$.','$-800w + 2200 + 300w = 1200$, so $-500w = -1000$ and $w = 2$.']},
   {stem:'Solve the system $y = 2x - 1$ and $3x + y = 14$.',choices:['$x = 5$, $y = 3$','$x = 3$, $y = 7$','$x = 2.6$, $y = 6.2$','$x = 3$, $y = 5$'],key:3,
    miss:['swapped_values','sign_error_back_substitution','sign_error_substitution',null],
    why:['These values are swapped: $y = 2(5) - 1 = 9$, not $3$.','$x = 3$ is right, but $y = 2(3) - 1 = 5$, not $7$.','This substitutes $2x + 1$ instead of $2x - 1$.','Correct. $3x + (2x - 1) = 14$ gives $5x = 15$, so $x = 3$ and $y = 5$.'],
    steps:['Substitute: $3x + (2x - 1) = 14$.','$5x - 1 = 14$, so $5x = 15$ and $x = 3$.','Back-substitute: $y = 2(3) - 1 = 5$.']},
   {stem:'After substituting, a student finds $w = 2$ and reports the solution of the system as $2$. What is missing?',choices:['Nothing; one value solves a system','The value of $m$: substitute $w = 2$ into $m = -4w + 11$ to get $m = 3$','The value of $m$, which must equal $w$, so $m = 2$','A second solution by elimination to confirm it'],key:1,
    miss:['one_value_enough',null,'assume_equal','must_use_both_methods'],
    why:['A system in two unknowns needs both values.','Correct. $m = -4(2) + 11 = 3$, and $(m, w) = (3, 2)$ satisfies both equations.','Nothing says $m$ and $w$ are equal; substitute to find $m$.','Checking another way is optional; finding $m$ is not.'],
    steps:['$m = -4(2) + 11 = 3$.','Check: $200(3) + 300(2) = 1200$ and $100(3) + 400(2) = 1100$.']},
  ]}),
 lessonQuiz({lesson:'quadratic-equations',video:'i7idZfS8t8w',reviewed:'2026-10-08',
  keyIdea:'For $ax^2 + bx + c = 0$, the quadratic formula $x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}$ gives the solutions even when factoring is hard; a negative value of $b^2 - 4ac$ means there are no real solutions.',
  watchFor:[{at:54,text:'The general equation is written. Note what each letter in it stands for.'},{at:390,text:'Before the formula is used, the equation is rearranged. Notice why.'},{at:533,text:'The number under the root turns out negative. Listen for what that says about the graph.'}],
  practice:{url:'https://www.khanacademy.org/math/9th-grade-math-revised-k-to-10-3-terms/x1e64c39423990571:2nd-quarter/x1e64c39423990571:solving-quadratic-equations/e/quadratic_equation',label:'Solve quadratic equations with the quadratic formula',checked:'2026-10-08'},
  items:[
   {stem:'In the quadratic formula, which expression sits under the square root?',choices:['$b^2 - 4ac$','$b^2 + 4ac$','$4ac - b^2$','$b - 4ac$'],key:0,
    miss:[null,'sign_inside_root','reversed_discriminant','forgot_square'],
    why:['Correct. The formula is $x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}$.','The sign is minus: $b^2 - 4ac$.','The order matters; reversing it flips the sign.','$b$ is squared under the root.'],
    steps:['$x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}$.']},
   {stem:'Why is $3x^2 + 6x = -10$ rewritten as $3x^2 + 6x + 10 = 0$ before the formula is used?',choices:['Because the formula only works when $c$ is positive','To make the equation easy to factor','The formula solves $ax^2 + bx + c = 0$, so every term must be on one side with zero on the other before reading off $c$','It is not necessary; $c$ can be read as $-10$ directly'],key:2,
    miss:['c_positive','formula_needs_factoring',null,'wrong_c_sign'],
    why:['The formula works for any sign of $c$; the issue is the zero on one side.','The formula is used precisely because factoring may be hard.','Correct. Adding $10$ to both sides gives the standard form, where $c = 10$.','With $-10$ on the right side, $c$ is not $-10$. Moving it across makes $c = 10$.'],
    steps:['Add $10$ to both sides: $3x^2 + 6x + 10 = 0$.','Now $a = 3$, $b = 6$ and $c = 10$.']},
   {stem:'Solve $x^2 + 2x - 15 = 0$ with the quadratic formula.',choices:['$x = -3$ or $x = 5$','$x = 6$ or $x = -10$','No real solutions','$x = 3$ or $x = -5$'],key:3,
    miss:['sign_of_b','forgot_divide_2a','wrong_c_sign',null],
    why:['These signs come from using $+b$ instead of $-b$ at the start of the formula.','These are the numerators, $-2 \\pm 8$, before dividing by $2a = 2$.','With $c = -15$, $b^2 - 4ac = 4 + 60 = 64$, which is positive.','Correct. $\\frac{-2 \\pm \\sqrt{64}}{2} = \\frac{-2 \\pm 8}{2}$, giving $3$ or $-5$.'],
    steps:['$a = 1$, $b = 2$, $c = -15$.','$b^2 - 4ac = 4 + 60 = 64$, and $\\sqrt{64} = 8$.','$x = \\frac{-2 \\pm 8}{2}$, so $x = 3$ or $x = -5$.']},
   {stem:'For $2x^2 + 4x + 5 = 0$, a student finds $b^2 - 4ac = 16 - 40 = -24$ and decides the formula has failed. What does this result actually mean?',choices:['The arithmetic must be wrong, because $b^2 - 4ac$ is never negative','The equation has no real solutions; its graph never crosses the $x$-axis','The solutions are $x = \\pm\\sqrt{24}$','The equation has exactly one solution, $x = -1$'],key:1,
    miss:['discriminant_never_negative',null,'drop_sign','vertex_as_root'],
    why:['$b^2 - 4ac$ can be negative whenever $4ac$ is larger than $b^2$.','Correct. A real square root of a negative number does not exist, so there are no real solutions.','Dropping the negative sign changes the problem; the root of $-24$ is not real.','$x = -1$ is where the parabola turns, but it does not reach zero there.'],
    steps:['$b^2 - 4ac = 16 - 4(2)(5) = -24$.','A negative value under the root means no real solutions.']},
  ]}),
 lessonQuiz({lesson:'functions-and-their-graphs',video:'Id6UovYjd-M',reviewed:'2026-10-08',
  keyIdea:'To evaluate a function such as $f(x) = 49 - x^2$ at an input, replace every $x$ in the rule with that input and simplify.',
  watchFor:[{at:0,text:'A rule and an input are given. Identify each before calculating.'},{at:14,text:'The function is pictured as a box. Listen for what the box does to its input.'},{at:28,text:'Watch what takes the place of each $x$ in the rule.'}],
  practice:{url:'https://www.khanacademy.org/math/als-k-to-12-math/x54b4346ef80b5dcc:performance-standard-e/x54b4346ef80b5dcc:polynomial-functions/e/functions_1',label:'Evaluate functions',checked:'2026-10-08'},
  items:[
   {stem:'In $f(5)$, what does the $5$ represent?',choices:['The output of the function','A number multiplied by $f$','The number of times to apply the rule','The input that replaces $x$ in the rule'],key:3,
    miss:['input_output_swap','notation_as_product','repeat_count',null],
    why:['$f(5)$ is the output; the $5$ inside the brackets is what goes in.','$f(5)$ is function notation, not $f$ times $5$.','The rule is applied once, to the input $5$.','Correct. $f(5)$ means the output when the input is $5$.'],
    steps:['In $f(5)$, the $5$ is the input.','Substitute it for $x$ in the rule to find the output.']},
   {stem:'Why is $f(5)$ equal to $49 - 5^2$ when $f(x) = 49 - x^2$?',choices:['Because $f(5)$ means $f \\times 5$','Every $x$ in the rule is replaced by the input, $5$','Because $5$ is subtracted from $49$ and the result is squared','Because the $x$ becomes $5x$'],key:1,
    miss:['notation_as_product',null,'order_of_operations','coefficient_insert'],
    why:['The brackets in $f(5)$ hold the input; nothing is multiplied by $f$.','Correct. The rule says square the input and subtract it from $49$.','The rule squares the input first; subtracting first gives $(49 - 5)^2$, a different expression.','The input replaces $x$; it does not multiply it.'],
    steps:['Replace $x$ with $5$: $f(5) = 49 - 5^2$.','$49 - 25 = 24$.']},
   {stem:'If $g(x) = 3x^2 - 7$, what is $g(-2)$?',choices:['$5$','$-19$','$29$','$-13$'],key:0,
    miss:[null,'negative_square','multiply_before_square','forgot_square'],
    why:['Correct. $(-2)^2 = 4$, so $3 \\times 4 - 7 = 5$.','This treats $(-2)^2$ as $-4$. A negative number squared is positive.','This squares $3 \\times (-2)$; only the input is squared.','This forgets to square the input: $3 \\times (-2) - 7$.'],
    steps:['Replace $x$ with $-2$: $g(-2) = 3(-2)^2 - 7$.','$(-2)^2 = 4$, so $3 \\times 4 - 7 = 12 - 7 = 5$.']},
   {stem:'For $f(x) = 49 - x^2$, a student writes $f(5) = 44^2$, because $49 - 5 = 44$. What is the mistake?',choices:['There is none; subtract first because it appears first','$49$ should be squared as well','Exponents come before subtraction: square $5$ first, so $f(5) = 49 - 25 = 24$','$5^2$ means $5 \\times 2$, so $f(5) = 39$'],key:2,
    miss:['left_to_right_over_exponent','square_everything',null,'exponent_as_multiplier'],
    why:['Position does not beat priority; exponents come before subtraction.','Only the input is squared in this rule.','Correct. The rule squares the input, then subtracts it from $49$.','$5^2 = 5 \\times 5 = 25$, not $10$.'],
    steps:['$f(5) = 49 - 5^2$.','Exponent first: $5^2 = 25$.','$49 - 25 = 24$.']},
  ]}),
 lessonQuiz({lesson:'the-coordinate-plane-lines-and-slope',video:'WkspBxrzuZo',reviewed:'2026-10-08',
  keyIdea:'Slope is the change in $y$ divided by the change in $x$, $m = \\frac{y_2 - y_1}{x_2 - x_1}$; either point can be the start as long as both differences use the same order.',
  watchFor:[{at:16,text:'Slope is defined in two ways. Note what the triangle symbol means.'},{at:68,text:'A start point and an end point are chosen. Watch how the change in $x$ is found.'},{at:197,text:'The points are swapped. Predict whether the slope changes before it is worked out.'}],
  practice:{url:'https://www.khanacademy.org/math/pisa-2025-math-supplement/x092b0b93d51c9e96:1/x092b0b93d51c9e96:equations/e/slope-from-two-points',label:'Slope from two points',checked:'2026-10-08'},
  items:[
   {stem:'Which formula gives the slope of the line through $(x_1, y_1)$ and $(x_2, y_2)$?',choices:['$m = \\frac{x_2 - x_1}{y_2 - y_1}$','$m = \\frac{y_2 - y_1}{x_2 - x_1}$','$m = \\frac{y_2 - y_1}{x_1 - x_2}$','$m = \\frac{y_2 + y_1}{x_2 + x_1}$'],key:1,
    miss:['run_over_rise',null,'mixed_order','sum_not_difference'],
    why:['This is run over rise, upside down.','Correct. Rise over run: the change in $y$ over the change in $x$, both in the same order.','The two differences use opposite orders, which flips the sign.','Slope uses differences, not sums.'],
    steps:['Slope is $\\frac{\\Delta y}{\\Delta x}$.','$m = \\frac{y_2 - y_1}{x_2 - x_1}$.']},
   {stem:'Why do you get the same slope whichever of the two points you treat as the start?',choices:['Because slope is always positive','Because only the change in $y$ matters','You do not; swapping the points reverses the sign of the slope','Swapping makes both the change in $y$ and the change in $x$ change sign, and the two signs cancel'],key:3,
    miss:['slope_always_positive','rise_only','swap_changes_sign',null],
    why:['Slopes can be negative, as for a line falling from left to right.','The change in $x$ matters too; slope is a ratio.','Both differences flip, so their ratio is unchanged.','Correct. $\\frac{14}{-7}$ and $\\frac{-14}{7}$ are both $-2$.'],
    steps:['From $(4, 2)$ to $(-3, 16)$: $\\frac{14}{-7} = -2$.','From $(-3, 16)$ to $(4, 2)$: $\\frac{-14}{7} = -2$.']},
   {stem:'Find the slope of the line through $(2, -3)$ and $(6, 9)$.',choices:['$\\frac{1}{3}$','$-3$','$3$','$\\frac{3}{4}$'],key:2,
    miss:['run_over_rise','mixed_order',null,'sum_not_difference'],
    why:['This divides the change in $x$ by the change in $y$.','The differences were taken in opposite orders.','Correct. $\\frac{9 - (-3)}{6 - 2} = \\frac{12}{4} = 3$.','This adds the coordinates: $\\frac{9 + (-3)}{6 + 2} = \\frac{6}{8}$.'],
    steps:['$\\Delta y = 9 - (-3) = 12$.','$\\Delta x = 6 - 2 = 4$.','$m = \\frac{12}{4} = 3$.']},
   {stem:'A student finds the slope through $(4, 2)$ and $(-3, 16)$ as $\\frac{16 - 2}{4 - (-3)} = 2$. What went wrong?',choices:['The change in $y$ runs from the first point to the second, but the change in $x$ runs the other way; the same order gives $\\frac{14}{-7} = -2$','Nothing; the slope is $2$','They should have added the coordinates','Slope is change in $x$ over change in $y$, so it is $-\\frac{1}{2}$'],key:0,
    miss:[null,'mixed_order','sum_not_difference','run_over_rise'],
    why:['Correct. Keep one order for both differences.','A line from $(-3, 16)$ down to $(4, 2)$ falls, so its slope must be negative.','Slope uses differences, not sums.','Slope is rise over run, change in $y$ over change in $x$.'],
    steps:['$\\Delta y = 16 - 2 = 14$ and $\\Delta x = -3 - 4 = -7$.','$m = \\frac{14}{-7} = -2$.']},
  ]}),
 lessonQuiz({lesson:'exponents-and-logarithms',video:'Obch1OP5QyA',reviewed:'2026-10-08',concept:'logarithms',chapter:'m_polynomials',
  keyIdea:'$\\log_b a = c$ says the same thing as $b^c = a$: a logarithm is the power you raise the base to in order to get the number.',
  watchFor:[{at:0,text:'A power of $10$ is rewritten. Listen for the question the logarithm answers.'},{at:46,text:'Watch how the base is written in logarithmic form.'},{at:59,text:'A logarithm with a negative value is turned back into a power.'}],
  practice:{url:'https://www.khanacademy.org/math/senior-high-school-general-math/xc1934d16446a5789:unit-1/xc1934d16446a5789:logarithmic-functions/e/understanding-logs-as-inverse-exponentials',label:'Relationship between exponentials & logarithms',checked:'2026-10-08'},
  items:[
   {stem:'Which logarithmic statement says the same thing as $10^2 = 100$?',choices:['$\\log_{2} 100 = 10$','$\\log_{10} 2 = 100$','$\\log_{10} 100 = 2$','$\\log_{100} 10 = 2$'],key:2,
    miss:['base_exponent_swap','argument_result_swap',null,'wrong_base'],
    why:['The base of the power, $10$, must be the base of the logarithm.','The logarithm gives the exponent, $2$; it takes the result, $100$.','Correct. The power you raise $10$ to in order to get $100$ is $2$.','The base is $10$, not $100$.'],
    steps:['$b^c = a$ becomes $\\log_b a = c$.','$10^2 = 100$ becomes $\\log_{10} 100 = 2$.']},
   {stem:'Why is $\\log_5 \\frac{1}{125} = -3$?',choices:['Because $\\frac{1}{125}$ is a negative number','Because the power that turns $5$ into $\\frac{1}{125}$ is $-3$: $5^{-3} = \\frac{1}{125}$','Because $5 \\times (-3)$ gives $\\frac{1}{125}$','Because a number less than $1$ always has logarithm $-3$'],key:1,
    miss:['fraction_is_negative',null,'log_as_product','fixed_negative_log'],
    why:['$\\frac{1}{125}$ is positive. The logarithm is negative because the exponent is.','Correct. $5^{-3} = \\frac{1}{5^3} = \\frac{1}{125}$.','A logarithm is an exponent, not a factor: $5 \\times (-3) = -15$.','The value depends on the number: $\\log_5 \\frac{1}{25} = -2$.'],
    steps:['Ask: $5$ to what power gives $\\frac{1}{125}$?','$5^3 = 125$, so $5^{-3} = \\frac{1}{125}$, and the logarithm is $-3$.']},
   {stem:'What is $\\log_3 81$?',choices:['$27$','$9$','$243$','$4$'],key:3,
    miss:['log_as_division','log_as_root','log_as_product',null],
    why:['$81 \\div 3 = 27$, but a logarithm asks for an exponent.','$\\sqrt{81} = 9$ is a square root; a logarithm asks for the exponent: $3$ to what power gives $81$?','$81 \\times 3 = 243$ multiplies instead of finding the exponent.','Correct. $3^4 = 81$, so $\\log_3 81 = 4$.'],
    steps:['Ask: $3$ to what power gives $81$?','$3 \\times 3 \\times 3 \\times 3 = 81$, so the answer is $4$.']},
   {stem:'A student rewrites $\\log_4 16 = 2$ as $2^4 = 16$. Why is this a problem, even though $2^4 = 16$ is true?',choices:['The base of the logarithm, $4$, must be the base of the power: $4^2 = 16$','It is not a problem; both forms say the same thing','The correct form is $16^2 = 4$','The correct form is $4^{16} = 2$'],key:0,
    miss:[null,'base_exponent_swap','argument_result_swap','wrong_rearrangement'],
    why:['Correct. The statement is about base $4$. Swapping base and exponent only works here by coincidence.','Try $\\log_3 9 = 2$: swapping gives $2^3 = 8$, not $9$.','The number inside the logarithm is the result of the power, not its base.','The value of the logarithm is the exponent, not the result.'],
    steps:['$\\log_b a = c$ means $b^c = a$.','$\\log_4 16 = 2$ means $4^2 = 16$.']},
  ]}),
 lessonQuiz({lesson:'sequences-and-series',video:'cYw4MFWsB6c',reviewed:'2026-10-08',
  keyIdea:'Writing $1 + 2 + \\ldots + n$ forwards and backwards and adding gives $n$ pairs that each total $n + 1$, so the sum is $\\frac{n(n + 1)}{2}$.',
  watchFor:[{at:37,text:'The same sum is written a second time. Notice the order of its terms.'},{at:65,text:'Matching terms are added in pairs. Look at what every pair adds to.'},{at:186,text:'The formula is reread as an average times a count. Listen for which two terms are averaged.'}],
  practice:{url:'https://www.khanacademy.org/math/strengthened-shs-general-math/x24dc5a0902f75de5:first-quarter/x24dc5a0902f75de5:series/e/arithmetic_series',label:'Arithmetic series',checked:'2026-10-08'},
  items:[
   {stem:'What is the sum $1 + 2 + 3 + \\ldots + n$?',choices:['$n(n + 1)$','$\\frac{n(n + 1)}{2}$','$\\frac{n(n - 1)}{2}$','$\\frac{n^2}{2}$'],key:1,
    miss:['forgot_halving',null,'off_by_one','dropped_term'],
    why:['$n(n + 1)$ is twice the sum, because the list was added to its own reverse.','Correct. $n$ pairs of $n + 1$, halved because the sum was doubled.','Each pair adds to $n + 1$, not $n - 1$.','The pairs add to $n + 1$, so the $+1$ cannot be dropped.'],
    steps:['$2S_n = n(n + 1)$.','$S_n = \\frac{n(n + 1)}{2}$.']},
   {stem:'Why is the doubled sum, $2S_n$, equal to $n(n + 1)$?',choices:['Because the largest term is $n$ and the next number is $n + 1$','Because there are $n + 1$ terms in the list','Because every term is doubled to become $n + 1$','Adding the forward and reversed lists pairs the terms, and each of the $n$ pairs adds to $n + 1$'],key:3,
    miss:['adjacent_terms','term_count','double_each_term',null],
    why:['$n + 1$ is not the next term; it is what each pair adds to.','There are $n$ terms, so there are $n$ pairs.','Terms are not doubled individually; matching terms from the two lists are added.','Correct. $1 + n$, $2 + (n - 1)$ and so on each give $n + 1$.'],
    steps:['Forward: $1 + 2 + \\ldots + n$. Reversed: $n + (n - 1) + \\ldots + 1$.','Each matching pair adds to $n + 1$, and there are $n$ pairs.']},
   {stem:'What is $1 + 2 + 3 + \\ldots + 60$?',choices:['$1830$','$3660$','$1770$','$1800$'],key:0,
    miss:[null,'forgot_halving','off_by_one','dropped_term'],
    why:['Correct. $\\frac{60 \\times 61}{2} = 1830$.','$60 \\times 61 = 3660$ is the doubled sum; halve it.','This uses $60 \\times 59$, but each pair adds to $61$.','$\\frac{60^2}{2} = 1800$ drops the $+1$ in each pair.'],
    steps:['$n = 60$.','$\\frac{60 \\times 61}{2} = \\frac{3660}{2} = 1830$.']},
   {stem:'A student says $1 + 2 + \\ldots + 100 = 100 \\times 101 = 10{,}100$. What is wrong?',choices:['Nothing; that is the sum','There are only $99$ pairs, so it is $99 \\times 101$','Adding the list to its reverse counts every number twice, so divide by $2$: the sum is $5050$','The pairs add to $100$, so it is $\\frac{100 \\times 100}{2}$'],key:2,
    miss:['forgot_halving','off_by_one',null,'pair_sum_error'],
    why:['$100 \\times 101$ is the doubled sum.','There are $100$ numbers, so $100$ pairs when the two lists are lined up.','Correct. $\\frac{100 \\times 101}{2} = 5050$.','Each pair is $1 + 100 = 101$, not $100$.'],
    steps:['Each pair adds to $101$, and there are $100$ pairs: $10{,}100$.','That counts the sum twice, so the sum is $5050$.']},
  ]}),
 lessonQuiz({lesson:'word-problems',video:'oRKxmXwLvUU',reviewed:'2026-10-08',
  keyIdea:'Average velocity is displacement, with its direction, divided by elapsed time, while speed is distance divided by time with no direction; units convert by multiplying by factors equal to one.',
  watchFor:[{at:37,text:'Two quantities are separated: one includes a direction and one does not.'},{at:152,text:'Velocity and speed are defined side by side. Compare what each one divides.'},{at:421,text:'Kilometres per hour are converted. Watch how each factor is arranged so units cancel.'}],
  practice:{url:'https://www.khanacademy.org/science/strengthened-shs-physics-1/x5eb5cea12d2cf683:introduction-to-physics/x5eb5cea12d2cf683:descriptors-of-motion/e/practice--velocity---speed--without-graphs-',label:'Average velocity and speed in one direction: word problems',checked:'2026-10-08'},
  items:[
   {stem:'Which of these is a vector quantity?',choices:['Displacement, such as $5$ km to the north','Distance, such as $5$ km','Speed, such as $5$ km per hour','Time, such as $1$ hour'],key:0,
    miss:[null,'distance_vector','speed_vector','time_vector'],
    why:['Correct. Displacement has a size and a direction.','Distance has a size only, so it is a scalar.','Speed has no direction; with a direction it would be velocity.','Elapsed time has no direction.'],
    steps:['A vector has a size and a direction.','$5$ km to the north gives both, so displacement is a vector.']},
   {stem:'Why is “$5$ kilometres per hour” a speed rather than a velocity?',choices:['Because it uses kilometres rather than metres','Because the time is one hour','It gives only a size; a velocity also needs a direction, such as north','Because a velocity is always larger than a speed'],key:2,
    miss:['units_decide','time_decides',null,'velocity_larger'],
    why:['The units do not decide; $5$ metres per second north is a velocity.','The time interval does not decide either.','Correct. Adding “to the north” would make it a velocity.','Their sizes can be equal: $5$ metres per second north has the same size as a speed of $5$ metres per second.'],
    steps:['Speed: distance over time, with no direction.','Velocity: displacement over time, with direction.']},
   {stem:'A cyclist rides $18$ km east in $0.5$ hours. What is the average velocity?',choices:['$9$ km per hour east','$36$ km per hour east','$36$ km per hour','$18.5$ km per hour east'],key:1,
    miss:['multiply_by_time',null,'dropped_direction','added_quantities'],
    why:['Velocity divides displacement by time; it does not multiply.','Correct. $\\frac{18}{0.5} = 36$ km per hour, to the east.','The size is right, but without a direction this is a speed.','Adding the numbers has no meaning here; divide displacement by time.'],
    steps:['$\\text{velocity} = \\frac{\\text{displacement}}{\\text{time}}$.','$\\frac{18}{0.5} = 36$, so $36$ km per hour east.']},
   {stem:'Converting $72$ km per hour to metres per second, a student multiplies by $1000$ and by $3600$ and gets $259{,}200{,}000$ metres per second. What went wrong?',choices:['Nothing; converting to smaller units always gives bigger numbers','They should divide by $1000$ and multiply by $3600$','They should only divide by $60$','The hours must cancel: multiply by $\\frac{1000\\ \\text{m}}{1\\ \\text{km}}$ and by $\\frac{1\\ \\text{h}}{3600\\ \\text{s}}$, giving $20$ metres per second'],key:3,
    miss:['no_gut_check','inverted_both','single_factor',null],
    why:['A gut check fails: metres per second should be a smaller number than metres per hour.','Both factors are then upside down: kilometres would not cancel.','An hour has $3600$ seconds, and kilometres must also become metres.','Correct. $72 \\times 1000 = 72{,}000$ metres per hour, and $\\frac{72{,}000}{3600} = 20$.'],
    steps:['$72 \\times \\frac{1000}{1} = 72{,}000$ metres per hour.','$\\frac{72{,}000}{3600} = 20$ metres per second.']},
  ]}),
 lessonQuiz({lesson:'imaginary-and-complex-numbers',video:'ysVcAYo7UPI',reviewed:'2026-10-08',concept:'complex_numbers',chapter:'m_quadratics',
  keyIdea:'The imaginary unit $i$ is defined by $i^2 = -1$, so its powers repeat in a cycle of four: $i$, $-1$, $-i$, $1$.',
  watchFor:[{at:25,text:'Listen for the single property that defines $i$.'},{at:149,text:'Each new power is built from the one before. Watch how the third power comes out.'},{at:235,text:'Compare the fourth power with the zeroth power, then watch the pattern repeat.'}],
  practice:{url:'https://www.khanacademy.org/math/algebra2/x2ec2f6f830c9fb89:complex/x2ec2f6f830c9fb89:imaginary/e/imaginary_unit_powers',label:'Powers of the imaginary unit',checked:'2026-10-08'},
  items:[
   {stem:'How is the imaginary unit $i$ defined?',choices:['The number $-1$','The number whose square is $1$','The number $\\sqrt{1}$, which is $1$','The number whose square is $-1$'],key:3,
    miss:['i_equals_minus_one','sign_dropped','root_of_one',null],
    why:['$i$ is not $-1$; it is $i^2$ that equals $-1$.','A number whose square is $1$ is $1$ or $-1$, both real.','$\\sqrt{1} = 1$ is real; $i$ is not.','Correct. $i^2 = -1$.'],
    steps:['$i$ is defined by $i^2 = -1$.']},
   {stem:'Why is $i^3$ equal to $-i$?',choices:['$i^3 = i^2 \\cdot i$, and $i^2 = -1$, so $i^3 = -1 \\cdot i = -i$','Because $i^3$ means $3i$','Because every odd power of $i$ is $-i$','Because $i^3 = (-1)(-1)(-1)$'],key:0,
    miss:[null,'exponent_as_multiplier','odd_powers_negative','i_equals_minus_one'],
    why:['Correct. Build each power from the one before.','An exponent means repeated multiplication, not multiplying by $3$.','$i^1 = i$ and $i^5 = i$ are odd powers too.','This treats $i$ itself as $-1$.'],
    steps:['$i^3 = i^2 \\cdot i$.','$i^2 = -1$, so $i^3 = -i$.']},
   {stem:'What is $i^{10}$?',choices:['$1$','$10i$','$-1$','$i$'],key:2,
    miss:['even_powers_positive','exponent_as_multiplier',null,'exponent_ignored'],
    why:['Even powers of $i$ alternate between $-1$ and $1$; $i^{10}$ is $-1$.','An exponent is not a multiplier.','Correct. $i^{10} = i^8 \\cdot i^2 = 1 \\cdot (-1) = -1$.','The cycle repeats every four powers; $10$ leaves remainder $2$, which gives $-1$.'],
    steps:['The cycle has length $4$: $i$, $-1$, $-i$, $1$.','$i^8 = 1$, so $i^{10} = i^2 = -1$.']},
   {stem:'A student says $i^4 = -1$ because $i^2 = -1$. What is the correct value of $i^4$?',choices:['$-1$, because every power of $i$ is $-1$','$1$, because $i^4 = i^2 \\cdot i^2 = (-1)(-1)$','$4i$','$-4$'],key:1,
    miss:['all_powers_negative',null,'exponent_as_multiplier','exponent_times_value'],
    why:['Only some powers are $-1$; the powers cycle.','Correct. Two factors of $-1$ multiply to $1$.','An exponent means repeated multiplication.','The exponent does not multiply the value of $i^2$.'],
    steps:['$i^4 = i^2 \\cdot i^2$.','$(-1)(-1) = 1$.']},
  ]}),
];
