import {lessonQuiz} from './author.ts';

/** UPCAT Mathematics: Trigonometry. Original draft items written from Khan's timestamped
 * caption transcripts, read 2026-10-08; pending subject review.
 * Receipts: docs/THIRD_PARTY_MATERIALS.md, "Lesson quiz caption reviews". */
export const MATH_TRIGONOMETRY=[
 lessonQuiz({lesson:'the-six-trigonometric-ratios',video:'Jsiy4TxgIME',reviewed:'2026-10-08',
  keyIdea:'In a right triangle, sine is opposite over hypotenuse, cosine is adjacent over hypotenuse and tangent is opposite over adjacent; which side is opposite or adjacent depends on the angle you choose.',
  watchFor:[{at:67,text:'The side lengths are checked against the Pythagorean theorem first.'},{at:159,text:'A memory aid is written. Note what each part of it stands for.'},{at:388,text:'The other acute angle is used. Watch which sides change their names.'}],
  practice:{url:'https://www.khanacademy.org/math/9th-grade-math-revised-k-to-10-3-terms/x1e64c39423990571:3rd-quarter/x1e64c39423990571:trigonometric-ratios/e/trigonometry_1',label:'Trigonometric ratios in right triangles',checked:'2026-10-08'},
  items:[
   {stem:'In the memory aid “soh cah toa”, what does “toa” say?',choices:['Tangent is opposite over hypotenuse','Tangent is adjacent over opposite','Tangent is opposite over adjacent','Tangent is adjacent over hypotenuse'],key:2,
    miss:['tan_as_sin','inverted_tan',null,'tan_as_cos'],
    why:['Opposite over hypotenuse is sine, the “soh” part.','This is the reciprocal of tangent.','Correct. T-O-A: tangent, opposite, adjacent.','Adjacent over hypotenuse is cosine, the “cah” part.'],
    steps:['soh: $\\sin = \\frac{\\text{opposite}}{\\text{hypotenuse}}$; cah: $\\cos = \\frac{\\text{adjacent}}{\\text{hypotenuse}}$; toa: $\\tan = \\frac{\\text{opposite}}{\\text{adjacent}}$.']},
   {stem:'In a right triangle with sides $3$, $4$ and $5$, why is the side of length $4$ adjacent to one acute angle but opposite the other?',choices:['Opposite and adjacent are named from the chosen angle: a side that forms the angle is adjacent, and the side it opens onto is opposite','Because the side of length $4$ is the hypotenuse','Because opposite always means the shorter of the two legs','It cannot be; each side keeps one fixed name'],key:0,
    miss:[null,'wrong_hypotenuse','opposite_shorter','fixed_names'],
    why:['Correct. Change the angle and the roles of the two legs swap; only the hypotenuse stays the same.','The hypotenuse is $5$, opposite the right angle.','Length does not decide; the position relative to the angle does.','Only the hypotenuse has a fixed name. The legs are named from the angle.'],
    steps:['For angle $\\theta$, the leg forming $\\theta$ is adjacent and the leg across from it is opposite.','For the other acute angle, the two legs swap roles.']},
   {stem:'A right triangle has legs $5$ and $12$ and hypotenuse $13$. For the angle $\\theta$ between the side of length $12$ and the hypotenuse, what is $\\sin\\theta$?',choices:['$\\frac{12}{13}$','$\\frac{5}{12}$','$\\frac{13}{5}$','$\\frac{5}{13}$'],key:3,
    miss:['used_adjacent','used_tangent','inverted_ratio',null],
    why:['$12$ forms the angle, so it is adjacent; this is $\\cos\\theta$.','Opposite over adjacent is $\\tan\\theta$.','This is the ratio upside down.','Correct. The side opposite $\\theta$ is $5$, so $\\sin\\theta = \\frac{5}{13}$.'],
    steps:['Opposite $\\theta$: $5$. Hypotenuse: $13$.','$\\sin\\theta = \\frac{5}{13}$.']},
   {stem:'In a right triangle with sides $8$, $15$ and $17$, the side of length $15$ forms angle $\\theta$ with the hypotenuse. A student writes $\\cos\\theta = \\frac{15}{8}$. What is the correct value?',choices:['$\\frac{15}{8}$, as written','$\\frac{15}{17}$, because cosine divides the adjacent side by the hypotenuse','$\\frac{8}{17}$, because adjacent means the shorter leg','$\\frac{8}{15}$, because cosine is opposite over adjacent'],key:1,
    miss:['cos_over_opposite',null,'opposite_shorter','cos_as_tan'],
    why:['Dividing by the opposite side does not give cosine; a cosine is never more than $1$.','Correct. Adjacent is $15$ and the hypotenuse is $17$.','$8$ is opposite $\\theta$; $15$ forms the angle.','Opposite over adjacent is tangent.'],
    steps:['Adjacent to $\\theta$: $15$. Hypotenuse: $17$.','$\\cos\\theta = \\frac{15}{17}$.']},
  ]}),
 lessonQuiz({lesson:'special-angles-and-the-unit-circle',video:'1m9p9iubMLU',reviewed:'2026-10-08',
  keyIdea:'On a unit circle, an angle measured counterclockwise from the positive $x$-axis ends at a point $(a, b)$, and that point gives $\\cos\\theta = a$ and $\\sin\\theta = b$, extending sine and cosine to any angle.',
  watchFor:[{at:13,text:'The four points where the circle meets the axes are found.'},{at:64,text:'A rule for positive angles is set. Note the direction of turning.'},{at:384,text:'The triangle definition runs into trouble. Listen for the angles where it breaks.'}],
  practice:{url:'https://www.khanacademy.org/math/senior-high-school-precalculus/x3589147324a289c1:trigonometry/x3589147324a289c1:trigonometric-identities/e/circles-and-pythagorean-identities',label:'Use the Pythagorean identity',checked:'2026-10-08'},
  items:[
   {stem:'On the unit circle, the terminal side of angle $\\theta$ meets the circle at $(a, b)$. Which statement is true?',choices:['$\\sin\\theta = a$ and $\\cos\\theta = b$','$\\cos\\theta = a$ and $\\sin\\theta = b$','$\\cos\\theta = \\frac{a}{b}$','$\\cos\\theta = 2a$ and $\\sin\\theta = 2b$, because the diameter is $2$'],key:1,
    miss:['swap_sin_cos',null,'ratio_confusion','diameter_confusion'],
    why:['Sine and cosine are swapped: cosine goes with the horizontal coordinate.','Correct. Cosine is the $x$-coordinate and sine is the $y$-coordinate.','$\\frac{a}{b}$ divides one coordinate by the other (it is the reciprocal of the tangent). Cosine is just the $x$-coordinate, $a$.','The hypotenuse is a radius, length $1$, not the diameter.'],
    steps:['Hypotenuse: the radius, $1$.','$\\cos\\theta = \\frac{a}{1} = a$ and $\\sin\\theta = \\frac{b}{1} = b$.']},
   {stem:'Why does the cosine of $\\theta$ equal the $x$-coordinate $a$ on the unit circle?',choices:['Because cosine is always the larger coordinate','Because the angle is measured clockwise','Because $a$ is the height of the triangle','The hypotenuse is a radius of length $1$, so adjacent over hypotenuse is $\\frac{a}{1} = a$'],key:3,
    miss:['larger_coordinate','direction_confusion','height_as_adjacent',null],
    why:['Either coordinate can be larger, depending on the angle.','Positive angles are measured counterclockwise, and direction is not the reason anyway.','The height is $b$; $a$ is the base along the $x$-axis.','Correct. Dividing by $1$ leaves the adjacent side, $a$.'],
    steps:['The adjacent side runs along the $x$-axis and has length $a$.','$\\cos\\theta = \\frac{a}{1} = a$.']},
   {stem:'Which point on the unit circle matches an angle of $90^\\circ$, and what is $\\cos 90^\\circ$?',choices:['$(0, 1)$, so $\\cos 90^\\circ = 0$','$(1, 0)$, so $\\cos 90^\\circ = 1$','$(0, 1)$, so $\\cos 90^\\circ = 1$','$(-1, 0)$, so $\\cos 90^\\circ = -1$'],key:0,
    miss:[null,'start_point','swap_sin_cos','half_turn'],
    why:['Correct. A quarter turn counterclockwise reaches the top of the circle, where the $x$-coordinate is $0$.','$(1, 0)$ is where angles start, at $0^\\circ$.','The point is right, but $1$ is its $y$-coordinate, the sine.','$(-1, 0)$ is a half turn, $180^\\circ$.'],
    steps:['$90^\\circ$ counterclockwise from $(1, 0)$ reaches $(0, 1)$.','$\\cos 90^\\circ$ is the $x$-coordinate, $0$.']},
   {stem:'A student says $\\sin 90^\\circ$ cannot be found, because a right triangle cannot have a second $90^\\circ$ angle. What does the unit circle definition give?',choices:['It is undefined','$0$, the $x$-coordinate of $(0, 1)$','$1$, the $y$-coordinate of $(0, 1)$','$90$, the angle itself'],key:2,
    miss:['triangle_only','swap_sin_cos',null,'angle_as_value'],
    why:['The unit circle definition works for every angle, including $90^\\circ$.','The $x$-coordinate gives cosine, not sine.','Correct. Sine is the $y$-coordinate, and the point for $90^\\circ$ is $(0, 1)$.','Sine of an angle is a coordinate between $-1$ and $1$, not the angle.'],
    steps:['The terminal side of $90^\\circ$ meets the circle at $(0, 1)$.','$\\sin 90^\\circ = 1$.']},
  ]}),
 lessonQuiz({lesson:'angles-of-elevation-and-depression',video:'TgQs7k5p2Ag',reviewed:'2026-10-08',concept:'trigonometry',
  keyIdea:'Angles of elevation and depression are measured from the horizontal line of sight, up or down; draw the right triangle they make and use the ratio that links the side you know to the side you want.',
  watchFor:[{at:64,text:'The head tilts up from looking straight ahead. Note what angle is being measured.'},{at:312,text:'A name is given to that upward angle.'},{at:413,text:'Now the view looks down from the rooftop. Predict the name of this angle.'}],
  practice:{url:'https://www.khanacademy.org/math/9th-grade-math-revised-k-to-10-3-terms/x1e64c39423990571:3rd-quarter/x1e64c39423990571:trigonometric-ratios/e/applying-right-triangles',label:'Right triangle trigonometry word problems',checked:'2026-10-08'},
  items:[
   {stem:'From where is an angle of elevation measured?',choices:['From the horizontal line of sight, up to the object','From the vertical, down to the object','From the ground directly below the object','From the object back to the observer’s feet'],key:0,
    miss:[null,'vertical_reference','base_reference','wrong_endpoints'],
    why:['Correct. Start looking straight ahead, then tilt up until you see the object.','Both elevation and depression start from the horizontal, not the vertical.','The angle is at the observer’s eye, not under the object.','The angle is measured at the observer, from the horizontal.'],
    steps:['Line of sight straight ahead: horizontal.','Tilt up to the object: the angle turned is the angle of elevation.']},
   {stem:'Looking down from a rooftop at an angle of depression of $60^\\circ$, why is the angle at the person on the ground also $60^\\circ$?',choices:['Because every angle in the triangle is $60^\\circ$','Because the building makes a $60^\\circ$ angle with the ground','The horizontal at the rooftop and the ground are parallel, and the line of sight crosses both, so the alternate angles are equal','Because depression and elevation always add to $90^\\circ$'],key:2,
    miss:['equilateral_assumed','building_angle',null,'complement_rule'],
    why:['The triangle has a right angle at the building’s base, so not all angles are $60^\\circ$.','The building meets the ground at $90^\\circ$.','Correct. Parallel lines cut by a transversal give equal alternate angles.','They are equal here, not complementary.'],
    steps:['The rooftop horizontal is parallel to the ground.','The line of sight is a transversal, so the angle at the ground equals the angle of depression.']},
   {stem:'You stand $50$ m from the base of a tower and see its top at an angle of elevation of $45^\\circ$. How far is it in a straight line from you to the top?',choices:['$50$ m','$25\\sqrt{2}$ m','$100$ m','$50\\sqrt{2}$ m'],key:3,
    miss:['tan_gives_height','multiplied_by_cos','doubled_distance',null],
    why:['$50$ m is the height of the tower (from tangent), not the slanted distance.','This multiplies by $\\cos 45^\\circ$ instead of dividing.','Doubling is not a trigonometric step.','Correct. $\\cos 45^\\circ = \\frac{50}{d}$, so $d = \\frac{50}{\\frac{1}{\\sqrt{2}}} = 50\\sqrt{2}$.'],
    steps:['Adjacent: $50$ m. Hypotenuse: $d$.','$\\cos 45^\\circ = \\frac{1}{\\sqrt{2}} = \\frac{50}{d}$.','$d = 50\\sqrt{2}$ m, about $70.7$ m.']},
   {stem:'From a rooftop $30$ m high, the angle of depression to a car is $30^\\circ$. A student marks the $30^\\circ$ between the building’s wall and the line of sight. What is wrong?',choices:['Nothing; depression is measured from the wall','The angle of depression is measured from the horizontal, so the angle between the wall and the line of sight is $60^\\circ$','The angle of depression should be measured at the car','The height of $30$ m should be the hypotenuse'],key:1,
    miss:['vertical_reference',null,'wrong_endpoints','height_as_hypotenuse'],
    why:['The wall is vertical; depression starts from the horizontal.','Correct. Horizontal and vertical are $90^\\circ$ apart, so $90^\\circ - 30^\\circ = 60^\\circ$.','It is measured at the observer on the roof (it equals the elevation from the car).','The slanted line of sight is the hypotenuse.'],
    steps:['Depression: from the horizontal down to the car, $30^\\circ$.','The wall is perpendicular to the horizontal, so wall to line of sight is $60^\\circ$.']},
  ]}),
 lessonQuiz({lesson:'trigonometric-identities',video:'a70-dYvDJZY',reviewed:'2026-10-08',concept:'trigonometry',
  keyIdea:'From $\\sin(a + b) = \\sin a \\cos b + \\sin b \\cos a$ and $\\cos(a + b) = \\cos a \\cos b - \\sin a \\sin b$, setting $b = a$ gives double-angle identities such as $\\sin 2a = 2\\sin a \\cos a$ and $\\cos 2a = \\cos^2 a - \\sin^2 a$.',
  watchFor:[{at:25,text:'The starting identities are stated. Note the sign in each one.'},{at:226,text:'The cosine of a doubled angle is built from a sum formula.'},{at:582,text:'The sine of a doubled angle is found the same way.'}],
  practice:{url:'https://www.khanacademy.org/math/precalculus/x9e81a4f98389efdf:trig/x9e81a4f98389efdf:angle-addition/e/trig_addition_identities',label:'Use the trig angle addition identities',checked:'2026-10-08'},
  items:[
   {stem:'Which expression equals $\\cos(a + b)$?',choices:['$\\cos a \\cos b + \\sin a \\sin b$','$\\sin a \\cos b + \\sin b \\cos a$','$\\cos a + \\cos b$','$\\cos a \\cos b - \\sin a \\sin b$'],key:3,
    miss:['sign_swap','sine_formula','distribute_cos',null],
    why:['A plus inside gives a minus here; the plus belongs to $\\cos(a - b)$.','That is the formula for $\\sin(a + b)$.','Cosine does not distribute over a sum.','Correct. For a sum, the cosine identity has a minus sign.'],
    steps:['$\\cos(a + b) = \\cos a \\cos b - \\sin a \\sin b$.']},
   {stem:'Why is $\\cos 2a = \\cos^2 a - \\sin^2 a$?',choices:['Because $\\cos 2a = 2\\cos a$','Write $2a$ as $a + a$ and use the cosine sum identity with $b = a$','Because cosine is an even function','Because $\\sin^2 a + \\cos^2 a = 1$ gives it directly'],key:1,
    miss:['double_outside',null,'even_function_misuse','pythagorean_only'],
    why:['Doubling the angle does not double the cosine.','Correct. $\\cos(a + a) = \\cos a \\cos a - \\sin a \\sin a$.','Being even explains $\\cos(-c) = \\cos c$, not the double angle.','That identity rewrites the result in other forms, but the sum formula produces it.'],
    steps:['$\\cos 2a = \\cos(a + a)$.','$= \\cos a \\cos a - \\sin a \\sin a = \\cos^2 a - \\sin^2 a$.']},
   {stem:'If $\\sin a = \\frac{3}{5}$ and $\\cos a = \\frac{4}{5}$, what is $\\sin 2a$?',choices:['$\\frac{24}{25}$','$\\frac{6}{5}$','$\\frac{7}{25}$','$\\frac{12}{25}$'],key:0,
    miss:[null,'double_outside','used_cos_double','forgot_two'],
    why:['Correct. $2 \\times \\frac{3}{5} \\times \\frac{4}{5} = \\frac{24}{25}$.','Doubling $\\sin a$ does not give $\\sin 2a$; a sine is never more than $1$.','$\\frac{16}{25} - \\frac{9}{25} = \\frac{7}{25}$ is $\\cos 2a$.','The identity has a factor of $2$: $2\\sin a \\cos a$.'],
    steps:['$\\sin 2a = 2\\sin a \\cos a$.','$= 2 \\times \\frac{3}{5} \\times \\frac{4}{5} = \\frac{24}{25}$.']},
   {stem:'A student writes $\\sin(a - c) = \\sin a \\cos c + \\sin c \\cos a$, the same as for $a + c$. What is correct?',choices:['The student’s version is correct','$\\sin a - \\sin c$','$\\sin a \\cos c - \\sin c \\cos a$, because $\\sin(-c) = -\\sin c$ while $\\cos(-c) = \\cos c$','$\\sin a \\cos c - \\sin c \\cos a$, because cosine is an odd function'],key:2,
    miss:['sign_ignored','distribute_sin',null,'odd_even_swap'],
    why:['Replacing $c$ with $-c$ changes the sign of the sine term.','Sine does not distribute over a difference.','Correct. Sine is odd and cosine is even.','The formula is right, but the reason is wrong: cosine is even and sine is odd.'],
    steps:['$\\sin(a + (-c)) = \\sin a \\cos(-c) + \\sin(-c) \\cos a$.','$= \\sin a \\cos c - \\sin c \\cos a$.']},
  ]}),
 lessonQuiz({lesson:'laws-of-sines-and-cosines',video:'APNkWrD-U1k',reviewed:'2026-10-08',concept:'trigonometry',
  keyIdea:'Dropping an altitude $x$ gives $x = A\\sin\\beta$ and $x = B\\sin\\alpha$, so $\\frac{\\sin\\alpha}{A} = \\frac{\\sin\\beta}{B}$: each angle’s sine over the length of its opposite side is the same throughout the triangle.',
  watchFor:[{at:66,text:'An altitude is drawn. Notice the two right triangles it makes.'},{at:130,text:'The altitude is written using one angle and one side.'},{at:282,text:'Two expressions for the same altitude are set equal.'}],
  practice:{url:'https://www.khanacademy.org/math/10th-grade-math-revised-k-to-10-3-terms/x06a77af3c81397cf:unit-1/x06a77af3c81397cf:laws-of-sines-and-its-ambiguous-cases/e/law_of_sines',label:'Solve triangles using the law of sines',checked:'2026-10-08'},
  items:[
   {stem:'A triangle has angles $\\alpha$ and $\\beta$ opposite sides of length $A$ and $B$. Which statement is the law of sines?',choices:['$\\frac{\\sin\\alpha}{B} = \\frac{\\sin\\beta}{A}$','$\\frac{\\sin\\alpha}{A} = \\frac{\\sin\\beta}{B}$','$A\\sin\\alpha = B\\sin\\beta$','$\\frac{\\alpha}{A} = \\frac{\\beta}{B}$'],key:1,
    miss:['adjacent_pairing',null,'cross_wrong','angles_not_sines'],
    why:['Each sine must be paired with the side opposite its own angle.','Correct. The ratio of a sine to its opposite side is the same for every angle.','Cross-multiplying the law gives $A\\sin\\beta = B\\sin\\alpha$, not this.','The law uses the sines of the angles, not the angles.'],
    steps:['$\\frac{\\sin\\alpha}{A} = \\frac{\\sin\\beta}{B}$, which can also be written $\\frac{A}{\\sin\\alpha} = \\frac{B}{\\sin\\beta}$.']},
   {stem:'In the proof, why can the altitude $x$ be written both as $A\\sin\\beta$ and as $B\\sin\\alpha$?',choices:['It is opposite $\\beta$ in one right triangle with hypotenuse $A$, and opposite $\\alpha$ in the other right triangle with hypotenuse $B$','Because $A$ and $B$ are always equal','Because the altitude cuts the opposite side in half','Because sine is adjacent over hypotenuse'],key:0,
    miss:[null,'equal_sides','bisector_confusion','sine_as_cosine'],
    why:['Correct. Each small right triangle gives $\\sin = \\frac{\\text{opposite}}{\\text{hypotenuse}}$ with $x$ as the opposite side.','The triangle can be any shape; $A$ and $B$ need not match.','An altitude is perpendicular; it need not bisect the side.','Sine is opposite over hypotenuse.'],
    steps:['$\\sin\\beta = \\frac{x}{A}$, so $x = A\\sin\\beta$.','$\\sin\\alpha = \\frac{x}{B}$, so $x = B\\sin\\alpha$.']},
   {stem:'In a triangle, angle $\\alpha = 30^\\circ$ is opposite a side of length $8$, and angle $\\beta = 90^\\circ$. How long is the side opposite $\\beta$?',choices:['$4$','$8$','$16$','$24$'],key:2,
    miss:['inverted_ratio','equal_sides',null,'angles_not_sines'],
    why:['This divides where it should multiply; the side opposite the larger angle must be longer.','Different opposite angles give different side lengths.','Correct. $\\frac{\\sin 30^\\circ}{8} = \\frac{\\sin 90^\\circ}{B}$, so $\\frac{0.5}{8} = \\frac{1}{B}$ and $B = 16$.','This scales by the angles, $\\frac{90}{30} \\times 8$, instead of their sines.'],
    steps:['$\\frac{\\sin 30^\\circ}{8} = \\frac{\\sin 90^\\circ}{B}$.','$\\frac{0.5}{8} = \\frac{1}{B}$, so $B = \\frac{8}{0.5} = 16$.']},
   {stem:'Using the law of sines, a student pairs each angle with a side that forms it instead of the side opposite it. Why does this give wrong answers?',choices:['It does not matter which sides are used','Opposite sides are needed only in right triangles','The law uses the angles themselves, so the pairing cannot matter','The law pairs each angle’s sine with the side opposite that angle; other pairings do not share one common ratio'],key:3,
    miss:['any_pairing','right_only','angles_not_sines',null],
    why:['The pairing is the whole content of the law.','The law of sines works in every triangle, with opposite sides.','The law uses sines, and the pairing still matters.','Correct. In the proof, each side is the hypotenuse for the angle across from the other side, which forces the opposite pairing.'],
    steps:['Match each angle with the side across from it.','Then $\\frac{\\sin\\alpha}{A} = \\frac{\\sin\\beta}{B}$ holds.']},
  ]}),
];
