import {lessonQuiz} from './author.ts';
import {VERIFIED_CLIPS} from '../../lib/video-clips.ts';

/** UPCAT Mathematics: Arithmetic and number sense. Original draft items written from
 * Khan's timestamped caption transcripts, read 2026-10-08; pending subject review.
 * Receipts: docs/THIRD_PARTY_MATERIALS.md, "Lesson quiz caption reviews". */
export const MATH_NUMBER=[
 lessonQuiz({lesson:'the-real-number-system',video:'cLP7INqs3JM',reviewed:'2026-10-08',concept:'real_numbers',chapter:'m_fractions_percent',
  keyIdea:'A number is rational when it can be written as a ratio of two integers, which covers integers, terminating decimals and repeating decimals; numbers such as $\\pi$ and $\\sqrt{2}$ never end or repeat, so they are irrational.',
  watchFor:[{at:20,text:'One integer is written as a ratio in several different ways. Notice what every version has in common.'},{at:140,text:'An endless decimal appears. Listen for why it still counts as a ratio of two integers.'},{at:227,text:'The video turns to numbers that cannot be written as a ratio. Note the examples and what their decimals do.'}],
  practice:{url:'https://www.khanacademy.org/math/7th-grade-matatag/x065dcf1640354e81:1st-quarter/x065dcf1640354e81:rational-numbers/e/writing-fractions-as-repeating-decimals',label:'Writing fractions as repeating decimals',checked:'2026-10-08'},
  items:[
   {stem:'Which description defines a rational number?',choices:['Any number written with a decimal point','Any number that has only finitely many digits','Any number that can be written as a ratio of two integers','Any number that is greater than zero'],key:2,
    miss:['decimal_means_not_whole',"finite_digits_only",null,'positive_only'],
    why:['Decimals can be rational or irrational. $3.75$ is rational, but the decimal for $\\pi$ is not.','Repeating decimals have endless digits and are still rational: $0.333\\ldots$ is $\\frac{1}{3}$.','Correct. A rational number is any number that can be written as one integer divided by another (nonzero) integer.','Negative numbers can be rational too: $-7$ is $\\frac{-7}{1}$.'],
    steps:['A rational number can be written as $\\frac{a}{b}$ where $a$ and $b$ are integers and $b \\ne 0$.','Integers, terminating decimals and repeating decimals all fit this description.']},
   {stem:'Why is $0.333\\ldots$, with the $3$ repeating forever, a rational number even though its digits never end?',choices:['Because its repeating pattern means it equals $\\frac{1}{3}$, a ratio of two integers','Because every decimal is rational','Because it can be rounded to $0.33$','It is not rational, because its digits never end'],key:0,
    miss:[null,'all_decimals_rational','rounding_makes_rational','endless_means_irrational'],
    why:['Correct. A decimal whose digits repeat in a pattern can always be rewritten as a ratio of two integers; this one is $\\frac{1}{3}$.','Not every decimal is rational. The decimal for $\\sqrt{2}$ never ends and never repeats, so it is irrational.','Rounding changes the number. $0.33$ is a different number from $0.333\\ldots$; the reason must apply to the exact value.','Endless digits alone do not make a number irrational. Irrational decimals never end and also never repeat.'],
    steps:['Irrational means the decimal never ends and never repeats.','$0.333\\ldots$ repeats, and it equals $\\frac{1}{3}$, so it is rational.']},
   {stem:'Which of these numbers is irrational?',choices:['$\\sqrt{49}$','$-\\frac{18}{6}$','$2.125$','$\\sqrt{10}$'],key:3,
    miss:['every_root_irrational','negative_fraction_irrational','terminating_decimal_irrational',null],
    why:['$49$ is a perfect square, so $\\sqrt{49} = 7$, an integer and therefore rational.','$-\\frac{18}{6} = -3$, an integer. A negative ratio of integers is still rational.','$2.125$ terminates, so it equals $\\frac{2125}{1000}$ and is rational.','Correct. $10$ is not a perfect square, so $\\sqrt{10}$ never ends and never repeats.'],
    steps:['Check each number: can it be written as a ratio of two integers?','$\\sqrt{49} = 7$, $-\\frac{18}{6} = -3$ and $2.125 = \\frac{2125}{1000}$ are rational.','$10$ is not a perfect square, so $\\sqrt{10}$ is irrational.']},
   {stem:'A classmate says $\\frac{22}{7}$ is irrational because it is close to $\\pi$. What is wrong with this reasoning?',choices:['Nothing; any number close to $\\pi$ is irrational','$\\frac{22}{7}$ is a ratio of two integers, so it is rational; it is only an approximation of $\\pi$','$\\frac{22}{7}$ is irrational only because $7$ is a prime number','$\\frac{22}{7}$ is an integer, so it cannot be compared with $\\pi$'],key:1,
    miss:['closeness_decides_type',null,'prime_denominator_irrational','improper_fraction_integer'],
    why:['Being close to an irrational number does not change a number’s type. $\\frac{22}{7}$ is written as a ratio of integers.','Correct. $\\frac{22}{7}$ fits the definition of rational exactly. Its decimal repeats, while the decimal for $\\pi$ never repeats.','Primes in the denominator do not matter. Any integer over a nonzero integer is rational.','$\\frac{22}{7}$ is about $3.14$, so it is not an integer; it is still a ratio of integers.'],
    steps:['Apply the definition: $22$ and $7$ are integers, so $\\frac{22}{7}$ is rational.','It is an approximation of $\\pi$; $\\pi$ itself never ends and never repeats.']},
  ]}),
 lessonQuiz({lesson:'integers-and-the-order-of-operations',video:'ClYdw4d4OmA',reviewed:'2026-10-08',concept:'order_of_operations',chapter:'m_fractions_percent',
  keyIdea:'Everyone agrees to do parentheses, then exponents, then multiplication and division from left to right, then addition and subtraction from left to right, so each expression has exactly one value.',
  watchFor:[{at:25,text:'One short expression is read in two different ways. Notice why two answers is a problem.'},{at:126,text:'The agreed order is written out. Note which operations share the same level.'},{at:458,text:'Several operations of the same level appear in a row. Watch which direction the work goes.'}],
  segment:VERIFIED_CLIPS.ClYdw4d4OmA,
  practice:{url:'https://www.khanacademy.org/math/7th-grade-matatag/x065dcf1640354e81:3rd-quarter/x065dcf1640354e81:order-of-operations/e/order_of_operations',label:'Order of operations with negative numbers',checked:'2026-10-08'},
  prediction:{stem:'Before watching: what is the value of $7 + 3 \\times 5$?',choices:['$50$','$22$','$15$','$105$'],key:1,
   miss:['strict_left_to_right',null,'added_all_terms','multiplied_all_terms'],
   why:['Working left to right gives $10 \\times 5 = 50$, but multiplication comes before addition.','Multiplication first: $3 \\times 5 = 15$, then $7 + 15 = 22$.','Adding every number, $7 + 3 + 5 = 15$, ignores the multiplication sign.','Multiplying every number ignores the addition sign.'],
   steps:['The video settles this example: multiplication comes before addition, so $3 \\times 5 = 15$ and $7 + 15 = 22$.']},
  items:[
   {stem:'In the agreed order of operations, how are multiplication and division ranked?',choices:['Multiplication is always done before division','They are done after addition and subtraction','Division is always done before multiplication','They share one level and are done from left to right'],key:3,
    miss:['multiply_before_divide','add_before_multiply','divide_before_multiply',null],
    why:['Multiplication does not outrank division. In $16 \\div 4 \\times 2$, the division comes first because it is further left.','Multiplication and division come before addition and subtraction.','Division does not outrank multiplication either; position decides.','Correct. Multiplication and division share a level, so work left to right through them.'],
    steps:['Order: parentheses, exponents, then multiplication and division (left to right), then addition and subtraction (left to right).']},
   {stem:'Why does mathematics need an agreed order of operations?',choices:['So answers always come out as whole numbers','So an expression such as $7 + 3 \\times 5$ has only one value, whoever evaluates it','Because working from left to right is always wrong','Because calculators cannot add before they multiply'],key:1,
    miss:['order_for_whole_numbers',null,'left_to_right_always_wrong','calculator_rule'],
    why:['The order says nothing about whole numbers; $8 \\div 3$ is still $\\frac{8}{3}$.','Correct. Without an agreed order, the same expression could give $50$ or $22$; agreement removes the ambiguity.','Left to right is exactly what you do within one level, such as a run of additions and subtractions.','The rule comes from people agreeing on one reading. Calculators are programmed to follow it, not the other way round.'],
    steps:['Read left to right, $7 + 3 \\times 5$ gives $50$; multiplying first gives $22$.','An agreed order means everyone gets $22$.']},
   {stem:'Evaluate $20 - 12 \\div 4 \\times 2$.',choices:['$14$','$18.5$','$4$','$1$'],key:0,
    miss:[null,'multiply_before_divide','strict_left_to_right','subtract_then_multiply_first'],
    why:['Correct. $12 \\div 4 = 3$, then $3 \\times 2 = 6$, then $20 - 6 = 14$.','This multiplies $4 \\times 2$ before dividing: $12 \\div 8 = 1.5$. Division and multiplication share a level, so go left to right.','This works straight left to right from the subtraction: $20 - 12 = 8$, $8 \\div 4 = 2$, $2 \\times 2 = 4$. Subtraction must wait.','This subtracts first and then multiplies before dividing: $8 \\div 8 = 1$.'],
    steps:['No parentheses or exponents.','Multiplication and division, left to right: $12 \\div 4 = 3$, then $3 \\times 2 = 6$.','Subtraction: $20 - 6 = 14$.']},
   {stem:'Someone evaluates $16 \\div 4 \\times 2$ by computing $4 \\times 2 = 8$ first, then $16 \\div 8 = 2$. Which statement is correct?',choices:['Nothing went wrong; the value is $2$','The expression has no single value, so either answer is fine','Multiplication and division share a level, so work left to right: the value is $8$','Work right to left whenever division appears, so the value is $2$'],key:2,
    miss:['multiply_before_divide','no_agreed_order',null,'right_to_left'],
    why:['Multiplication does not come before division. Doing it first changes the answer.','The whole point of the agreed order is that every expression has one value.','Correct. $16 \\div 4 = 4$, then $4 \\times 2 = 8$.','There is no right-to-left rule. Within one level, always go left to right.'],
    steps:['$\\div$ and $\\times$ are on the same level, so go left to right.','$16 \\div 4 = 4$, then $4 \\times 2 = 8$.']},
  ]}),
 lessonQuiz({lesson:'fractions-and-decimals',video:'zkJ1gOrYhEg',reviewed:'2026-10-08',
  keyIdea:'To add halves and thirds, rewrite both in pieces of the same size, such as sixths, by multiplying the top and bottom of each fraction by the same number; then add the numbers of pieces.',
  watchFor:[{at:37,text:'Notice why halves and thirds cannot simply be added as they are.'},{at:90,text:'Watch what must happen to the numerator when the denominator is multiplied, and why the bar model agrees.'},{at:206,text:'Once both fractions use the same pieces, see how the pieces are counted.'}],
  practice:{url:'https://www.khanacademy.org/math/6th-grade-math-foundations/x7f9e1f592eb7eeaf:cd2-numbers-and-algebra/x7f9e1f592eb7eeaf:addition-and-subtraction-of-dissimilar-fractions/e/adding_fractions',label:'Add fractions with unlike denominators',checked:'2026-10-08'},
  items:[
   {stem:'To add $\\frac{1}{2}$ and $\\frac{1}{3}$, which common denominator does the video use, and why?',choices:['$5$, the sum of $2$ and $3$','$3$, the larger denominator','$1$, because both are parts of one whole','$6$, the least common multiple of $2$ and $3$'],key:3,
    miss:['add_denominators','pick_larger_denominator','whole_as_denominator',null],
    why:['Adding denominators does not make pieces of a shared size. Halves cannot be cut evenly into fifths.','Halves cannot be written as a whole number of thirds, so $3$ does not work.','A denominator of $1$ counts wholes, not the halves and thirds being added.','Correct. Both halves and thirds can be cut evenly into sixths, and $6$ is the smallest number that works.'],
    steps:['A common denominator must be a multiple of both $2$ and $3$.','The least common multiple is $6$.']},
   {stem:'When $\\frac{1}{2}$ is rewritten in sixths, what happens, and why does its value stay the same?',choices:['Only the bottom is multiplied by $3$, giving $\\frac{1}{6}$, the same amount','Top and bottom are both multiplied by $3$, which splits each half into $3$ sixths without changing the amount shaded','Both are multiplied by $3$, which makes the fraction three times as large','Only the top is multiplied by $3$, giving $\\frac{3}{2}$'],key:1,
    miss:['denominator_only',null,'scaling_changes_value','numerator_only'],
    why:['$\\frac{1}{6}$ is much smaller than $\\frac{1}{2}$. Cutting pieces smaller means you need more of them.','Correct. Three times as many pieces, each a third of the size, cover exactly the same amount: $\\frac{1}{2} = \\frac{3}{6}$.','Multiplying top and bottom by the same number is multiplying by $\\frac{3}{3} = 1$, so the value does not change.','$\\frac{3}{2}$ is three times as large as $\\frac{1}{2}$. The denominator must change too.'],
    steps:['Multiply top and bottom by $3$: $\\frac{1 \\times 3}{2 \\times 3} = \\frac{3}{6}$.','This multiplies by $\\frac{3}{3} = 1$, so the amount is unchanged.']},
   {stem:'What is $\\frac{2}{5} + \\frac{1}{4}$?',choices:['$\\frac{3}{9}$','$\\frac{3}{20}$','$\\frac{13}{20}$','$\\frac{9}{20}$'],key:2,
    miss:['add_across','denominator_only',null,'rescale_one_fraction'],
    why:['Adding tops and bottoms gives $\\frac{3}{9}$, which is even less than $\\frac{2}{5}$ alone.','This changes both denominators to $20$ but leaves the numerators as $2$ and $1$.','Correct. $\\frac{2}{5} = \\frac{8}{20}$ and $\\frac{1}{4} = \\frac{5}{20}$, so the sum is $\\frac{13}{20}$.','This rescales $\\frac{2}{5}$ to $\\frac{8}{20}$ but adds $1$ instead of $5$ for the second fraction.'],
    steps:['The least common multiple of $5$ and $4$ is $20$.','$\\frac{2}{5} = \\frac{8}{20}$ and $\\frac{1}{4} = \\frac{5}{20}$.','$\\frac{8}{20} + \\frac{5}{20} = \\frac{13}{20}$.']},
   {stem:'A student writes $\\frac{1}{2} + \\frac{1}{3} = \\frac{2}{5}$. Which quick check shows this must be wrong?',choices:['$\\frac{2}{5}$ is less than $\\frac{1}{2}$, but adding a positive amount to $\\frac{1}{2}$ must give more than $\\frac{1}{2}$','$\\frac{2}{5}$ cannot be simplified','The answer must use the larger denominator, $3$','The numerators should be multiplied, not added'],key:0,
    miss:[null,'simplification_check','pick_larger_denominator','multiply_numerators'],
    why:['Correct. The sum must be bigger than either part, and $\\frac{2}{5}$ is smaller than $\\frac{1}{2}$.','Whether a fraction simplifies says nothing about whether a sum is right.','Halves cannot be written in thirds, so $3$ cannot be the common denominator here.','Multiplying numerators is part of multiplying fractions, not adding them.'],
    steps:['Estimate: $\\frac{1}{2} + \\frac{1}{3}$ must be more than $\\frac{1}{2}$.','$\\frac{2}{5}$ is less than $\\frac{1}{2}$, so it cannot be the sum. The correct sum is $\\frac{5}{6}$.']},
  ]}),
 lessonQuiz({lesson:'percent',video:'TvSKeTFsaj4',reviewed:'2026-10-08',
  keyIdea:'Translate “$150$ is $25\\%$ of what number?” into $0.25x = 150$ and solve for the base; the amount equals the percent times the base.',
  watchFor:[{at:44,text:'The question in words is turned into an equation. Notice what the unknown stands for.'},{at:127,text:'Two ways to undo the multiplication are offered. Watch for the shortcut.'},{at:314,text:'The video names the percent, the amount and the base. Match each name to its number.'}],
  practice:{url:'https://www.khanacademy.org/math/7th-grade-foundations-matatag/x1e2e8b1648d78e6f:numbers-algebra/x1e2e8b1648d78e6f:percentage-rate-and-percent/e/percentage_word_problems_1',label:'Percent word problems',checked:'2026-10-08'},
  items:[
   {stem:'In the question “$150$ is $25\\%$ of what number?”, which number is the base?',choices:['The unknown number, which turns out to be $600$','$150$','$25$','$0.25$'],key:0,
    miss:[null,'swap_base_amount','percent_as_base','decimal_percent_as_base'],
    why:['Correct. The base is the number you take the percent of, here the unknown, which is $600$.','$150$ is the amount: the part that $25\\%$ of the base represents.','$25$ is the percent itself, not the base.','$0.25$ is the percent written as a decimal.'],
    steps:['$\\text{amount} = \\text{percent} \\times \\text{base}$.','Here the amount is $150$, the percent is $25\\%$, and the base is the unknown, $600$.']},
   {stem:'Why does it make sense that the answer to “$150$ is $25\\%$ of what number?” is larger than $150$?',choices:['Percent questions always have answers larger than the numbers given','Because you add $25$ to $150$','$25\\%$ is one quarter, so $150$ is only a quarter of the number, which must be four times as big','Dividing by any number makes the result larger'],key:2,
    miss:['always_larger','percent_as_number',null,'division_always_larger'],
    why:['Not so: $25\\%$ of $600$ is $150$, which is smaller than $600$. It depends on what is unknown.','A percent is a fraction of something, never a number to add on.','Correct. If $150$ is a quarter of the number, the number is $4 \\times 150 = 600$.','Dividing by a number greater than $1$ makes a result smaller; dividing by $0.25$ makes it larger.'],
    steps:['$25\\% = \\frac{1}{4}$.','If $150$ is a quarter of the number, the number is $4 \\times 150 = 600$.']},
   {stem:'$84$ is $35\\%$ of what number?',choices:['$29.4$','$240$','$119$','$2.4$'],key:1,
    miss:['took_percent_of_amount',null,'percent_as_number','forgot_hundred'],
    why:['$84 \\times 0.35 = 29.4$ finds $35\\%$ of $84$, the reverse question.','Correct. $0.35x = 84$, so $x = 84 \\div 0.35 = 240$.','Adding $84 + 35$ treats the percent as a plain number.','$84 \\div 35 = 2.4$ forgets that $35\\%$ means $\\frac{35}{100}$.'],
    steps:['Write the equation: $0.35x = 84$.','Divide both sides by $0.35$: $x = 240$.','Check: $35\\%$ of $240$ is $84$.']},
   {stem:'Which equation correctly represents “$18$ is $40\\%$ of a number $n$”?',choices:['$n = 0.40 \\times 18$','$40n = 18$','$18 + 0.40 = n$','$0.40n = 18$'],key:3,
    miss:['swap_base_amount','forgot_hundred','percent_as_number',null],
    why:['This takes $40\\%$ of $18$, but $18$ is the amount, not the base.','$40\\%$ is $0.40$, not $40$.','A percent multiplies the base; it is never added to the amount.','Correct. The amount, $18$, equals $40\\%$ of the base: $0.40n = 18$.'],
    steps:['$\\text{amount} = \\text{percent} \\times \\text{base}$.','$18 = 0.40n$, so $n = 45$.']},
  ]}),
 lessonQuiz({lesson:'ratio-and-proportion',video:'ZJ6y8OVJRw8',reviewed:'2026-10-08',
  keyIdea:'When two parts are in the ratio $2 : 3$, each group has $2 + 3 = 5$ parts in all, so scale the whole to the actual total and multiply every part by the same factor.',
  watchFor:[{at:44,text:'A table is set up with a row for each part and one for the total. Notice the two columns.'},{at:83,text:'Watch how a part-to-whole ratio is found from the part-to-part ratio.'},{at:111,text:'See which known total gives the scale factor, and how it is applied to every row.'}],
  practice:{url:'https://www.khanacademy.org/math/6th-grade-matatag/xb8e22b8c4894c878:2nd-quarter/xb8e22b8c4894c878:ratio-and-proportion/e/part-part-whole-ratios',label:'Part-part-whole ratios',checked:'2026-10-08'},
  items:[
   {stem:'If indoor and outdoor play times are in the ratio $2 : 3$, what is the ratio of indoor play times to all play times?',choices:['$2 : 3$','$3 : 5$','$2 : 5$','$2 : 6$'],key:2,
    miss:['part_as_whole','wrong_part',null,'multiplied_parts'],
    why:['$2 : 3$ compares indoor with outdoor, not with the total.','$3 : 5$ is outdoor to total.','Correct. For every $2$ indoor and $3$ outdoor there are $5$ in all, so indoor to total is $2 : 5$.','The total is found by adding the parts, $2 + 3$, not multiplying them.'],
    steps:['Total parts: $2 + 3 = 5$.','Indoor to total: $2 : 5$.']},
   {stem:'Indoor and outdoor play times are in the ratio $2 : 3$, and there are $30$ play times in all. Why is every row of the ratio table multiplied by the same factor, $6$?',choices:['So that indoor and outdoor become equal','Because $6$ is $2 \\times 3$, the product of the ratio terms','Because adding the same number to each part keeps the ratio','Multiplying every part by the same factor keeps the ratio between them unchanged'],key:3,
    miss:['equal_parts','product_of_terms','additive_scaling',null],
    why:['The counts stay unequal: $12$ indoor and $18$ outdoor.','The factor comes from the totals: $30 \\div 5 = 6$. That it equals $2 \\times 3$ here is a coincidence.','Adding the same amount changes a ratio: $2 + 6 : 3 + 6$ is $8 : 9$, not $2 : 3$.','Correct. $12 : 18$ and $12 : 30$ simplify back to $2 : 3$ and $2 : 5$.'],
    steps:['Scale factor: actual total $\\div$ ratio total $= 30 \\div 5 = 6$.','Multiply each part by $6$: $2 \\times 6 = 12$ and $3 \\times 6 = 18$.']},
   {stem:'A fruit stand sells mangoes and bananas in the ratio $4 : 5$. It sells $54$ fruits in all. How many are mangoes?',choices:['$24$','$30$','$43.2$','$27$'],key:0,
    miss:[null,'wrong_part','part_as_whole','equal_parts'],
    why:['Correct. There are $4 + 5 = 9$ parts, so each part is $54 \\div 9 = 6$ fruits and mangoes are $4 \\times 6 = 24$.','$30$ is the number of bananas, $5 \\times 6$.','This treats $\\frac{4}{5}$ as the share of the total, but the total has $9$ parts, not $5$.','Splitting the fruits evenly ignores the ratio.'],
    steps:['Total parts: $4 + 5 = 9$.','Scale factor: $54 \\div 9 = 6$.','Mangoes: $4 \\times 6 = 24$.']},
   {stem:'In a class, boys and girls are in the ratio $3 : 4$, and there are $35$ students. A student answers “$3$ boys”. What is the mistake?',choices:['There is no mistake; the ratio gives the count directly','They used a ratio term as the actual count; $35 \\div 7 = 5$, so there are $15$ boys','There are $20$ boys, because boys take the larger share','They should have divided $35$ by $3$'],key:1,
    miss:['ratio_as_count',null,'wrong_part','divide_by_part'],
    why:['A ratio compares sizes. With $35$ students, $3$ boys and $4$ girls would only make $7$.','Correct. Each part is $35 \\div 7 = 5$ students, so boys are $3 \\times 5 = 15$.','Girls have the larger share here: $4$ parts out of $7$.','The total is shared into $3 + 4 = 7$ parts, not $3$.'],
    steps:['Total parts: $3 + 4 = 7$.','Each part: $35 \\div 7 = 5$.','Boys: $3 \\times 5 = 15$.']},
  ]}),
];
