import {lessonQuiz} from './author.ts';

/** UPCAT Mathematics: Statistics and probability. Original draft items written from
 * Khan's timestamped caption transcripts, read 2026-10-08; pending subject review.
 * Receipts: docs/THIRD_PARTY_MATERIALS.md, "Lesson quiz caption reviews". */
export const MATH_STATISTICS=[
 lessonQuiz({lesson:'mean-median-and-mode',video:'h8EYEJ32oQ8',reviewed:'2026-10-08',
  keyIdea:'Mean, median and mode each describe a data set with one typical value: the mean shares the total equally, the median is the middle of the ordered values, and the mode is the most common value.',
  watchFor:[{at:129,text:'Listen for what “average” means in statistics, beyond its everyday use.'},{at:314,text:'Before the middle value is found, notice what is done to the list.'},{at:440,text:'The least used measure is introduced. Note when a data set has none.'}],
  practice:{url:'https://www.khanacademy.org/math/pisa-2025-math-supplement/x092b0b93d51c9e96:uncertainty-and-data/x092b0b93d51c9e96:data-variability/e/mean_median_and_mode',label:'Mean, median, and mode',checked:'2026-10-08'},
  items:[
   {stem:'What is the median of a data set?',choices:['The middle value once the data are put in order','The most common value','The sum of the values divided by how many there are','The middle value in the order the data were collected'],key:0,
    miss:[null,'mode_median_swap','mean_median_swap','unordered_median'],
    why:['Correct. Order the data first, then take the middle value, or halfway between the two middle values.','The most common value is the mode.','That is the arithmetic mean.','The data must be ordered first; the collection order is arbitrary.'],
    steps:['Order the values from least to greatest.','Odd count: take the middle one. Even count: go halfway between the two middle ones.']},
   {stem:'Why does the median describe $0$, $7$, $50$, $10{,}000$, $1{,}000{,}000$ better than the mean does?',choices:['Because a mean cannot be worked out for large numbers','Because the median is always larger than the mean','One huge value pulls the mean far above most of the data, but the median, $50$, does not depend on how extreme that value is','Because the mode of this set is $50$'],key:2,
    miss:['mean_impossible','median_larger',null,'mode_confusion'],
    why:['The mean can be computed; it just gives a value unlike most of the data.','Here the median is far smaller than the mean.','Correct. Replace $1{,}000{,}000$ with $100$ and the median stays $50$, but the mean drops sharply.','Every value appears once, so this set has no mode.'],
    steps:['The mean is $\\frac{1{,}010{,}057}{5}$, about $202{,}011$, larger than four of the five values.','The median is the middle ordered value, $50$.']},
   {stem:'Find the median of $9$, $2$, $7$, $4$, $12$, $5$.',choices:['$5.5$','$6.5$','$5$','$6$'],key:3,
    miss:['unordered_median','mean_median_swap','lower_middle',null],
    why:['This averages the middle pair of the unordered list, $7$ and $4$.','$6.5$ is the mean, $\\frac{39}{6}$.','With six values there are two middle values; use halfway between them.','Correct. Ordered: $2$, $4$, $5$, $7$, $9$, $12$. Halfway between $5$ and $7$ is $6$.'],
    steps:['Order: $2$, $4$, $5$, $7$, $9$, $12$.','The middle two are $5$ and $7$.','Median: $\\frac{5 + 7}{2} = 6$.']},
   {stem:'For the data $8$, $2$, $5$, $2$, $9$, $4$, a student says the mode is $9$ because it is the largest value. What is the mode?',choices:['$9$, the largest value','$2$, because it appears twice and every other value appears once','$4.5$, the middle of the ordered data','There is no mode'],key:1,
    miss:['largest_as_mode',null,'median_as_mode','no_mode_confusion'],
    why:['The mode is about frequency, not size.','Correct. The mode is the most common value.','$4.5$ is the median.','A set has no mode only when no value is more common than the others; here $2$ is.'],
    steps:['Count each value: $2$ appears twice, the rest once.','Mode: $2$.']},
  ]}),
 lessonQuiz({lesson:'permutations-and-combinations',video:'DROZVHObeko',reviewed:'2026-10-08',
  keyIdea:'To count ordered arrangements, multiply the number of choices for each position in turn, such as $5 \\times 4 \\times 3$ for $3$ seats filled from $5$ people, which matches the formula $\\frac{n!}{(n - r)!}$.',
  watchFor:[{at:41,text:'People are seated one chair at a time. Count the choices for each chair.'},{at:133,text:'Now there are fewer chairs than people. Pause and predict the count.'},{at:290,text:'The product is rewritten with factorials. Watch what is divided out.'}],
  practice:{url:'https://www.khanacademy.org/math/pisa-2025-math-supplement/x092b0b93d51c9e96:quantity/x092b0b93d51c9e96:counting-principles/e/permutations_1',label:'Permutations',checked:'2026-10-08'},
  items:[
   {stem:'In how many ways can $5$ people be seated in $5$ chairs?',choices:['$25$','$5! = 120$','$15$','$5$'],key:1,
    miss:['repeats_allowed',null,'added_choices','one_each'],
    why:['$5 \\times 5$ would let the same person sit in two chairs.','Correct. $5 \\times 4 \\times 3 \\times 2 \\times 1 = 120$.','The choices multiply; adding $5 + 4 + 3 + 2 + 1$ undercounts.','There are many orders, not just one per person.'],
    steps:['Chair one: $5$ choices; chair two: $4$; then $3$, $2$, $1$.','$5 \\times 4 \\times 3 \\times 2 \\times 1 = 120$.']},
   {stem:'When people are seated one chair at a time, why does each chair have one fewer choice than the chair before it?',choices:['Because the chairs are numbered','Because order does not matter','Because one chair must stay empty','Each seated person can no longer be chosen, so the group still waiting shrinks by one'],key:3,
    miss:['numbering_reason','order_irrelevant','empty_chair',null],
    why:['Numbering the chairs makes order matter, but it does not reduce the choices.','Here order does matter: who sits where counts.','No chair is left empty when the counts are equal.','Correct. Nobody can sit in two chairs.'],
    steps:['After one person sits, one fewer person remains for the next chair.']},
   {stem:'A club of $8$ members chooses a president, a vice president and a secretary, all different people. In how many ways can this be done?',choices:['$336$','$512$','$56$','$21$'],key:0,
    miss:[null,'repeats_allowed','order_ignored','added_choices'],
    why:['Correct. $8 \\times 7 \\times 6 = 336$.','$8^3$ lets one person hold two posts.','$56$ counts groups of three with no titles; here the posts are different.','The choices multiply, not add.'],
    steps:['President: $8$ choices. Vice president: $7$. Secretary: $6$.','$8 \\times 7 \\times 6 = 336$, which equals $\\frac{8!}{5!}$.']},
   {stem:'A student writes the number of ways to seat $6$ people in $2$ chairs as $\\frac{6!}{2!}$. What should the denominator be?',choices:['$2!$ is right: divide by the factorial of the number of chairs','$6!$, giving $1$','$(6 - 2)! = 4!$, because the factors left out are the ones for the $4$ people without chairs; the answer is $30$','There should be no denominator, so the answer is $720$'],key:2,
    miss:['divide_by_r','divide_by_n',null,'forgot_division'],
    why:['$\\frac{6!}{2!} = 360$, far more than $6 \\times 5$.','Dividing by $6!$ leaves only $1$ way, which is clearly wrong.','Correct. $\\frac{6!}{4!} = 6 \\times 5 = 30$.','$6!$ seats all six people; only two chairs exist.'],
    steps:['Directly: $6 \\times 5 = 30$.','With factorials: $\\frac{6!}{(6 - 2)!} = \\frac{720}{24} = 30$.']},
  ]}),
 lessonQuiz({lesson:'probability-of-events',video:'xSc4oLA9e8o',reviewed:'2026-10-08',
  keyIdea:'For independent events, such as separate flips of a fair coin, the probability of a whole sequence is the product of the individual probabilities, and earlier results do not change later ones.',
  watchFor:[{at:39,text:'The probabilities of every outcome of one flip are added. Note the total.'},{at:158,text:'A common belief about streaks is named and rejected.'},{at:235,text:'A specific three-flip sequence is considered. Count the outcomes to check the product.'}],
  practice:{url:'https://www.khanacademy.org/math/10th-grade-math-revised-k-to-10-3-terms/x06a77af3c81397cf:third-term/x06a77af3c81397cf:probability-of-compound-events/e/independent_probability',label:'Independent probability',checked:'2026-10-08'},
  items:[
   {stem:'What do the probabilities of all the possible outcomes of one coin flip add up to?',choices:['$\\frac{1}{2}$','$2$','$1$','$0$'],key:2,
    miss:['one_outcome','count_outcomes',null,'cancel_outcomes'],
    why:['$\\frac{1}{2}$ is one outcome’s probability.','$2$ is the number of outcomes, not their total probability.','Correct. $\\frac{1}{2} + \\frac{1}{2} = 1$; something must happen.','Probabilities are not negative, so they cannot cancel to $0$.'],
    steps:['Heads: $\\frac{1}{2}$. Tails: $\\frac{1}{2}$.','Total: $1$.']},
   {stem:'After five heads in a row, a friend says tails is “due” on the next flip of a fair coin. Why is that wrong?',choices:['Each flip is independent, so the next flip is still $\\frac{1}{2}$ heads, whatever came before','It is right; results must even out on the next flip','Heads is more likely, because the coin is on a streak','The next flip is $\\frac{1}{32}$ heads, because a sixth head in a row is rare'],key:0,
    miss:[null,'gamblers_fallacy','hot_hand','sequence_vs_single'],
    why:['Correct. Past flips do not affect a fair coin.','The coin has no memory; this is the gambler’s fallacy.','A streak does not make a fair coin favour heads.','Six heads in a row was unlikely before the flips began, but the next single flip is still $\\frac{1}{2}$.'],
    steps:['Flips are independent events.','$P(\\text{heads on next flip}) = \\frac{1}{2}$.']},
   {stem:'A fair coin is flipped $4$ times. What is the probability of heads, tails, tails, heads, in exactly that order?',choices:['$\\frac{1}{8}$','$\\frac{1}{16}$','$\\frac{1}{4}$','$\\frac{6}{16}$'],key:1,
    miss:['wrong_count',null,'two_outcomes','any_order'],
    why:['$\\frac{1}{8}$ is for three flips.','Correct. $\\frac{1}{2} \\times \\frac{1}{2} \\times \\frac{1}{2} \\times \\frac{1}{2} = \\frac{1}{16}$.','$\\frac{1}{4}$ is for two flips.','$\\frac{6}{16}$ counts two heads and two tails in any order.'],
    steps:['Each flip: $\\frac{1}{2}$.','Four independent flips: $\\left(\\frac{1}{2}\\right)^4 = \\frac{1}{16}$.']},
   {stem:'Tails, heads, tails in that order has probability $\\frac{1}{8}$. A student says two tails and one head in any order also has probability $\\frac{1}{8}$. What is the correct probability?',choices:['$\\frac{1}{8}$','$\\frac{2}{3}$','$\\frac{1}{2}$','$\\frac{3}{8}$, because three of the eight equally likely outcomes have two tails and one head'],key:3,
    miss:['any_order_as_one','fraction_of_flips','single_flip',null],
    why:['$\\frac{1}{8}$ is for one particular order only.','$\\frac{2}{3}$ is the fraction of flips that are tails, not a probability of the outcome.','$\\frac{1}{2}$ is the chance of one flip.','Correct. TTH, THT and HTT each have probability $\\frac{1}{8}$.'],
    steps:['List the $8$ outcomes of three flips.','TTH, THT and HTT fit, so the probability is $\\frac{3}{8}$.']},
  ]}),
 lessonQuiz({lesson:'reading-tables-and-graphs',video:'R48KimqkYTA',reviewed:'2026-10-08',concept:'statistics_probability',
  keyIdea:'Read each bar’s height against the scale, then answer by comparing, adding or subtracting those values; check the scale’s step size before reading between gridlines.',
  watchFor:[{at:25,text:'A threshold is drawn across the graph. Notice which bars fall below it.'},{at:95,text:'Two bars are combined and matched with a third.'},{at:196,text:'A difference is found a second way, by counting gridlines.'}],
  practice:{url:'https://www.khanacademy.org/math/10th-grade-math-foundations/x6c7b196f1c375936:data-and-probability/x6c7b196f1c375936:data-collection-and-sampling-techniques-and-the-presentation-of-data-in-appropriate-tables-and-graphs/e/solving-problems-with-bar-graphs-3',label:'Read bar graphs',checked:'2026-10-08'},
  items:[
   {stem:'In a bar graph, what tells you the value for a category?',choices:['The width of its bar','The order of the bars from left to right','The number of gridlines the bar crosses, ignoring the scale','The height of its bar, read against the scale on the axis'],key:3,
    miss:['width_as_value','position_as_value','gridlines_as_value',null],
    why:['Bars are usually the same width; width carries no value.','Order is just how the categories are arranged.','Gridlines only mean something together with the scale’s step size.','Correct. The bar’s end lines up with a value on the scale.'],
    steps:['Find where the bar ends.','Read that level on the scale.']},
   {stem:'When the gridlines go up in steps of $25$, why can a difference between two bars be found by counting gridlines?',choices:['Each gridline is worth $1$, so count them directly','Each gridline step is worth $25$, so counting the steps and multiplying by $25$ gives the difference','Gridlines matter only for the tallest bar','Counting gridlines gives the sum of the bars, not the difference'],key:1,
    miss:['unit_steps',null,'gridline_irrelevant','sum_difference_confusion'],
    why:['The step size is $25$, not $1$.','Correct. Six steps of $25$ is a difference of $150$.','Every bar is read against the same gridlines.','Counting the steps between two bar tops measures the gap, which is the difference.'],
    steps:['Count the gridline steps between the two bar tops.','Multiply by the step size.']},
   {stem:'A bar graph shows $175$ votes for vanilla, $60$ for mango and $240$ for chocolate. How many more votes did the most popular flavour get than the least popular?',choices:['$65$','$300$','$180$','$115$'],key:2,
    miss:['wrong_least','added_values',null,'wrong_most'],
    why:['$240 - 175$ uses vanilla, but mango is the least popular.','The question asks how many more, which is a difference, not a sum.','Correct. $240 - 60 = 180$.','$175 - 60$ uses vanilla, but chocolate is the most popular.'],
    steps:['Most popular: chocolate, $240$. Least popular: mango, $60$.','$240 - 60 = 180$.']},
   {stem:'On a bar graph with gridlines every $20$, a bar ends halfway between the gridlines for $40$ and $60$. A student reads it as $45$. What is the better reading?',choices:['$50$, because halfway between $40$ and $60$ is $50$','$45$, because each half step is $5$','$41$, just above the lower gridline','$60$, the next gridline up'],key:0,
    miss:[null,'unit_steps','read_nearest_gridline','round_up'],
    why:['Correct. Half of a $20$ step is $10$, and $40 + 10 = 50$.','Half of a $20$ step is $10$, not $5$.','Halfway is not just above the lower line.','The bar stops short of $60$.'],
    steps:['Step size: $20$, so half a step is $10$.','$40 + 10 = 50$.']},
  ]}),
 lessonQuiz({lesson:'variance-standard-deviation-and-percentiles',video:'E4HAYd0QnRc',reviewed:'2026-10-08',concept:'statistics_probability',
  keyIdea:'Two data sets can share a mean but differ in spread: the range is the largest minus the smallest value, the variance averages the squared distances from the mean, and the standard deviation is the square root of the variance, in the data’s own units.',
  watchFor:[{at:27,text:'Two data sets are compared. Find their means before anything else.'},{at:199,text:'The simplest measure of spread is worked out for both sets.'},{at:579,text:'Listen for why a square root is taken at the end.'}],
  practice:{url:'https://www.khanacademy.org/math/statistics-probability/summarizing-quantitative-data/variance-standard-deviation-population/e/standard_deviation_of_a_population',label:'Standard deviation of a population',checked:'2026-10-08'},
  items:[
   {stem:'What is the standard deviation of a population?',choices:['The square root of the variance','The variance multiplied by $2$','The largest value minus the smallest value','The mean of the data'],key:0,
    miss:[null,'double_variance','range_as_sd','mean_as_sd'],
    why:['Correct. $\\sigma = \\sqrt{\\sigma^2}$.','Doubling the variance has no meaning here.','That is the range.','The mean measures centre, not spread.'],
    steps:['Variance: the average of the squared distances from the mean, $\\sigma^2$.','Standard deviation: $\\sigma = \\sqrt{\\sigma^2}$.']},
   {stem:'Why is the standard deviation often preferred to the variance?',choices:['Because the variance can be negative','Because the standard deviation ignores the mean','Squaring makes the variance’s units squared, such as square metres; the square root returns to the data’s own units','Because the variance uses only the largest and smallest values'],key:2,
    miss:['negative_variance','ignores_mean',null,'variance_as_range'],
    why:['Squares are never negative, so the variance is never negative.','Both are built from distances to the mean.','Correct. Data in metres give a variance in square metres and a standard deviation in metres.','The variance uses every value; that description fits the range.'],
    steps:['Variance is in squared units.','Taking the square root gives the standard deviation in the original units.']},
   {stem:'Find the population variance of $2$, $4$, $6$, $8$.',choices:['$\\sqrt{5}$','$5$','$6$','$20$'],key:1,
    miss:['sd_not_variance',null,'range_as_variance','forgot_divide'],
    why:['$\\sqrt{5}$ is the standard deviation, one step too far.','Correct. Mean $5$; squared distances $9$, $1$, $1$, $9$ sum to $20$; $\\frac{20}{4} = 5$.','$8 - 2 = 6$ is the range.','$20$ is the sum of the squared distances; divide by the $4$ values.'],
    steps:['Mean: $\\frac{2 + 4 + 6 + 8}{4} = 5$.','Squared distances: $9$, $1$, $1$, $9$, with sum $20$.','Variance: $\\frac{20}{4} = 5$.']},
   {stem:'Two data sets both have mean $10$. A student concludes they must be spread out the same way. Which example shows this is wrong?',choices:['None; equal means force equal spread','$5$, $10$, $15$ and $15$, $10$, $5$','$10$, $10$, $10$ and $10$, $10$, $10$','$0$, $10$, $20$ and $9$, $10$, $11$, which share a mean of $10$ but have ranges $20$ and $2$'],key:3,
    miss:['mean_decides_spread','order_matters','identical_example',null],
    why:['A mean says nothing about spread.','These are the same values in a different order, so the spread is identical.','Identical sets cannot show a difference in spread.','Correct. Same centre, very different spread.'],
    steps:['Both sets have mean $10$.','Ranges: $20 - 0 = 20$ and $11 - 9 = 2$, so their spreads differ.']},
  ]}),
 lessonQuiz({lesson:'fundamental-counting-principle-and-factorials',video:'DROZVHObeko',reviewed:'2026-10-08',concept:'statistics_probability',
  keyIdea:'When a task happens in stages, multiply the number of choices at each stage; filling every position in order gives $n! = n \\times (n - 1) \\times \\ldots \\times 1$.',
  watchFor:[{at:29,text:'Count how many people could take the first chair, then the second.'},{at:92,text:'A product that runs all the way down to one is given a name.'},{at:227,text:'Listen for why the speaker prefers reasoning it through to memorising a formula.'}],
  practice:{url:'https://www.khanacademy.org/math/pisa-2025-math-supplement/x092b0b93d51c9e96:quantity/x092b0b93d51c9e96:counting-principles/e/fundamental-counting-principle',label:'The counting principle',checked:'2026-10-08'},
  items:[
   {stem:'What does $4!$ mean?',choices:['$4 + 3 + 2 + 1 = 10$','$4 \\times 3 \\times 2 \\times 1 = 24$','$4 \\times 4 = 16$','$4 \\times 3 = 12$'],key:1,
    miss:['factorial_as_sum',null,'factorial_as_square','stopped_early'],
    why:['A factorial multiplies; it does not add.','Correct. Multiply every whole number from $4$ down to $1$.','A factorial uses decreasing factors, not the same one twice.','The product continues down to $1$.'],
    steps:['$4! = 4 \\times 3 \\times 2 \\times 1 = 24$.']},
   {stem:'Why are the numbers of choices multiplied, not added, when people are seated chair by chair?',choices:['For each way of filling the first chair there is a full set of ways to fill the next, so the counts multiply','Because addition is used only for probabilities','Because multiplication always gives the larger, safer answer','Because every chair has the same number of choices'],key:0,
    miss:[null,'operation_rule','bigger_is_right','equal_choices'],
    why:['Correct. $5$ first choices, each followed by $4$ second choices, gives $5 \\times 4 = 20$ pairs.','The operation comes from the structure of the choices, not from a rule about topics.','A bigger number is not automatically right; the structure decides.','The number of choices falls by one each time.'],
    steps:['Each first choice pairs with every second choice.','So the counts multiply: $5 \\times 4 = 20$.']},
   {stem:'A lunch combo lets you pick $1$ of $3$ rice dishes, $1$ of $4$ viands and $1$ of $2$ drinks. How many different combos are there?',choices:['$9$','$12$','$24$','$6$'],key:2,
    miss:['added_choices','forgot_stage',null,'partial_product'],
    why:['Adding $3 + 4 + 2$ counts single items, not combinations.','$3 \\times 4$ forgets the drink.','Correct. $3 \\times 4 \\times 2 = 24$.','$3 \\times 2$ forgets the viand.'],
    steps:['Three stages: $3$, $4$ and $2$ choices.','$3 \\times 4 \\times 2 = 24$.']},
   {stem:'A student says $\\frac{6!}{4!}$ means $\\frac{6}{4}$, which is $1.5$. What is its value?',choices:['$1.5$','$2! = 2$','$720$','$30$, because the common factors cancel and leave $6 \\times 5$'],key:3,
    miss:['factorial_ignored','subtract_inside','forgot_division',null],
    why:['The factorial signs cannot be dropped.','$\\frac{6!}{4!}$ is not $(6 - 4)!$.','$720$ is $6!$ alone; divide by $4! = 24$.','Correct. $\\frac{6 \\times 5 \\times 4!}{4!} = 30$.'],
    steps:['$6! = 6 \\times 5 \\times 4!$.','$\\frac{6!}{4!} = 6 \\times 5 = 30$.']},
  ]}),
];
