import {lessonQuiz} from './author.ts';

/** UPCAT Mathematics: Logic and calculus basics. Original draft items written from Khan's
 * timestamped caption transcripts, read 2026-10-08; pending subject review.
 * Receipts: docs/THIRD_PARTY_MATERIALS.md, "Lesson quiz caption reviews". */
export const MATH_LOGIC_CALCULUS=[
 lessonQuiz({lesson:'propositions-and-truth-tables',video:'5kojy1CHuyI',reviewed:'2026-10-08',concept:'logic',chapter:'m_geometry',
  keyIdea:'A conditional “if $p$, then $q$” always agrees with its contrapositive, “if not $q$, then not $p$”, but not with its converse or its inverse, which can be false even when the original is true.',
  watchFor:[{at:39,text:'The parts after “if” and “then” are swapped. Listen for the name of this version.'},{at:115,text:'A “not” is added to both parts. Test it against another cause of sneezing.'},{at:193,text:'Both moves are combined. Decide whether this version must be true.'}],
  practice:{url:'https://www.khanacademy.org/math/strengthened-shs-general-math/x24dc5a0902f75de5:fourth-quarter/x24dc5a0902f75de5:propositions/e/conditional-statements',label:'Conditional statements',checked:'2026-10-08'},
  items:[
   {stem:'What is the contrapositive of “if $p$, then $q$”?',choices:['If $q$, then $p$','If not $p$, then not $q$','If not $q$, then not $p$','If $p$, then not $q$'],key:2,
    miss:['converse_as_contrapositive','inverse_as_contrapositive',null,'negation_confusion'],
    why:['Swapping the parts without negating them gives the converse.','Negating both parts without swapping them gives the inverse.','Correct. Swap the parts and negate both.','This keeps $p$ but negates the result, so it disagrees with the original whenever $p$ is true.'],
    steps:['Converse: swap. Inverse: negate both. Contrapositive: swap and negate both.','Contrapositive of “if $p$, then $q$”: “if not $q$, then not $p$”.']},
   {stem:'Assume “if it is raining, then the road is wet” is true. Why need “if the road is wet, then it is raining” not be true?',choices:['Something else, such as a burst pipe, could wet the road; the original only says rain is enough to wet it','It must be true, because a statement and its converse always agree','Because the converse puts “not” in front of both parts','Because a conditional is true only when both of its parts are true'],key:0,
    miss:[null,'converse_equivalent','converse_inverse_confusion','conditional_truth_confusion'],
    why:['Correct. Rain is sufficient for a wet road, but it is not the only cause.','A converse can fail even when the original holds, as the burst pipe shows.','That describes the inverse; the converse swaps the parts.','A conditional only promises what happens when its “if” part holds.'],
    steps:['The original: rain guarantees a wet road.','The converse claims a wet road guarantees rain, which another cause can break.']},
   {stem:'Assume “if a number is divisible by $6$, then it is even” is true. Which statement must also be true?',choices:['If a number is even, then it is divisible by $6$','If a number is not divisible by $6$, then it is not even','If a number is even, then it is not divisible by $6$','If a number is not even, then it is not divisible by $6$'],key:3,
    miss:['converse_as_true','inverse_as_true','negation_confusion',null],
    why:['This is the converse, and $4$ is even but not divisible by $6$.','This is the inverse, and $4$ again breaks it.','$12$ is even and divisible by $6$, so this fails.','Correct. This is the contrapositive, which always agrees with the original.'],
    steps:['Contrapositive: swap the parts and negate both.','“If not even, then not divisible by $6$”: an odd number cannot be a multiple of $6$.']},
   {stem:'“If a shape is a square, then it has four sides” is true. A student concludes that being a square is necessary for having four sides. What is correct?',choices:['The student is right; the “if” part is always necessary','Being a square is sufficient for having four sides, not necessary: rectangles have four sides too','Being a square is neither necessary nor sufficient for having four sides','Having four sides is sufficient for being a square'],key:1,
    miss:['sufficient_necessary_swap',null,'neither_confusion','converse_as_true'],
    why:['The “if” part of a true conditional is sufficient, not necessary.','Correct. A square is enough to have four sides, but other shapes have four sides as well.','Being a square does guarantee four sides, so it is sufficient.','This is the converse, which fails for rectangles.'],
    steps:['“If $p$, then $q$” makes $p$ sufficient for $q$.','It does not make $p$ necessary for $q$.']},
  ]}),
 lessonQuiz({lesson:'limits',video:'riXcZT2ICjA',reviewed:'2026-10-08',concept:'limits',chapter:'m_lines',
  keyIdea:'The limit of $f(x)$ as $x$ approaches a value is what $f(x)$ gets closer and closer to from both sides; it can differ from the function’s value there, or exist where the function is undefined.',
  watchFor:[{at:27,text:'A function that seems to simplify to $1$ is defined. Find the one input where it fails.'},{at:205,text:'The question changes from the value at a point to what the function approaches.'},{at:578,text:'The limit is estimated numerically, from below and then from above.'}],
  practice:{url:'https://www.khanacademy.org/math/senior-high-school-basic-calculus/x7f730b2f064f7e01:unit-1/x7f730b2f064f7e01:lesson-1/e/limits-intro',label:'Limits intro',checked:'2026-10-08'},
  items:[
   {stem:'What does “the limit of $f(x)$ as $x$ approaches $1$” describe?',choices:['The value of $f(1)$ itself','The value $f(x)$ gets closer and closer to as $x$ gets closer to $1$ from both sides','The largest value $f(x)$ ever reaches','The input where $f(x)$ is undefined'],key:1,
    miss:['limit_as_value',null,'limit_as_max','limit_as_input'],
    why:['The limit can exist even when $f(1)$ is undefined or different.','Correct. A limit is about where the outputs are heading.','A limit is about nearby inputs, not the maximum.','The limit is an output value, not an input.'],
    steps:['Look at inputs close to $1$, from both sides.','The limit is the value the outputs approach.']},
   {stem:'For $f(x) = \\frac{x - 1}{x - 1}$, why is $f(1)$ undefined even though $f(x) = 1$ for every other $x$?',choices:['Because $\\frac{x - 1}{x - 1}$ always equals $0$','Because a limit cannot be taken at $x = 1$','At $x = 1$ the expression becomes $\\frac{0}{0}$, and division by zero is undefined','It is not undefined; the factors cancel, so $f(1) = 1$'],key:2,
    miss:['zero_over_zero_as_zero','limit_domain_confusion',null,'cancel_ignores_domain'],
    why:['For any $x$ other than $1$, the expression equals $1$.','The limit at $1$ exists and equals $1$; it is the value that is missing.','Correct. Cancelling is allowed only when $x - 1 \\ne 0$.','Simplifying to $1$ needs the condition $x \\ne 1$.'],
    steps:['$f(1) = \\frac{1 - 1}{1 - 1} = \\frac{0}{0}$, which is undefined.','For $x \\ne 1$, $f(x) = 1$, so the limit as $x$ approaches $1$ is $1$.']},
   {stem:'Let $h(x) = x + 3$ when $x \\ne 2$, and $h(2) = 10$. What is the limit of $h(x)$ as $x$ approaches $2$?',choices:['$5$','$10$','It does not exist','$2$'],key:0,
    miss:[null,'value_as_limit','jump_no_limit','input_as_limit'],
    why:['Correct. Near $x = 2$, $h(x) = x + 3$ gets close to $5$.','$10$ is the value at $2$, not the value approached.','The outputs approach $5$ from both sides, so the limit exists.','$2$ is the input being approached.'],
    steps:['For $x$ near $2$, $h(x) = x + 3$.','As $x$ approaches $2$, $x + 3$ approaches $5$.']},
   {stem:'Let $k(x) = 3x$ when $x \\ne 4$, and $k(4) = 0$. A student says the limit of $k(x)$ as $x$ approaches $4$ is $0$, because $k(4) = 0$. What is the limit?',choices:['$0$, because $k(4) = 0$','It does not exist, because of the gap','$4$, the input being approached','$12$, because the values of $k(x)$ near $x = 4$ approach $3 \\times 4$'],key:3,
    miss:['value_as_limit','gap_no_limit','input_as_limit',null],
    why:['The value at the point does not decide the limit.','A single moved point does not stop the outputs approaching $12$.','The limit is an output, not the input.','Correct. $3 \\times 3.99 = 11.97$ and $3 \\times 4.01 = 12.03$, both close to $12$.'],
    steps:['Try inputs near $4$: $k(3.99) = 11.97$ and $k(4.01) = 12.03$.','Both sides approach $12$.']},
  ]}),
 lessonQuiz({lesson:'simple-derivatives-and-integrals',video:'MMv-027KEqU',reviewed:'2026-10-08',concept:'calculus_basics',chapter:'m_lines',
  keyIdea:'An antiderivative undoes a derivative; because the derivative of any constant is $0$, $2x$ is the derivative of $x^2 + C$ for every constant $C$, so the indefinite integral of $2x$ is written $x^2 + C$.',
  watchFor:[{at:12,text:'Several different functions are differentiated. Notice that the results match.'},{at:65,text:'The direction is reversed. Listen for the new question being asked.'},{at:151,text:'A new notation is introduced for this reversed question.'}],
  practice:{url:'https://www.khanacademy.org/math/calculus-1/cs1-integrals/cs1-fundamental-theorem-of-calculus-and-definite-integrals/e/antiderivatives',label:'Antiderivatives and indefinite integrals',checked:'2026-10-08'},
  items:[
   {stem:'What is the most general antiderivative of $2x$?',choices:['$x^2$ only','$2$','$2x^2 + C$','$x^2 + C$, for any constant $C$'],key:3,
    miss:['forgot_constant','derivative_instead','kept_coefficient',null],
    why:['$x^2 + 1$ and $x^2 + \\pi$ also have derivative $2x$.','$2$ is the derivative of $2x$, the opposite direction.','$2x^2$ has derivative $4x$.','Correct. Every function $x^2 + C$ has derivative $2x$.'],
    steps:['The derivative of $x^2$ is $2x$.','Adding any constant does not change the derivative, so the answer is $x^2 + C$.']},
   {stem:'Why does the antiderivative need “$+ C$”?',choices:['Because $C$ stands for the coefficient $2$','The derivative of any constant is $0$, so $x^2$, $x^2 + 1$ and $x^2 + \\pi$ all have derivative $2x$','To show that the answer is only approximate','Because every derivative adds a constant'],key:1,
    miss:['c_as_coefficient',null,'c_as_error','derivative_adds_constant'],
    why:['$C$ is an unknown constant term, not a coefficient.','Correct. The constant is lost when differentiating, so reversing cannot tell which one it was.','The family $x^2 + C$ is exact; $C$ can be any constant.','Differentiating removes constants rather than adding them.'],
    steps:['A constant does not change, so its derivative is $0$.','So many functions share the derivative $2x$; $C$ covers all of them.']},
   {stem:'Which function has derivative $2x$ and passes through the point $(0, 5)$?',choices:['$x^2$','$2x + 5$','$x^2 + 5$','$x^2 + 5x$'],key:2,
    miss:['forgot_constant','derivative_confusion',null,'linear_term'],
    why:['$x^2$ passes through $(0, 0)$, not $(0, 5)$.','$2x + 5$ has derivative $2$, not $2x$.','Correct. Its derivative is $2x$, and at $x = 0$ it equals $5$.','$x^2 + 5x$ has derivative $2x + 5$.'],
    steps:['Antiderivatives of $2x$: $x^2 + C$.','At $x = 0$: $0 + C = 5$, so $C = 5$.']},
   {stem:'A student says $x^2 + x$ is an antiderivative of $2x$, because extra terms disappear when you differentiate. What is wrong?',choices:['$x^2 + x$ differentiates to $2x + 1$, not $2x$; only a constant can be added without changing the derivative','Nothing; any added term disappears','The $+ x$ is fine because $x$ is a constant','Checking by differentiating is not allowed'],key:0,
    miss:[null,'any_term_vanishes','x_as_constant','no_check'],
    why:['Correct. Only constants have derivative $0$.','Only constant terms disappear; $x$ has derivative $1$.','$x$ is the variable, not a constant.','Differentiating is exactly how to check an antiderivative.'],
    steps:['Differentiate $x^2 + x$: $2x + 1$.','That is not $2x$, so $x^2 + x$ is not an antiderivative of $2x$.']},
  ]}),
];
