import {lessonQuiz} from './author.ts';

/** UPCAT Mathematics: Geometry. Original draft items written from Khan's timestamped
 * caption transcripts, read 2026-10-08; pending subject review.
 * Receipts: docs/THIRD_PARTY_MATERIALS.md, "Lesson quiz caption reviews". */
export const MATH_GEOMETRY=[
 lessonQuiz({lesson:'lines-angles-and-their-properties',video:'H-E5rlpCVu4',reviewed:'2026-10-08',
  keyIdea:'When a transversal crosses two parallel lines, vertical angles are equal and corresponding angles are equal, so alternate interior angles are equal as well.',
  watchFor:[{at:38,text:'Listen for the two conditions that make two lines parallel.'},{at:147,text:'Angles opposite each other at one crossing are compared. Note which pairs match.'},{at:307,text:'A name is given to angles in matching positions at the two crossings.'}],
  practice:{url:'https://www.khanacademy.org/math/9th-grade-math-revised-k-to-10-3-terms/x1e64c39423990571:unit-1/x1e64c39423990571:parallel-and-perpendicular-lines/e/parallel_lines_1',label:'Angle relationships with parallel lines',checked:'2026-10-08'},
  items:[
   {stem:'Two different lines are parallel when they',choices:['lie in the same plane and never intersect','meet at a right angle','have the same length','are both crossed by one transversal'],key:0,
    miss:[null,'perpendicular_as_parallel','length_decides','transversal_decides'],
    why:['Correct. Same plane, never meeting: that is what parallel means.','Lines that meet at a right angle are perpendicular, not parallel.','Lines go on forever, so length cannot decide anything.','Any two lines can be crossed by a transversal, parallel or not.'],
    steps:['Parallel lines lie in the same plane and never intersect.']},
   {stem:'Why are alternate interior angles equal when a transversal crosses two parallel lines?',choices:['Because all eight angles at the two crossings are equal','Because they sit next to each other on a straight line','Because the transversal must be perpendicular to both lines','Each one equals the same angle: one by being vertical to it, the other by corresponding to it'],key:3,
    miss:['all_angles_equal','adjacent_supplementary','perpendicular_assumed',null],
    why:['Unless the transversal is perpendicular, there are two different sizes of angle at each crossing.','Angles next to each other on a straight line add to $180^\\circ$; they are not usually equal.','The result holds for a slanted transversal too.','Correct. Vertical angles are equal, and corresponding angles are equal, so the alternate interior pair must match.'],
    steps:['Let $b$ and $c$ be vertical angles, so $b = c$.','$b$ and $f$ correspond, so $b = f$.','Then $c = f$: the alternate interior angles are equal.']},
   {stem:'A transversal crosses two parallel lines. Angle $a$ at the upper crossing is $70^\\circ$. Angle $b$ is vertical to $a$, and angle $f$ at the lower crossing corresponds to $b$. What is angle $f$?',choices:['$110^\\circ$','$70^\\circ$','$20^\\circ$','$140^\\circ$'],key:1,
    miss:['used_supplement',null,'used_complement','added_angles'],
    why:['$110^\\circ$ is the angle beside $a$ on a straight line, not one equal to it.','Correct. $b = a = 70^\\circ$ by vertical angles, and $f = b$ by corresponding angles.','Complements add to $90^\\circ$; no right angle is involved here.','Equal angles are not added together.'],
    steps:['Vertical angles: $b = 70^\\circ$.','Corresponding angles: $f = b = 70^\\circ$.']},
   {stem:'A transversal crosses two lines, making corresponding angles of $70^\\circ$ and $75^\\circ$. A student says these angles are equal anyway, because corresponding angles are always equal. What is the flaw?',choices:['There is no flaw; corresponding angles are always equal','Corresponding angles must add to $180^\\circ$ instead','Corresponding angles are equal only when the lines are parallel, and these lines are not','Vertical angles should be compared, since they are equal only for parallel lines'],key:2,
    miss:['parallel_assumed','supplementary_confusion',null,'vertical_needs_parallel'],
    why:['The measured angles differ, so the rule cannot apply to these lines.','Corresponding angles of parallel lines are equal, not supplementary.','Correct. The equal-angle result needs parallel lines; unequal corresponding angles show the lines are not parallel.','Vertical angles are equal at any crossing, parallel lines or not.'],
    steps:['Corresponding angles are equal when the lines are parallel.','$70^\\circ \\ne 75^\\circ$, so these lines are not parallel.']},
  ]}),
 lessonQuiz({lesson:'triangles-congruence-and-similarity',video:'9ThXDY9Y3oU',reviewed:'2026-10-08',
  keyIdea:'Similar triangles are scaled copies: all corresponding angles are equal, and every pair of corresponding sides has the same ratio, the scale factor $k$.',
  watchFor:[{at:13,text:'Compare the angles of the two triangles before looking at the sides.'},{at:37,text:'Find the number each side length is multiplied by.'},{at:155,text:'Listen for how congruent triangles fit inside the idea of similar triangles.'}],
  practice:{url:'https://www.khanacademy.org/math/9th-grade-math-revised-k-to-10-3-terms/x1e64c39423990571:3rd-quarter/x1e64c39423990571:polygon-similiarity/e/solving_similar_triangles_1',label:'Solve similar triangles (basic)',checked:'2026-10-08'},
  items:[
   {stem:'If triangle $ABC$ is similar to triangle $XYZ$, which statement must be true?',choices:['$AB = XY$, $BC = YZ$ and $AC = XZ$','$AB + XY = BC + YZ$','$\\frac{AB}{XY} = \\frac{BC}{YZ} = \\frac{AC}{XZ}$','Only one pair of corresponding angles is equal'],key:2,
    miss:['similar_means_congruent','additive_scaling',null,'partial_angles'],
    why:['Equal sides would make the triangles congruent; similar triangles can differ in size.','Similarity scales sides by multiplying, so sums tell you nothing.','Correct. Every pair of corresponding sides has the same ratio, the scale factor.','All three pairs of corresponding angles are equal.'],
    steps:['Similar triangles have equal corresponding angles.','Corresponding sides share one ratio: $\\frac{AB}{XY} = \\frac{BC}{YZ} = \\frac{AC}{XZ} = k$.']},
   {stem:'Why are congruent triangles always similar, while similar triangles are not always congruent?',choices:['Congruent triangles use a scale factor of $1$; similar triangles may use any scale factor, so their sides can differ','Similar triangles must have different angles','Congruent triangles can be flipped, but similar triangles cannot','They are the same thing'],key:0,
    miss:[null,'angles_change','flip_rule','similar_means_congruent'],
    why:['Correct. Congruence is the special case of similarity where nothing is scaled.','Similar triangles have equal corresponding angles.','Both may be rotated, shifted or flipped.','Similar triangles can be different sizes; congruent triangles cannot.'],
    steps:['Similarity allows rotating, shifting, flipping and scaling.','Congruence allows the same moves but a scale factor of exactly $1$.']},
   {stem:'Triangle $PQR$ is similar to triangle $STU$, with $PQ = 6$, $QR = 9$ and $ST = 10$. What is $TU$?',choices:['$13$','$5.4$','$18$','$15$'],key:3,
    miss:['additive_scaling','inverted_ratio','doubled_side',null],
    why:['Adding $4$ to each side is not scaling; ratios must match.','This uses the ratio upside down: $9 \\times \\frac{6}{10}$.','Doubling would need $ST = 12$.','Correct. The scale factor is $\\frac{10}{6} = \\frac{5}{3}$, and $9 \\times \\frac{5}{3} = 15$.'],
    steps:['$PQ$ corresponds to $ST$, so $k = \\frac{10}{6} = \\frac{5}{3}$.','$QR$ corresponds to $TU$: $TU = 9 \\times \\frac{5}{3} = 15$.']},
   {stem:'Two triangles have sides $3$, $4$, $5$ and $6$, $8$, $12$. A student says they are similar because the first two sides doubled. What is wrong?',choices:['Nothing; two matching ratios are enough','Every pair of corresponding sides must share one ratio, and $\\frac{12}{5}$ is not $2$, so they are not similar','They must be similar because every side got longer','Triangles with whole-number sides are always similar'],key:1,
    miss:['partial_ratio',null,'any_enlargement','whole_numbers'],
    why:['All three ratios must match; the third side breaks the pattern.','Correct. $\\frac{6}{3} = 2$ and $\\frac{8}{4} = 2$, but $\\frac{12}{5} = 2.4$.','Growing unevenly changes the shape.','Whole numbers have nothing to do with similarity.'],
    steps:['Ratios: $\\frac{6}{3} = 2$, $\\frac{8}{4} = 2$, $\\frac{12}{5} = 2.4$.','The ratios are not all equal, so the triangles are not similar.']},
  ]}),
 lessonQuiz({lesson:'right-triangles-and-the-pythagorean-theorem',video:'AA6RfgP-AHU',reviewed:'2026-10-08',
  keyIdea:'In a right triangle, the squares of the two shorter sides add to the square of the hypotenuse, $a^2 + b^2 = c^2$, where $c$ is the side opposite the right angle.',
  watchFor:[{at:94,text:'Learn the name of the longest side and how to find it in any drawing.'},{at:197,text:'The theorem is stated. Note which side is squared on its own.'},{at:458,text:'This time the unknown is a shorter side. Watch how the solving changes.'}],
  practice:{url:'https://www.khanacademy.org/math/pisa-2025-math-supplement/x092b0b93d51c9e96:space-and-shape/x092b0b93d51c9e96:measurement-of-distance-and-lengths-including-pythagorean-theorem/e/pythagorean_theorem_1',label:'Use Pythagorean theorem to find right triangle side lengths',checked:'2026-10-08'},
  items:[
   {stem:'Which side of a right triangle is the hypotenuse?',choices:['A side next to the right angle','The side opposite the right angle, which is the longest side','The shortest side','Whichever side is drawn at the bottom'],key:1,
    miss:['adjacent_leg',null,'shortest_side','orientation'],
    why:['The two sides that form the right angle are the shorter sides.','Correct. The right angle opens onto the hypotenuse.','The hypotenuse is the longest side.','Drawings can be rotated; the right angle decides, not the position on the page.'],
    steps:['Find the right angle.','The side opposite it is the hypotenuse, the longest side.']},
   {stem:'Why must you identify the hypotenuse before using $a^2 + b^2 = c^2$?',choices:['Because the hypotenuse is always $5$','It does not matter which side is called $c$','Only the hypotenuse is squared on its own side of the equation, so labelling the wrong side as $c$ gives a wrong length','Because the hypotenuse is the only side that can be squared'],key:2,
    miss:['fixed_value','any_side_c',null,'only_c_squared'],
    why:['$5$ was only the answer in one example.','Swapping a shorter side into $c$ changes the equation and the answer.','Correct. The equation is not symmetric: $c$ must be the hypotenuse.','All three sides are squared; the point is which square stands alone.'],
    steps:['$c$ is the side opposite the right angle.','$a$ and $b$ are the two shorter sides, in either order.']},
   {stem:'A right triangle has hypotenuse $13$ and one shorter side $5$. How long is the other shorter side?',choices:['$12$','$\\sqrt{194}$','$8$','$144$'],key:0,
    miss:[null,'hypotenuse_as_leg','subtract_lengths','forgot_root'],
    why:['Correct. $5^2 + b^2 = 13^2$, so $b^2 = 144$ and $b = 12$.','This adds $13^2$ and $5^2$, treating the hypotenuse as a shorter side.','Side lengths do not subtract directly; their squares do.','$144$ is $b^2$. Take the square root.'],
    steps:['$5^2 + b^2 = 13^2$, so $25 + b^2 = 169$.','$b^2 = 144$, so $b = 12$.']},
   {stem:'A right triangle has shorter sides $6$ and $8$. A student writes the hypotenuse as $6 + 8 = 14$. What is the hypotenuse?',choices:['$14$, because the side lengths add','$100$','$\\sqrt{28}$','$10$, because the squares add: $36 + 64 = 100$'],key:3,
    miss:['add_lengths','forgot_root','subtract_squares',null],
    why:['The squares add, not the lengths. A hypotenuse is always shorter than the other two sides together.','$100$ is $c^2$; the hypotenuse is its square root.','This subtracts the squares, $64 - 36$; for the hypotenuse you add them.','Correct. $c^2 = 100$, so $c = 10$.'],
    steps:['$6^2 + 8^2 = 36 + 64 = 100$.','$c = \\sqrt{100} = 10$.']},
  ]}),
 lessonQuiz({lesson:'perimeter-and-area-of-plane-figures',video:'rRTXKQpblEc',reviewed:'2026-10-08',
  keyIdea:'Two copies of a triangle fit together into a parallelogram with the same base and height, so a triangle’s area is half of base times height, $\\frac{1}{2}bh$, even when the height falls outside the triangle.',
  watchFor:[{at:14,text:'A parallelogram is rearranged into a rectangle. Notice what stays the same.'},{at:88,text:'The triangle is copied and turned. Watch what shape the two copies make.'},{at:196,text:'An obtuse triangle appears. Notice where its height is measured.'}],
  practice:{url:'https://www.khanacademy.org/math/pisa-2025-math-supplement/x092b0b93d51c9e96:space-and-shape/x092b0b93d51c9e96:measurement-of-area/e/area_of_triangles_1',label:'Area of triangles',checked:'2026-10-08'},
  items:[
   {stem:'What is the area of a triangle with base $b$ and height $h$?',choices:['$bh$','$\\frac{1}{2}(b + h)$','$2bh$','$\\frac{1}{2}bh$'],key:3,
    miss:['forgot_half','added_dimensions','doubled_area',null],
    why:['$bh$ is the area of the parallelogram made of two copies.','Area multiplies the base and height; it does not add them.','Doubling goes the wrong way: the triangle is half the parallelogram.','Correct. The triangle is half of a parallelogram with area $bh$.'],
    steps:['Two copies make a parallelogram with area $bh$.','One triangle: $\\frac{1}{2}bh$.']},
   {stem:'Why is a triangle’s area exactly half of base times height?',choices:['Two identical copies of the triangle form a parallelogram whose area is base times height','Because a triangle has three sides instead of four','Because the height of a triangle is always half its base','Because every triangle is half of a square'],key:0,
    miss:[null,'side_count','height_half_base','half_square'],
    why:['Correct. The original triangle is one of the two equal halves.','The number of sides does not decide area.','Height and base can be any lengths.','A triangle is half of a parallelogram with the same base and height, which is usually not a square.'],
    steps:['Copy the triangle, rotate the copy and join them.','The parallelogram has area $bh$, so one triangle has $\\frac{1}{2}bh$.']},
   {stem:'A triangle has a base of $14$ cm and a height of $9$ cm. What is its area?',choices:['$126\\ \\text{cm}^2$','$11.5\\ \\text{cm}^2$','$63\\ \\text{cm}^2$','$31.5\\ \\text{cm}^2$'],key:2,
    miss:['forgot_half','added_dimensions',null,'halved_twice'],
    why:['$14 \\times 9 = 126$ is the parallelogram; halve it.','Adding and halving, $\\frac{14 + 9}{2}$, is not an area.','Correct. $\\frac{1}{2} \\times 14 \\times 9 = 63$.','This halves twice; halve only once.'],
    steps:['$\\frac{1}{2} \\times 14 \\times 9$.','$= 7 \\times 9 = 63\\ \\text{cm}^2$.']},
   {stem:'In an obtuse triangle, the height falls outside the triangle. A student uses the slanted side as the height instead. Why is that wrong?',choices:['It is not wrong; any side can be the height','The height is the perpendicular distance from the base line up to the top vertex, even when it lies outside the triangle','Obtuse triangles have no height, so the formula fails','The height of an obtuse triangle is always its longest side'],key:1,
    miss:['side_as_height',null,'no_height_obtuse','longest_side_height'],
    why:['A slanted side is longer than the perpendicular height, so the area comes out too big.','Correct. Height means straight up from the base line, like dropping a ball to the ground.','The formula still works; the height just lies outside.','The longest side is a side, not the perpendicular height.'],
    steps:['Extend the base line if needed.','Measure straight down from the top vertex to that line: that is the height.']},
  ]}),
 lessonQuiz({lesson:'circles',video:'ZyOhRgnFmIY',reviewed:'2026-10-08',
  keyIdea:'A circle’s area is $\\pi r^2$, so halve a given diameter to get the radius first; an answer in terms of $\\pi$ is exact, and decimals for $\\pi$ give approximations.',
  watchFor:[{at:13,text:'The given length goes all the way across the circle. Note its name.'},{at:51,text:'Listen for the area formula and the length it needs.'},{at:125,text:'Two approximations for $\\pi$ are used. Notice which one is closer.'}],
  practice:{url:'https://www.khanacademy.org/math/pisa-2025-math-supplement/x092b0b93d51c9e96:space-and-shape/x092b0b93d51c9e96:measurement-of-area/e/area_of_a_circle',label:'Area of a circle',checked:'2026-10-08'},
  items:[
   {stem:'What is the area of a circle with radius $r$?',choices:['$\\pi r^2$','$2\\pi r$','$\\pi d^2$, where $d$ is the diameter','$\\pi r$'],key:0,
    miss:[null,'circumference_formula','diameter_in_formula','forgot_square'],
    why:['Correct. Area is $\\pi$ times the radius squared.','$2\\pi r$ is the circumference, a length.','Using the diameter makes the area four times too big.','The radius must be squared for an area.'],
    steps:['$A = \\pi r^2$.']},
   {stem:'Why is $64\\pi$ square millimetres an exact area while $200.96$ square millimetres is not?',choices:['Because decimals are never exact','Because square millimetres cannot be written as decimals','$200.96$ is exact, and $64\\pi$ is the estimate','$200.96$ comes from using $3.14$, a rounded value of $\\pi$, whose decimal never ends or repeats'],key:3,
    miss:['decimals_inexact','units_restrict','pi_estimate_swap',null],
    why:['Many decimals are exact, such as $0.5$. The issue is the rounded $\\pi$.','Units do not limit the form of a number.','The rounded value of $\\pi$ makes the decimal answer approximate.','Correct. Keeping $\\pi$ avoids rounding; a calculator gives a closer value, about $201.06$.'],
    steps:['$64 \\times 3.14 = 200.96$, using a rounded $\\pi$.','$64\\pi$ keeps the exact value.']},
   {stem:'A round table top has a diameter of $10$ dm. What is its area, in terms of $\\pi$?',choices:['$100\\pi\\ \\text{dm}^2$','$10\\pi\\ \\text{dm}^2$','$25\\pi\\ \\text{dm}^2$','$5\\pi\\ \\text{dm}^2$'],key:2,
    miss:['diameter_in_formula','circumference_formula',null,'forgot_square'],
    why:['This squares the diameter; use the radius, $5$.','$10\\pi$ is the circumference, not the area.','Correct. $r = 5$, so $A = \\pi \\times 5^2 = 25\\pi$.','The radius must be squared: $5^2 = 25$.'],
    steps:['$r = \\frac{10}{2} = 5$ dm.','$A = \\pi \\times 5^2 = 25\\pi\\ \\text{dm}^2$.']},
   {stem:'A student finds the area of a circle with diameter $12$ cm as $\\pi \\times 12^2 = 144\\pi$. What is the correct area?',choices:['$144\\pi\\ \\text{cm}^2$, as written','$36\\pi\\ \\text{cm}^2$, because the radius is $6$','$12\\pi\\ \\text{cm}^2$','$72\\pi\\ \\text{cm}^2$, half of $144\\pi$'],key:1,
    miss:['diameter_in_formula',null,'circumference_formula','halved_area'],
    why:['The formula needs the radius, not the diameter.','Correct. $\\pi \\times 6^2 = 36\\pi$.','$12\\pi$ is the circumference.','Halving the area is not the fix; halve the diameter before squaring.'],
    steps:['$r = 6$ cm.','$A = \\pi \\times 6^2 = 36\\pi\\ \\text{cm}^2$.']},
  ]}),
 lessonQuiz({lesson:'surface-area-and-volume-of-solids',video:'gL3HxBQyeg0',reviewed:'2026-10-08',concept:'geometry',
  keyIdea:'A cylinder’s volume is its circular base area times its height, $\\pi r^2 h$; its surface area adds two circles to a rectangle whose sides are the circumference, $2\\pi r$, and the height.',
  watchFor:[{at:45,text:'Think of the top as a layer that is repeated down through the height.'},{at:200,text:'The surface is split into pieces. Count the flat pieces first.'},{at:251,text:'The curved side is cut and unrolled. Notice what one side of the rectangle equals.'}],
  practice:{url:'https://www.khanacademy.org/math/7th-grade-matatag/x065dcf1640354e81:2nd-quarter/x065dcf1640354e81:volume-of-pyramids/e/volumes-of-cones--cylinders--and-spheres',label:'Volume of cylinders',checked:'2026-10-08'},
  items:[
   {stem:'What is the volume of a cylinder with radius $r$ and height $h$?',choices:['$2\\pi rh$','$\\pi rh$','$\\frac{1}{3}\\pi r^2 h$','$\\pi r^2 h$'],key:3,
    miss:['lateral_as_volume','forgot_square','cone_formula',null],
    why:['$2\\pi rh$ is the area of the curved side, not a volume.','The base area needs the radius squared.','The $\\frac{1}{3}$ belongs to a cone.','Correct. Base area $\\pi r^2$ times height $h$.'],
    steps:['Base area: $\\pi r^2$.','Volume: $\\pi r^2 h$.']},
   {stem:'When the curved side of a cylinder is unrolled into a rectangle, why is one side of the rectangle $2\\pi r$ long?',choices:['That side wrapped once around the circular top, so its length is the circle’s circumference','Because it equals the area of the top','Because both sides of the rectangle equal the height','Because it equals the diameter, $2r$'],key:0,
    miss:[null,'area_as_length','height_both_sides','diameter_as_circumference'],
    why:['Correct. Going once around a circle of radius $r$ covers $2\\pi r$.','An area cannot be the length of a side.','Only the sides that were cut are the height.','The diameter goes across the circle; the edge went around it.'],
    steps:['The unrolled edge went once around the top circle.','So its length is the circumference, $2\\pi r$.']},
   {stem:'A cylinder has a radius of $3$ cm and a height of $10$ cm. What is its volume?',choices:['$60\\pi\\ \\text{cm}^3$','$90\\pi\\ \\text{cm}^3$','$30\\pi\\ \\text{cm}^3$','$9\\pi\\ \\text{cm}^3$'],key:1,
    miss:['lateral_as_volume',null,'forgot_square','base_only'],
    why:['$2\\pi \\times 3 \\times 10 = 60\\pi$ is the curved surface area.','Correct. $\\pi \\times 3^2 \\times 10 = 90\\pi$.','This forgets to square the radius.','$9\\pi$ is only the base area; multiply by the height.'],
    steps:['Base area: $\\pi \\times 3^2 = 9\\pi$.','Volume: $9\\pi \\times 10 = 90\\pi\\ \\text{cm}^3$.']},
   {stem:'A student gives the surface area of a closed cylinder as just $2\\pi rh$. What is missing?',choices:['Nothing; $2\\pi rh$ is the whole surface','The volume, $\\pi r^2 h$, must be added','The two circular ends, $2\\pi r^2$, must be added','One circular end, $\\pi r^2$, must be added'],key:2,
    miss:['lateral_only','add_volume',null,'one_end_only'],
    why:['A closed can has a top and a bottom too.','Volume is not part of a surface; the units would not even match.','Correct. Total surface area is $2\\pi r^2 + 2\\pi rh$.','A closed cylinder has two ends.'],
    steps:['Top and bottom: $2\\pi r^2$.','Curved side: $2\\pi rh$.','Total: $2\\pi r^2 + 2\\pi rh$.']},
  ]}),
 lessonQuiz({lesson:'converting-units-of-measurement',video:'SYkmadc2wOI',reviewed:'2026-10-08',concept:'geometry',
  keyIdea:'Metric prefixes are powers of ten (kilo $1000$, hecto $100$, deka $10$, deci $\\frac{1}{10}$, centi $\\frac{1}{100}$, milli $\\frac{1}{1000}$), so converting means multiplying by factors arranged so that units cancel.',
  watchFor:[{at:12,text:'The prefixes are listed from largest to smallest. Note the value of each.'},{at:122,text:'Before calculating, predict whether the answer should be a large or a small number.'},{at:243,text:'Each conversion factor is written so that one unit cancels.'}],
  practice:{url:'https://www.khanacademy.org/math/7th-grade-matatag/x065dcf1640354e81:2nd-quarter/x065dcf1640354e81:conversion-of-measurements/e/converting-units',label:'Convert units (metrics)',checked:'2026-10-08'},
  items:[
   {stem:'What does the prefix centi- mean?',choices:['$100$','$\\frac{1}{10}$','$\\frac{1}{1000}$','$\\frac{1}{100}$'],key:3,
    miss:['inverse_prefix','deci_confusion','milli_confusion',null],
    why:['$100$ is hecto-. Centi- is one hundredth.','$\\frac{1}{10}$ is deci-.','$\\frac{1}{1000}$ is milli-.','Correct. A centilitre is $\\frac{1}{100}$ of a litre.'],
    steps:['centi- means $\\frac{1}{100}$, so $100$ centilitres make $1$ litre.']},
   {stem:'Why must $1$ dekalitre equal many centilitres, rather than a small fraction of one?',choices:['Because converting always multiplies by $1000$','A dekalitre is a much larger unit than a centilitre, so many small units fit in one large unit','Because both prefixes make units smaller than a litre','It does not; $1$ dekalitre is $\\frac{1}{1000}$ of a centilitre'],key:1,
    miss:['fixed_factor',null,'deka_below_litre','inverted_conversion'],
    why:['The factor depends on the prefixes; here it happens to be $1000$.','Correct. A dekalitre is $10$ litres and a centilitre is $\\frac{1}{100}$ of a litre, so the answer is $1000$ centilitres.','Deka- means $10$, so a dekalitre is larger than a litre.','This divides when it should multiply; a reality check catches it.'],
    steps:['$1$ dekalitre $= 10$ litres.','$10$ litres $= 10 \\times 100 = 1000$ centilitres.']},
   {stem:'How many millilitres are in $2.5$ litres?',choices:['$0.0025$','$250$','$2500$','$25$'],key:2,
    miss:['inverted_conversion','centi_confusion',null,'deci_confusion'],
    why:['Dividing gives a tiny number, but millilitres are smaller units, so there should be many.','$250$ would be centilitres, using $100$ per litre.','Correct. $2.5 \\times 1000 = 2500$ millilitres.','$25$ would be decilitres.'],
    steps:['$1$ litre $= 1000$ millilitres.','$2.5 \\times 1000 = 2500$.']},
   {stem:'Converting $3$ km to centimetres, a student writes $3 \\times \\frac{1\\ \\text{km}}{1000\\ \\text{m}} \\times \\frac{1\\ \\text{m}}{100\\ \\text{cm}}$. What is wrong?',choices:['Both factors are upside down, so the units do not cancel; using $\\frac{1000\\ \\text{m}}{1\\ \\text{km}}$ and $\\frac{100\\ \\text{cm}}{1\\ \\text{m}}$ gives $300{,}000$ cm','Nothing; the answer is $0.00003$ cm','Only one factor is needed: $3 \\times 100 = 300$ cm','Kilometres cannot be converted to centimetres'],key:0,
    miss:[null,'inverted_conversion','single_factor','no_direct_conversion'],
    why:['Correct. Put the unit you are cancelling in the denominator each time.','A distance of $3$ km is far more than a fraction of a centimetre; the reality check fails.','Kilometres to metres needs a factor of $1000$ too.','Any length unit converts to another with the right factors.'],
    steps:['$3 \\times \\frac{1000\\ \\text{m}}{1\\ \\text{km}} = 3000$ m.','$3000 \\times \\frac{100\\ \\text{cm}}{1\\ \\text{m}} = 300{,}000$ cm.']},
  ]}),
 lessonQuiz({lesson:'geometric-reasoning-and-proofs',video:'u6O0YHyarlI',reviewed:'2026-10-08',concept:'proof_reasoning',chapter:'m_geometry',
  keyIdea:'In a proof by contradiction, assume the opposite of what you want to prove, reason correctly until something impossible appears, and conclude that the assumption was false.',
  watchFor:[{at:14,text:'Listen for what is assumed at the very start of the proof.'},{at:62,text:'A fact about triangle angles is recalled before any answer choice is read.'},{at:549,text:'An assumption leads to a clash with a given fact. Note what is concluded.'}],
  practice:{url:'https://www.khanacademy.org/math/strengthened-shs-general-math-3-terms/x52e1fe4f21d4618e:fourth-quarter/x52e1fe4f21d4618e:propositions/e/conditional-statements',label:'Conditional statements',checked:'2026-10-08'},
  items:[
   {stem:'What is the first step of a proof by contradiction?',choices:['Assume the statement is true and test an example','List every possible case and test each one','Assume the opposite of the statement you want to prove','Draw the figure to scale and measure it'],key:2,
    miss:['example_as_proof','exhaustion_confusion',null,'measure_as_proof'],
    why:['One example cannot prove a general statement.','Checking every case is a different method, proof by cases.','Correct. You assume the opposite and look for something impossible.','A drawing can mislead and is not a proof.'],
    steps:['Assume the opposite of the claim.','Reason until a contradiction appears, then reject the assumption.']},
   {stem:'To prove that a triangle has at most one obtuse angle, why does assuming two obtuse angles lead to a contradiction?',choices:['Obtuse angles cannot appear in triangles at all','Two angles greater than $90^\\circ$ add to more than $180^\\circ$, leaving the third angle less than $0^\\circ$, which is impossible','Two obtuse angles would make the triangle equilateral','The three angles would then add to exactly $180^\\circ$'],key:1,
    miss:['no_obtuse_triangles',null,'equilateral_confusion','exact_sum_confusion'],
    why:['A triangle can have one obtuse angle; the claim is about having two.','Correct. The angles of a triangle add to $180^\\circ$, so the third angle would have to be negative.','Equilateral triangles have three $60^\\circ$ angles.','Adding to exactly $180^\\circ$ is normal; the contradiction is that the third angle would be negative.'],
    steps:['Assume angles $A$ and $B$ are both greater than $90^\\circ$.','Then $A + B$ is more than $180^\\circ$, so $C = 180^\\circ - A - B$ is negative.','A negative angle is impossible, so the assumption is false.']},
   {stem:'You want to prove by contradiction that a triangle cannot have two right angles. What do you assume first?',choices:['The triangle has no right angles','The triangle has exactly one right angle','The angles of the triangle add to $180^\\circ$','The triangle has two right angles'],key:3,
    miss:['assume_conclusion','assume_conclusion_variant','assume_known_fact',null],
    why:['That assumes something consistent with the claim; nothing will contradict it.','This still agrees with the claim, so it cannot lead to a contradiction.','That is a known fact you will use, not the assumption to test.','Correct. Assume the opposite of the claim, then show it is impossible.'],
    steps:['Claim: a triangle cannot have two right angles.','Opposite: it has two right angles. Then they already total $180^\\circ$, leaving $0^\\circ$ for the third angle, which is impossible.']},
   {stem:'To prove lines $p$ and $q$ do not meet, a student assumes they meet, reaches a statement that contradicts a given fact, and then writes “so $p$ and $q$ meet.” What is wrong?',choices:['The contradiction shows the assumption was false, so the conclusion is that $p$ and $q$ do not meet','Nothing; the last line reached is the conclusion','The given fact must be false, since the reasoning was correct','Nothing can be concluded from a contradiction'],key:0,
    miss:[null,'last_line_conclusion','reject_given','contradiction_useless'],
    why:['Correct. Rejecting the assumption proves the original claim.','The contradiction rejects the assumption; it does not confirm it.','Given facts are accepted; the assumption is what gets rejected.','A contradiction is exactly what lets you reject the assumption.'],
    steps:['Assumption: $p$ and $q$ meet.','This leads to a contradiction, so the assumption is false.','Therefore $p$ and $q$ do not meet.']},
  ]}),
 lessonQuiz({lesson:'quadrilaterals-and-polygons',video:'Ka82QC4QvGA',reviewed:'2026-10-08',concept:'geometry',
  keyIdea:'Quadrilaterals are sorted by their properties: a parallelogram has two pairs of parallel sides, a rectangle is a parallelogram with four right angles, a rhombus is a parallelogram with four equal sides, and a square is both.',
  watchFor:[{at:65,text:'Quadrilaterals are first split into two groups. Listen for what decides the group.'},{at:179,text:'Two definitions of one shape are compared. Note how they differ.'},{at:430,text:'Two families of shapes overlap. Watch which shape sits in both.'}],
  practice:{url:'https://www.khanacademy.org/math/7th-grade-matatag/x065dcf1640354e81:1st-quarter/x065dcf1640354e81:angles/e/classifying-shapes',label:'Classifying shapes',checked:'2026-10-08'},
  items:[
   {stem:'What makes a quadrilateral a parallelogram?',choices:['All four angles are right angles','All four sides are equal','Exactly one pair of sides is parallel','Both pairs of opposite sides are parallel'],key:3,
    miss:['rectangle_as_definition','rhombus_as_definition','trapezoid_confusion',null],
    why:['Four right angles make a rectangle, a special parallelogram.','Four equal sides make a rhombus, also a special parallelogram.','Exactly one parallel pair describes a trapezoid.','Correct. Two pairs of parallel sides define a parallelogram.'],
    steps:['Parallelogram: both pairs of opposite sides parallel.']},
   {stem:'Why is every square also a rhombus?',choices:['A square is a parallelogram whose four sides are all equal, which is exactly what a rhombus requires','Both shapes always have four right angles','A rhombus is a special kind of square','It is not; squares and rhombi are separate shapes'],key:0,
    miss:[null,'rhombus_right_angles','reversed_inclusion','exclusive_categories'],
    why:['Correct. A square meets every condition for a rhombus, and adds right angles.','A rhombus need not have right angles.','The inclusion goes the other way: a square is a special rhombus.','The families overlap; a square belongs to both rectangles and rhombi.'],
    steps:['Rhombus: a parallelogram with four equal sides.','A square has four equal sides and is a parallelogram, so it is a rhombus.']},
   {stem:'A quadrilateral has two pairs of parallel sides and four right angles, but its sides are not all equal. What is the most specific name for it?',choices:['Square','Rectangle','Rhombus','Trapezoid'],key:1,
    miss:['assume_square',null,'rhombus_confusion','trapezoid_confusion'],
    why:['A square needs four equal sides.','Correct. A parallelogram with four right angles is a rectangle.','A rhombus needs four equal sides.','It has two pairs of parallel sides, so it is a parallelogram; under the exactly-one-pair definition it is not a trapezoid.'],
    steps:['Two pairs of parallel sides: parallelogram.','Four right angles: rectangle.','Sides not all equal: not a square.']},
   {stem:'A quadrilateral has one interior angle larger than $180^\\circ$. A student calls it convex. What is the correct description?',choices:['Convex, because every four-sided shape is convex','It cannot be a quadrilateral, because quadrilaterals never have an angle over $180^\\circ$','Concave, because a convex quadrilateral has every interior angle less than $180^\\circ$','A trapezoid, because one angle is large'],key:2,
    miss:['all_convex','no_reflex_angles',null,'trapezoid_angle_confusion'],
    why:['Some quadrilaterals look caved in; those are not convex.','A caved-in quadrilateral still has four sides and four angles.','Correct. An interior angle over $180^\\circ$ makes it concave.','Trapezoids are defined by parallel sides, not by a large angle.'],
    steps:['Convex: all interior angles less than $180^\\circ$.','One angle over $180^\\circ$: concave.']},
  ]}),
];
