import {lessonQuiz} from './author.ts';

/** UPCAT Mathematics: Algebra and functions. Original draft items written from Khan's
 * timestamped caption transcripts, read 2026-10-08; pending subject review.
 * Receipts: docs/THIRD_PARTY_MATERIALS.md, "Lesson quiz caption reviews". */
export const MATH_ALGEBRA=[
 lessonQuiz({lesson:'algebraic-expressions-and-laws-of-exponents',video:'zM_p7tfWvLU',reviewed:'2026-10-08',
  keyIdea:'An exponent counts repeated multiplication, so multiplying powers of one base adds the exponents, a power of a power multiplies them, and a power of a product applies to every factor.',
  watchFor:[{at:15,text:'A tempting wrong reading of a small power is named. Notice why it is wrong.'},{at:274,text:'Two powers of the same base are multiplied. Count the factors before using any shortcut.'},{at:434,text:'A power is raised to another power. Watch how writing it out explains the rule.'}],
  practice:{url:'https://www.khanacademy.org/math/als-k-to-12-math/x54b4346ef80b5dcc:performance-standard-e/x54b4346ef80b5dcc:exponents/e/multiply-powers',label:'Multiply powers',checked:'2026-10-08'},
  items:[
   {stem:'What does $2^3$ mean?',choices:['$2 \\times 3$, which is $6$','$2 \\times 2 \\times 2$, which is $8$','$3 \\times 3$, which is $9$','$2 + 2 + 2$, which is $6$'],key:1,
    miss:['exponent_as_multiplier',null,'swap_base_exponent','repeated_addition'],
    why:['The exponent is not a second factor. It says how many times the base is used as a factor.','Correct. The base $2$ is multiplied by itself $3$ times.','This swaps the base and the exponent: $3^2$, not $2^3$.','Repeated addition is multiplication by $3$. An exponent means repeated multiplication.'],
    steps:['$2^3$ means $2$ used as a factor $3$ times.','$2 \\times 2 \\times 2 = 8$.']},
   {stem:'Why is $6^3 \\times 6^6$ equal to $6^9$?',choices:['There are $3$ factors of $6$ followed by $6$ more, so $6$ is a factor $3 + 6 = 9$ times','When powers are multiplied, their exponents are multiplied','The bases multiply as well, so the result is really $36^9$','It is a rule to memorise; counting factors cannot explain it'],key:0,
    miss:[null,'multiply_exponents','multiply_bases','rule_without_reason'],
    why:['Correct. Writing out both powers shows nine factors of $6$ in a row.','Multiplying exponents would give $6^{18}$, which has twice as many factors as there really are.','The base stays $6$; every factor in the product is still a $6$.','Counting the factors is exactly what explains the rule.'],
    steps:['$6^3 = 6 \\times 6 \\times 6$ and $6^6$ is six more factors of $6$.','Altogether $6$ is a factor $9$ times: $6^{3 + 6} = 6^9$.']},
   {stem:'Simplify $(2x)^3 \\cdot x^4$.',choices:['$2x^7$','$8x^{12}$','$6x^7$','$8x^7$'],key:3,
    miss:['power_not_applied_to_coefficient','multiply_exponents','exponent_as_multiplier',null],
    why:['The cube applies to the $2$ as well as the $x$: $2^3 = 8$.','When multiplying $x^3$ by $x^4$, add the exponents; do not multiply them.','$2^3$ is $8$, not $2 \\times 3$.','Correct. $(2x)^3 = 2^3x^3 = 8x^3$, and $8x^3 \\cdot x^4 = 8x^7$.'],
    steps:['A power of a product: $(2x)^3 = 2^3 \\cdot x^3 = 8x^3$.','Same base, multiply: $x^3 \\cdot x^4 = x^{3 + 4} = x^7$.','Result: $8x^7$.']},
   {stem:'A student writes $(a^3)^4 = a^7$. What is the correct simplification?',choices:['$a^7$; the exponents add','$a^{81}$; the exponent is raised to the power','$a^{12}$; the exponents multiply','$4a^3$; the outer exponent multiplies the term'],key:2,
    miss:['add_for_power_of_power','power_the_exponent',null,'exponent_as_multiplier'],
    why:['Adding exponents is for multiplying two powers of the same base, such as $a^3 \\cdot a^4$.','$3^4 = 81$, but the rule multiplies the exponents rather than raising one to the other.','Correct. $(a^3)^4$ is four factors of $a^3$, so $a^{3 + 3 + 3 + 3} = a^{12}$.','The outer exponent means repeated multiplication of $a^3$, not multiplying by $4$.'],
    steps:['$(a^3)^4 = a^3 \\cdot a^3 \\cdot a^3 \\cdot a^3$.','Add the exponents: $3 + 3 + 3 + 3 = 12$, so the result is $a^{12}$.']},
  ]}),
 lessonQuiz({lesson:'polynomials-special-products-and-factoring',video:'JX5Zvh6swmo',reviewed:'2026-10-08',
  keyIdea:'A trinomial such as $x^2 + 6x + 9$ is a perfect square when its constant is $b^2$ and its middle coefficient is $2b$; then it factors as $(x + b)^2$, because $(a + b)^2 = a^2 + 2ab + b^2$.',
  watchFor:[{at:12,text:'Find two numbers with the needed product and sum. Notice that they turn out to be equal.'},{at:79,text:'Three features of the expression are pointed out. Note all three.'},{at:129,text:'A tempting shortcut for squaring a sum is rejected. Watch the distributing that shows why.'}],
  practice:{url:'https://www.khanacademy.org/math/8th-grade-math-revised-k-to-10-3-terms/x39ed6d789992bb2a:unit-1/x39ed6d789992bb2a:factoring-polynomials/e/intro-to-factoring-perfect-squares',label:'Perfect squares intro',checked:'2026-10-08'},
  items:[
   {stem:'Which feature tells you that $x^2 + bx + c$ is a perfect square trinomial?',choices:['$b$ is a perfect square','$c$ is twice $b$','$c$ is a perfect square and $b$ is twice its square root','All three coefficients are even'],key:2,
    miss:['wrong_term_square','reversed_relation',null,'even_coefficients'],
    why:['The squared number appears as the constant, not as the middle coefficient.','The relationship runs the other way: the middle coefficient is twice the square root of the constant.','Correct. For $x^2 + 6x + 9$: $9 = 3^2$ and $6 = 2 \\times 3$.','$x^2 + 6x + 9$ is a perfect square with odd coefficients, so evenness is not the test.'],
    steps:['$(x + k)^2 = x^2 + 2kx + k^2$.','So the constant must be $k^2$ and the middle coefficient $2k$.']},
   {stem:'Why is $(a + 7)^2$ not equal to $a^2 + 49$?',choices:['Squaring means $(a + 7)(a + 7)$, and distributing gives two middle terms, $7a + 7a = 14a$','It is equal, because squaring distributes over addition','The $49$ should be $14$, because $7$ is doubled','It should be $a^2 + 7a + 49$, with one middle term'],key:0,
    miss:[null,'square_distributes','doubled_constant','single_cross_term'],
    why:['Correct. $(a + 7)^2 = a^2 + 7a + 7a + 49 = a^2 + 14a + 49$.','Squaring does not distribute over a sum. Try $a = 1$: $(1 + 7)^2 = 64$, but $1 + 49 = 50$.','The constant is $7^2 = 49$. Doubling produces the middle coefficient, $14$.','Distributing twice produces $7a$ twice, so the middle term is $14a$.'],
    steps:['$(a + 7)^2 = (a + 7)(a + 7)$.','Distribute: $a^2 + 7a + 7a + 49$.','Combine: $a^2 + 14a + 49$.']},
   {stem:'Factor $y^2 + 18y + 81$.',choices:['$(y + 81)^2$','$(y + 18)^2$','$(y + 9)(y - 9)$','$(y + 9)^2$'],key:3,
    miss:['forgot_square_root','used_middle_coefficient','difference_of_squares',null],
    why:['$(y + 81)^2$ would have constant $81^2$. Use the square root of $81$, which is $9$.','$(y + 18)^2$ expands to $y^2 + 36y + 324$.','$(y + 9)(y - 9) = y^2 - 81$, with no middle term.','Correct. $81 = 9^2$ and $18 = 2 \\times 9$, so the trinomial is $(y + 9)^2$.'],
    steps:['Constant: $81 = 9^2$.','Middle: $18 = 2 \\times 9$, so it is a perfect square.','$y^2 + 18y + 81 = (y + 9)^2$.']},
   {stem:'Is $x^2 + 8x + 64$ a perfect square trinomial?',choices:['Yes; it factors as $(x + 8)^2$','No; $64 = 8^2$, but the middle coefficient would have to be $2 \\times 8 = 16$','Yes, because $8 \\times 8 = 64$','No, because $64$ is not a perfect square'],key:1,
    miss:['constant_only_check',null,'product_check','wrong_reason'],
    why:['$(x + 8)^2 = x^2 + 16x + 64$, which has a different middle term.','Correct. Both conditions must hold. The constant is a square, but $8 \\ne 16$.','A square constant is only one of the two conditions; the middle coefficient must also be $2 \\times 8$.','$64 = 8^2$ is a perfect square. The middle coefficient is what fails.'],
    steps:['Check the constant: $64 = 8^2$.','Check the middle coefficient: it should be $2 \\times 8 = 16$, but it is $8$.','So it is not a perfect square trinomial.']},
  ]}),
 lessonQuiz({lesson:'rational-expressions',video:'7Uos1ED3KHI',reviewed:'2026-10-08',concept:'rational_expressions',chapter:'m_polynomials',
  keyIdea:'Factor the numerator and denominator, cancel a common factor, and keep the condition that excludes any value that made the original denominator zero.',
  watchFor:[{at:39,text:'A number fraction is reduced first. Watch for the common factor that cancels.'},{at:97,text:'Both parts of an algebraic fraction are factored. Find what they share.'},{at:201,text:'After cancelling, a warning follows. Listen for the condition that must be added.'}],
  practice:{url:'https://www.khanacademy.org/math/pisa-2025-math-supplement/x092b0b93d51c9e96:1/x092b0b93d51c9e96:untitled-2/e/simplifying_rational_expressions_2',label:'Reduce rational expressions to lowest terms',checked:'2026-10-08'},
  items:[
   {stem:'When a rational expression is reduced to lowest terms, what is the first step?',choices:['Factor the numerator and the denominator','Cancel any terms that look the same','Multiply both parts by the denominator','Substitute $0$ for the variable'],key:0,
    miss:[null,'cancel_terms','clear_denominator','substitute_zero'],
    why:['Correct. Only common factors cancel, so you need the factored forms to see them.','Matching terms that are added cannot be cancelled; only whole factors can.','Multiplying the numerator and denominator by the same thing does not reduce the expression.','Substituting one value tests a single number; it does not simplify the expression.'],
    steps:['Factor both parts, for example $9x + 3 = 3(3x + 1)$ and $12x + 4 = 4(3x + 1)$.','Cancel the common factor $3x + 1$.']},
   {stem:'After writing $\\frac{x^2 - 9}{5x + 15}$ as $\\frac{x - 3}{5}$, why must the condition $x \\ne -3$ be added?',choices:['Because $x - 3$ equals zero when $x = 3$','The original expression is undefined at $x = -3$, so the simplified form must exclude it to be truly equal','Because cancelling is not allowed with negative numbers','It is not needed; once simplified, the two expressions agree everywhere'],key:1,
    miss:['wrong_excluded_value',null,'negatives_block_cancel','ignore_domain'],
    why:['A zero numerator is allowed. The excluded value comes from the original denominator.','Correct. $5x + 15 = 0$ when $x = -3$, so the original is undefined there while $\\frac{x - 3}{5}$ is not.','Cancelling common factors works regardless of sign.','The simplified form is defined at $x = -3$ but the original is not, so without the condition they differ there.'],
    steps:['$\\frac{x^2 - 9}{5x + 15} = \\frac{(x + 3)(x - 3)}{5(x + 3)}$.','The original denominator is zero at $x = -3$.','So $\\frac{x - 3}{5}$ with $x \\ne -3$.']},
   {stem:'Simplify $\\frac{6x + 12}{9x + 18}$.',choices:['$\\frac{2}{3}$, for every value of $x$','$\\frac{2}{3}$, with $x \\ne 2$','$\\frac{2}{3}$, with $x \\ne -2$','It cannot be simplified'],key:2,
    miss:['ignore_domain','sign_error_excluded',null,'no_common_factor'],
    why:['At $x = -2$ the original denominator is zero, so the expressions are not equal there.','The denominator $9(x + 2)$ is zero at $x = -2$, not $x = 2$.','Correct. $\\frac{6(x + 2)}{9(x + 2)} = \\frac{2}{3}$, excluding $x = -2$.','Both parts share the factor $x + 2$ once you factor out $6$ and $9$.'],
    steps:['Factor: $6x + 12 = 6(x + 2)$ and $9x + 18 = 9(x + 2)$.','Cancel $x + 2$: $\\frac{6}{9} = \\frac{2}{3}$.','Exclude $x = -2$.']},
   {stem:'A student cancels the $x$ in $\\frac{x + 4}{x + 7}$ and writes $\\frac{4}{7}$. What is wrong?',choices:['Nothing; equal letters may always cancel','They should have cancelled the numbers instead, leaving $\\frac{x}{x}$','The answer is right but needs the condition $x \\ne -7$','Only common factors cancel; here $x$ is a term being added, not a factor of the whole numerator and denominator'],key:3,
    miss:['cancel_terms','cancel_numbers','domain_only',null],
    why:['Try $x = 1$: $\\frac{5}{8}$ is not $\\frac{4}{7}$, so the cancelling changed the value.','Numbers that are added cannot be cancelled either.','The cancellation itself is invalid, so adding a condition does not fix it.','Correct. Neither part factors to share $x$, so the expression is already in lowest terms.'],
    steps:['Cancelling divides the numerator and denominator by the same factor.','$x + 4$ and $x + 7$ have no common factor, so nothing cancels.']},
  ]}),
 lessonQuiz({lesson:'radicals',video:'74iuGIaBgRc',reviewed:'2026-10-08',concept:'radicals',chapter:'m_polynomials',
  keyIdea:'Pull perfect-square factors out of a square root using $\\sqrt{ab} = \\sqrt{a}\\sqrt{b}$, then combine terms with the same root the way you combine like terms.',
  watchFor:[{at:36,text:'Look for the perfect square hiding inside each number under the root.'},{at:111,text:'Two terms with the same root are combined. Think of the root as the thing being counted.'},{at:201,text:'Two roots are multiplied into one. Listen for the exponent property that justifies it.'}],
  practice:{url:'https://www.khanacademy.org/math/10th-grade-math-revised-k-to-10-3-terms/x06a77af3c81397cf:second-quarter/x06a77af3c81397cf:radical-expressions/e/simplifying_radicals',label:'Simplify square roots',checked:'2026-10-08'},
  items:[
   {stem:'Which rewriting simplifies $\\sqrt{40}$ correctly?',choices:['$\\sqrt{4} + \\sqrt{10}$','$\\sqrt{20 \\times 2} = 20\\sqrt{2}$','$4\\sqrt{10}$','$\\sqrt{4 \\times 10} = 2\\sqrt{10}$'],key:3,
    miss:['product_as_sum','non_square_extracted','forgot_root_of_square',null],
    why:['$40 = 4 \\times 10$ is a product, so the root splits into a product, not a sum.','$20$ is not a perfect square, so it cannot come out of the root as $20$.','The $4$ comes out as its square root, $2$.','Correct. $4$ is a perfect square factor, and $\\sqrt{4} = 2$.'],
    steps:['$40 = 4 \\times 10$, and $4$ is a perfect square.','$\\sqrt{40} = \\sqrt{4}\\sqrt{10} = 2\\sqrt{10}$.']},
   {stem:'Why does $3\\sqrt{10} - 2\\sqrt{10}$ equal $\\sqrt{10}$?',choices:['The numbers under the roots subtract too, leaving $1\\sqrt{0}$','$3\\sqrt{10}$ means $\\sqrt{30}$, and $\\sqrt{30} - \\sqrt{20}$ is about $\\sqrt{10}$','Both terms count the same thing, $\\sqrt{10}$; three of it minus two of it leaves one','Any two square roots combine by subtracting the numbers in front'],key:2,
    miss:['subtract_radicands','coefficient_inside',null,'unlike_radicals_combine'],
    why:['The root is the thing being counted, like a unit; it does not change.','$3\\sqrt{10}$ means $3$ times $\\sqrt{10}$, not $\\sqrt{30}$.','Correct. This is like $3k - 2k = k$ with $k = \\sqrt{10}$.','Only like roots combine this way; $\\sqrt{2} + \\sqrt{3}$ does not simplify.'],
    steps:['Factor out the common root: $\\sqrt{10}(3 - 2)$.','$3 - 2 = 1$, so the result is $\\sqrt{10}$.']},
   {stem:'Simplify $\\sqrt{75} + \\sqrt{12}$.',choices:['$7\\sqrt{3}$','$\\sqrt{87}$','$29\\sqrt{3}$','$10\\sqrt{3}$'],key:0,
    miss:[null,'add_radicands','square_not_rooted','multiply_coefficients'],
    why:['Correct. $\\sqrt{75} = 5\\sqrt{3}$ and $\\sqrt{12} = 2\\sqrt{3}$, so the sum is $7\\sqrt{3}$.','Roots do not add by adding the numbers inside.','This brings out $25$ and $4$ themselves instead of their roots, $5$ and $2$.','Like terms add their coefficients: $5 + 2 = 7$, not $5 \\times 2$.'],
    steps:['$\\sqrt{75} = \\sqrt{25 \\times 3} = 5\\sqrt{3}$.','$\\sqrt{12} = \\sqrt{4 \\times 3} = 2\\sqrt{3}$.','$5\\sqrt{3} + 2\\sqrt{3} = 7\\sqrt{3}$.']},
   {stem:'A student writes $\\sqrt{9 + 16} = \\sqrt{9} + \\sqrt{16} = 7$. What is the correct value, and why?',choices:['$7$, because a root splits over a sum','$5$, because $\\sqrt{9 + 16} = \\sqrt{25}$; a root splits over a product, not over a sum','$25$, because the root and the sum cancel','$12.5$, half of $25$'],key:1,
    miss:['root_over_sum',null,'dropped_root','halving_as_root'],
    why:['The rule $\\sqrt{ab} = \\sqrt{a}\\sqrt{b}$ is for products only.','Correct. Add first, then take the root: $\\sqrt{25} = 5$.','The root still applies to the sum, $25$.','Halving is not taking a square root; $5 \\times 5 = 25$.'],
    steps:['Add inside the root: $9 + 16 = 25$.','$\\sqrt{25} = 5$.','Splitting the root over a sum would give $7$, which is wrong.']},
  ]}),
 lessonQuiz({lesson:'linear-equations-and-inequalities',video:'_y_Q3_B2Vh8',reviewed:'2026-10-08',
  keyIdea:'Treat an equation like a balanced scale: whatever you do to one side, do to the other, so undo the added number first and then undo the multiplication.',
  watchFor:[{at:27,text:'Before solving, the scale is turned into an equation. Try writing it yourself first.'},{at:108,text:'The small blocks are removed. Notice what must happen on the other side.'},{at:201,text:'One unknown is isolated from three. Watch what fraction of each side is kept.'}],
  practice:{url:'https://www.khanacademy.org/math/8th-grade-math-revised-k-to-10-3-terms/x39ed6d789992bb2a:2nd-quarter/x39ed6d789992bb2a:linear-equations-in-one-variable/e/linear_equations_2',label:'Two-step equations',checked:'2026-10-08'},
  items:[
   {stem:'Three unknown masses of $x$ kg and two $1$ kg blocks balance fourteen $1$ kg blocks. Which equation matches the scale?',choices:['$5x = 14$','$3x + 2 = 14$','$3x = 14 + 2$','$x + 2 = 14$'],key:1,
    miss:['combined_unlike',null,'wrong_side','dropped_coefficient'],
    why:['The $1$ kg blocks are not unknown masses, so $3x$ and $2$ cannot be combined.','Correct. The left pan holds $3x$ kg plus $2$ kg; the right pan holds $14$ kg.','The $2$ kg sits on the left pan with the unknowns, not on the right.','There are three unknown masses, so the left side has $3x$.'],
    steps:['Left pan: three masses of $x$ kg and $2$ kg, so $3x + 2$.','Right pan: $14$ kg.','Balanced: $3x + 2 = 14$.']},
   {stem:'Why must you subtract $2$ from both sides rather than only the left?',choices:['Because subtraction must always be done twice','To make both sides equal to zero','Because the right side is always larger','Removing mass from only one side would unbalance the scale, so the sides would no longer be equal'],key:3,
    miss:['ritual_steps','zero_both_sides','bigger_side',null],
    why:['The point is not repeating a step; it is keeping the two sides equal.','The goal is to isolate $x$, not to make each side zero.','Which side is larger is irrelevant; the sides are equal.','Correct. Doing the same thing to both sides keeps the balance, so the equation stays true.'],
    steps:['Start balanced: $3x + 2 = 14$.','Take $2$ from both pans: $3x = 12$, still balanced.']},
   {stem:'Solve $4x + 5 = 33$.',choices:['$9.5$','$28$','$7$','$3.25$'],key:2,
    miss:['added_instead_of_subtracting','stopped_after_one_step',null,'divide_before_subtract'],
    why:['Adding $5$ to $33$ gives $38$; the $5$ must be subtracted to undo it.','$28$ is $4x$, not $x$. One more step remains.','Correct. Subtract $5$: $4x = 28$. Divide by $4$: $x = 7$.','This divides only $33$ by $4$ and then subtracts $5$; every term must be divided.'],
    steps:['Subtract $5$ from both sides: $4x = 28$.','Divide both sides by $4$: $x = 7$.','Check: $4 \\times 7 + 5 = 33$.']},
   {stem:'To solve $3x + 2 = 14$, a student divides only the $3x$ by $3$ and writes $x + 2 = 14$. What went wrong?',choices:['A division must apply to every term on both sides; subtracting $2$ first gives $3x = 12$, so $x = 4$','Nothing; it leads to $x = 12$','They should have multiplied both sides by $3$','They should have divided both sides by $14$'],key:0,
    miss:[null,'partial_division','inverse_confusion','wrong_divisor'],
    why:['Correct. Undo the addition first, then divide both whole sides by $3$.','$x = 12$ does not check: $3 \\times 12 + 2 = 38$, not $14$.','Multiplying by $3$ makes the coefficient larger; dividing undoes it.','Dividing by $14$ does not isolate $x$.'],
    steps:['Subtract $2$ from both sides: $3x = 12$.','Divide both sides by $3$: $x = 4$.']},
  ]}),
 lessonQuiz({lesson:'systems-of-linear-equations',video:'2EwPpga_XPw',reviewed:'2026-10-08',
  keyIdea:'In substitution, solve one equation for a variable, put that expression in place of the variable in the other equation, and solve the single equation that remains.',
  watchFor:[{at:39,text:'One equation is chosen to solve for a variable. Notice which variable it gives.'},{at:132,text:'The expression replaces the variable. Watch exactly where it goes.'},{at:258,text:'Compare this result with the answer from the earlier method.'}],
  practice:{url:'https://www.khanacademy.org/math/8th-grade-math-revised-k-to-10-3-terms/x39ed6d789992bb2a:3rd-quarter/x39ed6d789992bb2a:systems-of-linear-equations-in-two-variables/e/systems_of_equations_with_substitution',label:'Systems of equations with substitution',checked:'2026-10-08'},
  items:[
   {stem:'What is the first step of the substitution method?',choices:['Add the two equations together','Guess a value and check it','Solve one equation for one variable in terms of the other','Set the two left sides equal to each other'],key:2,
    miss:['elimination_step','guess_check',null,'equate_left_sides'],
    why:['Adding equations is part of elimination, a different method.','Guessing may work by luck, but substitution is a systematic method.','Correct. For example, $100m + 400w = 1100$ becomes $m = -4w + 11$.','The left sides are not equal in general; only each equation’s two sides are equal.'],
    steps:['Pick an equation and isolate one variable.','That expression is then substituted into the other equation.']},
   {stem:'Why does substituting $m = -4w + 11$ into $200m + 300w = 1200$ help?',choices:['It leaves one equation with one unknown, $w$, which can be solved','It gives the value of $m$ without solving anything','It only checks that the other equation is correct','It changes the problem into a new system with different solutions'],key:0,
    miss:[null,'substitution_is_answer','check_only','changes_solution'],
    why:['Correct. Every $m$ becomes an expression in $w$, so only $w$ is unknown.','$m$ is still written in terms of $w$; you need $w$ first.','Substitution is a solving step, not just a check.','Replacing $m$ with an equal expression keeps the same solution.'],
    steps:['$200(-4w + 11) + 300w = 1200$.','$-800w + 2200 + 300w = 1200$, so $-500w = -1000$ and $w = 2$.']},
   {stem:'Solve the system $y = 2x - 1$ and $3x + y = 14$.',choices:['$x = 5$, $y = 3$','$x = 3$, $y = 7$','$x = 2.6$, $y = 6.2$','$x = 3$, $y = 5$'],key:3,
    miss:['swapped_values','sign_error_back_substitution','sign_error_substitution',null],
    why:['These values are swapped: $y = 2(5) - 1 = 9$, not $3$.','$x = 3$ is right, but $y = 2(3) - 1 = 5$, not $7$.','This substitutes $2x + 1$ instead of $2x - 1$.','Correct. $3x + (2x - 1) = 14$ gives $5x = 15$, so $x = 3$ and $y = 5$.'],
    steps:['Substitute: $3x + (2x - 1) = 14$.','$5x - 1 = 14$, so $5x = 15$ and $x = 3$.','Back-substitute: $y = 2(3) - 1 = 5$.']},
   {stem:'After substituting, a student finds $w = 2$ and reports the solution of the system as $2$. What is missing?',choices:['Nothing; one value solves a system','The value of $m$: substitute $w = 2$ into $m = -4w + 11$ to get $m = 3$','The value of $m$, which must equal $w$, so $m = 2$','A second solution by elimination to confirm it'],key:1,
    miss:['one_value_enough',null,'assume_equal','must_use_both_methods'],
    why:['A system in two unknowns needs both values.','Correct. $m = -4(2) + 11 = 3$, and $(m, w) = (3, 2)$ satisfies both equations.','Nothing says $m$ and $w$ are equal; substitute to find $m$.','Checking another way is optional; finding $m$ is not.'],
    steps:['$m = -4(2) + 11 = 3$.','Check: $200(3) + 300(2) = 1200$ and $100(3) + 400(2) = 1100$.']},
  ]}),
];
