import {lessonQuiz} from './author.ts';

/** UPCAT Science: Chemistry. Original draft items written from Khan's timestamped caption
 * transcripts, read 2026-10-08; pending subject review.
 * Receipts: docs/THIRD_PARTY_MATERIALS.md, "Lesson quiz caption reviews". */
export const SCIENCE_CHEMISTRY=[
 lessonQuiz({lesson:'matter-its-properties-and-changes',video:'n5cZ5CWuUJA',reviewed:'2026-10-08',concept:'matter_changes',chapter:'s_moles',
  keyIdea:'A physical change, such as melting or boiling, changes properties without changing composition, while a chemical change, such as burning or rusting, breaks and forms chemical bonds to make new substances.',
  watchFor:[{at:14,text:'Two kinds of change are defined. Note what each one does to composition.'},{at:66,text:'Melting ice is written as an equation. Check whether the molecules change.'},{at:143,text:'Burning propane is written out. Watch what happens to the bonds.'}],
  practice:{url:'https://www.khanacademy.org/science/als-k-to-12-science/x46c2fc9f8e023990:4th-quarter/x46c2fc9f8e023990:identifying-changes-in-matter-physical-and-chemical-transformations/e/physical-and-chemical-change',label:'Physical and chemical changes',checked:'2026-10-08'},
  items:[
   {stem:'What makes a change chemical rather than physical?',choices:['The substance changes state, for example from solid to liquid','The composition changes, because chemical bonds break and new ones form','The change involves heat','The change looks dramatic'],key:1,
    miss:['state_change_as_chemical',null,'heat_means_chemical','appearance_decides'],
    why:['Changes of state keep the same molecules, so they are physical.','Correct. New substances with new bonds mean a chemical change.','Melting ice also involves heat but is physical.','Appearance can mislead; composition decides.'],
    steps:['Ask: are the same molecules present afterwards?','If bonds broke and new substances formed, it is a chemical change.']},
   {stem:'Why is boiling water a physical change?',choices:['Because bubbles appear','Because the water breaks apart into hydrogen and oxygen gases','Because steam is a different substance from water','Only the forces between water molecules are overcome; each molecule still has one oxygen bonded to two hydrogens'],key:3,
    miss:['bubbles_as_reason','boiling_decomposes','steam_new_substance',null],
    why:['Bubbles appear in both kinds of change, so they do not decide it.','The bubbles in boiling water are water vapour, not hydrogen and oxygen.','Steam is still $\\mathrm{H_{2}O}$, just in the gas state.','Correct. The covalent bonds inside each molecule stay intact.'],
    steps:['Liquid $\\mathrm{H_{2}O}$ becomes gaseous $\\mathrm{H_{2}O}$.','No bonds within molecules break, so the change is physical.']},
   {stem:'Which of these is a chemical change?',choices:['A piece of wood burning to ash and smoke','Ice cream melting in the sun','Sugar dissolving in water','A glass bottle breaking into pieces'],key:0,
    miss:[null,'state_change_as_chemical','dissolving_as_chemical','shape_change_as_chemical'],
    why:['Correct. Burning, like the propane in the video, forms new substances.','Melting is a change of state.','The sugar molecules are still sugar, spread through the water.','Broken glass is still glass.'],
    steps:['Burning is combustion: bonds break and new products such as carbon dioxide form.']},
   {stem:'A student says rusting is a physical change because the iron is still a solid afterwards. What is wrong?',choices:['Nothing; anything that stays solid has changed only physically','Rusting is physical because no flame or heat is given off','Iron combines with oxygen to form iron oxide, a new substance with new bonds, so it is a chemical change','Rust is just iron that has changed colour'],key:2,
    miss:['state_decides','energy_signs_needed',null,'colour_only'],
    why:['Staying solid does not rule out a new substance.','A chemical change does not need a visible flame.','Correct. Bonds break in the iron and oxygen, and new bonds form in the oxide.','Rust is a different substance, iron oxide.'],
    steps:['$4\\mathrm{Fe} + 3\\mathrm{O_{2}} \\to 2\\mathrm{Fe_{2}O_{3}}$.','A new substance forms, so rusting is chemical.']},
  ]}),
 lessonQuiz({lesson:'atomic-structure',video:'lz_gMkQr7YE',reviewed:'2026-10-08',concept:'atomic_structure',chapter:'s_moles',
  keyIdea:'Atoms contain protons and neutrons in a tiny nucleus, with electrons in a much larger electron cloud; protons carry $+1$, electrons $-1$ and neutrons no charge, and almost all of an atom’s mass is in the nucleus.',
  watchFor:[{at:26,text:'Three smaller particles are named.'},{at:50,text:'Compare the size of the electron cloud with the size of the nucleus.'},{at:90,text:'Listen for which particles have a mass of about one unit and which are far lighter.'}],
  practice:{url:'https://www.khanacademy.org/science/8th-grade-science-revised-k-to-10-3-terms/x7174210a6d38b11d:1st-quarter/x7174210a6d38b11d:atom/e/atomic-structure',label:'Atomic structure',checked:'2026-10-08'},
  items:[
   {stem:'Which particles are found in an atom’s nucleus?',choices:['Protons and electrons','Neutrons and electrons','Protons and neutrons','Only electrons'],key:2,
    miss:['electrons_in_nucleus','proton_outside',null,'electron_core'],
    why:['Electrons are outside the nucleus.','Protons are inside the nucleus, electrons outside.','Correct. Electrons are found in the electron cloud outside the nucleus.','Electrons are in the cloud around the nucleus.'],
    steps:['Nucleus: protons and neutrons. Electron cloud: electrons.']},
   {stem:'Why is nearly all of an atom’s mass in its nucleus?',choices:['Protons and neutrons each have a mass of about $1$ u, while an electron’s mass is only about $0.0005$ u','Because the nucleus takes up most of the atom’s volume','Because electrons have no mass at all','Because neutrons are far heavier than protons'],key:0,
    miss:[null,'nucleus_volume','massless_electrons','neutron_heavier'],
    why:['Correct. Electrons are roughly $2000$ times lighter than protons or neutrons.','The nucleus is tiny; the electron cloud fills most of the volume.','Electrons do have mass, just very little.','Protons and neutrons have similar masses.'],
    steps:['Proton and neutron: about $1$ u each.','Electron: about $0.0005$ u.','So the nucleus holds almost all the mass.']},
   {stem:'A neutral atom has $8$ protons and $8$ neutrons. How many electrons does it have, and what is its approximate mass?',choices:['$16$ electrons, about $16$ u','$8$ electrons, about $16$ u','$8$ electrons, about $24$ u','$0$ electrons, about $16$ u'],key:1,
    miss:['electrons_equal_mass',null,'electrons_count_in_mass','neutral_means_none'],
    why:['The electron count matches the protons, not the total mass number.','Correct. Neutral means as many electrons as protons, and the mass comes from protons and neutrons.','Electrons add almost nothing to the mass.','Neutral means the charges cancel, so there are $8$ electrons.'],
    steps:['Neutral: electrons equal protons, so $8$.','Mass: about $8 + 8 = 16$ u.']},
   {stem:'A student says the electron cloud must hold most of an atom’s mass because it fills most of the atom’s volume. What is wrong?',choices:['Nothing; the larger part always holds more mass','The nucleus fills most of the volume, so it has most of the mass','Electrons and protons have equal mass, so the mass is shared evenly','Volume and mass are different: the cloud is large but electrons are very light, so the mass is in the small nucleus'],key:3,
    miss:['size_equals_mass','nucleus_volume','equal_masses',null],
    why:['A large region can contain very little mass.','The electron cloud can be about $100{,}000$ times larger than the nucleus.','An electron is far lighter than a proton.','Correct. Taking up space is not the same as having mass.'],
    steps:['Most of the volume: electron cloud.','Most of the mass: nucleus.']},
  ]}),
 lessonQuiz({lesson:'the-periodic-table-and-periodic-trends',video:'q--2WP8wXtk',reviewed:'2026-10-08',concept:'periodic_trends',chapter:'s_moles',
  keyIdea:'Atomic radius generally decreases across a period, because more protons pull the same outer shell inward, and increases down a group, because each period adds a shell; the largest atoms are at the bottom left and the smallest at the top right.',
  watchFor:[{at:65,text:'Electron orbits are rejected. Listen for what replaces them and why that makes size hard to define.'},{at:273,text:'Pause and predict how size changes from potassium to krypton.'},{at:500,text:'Now move down a group. Predict the trend before it is explained.'}],
  practice:{url:'https://www.khanacademy.org/science/strengthened-shs-chemistry-1/x174677b2bfa4bea2:1st-quarter/x174677b2bfa4bea2:periodic-trends-atomic-radius/e/apply-atomic-radii-trends',label:'Apply: Atomic radii trends',checked:'2026-10-08'},
  items:[
   {stem:'How does atomic radius generally change across a period, from left to right?',choices:['It increases','It stays the same','It doubles with each element','It decreases'],key:3,
    miss:['across_increases','no_trend','doubling',null],
    why:['More electrons across a period do not mean a bigger atom; the extra protons pull harder.','There is a clear general trend.','The change is gradual, not doubling.','Correct. Atoms get smaller towards the right of a period.'],
    steps:['Across a period: same outer shell, more protons.','The stronger pull makes the atoms smaller.']},
   {stem:'Why is a krypton atom smaller than a potassium atom, even though both have outer electrons in the fourth shell?',choices:['Krypton has fewer electrons','Krypton has many more protons pulling on the same outer shell, drawing it closer to the nucleus','Krypton has fewer shells','Noble gases have no outer electrons'],key:1,
    miss:['fewer_electrons',null,'fewer_shells','noble_empty'],
    why:['Krypton has $36$ electrons, potassium $19$.','Correct. $+36$ pulls harder than $+19$ on the fourth shell.','Both use four shells.','Krypton has $8$ electrons in its outer shell.'],
    steps:['Same shell, more nuclear charge.','Stronger attraction, smaller radius.']},
   {stem:'Which of these atoms is likely to be the largest: sodium, magnesium, rubidium or chlorine?',choices:['Chlorine','Magnesium','Rubidium','Sodium'],key:2,
    miss:['across_increases','more_protons_bigger',null,'period_ignored'],
    why:['Chlorine is near the right of its period, so it is small.','Magnesium is to the right of sodium in the same period, so it is smaller.','Correct. Rubidium is in group 1, further down than sodium, so it has more shells.','Sodium is in the same group as rubidium but higher up, with fewer shells.'],
    steps:['Size increases down a group and to the left.','Rubidium is the lowest and furthest left of these.']},
   {stem:'A student says hydrogen is the smallest atom because it has the fewest protons. Which atom does the video name as smallest, and why?',choices:['Helium, because its $2$ protons pull its two first-shell electrons in more strongly than hydrogen’s single proton','Hydrogen, because it has only one proton','Neon, because it is a noble gas','Lithium, because it starts a new period'],key:0,
    miss:[null,'fewest_protons_smallest','noble_smallest','period_start'],
    why:['Correct. Both use the first shell, and the larger charge in helium draws it inward.','Fewer protons means a weaker pull, not a smaller atom.','Neon has a second shell, so it is larger than helium.','Starting a new period adds a shell, making lithium larger.'],
    steps:['Hydrogen and helium both use only the first shell.','Helium’s $+2$ nucleus pulls harder, so helium is smaller.']},
  ]}),
 lessonQuiz({lesson:'chemical-bonding-and-naming-compounds',video:'ptAw20kem90',reviewed:'2026-10-08',concept:'naming_compounds',chapter:'s_moles',
  keyIdea:'Group 1 metals such as potassium tend to lose one electron to form $+1$ cations, halogens such as chlorine gain one to form $-1$ anions named with “-ide”, and in an ionic compound the cation is named first, as in potassium chloride.',
  watchFor:[{at:25,text:'Count the outer electrons of a group 1 element and predict what it loses.'},{at:102,text:'Listen for how the name changes when chlorine gains an electron.'},{at:142,text:'The compound’s name is built. Note which ion comes first.'}],
  practice:{url:'https://www.khanacademy.org/science/strengthened-shs-chemistry-1/x174677b2bfa4bea2:measurements-in-chemistry/x174677b2bfa4bea2:naming-compounds/e/naming-main-group-ionic-compounds',label:'Apply: Naming main group ionic compounds',checked:'2026-10-08'},
  items:[
   {stem:'What is the name of the ion $\\mathrm{Cl^{-}}$?',choices:['Chloride','Chlorine','Chlorate','Chlorium'],key:0,
    miss:[null,'element_name_for_ion','wrong_suffix','made_up_suffix'],
    why:['Correct. A single-element anion takes the “-ide” ending.','Chlorine is the element, not its anion.','Chlorate is a different ion that also contains oxygen.','“-ium” is not used for this anion.'],
    steps:['Chlorine gains an electron to become $\\mathrm{Cl^{-}}$, named chloride.']},
   {stem:'Why does potassium usually form a $+1$ ion?',choices:['It gains one extra electron','It has only one proton','It has one electron in its outermost shell and tends to lose it','It belongs to the halogen group'],key:2,
    miss:['gain_lose_swap','proton_count',null,'group_confusion'],
    why:['Gaining an electron would give a negative ion.','Potassium has $19$ protons.','Correct. Losing that electron leaves one more proton than electrons.','Potassium is an alkali metal in group 1.'],
    steps:['Group 1: one outer electron.','Lose it: $\\mathrm{K^{+}}$.']},
   {stem:'Sodium ions, $\\mathrm{Na^{+}}$, combine with bromide ions, $\\mathrm{Br^{-}}$. What is the compound called, and in what ratio do the ions combine?',choices:['Bromine sodide, one for one','Sodium bromine, two sodiums for each bromide','Sodium bromide, one sodium for two bromides','Sodium bromide, one sodium for each bromide'],key:3,
    miss:['anion_first','element_name_for_ion','ratio_error',null],
    why:['The cation is named first, and only the anion takes “-ide”.','The anion takes the “-ide” ending, and the charges balance one to one.','One $+1$ and one $-1$ already balance.','Correct. $+1$ and $-1$ balance one for one, and the cation is named first.'],
    steps:['Charges: $+1$ and $-1$, so the ratio is $1 : 1$.','Name: cation first, then the anion with “-ide”: sodium bromide.']},
   {stem:'A student names $\\mathrm{KCl}$ as “potassiumide chlorine”. What is the correct rule?',choices:['Name the anion first','Name the cation first with the element’s name, then the anion with the “-ide” ending: potassium chloride','Give both names the “-ide” ending','Use both element names unchanged: potassium chlorine'],key:1,
    miss:['anion_first',null,'both_ide','no_suffix'],
    why:['The cation always comes first.','Correct. Only the anion’s name changes.','The cation keeps the element’s name.','The anion needs “-ide” to show it is an ion.'],
    steps:['Cation: potassium.','Anion: chloride.','Compound: potassium chloride.']},
  ]}),
 lessonQuiz({lesson:'formulas-molar-mass-and-the-mole',video:'PAqzpZ-nMlg',reviewed:'2026-10-08',
  keyIdea:'A compound’s molar mass is the sum of its atoms’ molar masses, such as $180.16$ grams per mole for glucose, $\\mathrm{C_{6}H_{12}O_{6}}$, and the number of moles is the sample’s mass in grams divided by the molar mass.',
  watchFor:[{at:26,text:'A mole is compared with a familiar counting word. Note it.'},{at:55,text:'The molar mass of each element is read from the periodic table.'},{at:220,text:'The sample is changed into grams before dividing. Watch the units cancel.'}],
  practice:{url:'https://www.khanacademy.org/science/9th-grade-melcs/x48ae216379e0830b:2nd-quarter/x48ae216379e0830b:mole-concept/e/moles-and-molar-mass',label:'Moles and molar mass',checked:'2026-10-08'},
  items:[
   {stem:'What is the molar mass of a compound?',choices:['The mass of one molecule in kilograms','The mass of one mole of it, found by adding the molar masses of all its atoms','The number of atoms in one molecule','The mass of the sample being tested'],key:1,
    miss:['molecule_mass',null,'atom_count','sample_mass'],
    why:['Molar mass is per mole, not per molecule.','Correct. For glucose: $6(12.01) + 12(1.008) + 6(16.00)$ grams per mole.','Counting atoms is a step, but molar mass is a mass.','The sample mass is what you divide by the molar mass.'],
    steps:['Add each element’s molar mass times the number of its atoms.']},
   {stem:'Why is $1.52$ kg of glucose first changed to $1520$ g before dividing by the molar mass?',choices:['The molar mass is in grams per mole, so the mass must be in grams for the units to cancel','Because kilograms cannot be used in chemistry','Because glucose is only ever measured in grams','To make the number bigger so the answer is easier'],key:0,
    miss:[null,'no_kilograms','substance_unit','bigger_number'],
    why:['Correct. Grams divided by grams per mole leaves moles.','Kilograms are fine; they just need converting to match.','The unit depends on the calculation, not the substance.','The aim is matching units, not bigger numbers.'],
    steps:['$1.52\\ \\text{kg} = 1520\\ \\text{g}$.','$\\frac{1520}{180.16}$ gives about $8.44$ mol.']},
   {stem:'Water, $\\mathrm{H_{2}O}$, has a molar mass of about $18$ grams per mole. How many moles are in $54$ g of water?',choices:['$972$','$0.33$','$3$','$36$'],key:2,
    miss:['multiplied','inverted',null,'subtracted'],
    why:['$54 \\times 18$ multiplies instead of dividing.','$\\frac{18}{54}$ is the ratio upside down.','Correct. $\\frac{54}{18} = 3$.','Subtracting $18$ from $54$ has no meaning here.'],
    steps:['$\\text{moles} = \\frac{\\text{mass}}{\\text{molar mass}}$.','$\\frac{54}{18} = 3$ mol.']},
   {stem:'To find the molar mass of $\\mathrm{CO_{2}}$, a student adds $12.01 + 16.00 = 28.01$ grams per mole. What is the correct molar mass?',choices:['$28.01$ grams per mole, as written','$56.02$ grams per mole, doubling everything','$32.00$ grams per mole, counting oxygen only','$44.01$ grams per mole, because there are two oxygen atoms'],key:3,
    miss:['subscript_ignored','double_all','oxygen_only',null],
    why:['The subscript $2$ means two oxygen atoms.','Only the oxygen is doubled; there is one carbon.','Carbon must be included too.','Correct. $12.01 + 2(16.00) = 44.01$.'],
    steps:['One carbon: $12.01$. Two oxygens: $2 \\times 16.00 = 32.00$.','Total: $44.01$ grams per mole.']},
  ]}),
 lessonQuiz({lesson:'stoichiometry',video:'5O083FL_9u8',reviewed:'2026-10-08',
  keyIdea:'Mole ratios from a balanced equation apply to moles, not grams, so convert grams to moles, use the ratio, and convert back; the reactant that runs out first is the limiting reactant and decides how much product forms.',
  watchFor:[{at:37,text:'The balanced equation gives a ratio. Note what that ratio counts.'},{at:87,text:'A tempting shortcut is rejected. Listen for why.'},{at:438,text:'Two starting masses of propane are compared. Predict which reactant runs out.'}],
  practice:{url:'https://www.khanacademy.org/science/shs-physical-science/x0492729e402f0c6b:unit-1-name/x0492729e402f0c6b:stoichiometry/e/apply-limiting-reactants',label:'Apply: Limiting reactants',checked:'2026-10-08'},
  items:[
   {stem:'In $\\mathrm{C_{3}H_{8}} + 5\\mathrm{O_{2}} \\to 3\\mathrm{CO_{2}} + 4\\mathrm{H_{2}O}$, what does the $1 : 5$ ratio of propane to oxygen compare?',choices:['Grams of propane to grams of oxygen','Molecules of water to molecules of carbon dioxide','Moles of propane to moles of oxygen','Atoms of carbon to atoms of oxygen'],key:2,
    miss:['mass_ratio','wrong_species',null,'atom_ratio'],
    why:['A mole of each substance has a different mass, so the mass ratio is different.','That ratio would be $4 : 3$.','Correct. Coefficients count moles, or particles, not mass.','Coefficients count molecules, not individual atoms.'],
    steps:['Coefficients give mole ratios: $1$ mol propane with $5$ mol oxygen.']},
   {stem:'Why can you not find the mass of propane needed by taking one fifth of $256$ g of oxygen?',choices:['Because the equation is not balanced','Because oxygen is the limiting reactant','Because the ratio should be multiplied by five instead','The $1 : 5$ ratio is for moles, and a mole of propane has a different mass from a mole of oxygen'],key:3,
    miss:['unbalanced','limiting_confusion','inverse_ratio',null],
    why:['The equation in the video is balanced.','The issue is units, not which reactant runs out.','Multiplying would still treat grams as moles.','Correct. Convert to moles first, use the ratio, then convert back to grams.'],
    steps:['$256$ g of $\\mathrm{O_{2}}$ divided by $32.0$ grams per mole is $8$ mol.','Propane: $\\frac{8}{5} = 1.6$ mol, times $44.1$ grams per mole, is about $70.6$ g.']},
   {stem:'In $\\mathrm{N_{2}} + 3\\mathrm{H_{2}} \\to 2\\mathrm{NH_{3}}$, how many moles of hydrogen react completely with $4$ moles of nitrogen?',choices:['$\\frac{4}{3}$','$12$','$8$','$7$'],key:1,
    miss:['inverted_ratio',null,'used_product_coeff','added'],
    why:['The ratio is upside down.','Correct. $3$ mol hydrogen for each mole of nitrogen: $4 \\times 3 = 12$.','$8$ would be the moles of ammonia made.','Adding $4 + 3$ is not using the ratio.'],
    steps:['Ratio: $1$ mol $\\mathrm{N_{2}}$ to $3$ mol $\\mathrm{H_{2}}$.','$4 \\times 3 = 12$ mol $\\mathrm{H_{2}}$.']},
   {stem:'A reaction needs $70.6$ g of propane for $256$ g of oxygen. With $85.3$ g of propane and $256$ g of oxygen, a student says propane is limiting because its mass is smaller. What is correct?',choices:['Oxygen is limiting; there is more propane than the $70.6$ g needed, so oxygen runs out first and some propane is left over','Propane is limiting, because the smaller mass always runs out first','Neither is limiting, because both are present','Both run out at exactly the same moment'],key:0,
    miss:[null,'smaller_mass_limits','no_limiting','exact_ratio'],
    why:['Correct. Compare what is available with what is needed, not the raw masses.','Smaller mass does not decide; the mole ratio does.','One reactant runs out first unless the amounts match the ratio exactly.','They would only both run out if exactly $70.6$ g of propane were used.'],
    steps:['Propane needed: $70.6$ g. Propane available: $85.3$ g.','There is extra propane, so oxygen is the limiting reactant.']},
  ]}),
 lessonQuiz({lesson:'gas-laws',video:'qObcdZj8YTM',reviewed:'2026-10-08',
  keyIdea:'An ideal gas is modelled as particles that do not interact and take up no volume; combining $V \\propto \\frac{1}{P}$, $V \\propto T$ and $V \\propto n$ gives the ideal gas law, $PV = nRT$, with $T$ in kelvin.',
  watchFor:[{at:27,text:'Listen for the two simplifying assumptions about gas particles.'},{at:143,text:'A balloon is squeezed. Predict what happens to the pressure.'},{at:221,text:'A balloon goes into the fridge. Predict its size.'}],
  practice:{url:'https://www.khanacademy.org/science/10th-grade-melcs/x1cfbe2e54160ac98:4th-quarter/x1cfbe2e54160ac98:gas-laws/e/gas-laws',label:'Gas Laws',checked:'2026-10-08'},
  items:[
   {stem:'Which equation is the ideal gas law?',choices:['$P = nRTV$','$PT = nRV$','$PV = \\frac{nR}{T}$','$PV = nRT$'],key:3,
    miss:['v_multiplied','swap_t_v','inverse_t',null],
    why:['Pressure falls when volume rises, so they cannot multiply on the same side like this.','Temperature and volume are swapped.','Volume grows with temperature, so $T$ belongs in the numerator.','Correct. Pressure times volume equals moles times the gas constant times temperature.'],
    steps:['$V \\propto \\frac{nT}{P}$, so $PV = nRT$.']},
   {stem:'Why does a balloon shrink when it is put in a fridge?',choices:['Cold air leaks out through the rubber','Cooling removes moles of gas from the balloon','The cooler gas particles move less vigorously, so a smaller volume gives the same pressure as the air outside','Pressure always increases in the cold'],key:2,
    miss:['leak','moles_change',null,'pressure_cold'],
    why:['The amount of gas stays the same.','No gas is removed; the particles just slow down.','Correct. At constant pressure, volume is proportional to temperature.','Cooling lowers the particles’ energy, which would lower pressure at a fixed volume.'],
    steps:['Lower temperature at the same pressure and moles.','$V \\propto T$, so the volume decreases.']},
   {stem:'At constant temperature and amount of gas, a gas’s volume is halved. What happens to its pressure?',choices:['It doubles','It halves','It stays the same','It becomes four times as large'],key:0,
    miss:[null,'direct_pv','no_change','squared'],
    why:['Correct. $V \\propto \\frac{1}{P}$, so halving $V$ doubles $P$.','Pressure and volume move in opposite directions.','Squeezing a gas raises its pressure.','The relationship is inverse, not inverse-square.'],
    steps:['$PV$ stays constant.','If $V$ is halved, $P$ must double.']},
   {stem:'A student warms a gas from $20^\\circ\\mathrm{C}$ to $40^\\circ\\mathrm{C}$ at constant pressure and expects its volume to double. What is wrong?',choices:['Nothing; volume doubles when the Celsius temperature doubles','Temperature in the gas law must be in kelvin: $293$ K to $313$ K is only about a $7\\%$ increase','The volume would halve instead','Volume does not depend on temperature'],key:1,
    miss:['celsius_ok',null,'inverse_t','no_t'],
    why:['Celsius has an arbitrary zero, so ratios of Celsius values are meaningless here.','Correct. $\\frac{313}{293}$ is about $1.07$.','Warming a gas at constant pressure makes it expand.','At constant pressure, volume rises with temperature.'],
    steps:['Convert: $20^\\circ\\mathrm{C} = 293$ K and $40^\\circ\\mathrm{C} = 313$ K.','$\\frac{313}{293}$ is about $1.07$, about $7\\%$ more volume.']},
  ]}),
 lessonQuiz({lesson:'solutions-and-concentration',video:'L-Uhyjt8t10',reviewed:'2026-10-08',
  keyIdea:'Molarity is moles of solute per litre of solution; change the solute’s mass into moles with its molar mass and the volume into litres before dividing.',
  watchFor:[{at:17,text:'Molarity is defined. Note which volume it uses.'},{at:59,text:'Listen for why the solution’s volume is not just the water’s volume.'},{at:209,text:'The volume is changed into litres before dividing.'}],
  practice:{url:'https://www.khanacademy.org/science/shs-general-chemistry-2/x8e72aa8e889b96da:unit-1-name/x8e72aa8e889b96da:solution-chemistry-and-colligative-properties/e/molarity-calculations-exercise',label:'Molarity calculations',checked:'2026-10-08'},
  items:[
   {stem:'What is molarity?',choices:['Moles of solute per litre of solution','Grams of solute per litre of solution','Moles of solute per litre of solvent','Moles of solvent per mole of solute'],key:0,
    miss:[null,'grams_not_moles','solvent_volume','inverted_ratio'],
    why:['Correct. Molarity, written M, is moles of solute divided by litres of solution.','Molarity counts moles, not grams.','It uses the volume of the whole solution, not just the solvent.','Molarity counts solute per volume of solution.'],
    steps:['$\\text{molarity} = \\frac{\\text{moles of solute}}{\\text{litres of solution}}$.']},
   {stem:'In the example, why is the volume $250$ mL of solution rather than $250$ mL of water?',choices:['Because water takes up no volume once something dissolves in it','Molarity uses the total volume of the final solution, which includes the dissolved sodium sulfate','Because millilitres must be changed into grams','Because only the solute’s volume matters'],key:1,
    miss:['water_no_volume',null,'ml_to_g','solute_volume'],
    why:['Water still takes up space in the solution.','Correct. The solution is water plus the dissolved solute together.','Volume is changed into litres, not grams.','Molarity divides by the solution’s whole volume.'],
    steps:['Measure the final solution’s volume, $250$ mL, which is $0.250$ L.']},
   {stem:'$0.50$ mol of sodium chloride is dissolved to make $2.0$ L of solution. What is the molarity?',choices:['$1.0$ M','$4.0$ M','$2.5$ M','$0.25$ M'],key:3,
    miss:['multiplied','inverted','added',null],
    why:['$0.50 \\times 2.0$ multiplies instead of dividing.','$\\frac{2.0}{0.50}$ is upside down.','Adding moles and litres has no meaning.','Correct. $\\frac{0.50}{2.0} = 0.25$.'],
    steps:['$\\frac{0.50\\ \\text{mol}}{2.0\\ \\text{L}} = 0.25$ M.']},
   {stem:'A student dissolves $0.10$ mol of solute to make $500$ mL of solution and reports $\\frac{0.10}{500} = 0.0002$ M. What went wrong?',choices:['Nothing; millilitres are fine for molarity','The moles should first be changed into grams','The volume must be in litres: $\\frac{0.10}{0.500} = 0.20$ M','The answer should be $\\frac{500}{0.10} = 5000$ M'],key:2,
    miss:['ml_ok','grams_not_moles',null,'inverted'],
    why:['Using millilitres makes the answer $1000$ times too small.','Molarity uses moles, which were already given.','Correct. Molarity is per litre, so $500$ mL becomes $0.500$ L.','That divides volume by moles, upside down.'],
    steps:['$500$ mL $= 0.500$ L.','$\\frac{0.10}{0.500} = 0.20$ M.']},
  ]}),
 lessonQuiz({lesson:'acids-bases-and-ph',video:'J7-GewgqWUQ',reviewed:'2026-10-08',
  keyIdea:'pH is the negative base-10 logarithm of the hydrogen ion concentration, $\\mathrm{pH} = -\\log[\\mathrm{H^{+}}]$; pure water at $25^\\circ\\mathrm{C}$ has pH $7$, lower pH is acidic, higher pH is basic, and each step is a tenfold change.',
  watchFor:[{at:101,text:'The hydrogen ion concentration of pure water is given. Note its value.'},{at:288,text:'A shorter way to write these concentrations is introduced.'},{at:650,text:'Listen for what moving one step along the scale really means.'}],
  practice:{url:'https://www.khanacademy.org/science/shs-general-chemistry-2/x8e72aa8e889b96da:2nd-quarter/x8e72aa8e889b96da:acids-bases-and-ph-calculations/e/acids--bases--and-ph',label:'Acids, bases, and pH',checked:'2026-10-08'},
  items:[
   {stem:'What is the pH of pure water at $25^\\circ\\mathrm{C}$?',choices:['$0$','$7$','$14$','$1$'],key:1,
    miss:['zero_neutral',null,'max_neutral','one_neutral'],
    why:['A pH of $0$ is very strongly acidic.','Correct. $[\\mathrm{H^{+}}] = 10^{-7}$ M, so the pH is $7$.','A pH of $14$ is very strongly basic.','A pH of $1$ is strongly acidic.'],
    steps:['$-\\log(10^{-7}) = 7$.']},
   {stem:'Why does bleach, with $[\\mathrm{H^{+}}] = 10^{-12}$ M, have a higher pH than water?',choices:['Because bleach has more hydrogen ions than water','Because bleach is an acid','Because pH counts hydroxide ions directly','pH is a negative logarithm, so a lower hydrogen ion concentration gives a larger pH'],key:3,
    miss:['more_h_higher_ph','bleach_acid','ph_counts_oh',null],
    why:['Bleach has far fewer hydrogen ions than water.','A pH above $7$ means basic, not acidic.','pH is defined from the hydrogen ion concentration.','Correct. $10^{-12}$ is much smaller than $10^{-7}$, and the negative sign flips the order.'],
    steps:['$-\\log(10^{-12}) = 12$.','$12$ is above $7$, so bleach is basic.']},
   {stem:'A solution has $[\\mathrm{H^{+}}] = 10^{-3}$ M. What is its pH, and is it acidic or basic?',choices:['$-3$, acidic','$3$, basic','$3$, acidic','$11$, basic'],key:2,
    miss:['dropped_negative_sign','scale_direction',null,'poh_confusion'],
    why:['The negative in the definition makes the pH positive.','A pH below $7$ is acidic, not basic.','Correct. Below $7$ means acidic.','$14 - 3 = 11$ would be the pOH idea, not the pH.'],
    steps:['$\\mathrm{pH} = -\\log(10^{-3}) = 3$.','$3$ is below $7$, so it is acidic.']},
   {stem:'Seawater has pH $8$ and pure water pH $7$. A student says their hydrogen ion concentrations hardly differ. What is correct?',choices:['The scale is logarithmic: one pH step means seawater has one tenth the hydrogen ion concentration of pure water','They differ by $1$ M','Seawater has ten times more hydrogen ions','They differ by about $14\\%$'],key:0,
    miss:[null,'linear_scale','direction_error','percent_reading'],
    why:['Correct. Each step to the right divides the concentration by $10$.','The pH difference is not a difference in molarity.','A higher pH means fewer hydrogen ions.','pH steps are powers of ten, not percentages.'],
    steps:['pH $7$: $10^{-7}$ M. pH $8$: $10^{-8}$ M.','$10^{-8}$ is one tenth of $10^{-7}$.']},
  ]}),
 lessonQuiz({lesson:'reaction-rates-and-equilibrium',video:'CoNHV7786Hg',reviewed:'2026-10-08',concept:'reaction_rates',chapter:'s_moles',
  keyIdea:'Reactions speed up with higher reactant concentration, greater surface area, higher temperature and a catalyst, because each gives more frequent or more effective collisions; a catalyst is not used up.',
  watchFor:[{at:42,text:'Zinc meets acid of two strengths. Predict which one bubbles faster.'},{at:121,text:'The zinc is broken into pieces. Note what that changes.'},{at:240,text:'A slow reaction gets a helper. Watch what happens.'}],
  practice:{url:'https://www.khanacademy.org/science/shs-physical-science/x0492729e402f0c6b:unit-1-name/x0492729e402f0c6b:rates-of-reaction/e/understand-catalysts',label:'Understand: Catalysts',checked:'2026-10-08'},
  items:[
   {stem:'Which change speeds up the reaction between zinc and hydrochloric acid?',choices:['Using one large lump of zinc instead of small pieces','Cooling the flask','Using more concentrated acid','Using a weaker, more dilute acid'],key:2,
    miss:['surface_area_reversed','cooling_speeds',null,'dilute_faster'],
    why:['One lump has less surface area, which slows the reaction.','Cooling slows particles down.','Correct. More acid particles means more collisions with the zinc.','A more dilute acid has fewer particles to collide.'],
    steps:['Higher concentration means more frequent collisions, so a faster rate.']},
   {stem:'Why does a higher temperature usually speed up a reaction?',choices:['Heat adds more reactant particles','Particles move faster, so they collide more often and with more force','Heat turns into a catalyst','Heat lowers the concentration of the reactants'],key:1,
    miss:['heat_adds_particles',null,'heat_catalyst','heat_concentration'],
    why:['Heating does not create new reactant particles.','Correct. More frequent, more forceful collisions give a faster rate.','A catalyst is a substance; heat is not.','Heating does not lower concentration, and that would slow things anyway.'],
    steps:['Higher temperature means faster particles.','Faster particles collide more often and harder.']},
   {stem:'A cook wants charcoal to catch fire faster. Which choice uses the surface-area effect?',choices:['Breaking the charcoal into small pieces','Using one large block','Wetting the charcoal first','Adding more blocks of the same size'],key:0,
    miss:[null,'surface_area_reversed','water_helps','amount_vs_area'],
    why:['Correct. Smaller pieces expose more surface to the oxygen.','One block has the least surface for its amount.','Water slows burning instead.','More blocks of the same size do not change each block’s exposed surface.'],
    steps:['Smaller pieces mean more surface area.','More surface means more collisions, so a faster reaction.']},
   {stem:'A student says a catalyst speeds up a reaction by being used up as an extra reactant. What is correct?',choices:['The student is right; a catalyst is consumed like a reactant','A catalyst speeds a reaction by heating it','A catalyst works only on reactions that are already fast','A catalyst changes how particles collide so the reaction is faster, and it is not used up'],key:3,
    miss:['catalyst_consumed','catalyst_heats','fast_only',null],
    why:['A catalyst is left over after the reaction.','A catalyst works without raising the temperature.','Catalysts are most useful on slow reactions.','Correct. The iodide in the video sped up hydrogen peroxide’s decomposition without being used up.'],
    steps:['A catalyst affects the collisions between particles.','It is not consumed, so it can keep working.']},
  ]}),
 lessonQuiz({lesson:'heat-in-chemical-reactions',video:'NOmoGxniQoM',reviewed:'2026-10-08',concept:'reaction_energy',chapter:'s_energy',
  keyIdea:'Breaking bonds takes in energy and forming bonds releases it; a reaction that releases more than it takes in overall is exothermic, like burning magnesium, and one that takes in more is endothermic, like silver chloride breaking down in light.',
  watchFor:[{at:38,text:'Listen for what the prefix in each word means.'},{at:104,text:'Atoms are pulled apart, then allowed to snap together. Note which one needs energy.'},{at:332,text:'Watch where heat is written in each kind of equation.'}],
  practice:{url:'https://www.khanacademy.org/science/10th-grade-science-matatag/xaf924d0c475e22d4:3rd-quarter-science-of-materials/xaf924d0c475e22d4:energy-of-chemical-reactions/e/exothermic-and-endothermic-reactions',label:'Exothermic and endothermic reactions',checked:'2026-10-08'},
  items:[
   {stem:'What happens in an exothermic reaction?',choices:['Overall, energy is taken in','No energy change occurs','Only light is given out, never heat','Overall, energy is given out, often as heat'],key:3,
    miss:['endo_exo_swap','no_energy','light_only',null],
    why:['Taking in energy describes an endothermic reaction.','Every reaction involves energy changes.','Exothermic reactions usually give out heat, sometimes with light.','Correct. “Exo” means out: heat goes out.'],
    steps:['Exothermic: energy out. Endothermic: energy in.']},
   {stem:'Why does a reaction come out exothermic or endothermic?',choices:['Breaking bonds takes in energy and forming bonds gives it out; the overall balance decides','Breaking bonds releases energy and forming bonds absorbs it','It depends only on whether a flame is used','It depends on the colour of the products'],key:0,
    miss:[null,'bond_energy_reversed','flame_decides','colour_decides'],
    why:['Correct. Like the money example: more out than in is exothermic.','It is the other way round, as the magnets show.','Many exothermic reactions have no flame.','Colour does not decide the energy balance.'],
    steps:['Energy needed to break bonds, energy released forming bonds.','More released than needed: exothermic.']},
   {stem:'Adding water to calcium oxide makes the container feel warm. What type of reaction is this, and how is it written?',choices:['Endothermic, with heat written on the product side','Exothermic, with heat written on the product side','Exothermic, with heat written above the arrow','Endothermic, with heat written above the arrow'],key:1,
    miss:['endo_exo_swap',null,'notation_swap','both_wrong'],
    why:['A warm container means heat is released.','Correct. Heat is a product, so it goes with the products.','Above the arrow is the convention for heat that must be supplied.','Heat is given out here, not taken in.'],
    steps:['Warm container: heat is released.','Write heat with the products: exothermic.']},
   {stem:'A student says heating iron sulfate starts an exothermic reaction because heat is involved. What is correct?',choices:['It is exothermic, because any heated reaction releases heat','It is not a reaction, because a colour change is physical','Heat had to be supplied to make it react, so it is endothermic; supplying heat is not the same as releasing it','It is exothermic, because gases are produced'],key:2,
    miss:['heat_means_exo','colour_physical',null,'gas_means_exo'],
    why:['Needing heat means energy is taken in.','The colour change and new gases show a chemical reaction.','Correct. The reaction takes in energy, so it is endothermic.','Producing gas does not decide the energy balance.'],
    steps:['Energy supplied to start the reaction.','More energy taken in than given out: endothermic.']},
  ]}),
 lessonQuiz({lesson:'carbon-compounds-and-biochemistry',video:'FYTfo4y91TI',reviewed:'2026-10-08',concept:'organic_groups',chapter:'s_moles',
  keyIdea:'A functional group is a group of atoms with predictable chemical behaviour; alkenes have a carbon–carbon double bond, alkynes a triple bond, alcohols an $\\mathrm{OH}$ group, ethers an oxygen between two carbon groups, and amines a nitrogen.',
  watchFor:[{at:12,text:'Listen for what the letter R stands for.'},{at:164,text:'A ring with alternating double bonds is shown. Note why it gets its own group.'},{at:255,text:'Compare an alcohol with an ether. Note where the oxygen sits.'}],
  practice:{url:'https://www.khanacademy.org/science/9th-grade-melcs/x48ae216379e0830b:2nd-quarter/x48ae216379e0830b:carbon-compounds/e/identify-functional-groups-',label:'Identify the functional groups',checked:'2026-10-08'},
  items:[
   {stem:'Which functional group has a carbon–carbon triple bond?',choices:['Alkyne','Alkene','Arene','Alcohol'],key:0,
    miss:[null,'double_triple_swap','ring_confusion','oxygen_group'],
    why:['Correct. Alkynes have a triple bond, as in butyne.','Alkenes have a double bond.','Arenes are rings with alternating double bonds.','Alcohols have an $\\mathrm{OH}$ group.'],
    steps:['Double bond: alkene. Triple bond: alkyne.']},
   {stem:'Why is it useful to identify the functional groups in a molecule?',choices:['Functional groups tell you the colour of the molecule','Every functional group contains nitrogen','Functional groups stop a molecule from reacting','Molecules with the same functional group tend to react in similar, predictable ways'],key:3,
    miss:['colour','nitrogen_always','inert',null],
    why:['Functional groups describe reactivity, not colour.','Only amines in this list contain nitrogen.','Functional groups are where reactions tend to happen.','Correct. That is what makes functional groups useful.'],
    steps:['Same functional group, similar reactions.']},
   {stem:'Which name fits $\\mathrm{CH_{3}CH_{2}OH}$?',choices:['Diethyl ether, an ether','Ethene, an alkene','Ethanol, an alcohol','Ethanethiol, a thiol'],key:2,
    miss:['ether_alcohol_swap','alkene_confusion',null,'thiol_confusion'],
    why:['An ether has oxygen between two carbon groups, not an $\\mathrm{OH}$ end.','There is no carbon–carbon double bond here.','Correct. Two carbons with an $\\mathrm{OH}$ group is ethanol.','A thiol has $\\mathrm{SH}$, not $\\mathrm{OH}$.'],
    steps:['Two carbons: “eth”. $\\mathrm{OH}$ group: alcohol, “-ol”.','Name: ethanol.']},
   {stem:'A student says benzene must react like an alkene because its ring contains double bonds. What does the video say?',choices:['The student is right; any double bond makes an alkene','Arenes such as benzene react differently from alkenes, so they form a separate functional group','Benzene has no double bonds at all','Benzene is an alcohol'],key:1,
    miss:['double_bond_alkene',null,'no_double_bonds','ring_alcohol'],
    why:['Double bonds in an aromatic ring do not behave like an isolated alkene.','Correct. The alternating ring behaves differently, so it is its own group.','The ring is drawn with three alternating double bonds.','Benzene has no $\\mathrm{OH}$ group.'],
    steps:['Arene: six-carbon ring with alternating single and double bonds.','It is a separate functional group from alkenes.']},
  ]}),
 lessonQuiz({lesson:'elements-compounds-and-mixtures',video:'FNYDRzG7fuE',reviewed:'2026-10-08',concept:'matter_classification',chapter:'s_moles',
  keyIdea:'Matter has mass and takes up space; it is either a pure substance, an element or a compound with the same properties at every scale, or a mixture, which can be separated physically and is heterogeneous or homogeneous depending on how evenly it is mixed.',
  watchFor:[{at:12,text:'Matter is defined. Note both requirements.'},{at:131,text:'Pure substances are split into two kinds.'},{at:203,text:'Listen for the difference between a molecule and a compound.'}],
  practice:{url:'https://www.khanacademy.org/science/als-k-to-12-science/x46c2fc9f8e023990:4th-quarter/x46c2fc9f8e023990:distinguishing-mixtures-from-pure-substances/e/pure-substances-and-mixtures',label:'Pure substances and mixtures',checked:'2026-10-08'},
  items:[
   {stem:'Which of these is a compound?',choices:['Molecular oxygen, $\\mathrm{O_{2}}$','Water, $\\mathrm{H_{2}O}$','Neon gas','Air'],key:1,
    miss:['molecule_as_compound',null,'element_as_compound','mixture_as_compound'],
    why:['$\\mathrm{O_{2}}$ is a molecule but contains only one element.','Correct. Water has two different elements bonded together.','Neon is an element made of single atoms.','Air is a mixture of several substances.'],
    steps:['Compound: different elements chemically bonded.']},
   {stem:'Why is air a homogeneous mixture rather than a pure substance?',choices:['Because it has no mass','Because it is a single compound','It contains different substances, such as nitrogen and oxygen, that can be separated physically, and they are evenly mixed','Because its parts are easy to see separately'],key:2,
    miss:['gas_no_mass','air_compound',null,'hetero_confusion'],
    why:['Air has mass and volume, so it is matter.','Its parts are separate substances, not bonded together.','Correct. Several substances, evenly spread: a homogeneous mixture.','Easily seen separate parts would make it heterogeneous.'],
    steps:['Several substances, so a mixture.','Evenly mixed, so homogeneous.']},
   {stem:'Sand is mixed with iron filings. How is this classified?',choices:['A homogeneous mixture','A compound','An element','A heterogeneous mixture'],key:3,
    miss:['homogeneous_confusion','mixture_as_compound','element_confusion',null],
    why:['The parts are not evenly mixed at a small scale.','No new bonds form between sand and iron.','It contains more than one substance.','Correct. You can see the separate grains, and a magnet could pull out the iron.'],
    steps:['Different substances, physically separable, unevenly mixed: heterogeneous.']},
   {stem:'A student says light and sound are matter because they are real. What is correct?',choices:['Matter must have mass and take up space; light and sound are energy and waves, not matter','The student is right; anything real is matter','Only sound is matter, because it travels through air','Only light is matter, because it can be seen'],key:0,
    miss:[null,'real_is_matter','sound_matter','light_matter'],
    why:['Correct. Being real is not enough; matter has mass and volume.','Energy and waves are real but are not matter.','Sound is a wave travelling through matter, not matter itself.','Being visible does not make light matter.'],
    steps:['Matter: has mass and volume.','Light and sound: waves and energy.']},
  ]}),
 lessonQuiz({lesson:'electron-configuration-and-quantum-numbers',video:'LyFzELsUgBU',reviewed:'2026-10-08',concept:'electron_configuration',chapter:'s_moles',
  keyIdea:'Each orbital holds two electrons, so s, p, d and f subshells hold $2$, $6$, $10$ and $14$; electrons fill the lowest levels first, giving configurations such as carbon’s $1s^2 2s^2 2p^2$, shortened to $[\\mathrm{He}] 2s^2 2p^2$.',
  watchFor:[{at:38,text:'Count the orbitals in each subshell and note how many electrons each can hold.'},{at:142,text:'Lithium’s third electron needs a new home. Watch where it goes.'},{at:266,text:'A shorter notation uses a noble gas.'}],
  practice:{url:'https://www.khanacademy.org/science/strengthened-shs-chemistry-1/x174677b2bfa4bea2:1st-quarter/x174677b2bfa4bea2:electron-configurations/e/atomic-structure-and-electron-configuration',label:'Atomic structure and electron configuration',checked:'2026-10-08'},
  items:[
   {stem:'How many electrons can a p subshell hold?',choices:['$2$','$3$','$6$','$10$'],key:2,
    miss:['s_capacity','orbitals_not_electrons',null,'d_capacity'],
    why:['$2$ is the capacity of an s subshell.','$3$ is the number of p orbitals, not electrons.','Correct. Three orbitals with two electrons each.','$10$ is the capacity of a d subshell.'],
    steps:['p subshell: $3$ orbitals.','$3 \\times 2 = 6$ electrons.']},
   {stem:'Why does lithium’s third electron go into the $2s$ subshell?',choices:['The $1s$ subshell is already full with two electrons, so the next lowest-energy place is $2s$','Because $2p$ is always filled before $2s$','Because each shell can hold only one electron','Because lithium has three shells'],key:0,
    miss:[null,'p_before_s','one_per_shell','shell_per_electron'],
    why:['Correct. Lithium is $1s^2 2s^1$.','Within a shell, s fills before p.','The first shell holds two electrons.','Lithium uses two shells.'],
    steps:['$1s$ holds $2$ electrons.','The third electron goes to $2s$: $1s^2 2s^1$.']},
   {stem:'What is the electron configuration of a neutral oxygen atom, which has $8$ electrons?',choices:['$1s^2 2s^2 2p^6$','$1s^2 2p^6$','$1s^2 2s^6$','$1s^2 2s^2 2p^4$'],key:3,
    miss:['overfilled','skipped_2s','s_overfilled',null],
    why:['That totals $10$ electrons.','$2s$ fills before $2p$.','An s subshell holds only $2$ electrons.','Correct. $2 + 2 + 4 = 8$.'],
    steps:['$1s^2$: $2$ electrons. $2s^2$: $2$ more.','The remaining $4$ go into $2p$: $2p^4$.']},
   {stem:'A student writes boron, which has $5$ electrons, as $1s^2 2s^3$. What is wrong?',choices:['Nothing; it shows five electrons','An s subshell holds only $2$ electrons, so the fifth goes into $2p$: $1s^2 2s^2 2p^1$','It should be $1s^5$','It should be $1s^1 2s^2 2p^2$'],key:1,
    miss:['count_only',null,'one_shell','fill_order'],
    why:['The total is right, but $2s$ cannot hold three.','Correct. Each s subshell has a single orbital holding two electrons.','The first shell holds only two electrons.','$1s$ fills completely before electrons move on.'],
    steps:['$1s^2 2s^2$ uses $4$ electrons.','The fifth goes into $2p$: $1s^2 2s^2 2p^1$.']},
  ]}),
 lessonQuiz({lesson:'oxidation-reduction-and-electrochemistry',video:'DvYs1HILq1g',reviewed:'2026-10-08',concept:'redox',chapter:'s_moles',
  keyIdea:'Oxidation is losing electrons and reduction is gaining them; oxidation states are the charges atoms would have if every bond were ionic, such as $-2$ for oxygen and $+1$ for each hydrogen in water.',
  watchFor:[{at:37,text:'Sodium and chlorine meet. Predict which one gives up an electron.'},{at:208,text:'A convention is introduced that pretends covalent bonds are ionic.'},{at:605,text:'Two memory aids are given. Note what each letter stands for.'}],
  practice:{url:'https://www.khanacademy.org/science/shs-general-chemistry-2/x8e72aa8e889b96da:2nd-quarter/x8e72aa8e889b96da:electrochemistry/e/applications-of-electrode-potentials',label:'Applications of electrode potentials',checked:'2026-10-08'},
  items:[
   {stem:'What does it mean for an atom to be oxidised?',choices:['It gains electrons','It must gain oxygen atoms','It gains protons','It loses electrons'],key:3,
    miss:['gain_lose_swap','oxygen_required','protons',null],
    why:['Gaining electrons is reduction.','Oxidation can happen without oxygen, as with hydrogen fluoride.','Redox is about electrons, not protons.','Correct. Oxidation is loss of electrons.'],
    steps:['Oxidation is losing, reduction is gaining (OIL RIG).']},
   {stem:'Why is hydrogen said to be oxidised in hydrogen fluoride, even though no oxygen is present?',choices:['Because hydrogen gains an electron from fluorine','Fluorine is more electronegative and, treating the bond as ionic, takes hydrogen’s electron; losing electrons is oxidation','Because the term applies only when oxygen is present','Because fluorine loses an electron'],key:1,
    miss:['gain_lose_swap',null,'oxygen_required','direction_swap'],
    why:['Hydrogen loses its electron to the more electronegative fluorine.','Correct. Fluorine does to hydrogen what oxygen would do.','The word comes from oxygen but describes any loss of electrons.','Fluorine gains the electron, so it is reduced.'],
    steps:['Fluorine is more electronegative.','Hydrogen gets $+1$ and fluorine $-1$: hydrogen is oxidised.']},
   {stem:'Chlorine is more electronegative than hydrogen. What are the oxidation states in $\\mathrm{HCl}$?',choices:['Hydrogen $+1$, chlorine $-1$','Hydrogen $-1$, chlorine $+1$','Both $0$, because the bond is covalent','Hydrogen $+2$, chlorine $-2$'],key:0,
    miss:[null,'electronegativity_reversed','covalent_zero','water_values'],
    why:['Correct. The more electronegative atom is assigned the shared electrons.','The more electronegative chlorine takes the negative state.','Oxidation states pretend the bond is ionic, even though it is covalent.','One shared pair moves one electron, giving $+1$ and $-1$.'],
    steps:['Assign the bonding electrons to chlorine.','Hydrogen: $+1$. Chlorine: $-1$.']},
   {stem:'A student says oxidation states are the real charges on the atoms in a water molecule. What is correct?',choices:['The student is right; each hydrogen truly carries a full $+1$ charge','Water has no oxidation states because it is neutral overall','They are a bookkeeping tool: the bonds are covalent with partial charges, and oxidation states pretend they are fully ionic','Oxidation states are defined only for ionic compounds'],key:2,
    miss:['literal_charges','neutral_none',null,'ionic_only'],
    why:['The real charges on water’s hydrogens are only partial.','Neutral molecules still have oxidation states that add up to zero.','Correct. The real charges are partial; oxidation states are hypothetical.','They are assigned in covalent molecules too, such as water.'],
    steps:['Real bonds in water: covalent, with partial charges.','Oxidation states: $-2$ for oxygen, $+1$ for each hydrogen, as if ionic.']},
  ]}),
 lessonQuiz({lesson:'nuclear-reactions',video:'5jDFqpoTgDo',reviewed:'2026-10-08',concept:'nuclear',
  keyIdea:'In nuclear fission a heavy nucleus such as uranium-235 absorbs a neutron and splits into smaller nuclei, releasing energy and a few neutrons; those neutrons can start a chain reaction, which bombs leave uncontrolled and reactors control by absorbing neutrons and using low enrichment.',
  watchFor:[{at:74,text:'Count protons and particles on both sides to find the missing neutrons.'},{at:201,text:'Listen for where the released energy comes from, in terms of mass.'},{at:451,text:'A bomb and a reactor are compared. Note the two differences.'}],
  practice:{url:'https://www.khanacademy.org/science/hs-chemistry/x2613d8165d88df5e:nuclear-chemistry-hs/x2613d8165d88df5e:nuclear-fission/e/understand-nuclear-fission',label:'Understand: Nuclear fission',checked:'2026-10-08'},
  items:[
   {stem:'In induced nuclear fission, what starts the splitting of a uranium-235 nucleus?',choices:['Absorbing a neutron','Absorbing an electron','Heating it to a high temperature','Combining it with another nucleus'],key:0,
    miss:[null,'electron_trigger','heat_trigger','fusion_confusion'],
    why:['Correct. The extra neutron pushes an unstable nucleus over the edge.','Electrons do not trigger fission.','Fission is set off by a neutron, not by heat.','Combining nuclei is fusion, the opposite process.'],
    steps:['Uranium-235 absorbs a neutron, becomes more unstable and splits.']},
   {stem:'Why can fission continue as a chain reaction?',choices:['The energy released melts nearby uranium','The products fuse back together','Each fission releases a few neutrons that can split more uranium-235 nuclei','Each fission adds protons to nearby nuclei'],key:2,
    miss:['melting','fusion_confusion',null,'proton_transfer'],
    why:['Melting does not cause more fission.','Fission products do not fuse back.','Correct. One fission can lead to three, then nine, and so on.','Neutrons, not protons, carry the chain onward.'],
    steps:['Each fission frees $1$ to $3$ neutrons.','Those neutrons trigger more fissions.']},
   {stem:'Uranium-235 absorbs a neutron and splits into xenon-139 and strontium-95. How many neutrons are released?',choices:['$1$','$2$','$3$','$0$'],key:1,
    miss:['forgot_absorbed_neutron',null,'off_by_one','mass_conserved_exactly'],
    why:['This forgets the neutron that was absorbed.','Correct. $235 + 1 = 236$ particles, and $139 + 95 = 234$, so $2$ neutrons are left over.','Recount: $236 - 234 = 2$.','The products account for only $234$ of the $236$ particles.'],
    steps:['Before: $235 + 1 = 236$ particles.','After: $139 + 95 = 234$.','Neutrons released: $236 - 234 = 2$.']},
   {stem:'A student says a nuclear power reactor could explode like an atomic bomb because both use fission chain reactions. What is the key difference?',choices:['Reactors use fusion, not fission','Reactors use uranium-238, which splits more slowly','There is no difference; reactors are just smaller bombs','Reactors control the chain reaction by absorbing neutrons and use fuel only about $3$ to $5\\%$ enriched, unlike the roughly $90\\%$ needed for a bomb'],key:3,
    miss:['fusion_confusion','u238_fuel','no_difference',null],
    why:['Power reactors use fission.','Uranium-238 is non-fissile; the fuel still relies on uranium-235.','Control and enrichment make them very different.','Correct. Controlled, low-enrichment fission releases energy steadily.'],
    steps:['Bomb: uncontrolled chain reaction, about $90\\%$ enriched.','Reactor: neutrons absorbed to control it, about $3$ to $5\\%$ enriched.']},
  ]}),
];
