import {lessonQuiz} from './author.ts';

/** UPCAT Science: Earth science. Original draft items written from Khan's timestamped caption
 * transcripts, read 2026-10-08; pending subject review.
 * Receipts: docs/THIRD_PARTY_MATERIALS.md, "Lesson quiz caption reviews". */
export const SCIENCE_EARTH=[
 lessonQuiz({lesson:'earth-s-layers-and-composition',video:'hHteUIS0OFY',reviewed:'2026-10-08',
  keyIdea:'Earth’s layers can be described by composition (crust, mantle and core) or by how they behave (the rigid lithosphere, the putty-like asthenosphere, the rigid mesosphere, the liquid outer core and the solid inner core); deeper layers are denser, hotter and under more pressure.',
  watchFor:[{at:55,text:'The compositional layers start with the crust. Compare oceanic and continental crust.'},{at:303,text:'The mechanical layers begin. Note which two parts make up the lithosphere.'},{at:611,text:'The outer core is liquid but the inner core is solid. Listen for why.'}],
  practice:{url:'https://www.khanacademy.org/science/8th-grade-science-revised-k-to-10-3-terms/x7174210a6d38b11d:2nd-quarter-science-of-materials/x7174210a6d38b11d:continental-crust-and-oceanic-crust/e/understand-earths-layers',label:'Understand: Earth’s layers',checked:'2026-10-08'},
  items:[
   {stem:'Which layers make up the lithosphere?',choices:['The crust only','The crust and the uppermost, rigid part of the mantle','The mantle and the outer core','The asthenosphere and the mesosphere'],key:1,
    miss:['lithosphere_is_crust',null,'lithosphere_deep','lithosphere_soft_layers'],
    why:['The lithosphere also includes the cool top of the mantle.','Correct. The lithosphere is the rigid outer shell, and its plates are what move in plate tectonics.','The outer core is far below the lithosphere.','The asthenosphere lies below the lithosphere, and the mesosphere lies deeper still.'],
    steps:['Lithosphere $=$ crust $+$ the rigid top of the mantle.']},
   {stem:'Why is the inner core solid, even though it is hotter than the liquid outer core?',choices:['The inner core is made of rock rather than metal','The inner core is cooler than the outer core','The inner core is solid because it is the oldest layer','The pressure at the centre is so great that even the metals are forced to be solid'],key:3,
    miss:['inner_core_rock','inner_core_cooler','age_makes_solid',null],
    why:['The whole core is mainly iron and nickel.','Temperature keeps rising towards the centre.','Age does not decide whether a layer is solid.','Correct. Pressure wins over temperature at the centre.'],
    steps:['Outer core: hot enough to melt metal, pressure not high enough to stop it.','Inner core: pressure high enough to keep metal solid.']},
   {stem:'A drill passes through $8$ kilometres of rock beneath the sea floor before reaching the mantle. Which kind of crust did it pass through?',choices:['Oceanic crust, which is about $5$ to $10$ kilometres thick','Continental crust, which is about $5$ to $10$ kilometres thick','The asthenosphere','The mesosphere'],key:0,
    miss:[null,'swapped_crust_thickness','asthenosphere_as_crust','mesosphere_confusion'],
    why:['Correct. Rock under the oceans is thin oceanic crust.','Continental crust is thicker, about $10$ to $70$ kilometres.','The asthenosphere is part of the mantle, not crust.','The mesosphere is the deep, rigid lower mantle.'],
    steps:['Under the sea, crust is oceanic and about $5$ to $10$ kilometres thick; $8$ kilometres fits.']},
   {stem:'A student says the asthenosphere is a liquid layer of molten rock. What is wrong?',choices:['Nothing; the asthenosphere is fully liquid','The asthenosphere is the rigid outer layer','It is hot enough to flow slowly like putty, but it is not a liquid; it still carries waves that liquids do not','The asthenosphere is made of liquid iron'],key:2,
    miss:['asthenosphere_liquid','asthenosphere_rigid',null,'asthenosphere_iron'],
    why:['The video stresses that it should not be called a liquid.','The rigid outer layer is the lithosphere.','Correct. It is a soft, slowly flowing solid that the plates ride on.','Liquid iron is found in the outer core.'],
    steps:['Asthenosphere: same rock as the upper mantle, hot enough to flow slowly, not liquid.']},
  ]}),
 lessonQuiz({lesson:'rocks-and-minerals',video:'rmH4W92eHVM',reviewed:'2026-10-08',
  keyIdea:'Igneous rock forms when molten rock cools, sedimentary rock forms when sediments are deposited, compacted and cemented, and metamorphic rock forms when heat and pressure change a rock’s minerals; in the rock cycle any type can become any other.',
  watchFor:[{at:78,text:'Granite and obsidian are compared. Note where each cooled and how fast.'},{at:153,text:'Lithification is broken into steps. Note their order.'},{at:202,text:'Listen for what makes a rock metamorphic.'}],
  practice:{url:'https://www.khanacademy.org/science/5th-grade-science-revised-k-to-10-3-terms/xd90d8fbecb0e4173:3rd-quarter/xd90d8fbecb0e4173:rocks/e/understand-the-rock-cycle',label:'Understand: The rock cycle',checked:'2026-10-08'},
  items:[
   {stem:'How does igneous rock form?',choices:['Layers of sediment are pressed and cemented together','Heat and pressure change an existing rock’s minerals without melting it','Molten rock cools and becomes solid','Wind and water break rock into small pieces'],key:2,
    miss:['igneous_as_sedimentary','igneous_as_metamorphic',null,'weathering_as_formation'],
    why:['This describes sedimentary rock.','This describes metamorphic rock.','Correct. The name comes from the Latin for fiery.','This is weathering, which makes sediment, not igneous rock.'],
    steps:['Igneous: molten rock $\\to$ cools $\\to$ solid rock.']},
   {stem:'Why does granite have large crystals while obsidian has almost none?',choices:['Granite cooled quickly at the surface','Granite cooled slowly from magma underground, giving crystals time to grow; obsidian cooled quickly from lava at the surface','Obsidian is a sedimentary rock','Granite formed from lava and obsidian from magma'],key:1,
    miss:['speed_reversed',null,'obsidian_sedimentary','magma_lava_swapped'],
    why:['Quick cooling at the surface gives small crystals, as in obsidian.','Correct. Slow cooling means larger crystals.','Obsidian is igneous; it formed from lava.','It is the other way round: magma is underground, lava is at the surface.'],
    steps:['Magma: underground, slow cooling, large crystals.','Lava: surface, fast cooling, tiny crystals.']},
   {stem:'Limestone is buried deep and is heated and squeezed for a long time until its minerals change. It becomes marble. What type of rock is marble?',choices:['Igneous','Sedimentary','Still limestone, because it never melted','Metamorphic'],key:3,
    miss:['heat_means_igneous','starting_type_kept','no_change_without_melt',null],
    why:['Igneous rock needs molten rock to cool; the limestone did not melt.','Limestone was sedimentary, but changing its minerals made it metamorphic.','A rock can change type without melting.','Correct. Heat and pressure changed it without melting it.'],
    steps:['Existing rock $+$ heat and pressure $\\to$ metamorphic rock.']},
   {stem:'A student says that once a rock is sedimentary, it must stay sedimentary. What is wrong?',choices:['In the rock cycle any rock can change: sedimentary rock can be melted into igneous rock or squeezed into metamorphic rock','Nothing; each rock type is permanent','Only igneous rock can ever change','Sedimentary rock can become only igneous rock'],key:0,
    miss:[null,'rock_type_permanent','only_igneous_changes','single_path'],
    why:['Correct. Rocks keep changing over long periods of time.','Rocks keep changing; that is the rock cycle.','Every type can change.','It can also become metamorphic rock.'],
    steps:['Melt and cool $\\to$ igneous. Heat and squeeze $\\to$ metamorphic. Break down and cement $\\to$ sedimentary.']},
  ]}),
 lessonQuiz({lesson:'plate-tectonics-earthquakes-and-volcanoes',video:'Y0eWnOZpSpQ',reviewed:'2026-10-08',
  keyIdea:'At convergent boundaries plates collide: an oceanic plate pushed under a continental plate builds mountains, earthquakes and volcanoes; two oceanic plates form deep trenches and volcanic islands; and two continents jam together, pushing up ranges such as the Himalayas.',
  watchFor:[{at:43,text:'Listen for what happens to one plate when two plates ram into each other.'},{at:231,text:'The deepest trench is described. Note which two kinds of plate meet there.'},{at:304,text:'Two continents collide. Note why neither one sinks fully.'}],
  practice:{url:'https://www.khanacademy.org/science/strengthened-shs-earth-and-space-science-1/x006d5d274c051fd7:origin-and-structure-of-the-earth/x006d5d274c051fd7:a-brief-history-of-the-earth/e/plate-tectonics',label:'Plate tectonics',checked:'2026-10-08'},
  items:[
   {stem:'At most convergent boundaries, what happens to one of the plates?',choices:['It is pushed under the other plate, which is called subduction','It splits apart to make new crust','It slides sideways past the other plate','It melts completely at the surface'],key:0,
    miss:[null,'convergent_as_divergent','convergent_as_transform','melts_at_surface'],
    why:['Correct. One plate is pushed under the other.','New crust forms where plates move apart, at divergent boundaries.','Sliding past is a different kind of boundary.','The plate sinks below; it does not melt away at the surface.'],
    steps:['Convergent: plates collide, and one is usually subducted.']},
   {stem:'Why are there many volcanoes where an oceanic plate is pushed under a continental plate?',choices:['The continental plate is thinnest there','Volcanoes form only where plates move apart','Rock above the sinking plate melts into magma, which rises to the surface and erupts','Ocean water boils and builds volcanoes'],key:2,
    miss:['thin_continent','volcanoes_only_divergent',null,'boiling_ocean'],
    why:['Thickness is not the reason; magma forming above the sinking plate is.','Subduction zones also have many volcanoes.','Correct. Magma made above the subducting plate feeds volcanoes, as in the Andes.','Volcanoes are built from magma and lava, not boiling water.'],
    steps:['Subduction $\\to$ melting above the sinking plate $\\to$ magma rises $\\to$ volcanoes.']},
   {stem:'Two oceanic plates converge in the western Pacific. Which pair of features would you expect there?',choices:['A mid-ocean ridge and new sea floor','A tall range of folded mountains like the Himalayas','No features, because oceanic plates cannot collide','A deep ocean trench and a chain of volcanic islands'],key:3,
    miss:['convergent_as_divergent','continental_collision_result','no_oceanic_collision',null],
    why:['Ridges form where plates move apart.','The Himalayas formed where two continental plates met.','Oceanic plates do collide; one is subducted under the other.','Correct. The Mariana Trench and Mariana Islands formed this way.'],
    steps:['Oceanic under oceanic $\\to$ trench $+$ underwater volcanoes $\\to$ island chain.']},
   {stem:'A student says the Himalayas formed because the Indian plate sank completely under the Eurasian plate, as an ocean plate would. What is wrong?',choices:['Nothing; continental plates always sink fully','Both are continental plates, so neither is fully subducted; the crust jams together and is pushed up','The Himalayas formed at a boundary where plates move apart','The Himalayas were built by volcanoes alone'],key:1,
    miss:['continent_subducts',null,'himalaya_divergent','himalaya_volcanic'],
    why:['Continental crust does not sink fully the way oceanic crust does.','Correct. The colliding continental crust is pushed upward.','India and Eurasia are moving together, not apart.','The Himalayas were pushed up by the collision, not built by volcanoes.'],
    steps:['Continent against continent $\\to$ crust jams together $\\to$ mountains rise.']},
  ]}),
 lessonQuiz({lesson:'weathering-erosion-and-landforms',video:'xWWOHttrkWI',reviewed:'2026-10-08',concept:'weathering',chapter:'s_earth',
  keyIdea:'Weathering breaks rock apart, mechanically or chemically, and erosion carries the pieces away; larger and faster flows of water erode more, and where water slows down it deposits its sediment.',
  watchFor:[{at:53,text:'Two processes are separated. Note which one breaks rock and which one carries it.'},{at:120,text:'Listen for how the size and speed of a river affect erosion.'},{at:158,text:'An oxbow lake forms. Note where the current is fastest and slowest.'}],
  practice:{url:'https://www.khanacademy.org/science/strengthened-shs-earth-and-space-science-2/x21bb710e6de17395:plate-tectonics-and-earth-s-processes/x21bb710e6de17395:weathering-erosion-and-sedimentation/e/understand-weathering-and-erosion',label:'Understand: Weathering and erosion',checked:'2026-10-08'},
  items:[
   {stem:'What is the difference between weathering and erosion?',choices:['Weathering carries sediment away; erosion breaks rock apart','They are two names for the same process','Weathering happens only in deserts and erosion only in rivers','Weathering breaks rock apart; erosion carries the broken pieces away'],key:3,
    miss:['swapped_processes','same_process','location_split',null],
    why:['The two definitions are swapped.','They are separate processes.','Both happen in many places.','Correct. Breaking comes first, then moving.'],
    steps:['Weathering: break. Erosion: carry. Deposition: drop.']},
   {stem:'On a bend in a meandering river, why does the outer bank wear away while sediment builds up on the inner bank?',choices:['The current is fastest on the outside of the bend, so it erodes, and slowest on the inside, so it deposits','The current is fastest on the inside of the bend','Sediment is always heavier on the outside','The two banks are made of different rocks'],key:0,
    miss:[null,'speed_sides_swapped','sediment_weight','rock_type_only'],
    why:['Correct. Over time this can cut off an oxbow lake.','The inside of the bend has the slowest current.','The difference comes from water speed, not sediment weight.','The video explains it with the speed of the current.'],
    steps:['Fast water erodes; slow water deposits.']},
   {stem:'Rainwater containing carbonic acid slowly dissolves a layer of limestone, leaving a cave. What process is this?',choices:['Mechanical weathering','Deposition','Chemical weathering','Compaction'],key:2,
    miss:['chemical_as_mechanical','deposition_confusion',null,'compaction_confusion'],
    why:['Mechanical weathering breaks rock physically, as raindrops do.','Deposition drops sediment; it does not dissolve rock.','Correct. An acid dissolving rock is chemical weathering.','Compaction squeezes sediment layers together.'],
    steps:['Carbon dioxide dissolves in rain to form carbonic acid, which dissolves limestone.']},
   {stem:'A student says a slow river and a fast river carrying the same volume of water will cause the same erosion. What is wrong?',choices:['Nothing; only the volume of water matters','Faster water can carry more sediment, so the fast river erodes more','Slow water erodes more because it stays in contact longer','Rivers do not erode; only rain does'],key:1,
    miss:['volume_only',null,'slow_erodes_more','rivers_dont_erode'],
    why:['Speed matters as well as volume.','Correct. Both the volume and the speed of the water matter.','Slow water tends to drop sediment instead.','Rivers carry billions of tonnes of sediment every year.'],
    steps:['Same volume, higher speed $\\to$ more sediment carried $\\to$ more erosion.']},
  ]}),
 lessonQuiz({lesson:'fossils-and-the-geologic-time-scale',video:'UZ1YE68HszU',reviewed:'2026-10-08',concept:'geologic_time',chapter:'s_earth',
  keyIdea:'Geologists divide Earth’s history into formal units, from the longest eons down to eras, periods and epochs; the four eons are the Hadean, Archean, Proterozoic and Phanerozoic, and the Phanerozoic is split into the Paleozoic, Mesozoic and Cenozoic eras.',
  watchFor:[{at:64,text:'Listen for why geology needs more formal periods than human history.'},{at:102,text:'The four eons are named. Note what was happening in the first one.'},{at:221,text:'The Phanerozoic is split into three eras. Note what each name means.'}],
  practice:{url:'https://www.khanacademy.org/science/shs-earth-and-life-science/x901efce4a07b98a5:unit-1/x901efce4a07b98a5:history-of-the-earth/e/apply-fossils-and-rock-layers',label:'Apply: Fossils and rock layers',checked:'2026-10-08'},
  items:[
   {stem:'Which is the longest unit of geological time?',choices:['Era','Eon','Period','Epoch'],key:1,
    miss:['era_longest',null,'period_longest','epoch_longest'],
    why:['Eras are subdivisions of eons.','Correct. Eons are divided into eras, eras into periods, and periods into epochs.','Periods are subdivisions of eras.','Epochs are shorter still.'],
    steps:['Eon $\\to$ era $\\to$ period $\\to$ epoch, from longest to shortest.']},
   {stem:'Why is the earliest eon named the Hadean?',choices:['It was the coldest time in Earth’s history','It was when the first animals appeared','Earth was being assembled by huge impacts and was so hot that parts of it melted, like the underworld','It was named after the first geologist to study it'],key:2,
    miss:['hadean_cold','hadean_animals',null,'hadean_person'],
    why:['It was extremely hot, not cold.','Complex life appears in the Phanerozoic.','Correct. The video compares it to hell.','The name describes the conditions, not a person.'],
    steps:['Hadean: first half billion years, impacts and melting.']},
   {stem:'A fossil trilobite is found in rock from the Ordovician period. Which eon does that rock belong to?',choices:['Hadean','Archean','Proterozoic','Phanerozoic'],key:3,
    miss:['hadean_life','archean_complex_life','proterozoic_period',null],
    why:['The Hadean was far too hot for any life.','The Archean is long before trilobites and other animals with hard parts.','The Ordovician comes after the Proterozoic.','Correct. The Ordovician is a period within the Phanerozoic, the eon of visible, complex life.'],
    steps:['Ordovician $\\to$ Paleozoic era $\\to$ Phanerozoic eon.']},
   {stem:'A student says the Paleozoic, Mesozoic and Cenozoic are three eons. What is wrong?',choices:['They are eras, the subdivisions of the Phanerozoic eon','Nothing; they are three of the eons','They are periods within the Cretaceous','They are epochs of the Hadean'],key:0,
    miss:[null,'eras_as_eons','eras_as_periods','eras_in_hadean'],
    why:['Correct. Old life, middle life and young life are the three eras of the Phanerozoic.','The four eons are the Hadean, Archean, Proterozoic and Phanerozoic.','The Cretaceous is a period within the Mesozoic, not the other way round.','They belong to the Phanerozoic, the most recent eon.'],
    steps:['Phanerozoic eon $=$ Paleozoic $+$ Mesozoic $+$ Cenozoic eras.']},
  ]}),
 lessonQuiz({lesson:'weather-climate-and-the-atmosphere',video:'JMaqaspDpr0',reviewed:'2026-10-08',
  keyIdea:'The Sun’s energy drives the weather: it powers the water cycle, and because it heats Earth unevenly, warm air rises to leave low pressure and cool air sinks to make high pressure, with wind blowing from high to low; weather is the atmosphere’s state now, while climate is the pattern over decades.',
  watchFor:[{at:63,text:'Weather and climate are told apart. Note the time scale for each.'},{at:182,text:'Greenhouse gases are introduced. Note what they do with infrared radiation.'},{at:261,text:'Listen for why the equator heats up more than the poles.'}],
  practice:{url:'https://www.khanacademy.org/science/strengthened-shs-earth-and-space-science-1/x006d5d274c051fd7:origin-and-structure-of-the-earth/x006d5d274c051fd7:earth-s-place-in-the-solar-system/e/earths-air-and-water',label:'Earth’s air and water',checked:'2026-10-08'},
  items:[
   {stem:'What is the difference between weather and climate?',choices:['Weather is the long-term pattern; climate is what is happening today','Climate is only about temperature, and weather only about rain','Weather is the state of the atmosphere at one time and place; climate is the long-term pattern over decades','They mean the same thing'],key:2,
    miss:['swapped_weather_climate','climate_temperature_only',null,'weather_climate_same'],
    why:['The two definitions are swapped.','Both include temperature, rain, wind and more.','Correct. A sunny afternoon is weather; a dry, hot desert is climate.','They differ in time scale.'],
    steps:['Weather: now, here. Climate: decades, a region.']},
   {stem:'Why does air move from place to place as wind?',choices:['Uneven heating makes warm air rise, leaving low pressure, and cool air sink, making high pressure; air flows from high to low pressure','Air always flows from low pressure to high pressure','The Moon’s gravity pulls the air along','Clouds push the air along'],key:0,
    miss:[null,'low_to_high','moon_drives_wind','clouds_push'],
    why:['Correct. Pressure differences from uneven heating drive the wind.','Air flows from high pressure towards low pressure.','The video traces wind to the Sun’s uneven heating.','Clouds are carried by the wind; they do not cause it.'],
    steps:['Uneven heating $\\to$ pressure differences $\\to$ wind from high to low pressure.']},
   {stem:'A town has a dust storm on Tuesday, in a region that is usually hot and dry. Which statement is correct?',choices:['The dust storm is climate, and hot and dry is the weather','The dust storm is weather, and hot and dry is the climate','Both describe the climate','Both describe the weather'],key:1,
    miss:['swapped_weather_climate',null,'both_climate','both_weather'],
    why:['A single storm is weather; the long-term pattern is climate.','Correct. This matches the video’s desert example.','A storm on one day is weather.','The usual pattern over decades is climate.'],
    steps:['One event $\\to$ weather. Long-term pattern $\\to$ climate.']},
   {stem:'A student says Earth would be better off with no greenhouse gases at all. According to the video, what is wrong?',choices:['Nothing; any greenhouse gas makes Earth unlivable','Greenhouse gases cool Earth','Greenhouse gases reflect all sunlight back into space','The natural greenhouse effect keeps Earth warm enough for life; without it Earth would be too cold'],key:3,
    miss:['any_greenhouse_bad','greenhouse_cools','greenhouse_reflects',null],
    why:['The video says the natural effect is needed for life.','They warm Earth by re-emitting infrared radiation.','They absorb infrared radiation from Earth; they do not reflect sunlight.','Correct. Greenhouse gases absorb infrared radiation and send some back towards the surface.'],
    steps:['Earth emits infrared $\\to$ greenhouse gases absorb some $\\to$ re-emit some back $\\to$ warming.']},
  ]}),
 lessonQuiz({lesson:'rock-layers-and-relative-dating',video:'3LObb5WxMdw',reviewed:'2026-10-08',concept:'relative_dating',chapter:'s_earth',
  keyIdea:'Relative dating puts rocks and fossils in order without exact ages: in undisturbed layers the lower layers are older (superposition), a feature that cuts across others is younger (cross-cutting relationships), and index fossils match layers of the same age.',
  watchFor:[{at:61,text:'Listen for the rule about which layers are oldest.'},{at:139,text:'An igneous intrusion slices through the layers. Note the rule used.'},{at:188,text:'Index fossils are defined. Note what makes them useful.'}],
  practice:{url:'https://www.khanacademy.org/science/strengthened-shs-earth-and-space-science-1/x006d5d274c051fd7:origin-and-structure-of-the-earth/x006d5d274c051fd7:inside-the-earth/e/apply-fossils-and-rock-layers',label:'Apply: Fossils and rock layers',checked:'2026-10-08'},
  items:[
   {stem:'What does the law of superposition say?',choices:['The top layer is always the oldest','A feature that cuts through layers is older than they are','All the layers in a rock formed at the same time','In undisturbed sedimentary layers, the lower layers are older than the layers above them'],key:3,
    miss:['top_oldest','crosscut_older','same_age_layers',null],
    why:['The top layer was laid down last.','A cutting feature is younger, by the law of cross-cutting relationships.','The layers were laid down one after another.','Correct. Layers are laid down one on top of another.'],
    steps:['Undisturbed layers: bottom $=$ oldest, top $=$ youngest.']},
   {stem:'Why must a fault that cuts through several rock layers be younger than those layers?',choices:['Faults always form before any rock does','The layers had to exist before anything could break through them','Faults are made of younger minerals','A fault is younger only if it is shallow'],key:1,
    miss:['fault_first',null,'mineral_age','depth_age'],
    why:['Something must already exist before it can be broken.','Correct. You cannot break something before it exists.','The rule is about what cuts what, not minerals.','Depth does not decide the order here.'],
    steps:['Cutter is younger than what it cuts.']},
   {stem:'From bottom to top, a cliff shows layers A, B and C. A band of igneous rock, D, cuts through all three. Which list runs from oldest to youngest?',choices:['A, B, C, D','D, A, B, C','C, B, A, D','D, C, B, A'],key:0,
    miss:[null,'intrusion_first','top_oldest','reversed_all'],
    why:['Correct. Superposition orders A, B and C, and D cuts them all, so it is youngest.','D cuts through the layers, so it must be younger than them.','By superposition, A at the bottom is oldest.','This reverses every relationship.'],
    steps:['Superposition: A, then B, then C.','Cross-cutting: D after all three.']},
   {stem:'A student says relative dating shows that a rock is exactly $300$ million years old. What is wrong?',choices:['Nothing; relative dating always gives exact ages','Relative dating gives ages only in thousands of years','Relative dating gives only the order of events, older or younger, not an exact age','Relative dating works only on igneous rock'],key:2,
    miss:['relative_is_exact','relative_thousands',null,'relative_igneous_only'],
    why:['Relative dating compares; it does not measure an age in years.','It gives no numbers at all, only an order.','Correct. Like knowing a person is younger than their sister, but not their age.','It is used mainly with sedimentary layers.'],
    steps:['Relative dating: order only. An exact age needs another method.']},
  ]}),
];
