import {lessonQuiz} from './author.ts';

/** UPCAT Science: Physics. Original draft items written from Khan's timestamped caption
 * transcripts, read 2026-10-08; pending subject review.
 * Receipts: docs/THIRD_PARTY_MATERIALS.md, "Lesson quiz caption reviews". */
export const SCIENCE_PHYSICS=[
 lessonQuiz({lesson:'measurement-units-and-density',video:'rW_33U7-8u8',reviewed:'2026-10-08',
  keyIdea:'Density is mass divided by volume; it depends on the material, not on how much of it there is, so it helps identify a substance, and an irregular object’s volume can be found by water displacement.',
  watchFor:[{at:26,text:'Listen for why density does not depend on the amount of material.'},{at:215,text:'Water displacement is used for an irregular key. Note which two readings are subtracted.'},{at:328,text:'The key’s density is compared with a table of materials.'}],
  practice:{url:'https://www.khanacademy.org/science/strengthened-shs-chemistry-1/x174677b2bfa4bea2:1st-quarter/x174677b2bfa4bea2:investigating-density/e/apply-density',label:'Apply: Density',checked:'2026-10-08'},
  items:[
   {stem:'How is density calculated?',choices:['Volume divided by mass','Mass times volume','Mass divided by volume','Mass minus volume'],key:2,
    miss:['inverted_density','product_density',null,'difference_density'],
    why:['This gives volume per unit mass, the reciprocal of density.','Multiplying gives a quantity with units of mass times volume, not density.','Correct. Density tells you how much mass is packed into each unit of volume.','Mass and volume have different units, so they cannot be subtracted.'],
    steps:['$\\text{density} = \\text{mass} \\div \\text{volume}$, in $\\mathrm{g/cm^{3}}$.']},
   {stem:'Why can measuring density help identify an unknown metal?',choices:['Density depends only on the substance, not on how much of it there is','A larger sample of the same metal always has a higher density','Density depends on the object’s shape','Every material has its own mass'],key:0,
    miss:[null,'density_depends_on_amount','density_depends_on_shape','mass_identifies'],
    why:['Correct. Density is an intrinsic property, so a measured value can be matched to a table.','Doubling the sample doubles both mass and volume, so the density is unchanged.','Shape changes the volume measurement method, not the density.','Mass depends on the amount, so it cannot identify a material on its own.'],
    steps:['Measure mass and volume, divide, then compare the result with known densities.']},
   {stem:'A stone has a mass of $54\\ \\mathrm{g}$. A graduated cylinder reads $40.0\\ \\mathrm{mL}$ before the stone is lowered in and $60.0\\ \\mathrm{mL}$ after. What is the stone’s density?',choices:['$0.9\\ \\mathrm{g/cm^{3}}$','$1.35\\ \\mathrm{g/cm^{3}}$','$0.37\\ \\mathrm{g/cm^{3}}$','$2.7\\ \\mathrm{g/cm^{3}}$'],key:3,
    miss:['used_final_reading','used_initial_reading','inverted_density',null],
    why:['This divides by the final reading, which includes the water.','This divides by the starting water volume, not the displaced volume.','This divides volume by mass.','Correct. The stone displaces $20.0\\ \\mathrm{mL}$, and $54 \\div 20.0 = 2.7$.'],
    steps:['Displaced volume: $60.0 - 40.0 = 20.0\\ \\mathrm{mL} = 20.0\\ \\mathrm{cm^{3}}$.','Density: $54 \\div 20.0 = 2.7\\ \\mathrm{g/cm^{3}}$.']},
   {stem:'A student cuts a gold bar in half and says each half now has half the density. What is wrong?',choices:['Nothing; density halves when the mass halves','Each half has half the mass and half the volume, so the density is unchanged','The density doubles because each piece is smaller','Each half’s density depends on where it was cut'],key:1,
    miss:['density_depends_on_amount',null,'smaller_is_denser','density_depends_on_cut'],
    why:['Only the mass halving would change the ratio; the volume halves too.','Correct. Mass and volume shrink together, so their ratio stays the same.','Size does not change density for the same material.','A uniform material has the same density throughout.'],
    steps:['$\\frac{m \\div 2}{V \\div 2} = \\frac{m}{V}$, so the density does not change.']},
  ]}),
 lessonQuiz({lesson:'scalars-and-vectors',video:'ihNZlp7iUHE',reviewed:'2026-10-08',concept:'vectors',chapter:'s_motion',
  keyIdea:'A vector has both a magnitude and a direction, while a scalar has only a magnitude; distance and speed are scalars, and displacement and velocity are their vector partners.',
  watchFor:[{at:25,text:'Two definitions are given. Note what a vector has that a scalar does not.'},{at:215,text:'Five metres becomes five metres to the right. Listen for the new name.'},{at:464,text:'Speed and velocity are compared using the same brick.'}],
  practice:{url:'https://www.khanacademy.org/science/als-k-to-12-science/x46c2fc9f8e023990:4th-quarter/x46c2fc9f8e023990:differentiating-quantities-based-on-magnitude-and-direction/e/equivalent-vectors',label:'Vectors intro',checked:'2026-10-08'},
  items:[
   {stem:'Which of these is a vector quantity?',choices:['$5$ metres','$5$ metres to the right','$2.5$ metres per second','A mass of $3$ kilograms'],key:1,
    miss:['distance_as_vector',null,'speed_as_vector','mass_as_vector'],
    why:['This is a distance: a size with no direction.','Correct. It gives both a size and a direction, so it is a displacement.','This is a speed: a size with no direction.','Mass has a size but no direction.'],
    steps:['A vector needs a magnitude and a direction. Only “$5$ metres to the right” gives both.']},
   {stem:'Why is “the car moved $5$ kilometres” not enough to describe the car’s displacement?',choices:['It gives the direction but not the size','Displacement must be measured in seconds','Kilometres cannot be used for displacement','It gives the size of the change in position but not its direction'],key:3,
    miss:['swapped_parts','displacement_unit_time','unit_confusion',null],
    why:['The statement gives a size, $5$ kilometres, but no direction.','Displacement is a length, so it is measured in metres or kilometres.','Any unit of length works for displacement.','Correct. Without a direction, it is only a distance, a scalar.'],
    steps:['Displacement has a magnitude and a direction. Add a direction, such as north, to make it a vector.']},
   {stem:'A cart travels $12$ metres north in $4$ seconds. What is its average velocity?',choices:['$3$ metres per second north','$3$ metres per second','$48$ metres per second north','$0.33$ metres per second north'],key:0,
    miss:[null,'velocity_without_direction','multiplied_not_divided','inverted_rate'],
    why:['Correct. $12 \\div 4 = 3$, and velocity keeps the direction.','This is the speed. Velocity also needs the direction.','Displacement should be divided by time, not multiplied.','This divides time by displacement.'],
    steps:['$12 \\div 4 = 3$ metres per second.','Add the direction: $3$ metres per second north.']},
   {stem:'A runner says, “My speed was $6$ metres per second east.” What is the best correction?',choices:['Nothing is wrong; speed always includes a direction','It should be called a displacement','Giving a direction makes it a velocity; the speed is just $6$ metres per second','It should be called a distance'],key:2,
    miss:['speed_includes_direction','rate_as_displacement',null,'rate_as_distance'],
    why:['Speed is a scalar and has no direction.','Displacement is a change in position, measured in metres, not metres per second.','Correct. Speed is the scalar; speed with a direction is velocity.','Distance is measured in metres, not metres per second.'],
    steps:['Rate without direction: speed. Rate with direction: velocity.']},
  ]}),
 lessonQuiz({lesson:'speed-velocity-and-acceleration',video:'W6Ar0ls6tVA',reviewed:'2026-10-08',
  keyIdea:'Speed is distance divided by time, the slope of a distance–time graph gives the speed, and velocity is speed with a direction.',
  watchFor:[{at:14,text:'Speed is defined. Note which two quantities are divided.'},{at:303,text:'The slope of the graph is described as rise over run. Listen for what it stands for.'},{at:391,text:'A flat line appears. Note what it says about the object.'}],
  practice:{url:'https://www.khanacademy.org/science/strengthened-shs-physics-1/x5eb5cea12d2cf683:introduction-to-physics/x5eb5cea12d2cf683:descriptors-of-motion/e/understanding-velocity-and-speed',label:'Understanding velocity and speed',checked:'2026-10-08'},
  items:[
   {stem:'How is speed defined?',choices:['Time taken divided by the distance travelled','Distance travelled times the time taken','Distance travelled in a stated direction','Distance travelled divided by the time taken'],key:3,
    miss:['inverted_speed','product_speed','speed_as_displacement',null],
    why:['This gives seconds per metre, the reciprocal of speed.','Multiplying does not give a rate.','A distance with a direction is a displacement, not a speed.','Correct. Speed tells you how far something goes each second.'],
    steps:['$\\text{speed} = \\text{distance} \\div \\text{time}$, in metres per second.']},
   {stem:'On a distance–time graph, why does a steeper straight line mean a faster object?',choices:['A steeper line means the object travelled for longer','The slope, vertical over horizontal, equals the speed, so more distance each second gives a steeper line','A steeper line means the object is speeding up','A steeper line means the object started further away'],key:1,
    miss:['steep_means_longer',null,'steep_means_accelerating','steep_means_farther'],
    why:['Travel time is read along the horizontal axis, not from the steepness.','Correct. Rise over run is distance over time, which is speed.','A straight line has a constant slope, so the speed is constant.','The starting position is where the line begins, not how steep it is.'],
    steps:['$\\text{slope} = \\frac{\\text{rise}}{\\text{run}} = \\frac{\\text{distance}}{\\text{time}} = \\text{speed}$.']},
   {stem:'A distance–time graph is a straight line through $(0, 0)$ and $(4, 60)$, with time in seconds and distance in metres. What is the object’s speed?',choices:['$240$ metres per second','$0.067$ metres per second','$15$ metres per second','$60$ metres per second'],key:2,
    miss:['multiplied_not_divided','inverted_rate',null,'read_value_not_slope'],
    why:['Distance and time should be divided, not multiplied.','This divides time by distance.','Correct. The slope is $60 \\div 4 = 15$.','$60$ metres is the distance after $4$ seconds, not the distance per second.'],
    steps:['Rise: $60$ metres. Run: $4$ seconds.','Slope: $60 \\div 4 = 15$ metres per second.']},
   {stem:'A distance–time graph is a flat horizontal line. A student says the object is moving at a constant speed. What is wrong?',choices:['A flat line has zero slope, so the speed is zero and the object is at rest','Nothing; a flat line always means a constant, non-zero speed','A flat line means the object is speeding up','A flat line means the object is moving backwards'],key:0,
    miss:[null,'flat_means_constant_motion','flat_means_accelerating','flat_means_reverse'],
    why:['Correct. The distance does not change as time passes, so the object is not moving.','A constant non-zero speed gives a sloping straight line.','Speeding up gives a line that gets steeper.','The distance stays the same; nothing is moving.'],
    steps:['Rise $= 0$, so slope $= 0$ and speed $= 0$.']},
  ]}),
 lessonQuiz({lesson:'newton-s-laws-and-friction',video:'O5G4uHe-qc4',reviewed:'2026-10-08',
  keyIdea:'Newton’s second law gives acceleration as net force divided by mass, in the direction of the net force; a free-body diagram finds the net force, and force sets the direction of acceleration, not of motion.',
  watchFor:[{at:40,text:'A free-body diagram is drawn first. Note the two forces on the elevator.'},{at:181,text:'The elevator moves up but accelerates down. Listen for what that means.'},{at:510,text:'The net force is found first, then the applied force. Watch how friction is handled.'}],
  practice:{url:'https://www.khanacademy.org/science/als-k-to-12-science/x46c2fc9f8e023990:4th-quarter/x46c2fc9f8e023990:understanding-the-interrelationship-between-force-motion-and-energy/e/apply-newton-s-second-law-calculations',label:'Apply: Newton’s second law calculations',checked:'2026-10-08'},
  items:[
   {stem:'According to Newton’s second law, what is an object’s acceleration equal to?',choices:['The net force divided by the mass','The mass divided by the net force','The net force times the mass','The largest single force divided by the mass'],key:0,
    miss:[null,'inverted_newton','product_newton','largest_force_not_net'],
    why:['Correct. $a = \\frac{F_{\\text{net}}}{m}$, in the direction of the net force.','This is the reciprocal of acceleration.','Net force equals mass times acceleration, so multiplying gives the wrong quantity.','All forces must be combined into the net force first.'],
    steps:['$a = F_{\\text{net}} \\div m$.']},
   {stem:'An elevator is moving upward, but the net force on it points down. Why is this possible?',choices:['It is impossible; an object always moves in the direction of the net force','The net force must really be upward because the elevator moves up','Force sets the direction of acceleration, not of motion, so the elevator is moving up while slowing down','Gravity stops acting while the elevator moves'],key:2,
    miss:['force_sets_motion','motion_sets_force',null,'gravity_switches_off'],
    why:['An object can move against the net force; it just slows down.','The forces decide the net force, not the direction of motion.','Correct. Velocity up and acceleration down means the elevator is slowing.','Gravity acts all the time.'],
    steps:['Net force down $\\to$ acceleration down.','Velocity up and acceleration down $\\to$ slowing down.']},
   {stem:'A $50$-kilogram crate starts at rest and reaches $4$ metres per second in $2$ seconds. Friction on it is $120$ newtons. What applied force is needed?',choices:['$100$ newtons','$220$ newtons','$20$ newtons','$320$ newtons'],key:1,
    miss:['net_force_as_applied',null,'subtracted_friction','velocity_as_acceleration'],
    why:['This is the net force, not the applied force.','Correct. The applied force must supply the $100$-newton net force and also beat $120$ newtons of friction.','Friction should be added to the net force, not subtracted from it.','This uses the final speed as if it were the acceleration.'],
    steps:['Acceleration: $(4 - 0) \\div 2 = 2\\ \\mathrm{m/s^{2}}$.','Net force: $50 \\times 2 = 100\\ \\mathrm{N}$.','Applied force: $100 + 120 = 220\\ \\mathrm{N}$.']},
   {stem:'An $800$-kilogram elevator has $7{,}840$ newtons of gravity pulling down and $9{,}000$ newtons of cable tension pulling up. A student adds the forces and gets $16{,}840$ newtons. What is wrong?',choices:['Nothing; forces always add as plain numbers','The student should have used only the tension','The student should have divided the tension by gravity','The forces point in opposite directions, so the net force is their difference, $1{,}160$ newtons up'],key:3,
    miss:['forces_always_add','single_force_only','divide_by_gravity',null],
    why:['Forces are vectors, so their directions matter.','Every force on the lift counts toward the net force.','Dividing two forces gives no force at all.','Correct. Opposite forces subtract; the larger one, tension, sets the direction.'],
    steps:['Net force: $9{,}000 - 7{,}840 = 1{,}160\\ \\mathrm{N}$ up.','Acceleration: $1{,}160 \\div 800 = 1.45\\ \\mathrm{m/s^{2}}$ up.']},
  ]}),
 lessonQuiz({lesson:'projectile-motion',video:'txJP95lBv98',reviewed:'2026-10-08',concept:'projectiles',chapter:'s_motion',
  keyIdea:'A projectile’s horizontal and vertical motions are independent: horizontally it keeps a constant velocity, and vertically it accelerates down at about $9.8\\ \\mathrm{m/s^{2}}$, so a ball fired horizontally lands at the same time as one dropped from the same height.',
  watchFor:[{at:12,text:'Predict which ball lands first before the result is shown.'},{at:165,text:'Listen for how the sign of the vertical acceleration is decided.'},{at:244,text:'Look at the spacing of the fired ball’s snapshots across the screen.'}],
  practice:{url:'https://www.khanacademy.org/science/strengthened-shs-physics-1/x5eb5cea12d2cf683:introduction-to-physics/x5eb5cea12d2cf683:kinematics-projectile-motion/e/2d-projectile-motion-concepts-quiz',label:'Projectile motion',checked:'2026-10-08'},
  prediction:{stem:'A ball is fired horizontally off a table at the same moment another ball is dropped from the same height. Ignoring air resistance, which lands first?',choices:['The dropped ball','The fired ball','They land at the same time','It depends on how fast the ball is fired'],key:2,
   miss:['dropped_first','fired_first',null,'speed_affects_fall_time'],
   why:['Both start with zero vertical velocity, so they fall together.','The forward motion does not slow the fall.','Correct. Their vertical motions are identical, so they land together.','The launch speed changes how far the ball lands, not when.'],
   steps:['Vertical motion is the same for both: start at zero, accelerate at $9.8\\ \\mathrm{m/s^{2}}$.']},
  items:[
   {stem:'Ignoring air resistance, what is the horizontal acceleration of a projectile?',choices:['$9.8\\ \\mathrm{m/s^{2}}$','It grows as the projectile falls','Zero','It equals the launch speed'],key:2,
    miss:['gravity_horizontal','horizontal_grows',null,'speed_as_acceleration'],
    why:['Gravity acts vertically, not horizontally.','With no horizontal force, the horizontal velocity cannot change.','Correct. No horizontal force acts, so the horizontal velocity stays constant.','A speed is not an acceleration.'],
    steps:['Only gravity acts, and it acts downward, so $a_x = 0$.']},
   {stem:'Why does firing a ball faster horizontally not change how long it takes to reach the ground?',choices:['A faster ball is pulled down harder by gravity','A faster ball falls more slowly because it is moving forward','Air resistance cancels the extra speed','The horizontal launch speed does not affect the vertical motion, which starts from zero vertical velocity either way'],key:3,
    miss:['speed_increases_gravity','forward_motion_slows_fall','air_cancels_speed',null],
    why:['Gravity gives the same acceleration whatever the horizontal speed.','Forward motion does not change the vertical acceleration.','The analysis ignores air resistance, and the result still holds.','Correct. Horizontal and vertical motions are independent.'],
    steps:['Vertical: same start, same acceleration, same fall time.','Horizontal: faster launch only means landing further away.']},
   {stem:'A ball rolls off a table at $3$ metres per second horizontally and hits the floor $0.4$ seconds later. Ignoring air resistance, how far from the table does it land?',choices:['$7.5$ metres','$1.2$ metres','$0.78$ metres','$3.4$ metres'],key:1,
    miss:['divided_speed_by_time',null,'vertical_drop_as_range','added_speed_time'],
    why:['Distance is speed times time, not speed divided by time.','Correct. The horizontal velocity stays at $3$ metres per second for $0.4$ seconds.','This is roughly the height of the drop, not the horizontal distance.','Speed and time should be multiplied.'],
    steps:['Horizontal velocity is constant, so $x = v_x t$.','$3 \\times 0.4 = 1.2$ metres.']},
   {stem:'With upward taken as positive, a ball thrown up is still rising. A student says its acceleration is $+9.8\\ \\mathrm{m/s^{2}}$ because it is moving up. What is wrong?',choices:['Gravity’s acceleration always points down, so with up positive it is $-9.8\\ \\mathrm{m/s^{2}}$ whether the ball rises or falls','Nothing; the sign follows the direction of motion','The acceleration is zero while the ball rises','The acceleration is $+9.8\\ \\mathrm{m/s^{2}}$ on the way up and zero at the top'],key:0,
    miss:[null,'sign_follows_motion','zero_while_rising','zero_at_top'],
    why:['Correct. The sign depends on the chosen coordinate system, not on the motion.','The direction of motion does not set the sign of the acceleration.','The rising ball slows down, so it is accelerating.','Gravity still acts at the top, so the acceleration is not zero there.'],
    steps:['Up positive and gravity down $\\to a_y = -9.8\\ \\mathrm{m/s^{2}}$ throughout the flight.']},
  ]}),
 lessonQuiz({lesson:'work-energy-and-power',video:'ewfMcg3wRaQ',reviewed:'2026-10-08',
  keyIdea:'In physics, work is force times displacement, so work is done only when a force acts and the object moves; any force, including gravity, can do work, and the unit is the newton metre, or joule.',
  watchFor:[{at:25,text:'Work is defined. Note the two things that must both happen.'},{at:113,text:'Someone pushes a wall for hours. Decide whether work is done.'},{at:311,text:'A barbell is dropped. Listen for which force does the work.'}],
  practice:{url:'https://www.khanacademy.org/science/strengthened-shs-physics-1/x5eb5cea12d2cf683:kinematics/x5eb5cea12d2cf683:work-and-power/e/calculating-work-done',label:'Calculating work done',checked:'2026-10-08'},
  items:[
   {stem:'In physics, what is the work done by a force on an object?',choices:['The force divided by the displacement','The force times the object’s displacement','The force times the time it acts','How tired the person applying the force feels'],key:1,
    miss:['divide_force_distance',null,'force_time_as_work','effort_as_work'],
    why:['Dividing gives newtons per metre, not joules.','Correct. $W = Fd$, measured in joules.','Force times time is impulse, not work.','Feeling tired is not the physics meaning of work.'],
    steps:['$W = F \\times d$; $1$ newton metre $= 1$ joule.']},
   {stem:'A weightlifter holds a barbell still above their head for a minute. Why is no work done on the barbell?',choices:['The barbell does not move, so its displacement is zero','The weightlifter applies no force to it','Holding still uses no energy in the body','Work can only be done by machines'],key:0,
    miss:[null,'no_force_when_still','body_energy_as_work','work_only_machines'],
    why:['Correct. A force with no displacement does no work.','The lifter does push up; otherwise the barbell would fall.','The body does use energy, but that is not work on the barbell.','People and forces such as gravity can do work.'],
    steps:['$d = 0$, so $W = F \\times 0 = 0$.']},
   {stem:'A student pushes a box with a force of $45$ newtons and moves it $3$ metres in the direction of the push. How much work does the student do on the box?',choices:['$15$ joules','$48$ joules','$135$ joules','$0$ joules'],key:2,
    miss:['divided_not_multiplied','added_not_multiplied',null,'no_work_when_pushed'],
    why:['Force and displacement should be multiplied.','Force and displacement should be multiplied, not added.','Correct. $45 \\times 3 = 135$.','The box moves while being pushed, so work is done.'],
    steps:['$W = 45 \\times 3 = 135$ joules.']},
   {stem:'A barbell falls from a shelf with nobody touching it. A student says no work is done on it because nobody is pushing. What is wrong?',choices:['Nothing; only living things can do work','Work is done only if the barbell moves at a constant speed','No force acts on a falling object','Gravity is a force and the barbell moves in its direction, so gravity does work'],key:3,
    miss:['only_living_do_work','constant_speed_needed','no_force_on_falling',null],
    why:['Forces from non-living things, such as gravity, also do work.','Work does not need a constant speed.','Gravity acts on the barbell; that is why it falls.','Correct. Any force can do work if the object moves.'],
    steps:['Force: gravity, downward. Displacement: downward. Work is done.']},
  ]}),
 lessonQuiz({lesson:'momentum-and-impulse',video:'uMYAc04D0ak',reviewed:'2026-10-08',concept:'momentum',chapter:'s_motion',
  keyIdea:'Net impulse equals the change in momentum and also net force times time; because momentum is a vector, a ball that reverses direction must have its starting velocity entered with the opposite sign.',
  watchFor:[{at:78,text:'Impulse is defined. Note the two quantities that are multiplied.'},{at:219,text:'Listen for the most common mistake when the ball changes direction.'},{at:537,text:'The force on the face is found. Note which law is used.'}],
  practice:{url:'https://www.khanacademy.org/science/9th-grade-melcs/x48ae216379e0830b:4th-quarter/x48ae216379e0830b:momentum-impulse-and-collision/e/understand-momentum',label:'Understand: Momentum',checked:'2026-10-08'},
  items:[
   {stem:'Which of these is equal to the net impulse on an object?',choices:['Its final momentum only','Its mass times its acceleration','The net force divided by the time','Its change in momentum'],key:3,
    miss:['final_momentum_only','force_as_impulse','divide_force_time',null],
    why:['Impulse is the change, final minus initial.','Mass times acceleration is the net force, not the impulse.','Impulse is force times time, not force divided by time.','Correct. Net impulse $=\\Delta p = F_{\\text{net}} \\Delta t$.'],
    steps:['$J = \\Delta p = p_{f} - p_{i}$.']},
   {stem:'A ball comes in at $10$ metres per second to the left and bounces back at $5$ metres per second to the right. With right as positive, why must its starting velocity be entered as $-10$ metres per second?',choices:['Velocities before a collision are always negative','The minus sign shows that the ball lost energy','Momentum is a vector, and the two velocities point in opposite directions','It does not matter; the sign makes no difference'],key:2,
    miss:['before_is_negative','sign_shows_energy_loss',null,'sign_irrelevant'],
    why:['The sign comes from the direction, not from the timing.','The sign gives the direction, not information about energy.','Correct. Leftward is negative when rightward is positive.','Leaving out the sign gives the wrong change in momentum.'],
    steps:['Right is positive, so leftward velocities are negative.']},
   {stem:'A $0.5$-kilogram ball hits a wall at $8$ metres per second and rebounds at $6$ metres per second in the opposite direction. What is the size of its change in momentum?',choices:['$7\\ \\mathrm{kg\\,m/s}$','$1\\ \\mathrm{kg\\,m/s}$','$3\\ \\mathrm{kg\\,m/s}$','$14\\ \\mathrm{kg\\,m/s}$'],key:0,
    miss:[null,'ignored_sign_change','final_momentum_only','mass_omitted'],
    why:['Correct. $0.5 \\times 6 - 0.5 \\times (-8) = 3 + 4 = 7$.','This treats both velocities as the same direction.','This is only the final momentum.','This adds the speeds but leaves out the mass.'],
    steps:['Take the rebound direction as positive: $v_{f} = 6$, $v_{i} = -8$.','$\\Delta p = 0.5 \\times 6 - 0.5 \\times (-8) = 7\\ \\mathrm{kg\\,m/s}$.']},
   {stem:'A ball pushes on a player’s face with an average force of $150$ newtons. A student says the face pushes back on the ball with a smaller force, because the ball bounces away. What is wrong?',choices:['Nothing; the object that bounces away always receives the smaller force','By Newton’s third law, the two forces are equal in size and opposite in direction','The face exerts no force on the ball','The face exerts a larger force because it is heavier'],key:1,
    miss:['bouncer_gets_less',null,'one_way_force','heavier_pushes_more'],
    why:['Third-law pairs are always equal in size.','Correct. The face pushes the ball with $150$ newtons in the opposite direction.','The ball bounces back because the face pushes on it.','Mass does not make one of the paired forces larger.'],
    steps:['$F_{\\text{on face}} = -F_{\\text{on ball}}$: equal in size, opposite in direction.']},
  ]}),
 lessonQuiz({lesson:'pressure-and-buoyancy-in-fluids',video:'vzID7ds600c',reviewed:'2026-10-08',concept:'fluids',chapter:'s_units',
  keyIdea:'Fluid pressure grows with depth and acts in all directions, so a fluid pushes harder on the bottom of a submerged object than on its top; this net upward buoyant force equals the weight of the fluid displaced, which is Archimedes’ principle.',
  watchFor:[{at:30,text:'Listen for the directions in which the pressure at a point acts.'},{at:161,text:'Compare the pressure on the top and bottom faces of the cube.'},{at:488,text:'The net force is rewritten. Note what it turns out to equal.'}],
  practice:{url:'https://www.khanacademy.org/science/strengthened-shs-general-science-3-terms/x381269a1083161e8:physics/x381269a1083161e8:physics-of-fluids/e/archimedes-principle',label:'Archimedes principle',checked:'2026-10-08'},
  items:[
   {stem:'According to Archimedes’ principle, the buoyant force on a submerged object equals what?',choices:['The weight of the fluid it displaces','The weight of the object','The volume of the object','The pressure at the bottom of the object'],key:0,
    miss:[null,'buoyancy_equals_object_weight','volume_as_force','pressure_as_force'],
    why:['Correct. The net upward push equals the weight of the displaced fluid.','The object’s own weight is a separate, downward force.','A volume is not a force.','A pressure is not a force until it is multiplied by an area.'],
    steps:['$F_{\\text{buoyant}} = \\rho_{\\text{fluid}} V g$, the weight of the displaced fluid.']},
   {stem:'Why is there a net upward force from the water on a submerged cube?',choices:['Water pushes only upward','Pressure grows with depth, so the water pushes harder on the bottom face than on the top face','The pushes on the side faces add up to an upward force','Gravity is weaker under water'],key:1,
    miss:['pressure_one_direction',null,'sides_push_up','gravity_weaker_underwater'],
    why:['Pressure at a point acts in all directions.','Correct. The bottom face is deeper, so it feels a larger push.','The side pushes are horizontal and cancel in pairs.','Gravity is the same; the extra push comes from pressure.'],
    steps:['$P_{\\text{bottom}} > P_{\\text{top}}$, so the upward push beats the downward push.']},
   {stem:'A stone with a volume of $0.002\\ \\mathrm{m^{3}}$ is fully under water. Taking water’s density as $1{,}000\\ \\mathrm{kg/m^{3}}$ and $g$ as $9.8\\ \\mathrm{m/s^{2}}$, what is the buoyant force on it?',choices:['$2$ newtons','$0.0196$ newtons','$196$ newtons','$19.6$ newtons'],key:3,
    miss:['mass_not_weight','density_omitted','power_of_ten_slip',null],
    why:['$2$ kilograms is the mass of the displaced water, not its weight.','This leaves out the density of water.','This is ten times too large.','Correct. The displaced water has a mass of $2$ kilograms and a weight of $19.6$ newtons.'],
    steps:['Mass displaced: $1{,}000 \\times 0.002 = 2\\ \\mathrm{kg}$.','Weight: $2 \\times 9.8 = 19.6\\ \\mathrm{N}$.']},
   {stem:'A student says a cube held deeper in the same water feels a larger buoyant force, because pressure grows with depth. What is wrong?',choices:['Nothing; going deeper always increases the buoyant force','The buoyant force gets smaller with depth','The top and bottom pressures both grow by the same amount, so their difference, and the buoyant force, stays the same','Pressure does not change with depth'],key:2,
    miss:['deeper_more_buoyant','deeper_less_buoyant',null,'pressure_constant_depth'],
    why:['The extra depth adds the same pressure to both faces, so it cancels.','The displaced volume is unchanged, so the buoyant force is unchanged.','Correct. Only the difference between the faces matters, and that depends on the cube’s height, not its depth.','Pressure does grow with depth; it grows equally on both faces.'],
    steps:['The depth term cancels in $P_{\\text{bottom}} - P_{\\text{top}}$, leaving $\\rho g d$, where $d$ is the cube’s side length, not its depth.']},
  ]}),
 lessonQuiz({lesson:'heat-and-temperature',video:'9_gvwicIbHg',reviewed:'2026-10-08',
  keyIdea:'Heat capacity depends on both mass and material; specific heat capacity is heat capacity per kilogram, a property of the material, and the heat needed is $Q = mc\\Delta T$.',
  watchFor:[{at:54,text:'Two pots of water are compared. Note which boils sooner and why.'},{at:117,text:'Specific heat capacity is defined. Note what it is measured per.'},{at:323,text:'The heat equation is written. Note the three quantities multiplied.'}],
  practice:{url:'https://www.khanacademy.org/science/strengthened-shs-physics-2/x4423f488fef32c93:heat-and-thermonadynamics/x4423f488fef32c93:heat-calculations-temperature-change-phase-change-and-latent-heat/e/apply-specific-heat-capacity',label:'Apply: Specific heat capacity',checked:'2026-10-08'},
  items:[
   {stem:'What is specific heat capacity?',choices:['The total heat stored in an object','The temperature at which a material boils','The heat needed per kilogram to raise a material’s temperature by one kelvin','The heat needed to raise any object by one kelvin, whatever its mass'],key:2,
    miss:['specific_as_total','specific_as_boiling',null,'specific_ignores_mass'],
    why:['Specific heat capacity is a rate per kilogram per kelvin, not a stored total.','A boiling point is a temperature, not a heat capacity.','Correct. Its units are joules per kelvin per kilogram.','That describes heat capacity, which depends on mass.'],
    steps:['$c = \\text{heat capacity} \\div m$.']},
   {stem:'An aluminium chair and a plastic chair of the same mass absorb the same amount of energy from the Sun. Why does the aluminium chair’s temperature rise more?',choices:['Aluminium receives more sunlight than plastic','Aluminium has a lower specific heat capacity, so the same energy raises its temperature more','Plastic has the lower specific heat capacity','Metal chairs always have more mass than plastic ones'],key:1,
    miss:['more_sunlight',null,'reversed_capacity','metal_heavier'],
    why:['The stem fixes the energy absorbed; the difference comes from the material.','Correct. About $897$ against $1{,}670$ joules per kelvin per kilogram.','Plastic’s specific heat capacity is the higher one.','The stem says the masses are the same.'],
    steps:['Same energy in, lower $c$ $\\to$ larger temperature rise.']},
   {stem:'How much heat is needed to warm $0.5\\ \\mathrm{kg}$ of water from $20$ to $60$ degrees Celsius? Use $c$ as $4{,}184$ joules per kelvin per kilogram.',choices:['$83{,}680$ joules','$167{,}360$ joules','$125{,}520$ joules','$2{,}092$ joules'],key:0,
    miss:[null,'mass_omitted','final_temperature_as_change','temperature_change_omitted'],
    why:['Correct. $0.5 \\times 4{,}184 \\times 40 = 83{,}680$.','This leaves out the mass of $0.5$ kilograms.','This uses the final temperature, $60$, instead of the change, $40$.','This leaves out the temperature change.'],
    steps:['Temperature change: $60 - 20 = 40$ degrees Celsius, which is $40$ kelvin.','$Q = mc\\Delta T = 0.5 \\times 4{,}184 \\times 40 = 83{,}680\\ \\mathrm{J}$.']},
   {stem:'A student says a full pot and a half-full pot of water have the same heat capacity because both hold water. What is wrong?',choices:['Nothing; heat capacity depends only on the material','The half-full pot has the larger heat capacity','Heat capacity depends only on the burner used','They have the same specific heat capacity, but the full pot has more mass, so its heat capacity is larger'],key:3,
    miss:['capacity_material_only','less_mass_more_capacity','capacity_from_source',null],
    why:['Heat capacity depends on mass as well as material.','Less mass means a smaller heat capacity.','The burner supplies heat; it does not set the water’s heat capacity.','Correct. Heat capacity is specific heat capacity times mass.'],
    steps:['Heat capacity $= mc$. Same $c$, larger $m$ $\\to$ larger heat capacity.']},
  ]}),
 lessonQuiz({lesson:'waves-and-sound',video:'ClHuscLyuLo',reviewed:'2026-10-08',
  keyIdea:'A wave is a disturbance that travels and carries energy, not matter; wave speed is wavelength times frequency, and it depends on the type of wave and on the medium.',
  watchFor:[{at:89,text:'Listen for what a wave carries and what it leaves behind.'},{at:185,text:'Wave speed is built from wavelength and frequency. Note how the units cancel.'},{at:287,text:'Sound in water and in air is compared. Note which medium carries it faster.'}],
  practice:{url:'https://www.khanacademy.org/science/6th-grade-science-matatag/x1c42f0f13f909d5b:3rd-quarter/x1c42f0f13f909d5b:waves/e/understand-wave-properties',label:'Understand: Wave properties',checked:'2026-10-08'},
  items:[
   {stem:'What do all waves transfer from place to place?',choices:['Matter, but not energy','Energy, but not matter','Both energy and matter','Neither energy nor matter'],key:1,
    miss:['waves_carry_matter',null,'waves_carry_both','waves_carry_nothing'],
    why:['The medium stays in place; only the disturbance travels.','Correct. Each part of the rope moves up and down, but the rope stays where it is.','The matter of the medium is not carried along.','The disturbance carries energy, which is what travels.'],
    steps:['A wave is a travelling disturbance that carries energy.']},
   {stem:'Why is a wave’s speed equal to its wavelength times its frequency?',choices:['Because wavelength and frequency are always equal','Because a higher frequency always means a longer wavelength','Each cycle carries the wave forward one wavelength, and the frequency counts the cycles each second, so the product is distance per second','Because speed is the wavelength divided by the frequency'],key:2,
    miss:['equal_quantities','frequency_wavelength_direct',null,'divided_wavelength_by_frequency'],
    why:['Wavelength is a distance and frequency is a rate; they are different kinds of quantity.','For waves at the same speed, a higher frequency means a shorter wavelength, not a longer one.','Correct. Metres per cycle times cycles per second leaves metres per second.','Dividing gives the wrong units; the cycles must cancel.'],
    steps:['$\\lambda$ in metres per cycle, $f$ in cycles per second.','$v = \\lambda f$: the cycles cancel, leaving metres per second.']},
   {stem:'A wave has a wavelength of $0.5$ metres and a frequency of $40$ hertz. What is its speed?',choices:['$80$ metres per second','$0.0125$ metres per second','$40.5$ metres per second','$20$ metres per second'],key:3,
    miss:['divided_frequency_by_wavelength','divided_wavelength_by_frequency','added_not_multiplied',null],
    why:['Frequency should be multiplied by wavelength, not divided by it.','Wavelength should be multiplied by frequency, not divided by it.','Wavelength and frequency should be multiplied, not added.','Correct. $0.5 \\times 40 = 20$.'],
    steps:['$v = \\lambda f = 0.5 \\times 40 = 20$ metres per second.']},
   {stem:'In a storm, you see the lightning before you hear the thunder. A student says the thunder must be made later than the flash. What is the better explanation?',choices:['They happen together, but light is an electromagnetic wave that travels much faster than sound','The thunder really is made several seconds later','Sound is faster than light but starts later','Light needs a medium to travel and sound does not'],key:0,
    miss:[null,'thunder_made_later','sound_faster','medium_swapped'],
    why:['Correct. The two waves come from the same strike but travel at very different speeds.','Both come from the same event at the same time.','Light is much faster than sound.','It is the other way round: sound needs a medium and light does not.'],
    steps:['Same event, different wave types, different speeds.']},
  ]}),
 lessonQuiz({lesson:'light-mirrors-and-lenses',video:'K0sjZ5nqQ7g',reviewed:'2026-10-08',concept:'optics',chapter:'s_electricity',
  keyIdea:'A convex lens refracts rays parallel to its principal axis through a focal point on the other side, a ray through the near focal point leaves parallel, and an object beyond the focal length forms a real, inverted image.',
  watchFor:[{at:260,text:'Watch where all the parallel rays meet after the lens.'},{at:343,text:'Listen for the simplifying assumption made for lenses.'},{at:511,text:'An image forms on the far side. Note whether it is upright and whether it is real.'}],
  practice:{url:'https://www.khanacademy.org/science/10th-grade-melcs/x1cfbe2e54160ac98:2nd-quarter/x1cfbe2e54160ac98:image-formation-by-lenses/e/image-formation-in-lenses-using-ray-diagrams',label:'Image formation in lenses using ray diagrams',checked:'2026-10-08'},
  items:[
   {stem:'Light rays parallel to the principal axis pass through a convex lens. Where do they go?',choices:['They spread out as if from a focal point on the same side','They pass straight through without bending','They reflect back towards the source','They meet at the focal point on the other side'],key:3,
    miss:['convex_diverges','no_refraction','lens_reflects',null],
    why:['Spreading out is what a concave lens does.','Rays away from the centre are refracted at both surfaces.','A lens transmits and refracts light; it is not a mirror.','Correct. A convex lens brings parallel rays to a focus.'],
    steps:['Parallel in $\\to$ through the far focal point.']},
   {stem:'Why is the image a convex lens forms of an object beyond its focal length called a real image?',choices:['The light rays actually meet there, so the image can be shown on a screen','It is upright and the same size as the object','It only appears to come from behind the lens','It is formed by reflection rather than refraction'],key:0,
    miss:[null,'real_means_upright','virtual_definition','real_means_reflection'],
    why:['Correct. Real images form where light converges.','This image is inverted, and being real is about where the light meets.','Light that only appears to come from a point forms a virtual image.','A lens forms images by refraction.'],
    steps:['Rays converge $\\to$ real image $\\to$ can be projected.']},
   {stem:'A convex lens has a focal length of $8$ centimetres. A candle is placed $20$ centimetres in front of it. What kind of image forms?',choices:['A virtual, upright image on the same side','A real, inverted image on the other side of the lens','No image at all','A real, upright image on the same side'],key:1,
    miss:['virtual_upright',null,'no_image','real_upright'],
    why:['A virtual, upright image needs the object inside the focal length.','Correct. The candle is beyond the focal length, as in the video’s example.','The rays from the candle do converge, so an image forms.','Real images from a single convex lens are inverted and on the far side.'],
    steps:['$20$ centimetres is beyond the $8$-centimetre focal length.','Trace the parallel ray and the focal ray: they cross on the far side, below the axis.']},
   {stem:'A student says a convex lens has just one focal point, on the side the light leaves from. What is wrong?',choices:['Nothing; light can be focused on only one side','A convex lens has no focal point','A symmetric lens has two focal points, one on each side, at the same distance','Both focal points are on the same side'],key:2,
    miss:['one_focal_point','no_focal_point',null,'same_side_foci'],
    why:['Light arriving from the right is focused on the left.','A convex lens focuses parallel rays, so it has focal points.','Correct. Parallel light from either side focuses on the opposite side.','There is one on each side of the lens.'],
    steps:['Two foci, equal distances, one each side.']},
  ]}),
 lessonQuiz({lesson:'electric-circuits',video:'F_vLWkkOETI',reviewed:'2026-10-08',
  keyIdea:'Ohm’s law links voltage, current and resistance as $V = IR$, so current is voltage divided by resistance; current is charge per second in amperes, and by convention it is drawn from positive to negative, opposite to the flow of electrons.',
  watchFor:[{at:53,text:'Ohm’s law is written. Note how it is rearranged for current.'},{at:234,text:'Resistance is compared with a narrowing in a pipe.'},{at:516,text:'Listen for the direction in which current is drawn.'}],
  practice:{url:'https://www.khanacademy.org/science/9th-grade-science-matatag/xc6c9cbcd628f26fe:1st-quarter/xc6c9cbcd628f26fe:ohm-s-law/e/voltage-and-ohm-s-law-ap1',label:'Applying Ohm’s law',checked:'2026-10-08'},
  items:[
   {stem:'Which equation is Ohm’s law?',choices:['$V = \\frac{I}{R}$','$I = VR$','$V = IR$','$R = VI$'],key:2,
    miss:['divide_current_resistance','current_product',null,'resistance_product'],
    why:['Voltage is current times resistance, not current divided by it.','Current is voltage divided by resistance.','Correct. Voltage equals current times resistance.','Resistance is voltage divided by current.'],
    steps:['$V = IR$, so $I = \\frac{V}{R}$ and $R = \\frac{V}{I}$.']},
   {stem:'In a single loop with one resistor, why is the current the same at every point?',choices:['Current is used up as it passes through the resistor','Current is largest next to the battery','Current flows in the wires but not in the resistor','Charge cannot pile up anywhere, so the same charge per second must pass every point, as water flows through every part of one pipe'],key:3,
    miss:['current_used_up','current_largest_near_battery','no_current_in_resistor',null],
    why:['The resistor uses energy, not charge.','The same current passes every point in a single loop.','The current passes through the resistor too.','Correct. Like water through a pipe with a narrow section, the flow rate is the same everywhere.'],
    steps:['One path $\\to$ one current.']},
   {stem:'A $12$-volt battery is connected to a $4$-ohm resistor. What current flows?',choices:['$3$ amperes','$48$ amperes','$0.33$ amperes','$16$ amperes'],key:0,
    miss:[null,'multiplied_v_r','inverted_ohm','added_v_r'],
    why:['Correct. $12 \\div 4 = 3$.','Voltage should be divided by resistance, not multiplied.','This divides resistance by voltage.','Voltage and resistance should be divided, not added.'],
    steps:['$I = \\frac{V}{R} = \\frac{12}{4} = 3$ amperes.']},
   {stem:'A student draws the current flowing from the negative terminal to the positive terminal, because electrons flow that way. What is wrong?',choices:['Nothing; current is always drawn in the direction electrons move','By convention, current is drawn from positive to negative, the opposite of electron flow, a choice made before electrons were known','Current flows both ways at once','Electrons actually flow from positive to negative'],key:1,
    miss:['current_follows_electrons',null,'current_both_ways','electron_direction_reversed'],
    why:['The convention runs opposite to the electrons.','Correct. The convention dates from Benjamin Franklin’s time.','In this circuit the current has one direction.','Electrons leave the negative terminal and move towards the positive one.'],
    steps:['Electrons: negative $\\to$ positive. Conventional current: positive $\\to$ negative.']},
  ]}),
 lessonQuiz({lesson:'magnetism-and-electromagnetism',video:'yU--8Zk57-Y',reviewed:'2026-10-08',concept:'electromagnetism',chapter:'s_electricity',
  keyIdea:'A steady magnetic field through a coil induces no current, but a changing one does; moving a magnet or the coil, or switching an electromagnet on or off, changes the field and induces a voltage, which is how generators make electricity.',
  watchFor:[{at:167,text:'A magnet sits still beside a coil. Note whether the bulb lights.'},{at:192,text:'The magnet is moved. Watch for the flash.'},{at:527,text:'Listen for the rule Faraday found.'}],
  practice:{url:'https://www.khanacademy.org/science/10th-grade-melcs/x1cfbe2e54160ac98:2nd-quarter/x1cfbe2e54160ac98:electromagnetic/e/apply-electromagnetic-induction',label:'Apply: Electromagnetic induction',checked:'2026-10-08'},
  items:[
   {stem:'What induces a current in a coil that has no battery?',choices:['A changing magnetic field through the coil','Any steady magnetic field near the coil','A coil made of a magnetic metal','Leaving the coil near a light bulb'],key:0,
    miss:[null,'steady_field_induces','coil_material','bulb_as_source'],
    why:['Correct. This is electromagnetic induction.','A magnet held still gave no flash.','What matters is the changing field, not the coil’s metal.','The bulb only shows whether a current flows.'],
    steps:['Steady field: no current. Changing field: induced current.']},
   {stem:'When a switch in a primary coil is closed, a bulb on a nearby secondary coil flashes briefly and then goes dark. Why?',choices:['The bulb burns out','The battery runs flat','The magnetic field disappears once the current is steady','The current, and so the magnetic field, grows only for a moment; once steady, the field stops changing and no current is induced'],key:3,
    miss:['bulb_burnt','battery_flat','steady_field_vanishes',null],
    why:['The bulb flashes again when the switch is opened, so it still works.','The primary current stays on after the flash.','The field remains while the current flows; it just stops changing.','Correct. Only the brief growth of the field induces a current.'],
    steps:['Switch closed: field grows $\\to$ flash.','Field steady $\\to$ no induced current.']},
   {stem:'Which of these would light a bulb attached to a coil with no battery?',choices:['Holding a strong magnet still inside the coil','Wrapping more wire round the coil with no magnet nearby','Pulling a bar magnet quickly out of the coil','Placing the coil on a wooden table'],key:2,
    miss:['still_magnet_inside','more_turns_alone',null,'no_field'],
    why:['A still magnet gives a steady field, which induces nothing.','With no magnetic field, there is nothing to change.','Correct. Moving the magnet changes the field through the coil.','No magnetic field is changing, so nothing is induced.'],
    steps:['Look for a change in the magnetic field through the coil.']},
   {stem:'A student says a stronger magnet held still beside a coil should induce a larger current. What is wrong?',choices:['Nothing; field strength alone sets the current','A still magnet gives a steady field, and a steady field induces no current however strong it is','Only weak magnets can induce a current','The magnet must touch the coil to induce a current'],key:1,
    miss:['strength_alone',null,'weak_only','contact_needed'],
    why:['A strong but steady field still induces nothing.','Correct. Induction needs a changing field.','A strong magnet induces a current too, if it moves.','The moving magnet did not need to touch the coil.'],
    steps:['No change in field $\\to$ no induced current.']},
  ]}),
 lessonQuiz({lesson:'radioactivity-and-half-life',video:'9REPnibO4IQ',reviewed:'2026-10-08',
  keyIdea:'Each radioactive nucleus has a fixed chance of decaying in a given time; a half-life is the time in which half of a large sample decays, so after $n$ half-lives a fraction $(\\frac{1}{2})^{n}$ remains, though no one can say which atom will decay next.',
  watchFor:[{at:115,text:'Listen for whether we can predict when one atom will decay.'},{at:311,text:'A drawing of half a block turning to nitrogen is corrected. Note why.'},{at:620,text:'An 80-gram sample with a two-year half-life is worked through.'}],
  practice:{url:'https://www.khanacademy.org/science/shs-general-physics-2/xe75071a1e6b5ff51:4th-quarter/xe75071a1e6b5ff51:radioactive-decay/e/understand-half-life-and-radiometric-dating',label:'Understand: Half-life and radiometric dating',checked:'2026-10-08'},
  items:[
   {stem:'What is a half-life?',choices:['Half the time a sample takes to decay completely','The time for half of a large sample of a radioactive isotope to decay','The time for one particular atom to decay','The time for a sample’s mass to reach zero'],key:1,
    miss:['half_of_total_time',null,'single_atom','decays_to_zero'],
    why:['A sample never decays completely, so there is no total time to halve.','Correct. Each half-life halves the amount that remains.','One atom’s decay time cannot be predicted.','The amount keeps halving and never reaches exactly zero.'],
    steps:['After one half-life, $\\frac{1}{2}$ remains; after two, $\\frac{1}{4}$.']},
   {stem:'Why can we predict that half of a large sample will decay in one half-life, but not which atoms will?',choices:['Each atom decays at random with the same chance; only across huge numbers of atoms does the half become reliable','The atoms on the top of the sample decay first','Each atom keeps track of how old it is','The heaviest atoms always decay first'],key:0,
    miss:[null,'top_half_first','atoms_have_memory','heaviest_first'],
    why:['Correct. This is the law of large numbers at work.','Position in the sample does not matter.','An atom has the same chance of decaying whatever its age.','Atoms of the same isotope all have the same chance.'],
    steps:['Each atom: $50\\%$ chance per half-life.','Many atoms: about half decay.']},
   {stem:'A $96$-gram sample has a half-life of $3$ days. How much of it remains after $9$ days?',choices:['$32$ grams','$0$ grams','$24$ grams','$12$ grams'],key:3,
    miss:['divided_by_time','linear_decay_to_zero','miscounted_half_lives',null],
    why:['This divides by the half-life instead of halving once per half-life.','The sample halves each time; it does not run out.','This stops after two half-lives.','Correct. Nine days is three half-lives: $96 \\to 48 \\to 24 \\to 12$.'],
    steps:['$9 \\div 3 = 3$ half-lives.','$96 \\times (\\frac{1}{2})^{3} = 12$ grams.']},
   {stem:'A student says a radioactive sample is completely gone after two half-lives, because each half-life removes half. What is wrong?',choices:['Nothing; two halves make a whole','Half of the sample remains after two half-lives','Each half-life halves what is left, so a quarter remains after two half-lives','Three quarters of the sample remain after two half-lives'],key:2,
    miss:['halves_add_to_whole','half_after_two',null,'three_quarters_after_two'],
    why:['The second half-life halves the remaining half, not the original amount.','Half remains after one half-life, not two.','Correct. $\\frac{1}{2} \\times \\frac{1}{2} = \\frac{1}{4}$.','Three quarters have decayed; one quarter remains.'],
    steps:['$1 \\to \\frac{1}{2} \\to \\frac{1}{4}$.']},
  ]}),
 lessonQuiz({lesson:'relative-motion-and-velocities',video:'EmOis0kQuxM',reviewed:'2026-10-08',concept:'relative_motion',chapter:'s_motion',
  keyIdea:'A velocity depends on the reference frame it is measured from: a truck going $100$ kilometres per hour over the ground moves forward at only $5$ kilometres per hour as seen from a car going $95$ kilometres per hour the same way.',
  watchFor:[{at:78,text:'Pause and predict the truck’s speed as seen from the car.'},{at:143,text:'Listen for what the ground seems to do when you sit in the moving car.'},{at:318,text:'Listen for the term reference frame.'}],
  practice:{url:'https://www.khanacademy.org/science/strengthened-shs-physics-1/x5eb5cea12d2cf683:introduction-to-physics/x5eb5cea12d2cf683:descriptors-of-motion/e/speed-and-velocity-questions',label:'Speed and velocity questions',checked:'2026-10-08'},
  items:[
   {stem:'What does it mean to say that velocity is relative?',choices:['It must always be measured from the ground','It is the same for every observer','It changes only when the object speeds up','Its value depends on the reference frame it is measured from'],key:3,
    miss:['ground_only','same_for_all','changes_only_when_accelerating',null],
    why:['The ground is one frame among many.','Different observers can measure different velocities.','The same steady motion can have different velocities in different frames.','Correct. The ground frame and the car frame give different values.'],
    steps:['Always state which frame a velocity is measured from.']},
   {stem:'From inside a moving car, why does the car itself appear to be at rest?',choices:['The car stops whenever you look at it','Cars have no velocity','You move with the car, so relative to you its velocity is zero','Velocity can only be measured from the ground'],key:2,
    miss:['car_stops','no_velocity',null,'ground_only'],
    why:['The car keeps moving over the ground.','The car has a velocity in the ground frame.','Correct. In the car frame, the seats and windows do not move.','Any frame can be used, including the car.'],
    steps:['Same velocity as the car $\\to$ zero relative velocity.']},
   {stem:'A bus travels at $60$ kilometres per hour east. A cyclist on the same road travels at $20$ kilometres per hour east. What is the bus’s velocity as seen by the cyclist?',choices:['$80$ kilometres per hour east','$40$ kilometres per hour east','$60$ kilometres per hour east','$40$ kilometres per hour west'],key:1,
    miss:['added_same_direction',null,'ground_value','reversed_direction'],
    why:['Velocities in the same direction are subtracted for the relative velocity.','Correct. $60 - 20 = 40$, and the bus pulls ahead to the east.','This is the bus’s velocity in the ground frame.','The bus is faster, so it moves ahead of the cyclist, east.'],
    steps:['Relative velocity: $60 - 20 = 40$ kilometres per hour east.']},
   {stem:'Two cars drive side by side at $90$ kilometres per hour in the same direction. A passenger in one says the other car is moving at $90$ kilometres per hour. Seen from the passenger’s car, what is wrong?',choices:['Relative to the passenger, the other car is at rest, because both share the same velocity','Nothing; a velocity is the same from every frame','The other car moves at $180$ kilometres per hour relative to the passenger','The other car moves backwards at $90$ kilometres per hour'],key:0,
    miss:[null,'frame_independent','added_same_direction','reversed_frame'],
    why:['Correct. $90 - 90 = 0$ in the passenger’s frame.','The $90$ is the ground-frame value.','Adding is wrong for cars going the same way.','The other car keeps pace; it does not fall behind.'],
    steps:['$90 - 90 = 0$ kilometres per hour relative to the passenger.']},
  ]}),
 lessonQuiz({lesson:'thermodynamics-and-heat-transfer',video:'f1OokOgtcqg',reviewed:'2026-10-08',concept:'thermodynamics',chapter:'s_energy',
  keyIdea:'The first law says energy is conserved, so energy lost by a system is gained by its surroundings; the second law says entropy, a measure of how spread out energy is, cannot decrease spontaneously, so heat flows on its own only from hot to cold.',
  watchFor:[{at:40,text:'A system and its surroundings are defined. Note where the boundary goes.'},{at:286,text:'Listen for whether the first law forbids a cold coffee from warming itself.'},{at:583,text:'A refrigerator moves heat from cold to warm. Listen for why that is allowed.'}],
  practice:{url:'https://www.khanacademy.org/science/ap-physics-2/x0e2f5a2c:thermodynamics/x0e2f5a2c:thermal-energy-and-thermal-equilibrium/e/understand-thermodynamics',label:'Understand: Thermodynamics',checked:'2026-10-08'},
  items:[
   {stem:'What does the first law of thermodynamics state?',choices:['Entropy always decreases','Heat always flows from cold to hot','Energy is conserved, so energy lost by a system is gained by its surroundings','Temperature is conserved'],key:2,
    miss:['entropy_decreases','heat_cold_to_hot',null,'temperature_conserved'],
    why:['The second law says entropy does not decrease spontaneously.','Heat flows spontaneously from hot to cold.','Correct. Energy is neither created nor destroyed.','Temperatures change; energy is what is conserved.'],
    steps:['Energy lost by the system $=$ energy gained by the surroundings.']},
   {stem:'A room-temperature coffee never heats itself up by drawing energy from the room. Why not, when this would still conserve energy?',choices:['Concentrating the energy would lower the entropy, and the second law forbids entropy decreasing spontaneously','It would break the first law of thermodynamics','The room has less total energy than the coffee','Coffee cannot absorb heat'],key:0,
    miss:[null,'first_law_forbids','room_less_energy','coffee_cannot_absorb'],
    why:['Correct. The first law allows it, but the second law does not.','Energy would be conserved, so the first law is satisfied.','The room has far more energy, spread over far more molecules.','Coffee warms easily when heated by a stove.'],
    steps:['First law: allowed. Second law: entropy would fall, so not spontaneous.']},
   {stem:'A metal block at $80$ degrees Celsius is placed in a sealed, insulated box of air at $20$ degrees Celsius. What happens?',choices:['Energy flows from the air into the block, heating it further','Energy flows from the block to the air until both reach the same temperature','No energy flows, because the box is sealed','The block and the air both cool down'],key:1,
    miss:['cold_to_hot',null,'sealed_no_transfer','both_lose_energy'],
    why:['That would concentrate energy, lowering entropy.','Correct. Heat flows spontaneously from hot to cold until thermal equilibrium.','Sealing stops energy leaving the box, not flowing inside it.','Energy is conserved inside the insulated box, so the air must warm.'],
    steps:['Hot to cold until the temperatures are equal: thermal equilibrium.']},
   {stem:'A student says a refrigerator breaks the second law, because it moves heat from cold food to a warm kitchen. What is wrong?',choices:['Nothing; refrigerators do break the second law','Heat really flows from the kitchen into the refrigerator','The second law applies only to hot drinks','The second law forbids this only when it happens spontaneously; the refrigerator uses electrical energy, and total entropy still rises'],key:3,
    miss:['fridge_breaks_law','pump_reverses','law_limited_scope',null],
    why:['No process breaks the second law once all energy sources are counted.','The refrigerator pumps heat out, from cold to warm.','The second law applies to every system.','Correct. The process is driven, not spontaneous, and entropy rises elsewhere.'],
    steps:['Driven process $\\to$ allowed.','Counting the power source, total entropy does not decrease.']},
  ]}),
 lessonQuiz({lesson:'special-relativity',video:'EI2OPCdGXkw',reviewed:'2026-10-08',concept:'relativity',chapter:'s_motion',
  keyIdea:'No frame of reference is preferred, and experiments show light travels at about $300$ million metres per second in every frame; special relativity keeps both ideas, so velocities do not simply add and nothing can reach the speed of light.',
  watchFor:[{at:39,text:'Galilean relativity is introduced with a ball thrown in a moving car.'},{at:215,text:'Listen for what Michelson and Morley found about motion through the ether.'},{at:436,text:'Each tile is the same boost, but the tiles shrink near the edge. Listen for what this explains.'}],
  practice:{url:'https://www.khanacademy.org/science/shs-physical-science/x0492729e402f0c6b:4th-quarter/x0492729e402f0c6b:understanding-the-cosmos/e/doppler-effect-ap1',label:'Related practice: Doppler effect',checked:'2026-10-08'},
  items:[
   {stem:'What is the principle of the constancy of the speed of light?',choices:['Light is faster when its source moves towards you','Light travels at the same speed in every frame of reference','Light needs an ether to travel through','Light slows down in moving frames'],key:1,
    miss:['speeds_add_for_light',null,'ether_needed','light_slows_moving'],
    why:['The source’s motion does not change the speed of light.','Correct. About $300$ million metres per second for every observer.','The ether idea was ruled out by experiment.','The speed is the same in every frame.'],
    steps:['$c$ is the same in all frames.']},
   {stem:'Why could Michelson and Morley not detect Earth’s motion through the ether?',choices:['Earth moves too slowly to affect light at all','Earth does not move','The ether is dragged along exactly with Earth','Light’s measured speed did not change with Earth’s motion, showing there is no fixed ether frame'],key:3,
    miss:['earth_too_slow','earth_static','ether_dragged',null],
    why:['Earth’s speed differs by up to about $60$ kilometres per second during the year, enough for the test.','Earth moves round the Sun.','The video’s conclusion is that electromagnetism works the same in every frame, not that the ether moves with Earth.','Correct. The ether theory was wrong.'],
    steps:['No change in light speed $\\to$ no preferred frame.']},
   {stem:'A spaceship moving at half the speed of light switches on a forward headlight. How fast does that light travel in the ship’s frame and in the frame of a planet the ship is passing?',choices:['At one and a half times the speed of light in the planet’s frame','At half the speed of light in the planet’s frame','At the speed of light in both frames','At zero speed in the ship’s frame'],key:2,
    miss:['galilean_addition','galilean_subtraction',null,'light_at_rest'],
    why:['Simply adding speeds is Galilean relativity, which fails for light.','Subtracting speeds is also Galilean.','Correct. Light’s speed is the same in every frame.','Light always moves at $c$ for every observer.'],
    steps:['Do not add the ship’s speed to light’s speed; $c$ is the same everywhere.']},
   {stem:'A student says that with enough equal boosts a rocket must pass the speed of light, because each boost adds the same speed. What is wrong?',choices:['Close to light speed each equal boost adds less and less speed, so light speed is never reached','Nothing; repeated boosts add speed without limit','A rocket cannot be boosted more than once','The speed of light rises as the rocket speeds up'],key:0,
    miss:[null,'speeds_add_without_limit','single_boost','light_speed_changes'],
    why:['Correct. The tiles shrink near the edge, so infinitely many boosts would be needed.','Adding equal amounts is only a good approximation at low speeds.','A rocket can keep firing.','The speed of light is the same in every frame.'],
    steps:['Equal boosts $\\ne$ equal increases in speed near $c$.']},
  ]}),
];
