import {lessonQuiz} from './author.ts';

/** UPCAT Science: Astronomy. Original draft items written from Khan's timestamped caption
 * transcripts, read 2026-10-08; pending subject review.
 * Receipts: docs/THIRD_PARTY_MATERIALS.md, "Lesson quiz caption reviews". */
export const SCIENCE_ASTRONOMY=[
 lessonQuiz({lesson:'the-solar-system-and-its-planets',video:'wTyqO-tfs7Q',reviewed:'2026-10-08',
  keyIdea:'The solar system formed about $4.6$ billion years ago from a flattened cloud of gas and dust; the four inner, terrestrial planets are small and rocky, while the four outer planets beyond the asteroid belt are huge, cold worlds of gas and liquid with many moons and rings.',
  watchFor:[{at:14,text:'Gravity flattens a cloud of gas and dust. Note what forms at the centre.'},{at:87,text:'The terrestrial planets are described. Note what they have in common.'},{at:150,text:'The outer planets are described. Compare them with the inner planets.'}],
  practice:{url:'https://www.khanacademy.org/science/strengthened-shs-earth-and-space-science-1/x006d5d274c051fd7:origin-and-structure-of-the-earth/x006d5d274c051fd7:what-the-universe-is-made-of/e/understand-the-solar-system',label:'Understand: The solar system',checked:'2026-10-08'},
  items:[
   {stem:'Which four planets are the inner, terrestrial planets?',choices:['Jupiter, Saturn, Uranus and Neptune','Mercury, Venus, Jupiter and Saturn','Mercury, Venus, Earth and Mars','Earth, Mars, Jupiter and Saturn'],key:2,
    miss:['inner_outer_swapped','mixed_by_brightness',null,'mixed_by_distance'],
    why:['These are the outer planets.','Jupiter and Saturn are outer gas giants.','Correct. They lie between the Sun and the asteroid belt.','Jupiter and Saturn lie beyond the asteroid belt.'],
    steps:['Sun, Mercury, Venus, Earth, Mars, asteroid belt, then the outer planets.']},
   {stem:'Why are the inner planets called terrestrial?',choices:['They are the largest planets','They are made mostly of hydrogen and helium','They have the most moons and rings','They are rocky worlds with solid surfaces, like Earth; the word comes from the Latin for Earth'],key:3,
    miss:['terrestrial_largest','terrestrial_gas','terrestrial_rings',null],
    why:['The outer planets are much bigger.','That describes gas giants such as Jupiter.','The terrestrial planets have no rings and few moons.','Correct. They also have few or no moons and no rings.'],
    steps:['Terrestrial: rocky, solid surface, Earth-like.']},
   {stem:'A planet found around another star is huge and cold, made mostly of hydrogen and helium, and has many moons. Which planet in our solar system is it most like?',choices:['Jupiter','Mars','Mercury','Earth'],key:0,
    miss:[null,'mars_like','mercury_like','earth_like'],
    why:['Correct. Jupiter is a gas giant with many moons.','Mars is small and rocky, with two moons.','Mercury is small, rocky and has no moons.','Earth is rocky with one moon.'],
    steps:['Huge, cold, gas, many moons $\\to$ gas giant.']},
   {stem:'A student says Mercury must be the hottest planet because it is closest to the Sun. What does the video say?',choices:['Mercury is the hottest, as the student says','Venus is the hottest planet, even though Mercury is closer to the Sun','Earth is the hottest planet','Neptune is the hottest because it is the windiest'],key:1,
    miss:['closest_is_hottest',null,'earth_hottest','windy_hottest'],
    why:['The video names Venus, not Mercury, as the hottest planet.','Correct. Being closest does not make Mercury the hottest.','Earth is not the hottest.','Neptune is extremely cold, around $-214$ degrees Celsius.'],
    steps:['Distance from the Sun is not the only factor; Venus is the hottest.']},
  ]}),
 lessonQuiz({lesson:'earth-s-rotation-revolution-and-the-seasons',video:'05qDIjKevJo',reviewed:'2026-10-08',concept:'seasons',chapter:'s_earth',
  keyIdea:'Seasons are caused by the tilt of Earth’s axis, about $23.4^{\\circ}$, not by its distance from the Sun: the hemisphere tilted towards the Sun gets longer days, a larger share of the sunlight and higher, more direct rays, so it has summer.',
  watchFor:[{at:0,text:'Listen for what does not cause the seasons.'},{at:232,text:'The tilt angle is given. Note whether it changes during a year.'},{at:965,text:'Listen for the biggest cause of the difference between summer and winter.'}],
  practice:{url:'https://www.khanacademy.org/science/6th-grade-science-matatag/x1c42f0f13f909d5b:4th-quarter/x1c42f0f13f909d5b:earth-s-revolution-and-rotation/e/understand-seasons',label:'Understand: Seasons',checked:'2026-10-08'},
  items:[
   {stem:'What causes Earth’s seasons?',choices:['Earth moving closer to and farther from the Sun','The tilt of Earth’s axis relative to the plane of its orbit','The Sun giving out more energy in summer','The Moon’s position'],key:1,
    miss:['distance_causes_seasons',null,'sun_output_changes','moon_causes_seasons'],
    why:['Earth’s orbit is nearly circular, and distance is not the cause.','Correct. The tilt decides which hemisphere leans towards the Sun.','The video explains seasons by tilt, not by changes in the Sun.','The Moon does not cause the seasons.'],
    steps:['Tilt towards the Sun $\\to$ summer; tilt away $\\to$ winter.']},
   {stem:'When the Northern Hemisphere is tilted towards the Sun, why is it warmer there?',choices:['It gets longer days, a larger share of the Sun’s rays, and higher sunlight that passes through less atmosphere','It is much closer to the Sun at that time','The Sun is hotter in June','Earth spins faster in summer'],key:0,
    miss:[null,'distance_causes_seasons','sun_output_changes','spin_speed'],
    why:['Correct. All three effects come from the tilt.','Distance is not the reason.','The Sun’s output is not what changes.','Earth’s spin rate does not change with the seasons.'],
    steps:['More hours of daylight, more rays, steeper rays $\\to$ more energy $\\to$ summer.']},
   {stem:'It is summer in Japan, in the Northern Hemisphere. What season is it in southern Australia, in the Southern Hemisphere?',choices:['Summer','Spring','Winter','Autumn'],key:2,
    miss:['same_season_everywhere','spring_offset',null,'autumn_offset'],
    why:['The hemispheres have opposite seasons.','Spring is a season in between, when neither hemisphere leans towards the Sun.','Correct. When one hemisphere tilts towards the Sun, the other tilts away.','Autumn is also a season in between; when the north has summer, the south has the opposite extreme.'],
    steps:['North tilted towards the Sun $\\to$ south tilted away $\\to$ southern winter.']},
   {stem:'A student says the Arctic has continuous daylight in its summer because the North Pole is nearest the Sun then. What is wrong?',choices:['Nothing; the pole is much nearer the Sun','The Arctic actually has continuous darkness in summer','The Sun circles the pole in summer','The North Pole is tilted towards the Sun, so as Earth spins the Arctic never turns out of the sunlight'],key:3,
    miss:['distance_causes_seasons','reversed_polar_day','sun_circles_pole',null],
    why:['Distance is not the reason.','Continuous darkness comes in the Arctic winter, when it is tilted away.','Earth spins; the Sun does not circle the pole.','Correct. The tilt, not distance, keeps the Arctic in sunlight all day.'],
    steps:['Tilted towards the Sun $\\to$ the whole daily rotation stays in the lit half.']},
  ]}),
 lessonQuiz({lesson:'phases-of-the-moon-and-eclipses',video:'ZQcf9xLABa0',reviewed:'2026-10-08',concept:'moon_phases',chapter:'s_earth',
  keyIdea:'The Sun always lights half of the Moon; the phase we see depends on how much of that lit half faces Earth as the Moon orbits, from new moon (the Moon roughly between Earth and the Sun) through first quarter to full moon (Earth between the Moon and the Sun).',
  watchFor:[{at:39,text:'Listen for why the Moon and the Sun look about the same size in the sky.'},{at:216,text:'New moon is explained. Note where the Moon is.'},{at:253,text:'Full moon is explained. Note where Earth is.'}],
  practice:{url:'https://www.khanacademy.org/science/5th-grade-science-revised-k-to-10-3-terms/xd90d8fbecb0e4173:3rd-quarter/xd90d8fbecb0e4173:phases-of-the-moon/e/understand-the-moon-and-its-motions',label:'Understand: The moon and its motions',checked:'2026-10-08'},
  items:[
   {stem:'Where is the Moon at new moon?',choices:['On the far side of Earth from the Sun','At a right angle to the line from Earth to the Sun','Inside Earth’s shadow','Roughly between Earth and the Sun'],key:3,
    miss:['new_full_swapped','quarter_position','shadow_causes_phase',null],
    why:['That position gives a full moon.','At a right angle we see a quarter moon.','Phases are not caused by Earth’s shadow.','Correct. Its lit half faces away from us.'],
    steps:['New moon: Moon between Earth and Sun, lit side away from us.']},
   {stem:'Why does the Moon show phases?',choices:['Earth’s shadow covers part of the Moon','The Moon makes its own light, which changes','The Sun always lights half of the Moon, and as the Moon orbits we see different amounts of that lit half','Clouds cover parts of the Moon'],key:2,
    miss:['earth_shadow_phases','moon_own_light',null,'clouds_cover'],
    why:['Earth’s shadow on the Moon is a lunar eclipse, not a phase.','The Moon reflects sunlight; it does not make light.','Correct. The phase depends on our view of the lit half.','Clouds do not cause the regular monthly cycle.'],
    steps:['Half lit always; the fraction we see changes with the Moon’s position.']},
   {stem:'About a week after a new moon, you can see exactly half of the Moon’s face lit. What phase is it?',choices:['Full moon','First quarter','New moon','Last quarter'],key:1,
    miss:['half_is_full',null,'new_confusion','order_confusion'],
    why:['At full moon we see the whole lit side.','Correct. We see half the lit side and half the dark side.','At new moon we see none of the lit side.','Last quarter comes after full moon, not a week after new moon.'],
    steps:['New $\\to$ first quarter $\\to$ full, then back to new.']},
   {stem:'A student says a full moon happens because the Moon is closest to the Sun. What is wrong?',choices:['At full moon Earth is between the Moon and the Sun, so we see the whole lit side','Nothing; the Moon is lit only when it is near the Sun','At full moon the Moon is between Earth and the Sun','The Moon is full because it reflects light from Earth'],key:0,
    miss:[null,'closeness_lights_moon','new_full_swapped','earthshine'],
    why:['Correct. The Moon is on the far side of Earth from the Sun.','Half the Moon is lit at all times.','That is the new moon position.','The light we see at full moon is reflected sunlight.'],
    steps:['Full moon: Sun, Earth, Moon roughly in a line, with Earth in the middle.']},
  ]}),
 lessonQuiz({lesson:'the-origin-of-the-universe',video:'eUF59jCFcyQ',reviewed:'2026-10-08',concept:'big_bang',chapter:'s_earth',
  keyIdea:'The Big Bang is the expansion of space itself, not an explosion of matter into empty space; the universe has no edge and no outside, and as space expands every point moves away from every other, with more distant points moving away faster.',
  watchFor:[{at:65,text:'Listen for what is actually expanding in the Big Bang.'},{at:175,text:'The surface of a sphere is used as a model of a space with no edge.'},{at:635,text:'Listen for how things move apart as space expands.'}],
  practice:{url:'https://www.khanacademy.org/science/shs-earth-science/xecff05e2330f305a:unit-1-name/xecff05e2330f305a:universe-and-the-solar-system/e/quiz-the-big-bang',label:'Quiz: The Big Bang',checked:'2026-10-08'},
  items:[
   {stem:'In the Big Bang theory, what is expanding?',choices:['Space itself','Matter flying outward into empty space','Only the galaxies, through a fixed space','The edge of the universe, into the space beyond'],key:0,
    miss:[null,'explosion_into_space','galaxies_only','edge_expands'],
    why:['Correct. It is not matter spreading through a space that was already there.','The video warns against the picture of an explosion into space.','Space itself is stretching, not a fixed backdrop.','The universe has no edge and nothing outside it to expand into.'],
    steps:['Big Bang: space expands, carrying everything apart.']},
   {stem:'How can a space have a finite size but no edge?',choices:['It cannot; any finite space must have an edge','Its edge is simply too far away to see','Its edge is made of dark matter','If it curves back on itself, like the surface of a sphere, so travelling in one direction brings you back around'],key:3,
    miss:['finite_needs_edge','edge_hidden','edge_material',null],
    why:['A sphere’s surface is a counterexample.','The point is that there is no edge at all.','The video says there is no edge.','Correct. A sphere’s surface has a finite area and no edge.'],
    steps:['Surface of a sphere: finite area, no edge; the universe is pictured by analogy one dimension up.']},
   {stem:'Three dots are drawn on a balloon, which is then blown up. Seen from any one dot, what happens to the other two?',choices:['Both move towards it','Both move away, and the dot that is farther away moves away faster','Only the dot nearest the centre of the balloon moves','They stay at the same distance'],key:1,
    miss:['contraction',null,'central_point','no_change'],
    why:['The balloon is expanding, so the dots separate.','Correct. This is how galaxies appear to move apart in an expanding universe.','Every part of the surface stretches.','Stretching the surface increases every distance.'],
    steps:['Stretch the surface $\\to$ every distance grows, larger distances grow faster.']},
   {stem:'A student says that because the universe began very small, there must be a centre that everything is flying away from. What does the video say?',choices:['The Milky Way is that centre','The centre is where an explosion happened in empty space','Space expands everywhere at once, so everything moves away from everything else, with no special centre','The centre lies at the universe’s edge'],key:2,
    miss:['milky_way_centre','explosion_centre',null,'edge_centre'],
    why:['No galaxy has a special place.','There was no explosion into an empty space.','Correct. Every point sees the others moving away.','The universe has no edge.'],
    steps:['On a balloon’s surface, no dot is the centre.']},
  ]}),
 lessonQuiz({lesson:'the-formation-of-earth',video:'VbNXh0GaLYo',reviewed:'2026-10-08',concept:'earth_formation',chapter:'s_earth',
  keyIdea:'About $4.6$ billion years ago a cloud of gas, probably compressed by a supernova shock wave, collapsed into the Sun and a disc of material that clumped into planetesimals and planets; a Mars-sized body, Theia, probably struck the young Earth a glancing blow, and the debris formed the Moon.',
  watchFor:[{at:106,text:'Listen for the evidence that a supernova may have triggered the collapse.'},{at:198,text:'Particles clump into planetesimals. Note what they are.'},{at:274,text:'A Mars-sized body hits the young Earth. Note what forms from the debris.'}],
  practice:{url:'https://www.khanacademy.org/science/strengthened-shs-earth-and-space-science-1/x006d5d274c051fd7:origin-and-structure-of-the-earth/x006d5d274c051fd7:a-brief-history-of-the-earth/e/quiz--earth---the-formation-of-our-solar-system',label:'Quiz: Earth and the formation of our solar system',checked:'2026-10-08'},
  items:[
   {stem:'What is the leading explanation for how the Moon formed?',choices:['The Moon formed at the centre of the gas cloud, alongside the Sun','The Moon was a passing asteroid captured by Earth’s gravity','A Mars-sized body struck the young Earth a glancing blow, and debris thrown into orbit became the Moon','The Moon broke off a fast-spinning Mars'],key:2,
    miss:['moon_with_sun','captured_asteroid',null,'moon_from_mars'],
    why:['The Sun formed at the centre; the Moon formed later, near Earth.','The video describes an impact, not a capture.','Correct. The impactor is called Theia.','The impactor was about the size of Mars, not Mars itself.'],
    steps:['Theia hits Earth $\\to$ molten material splashes into orbit $\\to$ it gathers into the Moon.']},
   {stem:'Why are there no large rocks surviving from the Hadean eon?',choices:['All Hadean rocks were blasted into space','Earth’s surface was molten from impacts, so rock kept melting and being recycled','Hadean rocks were too small to see','Living things destroyed the Hadean rocks'],key:1,
    miss:['rocks_to_space',null,'rocks_too_small','life_destroyed'],
    why:['Some material reached orbit, but most stayed and kept melting.','Correct. Collisions turned kinetic energy into heat, keeping the surface molten.','The issue is melting, not size.','There was little or no life in the Hadean.'],
    steps:['Constant impacts $\\to$ heat $\\to$ molten surface $\\to$ no lasting rocks.']},
   {stem:'Which order matches the video’s account?',choices:['The Sun ignites, a gas cloud is compressed, the Moon forms, planetesimals form','Planetesimals form, a gas cloud is compressed, the Sun ignites, the Moon forms','The Moon forms, planetesimals form, the Sun ignites, a gas cloud is compressed','A gas cloud is compressed, the Sun ignites, planetesimals form, the Moon forms'],key:3,
    miss:['sun_before_cloud','planets_before_sun','reversed_order',null],
    why:['The cloud must collapse before the Sun can ignite.','Planetesimals form from the disc around the young Sun.','This is the sequence backwards.','Correct. Each step needs the one before it.'],
    steps:['Cloud $\\to$ Sun $\\to$ planetesimals $\\to$ Earth $\\to$ impact $\\to$ Moon.']},
   {stem:'A student says the Moon must be much younger than Earth because it formed from a collision. What is the better statement?',choices:['The collision happened early, while Earth was still forming, so the Moon also formed early in Earth’s history','Nothing; the Moon formed billions of years after Earth','The Moon is much older than Earth','The collision happened in the age of the dinosaurs'],key:0,
    miss:[null,'moon_much_younger','moon_older','recent_collision'],
    why:['Correct. The impact happened in the Hadean, Earth’s earliest eon.','The video places the impact very early.','The Moon formed from Earth’s material and Theia, after Earth began forming.','Dinosaurs lived billions of years later.'],
    steps:['Impact during the Hadean $\\to$ the Moon is nearly as old as Earth.']},
  ]}),
 lessonQuiz({lesson:'galaxies-and-other-objects-in-space',video:'rcLnMe1ELPA',reviewed:'2026-10-08',concept:'galaxies',chapter:'s_earth',
  keyIdea:'The Milky Way is a spiral galaxy whose main disc is about $100{,}000$ light years across, holding hundreds of billions of stars; we sit about $25{,}000$ light years from its centre, and because light takes time to travel, we see distant objects as they were when their light left them.',
  watchFor:[{at:78,text:'Listen for how long a very fast spacecraft would take to reach the nearest star.'},{at:305,text:'Listen for what we see when we look at an object $500$ light years away.'},{at:567,text:'Our distance from the centre of the galaxy is given.'}],
  practice:{url:'https://www.khanacademy.org/science/6th-grade-melcs/x88414687b4366ced:3rd-quarter/x88414687b4366ced:friction-and-gravity/e/understand-galaxies-and-gravity',label:'Understand: Galaxies and gravity',checked:'2026-10-08'},
  items:[
   {stem:'About how wide is the main disc of the Milky Way?',choices:['About $30$ light years','About $100{,}000$ light years','About $1{,}000$ light years','About $4.2$ light years'],key:1,
    miss:['local_neighbourhood',null,'thickness_as_width','nearest_star'],
    why:['$30$ light years is roughly our local neighbourhood of stars.','Correct. That is the rough diameter of the main disc.','$1{,}000$ light years is about the thickness of the disc.','$4.2$ light years is the distance to the nearest stars.'],
    steps:['Nearest star: about $4.2$ light years. Disc: about $100{,}000$ light years across.']},
   {stem:'Why do we see an object $500$ light years away as it was $500$ years ago?',choices:['The object is travelling backwards in time','Our telescopes are $500$ years old','Light slows down over long distances','Its light took $500$ years to reach us'],key:3,
    miss:['object_time_travel','telescope_age','light_slows',null],
    why:['Nothing travels back in time; the light is simply old.','Telescope age has nothing to do with it.','Light keeps the same speed; the distance is what takes time.','Correct. A light year is the distance light travels in a year.'],
    steps:['$500$ light years away $\\to$ $500$ years of travel for the light.']},
   {stem:'Light from a star cluster $2{,}000$ light years away reaches Earth today. When did it leave the cluster?',choices:['Today','About $2{,}000$ light years ago','About $2{,}000$ years ago','About $1{,}000$ years ago'],key:2,
    miss:['instant_light','year_unit_confusion',null,'halved_distance'],
    why:['Light takes time to travel; it does not arrive instantly.','A light year measures distance, not time.','Correct. Each light year of distance takes the light one year to cross.','The full distance takes $2{,}000$ years, not half of that.'],
    steps:['Distance in light years $=$ travel time in years.']},
   {stem:'A student says each small bright smudge in a photograph of the Milky Way’s centre is a single star. What is wrong?',choices:['Many smudges are thousands or millions of stars seen together from far away','Nothing; each smudge is one star','Each smudge is a planet','Each smudge is a separate galaxy outside the Milky Way'],key:0,
    miss:[null,'smudge_one_star','smudge_planet','smudge_galaxy'],
    why:['Correct. At such distances whole crowds of stars blur together.','The video stresses that many are huge groups of stars.','Planets would be far too faint to see this way.','The photograph looks towards our own galaxy’s centre.'],
    steps:['Huge distance $\\to$ many stars merge into one smudge.']},
  ]}),
];
