import {lessonQuiz} from './author.ts';

/** UPCAT Science: Biology. Original draft items written from Khan's timestamped caption
 * transcripts, read 2026-10-08; pending subject review.
 * Receipts: docs/THIRD_PARTY_MATERIALS.md, "Lesson quiz caption reviews". */
export const SCIENCE_BIOLOGY=[
 lessonQuiz({lesson:'characteristics-of-life-and-the-scientific-method',video:'N6IAzlugWw0',reviewed:'2026-10-08',concept:'scientific_method',chapter:'s_cells',
  keyIdea:'The scientific method turns an observation and a question into a testable explanation, a hypothesis, then tests a prediction in a controlled, reproducible experiment and refines the explanation using the results.',
  watchFor:[{at:87,text:'The first step is named. Note what was noticed about the pond and the ocean.'},{at:139,text:'Listen for the one property a good explanation must have.'},{at:327,text:'Before the cups go into the freezer, notice what is kept the same between them.'}],
  practice:{url:'https://www.khanacademy.org/science/als-k-to-12-science/x46c2fc9f8e023990:1st-quarter/x46c2fc9f8e023990:understanding-the-components-of-a-scientific-investigation/e/the-scientific-method-and-experimental-design',label:'The scientific method and experimental design',checked:'2026-10-08'},
  items:[
   {stem:'In the scientific method, what is a hypothesis?',choices:['A testable explanation for an observation','A fact that has already been proven','The data collected during an experiment','Any guess, whether or not it can be tested'],key:0,
    miss:[null,'hypothesis_as_fact','hypothesis_as_data','untestable_ok'],
    why:['Correct. A hypothesis explains an observation in a way an experiment can check.','A hypothesis has not been tested yet; testing is what comes next.','Data come from the experiment; the hypothesis comes before it.','An explanation that cannot be tested does not count as a scientific hypothesis.'],
    steps:['Observe, ask a question, then propose a testable explanation: the hypothesis.']},
   {stem:'Why is “a fairy freezes the pond faster” a poor scientific hypothesis?',choices:['Because the word “fairy” is not scientific vocabulary','Because a hypothesis must already be proven true','It cannot be tested, because there is no way to observe or control the fairy in an experiment','Because it is too short to be a hypothesis'],key:2,
    miss:['vocabulary_reason','hypothesis_as_fact',null,'length_reason'],
    why:['The problem is testability, not the choice of words.','No hypothesis is proven before it is tested.','Correct. A good hypothesis can be checked by an experiment that anyone can run.','Length has nothing to do with whether an idea can be tested.'],
    steps:['Ask: could an experiment show this explanation is wrong?','Nothing about the fairy can be observed or controlled, so it cannot be tested.']},
   {stem:'A student tests whether salt changes how fast ice melts. Which setup is the best controlled experiment?',choices:['One ice cube with salt in the sun and one without salt in the shade','Two identical ice cubes in identical cups in the same room, with salt added to only one','A single ice cube with salt, timed until it melts','Two cups holding different amounts of ice, both with salt'],key:1,
    miss:['two_variables',null,'no_comparison','variable_not_varied'],
    why:['Salt and sunlight both change, so you cannot tell which one caused a difference.','Correct. Only the salt differs, so any difference in melting can be traced to it.','Without a cube that has no salt, there is nothing to compare against.','Here salt is not varied at all, and the amount of ice differs instead.'],
    steps:['Change one variable, the salt.','Keep everything else the same, like the two cups in the video.']},
   {stem:'In an experiment, fresh water freezes but salt water does not, as predicted. A classmate says the hypothesis is now proven forever and nobody needs to check it again. What is wrong?',choices:['Nothing; one successful test proves a hypothesis','The hypothesis must be wrong, because its result was predicted','Experiments only matter when they fail','Results must be reproducible and stay open to testing; scientists repeat, refine and stay sceptical, even of their own work'],key:3,
    miss:['single_test_proof','prediction_invalidates','failure_only',null],
    why:['One test supports a hypothesis; it does not end the investigation.','A correct prediction supports a hypothesis rather than ruling it out.','Results that agree with a prediction are useful too.','Correct. Others must be able to repeat the test, and new questions lead to refinement.'],
    steps:['Science keeps testing: repeat the experiment, refine the explanation, ask new questions.']},
  ]}),
 lessonQuiz({lesson:'cell-structure-and-transport',video:'jQN07Hvq6WI',reviewed:'2026-10-08',
  keyIdea:'In passive transport, molecules move down their concentration gradient without the cell spending energy; the membrane lets small uncharged molecules such as oxygen and carbon dioxide through easily, water slowly, and ions or large molecules hardly at all.',
  watchFor:[{at:26,text:'A kind of transport is named. Listen for what it does not need.'},{at:91,text:'Two properties make crossing the membrane easy. Note both.'},{at:238,text:'Charged particles are considered. Watch where they get stuck.'}],
  practice:{url:'https://www.khanacademy.org/science/shs-biology-1/xca2b82fdfba136b8:unit-1-name/xca2b82fdfba136b8:cellular-transport/e/diffusion-and-osmosis',label:'Diffusion, osmosis, and tonicity',checked:'2026-10-08'},
  items:[
   {stem:'In passive transport, molecules move',choices:['from lower to higher concentration, using energy','from higher to lower concentration, without the cell using energy','only from outside the cell to inside','only when the cell pumps them across'],key:1,
    miss:['active_passive_swap',null,'one_direction','pump_required'],
    why:['Moving against the gradient with energy describes active transport.','Correct. Passive transport follows the concentration gradient and needs no energy.','Molecules can leave or enter; the gradient decides the net direction.','Pumping uses energy, which passive transport does not.'],
    steps:['Passive transport: down the concentration gradient, no energy needed.']},
   {stem:'Why does a sodium ion have trouble diffusing through the membrane on its own?',choices:['Its charge draws it to the water-loving heads, but the water-fearing tails in the middle of the membrane block it','It is too large to fit, like a big protein','Sodium always moves against its concentration gradient','The membrane has no gaps between its molecules at all'],key:0,
    miss:[null,'size_only','gradient_reversed','no_gaps'],
    why:['Correct. The hydrophobic middle offers nothing for a charged particle, so it cannot pass easily.','Sodium ions are small; their charge, not their size, is the problem.','Without help, particles tend to move down their gradient, not against it.','Small uncharged molecules do slip between the membrane molecules.'],
    steps:['Charged ions are attracted to the hydrophilic heads.','The hydrophobic tails stop them crossing on their own.']},
   {stem:'Which of these crosses a cell membrane most easily by simple diffusion?',choices:['A potassium ion, which carries a charge','A large protein molecule','Water, which crosses faster than oxygen does','Oxygen, $\\mathrm{O_{2}}$, which is small and uncharged'],key:3,
    miss:['charged_crosses','size_irrelevant','water_fastest',null],
    why:['Charged ions have difficulty crossing on their own.','Large molecules have trouble even fitting through the gaps.','Water is partly charged, so it crosses more slowly than oxygen.','Correct. Small size and no charge make diffusion through the membrane easy.'],
    steps:['Small and uncharged crosses best; charged or large crosses poorly.']},
   {stem:'A student says carbon dioxide leaves a cell because the cell wants to get rid of it. What is the better explanation?',choices:['The cell pumps carbon dioxide out using energy','Carbon dioxide is charged and is pushed away by the cell','With more carbon dioxide inside, more molecules hit the membrane from inside, so more cross outward than inward, with no intention or energy involved','Carbon dioxide only moves out when there is more of it outside'],key:2,
    miss:['active_passive_swap','charge_confusion',null,'gradient_reversed'],
    why:['Carbon dioxide diffuses passively; no pump is needed.','Carbon dioxide has no overall charge, which is why it crosses easily.','Correct. Random motion plus a concentration difference gives a net flow down the gradient.','Net movement is from more concentrated to less concentrated, so it leaves when there is more inside.'],
    steps:['Higher concentration inside means more collisions with the membrane from inside.','So the net movement is outward, by diffusion.']},
  ]}),
 lessonQuiz({lesson:'photosynthesis-and-cellular-respiration',video:'-rsYk4eCKnA',reviewed:'2026-10-08',
  keyIdea:'Photosynthesis uses light energy to turn carbon dioxide and water into carbohydrates and oxygen; the light-dependent reactions use light and water to make ATP, NADPH and oxygen, and the Calvin cycle uses these with carbon dioxide to build sugars.',
  watchFor:[{at:43,text:'The inputs and outputs are listed in simple terms first.'},{at:347,text:'The process is split into two stages. Note why one of the names is misleading.'},{at:466,text:'Follow where water goes in and where oxygen comes out.'}],
  practice:{url:'https://www.khanacademy.org/science/8th-grade-science-revised-k-to-10-3-terms/x7174210a6d38b11d:1st-quarter/x7174210a6d38b11d:photosynthesis-and-cellular-respiration/e/overview-of-photosynthesis',label:'Overview of photosynthesis',checked:'2026-10-08'},
  items:[
   {stem:'Which substances does photosynthesis take in?',choices:['Oxygen and sugar','Carbon dioxide and oxygen','Carbon dioxide and water, using light energy','Water and sugar'],key:2,
    miss:['reversed_equation','oxygen_input',null,'sugar_input'],
    why:['Oxygen and sugar are what cellular respiration uses; photosynthesis makes them.','Oxygen is released by photosynthesis, not taken in for it.','Correct. Light, carbon dioxide and water go in; carbohydrates and oxygen come out.','Sugar is a product of photosynthesis, not an input.'],
    steps:['Inputs: $\\mathrm{CO_{2}}$, $\\mathrm{H_{2}O}$ and light.','Outputs: carbohydrates and $\\mathrm{O_{2}}$.']},
   {stem:'Why is “light-independent reactions” a better name than “dark reactions” for the Calvin cycle?',choices:['Because they only happen at night','Because they are the stage that releases oxygen','Because they need more light than the other stage','They do not need light directly, but they still happen in daylight, using ATP and NADPH from the light-dependent reactions'],key:3,
    miss:['night_only','oxygen_source','more_light',null],
    why:['They run while the sun is out, as long as ATP and NADPH are supplied.','Oxygen is released in the light-dependent reactions.','They do not use light directly at all.','Correct. They depend on products of the light stage, not on photons themselves.'],
    steps:['Light-dependent reactions need photons.','The Calvin cycle needs their products, ATP and NADPH, but not photons.']},
   {stem:'A plant is kept in bright light but with no carbon dioxide available. Which stage is directly stopped?',choices:['The Calvin cycle, because it needs carbon dioxide to build sugars','The light-dependent reactions, because they take in carbon dioxide','Neither, because carbon dioxide is a product of photosynthesis','Both, because water can no longer enter the plant'],key:0,
    miss:[null,'co2_light_stage','co2_as_product','water_link'],
    why:['Correct. Carbon dioxide supplies the carbon that the Calvin cycle builds into sugars.','The light-dependent reactions take in light and water, not carbon dioxide.','Carbon dioxide is an input; oxygen and carbohydrates are the products.','Removing carbon dioxide does not stop water entering.'],
    steps:['Carbon dioxide enters at the Calvin cycle.','Without it, no sugars can be built.']},
   {stem:'A student says the oxygen released by plants comes from the carbon dioxide they take in. According to the video’s outline, where does it come from?',choices:['From carbon dioxide split in the Calvin cycle','From water, which goes into the light-dependent reactions as oxygen comes out','From glucose being broken down','From the soil, through the roots'],key:1,
    miss:['oxygen_from_co2',null,'respiration_confusion','soil_oxygen'],
    why:['The Calvin cycle uses carbon dioxide to build sugar; it does not release oxygen.','Correct. Water enters the light-dependent reactions, and molecular oxygen leaves them.','Breaking down glucose is respiration, which uses oxygen.','Oxygen is released from the leaves during the light-dependent reactions.'],
    steps:['Light-dependent reactions: water in, oxygen out, plus ATP and NADPH.']},
  ]}),
 lessonQuiz({lesson:'mitosis-and-meiosis',video:'IQJ4DBkCnco',reviewed:'2026-10-08',concept:'genetics',
  keyIdea:'Mitosis turns one diploid cell into two identical diploid cells and repeats as a cycle in body cells, while meiosis, in germ cells, uses two divisions to make four haploid gametes that are genetically different.',
  watchFor:[{at:12,text:'Mitosis starts from a cell with two sets of chromosomes. Note the symbol used.'},{at:118,text:'Meiosis has two rounds. Watch what happens to the chromosome number in the first.'},{at:240,text:'Listen for why meiosis is not called a cycle.'}],
  practice:{url:'https://www.khanacademy.org/science/strengthened-shs-biology-1/x12d91beacfa56326:cell-biology/x12d91beacfa56326:the-cell-cycle/e/meiosis-class-11-biology',label:'Meiosis',checked:'2026-10-08'},
  items:[
   {stem:'From one diploid cell, what does meiosis produce?',choices:['Two diploid cells','Four diploid cells','Two haploid cells','Four haploid cells'],key:3,
    miss:['mitosis_result','no_halving','one_division',null],
    why:['Two diploid cells is the result of mitosis.','The chromosome number is halved in meiosis I.','After meiosis I there are two haploid cells, but meiosis II divides each again.','Correct. Two divisions give four cells, each with one set of chromosomes.'],
    steps:['Meiosis I: one diploid cell becomes two haploid cells.','Meiosis II: each divides again, giving four haploid cells.']},
   {stem:'Why are the gametes made by meiosis not genetically identical to one another?',choices:['Because the DNA is not copied before meiosis','In meiosis I the homologous pairs separate randomly, so each cell gets a different mix of chromosomes from the mother and the father','Because meiosis repeats as a cycle','Because mitosis first mixes the chromosomes'],key:1,
    miss:['no_replication',null,'cycle_confusion','mitosis_mixing'],
    why:['DNA is copied during interphase before meiosis.','Correct. Random separation of pairs gives different combinations.','Meiosis is not a cycle; it ends with gametes.','Mitosis produces identical cells; it does not create the variety.'],
    steps:['Homologous pairs split in meiosis I.','Which member of each pair goes where is random, so gametes differ.']},
   {stem:'A fruit fly body cell has $8$ chromosomes. How many chromosomes does each of its gametes have?',choices:['$8$','$16$','$4$','$2$'],key:2,
    miss:['no_halving','doubled_number',null,'halved_twice'],
    why:['$8$ is the diploid number of a body cell.','Chromosome numbers are halved, not doubled, in meiosis.','Correct. Gametes are haploid, with half the diploid number.','The number is halved once, in meiosis I; meiosis II does not halve it again.'],
    steps:['Body cell: $2n = 8$.','Gamete: $n = 4$.']},
   {stem:'A student says skin cells divide by meiosis to replace damaged skin. What is wrong?',choices:['Body cells divide by mitosis, which keeps the diploid number; meiosis happens only in germ cells to make gametes','Nothing; all cells divide by meiosis','Skin cells cannot divide at all','Skin cells use meiosis and then fuse back together'],key:0,
    miss:[null,'meiosis_everywhere','no_division','fusion_confusion'],
    why:['Correct. Mitosis makes identical diploid cells for growth and repair.','Meiosis is limited to germ cells in the testes and ovaries.','Body cells grow and repair by mitosis.','Fusion of haploid cells happens at fertilisation, not in skin repair.'],
    steps:['Growth and repair: mitosis, in somatic cells.','Gametes: meiosis, in germ cells.']},
  ]}),
 lessonQuiz({lesson:'dna-rna-and-protein-synthesis',video:'6gUY5NoX1Lk',reviewed:'2026-10-08',concept:'genetics',
  keyIdea:'DNA is copied by using each strand as a template, with A pairing with T and G with C; a gene is transcribed into messenger RNA, with U in place of T, and ribosomes translate each three-base codon into an amino acid to build a protein.',
  watchFor:[{at:105,text:'The ladder is split in two. Watch how each half rebuilds the other.'},{at:487,text:'A copy is made that can leave the nucleus. Note which base is different.'},{at:734,text:'Count how many bases make one codon, and how many codons are possible.'}],
  practice:{url:'https://www.khanacademy.org/science/shs-biology-2/x2ea931c66bba6acd:3rd-quarter/x2ea931c66bba6acd:lesson-3-genetics-central-dogma/e/central-dogma',label:'Central dogma',checked:'2026-10-08'},
  items:[
   {stem:'During transcription, which RNA base pairs with adenine in the DNA?',choices:['Uracil','Thymine','Guanine','Cytosine'],key:0,
    miss:[null,'thymine_in_rna','wrong_pair','cg_confusion'],
    why:['Correct. RNA uses uracil where DNA uses thymine.','Thymine pairs with adenine in DNA, but RNA has uracil instead.','Guanine pairs with cytosine.','Cytosine pairs with guanine.'],
    steps:['DNA A pairs with RNA U; DNA T pairs with RNA A; G pairs with C.']},
   {stem:'Why can each strand of a DNA molecule serve as a template for a new strand?',choices:['Because both strands are identical copies of each other','Because RNA fills in the missing side','Because any base can pair with any other base','Bases pair in a fixed way, A with T and G with C, so one side determines the other'],key:3,
    miss:['identical_strands','rna_replication','random_pairing',null],
    why:['The strands are complementary, not identical.','DNA replication builds DNA; RNA is made in transcription.','If pairing were random, a strand could not specify its partner.','Correct. Knowing one strand tells you exactly what the partner strand must be.'],
    steps:['Separate the strands.','Build each new partner by the pairing rules: A with T, G with C.']},
   {stem:'A DNA template strand reads TAC GGA. Which messenger RNA is transcribed from it?',choices:['ATG CCT','UAC GGA','AUG CCU','AUG GGA'],key:2,
    miss:['thymine_in_rna','copied_template',null,'partial_pairing'],
    why:['RNA uses U, not T.','This copies the template with U swapped in, instead of pairing each base.','Correct. T to A, A to U, C to G, then G to C, G to C, A to U.','Only the first codon was paired; GGA must become CCU.'],
    steps:['Pair each base: T with A, A with U, C with G, G with C.','TAC GGA becomes AUG CCU.']},
   {stem:'A student says each single base codes for one amino acid. Why can that not work?',choices:['It can work; each base codes for five amino acids at once','Four bases could code for only $4$ amino acids, but there are $20$; reading three bases at a time gives $4 \\times 4 \\times 4 = 64$ codons','Reading two bases at a time would give exactly $20$','Proteins are built from bases, not from amino acids'],key:1,
    miss:['multi_coding',null,'pairs_enough','protein_of_bases'],
    why:['Each codon must point to one amino acid, or the message would be ambiguous.','Correct. Three-base codons give more than enough combinations.','Two bases give only $4 \\times 4 = 16$ combinations, fewer than $20$.','Proteins are chains of amino acids; the bases carry the code.'],
    steps:['One base: $4$ possibilities. Two bases: $16$. Three bases: $64$.','Only three-base codons cover $20$ amino acids.']},
  ]}),
 lessonQuiz({lesson:'inheritance-and-punnett-squares',video:'VH1lAfZL_fU',reviewed:'2026-10-08',
  keyIdea:'A Punnett square lists each parent’s possible alleles to show the equally likely offspring genotypes; with a dominant allele, any offspring carrying it shows the dominant trait, so a cross of two heterozygous parents gives a $3 : 1$ ratio.',
  watchFor:[{at:54,text:'Pause and decide what “heterozygous” means for the parents’ genotypes.'},{at:159,text:'The question asks about appearance, not genotype. Note which boxes give round seeds.'},{at:227,text:'A new cross pairs a homozygous recessive parent with a heterozygous one.'}],
  practice:{url:'https://www.khanacademy.org/science/shs-biology-2/x2ea931c66bba6acd:3rd-quarter/x2ea931c66bba6acd:lesson-1-genetics/e/punnett-squares',label:'Monohybrid punnett squares',checked:'2026-10-08'},
  items:[
   {stem:'What does it mean for a pea plant to be heterozygous for seed shape?',choices:['It has two dominant alleles, RR','It has two different alleles of the gene, such as Rr','It has wrinkled seeds','It has only one allele for the gene'],key:1,
    miss:['homozygous_dominant',null,'phenotype_as_genotype','single_allele'],
    why:['RR is homozygous dominant.','Correct. Hetero means different: one R and one r.','Seed shape is the phenotype; heterozygous describes the alleles.','Each plant carries two alleles of the gene, one from each parent.'],
    steps:['Heterozygous: two different alleles, Rr.']},
   {stem:'Why does an Rr plant have round seeds when R is dominant?',choices:['R and r blend to give a shape between round and wrinkled','The R allele came from the mother, and her allele always shows','One dominant allele is enough for the dominant trait to show','Having two alleles always gives round seeds'],key:2,
    miss:['blending','parent_decides',null,'count_decides'],
    why:['Dominance means no blending: the seeds are fully round.','Which parent gave the allele does not matter here.','Correct. A dominant allele is expressed even when paired with a recessive one.','rr also has two alleles and gives wrinkled seeds.'],
    steps:['R is dominant, so RR and Rr both show round seeds.','Only rr shows wrinkled seeds.']},
   {stem:'In guinea pigs, black fur (B) is dominant to white fur (b). What ratio of black to white offspring is expected from a cross between Bb and bb?',choices:['$1 : 1$','$3 : 1$','$1 : 0$','$1 : 3$'],key:0,
    miss:[null,'hetero_cross_ratio','all_dominant','reversed_ratio'],
    why:['Correct. Two boxes are Bb (black) and two are bb (white).','$3 : 1$ comes from crossing two heterozygous parents.','The bb parent can only give b, so white offspring are possible.','Black is dominant, so it is not the rarer outcome here.'],
    steps:['Bb gives B or b; bb gives b or b.','Boxes: Bb, Bb, bb, bb.','Black to white: $2 : 2 = 1 : 1$.']},
   {stem:'From a cross of two Rr plants, a student expects exactly $3$ round and $1$ wrinkled in every group of $4$ offspring. What is wrong?',choices:['Nothing; the ratio is guaranteed in every group of four','The ratio should be $1 : 1$','The ratio describes only genotypes, not seed shape','The $3 : 1$ ratio is an expected proportion over many offspring; each offspring independently has a $\\frac{3}{4}$ chance of round seeds'],key:3,
    miss:['ratio_guaranteed','wrong_ratio','genotype_only',null],
    why:['Like coin flips, four offspring will not always split exactly.','$1 : 1$ is for a cross between Rr and rr.','The $3 : 1$ ratio is for phenotype: round to wrinkled.','Correct. A Punnett square gives probabilities, so small groups can differ.'],
    steps:['Each offspring: $\\frac{3}{4}$ chance of round, $\\frac{1}{4}$ chance of wrinkled.','The $3 : 1$ ratio appears on average over many offspring.']},
  ]}),
 lessonQuiz({lesson:'evolution-and-natural-selection',video:'GcjgWov7mTM',reviewed:'2026-10-08',concept:'evolution',chapter:'s_genetics',
  keyIdea:'Natural selection acts on existing variation: when the environment changes, individuals whose random traits happen to suit it survive and reproduce more, so those traits become common; no organism decides to change.',
  watchFor:[{at:101,text:'A popular picture of evolution is questioned. Listen for what is wrong with it.'},{at:260,text:'A key word about populations is introduced. Note it.'},{at:394,text:'The trees darken. Predict which moths birds catch more often.'}],
  practice:{url:'https://www.khanacademy.org/science/als-k-to-12-science/x46c2fc9f8e023990:performance-standard-d-relate-how-science-and-technology-affect-people-s-beliefs-practices-and-ways-of-thinking/x46c2fc9f8e023990:evolution-adaptation-and-the-causes-of-extinction/e/natural-selection',label:'Natural selection',checked:'2026-10-08'},
  items:[
   {stem:'Natural selection needs which of these in a population?',choices:['Organisms deciding to change their traits','Every individual being identical','Variation among individuals in a trait that affects survival or reproduction','Changes made by effort during an organism’s life'],key:2,
    miss:['intentional_change','no_variation_needed',null,'use_disuse'],
    why:['Organisms do not choose their inherited traits.','Without variation there is nothing to select between.','Correct. Selection can only favour differences that already exist.','Traits gained by effort during life are not passed on through genes.'],
    steps:['Variation exists.','The environment favours some variants, which reproduce more.']},
   {stem:'Why did dark peppered moths become more common after soot darkened the trees?',choices:['Birds spotted light moths more easily on dark bark, so dark moths survived and reproduced more often','The moths chose to turn darker to hide','Soot dyed the moths’ wings','Pollution made dark moths lay more eggs'],key:0,
    miss:[null,'intentional_change','environment_paints','pollution_fertility'],
    why:['Correct. Predators removed more light moths, so the dark variant spread.','No moth decided anything; the variation was already there.','The colour is inherited, not painted on by soot.','The difference came from survival, not from egg-laying.'],
    steps:['Variation: light and dark moths.','Selection: birds see light moths on dark bark.','Result: dark moths become common.']},
   {stem:'A farm sprays the same insecticide every week for years. Most pests now survive it. What is the best explanation?',choices:['The pests learned to resist the spray','The spray caused every pest to mutate in a helpful way','The spray became weaker with age','A few pests could already resist it; they survived and reproduced while the others died'],key:3,
    miss:['learned_resistance','directed_mutation','weaker_spray',null],
    why:['Resistance is inherited, not learned.','Mutations are random; the spray does not create helpful ones on demand.','The pests changed; the explanation does not need a weaker spray.','Correct. Like antibiotic-resistant bacteria, the spray selected for resistant variants.'],
    steps:['Resistant variants existed by chance.','Spraying removed their competitors, so they multiplied.']},
   {stem:'A student says giraffes got long necks because their ancestors kept stretching to reach high leaves. What does natural selection say instead?',choices:['The student is right; stretching lengthens the necks of the offspring','Ancestors already varied in neck length; those with longer necks may have survived and reproduced more, passing on the trait','Necks grew because the giraffes wanted them to','Giraffe necks have never changed'],key:1,
    miss:['use_disuse',null,'intentional_change','no_change'],
    why:['Stretching during life does not change the genes passed on.','Correct. Selection works on inherited variation that is already present.','Wanting a trait does not produce it.','Natural selection is about traits changing in frequency over generations.'],
    steps:['Start with variation in neck length.','Longer-necked individuals may reproduce more, so the trait spreads.']},
  ]}),
 lessonQuiz({lesson:'classification-and-biodiversity',video:'oHvLlS_Sc54',reviewed:'2026-10-08',concept:'classification',chapter:'s_genetics',
  keyIdea:'Taxonomy groups living things into nested ranks, from domain and kingdom down to genus and species; a species is named by its genus and species, as in Homo sapiens, and DNA comparisons now help show how closely species are related.',
  watchFor:[{at:55,text:'Listen for how similar species are gathered into larger groups.'},{at:109,text:'Two tools unknown to the father of taxonomy are mentioned. Note them.'},{at:354,text:'A naming convention is explained. Note which word is capitalised.'}],
  practice:{url:'https://www.khanacademy.org/science/shs-biology-2/x2ea931c66bba6acd:3rd-quarter/x2ea931c66bba6acd:lesson-3-systematics-based-on-evolutionary-relationships/e/phylogeny',label:'Phylogeny',checked:'2026-10-08'},
  items:[
   {stem:'In the name Homo sapiens, what does Homo identify?',choices:['The species on its own','The family','The kingdom','The genus'],key:3,
    miss:['species_genus_swap','rank_confusion','rank_confusion_high',null],
    why:['The species is named by sapiens together with the genus.','Humans are in the family Hominidae, which is broader than the genus.','The kingdom is Animalia, far broader.','Correct. The first word is the genus; the second names the species.'],
    steps:['Scientific name: Genus species.','Homo is the genus.']},
   {stem:'Why is DNA comparison now used to help classify organisms?',choices:['Because all organisms with DNA belong to the same species','Because the founder of taxonomy classified organisms by DNA','Similar DNA shows how recently two species shared a common ancestor, which body features alone may miss','Because DNA removes the need for any groups'],key:2,
    miss:['dna_same_species','anachronism',null,'no_groups'],
    why:['Nearly all living things have DNA, across many species.','He relied on observation; DNA tools came much later.','Correct. DNA gives a more systematic measure of how related two species are.','Groups are still used; DNA helps decide where boundaries go.'],
    steps:['More shared DNA suggests a more recent common ancestor.']},
   {stem:'Which list runs from the broadest group to the narrowest?',choices:['Species, genus, family, order, class, phylum, kingdom','Kingdom, phylum, class, order, family, genus, species','Kingdom, class, phylum, order, family, genus, species','Kingdom, phylum, order, class, family, species, genus'],key:1,
    miss:['reversed_order',null,'phylum_class_swap','mixed_order'],
    why:['This runs from narrowest to broadest.','Correct. Each rank sits inside the one before it.','Phylum is broader than class.','Class is broader than order, and genus is broader than species.'],
    steps:['Broadest to narrowest: kingdom, phylum, class, order, family, genus, species.']},
   {stem:'A student writes the chimpanzee’s scientific name as troglodytes Pan. What is wrong?',choices:['The genus comes first and is capitalised, then the species in lower case: Pan troglodytes','Nothing; the order of the words does not matter','Both words must be capitalised: Troglodytes Pan','Scientific names use the family, not the genus'],key:0,
    miss:[null,'order_irrelevant','capitalise_both','family_naming'],
    why:['Correct. Genus first, capitalised; species second, lower case.','The order is part of the convention.','Only the genus is capitalised.','The two-part name uses the genus and the species.'],
    steps:['Genus: Pan. Species: troglodytes.','Written: Pan troglodytes.']},
  ]}),
 lessonQuiz({lesson:'human-body-systems',video:'QhiVnFvshZg',reviewed:'2026-10-08',concept:'body_systems',chapter:'s_cells',
  keyIdea:'The right side of the heart pumps deoxygenated blood through the pulmonary arteries to the lungs, oxygenated blood returns through the pulmonary veins to the left side, and the left ventricle pumps it through the aorta to the body; arteries carry blood away from the heart and veins carry it back.',
  watchFor:[{at:42,text:'Listen for why hemoglobin is packed inside red blood cells.'},{at:275,text:'Notice which pulmonary vessel carries blood with little oxygen.'},{at:351,text:'Follow blood from the body back into the heart, one chamber at a time.'}],
  practice:{url:'https://www.khanacademy.org/science/shs-biology-2/x2ea931c66bba6acd:unit-1-name/x2ea931c66bba6acd:animal-circulatory-system/e/hs-the-circulatory-and-respiratory-systems',label:'The circulatory and respiratory systems',checked:'2026-10-08'},
  items:[
   {stem:'Which vessel carries blood away from the heart to the lungs?',choices:['The pulmonary artery','The pulmonary vein','The aorta','The inferior vena cava'],key:0,
    miss:[null,'artery_vein_swap','systemic_confusion','vena_cava_confusion'],
    why:['Correct. It leaves the right ventricle and heads to the lungs.','The pulmonary vein brings blood back from the lungs.','The aorta carries blood to the rest of the body.','The vena cava returns blood from the body to the heart.'],
    steps:['Right ventricle, then pulmonary artery, then lungs.']},
   {stem:'Why is the pulmonary artery called an artery even though its blood carries little oxygen?',choices:['Because every artery carries oxygen-rich blood','Arteries are named for carrying blood away from the heart, not for how much oxygen the blood holds','Because it is larger than any vein','It is not; it is really a vein'],key:1,
    miss:['artery_means_oxygen',null,'size_defines','vein_label'],
    why:['The pulmonary artery is the exception that shows this is false.','Correct. Direction decides the name: away from the heart means artery.','Size does not decide whether a vessel is an artery.','It carries blood away from the heart, so it is an artery.'],
    steps:['Artery: away from the heart. Vein: towards the heart.']},
   {stem:'A red blood cell has just returned from the leg. In which order does it travel next?',choices:['Left atrium, left ventricle, lungs, right atrium, right ventricle, aorta','Right atrium, left atrium, lungs, right ventricle, left ventricle, aorta','Right ventricle, right atrium, lungs, left ventricle, left atrium, aorta','Right atrium, right ventricle, lungs, left atrium, left ventricle, aorta'],key:3,
    miss:['sides_swapped','atria_first','ventricle_first',null],
    why:['Blood from the body enters the right side first.','Each atrium passes blood to the ventricle on its own side.','Blood enters an atrium before its ventricle.','Correct. Body to right side, to lungs, to left side, to body.'],
    steps:['Vena cava into the right atrium, then the right ventricle.','Pulmonary artery to the lungs, pulmonary vein to the left atrium.','Left ventricle into the aorta.']},
   {stem:'Looking at a heart diagram that faces them, a student labels the chamber on the viewer’s left as the left atrium. What is wrong?',choices:['Nothing; diagrams use the viewer’s left and right','Atria are always drawn at the bottom of the heart','Left and right refer to the owner’s sides, so the chamber on the viewer’s left is the right atrium','The left atrium is the chamber that receives blood from the body'],key:2,
    miss:['viewer_left','position_confusion',null,'left_receives_body'],
    why:['Heart diagrams use the body’s own left and right.','The atria are the upper chambers.','Correct. The heart is facing you, so its right side is on your left.','The left atrium receives oxygenated blood from the lungs.'],
    steps:['Imagine the heart’s owner facing you.','Their right side is on your left.']},
  ]}),
 lessonQuiz({lesson:'plant-structure-and-function',video:'d60lqIfGeQw',reviewed:'2026-10-08',concept:'plant_transport',chapter:'s_cells',
  keyIdea:'Xylem is a tube of dead cells that carries water and minerals upward; evaporation from the leaves, called transpiration, pulls the connected water column up by day, and root pressure from osmosis pushes it up at night.',
  watchFor:[{at:25,text:'Listen for the surprising share of absorbed water that a tree loses.'},{at:132,text:'Find out what xylem is made from.'},{at:529,text:'At night there is little transpiration. Note the second force that keeps the water up.'}],
  practice:{url:'https://www.khanacademy.org/science/shs-biology-2/x2ea931c66bba6acd:unit-1-name/x2ea931c66bba6acd:plant-transportation/e/transportation-in-plants',label:'Transportation in plants',checked:'2026-10-08'},
  items:[
   {stem:'What does xylem mainly carry?',choices:['Food made in the leaves','Water and dissolved minerals','Oxygen gas to the roots','Energy from sunlight'],key:1,
    miss:['phloem_role',null,'gas_transport','energy_transport'],
    why:['Food is carried by phloem.','Correct. Xylem carries water and minerals up from the roots.','Xylem is a water pipe, not a gas pipe.','Sunlight is captured in the leaves, not carried by xylem.'],
    steps:['Xylem: water and minerals. Phloem: food.']},
   {stem:'How does evaporation at the leaves move water up from the roots?',choices:['Evaporation pushes water down so the roots squeeze it back up','Living xylem cells pump the water upward','Gravity works in reverse inside a tree','Water molecules attract one another, so as some leave through the stomata they pull the whole connected column upward'],key:3,
    miss:['push_confusion','living_xylem','gravity_reverse',null],
    why:['The force starts at the leaves and pulls; it does not push down.','Xylem cells are dead and do not pump.','Gravity still pulls down; the column is pulled up by attraction between water molecules.','Correct. Like sucking on a straw, losing water at the top pulls the column up.'],
    steps:['Water evaporates from the leaves.','Attraction between water molecules pulls the column up the xylem.']},
   {stem:'How does transpiration on a hot, dry afternoon compare with a cool night, and why?',choices:['It is higher at night, because root pressure is stronger then','It is the same, because transpiration does not depend on heat','It is higher in the afternoon, because heat speeds up evaporation from the leaves','It is zero in the afternoon, because stomata never open in heat'],key:2,
    miss:['night_higher','no_heat',null,'stomata_never_open'],
    why:['Root pressure is what remains at night, but it is not transpiration.','Evaporation depends strongly on heat.','Correct. Transpiration is evaporation, which needs heat; at night it is low.','Stomata do open in the day; that is when transpiration is highest.'],
    steps:['Transpiration is evaporation from leaves.','More heat means more evaporation.']},
   {stem:'A student says xylem must be made of living cells because it moves water. What is correct?',choices:['Xylem cells are dead and hollow; water is pulled by transpiration and pushed by root pressure, not moved by the cells','The student is right; living xylem cells pump the water','Xylem is living, and phloem is the tissue made of dead cells','Xylem cells come alive only at night'],key:0,
    miss:[null,'living_xylem','xylem_phloem_swap','night_alive'],
    why:['Correct. Mature xylem cells lose their contents and form empty pipes.','The forces come from evaporation and from the roots, not from xylem cells.','It is the other way round: phloem is made of living cells.','Dead cells do not come back to life; root pressure works at night.'],
    steps:['Xylem forms from cells that lose their contents and die.','Transpiration and root pressure move the water.']},
  ]}),
 lessonQuiz({lesson:'enzymes-and-cellular-metabolism',video:'A90HKrgUOg0',reviewed:'2026-10-08',concept:'cells_life',chapter:'s_cells',
  keyIdea:'Enzymes, mostly proteins, speed up reactions by lowering the activation energy; substrates bind at the active site, the enzyme may close around them (induced fit), and the enzyme is released unchanged to work again.',
  watchFor:[{at:77,text:'A reaction that releases energy still needs a push to start. Note the name of that push.'},{at:255,text:'Find the name of the place where the substrates bind.'},{at:318,text:'Listen for what can stop an enzyme working.'}],
  practice:{url:'https://www.khanacademy.org/science/shs-biology-1/xca2b82fdfba136b8:unit-1-name/xca2b82fdfba136b8:enzymes/e/enzymes-and-the-mechanism-of-enzyme-activity',label:'Enzymes and enzyme activity',checked:'2026-10-08'},
  items:[
   {stem:'What is the active site of an enzyme?',choices:['The product released at the end','The energy given off by the reaction','The region where the substrates bind and react','Any place in the cell where reactions happen'],key:2,
    miss:['site_as_product','site_as_energy',null,'site_as_location'],
    why:['Products are released from the active site; they are not the site.','The active site is a part of the enzyme, not energy.','Correct. The active site is where the action is.','The active site is a specific region of the enzyme itself.'],
    steps:['Substrates bind at the active site, where the reaction is helped along.']},
   {stem:'How does an enzyme make a reaction happen faster?',choices:['It adds energy so the products have more energy','It lowers the activation energy, for example by positioning the substrates and drawing charges away','It is used up and becomes part of the products','It turns a reaction that releases energy into one that absorbs it'],key:1,
    miss:['adds_energy',null,'consumed_enzyme','reverses_reaction'],
    why:['The overall energy change is the same; only the hump is lowered.','Correct. A lower hump means the reaction proceeds more easily.','The enzyme is released unchanged.','An enzyme does not change whether a reaction releases energy.'],
    steps:['Activation energy is the push a reaction needs to start.','Enzymes lower it, so the reaction happens faster.']},
   {stem:'An enzyme from the human body is heated to a very high temperature and then cooled, and it no longer works. What is the best explanation?',choices:['The heat denatured it, changing the shape it needs to bind its substrates','It was used up by too many reactions','Heat always helps enzymes, so the cooling must have damaged it','The cooling destroyed its substrates'],key:0,
    miss:[null,'consumed_enzyme','heat_always_helps','substrate_damage'],
    why:['Correct. Too much heat makes a protein lose its structure.','Enzymes are reused, not used up.','Moderate warming speeds reactions, but too much heat denatures enzymes.','The enzyme is what changed; fresh substrates would still not react.'],
    steps:['Enzymes are proteins with specific shapes.','High heat denatures them, so they stop working.']},
   {stem:'A student says each enzyme molecule can catalyse only one reaction before it is used up. What is correct?',choices:['The student is right; enzymes are consumed like substrates','One enzyme catalyses every reaction in the cell','Enzymes work once but can be recharged with ATP','An enzyme is released unchanged after each reaction and can catalyse the same reaction many times'],key:3,
    miss:['consumed_enzyme','enzyme_universal','atp_recharge',null],
    why:['Substrates are changed; the enzyme is not.','Each enzyme helps specific reactions with specific substrates.','No recharging is needed; the enzyme is unchanged.','Correct. One enzyme can act over and over during its life.'],
    steps:['Substrates bind, react and leave as products.','The enzyme is free to bind new substrates.']},
  ]}),
 lessonQuiz({lesson:'nutrient-cycles-in-ecosystems',video:'DsCMYyQ0NWU',reviewed:'2026-10-08',concept:'ecosystems',chapter:'s_cells',
  keyIdea:'Most nitrogen is in the air as $\\mathrm{N_{2}}$, which plants cannot use directly; nitrogen-fixing bacteria turn it into ammonia that plants take up, animals get nitrogen by eating plants, and decomposers and other bacteria return it to the soil and air.',
  watchFor:[{at:14,text:'Note how much of the atmosphere is nitrogen.'},{at:68,text:'Listen for which organisms can fix nitrogen from the air.'},{at:227,text:'When an organism dies, follow where its nitrogen goes.'}],
  practice:{url:'https://www.khanacademy.org/science/ap-college-environmental-science/x0b0e430a38ebd23f:the-living-world-ecosystems-and-biodiversity/x0b0e430a38ebd23f:biogeochemical-cycles/e/biogeochemical-cycles-exercise',label:'Biogeochemical cycles',checked:'2026-10-08'},
  items:[
   {stem:'Which organisms can fix nitrogen gas from the air?',choices:['Plants, through their leaves','Animals, through breathing','No organisms at all','Certain bacteria and other prokaryotes'],key:3,
    miss:['plants_fix','animals_fix','no_fixers',null],
    why:['Plants cannot use $\\mathrm{N_{2}}$ directly.','Animals breathe nitrogen in and out unchanged.','Bacteria do fix nitrogen; that is the key step in the cycle.','Correct. Nitrogen-fixing prokaryotes turn $\\mathrm{N_{2}}$ into ammonia.'],
    steps:['$\\mathrm{N_{2}}$ in the air is fixed by bacteria into ammonia, $\\mathrm{NH_{3}}$.']},
   {stem:'Why do living things need nitrogen?',choices:['It is part of key molecules such as amino acids, ATP and DNA','It is the main source of energy in food','It is needed only for breathing','It replaces carbon in sugars'],key:0,
    miss:[null,'nitrogen_energy','breathing_only','replaces_carbon'],
    why:['Correct. Proteins, energy carriers and genetic material all contain nitrogen.','Energy in food is stored mainly in carbon bonds.','We breathe nitrogen in and out without using it.','Sugars are made of carbon, hydrogen and oxygen.'],
    steps:['Amino acids, ATP and DNA all contain nitrogen.']},
   {stem:'A farmer adds a nitrogen fertiliser to a field. Why might the crops grow faster?',choices:['The fertiliser lets the plants fix nitrogen from the air themselves','Usable nitrogen in the soil often limits growth, so adding it removes that limit','Nitrogen gives the plants extra light energy','Plants grow faster whenever any gas is added to the soil'],key:1,
    miss:['plants_fix',null,'nitrogen_energy','any_gas'],
    why:['Plants still cannot fix $\\mathrm{N_{2}}$; the fertiliser supplies usable nitrogen.','Correct. Nitrogen is often the rate-limiting nutrient for plants.','Light energy comes from the sun, not from nitrogen.','It is the nitrogen in a usable form that matters.'],
    steps:['Growth needs nitrogen for proteins and DNA.','Adding usable nitrogen lets growth speed up.']},
   {stem:'A student says that because air is $78\\%$ nitrogen, plants never run short of it. What is wrong?',choices:['Nothing; plants absorb $\\mathrm{N_{2}}$ through their leaves','Air is mostly oxygen, not nitrogen','Plants cannot use $\\mathrm{N_{2}}$ directly; it must first be fixed into a form such as ammonia, mostly by bacteria','Plants do not need nitrogen at all'],key:2,
    miss:['plants_fix','air_composition',null,'no_need'],
    why:['Plants rely on fixed nitrogen in the soil.','About $78\\%$ of air is nitrogen.','Correct. Plenty of $\\mathrm{N_{2}}$ in the air does not help until it is fixed.','Plants need nitrogen for amino acids and DNA.'],
    steps:['$\\mathrm{N_{2}}$ is abundant but unusable by plants.','Fixation by bacteria makes it usable.']},
  ]}),
];
