import type {TopicGuide} from './topic-guides.ts';

/** Original notes for the owner's expanded UPCAT outline. Draft teaching material;
 * specialist review is pending. Revealed answers are support, never scored evidence. */
const g=(idea:string,example:string,question:string,answer:string,trap:string):TopicGuide=>({idea,example,question,answer,trap});
export const EXPANDED_TOPIC_GUIDES:Record<string,TopicGuide>={
 'Word relationships and analogies':g(
  'Name the relationship between the first pair, then apply that same relationship in the same direction to the second pair.',
  'A seed grows into a plant; an egg develops into an animal. The relationship is an early stage to the organism it can become.',
  'Painter is to brush as writer is to what, if the relationship is a person to a tool?',
  'A pen or keyboard fits the stated tool relationship. A book is a product rather than a tool.',
  'Two words sharing a subject is weaker than matching the exact relationship.'),
 'Finding and correcting sentence errors':g(
  'Check one layer at a time: subject and verb, pronoun reference, verb tense, complete clauses, modifiers and parallel structure. Change only what the error requires.',
  '“The list of supplies are ready.” The subject is list, not supplies. Correct it to “The list of supplies is ready.”',
  'Correct “She enjoys reading, swimming and to paint.”',
  '“She enjoys reading, swimming and painting.” The three activities now share the same grammatical form.',
  'A nearby plural noun can distract you from the actual singular subject.'),
 'Organizing paragraphs and transitions':g(
  'Identify the paragraph’s main point, then place support in an order that follows its logic. Choose a transition that names the actual relationship: contrast, cause, example or sequence.',
  '“The seedlings received enough water. However, they wilted in the heat.” However signals an unexpected contrast, not another step in a timeline.',
  'Which transition fits “The bus broke down. ___, the passengers arrived late”: Therefore or Similarly?',
  'Therefore, because the breakdown is given as the cause of the delay.',
  'A transition cannot repair a missing logical link between unrelated sentences.'),
 'Mga bahagi ng pananalita':g(
  'Kilalanin ang tungkulin ng salita sa pangungusap: ang pangngalan ay ngalan, ang panghalip ay pamalit dito, ang pandiwa ay kilos o pangyayari, at ang pang-uri ay naglalarawan ng pangngalan.',
  'Sa “Masipag na nag-aaral si Liza,” ang nag-aaral ay pandiwa. Sa “Masipag na mag-aaral si Liza,” ang mag-aaral ay pangngalan.',
  'Sa “Mabilis tumakbo si Ana,” ano ang tungkulin ng mabilis?',
  'Pang-abay ito dahil inilalarawan nito ang kilos na tumakbo.',
  'Maaaring magbago ang bahagi ng pananalita ayon sa gamit ng salita sa pangungusap.'),
 'Panlapi at pagbuo ng salita':g(
  'Hanapin muna ang salitang-ugat, saka tukuyin kung paano binabago ng panlapi ang kahulugan o gamit nito. Maaaring nasa unahan, gitna o hulihan ang panlapi.',
  'Sa sumulat, ang ugat ay sulat at ang gitlapi ay -um-. Sa sulatan, ang hulapi ay -an.',
  'Ano ang ugat at panlapi sa magluto?',
  'Luto ang ugat at mag- ang unlapi.',
  'Hindi lahat ng magkaparehong simula ng salita ay may iisang ugat o kahulugan.'),
 'Simuno at panaguri':g(
  'Ang simuno ang pinag-uusapan; ang panaguri ang sinasabi tungkol dito. Maaaring mauna ang panaguri sa karaniwang ayos.',
  'Sa “Nagbabasa si Mina,” si Mina ang simuno at nagbabasa ang panaguri. Sa “Si Mina ay nagbabasa,” pareho pa rin ang kanilang tungkulin.',
  'Ano ang simuno sa “Maliwanag ang silid”?',
  'Ang silid ang simuno; maliwanag ang panaguri.',
  'Hindi awtomatikong simuno ang unang salita ng pangungusap.'),
 'Pagkilala at pagwawasto ng mali':g(
  'Basahin muna ang buong pangungusap. Suriin ang ugnayan ng mga salita, wastong anyo ng pandiwa, panghalip, pang-ugnay, baybay at bantas bago pumili ng pagwawasto.',
  'Sa “Naglakad ng mabilis si Leo,” ang mabilis ay naglalarawan ng kilos. Ang wastong gamit ay “Naglakad nang mabilis si Leo.”',
  'Itama ang “Bumili nang aklat si Lia.”',
  '“Bumili ng aklat si Lia.” Ipinakikilala ng ng ang bagay na binili.',
  'Huwag baguhin ang kahulugan kung ang kailangang ayusin ay isang pang-ugnay lamang.'),
 'Pag-aayos ng talata at pangungusap':g(
  'Hanapin ang pangunahing ideya. Ayusin ang mga pangungusap ayon sa panahon, sanhi at bunga, o paliwanag at halimbawa. Tiyaking malinaw ang tinutukoy ng mga panghalip.',
  'Unang ipinakilala si Ben bago gamitin ang siya. Kung wala pang malinaw na tinutukoy, maaaring malito ang mambabasa.',
  'Ano ang wastong pagkakasunod: “Diniligan niya ang halaman,” “Nagtanim si Ben ng buto,” “Tumubo ito”?',
  'Nagtanim si Ben ng buto; diniligan niya ang halaman; tumubo ito.',
  'Ang magandang tunog ng pangungusap ay hindi sapat kung salungat ang pagkakasunod ng mga pangyayari.'),
 'Comparing ideas in a passage':g(
  'Compare the same feature on both sides. Separate similarities, differences and the author’s reasons instead of assuming two passages make the same argument.',
  'Both writers favor cleaner transport. One emphasizes cost; the other emphasizes public health. Their shared goal does not make their supporting reasons identical.',
  'If two passages support recycling but only one discusses jobs, is employment a shared argument?',
  'No. It is supported only by the passage that discusses jobs.',
  'A shared keyword does not establish a shared claim.'),
 'Literary analysis and interpreting evidence':g(
  'Make a claim about the text, choose a specific detail, and explain how that detail supports the claim. Distinguish the narrator’s words from the author’s own beliefs.',
  'A character checks the door repeatedly before speaking. That behavior can support an inference of anxiety; explain the connection rather than merely quoting it.',
  'Does a character saying “I am fearless” prove the character never feels fear?',
  'No. Compare the statement with actions and context; the speaker may be unreliable or trying to appear brave.',
  'Retelling the plot without explaining evidence is different from analysis.'),
 'Comic strips':g(
  'Read panel order, dialogue, captions and visual details together. Notice how a final panel changes the meaning of an earlier one.',
  'A character says “Perfect weather!” while standing under a leaking roof in a storm. The picture makes the words ironic.',
  'If a character’s words say one thing but the facial expression suggests another, what should you use?',
  'Both. Explain how the visual detail changes or qualifies the spoken message.',
  'Reading only the speech bubbles can miss the evidence that creates the joke or inference.'),
 'Novel excerpts':g(
  'Use the excerpt’s own setting, narration, dialogue and actions. Infer relationships or motives from details without inventing events from the rest of the novel.',
  'A narrator describes an unopened letter beside the door and a character avoiding it. This suggests reluctance, but the excerpt must support any proposed reason.',
  'Can you assume the letter contains bad news without further evidence?',
  'No. Reluctance is an inference; the exact contents remain unknown.',
  'Background knowledge about a familiar novel should not replace the evidence provided in the question.'),
 'Practical texts and visual messages':g(
  'Identify the intended audience, required action, conditions and source. Combine text with headings, symbols, layout and any chart labels.',
  'A notice says “Registration closes Friday at noon.” A large date is useful only when read together with the closing time and any eligibility rules.',
  'If an advertisement says “up to 50% off,” does every item cost half its original price?',
  'No. Up to gives a maximum discount; individual items may have smaller discounts.',
  'Prominent wording can omit a condition that appears in smaller text.'),
 'Pangunahing ideya at buod':g(
  'Ang pangunahing ideya ang pinakasentrong mensahe ng teksto. Sa buod, panatilihin ang mahahalagang ideya at alisin ang paulit-ulit na detalye at sariling opinyon.',
  'Kung ipinaliliwanag ng talata ang pagtitipid ng tubig sa bahay, maaaring halimbawa lamang ang pagsasara ng gripo at pagkukumpuni ng tagas.',
  'Dapat bang isama sa buod ang iyong sariling mungkahing wala sa teksto?',
  'Hindi. Ang buod ay tapat na pinaikling paglalahad ng teksto.',
  'Maaaring mahalagang detalye ang unang pangungusap nang hindi ito ang buong pangunahing ideya.'),
 'Detalye at ebidensiya sa teksto':g(
  'Hanapin ang mismong pahayag o detalyeng sumusuporta sa sagot. Ihiwalay ang tuwirang sinabi sa tekstong dapat pang mahinuha.',
  'Kung nakasaad na nagsara ang paaralan dahil sa baha, ang baha ang tuwirang ibinigay na dahilan.',
  'Kung sinabing dumating si Ana bago si Ben, sino ang unang dumating?',
  'Si Ana. Tuwirang ipinapakita ito ng bago.',
  'Ang maaaring totoo sa karaniwang buhay ay hindi awtomatikong ebidensiya mula sa teksto.'),
 'Paghihinuha at kongklusyon':g(
  'Pagsamahin ang mga detalye upang makabuo ng makatwirang ideyang hindi tahasang sinabi. Piliin ang kongklusyong may sapat na suporta at hindi labis sa ebidensiya.',
  'May dalang basang payong si Rosa at may putik ang kanyang sapatos. Maaaring naharap siya sa ulan; hindi pa nito pinatutunayan kung saan siya nanggaling.',
  'Pinatutunayan ba ng basang payong na maghapon umulan?',
  'Hindi. Walang sapat na detalye tungkol sa tagal ng ulan.',
  'Ang paghihinuha ay hindi lisensiyang magdagdag ng anumang posibleng pangyayari.'),
 'Layunin, tono at pananaw ng may-akda':g(
  'Suriin kung ano ang nais gawin ng may-akda: magpaliwanag, manghikayat o maglahad ng karanasan. Ang tono ay saloobing ipinapakita ng mga salita; ang pananaw ay posisyong pinagmumulan ng paglalahad.',
  'Ang panawagang “Makilahok tayo sa paglilinis ng ilog” ay maaaring manghikayat. Ang pagbanggit ng datos ay maaaring suporta sa layuning iyon.',
  'Sapat bang may datos ang teksto upang sabihing wala itong layuning manghikayat?',
  'Hindi. Maaaring gamitin ang datos sa panghihikayat; basahin ang buong mensahe.',
  'Ihiwalay ang sariling damdamin bilang mambabasa sa tonong ipinapakita ng may-akda.'),
 'Kahulugan ng salita sa binasa':g(
  'Gamitin ang kalapit na paliwanag, halimbawa, paghahambing o pagsalungat. Subukan ang payak na kapalit ng salita at basahing muli ang pangungusap.',
  'Sa “Payapa ang silid, malayo sa maingay na lansangan,” ipinapakita ng pagsalungat na tahimik ang kahulugan ng payapa.',
  'Ano ang marupok sa “Ingatan ang marupok na baso; madali itong mabasag”?',
  'Madaling masira o mabasag.',
  'Piliin ang kahulugang akma sa gamit sa teksto, hindi lamang ang unang kahulugang naaalala.'),
 'Sanhi, bunga at pagkakasunod-sunod':g(
  'Ang sanhi ang dahilan; ang bunga ang resulta. Ang pagkakasunod-sunod ay ayos ng mga pangyayari, na hindi laging patunay na sanhi ng isa ang isa pa.',
  '“Dahil bumaha, kinansela ang biyahe.” Sanhi: baha. Bunga: pagkansela. Iba ito sa dalawang pangyayaring magkasunod lamang.',
  'Sa “Una niyang binasa ang panuto, saka sinagutan ang papel,” ano ang unang ginawa?',
  'Binasa ang panuto. Sinasabi nito ang ayos, ngunit hindi sapat upang patunayang tama ang lahat ng sagot.',
  'Huwag ipagpalit ang pagkatapos sa dahil.'),
 'Paghahambing at pagsusuring pampanitikan':g(
  'Pumili ng iisang batayan ng paghahambing, gaya ng tauhan, tema o paraan ng paglalahad. Gumamit ng detalye sa bawat akda at ipaliwanag ang pagkakatulad o pagkakaiba.',
  'Parehong tumatalakay sa pag-asa ang dalawang tula, ngunit ang isa ay gumagamit ng larawan ng umaga at ang isa ay ng paglalakbay.',
  'Sapat bang pareho ang paksa upang sabihing pareho ang mensahe?',
  'Hindi. Kailangang suriin ang mga detalye, tono at pahayag ng bawat akda.',
  'Ang pagbubuod ng dalawang akda nang magkahiwalay ay hindi pa malinaw na paghahambing.'),
 'Sets and Venn diagrams':g(
  'A set is a well-defined collection. A Venn diagram shows membership and overlap. Union includes members in either set; intersection includes members in both.',
  'Of 20 learners, 12 like math, 9 like science and 5 like both. The number liking at least one is $12+9-5=16$.',
  'How many in this example like neither subject?',
  '$20-16=4$. Subtract the union from the total.',
  'Adding both set totals counts the overlap twice.'),
 'Imaginary and complex numbers':g(
  'The imaginary unit satisfies $i^2=-1$. A complex number has the form $a+bi$, with real numbers $a$ and $b$. Combine real and imaginary parts separately.',
  '$(2+3i)+(4-i)=6+2i$. Also, $i^4=(i^2)^2=1$.',
  'Simplify $(1+i)(1-i)$.',
  '$1-i^2=2$, because $i^2=-1$.',
  'An imaginary coefficient is not a real number you can combine with the real part.'),
 'Geometric reasoning and proofs':g(
  'Start with the givens, state what must be proved, and justify each step using a definition, theorem or earlier established statement.',
  'Two intersecting lines make adjacent supplementary angles. Subtracting the shared adjacent angle from both straight-angle totals proves that opposite angles are equal.',
  'Does a diagram that looks symmetric prove two lengths are equal?',
  'No. You need a given equality or a valid deduction from known properties.',
  'A conclusion cannot also serve as an unproved reason for itself.'),
 'Quadrilaterals and polygons':g(
  'Classify polygons by properties rather than appearance. A parallelogram has two pairs of parallel opposite sides; a rectangle also has four right angles; a square also has four equal sides.',
  'Every square is a rectangle and a rhombus. A rectangle need not have all four sides equal.',
  'What is the sum of the interior angles of a pentagon?',
  '$(5-2)\\times180^\\circ=540^\\circ$. Draw diagonals from one vertex to divide it into three triangles.',
  'Special categories overlap. A square does not stop being a rectangle because it has another name.'),
 'Trigonometric identities':g(
  'An identity holds for every input where both sides are defined. Use known identities to rewrite one side; preserve restrictions when dividing by an expression.',
  'From $\\sin^2 x+\\cos^2 x=1$, dividing by $\\cos^2 x$ gives $\\tan^2 x+1=1/\\cos^2 x$ where $\\cos x\\ne0$.',
  'If $\\sin x=3/5$ and $x$ is acute, what is $\\cos x$?',
  '$\\cos x=4/5$, using the identity and the positive sign for an acute angle.',
  'A statement true at one chosen angle has not been proved to be an identity.'),
 'Variance, standard deviation and percentiles':g(
  'Variance measures squared spread around the mean; standard deviation returns that spread to the data’s units. A percentile describes relative position, not a percentage score.',
  'For population data $2,4,6$, the mean is $4$, the variance is $8/3$, and the standard deviation is $\\sqrt{8/3}$. A sample variance uses a different denominator.',
  'Does the 80th percentile mean answering 80% of questions correctly?',
  'No. It describes a position relative to a reference distribution. Exact percentile conventions can differ, especially at ties.',
  'Check whether a variance calculation is for a population or a sample.'),
 'Fundamental counting principle and factorials':g(
  'Multiply the number of choices at each stage when each stage count is known. For arranging distinct objects without repetition, available choices decrease at each step.',
  'Three shirts and two trousers give $3\\times2=6$ outfits. Three distinct books can be ordered in $3!=3\\times2\\times1=6$ ways.',
  'How many two-letter codes can be made from A, B and C if repetition is allowed?',
  '$3\\times3=9$. The second position still has three choices.',
  'State whether repetition is allowed and whether order matters before counting.'),
 'Enzymes and cellular metabolism':g(
  'Enzymes catalyze reactions by lowering activation energy. Metabolism includes pathways that break molecules down and pathways that build them. Enzymes do not change the overall equilibrium of a reaction.',
  'An enzyme can make a reaction reach equilibrium faster while leaving its equilibrium position unchanged.',
  'Is an enzyme used up as a reactant each time it catalyzes a reaction?',
  'No. It participates in the mechanism but is regenerated, although it can lose activity through damage or unsuitable conditions.',
  'Faster does not mean a reaction has a more favorable overall energy change.'),
 'Nutrient cycles in ecosystems':g(
  'Matter cycles between organisms and the environment. In the nitrogen cycle, fixation makes atmospheric nitrogen available in usable forms; other processes return nitrogen to the atmosphere.',
  'Plants absorb nitrogen-containing compounds from soil. Animals obtain nitrogen through food. Decomposition returns compounds to the environment.',
  'Does energy cycle through an ecosystem in the same way as nitrogen?',
  'No. Energy flows through the system and is dispersed as heat; atoms can be recycled.',
  'Plants generally cannot use atmospheric nitrogen gas directly; fixation is a key step.'),
 'Accuracy, precision and experimental uncertainty':g(
  'Accuracy means closeness to a reference value; precision means agreement between repeated measurements. Uncertainty describes the limits on a measured value.',
  'A miscalibrated balance can repeatedly report 105 g for a 100 g reference mass. The readings can be precise while inaccurate.',
  'Does adding more decimal places automatically make a measurement more accurate?',
  'No. Report only precision justified by the instrument and method; extra digits cannot remove a systematic error.',
  'Repeating a measurement can reveal random variation without detecting every calibration error.'),
 'Elements, compounds and mixtures':g(
  'An element has one type of atom. A compound has elements chemically joined in fixed proportions. A mixture combines substances physically and can have variable proportions.',
  'Copper is an element, pure water is a compound, and salt water is a mixture. Filtering alone cannot separate water into hydrogen and oxygen.',
  'Is air a compound because it contains several elements?',
  'No. Air is a mixture of gases with variable composition.',
  'A uniform appearance does not make a homogeneous mixture a pure substance.'),
 'Electron configuration and quantum numbers':g(
  'Electron configuration records how electrons occupy subshells. Quantum numbers describe an electron’s shell, subshell, orbital orientation and spin. An orbital can hold at most two electrons with opposite spins.',
  'Lithium’s ground-state configuration is $1s^2 2s^1$: two electrons in the first subshell and one in the next.',
  'How many electrons can occupy a single orbital?',
  'At most two, with opposite spin quantum numbers.',
  'An orbital is a probability-based description, not a fixed circular electron path.'),
 'Oxidation, reduction and electrochemistry':g(
  'Oxidation is electron loss; reduction is electron gain. They occur together. Oxidation occurs at the anode and reduction at the cathode in both galvanic and electrolytic cells.',
  'When zinc loses electrons and copper ions gain them, zinc is oxidized and the copper ions are reduced.',
  'Is the oxidizing agent itself oxidized or reduced?',
  'Reduced. It accepts electrons and causes another species to be oxidized.',
  'Electrode sign depends on the type of cell; anode and cathode are defined by the reactions.'),
 'Nuclear reactions':g(
  'Nuclear reactions change nuclei rather than only rearranging electron bonds. In a nuclear equation, conserve total mass number and charge number.',
  'Alpha emission reduces the parent nucleus’s mass number by four and atomic number by two. Beta-minus emission keeps mass number unchanged and raises atomic number by one.',
  'Does ordinary chemical bonding change one element into another?',
  'No. Changing the element requires changing the nucleus’s proton number.',
  'Mass number is not the same as atomic number. Balance both in a nuclear equation.'),
 'Relative motion and velocities':g(
  'A velocity is measured relative to a reference frame. In everyday collinear motion, subtract the observer’s velocity from the object’s velocity, using consistent directions and units.',
  'A bus moves east at 10 m/s and a cyclist moves east at 6 m/s. The cyclist’s velocity relative to the bus is $6-10=-4$ m/s, toward the west.',
  'If two trains move in opposite directions at 8 m/s and 12 m/s, what is their relative speed?',
  '20 m/s. Their signed velocities differ by 20 m/s.',
  'A negative velocity describes direction; it does not mean a negative speed.'),
 'Thermodynamics and heat transfer':g(
  'Heat is energy transferred because of a temperature difference. Conduction, convection and radiation transfer energy by different mechanisms. Internal-energy change depends on both heat and work.',
  'A metal spoon warms by conduction. Moving warm water transfers energy by convection. Sunlight transfers energy by radiation without requiring a material medium.',
  'Can two objects have equal temperatures but different total internal energies?',
  'Yes. Internal energy also depends on the amount and type of matter and its state.',
  'Heat, temperature and internal energy are related but different quantities.'),
 'Special relativity':g(
  'Special relativity describes inertial reference frames. The laws of physics are the same in them, and the measured speed of light in vacuum is the same for every inertial observer.',
  'A moving clock is measured to tick more slowly relative to an observer’s frame. This comparison concerns measurements of the same physical events.',
  'Should ordinary velocity addition be applied without correction to speeds near the speed of light?',
  'No. Relativistic velocity addition is required; ordinary addition is a useful low-speed approximation.',
  'Time dilation is not a claim that a person notices their own clock behaving abnormally.'),
 'Depositional landforms and bodies of water':g(
  'Deposition happens when transported sediment settles. Changes in flow speed, particle size and the setting determine where material accumulates.',
  'A river can deposit sediment as it enters quieter water, helping form a delta. A delta is not the same feature as an alluvial fan at a mountain front.',
  'Why can a stream deposit larger particles when its flow slows?',
  'The slower flow may no longer have enough transporting capacity to keep those particles moving.',
  'Weathering breaks material down, erosion transports it, and deposition leaves it in a new place.'),
 'Rock layers and relative dating':g(
  'Relative dating places events in order. In an undisturbed sedimentary sequence, lower layers are older. A feature cutting another rock must be younger than the rock it cuts.',
  'A fault cutting three layers formed after those layers. A younger layer deposited across an eroded surface may record a gap in the sequence.',
  'Does relative dating alone give an exact age in years?',
  'No. It establishes older/younger relationships; numerical ages require additional evidence.',
  'Folding, overturning and erosion can complicate the simple lower-is-older rule.'),
 'The formation of Earth':g(
  'Earth formed as material in the early solar system accumulated into larger bodies. Heating and differentiation allowed denser material to concentrate toward the core.',
  'Rocky debris joined through accretion. Early heating came from impacts, gravitational processes and radioactive decay.',
  'Did Earth form fully assembled in a single ordinary collision?',
  'No. Accretion describes growth through many encounters and collisions over time.',
  'Earth’s formation is a different event from the beginning of the universe.'),
 'Pagkumpleto ng pangungusap':g(
  'Basahin muna ang buong pangungusap at tukuyin ang kahulugang kailangan sa puwang. Suriin kung ang kapalit ay angkop sa gramatika at sa lohika ng pangungusap.',
  'Sa “Hindi siya sumuko ___ mahirap ang gawain,” ang kahit ay nagpapakita ng pagsalungat sa inaasahang resulta.',
  'Piliin ang dahil o kaya: “Malakas ang ulan, ___ nabasa ang daan.”',
  'Kaya. Bunga ng malakas na ulan ang pagkabasa ng daan.',
  'Hindi sapat na tama ang anyo ng salita kung mali ang ugnayang ipinapakita nito.'),
 'Laws of sines and cosines':g(
  'Use the sine law when a side and its opposite angle are paired. Use the cosine law for three known sides or two known sides with the included angle. Check whether the sine-law case permits two different triangles.',
  'For sides $a$ and $b$ with included angle $C$, the cosine law is $c^2=a^2+b^2-2ab\\cos C$. At a right angle it reduces to the Pythagorean theorem.',
  'Which law is the direct choice when all three side lengths are given and you need an angle?',
  'The cosine law. It relates that angle to all three known sides.',
  'The angle paired with a side must be the opposite angle; the included angle lies between the other two sides.'),
 'Galaxies and other objects in space':g(
  'Distinguish the scale and structure of a planet, star, stellar system, galaxy and the universe. A galaxy contains many stars, gas, dust and dark matter bound by gravity.',
  'Earth belongs to the solar system, which belongs to the Milky Way galaxy. The Milky Way is one galaxy among many.',
  'Is the Sun itself a galaxy?',
  'No. It is a star within the Milky Way.',
  'A constellation is an apparent sky pattern, not necessarily a gravitationally bound group of stars.'),
};
