export const slides=[
 {title:'Your GPS recalculates.\nWhy doesn’t learning?',copy:['BACKTRACK','A new route to the lesson you need now.','University of the Philippines Manila'],visual:'A route bends around a missing step and reconnects to a fixed destination.',purpose:'Make the metaphor immediately understandable.',source:'Working BACKTRACK concept; no outcome claim.',avoid:'Statistics, feature lists, or a long team introduction.'},
 {title:'“Review.”\nReview what?',copy:['TODAY’S CLASS','x² + 7x + 12 = 0','A learner can be stuck here because of a step underneath.'],visual:'Large current equation, with factoring and multiplication named underneath as possible checks.',purpose:'Show the navigation problem without reducing the education crisis to one cause.',source:'Illustrative mathematics; local need validation pending.',avoid:'Invented student quotations, national causation claims, and stock crisis numbers.'},
 {title:'The destination stays.\nThe route changes.',copy:['Current goal','Check a prerequisite','Find useful practice','Fresh return task'],visual:'Editable route diagram that inserts a prerequisite detour while retaining the goal.',purpose:'Explain the product in one visible loop.',source:'Implemented route behavior; authored dependency map.',avoid:'A dense full curriculum graph or a claim of exact diagnosis.'},
 {title:'The reward is\nless review.',copy:['Two fresh checks','One review removed','Your earlier progress stays.','Try BACKTRACK'],visual:'Before/after route drawings with one specific review stop removed, not fake minutes saved.',purpose:'Demonstrate the signature motivation mechanic and link to the product.',source:'Illustrative states from the working product; no field retention result.',avoid:'XP, fabricated saved minutes, or a made-up learner outcome.'},
 {title:'Khan is the\nlearning engine.',copy:['WATCH HERE','Official Khan lessons inside the route.','PRACTICE ON KHAN','Matched exercises in an existing learning environment.','RETURN HERE','Fresh checks reconnect the route.'],visual:'Official Khan logo and three clear stages, with practice visually central.',purpose:'Make the platform relationship concrete for the 25% integration category.',source:'Khan resources and official teacher reporting guide.',avoid:'Claiming an API relationship, automatic result sync, or endorsement.'},
 {title:'Back to today’s lesson.',copy:['FRESH DESTINATION TASK','x² + 11x + 28 = 0','x = −4 or x = −7','The route ends with something the learner can demonstrate.'],visual:'The fresh equation and worked return, with the route reconnecting.',purpose:'Show the intended capability rather than claiming a pilot outcome.',source:'Worked product example. Formal learning outcomes remain unmeasured.',avoid:'Presenting this authored example as data from a real student.'},
 {title:'Did the return last?',copy:['RETAINED REENTRY','Pass a fresh destination task after the route','Pass again 7–14 days later','Report against every enrolled baseline-blocked learner.'],visual:'Post and delayed check connected to a single clearly named outcome.',purpose:'Give judges one memorable, defensible metric.',source:'Proposed evaluation design; retrieval and spacing research informs timing.',avoid:'An invented recovery percentage or excluding missing follow-up.'},
 {title:'Five months to\nearn the evidence.',copy:['80–120 learners','2–3 cohorts','Planning targets, subject to school agreements, permissions and access.','NOV · Review + baseline','DEC–JAN · First cycle + comparison','FEB · Second educator + replication','MAR · Follow-up + handover'],visual:'A clean November–March implementation timeline.',purpose:'Separate the ambitious product from the bounded proof.',source:'Official KEIC implementation dates; proposed cohort and plan.',avoid:'Implying schools or learners are already committed.'},
 {title:'A fair comparison.',copy:['Teacher-selected Khan practice','BACKTRACK-supported Khan practice','Comparable access time and adult support.','Fresh post and delayed tasks in both groups.','Randomized delayed start where feasible. Otherwise report feasibility, not causation.'],visual:'Two parallel study conditions converging on the same assessments.',purpose:'Show that the team intends to test incremental value.',source:'Proposed design; school and evaluator approval required.',avoid:'Power claims, assumed effect sizes, or a false claim that randomization is secured.'},
 {title:'Adaptive learning\nalready exists.',copy:['ALEKS · Objectives and prerequisites','Gemini · Goal-based diagnosis and study plans','Khan · Personalization and learning infrastructure','Our opportunity: a repeatable Khan recovery routine that schools can inspect and test.'],visual:'A clear competitor acknowledgment with the proposed workflow distinguished beneath it.',purpose:'Defuse the strongest novelty objection before Q&A.',source:'ALEKS custom objectives; Google study notebooks, June 2026; Khan Learning Paths documentation.',avoid:'“We invented adaptive learning” or “AI cannot diagnose gaps.”'},
 {title:'One goal.\nA manageable routine.',copy:['Teacher confirms the destination.','Learners follow different routes.','Khan assignments provide practice.','Separate supervised tasks check the return.','Measure teacher minutes, not just learner clicks.'],visual:'One class destination branches into routes, then returns to an educator’s assessment.',purpose:'Make adoption credible and burden measurable.',source:'Proposed school workflow; sharing a topic link works in the current build.',avoid:'A fake classroom dashboard with invented participant counts.'},
 {title:'A kit another\neducator can use.',copy:['A reviewed destination map','Checks and answer rationales','Matched Khan material','Parallel return assessments','Facilitator and reporting guide','Topic links for schools, Reels and self-study.'],visual:'The reusable kit as six plainly labeled components, with the second educator as the replication test.',purpose:'Show what actually scales beyond the student team.',source:'Proposed replication model; two working topic entries.',avoid:'A national rollout map or unearned thousands-of-users claims.'},
 {title:'PHP 100,000\nimplementation scenario.',copy:['Learning review · 24,000','Access support · 18,000','Deployment · 16,000','Evaluation · 18,000','Product operations · 8,000','Teacher onboarding · 8,000','Recruitment content · 3,000','Contingency · 5,000','Planning allocation. Not quotes or secured funds. Learner access stays free.'],visual:'Readable allocation list with an explicit total and measured-cost commitment.',purpose:'Demonstrate resource choices and honest unit economics.',source:'BACKTRACK planning allocation; official champion implementation-grant amount.',avoid:'Treating the team award as grant money or inventing a school price.'},
 {title:'Keep the goal.\nChange the route.',copy:['BACKTRACK · University of the Philippines Manila','Matthew Labrador · Paul Recio · Harry Gomez','Coach: Justin Mesias','A new route to today’s lesson. A clear way to measure the return.','Try BACKTRACK'],visual:'A completed route and the product link, followed by the named team.',purpose:'Close with the product idea and a clear invitation to use it.',source:'Team names supplied by Matthew.',avoid:'A fake partner logo wall, promised victory, or unmeasured success claims.'},
 {title:'Research behind\nthe approach',copy:['Khan Academy teacher reporting','ALEKS custom objectives','Google Gemini study notebooks · June 25, 2026','IES learning practice guide','Carpenter, Pan & Butler · Spacing and retrieval','Foster · Confidence assessment','Self-Determination Theory in education'],visual:'A readable linked research inventory supporting the learning design and competitor comparison.',purpose:'Make substantive claims auditable.',source:'Exact research URLs in notes and the source links on this page.',avoid:'Organizer rules, application links, internal review notes, tiny URLs, or extra pages.'}
];
