"""Prepare edits for the existing Canva deck; this does not publish or export it."""
from pathlib import Path
import json

root=Path(__file__).resolve().parents[1]
data=json.loads((root/'.refs/canva-expanded-before.json').read_text(encoding='utf-8'))
N='#0A2A66';W='#FFFFFF';G='#14BF96'
def item(text,size=26,**kw):return dict(text=text,size=size,**kw)
def title(text):return item(text,46,x=64,y=92,w=1152,h=110,bold=True)
story={
1:[item('Studied the lesson.',52,bold=True),item('Still stuck on the next step.',52,bold=True),item('Dunlo prepares a useful session around your Khan goal, helps the difficult step click, and builds your next reviewer.',26,y=280,h=96),item('University of the Philippines Manila',18),item('Bring your\nKhan goal',26,bold=True),item('A useful study session\nwith focused help',26,bold=True),item('Come back with\na personal reviewer',26,bold=True)],
2:[title('Same task. Different next steps.'),item('x² + 7x + 12 = 0',36,x=64,y=200,w=1152,h=60,bold=True),item('3 and 4',40,y=302,bold=True),item('Check factors → solutions',25,y=382,h=66),item('When is a factor zero?',23,y=459,h=60),item('A fresh follow-up decides where help begins.',26,x=64,y=583,w=1152,h=65,bold=True),item('2 and 6',40,y=302,bold=True),item('Check product + sum',25,y=382,h=66),item('Does the pair satisfy both?',23,x=752,y=459,w=440,h=60)],
3:[title('One session makes the next one easier.'),item('1',30,color=W),item('Bring your\nKhan goal',28,bold=True),item('2',30,color=W),item('Learn or try\na useful check',28,bold=True),item('3',30),item('Practise the\nrelevant step',28,bold=True),item('4',30,color=W),item('Keep your\nnext review',28,bold=True),item('The recovery route steps in when a specific skill needs help.',27,y=563,h=80)],
4:[title('See why the step breaks.'),item('Both pairs multiply to 12. Only one also adds to 7.',28,y=192,h=65),item('(x + 2)(x + 6)',37,y=303,h=60,bold=True),item('x² + 8x + 12\n8 does not match 7.',27,y=386,h=88),item('(x + 3)(x + 4)',37,y=303,h=60,bold=True),item('x² + 7x + 12\nBoth conditions match.',27,y=386,h=88),item('Change the pair. See what changes.',26,x=380,y=611,w=520,h=58,bold=True)],
5:[title('Your study becomes your reviewer.'),item('TODAY',22,w=285,bold=True),item('Fresh checks',27,bold=True),item('Use the idea without\nthe explanation.',24,h=85),item('SAVED',22,w=285,bold=True),item('Your reviewer',27,bold=True),item('Skill, context, Khan help,\nand a next review date.',24,h=85),item('NEXT TIME',22,w=285,bold=True),item('A fresh Rematch',27,bold=True),item('New numbers.\nYour earlier work stays.',24,h=85),item('A useful stop today makes the next start easier.',27,y=579,h=70),item('Learning, practice and review share the same history.',24,x=64,y=181,w=1152,h=65,link='')],
6:[title('Your quiz, notes and next study session.'),item('YOUR QUIZ TOPICS + YOUR NOTES',23,y=233,h=48),item('10 minutes → 2 useful rounds',46,y=304,h=100,bold=True),item('One class goal. Personal help and review.',31,y=435,h=82),item('Teacher sheets show the next useful step.\nShared links carry the scope. Each learner keeps their own progress.',24,y=564,h=82)],
7:[title('A useful reel becomes useful study.'),item('1',30,color=W),item('A useful hook:\nWhy don’t 2 and 6 fit?',27,h=115,bold=True),item('2',30,color=W),item('A matching challenge:\nTry the idea yourself.',27,h=115,bold=True),item('3',30),item('A reason to return:\nKhan practice + reviewer.',27,h=115,bold=True),item('Quiz, cooking and gaming hooks.',29,y=543,h=55,bold=True),item('12 variants · 3 skills · One connected learning experience',23,y=606,h=48),item('Try challenge FQ1',18,link='https://dunlo.vercel.app/challenge?code=FQ1')],
8:[title('Try Dunlo. See the next step change.'),item('Compare two wrong answers.\nWatch the explanation and next check change.',29,y=235,w=720,h=125),item('Try Dunlo',46,color=N,bold=True,link='https://dunlo.vercel.app/demo'),item('dunlo.vercel.app/demo',24,link='https://dunlo.vercel.app/demo'),item('Scan to start',20,bold=True),item('A few sample routes to help you explore the idea.\nThe full product is still in development.',19,y=617,w=800,h=57)],
9:[title('Khan is part of every useful cycle.'),item('Start with its learning goal. Keep a saved way back.',28,y=175,h=60),item('GOAL',24,bold=True),item('Choose a supported\nKhan activity',24,h=100),item('HELP',24,bold=True),item('Use a focused clip\nor explanation',24,h=100),item('KHAN',24,bold=True),item('Practise the\nmatched exercise',24,h=100),item('CHECK',24,bold=True),item('Return to fresh\nindependent problems',24,h=100),item('REVIEW',24,bold=True),item('Keep the step for\na later session',24,h=100),item('Report: completed, still difficult, or unable to access.',24,y=583,h=50),item('Opens, self-reports, teacher-confirmed activity and fresh checks stay separate.',19,y=642,w=1110,h=35)],
10:[title('Start where learning already happens.'),item('Classroom study',34,bold=True,align='center'),item('Teacher shares the goal.\nEach learner gets a useful session.',25,h=86,align='center'),item('Independent study',34,bold=True,align='center'),item('Try one useful question.\nSave a pack and come back.',25,h=86,align='center'),item('Phone. Laptop. Shared study table.',32,color=W,bold=True,align='center'),item('Text explanations, a saved place, and optional video.',24,y=637,h=40)],
11:[title('Can they still do it next week?'),item('PROPOSED SCHOOL PILOT',21,bold=True),item('80–120 learners · 2–3 cohorts',21,bold=True),item('Khan practice',34,bold=True,align='center'),item('Khan + Dunlo',34,bold=True,align='center'),item('Teacher-selected support',25,align='center'),item('Personal session + focused recovery',25,align='center'),item('The same fresh assessments',32,x=64,w=1152,h=56,bold=True,align='center'),item('After practice, then 7–14 days later.',25,x=64,y=600,w=1152,h=43,align='center'),item('Also track useful returns, repeated Khan use and teacher effort.',20,y=651,h=32)],
12:[title('Scale the pack. Keep support personal.'),item('Fractions',30,bold=True),item('Algebra',30,bold=True),item('Graphs',30,bold=True),item('A reviewed pack carries the routine.',33,bold=True),item('Useful checks + Khan activities + a personal reviewer',26,h=62),item('Another educator can run the same connected routine.',27,y=563,h=65),item('For a class, a shared challenge, or the next topic a learner needs.',22,y=632,h=39)],
13:[title('Free learning. A plan for continuity.'),item('PHP 100,000',42,bold=True),item('60%',76,bold=True),item('Learning review,\naccess and evaluation',31,y=442,h=111),item('Institutions support access, training and upkeep.',23,y=597,w=520,h=66),item('Implementation planning scenario',17,link='')],
14:[item('A useful session today.\nA clearer next step tomorrow.',50,y=128,h=153,bold=True),item('University of the Philippines Manila\nInstitutional endorsement confirmed',22,y=509,h=62),item('Matthew Labrador · Paul Recio · Harry Gomez',23,y=580,h=43),item('Coach: Justin Mesias',21,y=635,h=34)],
15:[title('The work behind the idea.'),item('Integration · Khan teacher reports',22),item('Precedent · ALEKS objectives',22),item('Context · Khan’s Philippine rollout',22,link='https://www.deped.gov.ph/2026/01/26/deped-kinilala-ang-papel-ng-khan-academy-ph-sa-suporta-sa-2700-paaralan-para-sa-learning-recovery-digital-innovation/'),item('Learning · IES practice guide',22),item('Learning · Spacing and retrieval',22),item('Content · Khan use and attribution',22,link='https://support.khanacademy.org/hc/en-us/articles/202262954-Can-I-use-Khan-Academy-s-videos-name-materials-links-in-my-project'),item('Dunlo keeps the next step within reach.',30,x=64,y=608,w=1152,h=60,bold=True,link='')]
}
ops=[{'type':'update_title','title':'Dunlo - Competition pitch'}]
for page,entries in story.items():
    texts=[r for r in data['richtexts'] if r['page_index']==page and r['containerElement']['type']=='TEXT' and r['regions']]
    numbered=[r for r in texts if ''.join(s.get('text','') for s in r['regions']).isdigit() and len(''.join(s.get('text','') for s in r['regions']))==2]
    content=[r for r in texts if r not in numbered]
    assert len(content)==len(entries),(page,len(content),len(entries))
    for number in numbered:ops.append({'type':'replace_text','element_id':number['element_id'],'text':f'{page:02d}'})
    for old,new in zip(content,entries):
        eid=old['element_id'];pos=old['containerElement']['position'];dim=old['containerElement']['dimension']
        ops.append({'type':'replace_text','element_id':eid,'text':new['text']})
        fmt={'font_size':new['size'],'color':new.get('color',N),'font_style':'normal','font_weight':'bold' if new.get('bold') else 'normal'}
        if 'align' in new:fmt['text_align']=new['align']
        if 'link' in new:fmt['link']=new['link']
        ops.append({'type':'format_text','element_id':eid,'formatting':fmt})
        if 'x' in new or 'y' in new:ops.append({'type':'position_element','element_id':eid,'left':new.get('x',pos['left']),'top':new.get('y',pos['top'])})
        if 'w' in new or 'h' in new:ops.append({'type':'resize_element','element_id':eid,'width':new.get('w',dim['width']),'preserve_aspect_ratio':False})
(root/'.refs/canva-expanded-operations.json').write_text(json.dumps(ops,ensure_ascii=False,indent=2),encoding='utf-8')
(root/'.refs/expanded-deck-story.json').write_text(json.dumps(story,ensure_ascii=False,indent=2),encoding='utf-8')
print(f'Staged {len(ops)} operations for the existing {len(story)} pages; not yet committed.')
