import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {spawn} from 'node:child_process';
import {validStudy} from '../src/lib/study.ts';
const origin='http://127.0.0.1:3059',dir='.refs/explore-release';await fs.mkdir(dir,{recursive:true});
const server=spawn(process.execPath,['scripts/serve-static.mjs'],{env:{...process.env,BACKTRACK_PORT:'3059'},windowsHide:true,stdio:'pipe'});
await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.once('exit',code=>reject(Error('Server exited '+code)));});
const browser=await chromium.launch({channel:'chrome',headless:true}),results=[];
async function scenario(name,run,options={}){const context=await browser.newContext({viewport:{width:1440,height:1000},...options}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));try{await run(page,context);assert.deepEqual(errors,[]);results.push({name,passed:true});console.log('PASS '+name);}catch(e){results.push({name,passed:false,error:e.message});console.log('FAIL '+name+': '+e.message);await page.screenshot({path:`${dir}/${name.replace(/\W/g,'-')}-failure.png`,fullPage:true});}finally{await context.close();}}
const state=page=>page.evaluate(()=>JSON.parse(localStorage.getItem('backtrack.study.v1')||'null'));
const overflow=async page=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal overflow');
try{
 await scenario('direct entry and clear navigation',async page=>{await page.goto(origin);await page.getByRole('heading',{name:'Follow your curiosity.'}).waitFor();await page.getByRole('button',{name:'Explore on my own',exact:true}).click();assert.equal(await page.getByRole('dialog').count(),0);await page.getByRole('link',{name:'Explore ideas ↓',exact:true}).click();await page.locator('#idea-same-mix').waitFor();assert.equal(await page.locator('[data-idea]').count(),10);await overflow(page);await page.screenshot({path:`${dir}/explore-desktop.png`,fullPage:false});});
 await scenario('saved ideas controls and exploration survive reload without scores',async page=>{await page.goto(origin+'/explore?item=same-amount');const card=page.locator('#idea-same-amount');await card.getByRole('slider').fill('3');await card.getByRole('button',{name:'Save More pieces. More chocolate?',exact:true}).click();await card.getByRole('button',{name:'No, the amount stays the same',exact:false}).click();await page.reload();await card.getByRole('slider').waitFor();assert.equal(await card.getByRole('slider').inputValue(),'3');assert.equal(await card.getByRole('button',{name:'Unsave More pieces. More chocolate?',exact:true}).getAttribute('aria-pressed'),'true');const s=await state(page);assert.equal(validStudy(s),true);assert.equal(s.xp,0);assert.deepEqual(s.review,{});await card.locator('.idea-visual').screenshot({path:`${dir}/fraction-thirds.png`});await page.getByRole('group',{name:'Explore topics'}).getByRole('button',{name:'Saved',exact:false}).click();assert.equal(await page.locator('[data-idea]').count(),1);await overflow(page);});
 await scenario('Khan video is opt in and closes offscreen',async(page,context)=>{let requests=0;await context.route(/youtube|ytimg|googlevideo/,route=>{requests++;return route.abort();});await page.goto(origin+'/explore?item=khan-open-brackets');const card=page.locator('#idea-khan-open-brackets');await card.waitFor();assert.equal(requests,0);assert.equal(await page.locator('iframe').count(),0);await card.getByRole('button',{name:/Play Khan Academy explanation/}).click();await card.locator('iframe').waitFor();const src=await card.locator('iframe').getAttribute('src');assert.match(src,/start=51/);assert.match(src,/end=139/);await page.getByRole('group',{name:'Explore topics'}).getByRole('button',{name:'Everyday numbers',exact:true}).click();assert.equal(await page.locator('iframe').count(),0);assert.ok(requests>0);assert.equal((await state(page)).xp,0);});
 await scenario('Khan practice returns to the same idea',async(page,context)=>{await context.route('https://www.khanacademy.org/**',r=>r.fulfill({status:200,body:'Test external destination'}));await page.goto(origin+'/explore?item=same-mix');const card=page.locator('#idea-same-mix');await card.getByRole('link',{name:'Practise on Khan ↗',exact:true}).click();await card.getByRole('heading',{name:'How did Khan practice go?'}).waitFor();await page.reload();await card.getByRole('button',{name:'I completed it',exact:true}).click();const s=await state(page);assert.equal(s.pendingKhan.returnPath,'/explore?item=same-mix');assert.equal(validStudy(s),true);assert.equal(s.xp,0);assert.equal(Object.values(s.review)[0].streak,0);await card.getByRole('button',{name:'Try a fresh check ↗',exact:true}).click();await page.locator('.question-stage').waitFor();assert.equal((await state(page)).activeSession.tasks[0].skill,'unit_rate');});
 await scenario('shared idea and fresh assessment retain the learning goal',async page=>{await page.goto(origin+'/explore?item=khan-factor-pairs');const card=page.locator('#idea-khan-factor-pairs');await card.getByRole('button',{name:'Show me why',exact:false}).click();await card.getByRole('button',{name:'Try a fresh question →',exact:true}).click();await page.locator('.question-stage').waitFor();const s=await state(page);assert.equal(s.activeSession.tasks[0].skill,'factor');assert.ok(s.pairs.quadratics.includes('3,4'));assert.equal(s.xp,0);assert.equal(validStudy(s),true);});
 await scenario('phone touch controls and all concepts fit',async page=>{await page.goto(origin+'/explore?item=every-term');for(const id of ['same-mix','same-amount','every-term','four-pieces','find-the-zero','read-the-graph','khan-factor-pairs']){await page.goto(origin+'/explore?item='+id);const card=page.locator('#idea-'+id);await card.waitFor();await card.scrollIntoViewIfNeeded();await overflow(page);assert.ok(await card.getByRole('link',{name:'Practise on Khan ↗',exact:true}).isVisible());if(id==='every-term'){await card.getByRole('button',{name:'Open and regroup',exact:true}).click();await card.locator('.idea-visual').screenshot({path:`${dir}/distribution-regrouped.png`});}if(id==='four-pieces'){await card.locator('.idea-visual').screenshot({path:`${dir}/factor-assembled.png`});await card.getByRole('button',{name:'Separate the four pieces',exact:true}).click();await card.locator('.idea-visual').screenshot({path:`${dir}/factor-separated.png`});}if(id==='khan-factor-pairs')await card.locator('.idea-visual').screenshot({path:`${dir}/khan-clip.png`});}await page.goto(origin+'/explore?item=same-mix');await page.locator('#idea-same-mix').waitFor();await page.screenshot({path:`${dir}/explore-phone.png`,fullPage:false});},{viewport:{width:390,height:844},hasTouch:true,isMobile:true});
 await scenario('keyboard and reduced motion retain full access',async page=>{await page.goto(origin+'/explore?item=read-the-graph');const card=page.locator('#idea-read-the-graph'),slider=card.getByRole('slider');await slider.focus();await slider.press('ArrowRight');assert.equal(await slider.inputValue(),'1');await card.getByRole('button',{name:'12 litres',exact:false}).click();await card.getByText('That’s the relationship.',{exact:true}).waitFor();await overflow(page);await card.locator('.idea-visual').screenshot({path:`${dir}/graph.png`});assert.equal(await page.getByRole('button',{name:'Still view',exact:true}).isDisabled(),true);},{viewport:{width:640,height:900},reducedMotion:'reduce'});
 await scenario('Explore tutorial covers the journey and restores the chosen topic',async page=>{await page.goto(origin+'/explore');await page.getByRole('group',{name:'Explore topics'}).getByRole('button',{name:'Algebra',exact:true}).click();await page.getByRole('button',{name:'Quick tour',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('heading',{name:'Find an idea that interests you'}).waitFor();for(let i=0;i<5;i++){await page.locator('.tour-spotlight').waitFor();await dialog.getByRole('button',{name:'Next',exact:true}).click();}await dialog.getByRole('heading',{name:'Give the idea another look'}).waitFor();await dialog.getByRole('button',{name:'Done',exact:true}).click();assert.equal(await page.getByRole('dialog').count(),0);assert.equal(await page.getByRole('group',{name:'Explore topics'}).getByRole('button',{name:'Algebra',exact:true}).getAttribute('aria-pressed'),'true');assert.equal((await state(page)).xp,0);await page.getByRole('button',{name:'Quick tour',exact:true}).click();await dialog.waitFor();await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);await overflow(page);},{viewport:{width:390,height:844},hasTouch:true});
 await scenario('invalid link and empty saved view have useful exits',async page=>{await page.goto(origin+'/explore?item=missing');await page.getByText('That idea is not in this collection. Here is a place to start.').waitFor();await page.getByRole('group',{name:'Explore topics'}).getByRole('button',{name:'Saved',exact:true}).click();await page.getByRole('heading',{name:'Keep an idea for later.'}).waitFor();await page.getByRole('button',{name:'Explore the collection',exact:true}).click();assert.equal(await page.locator('[data-idea]').count(),10);});
}finally{await browser.close();server.kill();await fs.writeFile(`${dir}/results.json`,JSON.stringify(results,null,2));}
if(results.some(x=>!x.passed))process.exitCode=1;
